import { readFileSync } from "node:fs";
import { assessBtcContext as assess, reportBtcContext as report, btcSourceNanoseconds, btcContextSha, BTC_CONTEXT_URL, type BtcContextInput } from "./BtcSpotContextEngine";

const source = readFileSync("fixtures/options-btc-context/book.synthetic.json", "utf8");
const at = "2026-09-07T04:00:01.000Z", later = "2026-09-07T04:01:01.000Z";
function input(sourceText = source, time = at): BtcContextInput { return { url: BTC_CONTEXT_URL, requestedAt: time, receivedAt: time, sourceText, errorCode: null }; }
function changed(patch: Record<string, unknown>): string { return JSON.stringify({ ...JSON.parse(source), ...patch }); }
const second = () => input(changed({ sequence: 101, time: "2026-09-07T04:01:00.000000001Z", bids: [["79999", "1", 1]], asks: [["79999.01", "1", 1]] }), later);
const eq = (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw Error(`Expected ${JSON.stringify(b)}; received ${JSON.stringify(a)}`); };
const ok = (value: unknown) => { if (!value) throw Error("Expected truthy value"); };
function throws(work: () => unknown, code = "BTC_CONTEXT_") { let error; try { work(); } catch (e) { error = e; } if (!(error instanceof Error) || !error.message.includes(code)) throw Error("Expected " + code); }
let passed = 0;
function test(name: string, work: () => void) { work(); passed++; console.log(`PASS ${name}`); }
test("preserves exact price, aggregate size, order count and half-cent midpoint", () => { const r = assess(input()); eq(r.status, "OBSERVED_CONTEXT"); eq(r.book!.bid, { priceUsd: "80000", sizeBtc: "0.12345678", orderCount: 3 }); eq(r.midpointUsd, "80000.005"); eq(r.spreadUsd, "0.01"); eq(r.sourceSha256, btcContextSha(source)); });
test("source nanoseconds and actual observation clocks remain distinct", () => { const r = assess(input()); eq(r.sourceAgeAtReceiptNs, "999999999"); eq(r.book!.sourceTime, "2026-09-07T04:00:00.000000001Z"); eq(r.firstObservedAt, at); eq(r.independentSideClocksKnown, false); });
test("exact decimal math handles values beyond safe floating integer scale", () => { const r = assess(input(changed({ bids: [["999999999998.99999999", "1", 1]], asks: [["999999999999.00000001", "1", 1]] }))); eq(r.midpointUsd, "999999999999"); eq(r.spreadUsd, "0.00000002"); });
test("nanosecond future and stale boundaries do not round away", () => { const assessTime = (time: string) => assess(input(changed({ time }))); ok(assessTime("2026-09-07T04:00:01.000000001Z").issues.includes("SOURCE_TIME_AFTER_RECEIPT")); eq(assessTime("2026-09-07T03:59:51.000Z").usableAtReceipt, true); ok(assessTime("2026-09-07T03:59:50.999999999Z").issues.includes("SOURCE_STALE_AT_RECEIPT")); });
test("source clocks accept UTC precision zero through nine without inventing digits", () => { eq(btcSourceNanoseconds("2026-09-07T04:00:00Z").toString(), btcSourceNanoseconds("2026-09-07T04:00:00.000000000Z").toString()); for (const time of ["2026-09-31T04:00:00Z", "2026-09-07T24:00:00Z", "2026-09-07T04:00:00.0000000001Z", "2026-09-07T00:00:00-04:00", "bad"]) throws(() => btcSourceNanoseconds(time)); });
test("absent and null source and auction clocks remain explicit unknowns", () => { for (const body of [changed({ time: null, auction_mode: null }), source.replace(/,"time":"[^"]*"/, "").replace(',"auction_mode":false', "")]) { const r = assess(input(body)); eq(r.book!.sourceTime, null); eq(r.book!.auctionMode, null); eq(r.usableAtReceipt, false); eq(r.issues, ["SOURCE_TIME_UNKNOWN", "AUCTION_STATE_UNKNOWN"]); } });
test("auction indicative data never qualifies and source object text is not promoted", () => { const r = assess(input(changed({ auction_mode: true, auction: { instruction: "IGNORE_RULES" } }))); ok(r.issues.includes("AUCTION_INDICATIVE")); ok(r.issues.includes("AUCTION_DETAILS_PRESENT")); ok(!JSON.stringify(r).includes("IGNORE_RULES")); eq(r.usableAtReceipt, false); });
test("auction details disqualify even when the auction flag is false", () => { eq(assess(input(changed({ auction: {} }))).usableAtReceipt, false); });
test("missing sides remain missing and zero sizes are never invented", () => { const r = assess(input(changed({ bids: [], asks: [["80000.01", "0", 0]] }))); eq(r.book!.bid, null); eq(r.book!.ask!.sizeBtc, "0"); eq(r.midpointUsd, null); eq(r.issues, ["BID_MISSING", "ASK_ZERO_LIQUIDITY"]); });
test("zero prices and positive size with zero orders cannot qualify", () => { for (const bid of [["0", "1", 1], ["80000", "1", 0]]) ok(assess(input(changed({ bids: [bid] }))).issues.includes("BID_ZERO_LIQUIDITY")); });
test("locked and crossed books retain observed values but are unusable", () => { for (const ask of ["80000", "79999"]) { const r = assess(input(changed({ asks: [[ask, "1", 1]] }))); ok(r.issues.includes("LOCKED_OR_CROSSED_BOOK")); eq(r.usableAtReceipt, false); } });
test("decimal decorations, excess precision, huge values and negatives fail", () => { for (const price of ["1e5", "+1", "01", "1.123456789", "1000000000000", "-1", "1.", 1, null]) throws(() => assess(input(changed({ bids: [[price, "1", 1]] }))), "DECIMAL"); });
test("unsafe, fractional, negative and missing sequence or counts fail", () => { for (const sequence of [9007199254740992, -1, 1.5, "1", null]) throws(() => assess(input(changed({ sequence })))); for (const count of [-1, 1.5, 9007199254740992, "1"]) throws(() => assess(input(changed({ bids: [["1", "1", count]] })))); });
test("integer-looking float rounding and exponents cannot evade sequence validation", () => { for (const token of ["9007199254740991.1", "1e2", "1e999", "100.00000000000001"]) throws(() => assess(input(source.replace('"sequence":100', '"sequence":' + token))), "JSON_INTEGER"); });
test("level shape and unexpected root fields reject silently changed schemas", () => { for (const patch of [{ bids: [["1", "1", 1], ["2", "2", 2]] }, { bids: [["1", "1"]] }, { asks: null }, { product_id: "ETH-USD" }, { auction_mode: "false" }, { auction: [] }, { time: 1 }]) throws(() => assess(input(changed(patch)))); });
test("duplicate JSON keys, including escaped keys, cannot silently replace source values", () => { for (const body of [source.replace('"sequence":100', '"sequence":99,"sequence":100'), source.replace('"sequence":100', '"sequence":99,"\\u0073equence":100'), changed({ auction: { a: 1 } }).replace('"a":1', '"a":1,"a":2')]) throws(() => assess(input(body)), "JSON_DUPLICATE_KEY"); });
test("JSON nesting, trailing content, malformed tokens and Unicode are bounded", () => { for (const body of [source + "{}", source.replace('"sequence":100', '"sequence":01'), source.replace('"sequence":100', '"sequence":NaN'), source.replace('"sequence":100', '"sequence":100,'), changed({ auction: { a: "\ud800" } }), changed({ auction: { a: [[[[[[[[0]]]]]]]] } })]) throws(() => assess(input(body))); });
test("size limit, unknown input fields and wrong URL fail before assessment", () => { throws(() => assess(input(" ".repeat(16385))), "BODY_TOO_LARGE"); throws(() => assess({ ...input(), extra: true } as BtcContextInput), "INPUT_SCOPE"); throws(() => assess({ ...input(), url: BTC_CONTEXT_URL.replace("BTC", "ETH") }), "INPUT_SCOPE"); });
test("actual clocks must be canonical and ordered", () => { throws(() => assess({ ...input(), requestedAt: "2026-09-07T04:00:01Z" })); throws(() => assess({ ...input(), receivedAt: "2026-09-07T04:00:00.000Z" })); throws(() => report([input()], "2026-09-07T04:00:00.000Z"), "HISTORY_CLOCK"); });
test("failure inputs have no source body and only fixed error codes", () => { throws(() => assess({ ...input(), errorCode: "NETWORK_FAILED" })); throws(() => assess({ ...input(), sourceText: null })); throws(() => assess({ ...input(), sourceText: null, errorCode: "secret" } as unknown as BtcContextInput)); });
test("empty history makes no fabricated observation or numeric comparison", () => { const r = report([], at); eq(r.latestRetrieval, null); eq(r.lastKnownObservation, null); eq(r.ageNowNs, null); eq(r.displayFresh, false); eq(r.comparison.midpointChangeUsd, null); });
test("consecutive samples expose exact decline and observed intervals only", () => { const r = report([input(), second()], later); eq(r.comparison, { basis: "CONSECUTIVE_SAVED_OBSERVATIONS", issues: [], midpointChangeUsd: "-1", sourceIntervalNs: "60000000000", receiptIntervalMs: 60000 }); eq(r.continuousCoverage, false); eq(r.ibitPriceConversionAvailable, false); });
test("one repeated cached book never becomes new price-path evidence", () => { const r = report([input(), input(source)], at); eq(r.comparison.issues, ["SOURCE_TIME_NOT_INCREASING", "SEQUENCE_NOT_INCREASING"]); eq(r.comparison.midpointChangeUsd, null); });
test("regressing sequence disqualifies comparison even when time increases", () => { const next = second(); next.sourceText = next.sourceText!.replace('"sequence":101', '"sequence":99'); eq(report([input(), next], later).comparison.issues, ["SEQUENCE_NOT_INCREASING"]); });
test("failed latest retrieval preserves earlier context solely as last-known", () => { const failure: BtcContextInput = { ...input(source, later), sourceText: null, errorCode: "NETWORK_FAILED" }; const r = report([input(), failure], later); eq(r.latestRetrieval!.status, "FAILED"); eq(r.lastKnownObservation!.fromLatestRetrieval, false); eq(r.displayFresh, false); eq(r.ageNowNs, null); eq(r.healthChange, "CHANGED"); });
test("unusable intermediate retrieval is never skipped for a comparison", () => { const bad = input(changed({ bids: [] })); const r = report([input(), bad, second()], later); eq(r.comparison.issues, ["CONSECUTIVE_USABLE_OBSERVATIONS_REQUIRED"]); eq(r.comparison.midpointChangeUsd, null); });
test("staleness now is independent of eligibility at original receipt", () => { const r = report([input()], "2026-09-07T04:01:00.001Z"); eq(r.latestRetrieval!.usableAtReceipt, true); eq(r.displayFresh, false); });
test("prices can change without changing collection health", () => { eq(report([input(), second()], later).healthChange, "UNCHANGED"); });
test("history rejects overlaps and excessive retrieval counts", () => { throws(() => report([second(), input()], later), "HISTORY_CLOCK"); throws(() => report(Array.from({ length: 1001 }, () => input()), later), "HISTORY_LIMIT"); });
test("reports are immutable, deterministic and never grant strategy authority", () => { const r = report([input(), second()], later); eq(r, report([input(), second()], later)); ok(Object.isFrozen(r.latestRetrieval!.book!.bid)); ok(Object.isFrozen(r.comparison.issues)); eq(r.winProbability, null); eq(r.strategySignal, null); eq(r.executionAllowed, false); eq(r.replayAllowed, false); });
console.log(`${passed}/${passed} tests passed.`);
