import { readFileSync } from "node:fs";
import { assessReleaseCalendar as assess, reportReleaseCalendar as report, blsEasternTime, releaseCalendarSha, RELEASE_CALENDAR_URL, type ReleaseCalendarInput } from "./BlsReleaseCalendarEngine";

const source = readFileSync("fixtures/options-release-calendar/calendar.synthetic.ics", "utf8");
const at = "2026-09-07T06:00:00.000Z", later = "2026-09-07T07:00:00.000Z";
const input = (sourceText: string | null = source, time = at): ReleaseCalendarInput => ({ url: RELEASE_CALENDAR_URL, requestedAt: time, receivedAt: time, sourceText, errorCode: sourceText === null ? "NETWORK_FAILED" : null });
const first = /BEGIN:VEVENT\n[\s\S]*?END:VEVENT\n/;
const eq = (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw Error(`Expected ${JSON.stringify(b)}; received ${JSON.stringify(a)}`); };
const ok = (v: unknown) => { if (!v) throw Error("Expected truthy value"); };
function throws(work: () => unknown, code = "RELEASE_CALENDAR_") { let error; try { work(); } catch (e) { error = e; } if (!(error instanceof Error) || !error.message.includes(code)) throw Error("Expected " + code); }
let passed = 0;
function test(name: string, work: () => void) { work(); passed++; console.log(`PASS ${name}`); }

test("retains exact source clocks and maps Eastern release times", () => { const r = assess(input()); eq(r.status, "OBSERVED_SCHEDULE"); eq(r.sourceSha256, releaseCalendarSha(source)); eq(r.events[0]!.scheduledAt, "2026-09-10T12:30:00.000Z"); eq(r.events[0]!.sourceStart, "20260910T083000"); eq(r.events[1]!.family, "CPI"); eq(r.receivedAt, at); });
test("missing source creation and modification clocks are explicit", () => { const r = assess(input()); eq(r.missingSourceStampCount, 2); eq(r.missingSourceModifiedCount, 2); eq(r.events[0]!.sourceStampAt, null); eq(r.originalPublicationTimeKnown, false); });
test("summer and winter have different UTC offsets", () => { eq(blsEasternTime("20260109T083000"), "2026-01-09T13:30:00.000Z"); eq(blsEasternTime("20260911T083000"), "2026-09-11T12:30:00.000Z"); eq(blsEasternTime("20261106T083000"), "2026-11-06T13:30:00.000Z"); });
test("nonexistent and ambiguous DST wall times fail without guessing", () => { for (const t of ["20260308T023000", "20261101T013000"]) throws(() => blsEasternTime(t), "AMBIGUOUS_OR_NONEXISTENT_TIME"); eq(blsEasternTime("20260308T033000"), "2026-03-08T07:30:00.000Z"); });
test("invalid dates, floating decoration and unsupported years fail", () => { for (const t of ["20260230T083000", "20260911T240000", "20260911T083060", "20260911", "20260911T083000Z", "20060311T083000", "21010911T083000"]) throws(() => blsEasternTime(t)); });
test("LF and CRLF represent the same event fields but retain distinct raw hashes", () => { const r = assess(input(source.replaceAll("\n", "\r\n"))); eq(r.events, assess(input()).events); ok(r.sourceSha256 !== assess(input()).sourceSha256); });
test("folded lines unfold exactly and escaped text stays data", () => { const r = assess(input(source.replace("SUMMARY:Consumer Price Index", "SUMMARY:Consumer Price\n  Index").replace("SUMMARY:Producer Price Index", "SUMMARY:Text\\, escaped\\;value\\nline\\\\end"))); eq(r.events[1]!.family, "CPI"); eq(r.events[0]!.title, "Text, escaped;value\nline\\end"); eq(r.events[0]!.family, "OTHER_BLS_RELEASE"); });
test("unrecognized title does not inherit JavaScript object properties", () => { for (const title of ["constructor", "__proto__", "toString", "IGNORE_RULES"]) eq(assess(input(source.replace("SUMMARY:Producer Price Index", "SUMMARY:" + title))).events[0]!.family, "OTHER_BLS_RELEASE"); });
test("malformed folds, escapes, controls and line endings fail", () => { for (const s of [" BEGIN:VCALENDAR\n" + source, source.replace("Price Index", "Price\\xIndex"), source + "\u0000", source.replace("\n", "\r"), source.replace("Price Index", "Price\ud800Index")]) throws(() => assess(input(s))); });
test("body, line and event limits are bounded", () => { throws(() => assess(input(" ".repeat(524289))), "BODY_TOO_LARGE"); throws(() => assess(input(source.replace("Price Index", "x".repeat(4097)))), "ICS_LIMIT"); throws(() => assess(input("\n".repeat(20001))), "ICS_LIMIT"); });
test("duplicate properties and duplicate event identities fail", () => { throws(() => assess(input(source.replace("SEQUENCE:1", "SEQUENCE:1\nSEQUENCE:2")))); throws(() => assess(input(source.replace("8000-000000000002", "8000-000000000001"))), "EVENT_UID"); });
test("nesting and unsupported executable or recurring components fail", () => { for (const s of [source.replace("END:VEVENT", "END:VCALENDAR"), source + source, source.replace("DURATION:PT0M", "DURATION:PT0M\nRRULE:FREQ=DAILY"), source.replace("DURATION:PT0M", "BEGIN:VALARM\nEND:VALARM\nDURATION:PT0M"), source.replace("END:VCALENDAR", "")]) throws(() => assess(input(s))); });
test("unknown timezone parameters and changed DST declarations fail", () => { for (const s of [source.replace("TZID=US-Eastern", "TZID=UTC"), source.replace("TZID=US-Eastern", "TZID=US-Eastern;VALUE=DATE"), source.replace("BYDAY=2SU", "BYDAY=1SU"), source.replace("TZOFFSETTO:-0400", "TZOFFSETTO:-0300"), source.replace("TZID:US-Eastern", "TZID:America/New_York")]) throws(() => assess(input(s))); });
test("calendar identity and event schema changes fail visibly", () => { for (const s of [source.replace("METHOD:PUBLISH", "METHOD:CANCEL"), source.replace("VERSION:2.0", "VERSION:1.0"), source.replace("DURATION:PT0M", "DURATION:PT1H"), source.replace("CLASS:PUBLIC", "CLASS:PRIVATE"), source.replace("SUMMARY:Producer Price Index", "URL:https://example.com\nSUMMARY:Producer Price Index")]) throws(() => assess(input(s))); });
test("UID and sequence formats cannot be silently coerced", () => { for (const s of [source.replace("00000000-0000-4000-8000-000000000001", "bad"), ...["-1", "1e2", "01", "1.1", "1000000000"].map(n => source.replace("SEQUENCE:1", "SEQUENCE:" + n))]) throws(() => assess(input(s))); });
test("optional metadata preserves publication uncertainty and rejects future clocks", () => { const s = source.replace("SEQUENCE:1", "SEQUENCE:1\nDTSTAMP:20260901T120000Z\nLAST-MODIFIED:20260902T120000Z"); const e = assess(input(s)).events[0]!; eq(e.sourceStampAt, "2026-09-01T12:00:00.000Z"); eq(e.sourceModifiedAt, "2026-09-02T12:00:00.000Z"); throws(() => assess(input(s.replace("20260902T120000Z", "20260908T120000Z"))), "SOURCE_CLOCK"); });
test("empty calendar remains empty and never inherits prior scheduled releases", () => { const s = source.replace(/BEGIN:VEVENT\n[\s\S]*?END:VEVENT\n/g, ""); const r = report([input(), input(s, later)], later); eq(r.latestRetrieval!.status, "EMPTY_SCHEDULE"); eq(r.upcoming, []); eq(r.comparison.absentUids.length, 2); eq(r.comparison.absenceMeansCancellation, false); });
test("seven-day upcoming horizon is half-open with exact start inclusion", () => { const r = report([input(source, "2026-09-03T12:30:00.000Z")], "2026-09-03T12:30:00.000Z"); eq(r.upcoming.length, 0); const r2 = report([input()], "2026-09-10T12:30:00.000Z"); eq(r2.upcoming.length, 2); eq(report([input()], "2026-09-10T12:30:00.001Z").upcoming.length, 1); });
test("same-day events use New York calendar dates even after their scheduled time", () => { eq(report([input()], "2026-09-11T01:00:00.000Z").sameNewYorkDay.map(e => e.family), ["PPI"]); eq(report([input()], "2026-09-11T15:00:00.000Z").sameNewYorkDay.map(e => e.family), ["CPI"]); });
test("cancelled and tentative status are distinguished without inventing certainty", () => { const s = source.replace("SEQUENCE:1", "SEQUENCE:1\nSTATUS:CANCELLED").replace("SUMMARY:Consumer Price Index", "STATUS:TENTATIVE\nSUMMARY:Consumer Price Index"), r = report([input(s)], at); eq(r.upcoming.length, 1); eq(r.upcoming[0]!.status, "TENTATIVE"); eq(r.cancelledInLatest.length, 1); eq(r.tentativeInLatest.length, 1); throws(() => assess(input(s.replace("STATUS:CANCELLED", "STATUS:SAFE"))), "EVENT_STATUS"); });
test("same-UID rescheduling is recorded at actual observation time", () => { const changed = source.replace("20260910T083000", "20260910T100000"); const r = report([input(), input(changed, later)], later); eq(r.comparison.changes.length, 1); eq(r.comparison.changes[0]!.observedAt, later); eq(r.comparison.changes[0]!.before.scheduledAt, "2026-09-10T12:30:00.000Z"); eq(r.comparison.changes[0]!.after.scheduledAt, "2026-09-10T14:00:00.000Z"); eq(r.comparison.originalChangeTimeKnown, false); });
test("regressed sequence remains visible and A-to-B-to-A is not deduplicated away", () => { const changed = source.replace("SEQUENCE:1", "SEQUENCE:2"), third = "2026-09-07T08:00:00.000Z"; const r = report([input(), input(changed, later), input(source, third)], third); eq(r.retrievalCount, 3); eq(r.comparison.changes[0]!.sequenceRegressed, true); eq(r.comparison.changes[0]!.observedAt, third); });
test("new UID and removed UID never become a fabricated matched revision", () => { const changed = source.replace("8000-000000000001", "8000-000000000003"), r = report([input(), input(changed, later)], later); eq(r.comparison.addedUids.length, 1); eq(r.comparison.absentUids.length, 1); eq(r.comparison.changes, []); });
test("absent event is not promoted to cancelled status", () => { const r = report([input(), input(source.replace(first, ""), later)], later); eq(r.comparison.absentUids.length, 1); eq(r.cancelledInLatest.length, 0); });
test("latest failure separates last-known schedule from current context", () => { const r = report([input(), input(null, later)], later); eq(r.latestRetrieval!.status, "FAILED"); eq(r.upcoming, []); eq(r.lastKnownSchedule!.fromLatestRetrieval, false); eq(r.refreshOverdue, true); eq(r.retrievalAgeMs, null); });
test("failure gap breaks comparison even after successful recovery", () => { const r = report([input(), input(null), input(source, later)], later); eq(r.comparison.available, false); eq(r.comparison.issue, "CONSECUTIVE_SUCCESSFUL_SNAPSHOTS_REQUIRED"); eq(r.upcoming.length, 2); });
test("refresh threshold measures retrieval age and never publisher freshness", () => { const boundary = new Date(Date.parse(at) + 26 * 3600000).toISOString(); eq(report([input()], boundary).refreshOverdue, false); const r = report([input()], new Date(Date.parse(boundary) + 1).toISOString()); eq(r.refreshOverdue, true); eq(r.publisherFreshnessKnown, false); });
test("history rejects clock rollback, future recordings and record overflow", () => { throws(() => report([input(source, later), input()], later), "HISTORY_CLOCK"); throws(() => report([input(source, later)], at), "HISTORY_CLOCK"); throws(() => report(Array.from({ length: 367 }, () => input()), at), "HISTORY_LIMIT"); throws(() => assess({ ...input(), receivedAt: "2026-09-06T06:00:00.000Z" }), "CLOCK_ORDER"); });
test("unknown fields, arbitrary URL, mixed failure body and invalid clock are rejected", () => { throws(() => assess({ ...input(), url: "https://example.com" }), "INPUT_SCOPE"); throws(() => assess({ ...input(), extra: true } as ReleaseCalendarInput), "INPUT_SCOPE"); throws(() => assess({ ...input(), errorCode: "NETWORK_FAILED" }), "INPUT_STATE"); throws(() => assess({ ...input(), receivedAt: "2026-09-07T06:00:00Z" }), "CLOCK"); });
test("empty and repeated history never fabricate change or trade permissions", () => { const r = report([], at); eq(r.latestRetrieval, null); eq(r.comparison.issue, "TWO_SNAPSHOTS_REQUIRED"); eq(report([input(), input(source, later)], later).comparison.changes, []); eq(r.coverageComplete, false); eq(r.winProbability, null); eq(r.strategySignal, null); eq(r.tradingRiskWindow, null); eq(r.executionAllowed, false); eq(r.replayAllowed, false); });
test("deterministic nested results are immutable", () => { const r = report([input()], at); eq(r, report([input()], at)); ok(Object.isFrozen(r.upcoming[0])); ok(Object.isFrozen(r.comparison.changes)); });
console.log(`${passed}/${passed} tests passed.`);
