import { readFileSync } from "node:fs";
import { buildOptionsReadiness, READINESS_COMPONENTS, type ReadinessEvidenceMap } from "./OptionsReadinessEngine";
import { createBtcReadinessEvidence as evidence, buildOptionsContextReadiness as report, type BtcReadinessEvidence } from "./OptionsContextReadinessEngine";
import { BTC_CONTEXT_URL, type BtcContextInput } from "../options-btc-context/BtcSpotContextEngine";

const source = readFileSync("fixtures/options-btc-context/book.synthetic.json", "utf8"), at = "2026-09-07T04:00:01.000Z", later = "2026-09-07T04:10:00.000Z";
const input = (): BtcContextInput => ({ requestedAt: at, receivedAt: at, url: BTC_CONTEXT_URL, sourceText: source, errorCode: null });
function missing(checkedAt = at) { return { state: "MISSING", checkedAt, reportSha256: null, summary: null, errorCode: "STORE_MISSING" } as const; }
function core() { return buildOptionsReadiness("test-study", Object.fromEntries(READINESS_COMPONENTS.map(key => [key, missing()])) as ReadinessEvidenceMap, at); }
const eq = (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw Error(`Expected ${JSON.stringify(b)}; received ${JSON.stringify(a)}`); };
const ok = (value: unknown) => { if (!value) throw Error("Expected truthy value"); };
function throws(work: () => unknown, code = "READINESS_") { let error; try { work(); } catch (e) { error = e; } if (!(error instanceof Error) || !error.message.includes(code)) throw Error("Expected " + code); }
let passed = 0;
function test(name: string, work: () => void) { work(); passed++; console.log(`PASS ${name}`); }
test("v2 preserves exact v1 review calculations, next step and mandatory dependencies", () => { const v1 = core(), before = JSON.stringify(v1), r = report(v1, evidence([input()], at), at); eq(r.version, "OPTIONS_OPERATIONAL_READINESS_V2"); eq(r.coreReportSha256, v1.reportSha256); eq(r.nextStep, v1.nextStep); eq(r.dependencies, v1.dependencies); eq(r.closedPaperReviewCoverage, v1.closedPaperReviewCoverage); eq(r.candidateNotebooks, v1.candidateNotebooks); eq(JSON.stringify(v1), before); eq(r.btcContextRequiredForReplay, false); });
test("seven-component fingerprint includes independently checked BTC evidence", () => { const r = report(core(), evidence([input()], at), at), m = report(core(), missing(), at); ok(r.reportSha256 !== m.reportSha256); eq(Object.keys(r.evidence).length, 7); eq(r.missingStores.length, 6); eq(m.missingStores.length, 7); });
test("later BTC checks retain the original core clock and separate source nanoseconds", () => { const r = report(core(), evidence([input()], later), later); eq(r.coreAssessedAt, at); eq(r.assessedAt, later); if (r.evidence.btc.state !== "AVAILABLE") throw Error("missing"); eq(r.evidence.btc.summary.sourceTime, "2026-09-07T04:00:00.000000001Z"); eq(r.evidence.btc.summary.displayFreshAtCheck, false); eq(r.evidence.btc.summary.sourceAgeAtReceiptNs, "999999999"); });
test("busy optional BTC does not change core dependency authority", () => { const blocked: BtcReadinessEvidence = { ...missing(), state: "BLOCKED", errorCode: "STORE_BUSY" }; const r = report(core(), blocked, at); eq(r.blockedStores, ["btc"]); eq(r.nextStep, core().nextStep); eq(r.contextNextStep, "REVIEW_BTC_CONTEXT_STORAGE"); eq(r.realPriceTestReady, false); });
test("failed source is distinct from blocked storage and cannot display stale prices", () => { const failure: BtcContextInput = { ...input(), sourceText: null, errorCode: "NETWORK_FAILED" }; const e = evidence([input(), failure], at), r = report(core(), e, at); eq(r.blockedStores, []); eq(e.summary.status, "FAILED"); eq(e.summary.midpointUsd, null); eq(e.summary.displayFreshAtCheck, false); eq(r.contextNextStep, "REVIEW_BTC_SOURCE_FAILURE"); });
test("empty recovered history retains zero counts and unknown clocks", () => { const e = evidence([], at); report(core(), e, at); eq(e.summary.status, "NOT_REFRESHED"); eq(e.summary.receivedAt, null); eq(e.summary.retrievalCount, 0); });
test("invalid source books retain explicit issues without exposing raw text", () => { const raw = source.replace('"auction":null', '"auction":{"note":"EXTERNAL_INSTRUCTION"}'); const e = evidence([{ ...input(), sourceText: raw }], at); report(core(), e, at); eq(e.summary.status, "UNUSABLE_CONTEXT"); ok(e.summary.issues.includes("AUCTION_DETAILS_PRESENT")); ok(!JSON.stringify(e).includes("EXTERNAL_INSTRUCTION")); });
test("missing source clock remains unusable unknown instead of receiving the host clock", () => { const e = evidence([{ ...input(), sourceText: source.replace(/,"time":"[^"]*"/, "") }], at); report(core(), e, at); eq(e.summary.sourceTime, null); eq(e.summary.ageAtCheckNs, null); });
test("future and stale source clocks keep their original quality findings", () => { for (const time of ["2026-09-07T04:00:01.000000001Z", "2026-09-07T03:59:00Z"]) { const e = evidence([{ ...input(), sourceText: source.replace(/"time":"[^"]*"/, '"time":"' + time + '"') }], at); report(core(), e, at); eq(e.summary.status, "UNUSABLE_CONTEXT"); } });
test("modified v1 version, permissions, dependencies or fingerprint are rejected", () => { for (const patch of [{ version: "other" }, { executionAllowed: true }, { reportSha256: "a".repeat(64) }, { dependencies: [] }]) throws(() => report({ ...core(), ...patch } as ReturnType<typeof core>, evidence([input()], at), at), "CORE_REPORT_CHANGED"); });
test("BTC check cannot precede the original core completion or follow v2 completion", () => { throws(() => report(core(), missing("2026-09-07T04:00:00.000Z"), at), "CHECK_CLOCK_ORDER"); throws(() => report(core(), evidence([input()], later), at), "CHECK_CLOCK_ORDER"); });
test("wrong source product, trading scope and continuous-coverage claims fail", () => { for (const patch of [{ product: "ETH-USD" }, { contextFor: ["GLD"] }, { continuousCoverage: true }, { ibitPriceConversionAvailable: true }, { source: "ROBINHOOD" }]) { const e = structuredClone(evidence([input()], at)); Object.assign(e.summary, patch); throws(() => report(core(), e, at), "SCOPE"); } });
test("negative or contradictory counts and invented source states fail", () => { for (const patch of [{ retrievalCount: -1 }, { usableAtReceiptCount: 2 }, { status: "LIVE" }, { retrievalCount: 0 }, { status: "FAILED" }]) { const e = structuredClone(evidence([input()], at)); Object.assign(e.summary, patch); throws(() => report(core(), e, at)); } });
test("summary ages and stale flags must match exact source and receipt clocks", () => { for (const patch of [{ ageAtCheckNs: "1" }, { sourceAgeAtReceiptNs: "1000000000" }, { displayFreshAtCheck: false }, { receivedAt: later }]) { const e = structuredClone(evidence([input()], at)); Object.assign(e.summary, patch); throws(() => report(core(), e, at)); } });
test("failed or missing evidence cannot carry old source values", () => { const f = evidence([{ ...input(), sourceText: null, errorCode: "NETWORK_FAILED" }], at); const e = structuredClone(f); Object.assign(e.summary, { midpointUsd: "80000" }); throws(() => report(core(), e, at), "STALE_PROMOTION"); const m = { ...missing(), summary: f.summary } as unknown as BtcReadinessEvidence; throws(() => report(core(), m, at), "STORAGE_STATE"); });
test("unknown issue text and false comparison claims fail", () => { for (const patch of [{ issues: ["PRIVATE_INSTRUCTION"] }, { comparisonAvailable: true }, { comparisonIssues: [] }, { midpointUsd: "Infinity" }]) { const e = structuredClone(evidence([input()], at)); Object.assign(e.summary, patch); throws(() => report(core(), e, at)); } });
test("price strings cannot be replaced by numeric coercion or an impossible zero", () => { for (const midpointUsd of [80000, "0"]) { const e = structuredClone(evidence([input()], at)); Object.assign(e.summary, { midpointUsd }); throws(() => report(core(), e, at), "PRICE"); } });
test("availability comparisons need two consecutive usable observations", () => { const next = { ...input(), requestedAt: later, receivedAt: later, sourceText: source.replace('"sequence":100', '"sequence":101').replace('04:00:00.000000001Z', '04:09:59.000000001Z') }; const e = evidence([input(), next], later); const r = report(core(), e, later); eq(e.summary.comparisonAvailable, true); eq(r.winProbability, null); eq(r.executionAllowed, false); });
test("output is immutable and no input bytes are changed", () => { const e = evidence([input()], at), r = report(core(), e, at); eq(r, report(core(), e, at)); ok(Object.isFrozen(r.evidence.btc)); ok(Object.isFrozen(r.dependencies)); eq(r.networkAccess, false); eq(r.hostSchedule, "NOT_INSPECTED"); });
console.log(`${passed}/${passed} tests passed.`);
