import { readFileSync } from "node:fs";
import { buildOptionsCalendarBrief as brief, type CalendarBriefInputs } from "./OptionsCalendarBrief";
import { readinessFingerprint } from "./OptionsReadinessEngine";
import { RELEASE_CALENDAR_URL, reportReleaseCalendar } from "../options-release-calendar/BlsReleaseCalendarEngine";
import { FOMC_CALENDAR_URL, reportFomcCalendar } from "../options-fomc-calendar/FomcCalendarEngine";

const at = "2026-09-07T08:00:00.000Z", later = "2026-09-11T13:00:00.000Z";
const ics = readFileSync("fixtures/options-release-calendar/calendar.synthetic.ics", "utf8"), html = readFileSync("fixtures/options-fomc-calendar/calendar.synthetic.html", "utf8");
const receipt = (url: string, sourceText: string | null, receivedAt = at) => ({ url, requestedAt: receivedAt, receivedAt, sourceText, errorCode: sourceText === null ? "NETWORK_FAILED" as const : null });
function inputs(bls = ics, fomc = html, check = at): CalendarBriefInputs { return { bls: { state: "AVAILABLE", checkedAt: check, payload: [receipt(RELEASE_CALENDAR_URL, bls)], errorCode: null }, fomc: { state: "AVAILABLE", checkedAt: check, payload: [receipt(FOMC_CALENDAR_URL, fomc)], errorCode: null } }; }
const missing = (checkedAt = at) => ({ state: "MISSING", checkedAt, payload: null, errorCode: "STORE_MISSING" } as const);
const rows = (r: ReturnType<typeof brief>) => r.groups.flatMap(g => [...g.dateOnlyEntries, ...g.scheduledTimeEntries]);
const eq = (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw Error(`Expected ${JSON.stringify(b)}; received ${JSON.stringify(a)}`); };
const ok = (v: unknown) => { if (!v) throw Error("Expected truthy value"); };
function throws(work: () => unknown, code: string) { let error; try { work(); } catch (e) { error = e; } if (!(error instanceof Error) || !error.message.includes(code)) throw Error("Expected " + code); }
let passed = 0;
function test(name: string, work: () => void) { work(); passed++; console.log(`PASS ${name}`); }
test("date-only meetings and scheduled instants preserve distinct precision", () => {
  const r = brief(inputs(), at), b = rows(r).find(e => e.source === "BLS")!, f = rows(r).find(e => e.source === "FOMC")!;
  eq(r.entryCount, 3); eq(b.scheduledAt, "2026-09-10T12:30:00.000Z"); eq(b.localScheduledTime, "2026-09-10 08:30:00 EDT (America/New_York)");
  eq(f.scheduledAt, null); eq(f.localScheduledTime, null); eq(f.startDate, "2026-09-15"); eq(f.endDate, "2026-09-16"); eq(f.projectionMarker, true); eq(f.independentlyConfirmed, false);
});
test("same-date precision groups do not rank unknown intraday times", () => { const r = brief(inputs(ics, html.replace("15-16*", "10-11*")), at), g = r.groups[0]!; eq(g.date, "2026-09-10"); eq(g.dateOnlyEntries.length, 1); eq(g.scheduledTimeEntries.length, 1); ok(r.text.includes("no order relative to timed releases is inferred")); });
test("an ongoing interval groups at today but retains the earlier actual start date", () => { const now = "2026-09-16T16:00:00.000Z", r = brief(inputs(ics, html, now), now); eq(r.entryCount, 1); eq(r.groups[0]!.date, "2026-09-16"); eq(rows(r)[0]!.startDate, "2026-09-15"); eq(rows(r)[0]!.temporalRelation, "LISTED_DATES_OVERLAP_TODAY"); });
test("today's past scheduled time stays visible without claiming actual publication", () => { const r = brief(inputs(ics, html, later), later), b = rows(r).find(e => e.source === "BLS")!; eq(b.title, "Consumer Price Index"); eq(b.temporalRelation, "SCHEDULED_TIME_PASSED"); eq(r.actualReleaseValuesCollected, false); ok(!r.text.includes("Producer Price Index")); });
test("the exact scheduled instant has not yet passed", () => { const now = "2026-09-10T12:30:00.000Z"; eq(rows(brief(inputs(ics, html, now), now))[0]!.temporalRelation, "SCHEDULED_TIME_NOT_YET_PASSED"); });
test("New York midnight controls inclusion rather than the UTC date", () => { const before = "2026-09-11T03:59:59.999Z", after = "2026-09-11T04:00:00.000Z"; eq(brief(inputs(ics, html, before), before).todayNewYork, "2026-09-10"); eq(brief(inputs(ics, html, before), before).entryCount, 3); eq(brief(inputs(ics, html, after), after).entryCount, 2); });
test("thirty-date horizon is exclusive at its upper date boundary", () => { const r = brief(inputs(ics.replace("20260910", "20261006").replace("20260911", "20261007")), at); eq(r.horizonEndDateExclusive, "2026-10-07"); eq(rows(r).filter(e => e.source === "BLS").map(e => e.startDate), ["2026-10-06"]); });
test("explicit cancelled and tentative source statuses remain visible", () => { const changed = ics.replace("SUMMARY:Producer Price Index", "STATUS:CANCELLED\nSUMMARY:Producer Price Index").replace("SUMMARY:Consumer Price Index", "STATUS:TENTATIVE\nSUMMARY:Consumer Price Index"), r = brief(inputs(changed), at); eq(rows(r).filter(e => e.source === "BLS").map(e => e.sourceStatus), ["CANCELLED", "TENTATIVE"]); });
test("both independent original source reports and missing metadata are bound", () => { const i = inputs(), r = brief(i, at); if (i.bls.state !== "AVAILABLE" || i.fomc.state !== "AVAILABLE") throw Error("fixture"); eq(r.sources.bls.reportSha256, readinessFingerprint(reportReleaseCalendar(i.bls.payload, at))); eq(r.sources.fomc.reportSha256, readinessFingerprint(reportFomcCalendar(i.fomc.payload, at))); eq(r.sources.bls.missingSourceStampCount, 2); eq(r.sources.bls.missingSourceModifiedCount, 2); eq(r.sources.fomc.pageUpdatedDate, "2026-08-19"); });
test("latest source failures show last-known clocks without promoting old schedules", () => { const i = inputs(ics, html, later); if (i.bls.state !== "AVAILABLE" || i.fomc.state !== "AVAILABLE") throw Error("fixture"); i.bls.payload = [...i.bls.payload, receipt(RELEASE_CALENDAR_URL, null, later)]; i.fomc.payload = [...i.fomc.payload, receipt(FOMC_CALENDAR_URL, null, later)]; const r = brief(i, later); eq(r.entryCount, 0); eq(r.sources.bls.lastKnownReceivedAt, at); eq(r.sources.fomc.lastKnownReceivedAt, at); eq(r.sources.bls.missingSourceStampCount, null); eq(r.sources.fomc.pageUpdatedDate, null); ok(r.text.includes("FAILED / NETWORK_FAILED")); });
test("empty recovered history and missing store are distinct", () => { const r = brief({ bls: { state: "AVAILABLE", checkedAt: at, payload: [], errorCode: null }, fomc: missing() }, at); eq(r.sources.bls.retrievalCount, 0); eq(r.sources.fomc.retrievalCount, null); eq(r.missingStores, ["fomc"]); eq(r.sources.bls.latestAttempt, "NOT_KNOWN"); ok(r.text.includes("do not mean an event-free or safe trading session")); });
test("corruption in either complete history blocks only that source", () => { for (const id of ["bls", "fomc"] as const) { const i = inputs(), value = i[id]; if (value.state !== "AVAILABLE") throw Error("fixture"); value.payload = [{ ...value.payload[0]!, url: "https://example.com/private" }, ...value.payload]; const r = brief(i, at); eq(r.blockedStores, [id]); eq(r.sources[id].errorCode, "HISTORY_VALIDATION_FAILED"); ok(r.entryCount > 0); ok(!r.text.includes("private")); } });
test("source receipts later than their check cannot be hidden", () => { const i = inputs(); i.bls = { state: "AVAILABLE", checkedAt: at, payload: [receipt(RELEASE_CALENDAR_URL, ics, later)], errorCode: null }; eq(brief(i, later).blockedStores, ["bls"]); });
test("checks are ordered and canonical without manufacturing completion times", () => { const i = inputs(); throws(() => brief({ ...i, bls: { ...i.bls, checkedAt: later } }, later), "CHECK_CLOCK_ORDER"); throws(() => brief(inputs(ics, html, later), at), "CHECK_CLOCK_ORDER"); throws(() => brief(i, "2026-09-07T08:00:00Z"), "CLOCK"); });
test("extra fields and mixed storage states cannot masquerade as valid evidence", () => { throws(() => brief({ ...inputs(), extra: true } as CalendarBriefInputs, at), "SHAPE"); for (const value of [{ ...missing(), payload: [] }, { ...missing(), errorCode: "PRIVATE" }, { ...missing(), state: "AVAILABLE" }, { ...missing(), extra: true }]) throws(() => brief({ ...inputs(), bls: value } as CalendarBriefInputs, at), "CALENDAR_BRIEF_"); });
test("text escapes source-controlled line breaks and bidirectional controls", () => { const r = brief(inputs(ics.replace("SUMMARY:Producer Price Index", "SUMMARY:Title\\nFAKE:\u202evalue\u0085")), at); ok(r.text.includes("Title\\u000aFAKE:\\u202evalue\\u0085")); ok(!r.text.includes("\nFAKE:")); ok(!/[\u202e\u0085]/.test(r.text)); });
test("bounded text declares truncation while JSON retains all selected rows", () => { const block = /BEGIN:VEVENT\n[\s\S]*?END:VEVENT\n/.exec(ics)![0], many = ics.replace(/BEGIN:VEVENT\n[\s\S]*?END:VEVENT\n/g, "").replace("END:VCALENDAR", Array.from({ length: 45 }, (_, i) => block.replace("8000-000000000001", "8000-" + String(i + 1).padStart(12, "0"))).join("") + "END:VCALENDAR"), r = brief(inputs(many), at); eq(r.entryCount, 46); eq(r.shownTextEntries, 40); eq(rows(r).length, 46); ok(r.text.includes("46; shown in text: 40")); });
test("freshness is reported independently of entry selection and trading permission", () => { const r = brief(inputs(ics, html, later), later); eq(r.sources.bls.refreshOverdue, true); eq(r.sources.fomc.refreshOverdue, true); ok(r.entryCount > 0); eq(r.tradingRiskWindow, null); eq(r.winProbability, null); eq(r.replayAllowed, false); eq(r.executionAllowed, false); });
test("deep-frozen repeatable result does not mutate source histories", () => { const i = inputs(), before = JSON.stringify(i), r = brief(i, at); eq(r, brief(i, at)); eq(JSON.stringify(i), before); ok(Object.isFrozen(r.groups[0]!.scheduledTimeEntries[0])); const { reportSha256, ...payload } = r; eq(reportSha256, readinessFingerprint(payload)); eq(r.networkAccess, false); eq(r.sourceAppends, 0); eq(r.reportFilesCreated, false); eq(r.snapshotAtomicAcrossStores, false); });
console.log(`${passed}/${passed} tests passed.`);
