import { buildOptionsReadiness as report, READINESS_COMPONENTS, type ReadinessComponent, type ReadinessEvidence, type ReadinessEvidenceMap, type ReadinessSummaries } from "./OptionsReadinessEngine";

const at = "2026-09-07T14:00:00.000Z", end = "2026-09-08T13:50:00.000Z", study = "readiness-study";
const eq = (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw Error(`Expected ${JSON.stringify(b)}; received ${JSON.stringify(a)}`); };
const ok = (v: unknown) => { if (!v) throw Error("Expected truthy value"); };
function throws(work: () => unknown, code = "OPTIONS_READINESS_") { let error; try { work(); } catch (e) { error = e; } if (!(error instanceof Error) || !error.message.includes(code)) throw Error("Expected " + code); }
function evidence(): ReadinessEvidenceMap {
  const summaries: ReadinessSummaries = {
    collection: { studyId: study, stage: "WAITING_FOR_WINDOW", windowStartAt: "2026-09-08T13:30:00.000Z", windowEndAt: end,
      declaredSlots: 20, elapsedSlots: 0, completeUsableSlots: 0, automaticAttempts: 0, sourceFailures: 0, savedFrames: 0, usableObservations: 0,
      operationalLessons: 0, quoteQualityLessons: 0, blockerCodes: ["REPLAY_ADAPTER_NOT_IMPLEMENTED"] },
    paper: { origin: "SYNTHETIC_FIXTURE", tradeCount: 7, closedTradeCount: 5, reviewCount: 5, missingReviewCount: 0, openPositionCount: 0, pendingOrderCount: 0, candidateLessonCount: 4, notebookFingerprint: "sha256:" + "a".repeat(64) },
    historical: { runCount: 8, closedTradeCount: 4, reviewedRunCount: 8, candidateLessonCount: 15, syntheticRuns: 6, importedRuns: 0, missingDataRuns: 2 },
    imports: { datasetCount: 2, rowCount: 10, syntheticDatasets: 1, ownerProvidedDatasets: 1, decision: "NO_REPLAY" },
    headlines: { observationsInHistory: 118, sources: ["fed", "bls", "bea", "ecb", "ofac", "sec"].map(id => ({ id, status: "OK", observedAt: at, refreshOverdue: false })) },
    treasury: { retrievalCount: 1, status: "OK", receivedAt: at, sourceDate: "2026-09-04", dateLagDays: 3, missingTenors: [], versionCount: 4, ratesBps: { 5: -10, 7: 0, 10: 200, 20: 250, 30: 300 } },
  };
  const available = <K extends ReadinessComponent>(id: K): ReadinessEvidence<K> => ({ state: "AVAILABLE", checkedAt: at, reportSha256: "b".repeat(64), summary: summaries[id], errorCode: null });
  return { collection: available("collection"), paper: available("paper"), historical: available("historical"), imports: available("imports"), headlines: available("headlines"), treasury: available("treasury") };
}
const change = (map: ReadinessEvidenceMap, id: keyof ReadinessEvidenceMap): any => map[id].summary;
function atEnd() { const map = evidence(); for (const id of READINESS_COMPONENTS) map[id].checkedAt = end; change(map, "collection").stage = "WINDOW_ENDED"; change(map, "collection").elapsedSlots = 20; change(map, "treasury").dateLagDays = 4; return map; }
let passed = 0;
function test(name: string, work: () => void) { work(); passed++; console.log(`PASS ${name}`); }
test("pending frozen window is explicit rather than a failed feed", () => { const r = report(study, evidence(), at); eq(r.nextStep, "WAIT_FOR_FROZEN_OPENING_WINDOW"); eq(r.collectionState, "WAITING_FOR_WINDOW"); eq(r.blockedStores, []); });
test("completed paper reviews and separate candidate notebooks retain their own counts", () => { const r = report(study, evidence(), at); eq(r.closedPaperReviewCoverage, { closed: 5, reviewed: 5, missing: 0, consistent: true }); eq(r.candidateNotebooks.paper, 4); eq(r.candidateNotebooks.historical, 15); eq(r.candidateNotebooks.approvedKnowledge, false); });
test("all components available still cannot authorize a real-price replay or trade", () => { const r = report(study, evidence(), at); eq(r.realPriceTestReady, false); eq(r.status, "NO_REPLAY"); eq(r.winProbability, null); eq(r.realPriceTradeCount, 0); eq(r.automaticOrdersEnabled, false); eq(r.sizeEscalationAllowed, false); });
test("empty ended collection asks for a data review without fabricating an outcome", () => { const r = report(study, atEnd(), end); eq(r.collectionState, "NO_USABLE_OBSERVATIONS"); eq(r.nextStep, "REVIEW_EMPTY_OR_UNUSABLE_COLLECTION"); });
test("partial diagnostic coverage remains separate from full coverage", () => { const m = atEnd(), c = change(m, "collection"); Object.assign(c, { savedFrames: 1, usableObservations: 4, completeUsableSlots: 1 }); const r = report(study, m, end); eq(r.collectionState, "PARTIAL_DIAGNOSTIC_COVERAGE"); eq(r.nextStep, "REVIEW_SOURCE_SEMANTICS_AND_EXECUTION_ASSUMPTIONS"); });
test("complete quote diagnostics cannot satisfy missing source semantics and adapter", () => { const m = atEnd(), c = change(m, "collection"); Object.assign(c, { savedFrames: 20, usableObservations: 80, completeUsableSlots: 20 }); const r = report(study, m, end); eq(r.collectionState, "DIAGNOSTIC_COVERAGE_COMPLETE"); eq(r.dependencies.find(s => s.code === "IMPLEMENT_QUALIFIED_ROBINHOOD_PAPER_ADAPTER")!.state, "NOT_IMPLEMENTED"); eq(r.realPriceTestReady, false); });
test("active window preserves the existing authorized collection step", () => { const m = atEnd(), t = "2026-09-08T13:40:00.000Z"; m.collection.checkedAt = t; Object.assign(change(m, "collection"), { stage: "WINDOW_IN_PROGRESS", elapsedSlots: 10 }); for (const id of READINESS_COMPONENTS) m[id].checkedAt = t; eq(report(study, m, t).nextStep, "CONTINUE_AUTHORIZED_WINDOW_COLLECTION"); });
test("one blocked store remains isolated and takes operational priority", () => { const m = evidence(); m.treasury = { state: "BLOCKED", checkedAt: at, reportSha256: null, summary: null, errorCode: "STORE_BUSY" }; const r = report(study, m, at); eq(r.blockedStores, ["treasury"]); eq(r.evidence.paper.state, "AVAILABLE"); eq(r.nextStep, "REVIEW_BLOCKED_LOCAL_STORAGE"); });
test("missing optional imports do not invent a paid-data prerequisite", () => { const m = evidence(); m.imports = { state: "MISSING", checkedAt: at, reportSha256: null, summary: null, errorCode: "STORE_MISSING" }; const r = report(study, m, at); eq(r.missingStores, ["imports"]); eq(r.nextStep, "WAIT_FOR_FROZEN_OPENING_WINDOW"); });
test("missing selected study cannot be replaced by other available sources", () => { const m = evidence(); m.collection = { state: "MISSING", checkedAt: at, reportSha256: null, summary: null, errorCode: "STORE_MISSING" }; const r = report(study, m, at); eq(r.collectionState, "EVIDENCE_UNAVAILABLE"); eq(r.nextStep, "LOCATE_SELECTED_STUDY_EVIDENCE"); });
test("missing closed-trade review needs attention even if quotes are complete", () => { const m = evidence(); Object.assign(change(m, "paper"), { reviewCount: 4, missingReviewCount: 1 }); const r = report(study, m, at); eq(r.closedPaperReviewCoverage!.consistent, false); eq(r.nextStep, "REPAIR_MISSING_SIMULATED_TRADE_REVIEWS"); });
test("unreviewed historical missing-data runs cannot disappear", () => { const m = evidence(); change(m, "historical").reviewedRunCount = 7; eq(report(study, m, at).nextStep, "REPAIR_MISSING_RESEARCH_REVIEWS"); });
test("synthetic future scenario clocks are explicitly not actual brokerage times", () => { const r = report(study, evidence(), at); eq(r.paperClockBasis, "SCENARIO_CLOCKS_NOT_BROKER_OR_ACTUAL_RECORDING_TIMES"); eq(r.liveAccountInspected, false); eq(r.accountAggregation, "LOCAL_SIMULATION_AND_INDEPENDENT_RESEARCH_ARE_SEPARATE"); });
test("invalid IDs and mismatched studies fail instead of choosing another plan", () => { throws(() => report("../other", evidence(), at), "STUDY_ID"); const m = evidence(); change(m, "collection").studyId = "other-study"; throws(() => report(study, m, at), "STUDY_SCOPE"); });
test("future check clocks and malformed hashes cannot label evidence recovered", () => { const m = evidence(); m.paper.checkedAt = end; throws(() => report(study, m, at), "FUTURE_CHECK"); m.paper.checkedAt = at; m.paper.reportSha256 = "fake"; throws(() => report(study, m, at), "HASH"); });
test("a clock regression between component reads is not a valid sequential snapshot", () => { const m = evidence(); m.paper.checkedAt = "2026-09-07T13:59:59.000Z"; throws(() => report(study, m, at), "CHECK_CLOCK_REGRESSION"); });
test("missing and blocked states cannot carry stale summaries", () => { const m: any = evidence(); m.paper.state = "MISSING"; m.paper.errorCode = "STORE_MISSING"; throws(() => report(study, m, at), "EVIDENCE_STATE"); });
test("impossible count relationships and pending elapsed slots reject", () => { for (const patch of [{ elapsedSlots: 1 }, { sourceFailures: 1 }, { usableObservations: 1 }, { completeUsableSlots: 21 }]) { const m = evidence(); Object.assign(change(m, "collection"), patch); throws(() => report(study, m, at)); } });
test("negative, fractional and unsafe counts reject", () => { for (const v of [-1, 0.5, Number.MAX_SAFE_INTEGER + 1]) { const m = evidence(); change(m, "paper").tradeCount = v; throws(() => report(study, m, at), "COUNT"); } });
test("historical origins cannot be merged or silently omitted", () => { const m = evidence(); change(m, "historical").importedRuns = 1; throws(() => report(study, m, at), "HISTORICAL_COUNTS"); });
test("an invented real-paper origin or positive imported replay gate rejects", () => { const m = evidence(); change(m, "paper").origin = "BROKERAGE"; throws(() => report(study, m, at), "PAPER_ORIGIN"); const n = evidence(); change(n, "imports").decision = "REPLAY_READY"; throws(() => report(study, n, at), "IMPORT_BOUNDARY"); });
test("headline storage health remains available when a source fails", () => { const m = evidence(); change(m, "headlines").sources[0].status = "FAILED"; const r = report(study, m, at); eq(r.evidence.headlines.state, "AVAILABLE"); eq(r.blockedStores, []); });
test("headline source identity, future clocks and duplicates are checked", () => { for (const mutate of [(s: any) => { s.id = "other"; }, (s: any) => { s.observedAt = end; }]) { const m = evidence(); mutate(change(m, "headlines").sources[0]); throws(() => report(study, m, at)); } });
test("failed Treasury retrieval has no current rates despite recoverable history", () => { const m = evidence(); Object.assign(change(m, "treasury"), { status: "FAILED", sourceDate: null, ratesBps: null, dateLagDays: null, missingTenors: [5, 7, 10, 20, 30] }); const r = report(study, m, at); eq(r.evidence.treasury.state, "AVAILABLE"); eq(r.blockedStores, []); });
test("stale Treasury values cannot masquerade as a current failed retrieval", () => { const m = evidence(); change(m, "treasury").status = "FAILED"; throws(() => report(study, m, at), "TREASURY_CURRENT_VALUE"); });
test("Treasury nulls and negative basis points retain exact meanings", () => { const m = evidence(); const s = change(m, "treasury"); s.ratesBps[10] = null; s.missingTenors = [10]; const r = report(study, m, at); if (r.evidence.treasury.state !== "AVAILABLE") throw Error("Unavailable"); eq(r.evidence.treasury.summary.ratesBps![5], -10); eq(r.evidence.treasury.summary.ratesBps![10], null); });
test("Treasury source-date lag and missing-tenor declarations must agree", () => { for (const patch of [{ dateLagDays: 0 }, { missingTenors: [10] }, { sourceDate: "2026-09-08" }]) { const m = evidence(); Object.assign(change(m, "treasury"), patch); throws(() => report(study, m, at)); } });
test("deterministic reports clone inputs and freeze candidate evidence", () => { const m = evidence(), r = report(study, m, at); eq(r, report(study, m, at)); ok(Object.isFrozen(r.evidence.paper.summary)); change(m, "paper").candidateLessonCount = 99; eq(r.candidateNotebooks.paper, 4); eq(r.snapshotAtomicAcrossStores, false); eq(r.hostSchedule, "NOT_INSPECTED"); });
console.log(`${passed}/${passed} tests passed.`);
