import { readFileSync } from "node:fs";
import { reconstructOptionsContext as reconstruct, type ContextCutoffHistories, type ContextHistory } from "./OptionsContextCutoff";
import { createDriverObservation } from "../options-drivers/OptionsDriverMonitorEngine";
import { treasuryUrl, type TreasuryInput } from "../options-treasury/TreasuryRealYieldEngine";
import { BTC_CONTEXT_URL, type BtcContextInput } from "../options-btc-context/BtcSpotContextEngine";
import { RELEASE_CALENDAR_URL, type ReleaseCalendarInput } from "../options-release-calendar/BlsReleaseCalendarEngine";

const early = "2026-09-07T04:00:01.000Z", cutoff = "2026-09-07T04:30:00.000Z", later = "2026-09-07T05:00:00.000Z", checked = "2026-09-07T06:00:00.000Z", finish = "2026-09-07T07:00:00.000Z";
const xml = readFileSync("fixtures/options-treasury/real-yields.synthetic.xml", "utf8"), book = readFileSync("fixtures/options-btc-context/book.synthetic.json", "utf8"), ics = readFileSync("fixtures/options-release-calendar/calendar.synthetic.ics", "utf8");
const available = <T>(payload: T, checkedAt = checked): ContextHistory<T> => ({ state: "AVAILABLE", checkedAt, payload, errorCode: null });
const observation = (observedAt = early, headline = "Federal Reserve monetary policy rates decision") => createDriverObservation({ sourceId: "fed", itemId: "cutoff-1", headline, link: "https://www.federalreserve.gov/", publishedAt: "2026-09-06T12:00:00.000Z", observedAt, origin: "PUBLIC_FEED" });
const health = (observedAt = early) => ({ sourceId: "fed", status: "OK" as const, observedAt, itemsReceived: 1, truncated: false, diagnostic: null });
const treasury = (receivedAt = early, sourceText = xml): TreasuryInput => ({ requestedAt: receivedAt, receivedAt, url: treasuryUrl(receivedAt), sourceText, errorCode: null });
const btc = (receivedAt = early): BtcContextInput => ({ requestedAt: receivedAt, receivedAt, url: BTC_CONTEXT_URL, sourceText: book, errorCode: null });
const calendar = (receivedAt = early, sourceText = ics): ReleaseCalendarInput => ({ requestedAt: receivedAt, receivedAt, url: RELEASE_CALENDAR_URL, sourceText, errorCode: null });
function histories(): ContextCutoffHistories { return { headlines: available({ observations: [observation()], health: [health()] }), treasury: available([treasury()]), btc: available([btc()]), blsCalendar: available([calendar()]) }; }
const run = (h = histories(), at = cutoff, end = checked) => reconstruct(h, at, end);
const eq = (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw Error(`Expected ${JSON.stringify(b)}; received ${JSON.stringify(a)}`); };
const ok = (v: unknown) => { if (!v) throw Error("Expected truthy value"); };
function throws(work: () => unknown, code = "CONTEXT_CUTOFF_") { let error; try { work(); } catch (e) { error = e; } if (!(error instanceof Error) || !error.message.includes(code)) throw Error("Expected " + code); }
let passed = 0;
function test(name: string, work: () => void) { work(); passed++; console.log(`PASS ${name}`); }

test("each source is reconstructed at the cutoff and binds its selected prefix", () => { const r = run(); eq(r.blockedStores, []); for (const c of Object.values(r.context.components)) { eq(c.state, "AVAILABLE"); ok(c.selectedPrefixSha256); ok(c.reportSha256); eq(c.report && ("asOf" in c.report ? c.report.asOf : c.report.assessedAt), cutoff); } });
test("equal receipt time is included while even one millisecond later is excluded", () => { const h = histories(); h.treasury = available([treasury(cutoff), treasury("2026-09-07T04:30:00.001Z")]); eq(run(h).context.components.treasury.report!.retrievalCount, 1); });
test("request start and economic source date cannot substitute for receipt", () => { const h = histories(); h.treasury = available([{ ...treasury(later), requestedAt: early }]); const r = run(h).context.components.treasury; eq(r.state, "AVAILABLE"); eq(r.report!.retrievalCount, 0); eq(r.report!.currentRow, null); });
test("later discovered headlines with earlier publication dates remain excluded", () => { const h = histories(); h.headlines = available({ observations: [observation(later)], health: [health(later)] }); const r = run(h).context.components.headlines.report!; eq(r.observationsInHistory, 0); eq(r.currentItemVersions, 0); eq(r.sources[0]!.health.status, "NOT_REFRESHED"); });
test("undated health never claims an earlier successful refresh", () => { const h = histories(); h.headlines = available({ observations: [], health: [{ ...health(), status: "NOT_REFRESHED", observedAt: null, itemsReceived: 0 }] }); eq(run(h).context.components.headlines.report!.sources[0]!.health.status, "NOT_REFRESHED"); });
test("later valid source appends cannot change an earlier context fingerprint", () => { const a = run(), h = histories(); h.treasury = available([treasury(), treasury(later, xml.replace("1.90", "1.91"))], finish); h.btc = available([btc(), btc(later)], finish); h.blsCalendar = available([calendar(), calendar(later, ics.replace("Producer Price Index", "Corrected schedule"))], finish); h.headlines = available({ observations: [observation(), observation(later, "Corrected inflation policy")], health: [health(), health(later)] }, finish); const b = run(h, cutoff, finish); eq(b.contextSha256, a.contextSha256); ok(b.artifactSha256 !== a.artifactSha256); });
test("construction clock changes only artifact fingerprint", () => { const a = run(), b = run(histories(), cutoff, finish); eq(a.contextSha256, b.contextSha256); ok(a.artifactSha256 !== b.artifactSha256); });
test("latest Treasury failure by cutoff is not skipped for an older current row", () => { const h = histories(); h.treasury = available([treasury(), { ...treasury(cutoff), sourceText: null, errorCode: "NETWORK_FAILED" }]); const r = run(h).context.components.treasury.report!; eq(r.latestRetrieval!.status, "FAILED"); eq(r.currentRow, null); ok(r.lastKnownObservation); });
test("future Treasury failure does not erase earlier context", () => { const h = histories(); h.treasury = available([treasury(), { ...treasury(later), sourceText: null, errorCode: "NETWORK_FAILED" }]); eq(run(h).contextSha256, run().contextSha256); });
test("BTC failure and original stale sample semantics survive the cutoff", () => { const h = histories(); eq(run().context.components.btc.report!.displayFresh, false); h.btc = available([btc(), { ...btc(cutoff), sourceText: null, errorCode: "NETWORK_FAILED" }]); const r = run(h).context.components.btc.report!; eq(r.latestRetrieval!.status, "FAILED"); eq(r.lastKnownObservation!.fromLatestRetrieval, false); eq(r.comparison.midpointChangeUsd, null); });
test("failed calendar has no promoted upcoming schedule", () => { const h = histories(); h.blsCalendar = available([calendar(), { ...calendar(cutoff), sourceText: null, errorCode: "NETWORK_FAILED" }]); const r = run(h).context.components.blsCalendar.report!; eq(r.upcoming, []); eq(r.lastKnownSchedule!.fromLatestRetrieval, false); });
test("calendar publication metadata stays unknown and schedule stays sourced", () => { const r = run().context.components.blsCalendar.report!; eq(r.publisherFreshnessKnown, false); ok(r.latestRetrieval!.missingSourceStampCount > 0); ok(r.upcoming.length > 0); eq(r.tradingRiskWindow, null); });
test("A to B to A Treasury corrections retain cutoff order and first-observed clocks", () => { const h = histories(); h.treasury = available([treasury(), treasury("2026-09-07T04:15:00.000Z", xml.replace("1.90", "1.91")), treasury(cutoff)]); const r = run(h).context.components.treasury.report!; eq(r.versions.length, 4); eq(r.versions[3]!.firstObservedAt, cutoff); eq(r.versions[3]!.valueSha256, r.versions[1]!.valueSha256); });
test("same-clock headline revisions and health retain append order", () => { const h = histories(); h.headlines = available({ observations: [observation(), observation(early, "Revised monetary policy rates")], health: [health(), { ...health(), status: "FAILED", itemsReceived: 0, diagnostic: "HTTP_503" }] }); const r = run(h).context.components.headlines.report!; eq(r.sources[0]!.health.status, "FAILED"); eq(r.factors.find(f => f.id === "monetary_policy")!.candidates[0]!.headline, "Revised monetary policy rates"); });
test("invalid future numerical history blocks that source instead of returning an old prefix", () => { const h = histories(); h.btc = available([btc(), { ...btc(later), url: "https://private.invalid" }]); const r = run(h); eq(r.blockedStores, ["btc"]); eq(r.context.components.btc.errorCode, "HISTORY_VALIDATION_FAILED"); eq(r.context.components.treasury.state, "AVAILABLE"); ok(!JSON.stringify(r).includes("private.invalid")); });
test("corrupted later headline is validated before cutoff selection", () => { const h = histories(); h.headlines = available({ observations: [observation(), { ...observation(later), headline: "TAMPERED" }], health: [] }); eq(run(h).blockedStores, ["headlines"]); });
test("future receipt beyond actual recovery clock blocks that history", () => { const h = histories(); h.blsCalendar = available([calendar(finish)]); eq(run(h).blockedStores, ["blsCalendar"]); });
test("future and regressing discovery histories are independently blocked", () => { for (const observations of [[observation(finish)], [observation(later), observation()]]) { const h = histories(); h.headlines = available({ observations, health: [] }); eq(run(h).blockedStores, ["headlines"]); } });
test("regressing health clocks are not silently reordered", () => { const h = histories(); h.headlines = available({ observations: [], health: [health(later), health()] }); eq(run(h).blockedStores, ["headlines"]); });
test("independent feed completion order need not match catalog order", () => { const h = histories(); h.headlines = available({ observations: [observation(later), createDriverObservation({ sourceId: "bls", itemId: "other", headline: "Inflation data", link: "https://www.bls.gov/", publishedAt: early, observedAt: early, origin: "PUBLIC_FEED" })], health: [health(later), { ...health(), sourceId: "bls" }] }); const r = run(h); eq(r.blockedStores, []); eq(r.context.components.headlines.report!.observationsInHistory, 1); });
test("absent store differs from available history whose records all arrived later", () => { const h = histories(); h.btc = available([btc(later)]); h.blsCalendar = { state: "MISSING", checkedAt: checked, payload: null, errorCode: "STORE_MISSING" }; const r = run(h); eq(r.missingStores, ["blsCalendar"]); eq(r.context.components.btc.state, "AVAILABLE"); eq(r.context.components.btc.report!.retrievalCount, 0); eq(r.context.components.blsCalendar.report, null); });
test("busy unsafe and corrupt stores retain fixed independent errors", () => { for (const errorCode of ["STORE_BUSY", "STORE_UNSAFE", "RECOVERY_FAILED"] as const) { const h = histories(); h.btc = { state: "BLOCKED", checkedAt: checked, payload: null, errorCode }; eq(run(h).context.components.btc.errorCode, errorCode); } });
test("noncanonical clocks and future cutoff fail before source construction", () => { throws(() => run(histories(), "2026-09-07T04:30:00Z"), "OPTIONS_READINESS_CLOCK"); throws(() => run(histories(), finish), "FUTURE_CUTOFF"); });
test("component clocks cannot precede cutoff follow construction or regress", () => { for (const patch of [{ btc: available([], early) }, { btc: available([], finish) }, { headlines: available({ observations: [], health: [] }, finish) }]) throws(() => run({ ...histories(), ...patch }, cutoff, patch.headlines ? finish : checked), "CHECK_CLOCK_ORDER"); });
test("unknown source keys or ambiguous storage states are rejected", () => { throws(() => run({ ...histories(), extra: true } as ContextCutoffHistories), "SHAPE"); for (const patch of [{ errorCode: "STORE_BUSY" }, { payload: null }, { extra: true }, { state: "MISSING", payload: null, errorCode: "RECOVERY_FAILED" }]) { const h = histories(); h.btc = { ...h.btc, ...patch } as ContextCutoffHistories["btc"]; throws(() => run(h)); } });
test("history limits reject instead of truncating old context", () => { const h = histories(); h.headlines = available({ observations: Array.from({ length: 20001 }, () => observation()), health: [] }); eq(run(h).blockedStores, ["headlines"]); });
test("reconstruction grants no trading authority or claim of historical knowledge", () => { const h = histories(), before = JSON.stringify(h), r = run(h); eq(r, run(h)); eq(JSON.stringify(h), before); ok(Object.isFrozen(r.context.components.treasury.report!.versions)); eq(r.context.executionAllowed, false); eq(r.context.replayAllowed, false); eq(r.context.winProbability, null); eq(r.context.historicalDecisionProven, false); eq(r.context.journalAppendTimesKnown, false); eq(r.networkAccess, false); eq(r.sourceAppends, 0); });
console.log(`${passed}/${passed} tests passed.`);
