import { readFileSync } from "node:fs";
import { buildOptionsOperatorBrief as brief, type BriefCalendarInput } from "./OptionsOperatorBrief";
import { buildOptionsReadiness, READINESS_COMPONENTS, type ReadinessEvidenceMap } from "./OptionsReadinessEngine";
import { buildOptionsContextReadiness, createBtcReadinessEvidence } from "./OptionsContextReadinessEngine";
import { BTC_CONTEXT_URL } from "../options-btc-context/BtcSpotContextEngine";
import { RELEASE_CALENDAR_URL } from "../options-release-calendar/BlsReleaseCalendarEngine";

const at = "2026-09-07T06:00:00.000Z", later = "2026-09-07T07:00:00.000Z";
const ics = readFileSync("fixtures/options-release-calendar/calendar.synthetic.ics", "utf8"), book = readFileSync("fixtures/options-btc-context/book.synthetic.json", "utf8");
const missing = () => ({ state: "MISSING", checkedAt: at, reportSha256: null, summary: null, errorCode: "STORE_MISSING" } as const);
function core(map = Object.fromEntries(READINESS_COMPONENTS.map(k => [k, missing()])) as ReadinessEvidenceMap) { return buildOptionsContextReadiness(buildOptionsReadiness("brief-study", map, at), missing(), at); }
function calendar(sourceText: string | null = ics): BriefCalendarInput { return { state: "AVAILABLE", checkedAt: at, errorCode: null, inputs: [{ requestedAt: at, receivedAt: at, url: RELEASE_CALENDAR_URL, sourceText, errorCode: sourceText === null ? "NETWORK_FAILED" : null }] }; }
const absent = () => ({ state: "MISSING", checkedAt: at, inputs: null, errorCode: "STORE_MISSING" } as const);
const eq = (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw Error(`Expected ${JSON.stringify(b)}; received ${JSON.stringify(a)}`); };
const ok = (v: unknown) => { if (!v) throw Error("Expected truthy value"); };
function throws(work: () => unknown, code = "OPTIONS_") { let error; try { work(); } catch (e) { error = e; } if (!(error instanceof Error) || !error.message.includes(code)) throw Error("Expected " + code); }
let passed = 0;
function test(name: string, work: () => void) { work(); passed++; console.log(`PASS ${name}`); }
test("brief binds the unchanged v2 and independently derived calendar reports", () => { const c = core(), r = brief(c, calendar(), at); eq(r.coreReportSha256, c.reportSha256); ok(r.calendarReportSha256); ok(r.text.includes("Producer Price Index")); ok(r.text.includes("2026-09-10 08:30:00 EDT (America/New_York)")); ok(r.text.includes("2026-09-10T12:30:00.000Z")); });
test("unknown paper reviews are not rendered as zero missing reviews", () => { const r = brief(core(), absent(), at); ok(r.text.includes("Closed-trade review coverage: unknown")); ok(!r.text.includes("missing or unmatched closed-trade reviews: 0")); eq(r.missingStores.length, 8); });
test("calendar absence and source failure remain distinct", () => { const r = brief(core(), calendar(null), at); ok(r.text.includes("Latest attempt: FAILED")); ok(r.text.includes("Upcoming within seven days from the calendar check: 0")); eq(r.calendarState, "AVAILABLE"); const m = brief(core(), absent(), at); ok(m.text.includes("Upcoming schedule is unknown")); eq(m.calendarReportSha256, null); });
test("blocked calendar does not hide the other component states", () => { const r = brief(core(), { ...absent(), state: "BLOCKED", errorCode: "STORE_BUSY" }, at); eq(r.blockedStores, ["blsCalendar"]); ok(r.text.includes("paper: MISSING")); ok(r.text.includes("blsCalendar: BLOCKED / STORE_BUSY")); });
test("tampered v2 permissions, hashes and dependencies fail before display", () => { for (const patch of [{ executionAllowed: true }, { reportSha256: "a".repeat(64) }, { nextStep: "TRADE_NOW" }, { dependencies: [] }]) throws(() => brief({ ...core(), ...patch } as ReturnType<typeof core>, calendar(), at), "CORE_REPORT_CHANGED"); });
test("extra v2 evidence or modified core fingerprints cannot be silently ignored", () => { throws(() => brief({ ...core(), evidence: { ...core().evidence, extra: missing() } } as ReturnType<typeof core>, calendar(), at)); throws(() => brief({ ...core(), coreReportSha256: "f".repeat(64) }, calendar(), at), "CORE_REPORT_CHANGED"); });
test("calendar checks cannot precede v2 completion or follow brief completion", () => { throws(() => brief(core(), { ...absent(), checkedAt: "2026-09-07T05:00:00.000Z" }, at), "CHECK_CLOCK_ORDER"); throws(() => brief(core(), { ...absent(), checkedAt: later }, at), "CHECK_CLOCK_ORDER"); });
test("calendar evidence shapes reject mixed missing inputs and untrusted errors", () => { for (const c of [{ ...absent(), inputs: [] }, { ...calendar(), errorCode: "STORE_BUSY" }, { ...absent(), errorCode: "PRIVATE_TEXT" }, { ...calendar(), extra: true }]) throws(() => brief(core(), c as BriefCalendarInput, at)); });
test("calendar input authority and source clocks are validated by the existing engine", () => { const c = calendar(); if (c.state !== "AVAILABLE") throw Error("fixture"); const wrong = { ...c, inputs: c.inputs.map(i => ({ ...i, url: "https://example.com" })) }; throws(() => brief(core(), wrong, at), "RELEASE_CALENDAR_INPUT_SCOPE"); });
test("event titles cannot inject new text rows or bidi instructions", () => { const source = ics.replace("SUMMARY:Producer Price Index", "SUMMARY:Title\\nFAKE_STATUS:\u202evalue\u0085"); const r = brief(core(), calendar(source), at); ok(r.text.includes("Title\\u000aFAKE_STATUS:\\u202evalue\\u0085")); ok(!r.text.includes("\nFAKE_STATUS:")); ok(!/[\u202e\u0085]/.test(r.text)); });
test("twenty-event display limit declares how many are omitted", () => { const block = /BEGIN:VEVENT\n[\s\S]*?END:VEVENT\n/.exec(ics)![0]; const many = ics.replace(/BEGIN:VEVENT\n[\s\S]*?END:VEVENT\n/g, "").replace("END:VCALENDAR", Array.from({ length: 25 }, (_, i) => block.replace("8000-000000000001", "8000-" + String(i + 1).padStart(12, "0"))).join("") + "END:VCALENDAR"); const r = brief(core(), calendar(many), at); ok(r.text.includes("Upcoming within seven days from the calendar check: 25; shown: 20.")); eq(r.text.split("| Producer Price Index |").length - 1, 20); });
test("failed latest calendar displays last-known clock but no old upcoming list", () => { const c = calendar(); if (c.state !== "AVAILABLE") throw Error("fixture"); const failed = { ...c, checkedAt: later, inputs: [...c.inputs, { requestedAt: later, receivedAt: later, url: RELEASE_CALENDAR_URL, sourceText: null, errorCode: "NETWORK_FAILED" as const }] }; const r = brief(core(), failed, later); ok(r.text.includes("Last-known calendar exists from " + at)); ok(!r.text.includes("Producer Price Index")); });
test("empty history has unknown calendar attempt and zero known upcoming events", () => { const r = brief(core(), { state: "AVAILABLE", checkedAt: at, errorCode: null, inputs: [] }, at); ok(r.text.includes("Latest attempt: NOT_REFRESHED")); ok(r.text.includes("Calendar absence does not mean cancellation")); });
test("historical candidate counts never combine with simulated-account compounding", () => { const r = brief(core(), calendar(), at); ok(r.text.includes("Independent research accounts are not compounded together")); ok(r.text.includes("Candidates are not approved knowledge or established causes")); ok(r.text.includes("Paper scenario clocks are not actual brokerage trade times")); });
test("stale BTC midpoint stays labeled as a saved observation", () => { const btc = createBtcReadinessEvidence([{ requestedAt: "2026-09-07T04:00:01.000Z", receivedAt: "2026-09-07T04:00:01.000Z", url: BTC_CONTEXT_URL, sourceText: book, errorCode: null }], at); const { btc: _, ...base } = core().evidence; const v2 = buildOptionsContextReadiness(buildOptionsReadiness("brief-study", base, at), btc, at); const r = brief(v2, calendar(), at); ok(r.text.includes("display fresh at check: false")); ok(r.text.includes("Observed midpoint USD: 80000.005")); ok(r.text.includes("Single-venue saved observation")); });
test("component clocks remain distinct from the final brief timestamp", () => { const r = brief(core(), { ...calendar(), checkedAt: later }, later); eq(r.assessedAt, later); eq(r.coreAssessedAt, at); eq(r.calendarCheckedAt, later); ok(r.text.includes("Readiness v2 checked: " + at)); });
test("result is immutable, repeatable and has no execution or collection permission", () => { const c = core(), cal = calendar(), before = JSON.stringify([c, cal]), r = brief(c, cal, at); eq(r, brief(c, cal, at)); eq(JSON.stringify([c, cal]), before); ok(Object.isFrozen(r)); eq(r.executionAllowed, false); eq(r.networkAccess, false); eq(r.reportFilesCreated, false); ok(r.text.includes("NO_REPLAY")); ok(r.text.includes("Win probability: unknown")); });
console.log(`${passed}/${passed} tests passed.`);
