import { NewsSourceTier } from "../../contracts/OptionsNewsDomain";
import { NewsNetworkAuthority, NewsSourceEligibility, OPTIONS_NEWS_SOURCE_REGISTRY_VERSION, type NewsSourceRegistration } from "../../contracts/OptionsNewsSourceRegistry";

const common = { registryVersion: OPTIONS_NEWS_SOURCE_REGISTRY_VERSION, independenceGroupingRule: "UPSTREAM_ORIGIN_OR_PUBLISHER" as const, eligibility: NewsSourceEligibility.Eligible, costPerRequestMinorUnits: 0, credentialsRequiredForLive: false, liveNetworkAuthority: NewsNetworkAuthority.Blocked, effectiveFromUtc: "2026-08-08T00:00:00.000Z", effectiveToUtc: null, provenance: "docs/specifications/OPTIONS_NEWS_INFRASTRUCTURE.md#source-registry" };

export const OPTIONS_NEWS_SOURCE_REGISTRATIONS: readonly NewsSourceRegistration[] = [
  { ...common, sourceId: "source:sec-edgar", providerId: "provider:sec-edgar", publisherId: "publisher:sec", tier: NewsSourceTier.Tier0, sourceFamily: "SEC_EDGAR", originalSourceId: "publisher:sec", syndicationLineage: [], supportedEventTypes: ["SEC_FILING"], supportedTopics: ["TECH"], rateLimitDescription: "Fixture-only; no live request authority." },
  { ...common, sourceId: "source:federal-reserve", providerId: "provider:federal-reserve", publisherId: "publisher:federal-reserve", tier: NewsSourceTier.Tier0, sourceFamily: "FEDERAL_RESERVE", originalSourceId: "publisher:federal-reserve", syndicationLineage: [], supportedEventTypes: ["FOMC_RATE_DECISION"], supportedTopics: ["TREASURY","GOLD"], rateLimitDescription: "Fixture-only; no live request authority." },
  { ...common, sourceId: "source:finnhub-reuters", providerId: "provider:finnhub", publisherId: "publisher:reuters", tier: NewsSourceTier.Tier1, sourceFamily: "REUTERS_WIRE", originalSourceId: "publisher:reuters", syndicationLineage: ["provider:finnhub","publisher:reuters"], supportedEventTypes: ["CORPORATE_NEWS"], supportedTopics: ["TECH"], rateLimitDescription: "Fixture metadata only; future paid/live use requires Owner approval.", credentialsRequiredForLive: true },
  { ...common, sourceId: "source:alpha-vantage-reuters", providerId: "provider:alpha-vantage", publisherId: "publisher:reuters", tier: NewsSourceTier.Tier1, sourceFamily: "REUTERS_WIRE", originalSourceId: "publisher:reuters", syndicationLineage: ["provider:alpha-vantage","publisher:reuters"], supportedEventTypes: ["CORPORATE_NEWS"], supportedTopics: ["TECH"], rateLimitDescription: "Fixture metadata only; future paid/live use requires Owner approval.", credentialsRequiredForLive: true },
];
