import { readFileSync } from "node:fs";
import { assessTreasuryRetrieval as assess, reportTreasuryHistory as report, treasuryUrl, treasurySha, type TreasuryInput } from "./TreasuryRealYieldEngine";

const xml = readFileSync("fixtures/options-treasury/real-yields.synthetic.xml", "utf8");
const at = "2026-09-07T03:00:00.000Z", later = "2026-09-07T04:00:00.000Z";
function input(sourceText = xml, requestedAt = at, receivedAt = at): TreasuryInput { return { requestedAt, receivedAt, url: treasuryUrl(requestedAt), sourceText, errorCode: null }; }
const empty = xml.replace(/<entry>[\s\S]*?<\/entry>/g, "");
const eq = (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw Error(`Expected ${JSON.stringify(b)}; received ${JSON.stringify(a)}`); };
const ok = (value: unknown) => { if (!value) throw Error("Expected truthy value"); };
function throws(work: () => unknown, code = "TREASURY_") { let error; try { work(); } catch (e) { error = e; } if (!(error instanceof Error) || !error.message.includes(code)) throw Error("Expected " + code); }
let passed = 0;
function test(name: string, work: () => void) { work(); passed++; console.log(`PASS ${name}`); }
test("exact hundredths, negative yields and nulls preserve units", () => { const r = assess(input()); eq(r.rows[0]!.ratesBps, { 5: -12, 7: 0, 10: 200, 20: 250, 30: null }); eq(r.rows[1]!.ratesBps[30], 311); });
test("source date and updated clocks remain separate from actual retrieval", () => { const r = assess(input()); eq(r.rows[0]!.sourceDate, "2026-09-03"); eq(r.feedUpdatedAt, "2026-09-06T02:00:00.000Z"); eq(r.receivedAt, at); eq(r.sourceSha256, treasurySha(xml)); });
test("current-month URL follows New York across UTC month and DST boundaries", () => { ok(treasuryUrl("2026-10-01T03:59:59.000Z").endsWith("202609")); ok(treasuryUrl("2026-10-01T04:00:00.000Z").endsWith("202610")); ok(treasuryUrl("2026-02-01T04:59:59.000Z").endsWith("202601")); });
test("an empty schema-valid feed is explicit EMPTY", () => { const r = assess(input(empty)); eq(r.status, "EMPTY"); eq(r.rows, []); });
test("sorts source dates without assuming source order is chronological", () => { const entries = xml.match(/<entry>[\s\S]*?<\/entry>/g)!; const reversed = empty.replace("</feed>", [...entries].reverse().join("") + "</feed>"); eq(assess(input(reversed)).rows, assess(input()).rows); });
test("strict namespaces and dataset reject lookalike feeds", () => { for (const s of [xml.replace("http://www.w3.org/2005/Atom", "https://other.invalid"), xml.replace("DailyTreasuryRealYieldCurveRateData</title>", "Other</title>"), xml.replace("<entry>", '<entry xmlns:d="other">')]) throws(() => assess(input(s))); });
test("DTD, entities, processing instructions and CDATA are never interpreted", () => { for (const s of ["<!DOCTYPE feed>" + xml, xml.replace("synthetic-feed", "&secret;"), xml.replace("<entry>", "<?execute test?><entry>"), xml.replace("synthetic-feed", "<![CDATA[text]]>")]) throws(() => assess(input(s))); });
test("well-formed nesting, one root and complete entries are required", () => { for (const s of [xml.replace("</entry>", ""), xml + "<feed/>", xml.replace("</m:properties>", "</content>"), xml.replace("</feed>", ""), xml + "trailing"]) throws(() => assess(input(s))); });
test("duplicate fields and unknown data fields cannot silently disappear", () => { const field = '<d:TC_5YEAR m:type="Edm.Double">-0.12</d:TC_5YEAR>'; for (const s of [xml.replace(field, field + field), xml.replace(field, ""), xml.replace(field, field + "<d:EXTRA>1</d:EXTRA>")]) throws(() => assess(input(s))); });
test("duplicate attribute names and namespace shadowing fail", () => { for (const s of [xml.replace('m:type="Edm.Double"', 'm:type="Edm.Double" m:type="Edm.Double"'), xml.replace("<m:properties>", '<m:properties xmlns:m="other">')]) throws(() => assess(input(s))); });
test("types and leaf structure must match the reviewed source", () => { for (const s of [xml.replace('m:type="Edm.Double"', 'm:type="Edm.String"'), xml.replace("-0.12", "<n>-0.12</n>")]) throws(() => assess(input(s))); });
test("null cannot carry a number and false null is not silently coerced", () => { for (const s of [xml.replace('m:null="true" />', 'm:null="false" />'), xml.replace('m:null="true" />', 'm:null="true">0</d:TC_30YEAR>')]) throws(() => assess(input(s)), "NULL_RATE"); });
test("precise zero is distinct from null and negative zero is normalized", () => { const r = assess(input(xml.replace("-0.12", "-0.00"))); eq(r.rows[0]!.ratesBps[5], 0); eq(Object.is(r.rows[0]!.ratesBps[5], -0), false); });
test("exponents, excess precision, NaN and decorations fail visibly", () => { for (const rate of ["NaN", "Infinity", "1e2", "0.123", "2.00%", "+2.00", "100000.00"]) throws(() => assess(input(xml.replace("-0.12", rate))), "RATE_FORMAT"); });
test("source dates must be canonical real dates and in the requested month", () => { for (const date of ["2026-09-31T00:00:00", "2026-08-31T00:00:00", "2026-09-03T01:00:00", "2026-9-3T00:00:00", "2026-09-30T00:00:00"]) throws(() => assess(input(xml.replace("2026-09-03T00:00:00", date)))); });
test("duplicate daily IDs and dates fail", () => { for (const s of [xml.replace('>2</d:DailyTreasury', '>1</d:DailyTreasury'), xml.replace("2026-09-04T00:00:00", "2026-09-03T00:00:00")]) throws(() => assess(input(s)), "DUPLICATE_ROW"); });
test("source timestamps cannot exceed actual receipt or feed metadata", () => { throws(() => assess(input(xml.replace("2026-09-06T02:00:00Z", "2026-09-08T02:00:00Z"))), "SOURCE_CLOCK"); throws(() => assess(input(xml.replace("<updated>2026-09-06T02:00:00Z</updated>", "<updated>2026-09-05T02:00:00Z</updated>"))), "SOURCE_CLOCK"); });
test("exact retrieval shape, URL scope and canonical clocks are enforced", () => { for (const value of [{ ...input(), url: "https://example.com" }, { ...input(), requestedAt: "2026-09-31T00:00:00.000Z" }, { ...input(), receivedAt: "2026-09-06T00:00:00.000Z" }, { ...input(), extra: true }]) throws(() => assess(value)); });
test("bounded raw text and row count reject oversized sources", () => { throws(() => assess(input(" ".repeat(524289))), "BODY_TOO_LARGE"); throws(() => assess(input(empty.replace("</feed>", xml.match(/<entry>[\s\S]*?<\/entry>/)![0].repeat(32) + "</feed>"))), "ROW_LIMIT"); });
test("XML invalid scalar characters and unknown entities fail", () => { for (const text of ["\u0000", "\ud800", "&#0;", "&#xD800;", "&#1114112;", "&oops;"]) throws(() => assess(input(xml.replace("synthetic-feed", text)))); });
test("escaped metadata is inert and source parser cannot authenticate it", () => { const r = report([input(xml.replace("synthetic-feed", "&lt;instructions&gt;no&lt;/instructions&gt;"))], at); eq(r.sourceAuthenticatedByParser, false); eq(r.executionAllowed, false); });
test("consecutive observed date changes and slope use exact basis points", () => { const r = report([input()], at); eq(r.comparison.changesBps, { 5: 2, 7: 1, 10: -10, 20: 10, 30: null }); eq(r.tenMinusFiveYearSlopeBps, 200); eq(r.currentDateLagDays, 2); });
test("missing latest tenors stay missing without using previous values", () => { const r = report([input(xml.replace('<d:TC_10YEAR m:type="Edm.Double">1.90</d:TC_10YEAR>', '<d:TC_10YEAR m:type="Edm.Double" m:null="true" />'))], at); eq(r.missingTenors, [10]); eq(r.comparison.changesBps[10], null); eq(r.tenMinusFiveYearSlopeBps, null); });
test("failure health cannot promote older values to current", () => { const failure: TreasuryInput = { ...input(xml, later, later), sourceText: null, errorCode: "NETWORK_FAILED" }; const r = report([input(), failure], later); eq(r.latestRetrieval!.status, "FAILED"); eq(r.currentRow, null); eq(r.lastKnownObservation!.fromLatestRetrieval, false); eq(r.healthChange, "CHANGED"); });
test("empty retrieval cannot promote older values to current", () => { const r = report([input(), input(empty, later, later)], later); eq(r.currentRow, null); eq(r.lastKnownObservation!.row.sourceDate, "2026-09-04"); eq(r.latestRetrieval!.status, "EMPTY"); });
test("initial report has unknown values and no invented observations", () => { const r = report([], at); eq(r.currentRow, null); eq(r.retrievalCount, 0); eq(r.versions, []); eq(r.currentDateLagDays, null); eq(r.lastKnownObservation, null); });
test("repeat observations do not create fictitious new versions", () => { const r = report([input(), input(xml, later, later)], later); eq(r.versions.length, 2); eq(r.versions[0]!.firstObservedAt, at); eq(r.healthChange, "UNCHANGED"); });
test("A to B to A revisions preserve actual observation clocks", () => { const third = "2026-09-07T05:00:00.000Z"; const r = report([input(), input(xml.replace("1.90", "1.91"), later, later), input(xml, third, third)], third); eq(r.versions.length, 4); eq(r.versions[2]!.firstObservedAt, later); eq(r.versions[3]!.firstObservedAt, third); eq(r.versions[3]!.valueSha256, r.versions[1]!.valueSha256); });
test("metadata updates alone are not rate revisions", () => { const r = report([input(), input(xml.replaceAll("2026-09-06T02:00:00Z", "2026-09-06T03:00:00Z"), later, later)], later); eq(r.versions.length, 2); });
test("overlapping, backward and future receipt histories are rejected", () => { throws(() => report([input(xml, later, later)], at), "HISTORY_CLOCK"); throws(() => report([input(xml, at, later), input()], later), "HISTORY_CLOCK"); });
test("failures keep only fixed error codes and cannot include source bodies", () => { throws(() => assess({ ...input(), errorCode: "NETWORK_FAILED" }), "SOURCE_ERROR_SHAPE"); throws(() => assess({ ...input(), sourceText: null, errorCode: "private" as any }), "ERROR_CODE"); });
test("report and nested source values are immutable and deterministic", () => { const r = report([input()], at); eq(r, report([input()], at)); ok(Object.isFrozen(r.currentRow!.ratesBps)); ok(Object.isFrozen(r.versions)); eq(r.winProbability, null); eq(r.strategySignal, null); eq(r.historicalPublicationTimesKnown, false); });
console.log(`${passed}/${passed} tests passed.`);
