import {esc,words,cents,timestamp} from './model.js';
const money=n=>n===null||n===undefined?'Unknown':cents(n);
const tag=status=>'<span class="tag '+(status==='PASS'?'green':status==='UNKNOWN'?'blue':'amber')+'">'+esc(words(status))+'</span>';
export function filterCandidateChecks(rows,{asset='',budget='all'}={}){
  return rows.filter(r=>(!asset||r.contract.symbol===asset)&&(budget==='all'||budget==='within'&&r.premiumWithinBudget===true||budget==='over'&&(r.budgetPosition?r.budgetPosition==='OVER':r.premiumWithinBudget===false)||budget==='below'&&r.budgetPosition==='BELOW'||budget==='unknown'&&r.premiumWithinBudget===null));
}
export function candidateCheckDetail(row,report){
  const q=row.contract;
  return '<p><strong>'+esc(`${q.symbol} ${q.expiry} ${q.strike} ${q.type.toUpperCase()}`)+'</strong> · '+esc(words(row.disposition))+'</p>'+
    '<p class="hint">Source refresh '+esc(timestamp(q.updatedAt))+' · Receipt '+esc(timestamp(q.receivedAt))+' · Assessed '+esc(timestamp(report.assessedAt))+'</p>'+
    '<p>Per-share bid '+money(q.bidCents)+' / ask '+money(q.askCents)+'. One standard contract represents 100 shares. Passing a local check does not establish an executable quote.</p>'+
    '<div class="candidate-check-list">'+row.checks.map(c=>'<section class="candidate-check"><div class="status-line"><h3>'+esc(c.label)+'</h3>'+tag(c.status)+'</div><p>'+esc(c.explanation)+'</p>'+(c.status!=='PASS'?'<p><strong>Next:</strong> '+esc(c.nextAction)+'</p>':'')+(c.reasons.length?'<p class="hint">'+c.reasons.map(b=>esc(words(b))).join(' · ')+'</p>':'')+'</section>').join('')+'</div>'+
    '<div class="notice"><div><strong>Paper source qualification is not established.</strong><ul>'+report.qualification.requirements.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></div></div>'+
    '<details><summary>Original blockers, economics and source references</summary><pre>'+esc(JSON.stringify({contract:q,assessedAt:report.assessedAt,capturedAt:report.capturedAt,originalBlockers:row.originalBlockers,economics:row.economics,plan:row.plan,sourcePaths:report.sourcePaths,originalGuidanceFingerprint:report.originalGuidanceFingerprint},null,2))+'</pre></details>';
}
export function candidateChecksPanel(component,ui={}){
  const v=component?.data,r=v?.current;
  if(!r)return '<section class="card section-space"><h2>Candidate checks</h2><p>Unavailable: '+esc(component?.error??'No saved inputs')+'. Other source evidence remains separate.</p></section>';
  const filter=ui.candidateCheckFilter??{},rows=filterCandidateChecks(r.rows,filter),c=r.counts;
  return '<section class="card section-space candidate-checks-panel"><div class="card-head"><div><p class="eyebrow">FROM QUOTES TO A REVIEWABLE PLAN</p><h2>Candidate checks</h2><p>Check each sampled contract against separate budget, risk and evidence requirements.</p></div><button class="button secondary" id="save-candidate-checks"'+(ui.guidanceSettingsDraft?' disabled':'')+'>Save current check snapshot</button></div>'+
    '<p><strong>'+c.premiumWithinBudget+(r.settings.tradeBudget?' within the premium range':' premium-affordable')+'</strong> · '+c.premiumOverBudget+' over the premium budget'+(r.settings.tradeBudget?' · '+c.premiumBelowBudget+' below the range':'')+' · '+c.premiumUnknown+' unknown · '+c.conditionalResearch+' conditional research / '+c.sampled+' sampled. Affordability excludes costs and does not mean the risk checks passed.</p>'+
    (r.settings.tradeBudget?'<p><strong>Per-trade range: '+money(r.settings.tradeBudget.minCents)+'–'+money(r.settings.tradeBudget.maxCents)+'.</strong> The capital check includes declared fees. Planned loss stays capped at 0.5% of equity and full-premium stress at $25; the minimum is a selection preference, never an instruction to spend more.</p>':'')+
    '<p class="hint">'+esc(r.scope)+' Assessed '+esc(timestamp(r.assessedAt))+'.</p>'+
    (ui.guidanceSettingsDraft?'<div class="notice"><div>Your unsaved planning assumptions are preserved. Save or discard them before saving a check snapshot.</div></div>':'')+
    '<div class="candidate-check-filters"><label>Asset<select id="candidate-check-asset">'+[['','Both ETFs'],['GLD','GLD'],['IBIT','IBIT']].map(([v,l])=>'<option value="'+v+'"'+((filter.asset??'')===v?' selected':'')+'>'+l+'</option>').join('')+'</select></label><label>Premium budget<select id="candidate-check-budget">'+[['all','All candidates'],['within',r.settings.tradeBudget?'Within premium range':'Within premium budget'],['over','Over premium budget'],...(r.settings.tradeBudget?[['below','Below premium range']]:[]),['unknown','Unknown premium']].map(([v,l])=>'<option value="'+v+'"'+((filter.budget??'all')===v?' selected':'')+'>'+l+'</option>').join('')+'</select></label><p class="hint">Showing '+rows.length+' / '+c.sampled+'. This filter never changes a decision.</p></div>'+
    (rows.length?'<div class="table-scroll"><table><thead><tr><th>Contract</th><th>Premium / allocation ceiling</th><th>Planned loss / risk budget</th><th>Stress loss / cap</th><th>Decision</th><th>Evidence</th></tr></thead><tbody>'+rows.map(row=>{const q=row.contract,e=row.economics;return '<tr><td>'+esc(q.symbol+' '+q.expiry)+'<small>'+esc(q.strike+' '+q.type.toUpperCase())+'</small></td><td>'+money(e?.premiumCents)+' / '+money(e?.applicableAllocationBudgetCents)+'</td><td>'+money(e?.plannedStopCents)+' / '+money(e?.plannedRiskBudgetCents)+'</td><td>'+money(e?.stressLossCents)+' / '+money(e?.legacyNormalMaxLossCents)+'</td><td>'+esc(words(row.disposition))+'<small>'+row.originalBlockers.length+' original blocker(s)</small></td><td><button class="button secondary small" data-candidate-check="'+esc(q.id)+'">Inspect checks</button></td></tr>';}).join('')+'</tbody></table></div>':'<div class="notice"><div>No candidates match this filter. The sample and all excluded candidates remain available under All candidates; no substitute or trade has been created.</div></div>')+
    '<p><strong>Source qualification remains open.</strong> These checks cannot enable paper fills or orders. Costs and account values below are declared scenarios, and stop triggers do not guarantee an exit price.</p>'+
    '<details><summary>Saved check snapshots ('+v.history.length+')</summary>'+(v.history.length?'<ul>'+v.history.map(h=>'<li>'+esc(timestamp(h.recordedAt))+' · '+h.counts.sampled+' sampled · '+h.counts.conditionalResearch+' conditional<small>'+esc(h.path)+'</small></li>').join('')+'</ul>':'<p>No check snapshot saved. Reading this page does not write one.</p>')+'</details></section>';
}
