import {esc,cents} from './model.js';

export function costDeskControls(basis='DECLARED_FEES'){
  return `<label class="form-field">Cost comparison fee basis<select id="cost-fee-basis"><option value="DECLARED_FEES"${basis==='DECLARED_FEES'?' selected':''}>Use declared fees (blank stays unknown)</option><option value="REVIEWED_SCHEDULE_ASSUMPTION"${basis==='REVIEWED_SCHEDULE_ASSUMPTION'?' selected':''}>Assume reviewed nonprofessional, single-fill rates</option></select><small>Comparison only. Your original plan and saved guidance costs stay unchanged.</small></label><button type="button" class="button secondary" id="compare-costs">Compare fees & exit allowances</button><p id="cost-desk-error" class="error-text" role="alert"></p>`;
}
export function costDeskResult(r){
  if(!r)return '<p class="hint">Enter the planner bid, ask and quantity, then compare 0, 1, 2 and 5 ticks of adverse exit allowance. Calculations use the declared quote tick. No default fee or slippage is assumed.</p>';
  const original=r.original.scenario,removed=original.tradeBudget?.version==='OWNER_ALLOCATION_ONLY_V2';
  return `<p>Original fees: <strong>${cents(original.roundTripFeesCents)}</strong> · original exit allowance: <strong>${cents(original.slippageReserveCents)}</strong>.</p><p class="hint">${r.profile?'Reviewed-rate assumption · '+esc(r.profile.reviewedAt)+'. One buy and one sell execution; account status and actual charges are unverified.':'Uses your declared total round-trip fees. Missing fees remain unknown.'} Each comparison replaces the exit allowance; it does not add another spread charge.</p><div class="table-scroll"><table><thead><tr>${['Exit allowance','Fee reserve','Planned loss / R','Net target','Exit / share','Risk headroom','Assessment'].map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${r.rows.map(row=>{const e=row.result.economics;return `<tr><td>${row.ticks} ${row.ticks===1?'tick':'ticks'}<small>${cents(row.exitAllowanceCents)}</small></td><td>${cents(row.roundTripFeeReserveCents)}</td><td>${cents(e.plannedStopCents)}</td><td>${cents(e.roundedNetProfitTargetCents)}</td><td>${cents(e.indicativeExitLimitPerShareCents)}</td><td>${removed?'Not capped':cents(row.plannedRiskHeadroomCents)}</td><td><strong>${row.result.status==='NO_TRADE'?'Blocked':'Scenario only'}</strong><details><summary>Reasons & calculation</summary><ul class="rule-list">${row.result.blockers.map(b=>`<li>${esc(b.message)}</li>`).join('')}</ul><pre class="json-detail">${esc(JSON.stringify(row,null,2))}</pre></details></td></tr>`;}).join('')}</tbody></table></div><p class="hint">Net targets include fees and the stated allowance. Indicative prices and stops are not guaranteed fills. ${removed?'Legacy planned-loss and full-premium caps are removed. Review the displayed loss and full-premium exposure.':'Negative headroom exceeds the independent 0.5% planned-loss cap; the $25 full-premium cap also remains.'}</p><details><summary>Cost assumptions, sources & exact evidence</summary>${r.profile?'<ul>'+r.profile.sources.map((url,i)=>`<li><a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${i?'Robinhood trading fees':'Robinhood fee schedule'}</a></li>`).join('')+'</ul>':''}<ul>${r.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><pre class="json-detail">${esc(JSON.stringify(r,null,2))}</pre></details>`;
}
/** Compare the complete request, including the fee choice and inherited budget. */
export function costRequestMatches(request,current){return JSON.stringify(request)===JSON.stringify(current);}
