import {esc,words,cents,timestamp} from './model.js';
const list=xs=>'<ul>'+xs.map(x=>'<li>'+esc(words(x))+'</li>').join('')+'</ul>';
export function etfSourceAuditPanel(audit){
  if(!audit)return '';
  return '<div class="section-space etf-source-audit"><h3>ETF source consistency audit</h3><p>'+esc(audit.meaning)+'</p><p class="hint">Window '+esc(timestamp(audit.windowStart))+' – '+esc(timestamp(audit.windowEnd))+'<br>Five-minute request / receipt: '+esc(timestamp(audit.fiveMinuteClock.requestedAt))+' / '+esc(timestamp(audit.fiveMinuteClock.receivedAt))+'<br>One-minute request / receipt: '+esc(timestamp(audit.minuteClock.requestedAt))+' / '+esc(timestamp(audit.minuteClock.receivedAt))+'</p><div class="grid-two">'+audit.assets.map(a=>
    '<article class="decision-reference"><h4>'+esc(a.symbol)+' · '+esc(words(a.status))+'</h4><p>'+esc(a.matching)+' matching · '+esc(a.different)+' different · '+esc(a.notComparable)+' not comparable five-minute bars.</p><p class="hint">Received '+esc(a.returnedMinuteBars)+' / '+esc(a.expectedMinuteBars)+' minute bars. Unknown interpolation: '+esc(a.unknownFiveMinuteFlags)+' five-minute / '+esc(a.unknownMinuteFlags)+' minute bars.</p>'+list(a.qualityBlockers)+
    (a.different?'<details data-disclosure-key="etf-audit-'+esc(a.symbol)+'"><summary>Inspect '+esc(a.differingFields)+' field differences</summary><div class="table-scroll"><table><thead><tr><th>Bar start</th><th>Field</th><th>Five-minute source</th><th>One-minute aggregate</th></tr></thead><tbody>'+a.rows.flatMap(r=>r.differences.map(d=>'<tr><td>'+esc(timestamp(r.start))+'</td><td>'+esc(words(d.field))+'</td><td>'+esc(d.fiveMinute)+'</td><td>'+esc(d.minuteAggregate)+'</td></tr>')).join('')+'</tbody></table></div></details>':'')+'</article>').join('')+'</div><p class="notice">'+esc(audit.nextAction)+'</p><details data-disclosure-key="etf-audit-support"><summary>Questions for the data provider — draft, not sent</summary><ol>'+audit.supportQuestions.map(q=>'<li>'+esc(q)+'</li>').join('')+'</ol><p class="hint">Keep both source receipts and the exact difference table. Cause, flag defaults and source qualification remain unconfirmed.</p></details></div>';
}
export function etfSourcePanel(assets=[]){
  if(!assets.length)return '';
  return '<div class="section-space"><h3>Robinhood ETF price observations</h3><p>Historical window, not a live trend signal. Missing interpolation flags stay unknown even when volume is positive. Bar closes are not official daily closes.</p><div class="grid-two">'+assets.map(a=>{
    const o=a.observations;
    return '<article class="decision-reference"><h4>'+esc(a.symbol)+' · '+esc(words(a.status))+'</h4><p>'+a.returnedBars+' / '+a.expectedBars+' requested bars · '+a.unknownInterpolation+' unknown interpolation flags</p><p class="hint">Window '+esc(timestamp(a.windowStart))+' – '+esc(timestamp(a.windowEnd))+'<br>Requested '+esc(timestamp(a.requestedAt))+' · received '+esc(timestamp(a.receivedAt))+'</p>'+
      (o?'<dl class="metric-list"><dt>First bar open</dt><dd>$'+esc(o.firstBarOpen)+'</dd><dt>Last bar close</dt><dd>$'+esc(o.lastBarClose)+'</dd><dt>Window high / low</dt><dd>$'+esc(o.high)+' / $'+esc(o.low)+'</dd><dt>Reported share volume</dt><dd>'+esc(o.volume.toLocaleString('en-US'))+'</dd><dt>Open-to-last change</dt><dd>'+esc((o.openToLastCloseBps/100).toFixed(2))+'% · '+esc(words(o.direction))+'</dd></dl><p class="hint">'+esc(o.meaning)+'</p>':'<p>Summary unavailable because structural checks failed.</p>')+list(a.blockers)+
      '<p class="hint">Saved response, unqualified export. No rule or trade was created.</p><details data-disclosure-key="etf-source-'+esc(a.symbol)+'"><summary>Inspect received bars and quality</summary><div class="table-scroll"><table><thead><tr><th>Bar start</th><th>Open / high / low / close (USD)</th><th>Shares</th><th>Quality</th></tr></thead><tbody>'+a.rows.map(r=>'<tr><td>'+esc(r.bar?timestamp(r.bar.start):r.sourceStart??'Unknown')+'</td><td>'+esc(r.bar?[r.bar.open,r.bar.high,r.bar.low,r.bar.close].join(' / '):'Invalid')+'</td><td>'+esc(r.bar?.volume??'Unknown')+'</td><td>'+esc(r.issues.length?r.issues.map(words).join('; '):'Local shape checks passed; provenance unqualified')+'</td></tr>').join('')+'</tbody></table></div></details></article>';
  }).join('')+'</div></div>';
}
export function etfSetupRequest(f){
  const stamp=v=>{const d=new Date(v);if(!v||!Number.isFinite(d.getTime()))throw Error('Choose valid activation and exit times.');return d.toISOString();};
  const n=k=>{const v=Number(f[k]);if(!Number.isSafeInteger(v))throw Error('Use whole numbers for '+k+'.');return v;};
  return {version:'OPTIONS_ETF_SETUP_PLAN_V1',id:f.id,symbol:f.symbol,side:f.side,setup:f.setup,activeFrom:stamp(f.activeFrom),timeExit:stamp(f.timeExit),lower:f.lower,upper:f.upper,invalidation:f.invalidation,
    fastBars:n('fastBars'),slowBars:n('slowBars'),bufferBps:n('bufferBps'),chaseBps:n('chaseBps'),volumeRatioBps:n('volumeRatioBps'),expiryBufferDays:n('expiryBufferDays'),targetDeltaBps:n('targetDeltaBps')};
}
export function etfSetupPanel(component,ui={}){
  if(!component?.data)return '<section class="card section-space"><h2>ETF trend → contract research</h2><p>'+esc(component?.error??'Research desk unavailable.')+'</p></section>';
  const desk=component.data,d=ui.etfSetupDraft??{};
  const field=(name,label,type='text',value='')=>'<label>'+esc(label)+'<input name="'+name+'" type="'+type+'" value="'+esc(d[name]??value)+'" required></label>';
  const select=(name,label,options)=>'<label>'+label+'<select name="'+name+'">'+options.map(([v,l])=>'<option value="'+v+'"'+((d[name]??options[0][0])===v?' selected':'')+'>'+l+'</option>').join('')+'</select></label>';
  return '<section class="card section-space" id="etf-setup-desk"><div class="card-head"><div><h2>ETF trend → contract research</h2><p>Declare the rule first, inspect completed ETF bars, then compare contracts.</p></div><span class="tag amber">Research only</span></div>'+
    '<p class="notice">'+esc(desk.sourceCapability)+'</p>'+etfSourceAuditPanel(desk.sourceAudit)+etfSourcePanel(desk.sourceAssets)+'<p>Research matches never override Today’s decision. No automatic orders or calibrated win rate.</p><div class="grid-two">'+desk.assets.map(a=>
      '<article class="decision-reference"><h3>'+esc(a.symbol)+' · '+esc(words(a.status))+'</h3><p>Trend: <strong>'+esc(words(a.trend.direction))+'</strong> · fast '+esc(a.trend.fastMean??'Unknown')+' / slow '+esc(a.trend.slowMean??'Unknown')+'</p><p>Approximate bar VWAP: '+esc(a.trend.approximateBarVwap??'Unknown')+'</p><p class="hint">'+esc(a.trend.meaning)+'</p>'+
      (a.source?'<p>'+a.source.barCount+' bars · '+esc(a.source.reference)+'<br>Window '+esc(timestamp(a.source.windowStart))+' – '+esc(timestamp(a.source.windowEnd))+'<br>Received '+esc(timestamp(a.source.receivedAt))+' · Imported, unverified</p>':desk.sourceAssets?.some(s=>s.symbol===a.symbol)?'<p>No validated ETF bars installed for this setup. Review source quality above.</p>':'<p>No ETF OHLCV evidence saved.</p>')+
      (a.plan?'<p>Frozen '+esc(a.plan.id)+' · '+esc(words(a.plan.setup))+' · '+esc(words(a.plan.side))+'<br>Trigger $'+esc(a.triggerPrice??'Unknown')+' · first match '+esc(timestamp(a.triggerAt))+'<br>Invalidated '+esc(timestamp(a.invalidatedAt))+' · exit '+esc(timestamp(a.plan.timeExit))+'</p><button class="button secondary small" data-etf-snapshot="'+esc(a.plan.id)+'">Save current assessment</button>':'<p>No prospective rule registered.</p>')+list(a.gaps)+list(a.limitations)+
      (a.rows.length?'<details data-disclosure-key="etf-contracts-'+esc(a.symbol)+'"><summary>Why these expiries and strikes? '+a.rows.length+' contracts</summary><p>Ordered by mechanical eligibility, delta distance, expiry distance, spread and ID. This is not a profit ranking.</p>'+a.rows.map(r=>'<div class="decision-reference"><strong>'+esc(r.contract.expiry+' · $'+r.contract.strike+' '+r.contract.type.toUpperCase())+'</strong><p>Ask '+(r.contract.askCents===null?'Unknown':cents(r.contract.askCents))+' / share</p><p>'+esc(r.rationale.expiry)+'</p><p>'+esc(r.rationale.strike)+'</p><p>'+esc(r.rationale.cost)+'</p>'+list(r.blockers)+'<button class="button secondary small" data-guidance-plan="'+esc(r.contract.id)+'">Inspect original checks</button></div>').join('')+'</details>':'')+'</article>').join('')+'</div>'+
    '<details data-disclosure-key="etf-plan-form"><summary>Declare a future research rule</summary><p>Defaults are explicit, untested assumptions. Declare ETF levels before the window. Times use your device timezone; both times must be in one New York regular session.</p><form id="etf-setup-form" class="form-grid">'+
      field('id','Rule name (lowercase letters, numbers, hyphens)')+select('symbol','ETF',[['GLD','GLD'],['IBIT','IBIT']])+select('side','Scenario',[['BULLISH','Bullish'],['BEARISH','Bearish']])+select('setup','Setup',[['BREAKOUT','Trend breakout'],['PULLBACK','Trend pullback'],['KEY_LEVEL','Key-level resolution']])+
      field('activeFrom','Activation (device time)','datetime-local')+field('timeExit','Time exit (device time)','datetime-local')+field('lower','Range / pullback zone lower (USD)')+field('upper','Range / pullback zone upper (USD)')+field('invalidation','ETF invalidation price (USD)')+
      [['fastBars','Fast mean bars',3],['slowBars','Slow mean / volume baseline bars',5],['bufferBps','Break buffer (10 = 0.10%)',10],['chaseBps','Maximum chase (50 = 0.50%)',50],['volumeRatioBps','Mean-volume ratio (12000 = 1.20×)',12000],['expiryBufferDays','Expiry buffer after exit (calendar days)',7],['targetDeltaBps','Absolute delta target (5000 = 0.50)',5000]].map(([k,l,v])=>field(k,l,'number',v)).join('')+'<div><button class="button primary" type="submit">Freeze local research rule</button></div></form></details>'+
    '<details data-disclosure-key="etf-import-form"><summary>Import normalized ETF evidence</summary><p>Use OPTIONS_ETF_BARS_V1 JSON with source, receipt, raw prices, share volume, five-minute grid and explicit completed/noninterpolated flags. Importing does not authenticate the claimed source.</p><form id="etf-bars-form" class="form-grid"><label>Evidence file<input type="file" name="bars" accept=".json,application/json" required></label><div><button class="button secondary" type="submit">Validate and save evidence</button></div></form></details>'+
    '<p id="etf-setup-error" class="error-text" role="alert"></p><p class="hint">'+desk.plans.length+' recent rules · '+desk.barImports.length+' recent imports · '+desk.snapshots.length+' recent saved assessments. Snapshots copy original guidance and evidence for recovery.</p></section>';
}
