import {esc,timestamp} from './model.js';
const field=(name,label,value='',hint='')=>`<label>${esc(label)}<input name="${esc(name)}" value="${esc(value)}" autocomplete="off"><small>${esc(hint)}</small></label>`;
const select=(name,label,value,choices)=>`<label>${esc(label)}<select name="${name}">${choices.map(v=>`<option value="${v}"${value===v?' selected':''}>${esc(v)}</option>`).join('')}</select></label>`;
export function predictionFields(f){return `<details data-disclosure-key="prediction-config"><summary>Prediction evidence to be locked with this plan</summary><p>Optional for legacy workflows. Choose an explicit ETF forecast to link the new frozen plan. Draft saves never create a Prediction Log entry. No confidence, strategy version or model score is invented.</p><div class="form-grid">${select('predictionDirection','Expected ETF direction',f.predictionDirection??'',['','UP','DOWN','NEUTRAL','RANGE_BOUND'])}${field('predictionOwner','Prediction author / Owner',f.predictionOwner)}${field('predictionCatalyst','Expected catalyst',f.predictionCatalyst)}${field('predictionAssumptions','Important assumptions',f.predictionAssumptions)}</div><p>Horizon and invalidation use the original thesis fields above. Confirm & freeze confirms this is before actual entry and before knowing the result, and locks the displayed prediction evidence. It does not grant trade permission.</p></details>`;}
export function predictionPreview(p){
  if(!p)return '<p>Prediction link not configured. This plan will retain the legacy, unlinked workflow.</p>';
  return `<div class="notice"><div><h3>Prediction evidence to be locked</h3><p>${esc(p.forecast.direction)} · ${esc(p.horizonStartAt)} – ${esc(p.horizonEndAt)}</p><p>Thesis: ${esc(p.statement)}<br>Catalyst: ${esc(p.forecast.catalyst)}<br>Assumptions: ${esc(p.forecast.assumptions)}</p><p>Confidence: Not recorded / not calibrated. Author: ${esc(p.forecast.owner)}<br>Strategy version: ${esc(p.strategyStatus)}</p><p>Expectation: ${esc(p.expectation?.fingerprint??'Not configured')}<br>Scenario / Assumption EV: ${esc(p.scenario?.fingerprint??'Not configured')}<br>Contract Fit snapshot: ${esc(p.contractFitFingerprint??'Not available')}<br>Invalidation: ${esc(p.thesisVersion)}</p><details><summary>Immutable references, original fit and source clocks</summary><pre>${esc(JSON.stringify(p,null,2))}</pre></details><p>The frozen plan and Prediction Log are separate writes. An interrupted write remains pending and must be resumed before entry or the result window.</p></div></div>`;
}
const buttons=(kind,p,d)=>`<div class="form-actions"><button class="button secondary" type="submit" value="PREVIEW">Preview ${kind.toLowerCase()}</button><button class="button primary" type="submit" value="SAVE"${p?'':' disabled'}>Confirm ${kind==='JOURNAL'?'& finalize journal':'& save '+kind.toLowerCase()}</button></div><label class="check-row"><input name="ownerConfirmed" type="checkbox"${d.ownerConfirmed==='on'?' checked':''}> I reviewed this evidence and confirm my own assessment; this is not machine authentication.</label>`;
function outcomeForm(row,d,p){return `<form data-evidence-form="OUTCOME" data-evidence-trade="${esc(row.tradeId)}"><div class="form-grid">${select('kind','Outcome evidence type',d.kind??'OWNER_QUALITATIVE',['OWNER_QUALITATIVE','EVENT_NUMERIC'])}${field('symbol','Original ETF (must match)',d.symbol??row.contract.symbol)}${field('source','Original source / evidence reference',d.source)}${field('sourceAt','Actual evidence / publication time (UTC ISO)',d.sourceAt)}${field('receivedAt','Actual receipt time (UTC ISO)',d.receivedAt)}${select('actualDirection','Observed ETF direction — Owner reviewed',d.actualDirection??'UNKNOWN',['UNKNOWN','UP','DOWN','NEUTRAL','RANGE_BOUND'])}${field('result','What happened within the original forecast scope?',d.result,'Do not use contract P&L as evidence of ETF forecast accuracy.')}</div><details><summary>Structured event fact (numeric events only)</summary><p>Use the existing event/metric/period/unit/vintage/source fields. A value is checked against the original condition; semantic correctness still requires Owner confirmation. For qualitative evidence leave blank.</p><label>Event evidence JSON<textarea name="eventEvidence">${esc(d.eventEvidence??'')}</textarea></label></details>${buttons('OUTCOME',p,d)}</form>`;}
function reviewForm(row,d,p){return `<form data-evidence-form="REVIEW" data-evidence-trade="${esc(row.tradeId)}"><div class="form-grid">${select('accuracy','Prediction accuracy — your review',d.accuracy??'INDETERMINATE',['INDETERMINATE','PARTIALLY_ACCURATE','ACCURATE','INACCURATE'])}${field('rationale','Direction, horizon, timing / magnitude and limitations',d.rationale,'Profitability is read independently from the manual ledger; no numerical score is inferred.')}</div>${buttons('REVIEW',p,d)}</form>`;}
function journalForm(row,d,p){return `<form data-evidence-form="JOURNAL" data-evidence-trade="${esc(row.tradeId)}"><div class="form-grid">${[['interpretation','Interpretation (not established cause)'],['assumptions','Assumptions that held / failed'],['uncertainty','Uncertainty / missing evidence'],['rationale','Decision rationale'],['planAdherence','Plan adherence: facts vs Owner report'],['followUp','Follow-up question / candidate improvement']].map(([k,l])=>field(k,l,d[k])).join('')}${select('attribution','Candidate attribution — requires evidence',d.attribution??'UNKNOWN',['UNKNOWN','PREDICTION','RESEARCH','INSTRUMENT_SELECTION','EXECUTION','RISK_MANAGEMENT','MARKET_REGIME','UNEXPECTED_EVENT','BEHAVIOR','LUCK'])}</div><p>No lesson or strategy is automatically approved. Profit is not proof of process quality; loss is not proof of a mistake.</p>${buttons('JOURNAL',p,d)}</form>`;}
export function evidenceLoopPanel(s,ui={}){
  const e=s.evidenceLoop;if(!e?.data)return `<section class="card section-space"><h2>Evidence loop</h2><p>${esc(e?.error??'Evidence view unavailable')}</p></section>`;
  const {rows,drafts}=e.data;
  return `<section class="card section-space" id="evidence-loop"><h2>Evidence loop</h2><p>Prediction accuracy ≠ trading profitability. Local evidence only; no trading permission, automatic learning or strategy change.</p>${drafts.map(d=>`<p><strong>${esc(d.tradeId)}</strong> · DRAFT / NOT_CREATED<br>${esc(d.reason)} <a href="#planner">Open Trade planner →</a></p>`).join('')}${!rows.length&&!drafts.length?'<p>No saved plans. No predictions, fills or reviews have been created.</p>':''}${rows.map(row=>{
    const review=row.review,execution=row.execution;
    return `<article data-evidence-row="${esc(row.tradeId)}"><h3>${esc(row.tradeId)}</h3><p>Plan: ${esc(row.planStatus)} · Prediction: <strong>${esc(row.predictionStatus)}</strong> · Execution: ${esc(execution.execution)} (Owner-reported)</p><p>Trade review: ${esc(execution.status)} · Prediction review: ${review?'COMPLETE':'PENDING'} · Journal: ${row.journals.some(j=>j.entry)?'FINALIZED':'NOT_CREATED'}</p><p><strong>${esc(row.matrix)}</strong><br>Prediction: ${esc(review?.accuracy??'UNSCORABLE / UNKNOWN')} · Trade: ${esc(execution.profitability)} · Closed net P&amp;L: ${esc(execution.netPnlUsd??'UNKNOWN / NOT APPLICABLE')}</p>${row.reviewProfitabilityIsHistorical?'<p class="error-text">Ledger evidence changed after prediction review. Original review is retained; current profitability is shown separately.</p>':''}${row.legacy?'<p>LEGACY / PRE_ENTRY_PREDICTION_UNAVAILABLE. Existing execution and reviews remain readable; no backfilled prediction.</p>':''}${row.timingValid===false?'<p class="error-text">PRE_ENTRY_PREDICTION_UNAVAILABLE: later reported entry predates the lock. Original prediction and reviews are retained; current timing is unscorable.</p>':''}${row.error?'<p class="error-text">'+esc(row.error)+'</p>':''}${execution.execution==='NO_TRADE'?'<p>No reported fills. Prediction may be reviewed after its horizon; no P&amp;L is manufactured.</p>':''}
      <details data-disclosure-key="evidence-chain-${esc(row.tradeId)}"><summary>Evidence chain / original records</summary><p>Plan ${esc(row.planFingerprint??'Not configured')} · Prediction ${esc(row.predictionId??'Not available')} · Locked ${esc(timestamp(row.prediction?.lockedAt))}</p>${[['plan','Frozen plan / thesis'],['intent','Original evidence snapshot'],['research','Research / source comparison'],['expectation','Market expectation'],['scenario','Original scenario / Assumption EV'],['contractFit','Original Contract Fit'],['prediction','Prediction Log'],['outcome','Prediction Outcome'],['execution','Manual ledger trade review'],['review','Prediction review'],['journals','Alpha Journal']].map(([key,label])=>`<button class="link-button" data-evidence-detail="${key}" data-evidence-trade="${esc(row.tradeId)}">${label}</button>`).join(' · ')}<p>Strategy: ${esc(row.intent?.payload.strategyStatus??'Unavailable')} · Causal status NOT_ESTABLISHED · approvedKnowledge false</p><p>Trade diagnostics: ${esc((execution.candidateLessons??[]).map(x=>x.code).join(', ')||'No candidate observations')}. Stop/target path remains unknown without evidence.</p></details>
      ${row.predictionStatus==='PREDICTION_EVIDENCE_PENDING'?`<button type="button" class="button secondary" data-evidence-resume="${esc(row.tradeId)}">Resume the same prediction write</button><p>Only possible while still before entry and the original result window. No plan rollback.</p>`:''}
      ${[['OUTCOME',!row.outcome&&row.prediction?.lockedAt],['REVIEW',row.outcome&&!review],['JOURNAL',review&&execution.execution==='CLOSED']].filter(([,ok])=>ok).map(([kind])=>{const k=row.tradeId+':'+kind,d=ui.evidenceDrafts?.[k]??{},p=ui.evidencePreviews?.[k];return `<details data-disclosure-key="evidence-form-${esc(k)}"><summary>${kind==='JOURNAL'?'Post-trade review draft / preview':kind==='OUTCOME'?'Record independent prediction outcome':'Review prediction accuracy'}</summary>${kind==='OUTCOME'?outcomeForm(row,d,p):kind==='REVIEW'?reviewForm(row,d,p):journalForm(row,d,p)}${p?'<details open><summary>Review this exact preview</summary><pre>'+esc(JSON.stringify(p.draft,null,2))+'</pre></details>':''}<p class="error-text" data-evidence-error="${esc(k)}"></p></details>`;}).join('')}</article>`;
  }).join('')}<p>Existing paper Trade Review / Outcome Audit stay under <a href="#reviews">Reviews & lessons</a>. Their engineering results do not qualify a reported trade or prediction.</p></section>`;
}
export function evidenceRequest(kind,tradeId,data,id){
  const value=name=>String(data[name]??'').trim();
  if(kind==='OUTCOME')return {id,tradeId,kind:value('kind'),symbol:value('symbol'),source:value('source'),sourceAt:value('sourceAt'),receivedAt:value('receivedAt'),actualDirection:value('actualDirection'),result:value('result'),eventEvidence:value('eventEvidence')?JSON.parse(value('eventEvidence')):null};
  if(kind==='REVIEW')return {id,tradeId,accuracy:value('accuracy'),rationale:value('rationale')};
  return {id,tradeId,...Object.fromEntries(['interpretation','assumptions','uncertainty','rationale','planAdherence','followUp','attribution'].map(k=>[k,value(k)]))};
}

export function updateEvidenceDraft(ui,key,name,value){
  ui.evidenceDrafts??={};ui.evidenceDrafts[key]??={};
  ui.evidenceDrafts[key][name]=name==='ownerConfirmed'?(value?'on':''):value;
  if(name!=='ownerConfirmed'){ui.evidenceDrafts[key].ownerConfirmed='';if(ui.evidencePreviews)delete ui.evidencePreviews[key];if(ui.evidenceIds)delete ui.evidenceIds[key];}
}
export function evidenceDetail(state,row,kind){
  const original=row.intent?.payload;
  const resolve=(ref,records)=>ref?(records??[]).find(r=>r.path===ref.path&&r.fingerprint===ref.fingerprint)??{reference:ref,status:'ORIGINAL_RECORD_UNAVAILABLE_NO_REPLACEMENT'}:{status:'NOT_CONFIGURED'};
  if(kind==='expectation')return resolve(original?.expectation,state.marketExpectations?.data?.records);
  if(kind==='scenario')return resolve(original?.scenario,state.scenarioResearch?.data?.records);
  if(kind==='research')return (original?.sourceComparisons??[]).map(ref=>resolve(ref,state.sourceComparisons?.data?.records));
  if(kind==='contractFit')return original?.contractFit??{status:'NOT_CONFIGURED'};
  return row[kind]??{status:'NOT_CONFIGURED'};
}
