import {esc,words,decimalInteger,whole} from './model.js';

const field=(name,label,value='',hint='',attrs='')=>`<label class="form-field">${label}<input name="${name}" value="${esc(value)}" ${attrs}>${hint?`<small>${hint}</small>`:''}</label>`;
const select=(name,label,value,items)=>`<label class="form-field">${label}<select name="${name}">${items.map(([v,t])=>`<option value="${esc(v)}"${String(value)===String(v)?' selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
const check=(name,label,value)=>`<label class="check-row full"><input type="checkbox" name="${name}"${value?' checked':''}> ${label}</label>`;
const money=(name,label,d,hint='',required=true)=>field(name,label,d[name],hint,`inputmode="decimal" ${required?'required':''} autocomplete="off"`);
const clock=(name,label,d,required=false)=>field(name,label,d[name],'UTC ISO time, e.g. 2026-09-08T14:00:00.000Z',`${required?'required':''} placeholder="YYYY-MM-DDTHH:mm:ss.sssZ" autocomplete="off"`);
const text=(value)=>String(value??'').trim();
const nullable=v=>text(v)||null;
function usd(v,optional=false){if(!text(v)&&optional)return null;decimalInteger(v,6);return text(v);}
function sequence(v){if(!/^[1-9]\d{0,5}$/.test(text(v))||Number(v)>100000)throw Error('Execution sequence must be 1–100,000.');return Number(v);}
function utc(v,optional=false,precise=false){if(!text(v)&&optional)return null;const s=text(v);if(!(precise?/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,9})?Z$/:/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/).test(s))throw Error('Use a UTC ISO timestamp ending in Z'+(precise?'.':' with three fractional digits.'));return s;}

export const plannerDefaults=()=>({symbol:'GLD',strategy:'LONG_CALL',equity:'1000.00',cash:'1000.00',quantity:'1',bid:'',ask:'',tick:'0.01',fees:'',slippage:'',stop:'20',reward:'2'});
export function plannerBudgetDraft(d,settings){const b=settings?.tradeBudget;return {...d,budgetMin:d.budgetMin??(b?(b.minCents/100).toFixed(2):''),budgetMax:d.budgetMax??(b?(b.maxCents/100).toFixed(2):'')};}
export function tradeBudgetFromFields(d){const min=text(d.budgetMin),max=text(d.budgetMax);if(!min&&!max)return {};if(!min||!max)throw Error('Enter both budget bounds or leave both blank.');return {tradeBudget:{version:'OWNER_TRADE_BUDGET_V1',minCents:decimalInteger(min),maxCents:decimalInteger(max)}};}
const budgetFields=d=>money('budgetMin','Per-trade minimum ($)',d,'Selection range including declared fees; not a spending requirement.',false)+money('budgetMax','Per-trade maximum ($)',d,'Both blank retain the legacy 5% ceiling. Loss caps remain separate.',false);
export function plannerForm(d){return `<form id="planner-form"><div class="form-grid">${select('symbol','ETF',d.symbol,[['GLD','GLD · Gold'],['IBIT','IBIT · Bitcoin']])}${select('strategy','Purchased option',d.strategy,[['LONG_CALL','Long call'],['LONG_PUT','Long put']])}${money('equity','Declared equity ($)',d)}${money('cash','Declared settled cash ($)',d)}${budgetFields(d)}${field('quantity','Whole contracts',d.quantity,'Multiplier: 100 shares', 'inputmode="numeric" required')}${money('tick','Declared price tick ($ / share)',d)}${money('bid','Declared bid ($ / share)',d)}${money('ask','Declared ask ($ / share)',d)}${money('fees','Round-trip fees ($, total)',d,'Blank means unknown. Enter 0 only if explicitly assumed.',false)}${money('slippage','Adverse allowance ($, total)',d,'Blank means unknown; it is not silently set to zero.',false)}${select('stop','Premium stop',d.stop,[['10','10%'],['15','15%'],['20','20%'],['25','25%']])}${select('reward','Requested net reward',d.reward,[['1.5','1.5 R'],['2','2 R']])}</div><div class="form-actions"><button class="button primary" type="submit">Calculate risk & target</button><button class="link-button" type="button" id="reset-planner">Reset scenario</button></div></form>`;}
export function buildScenario(d){return {symbol:d.symbol,strategy:d.strategy,currentEquityCents:decimalInteger(d.equity),settledCashCents:decimalInteger(d.cash),quantity:whole(d.quantity),contractMultiplier:100,bidPerShareCents:decimalInteger(d.bid),askPerShareCents:decimalInteger(d.ask),minimumPriceTickCents:decimalInteger(d.tick),roundTripFeesCents:decimalInteger(d.fees,2,true),slippageReserveCents:decimalInteger(d.slippage,2,true),mode:'NORMAL',stopLossBps:decimalInteger(d.stop),rewardMultipleMilliR:decimalInteger(d.reward,3),...tradeBudgetFromFields(d)};}

export const registerDefaults=()=>({tradeId:'',symbol:'GLD',optionType:'CALL',expiry:'',strikeUsd:'',includePlan:false,declaredAt:'',maxContracts:'1',maxEntryDebitUsd:'',plannedRiskUsd:'',targetNetProfitUsd:'',stopPremiumUsd:'',entryDeadlineAt:'',timeExitAt:'',thesis:'',includeActivity:false,studyId:'',studyFingerprint:'',candidateId:''});
export const fillDefaults=()=>({tradeId:'',fillId:'',executionSequence:'',executedAt:'',action:'BUY_TO_OPEN',quantity:'1',pricePerShareUsd:'',feesUsd:'',externalExecutionRef:'',description:'',documentSha256:'',exitReason:'UNKNOWN',reason:'',voidFill:false,expectedRevision:''});
export function journalForm(mode,manual,d){
  const trades=manual.trades.map(t=>[t.tradeId,`${t.tradeId} · ${t.contract.symbol} ${t.contract.optionType}`]);
  let fields='';
  if(mode==='register'){
    fields=field('tradeId','Trade ID',d.tradeId,'Unique lowercase letters, numbers and hyphens; 3–80 characters.','required maxlength="80" placeholder="gld-sep08-01"')+select('symbol','ETF',d.symbol,[['GLD','GLD'],['IBIT','IBIT']])+select('optionType','Option type',d.optionType,[['CALL','Call'],['PUT','Put']])+field('expiry','Expiration date',d.expiry,'','type="date" required')+money('strikeUsd','Strike ($)',d)+check('includePlan','Include a declared plan',d.includePlan);
    if(d.includePlan)fields+=clock('declaredAt','Plan declaration time',d,true)+field('maxContracts','Maximum contracts',d.maxContracts,'','required inputmode="numeric"')+money('maxEntryDebitUsd','Maximum entry debit ($, including entry costs)',d)+money('plannedRiskUsd','Planned total loss ($)',d)+money('targetNetProfitUsd','Target net profit ($)',d)+money('stopPremiumUsd','Declared premium stop ($ / share)',d,'Optional; a stop is not a guaranteed execution.',false)+clock('entryDeadlineAt','Entry deadline',d)+clock('timeExitAt','Time exit',d)+field('thesis','Market view / plan',d.thesis,'Record the original view. Later entry stays labeled retrospective.','required maxlength="1000"');
    fields+=check('includeActivity','Link an existing frozen activity candidate',d.includeActivity);
    if(d.includeActivity)fields+=field('studyId','Study ID',d.studyId,'','required')+field('studyFingerprint','Original study fingerprint',d.studyFingerprint,'sha256: followed by 64 hexadecimal characters','required')+field('candidateId','Candidate contract ID',d.candidateId,'Original candidate UUID; verified again when saved.','required');
  }else{
    fields=select('tradeId','Registered trade',d.tradeId,[['','Select a trade'],...trades]);
    if(mode==='correct'){
      const trade=manual.trades.find(t=>t.tradeId===d.tradeId),fills=trade?.effectiveFills??[];
      fields+=select('fillId','Fill to correct',d.fillId,[['','Select a fill'],...fills.map(f=>[f.fillId,`${f.fillId} · revision ${f.revision}${f.value?'':' · voided'}`])])+field('expectedRevision','Revision being corrected',d.expectedRevision,'The server rejects a stale correction.','readonly required')+field('reason','Reason for correction',d.reason,'Original entries are retained. Explain the change.','required maxlength="1000"')+check('voidFill','Void this fill (preserve the original history)',d.voidFill);
    }else fields+=field('fillId','Fill ID',d.fillId,'A unique ID for this execution, e.g. gld-sep08-buy-01.','required maxlength="80"');
    if(mode!=='correct'||!d.voidFill)fields+=field('executionSequence','Execution sequence within this trade',d.executionSequence,'1 for the first fill, then 2, 3…','required inputmode="numeric"')+clock('executedAt','Actual execution time',d,true)+select('action','Execution action',d.action,[['BUY_TO_OPEN','Bought to open'],['SELL_TO_CLOSE','Sold to close']])+field('quantity','Filled contracts',d.quantity,'Whole contracts only','required inputmode="numeric"')+money('pricePerShareUsd','Actual fill premium ($ / share)',d)+money('feesUsd','Actual fee for this fill ($, total)',d,'Blank remains unknown; use 0 only when confirmed.',false)+field('externalExecutionRef','Execution reference',d.externalExecutionRef,'Optional reference from your broker record.','maxlength="120"')+field('description','Evidence description',d.description,'Optional: identify a local statement or screenshot; no file is uploaded.','maxlength="500"')+field('documentSha256','Evidence SHA-256',d.documentSha256,'Optional 64-character digest. A digest does not authenticate the record.','maxlength="64"')+(d.action==='SELL_TO_CLOSE'?select('exitReason','Reported exit reason',d.exitReason,[['UNKNOWN','Unknown'],['TARGET','Target'],['STOP','Stop'],['TIME','Time exit'],['MANUAL','Manual decision']]):'');
  }
  return `<form id="journal-form"><div class="form-grid">${fields}</div><div class="form-actions"><button class="button primary" type="submit">Preview local record</button><button class="link-button" type="button" id="reset-journal">Clear this draft</button></div><p class="hint">This app records your report. It does not send an order or verify a brokerage execution. Drafts stay in this tab until it closes.</p></form>`;
}
function buildFill(d){const description=nullable(d.description),hash=nullable(d.documentSha256);if(hash&&!description)throw Error('Add an evidence description when supplying a document hash.');return {executionSequence:sequence(d.executionSequence),executedAt:utc(d.executedAt,false,true),action:d.action,quantity:whole(d.quantity),pricePerShareUsd:usd(d.pricePerShareUsd),feesUsd:usd(d.feesUsd,true),externalExecutionRef:nullable(d.externalExecutionRef),evidence:description?{description,documentSha256:hash}:null,exitReason:d.action==='BUY_TO_OPEN'?'NOT_APPLICABLE':d.exitReason};}
export function buildCommand(mode,d,requestId){
  const common={requestId,tradeId:text(d.tradeId)};
  if(mode==='register')return {type:'REGISTER_TRADE',...common,contract:{symbol:d.symbol,expiry:text(d.expiry),optionType:d.optionType,strikeUsd:usd(d.strikeUsd),multiplier:100},plan:d.includePlan?{declaredAt:utc(d.declaredAt),maxContracts:whole(d.maxContracts),maxEntryDebitUsd:usd(d.maxEntryDebitUsd),plannedRiskUsd:usd(d.plannedRiskUsd),targetNetProfitUsd:usd(d.targetNetProfitUsd),stopPremiumUsd:usd(d.stopPremiumUsd,true),entryDeadlineAt:utc(d.entryDeadlineAt,true),timeExitAt:utc(d.timeExitAt,true),thesis:text(d.thesis)}:null,activityReference:d.includeActivity?{studyId:text(d.studyId),studyFingerprint:text(d.studyFingerprint),candidateId:text(d.candidateId)}:null};
  if(mode==='fill')return {type:'RECORD_FILL',...common,fillId:text(d.fillId),fill:buildFill(d)};
  if(mode==='correct')return {type:'CORRECT_FILL',...common,fillId:text(d.fillId),expectedRevision:whole(d.expectedRevision),reason:text(d.reason),replacement:d.voidFill?null:buildFill(d)};
  throw Error('Unknown record type.');
}
