import {esc,words,cents,dollars,timestamp,safeLink} from "./model.js";
import {candidateChecksPanel} from './candidate-checks.js';
import {capitalPolicyPanel} from './capital-policy.js';
const money=v=>v===null||v===undefined?"Unknown":cents(v);
const notice=s=>'<div class="notice"><div>'+s+'</div></div>';
const detail=(label,data)=>'<details><summary>'+esc(label)+'</summary><pre>'+esc(JSON.stringify(data,null,2))+'</pre></details>';
const sourceLinks=sources=>(sources??[]).map(s=>{const url=safeLink(s.url);return url?'<li><a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+esc(s.title)+'</a> · '+esc(timestamp(s.publishedAt??s.retrievedAt))+'</li>':"";}).join("");
export function guidanceDeliveryPanel(component) {
  const d=component?.data;
  if(!d)return notice('Market delivery check unavailable: '+esc(component?.error??'No check loaded')+'. Do not infer a successful capture.');
  const c=d.latestCapture,p=d.publication;
  return '<section class="card section-space"><h2>Market data → analysis → guidance</h2><p><strong>'+d.counts.recorded+' / '+d.counts.expectedCompleted+' ended fixed windows have a saved capture · '+d.counts.missing+' missing · '+d.counts.partial+' partial.</strong></p>'+
    '<p>Last seven calendar dates · 09:50, 12:50 and 15:50 New York. Event-dependent reads and full-chain closes are counted separately. A time match does not prove scheduled execution.</p>'+
    '<dl class="rationale-values guidance-delivery-clocks"><div><dt>Latest market capture</dt><dd>'+esc(timestamp(c?.capturedAt))+'</dd></div><div><dt>Returned / requested contracts</dt><dd>'+(c?c.returned+' / '+c.requested+' · '+(c.requested-c.returned)+' missing · '+(c.complete?'Complete receipt':'Partial receipt'):'Unknown')+'</dd></div><div><dt>Attributed analysis</dt><dd>'+esc(words(d.analysis.status))+' · '+esc(timestamp(d.analysis.assessedAt))+'</dd></div><div><dt>Latest issued guidance</dt><dd>'+esc(timestamp(p?.issuedAt))+'</dd></div></dl>'+
    notice(p?(p.usesCurrentMarketInputs?'The latest issued report contains the same market inputs as this view. Reissuing a report does not refresh its quotes.':'The latest issued report uses different market inputs. Its saved evidence must be reviewed separately.'):'No issued guidance record is available.')+
    '<div class="table-scroll"><table><thead><tr><th>ETF</th><th>Fresh option clocks</th><th>Stale / unknown / future clocks</th><th>ETF source clock</th></tr></thead><tbody>'+d.quoteClocks.map(q=>'<tr><td>'+esc(q.symbol)+'</td><td>'+q.fresh+' / '+q.requested+'</td><td>'+q.stale+' / '+q.unknown+' / '+q.future+'</td><td>'+esc(timestamp(q.underlyingAt))+'<small>'+esc(words(q.underlyingFreshness))+'</small></td></tr>').join('')+'</tbody></table></div>'+
    '<p class="hint">Freshness limit: '+d.freshnessLimitSeconds+' seconds. Unknown clocks include absent quotes. A saved receipt is not execution qualification. Next fixed window: '+esc(timestamp(d.nextExpectedSlot?.startAt))+'.</p>'+
    '<details data-disclosure-key="guidance-delivery-slots"><summary>Inspect collection windows and missing evidence</summary><p>'+esc(d.missingCause)+'</p><p>Calendar-unreviewed windows: '+d.counts.calendarUnknown+'.</p><div class="table-scroll"><table><thead><tr><th>New York window</th><th>Saved state</th><th>Returned / requested</th></tr></thead><tbody>'+d.slots.map(s=>'<tr><td>'+esc(s.slot)+'</td><td>'+esc(words(s.status))+'</td><td>'+(s.capture?s.capture.returned+' / '+s.capture.requested:'No saved receipt')+'</td></tr>').join('')+'</tbody></table></div></details></section>';
}
export function guidanceSessionPanel(r) {
  const s=r.marketSession;if(!s)return '';
  return notice('<strong>Regular-session guidance: '+(!s.knownYear?'calendar year unreviewed':s.isOpen?'open':'closed')+'.</strong> '+esc(s.date)+' · 09:30–'+esc(s.closeLocal)+' New York'+(s.earlyClose?' · Early close':'')+(s.holiday?' · Closed day':'')+'. Reviewed calendar model; halts remain unverified. New guidance requires an analyst review at or after its latest market capture.');
}
export function rationaleDimensions(asset) {
  if(!asset)return '';
  return '<details class="guidance-rationale" data-disclosure-key="dimensions-'+esc(asset.symbol)+'" open><summary>Six-dimension decision check</summary><dl class="rationale-dimensions">'+asset.dimensions.map(d=>'<div><dt>'+esc(words(d.id))+' · '+esc(words(d.status))+'</dt><dd>'+esc(d.explanation)+'</dd></div>').join('')+'</dl></details>';
}
export function contractRationale(r) {
  if(!r)return '';
  const t=r.terminal;
  return '<details class="guidance-rationale" data-disclosure-key="contract-'+esc(r.id)+'"><summary>Expiry, strike and event reasoning</summary><p>'+esc(r.expiryReason)+'</p><p>'+esc(r.strikeReason)+'</p>'+
    '<p><strong>'+esc(words(r.moneyness))+'</strong> · Reference quote '+esc(words(r.quoteFreshness))+' · '+(r.referencePricesComparable?'Recent source clocks':'Reference prices are not verified as comparable')+'</p>'+
    (r.referenceAnomaly?notice(esc(words(r.referenceAnomaly))):'')+
    '<dl class="rationale-values"><div><dt>Expiry-only breakeven, before costs</dt><dd>'+dollars(t.grossBreakEvenUsd)+' · '+esc(words(t.grossState))+'</dd></div><div><dt>Expiry threshold with declared cost reserve</dt><dd>'+dollars(t.reservedCostBreakEvenUsd)+' · '+esc(words(t.reservedCostState))+'</dd></div><div><dt>Move from reference ETF price to gross expiry breakeven</dt><dd>'+(t.grossMoveFromReferencePercent===null?'Unknown':esc(t.grossMoveFromReferencePercent)+'%')+'</dd></div><div><dt>Reference intrinsic / extrinsic per share</dt><dd>'+dollars(r.referenceIntrinsicPerShareUsd)+' / '+dollars(r.referenceExtrinsicPerShareUsd)+'</dd></div></dl>'+
    '<p class="hint">'+esc(t.interpretation)+'</p><p><strong>Pre-expiry ETF target: unestablished. Time exit: not declared.</strong></p>'+
    '<h4>Known major events through expiry</h4>'+(r.calendarCoverageAvailable?'':notice('Calendar coverage is incomplete; this list cannot establish all event exposure.'))+
    (r.expiryEvents.length?'<ul>'+r.expiryEvents.map(e=>'<li>'+esc(e.title)+' · '+esc(e.source)+' · '+esc(e.scheduledAt?timestamp(e.scheduledAt):e.startDate+' – '+e.endDate+' · time unknown')+' · '+esc(words(e.overlap))+'</li>').join('')+'</ul>':'<p>No upcoming major event in the saved calendar subset; absence is not a guarantee.</p>')+'</details>';
}
function candidate(c,rationale) {
  const q=c.contract,p=c.plan,e=c.feasibility.economics;
  return '<article class="guidance-contract"><div class="status-line"><strong>'+esc(q.symbol+' '+q.expiry+' '+q.strike+' '+q.type.toUpperCase())+'</strong><span class="tag '+(c.disposition==="NO_TRADE"?"amber":"blue")+'">'+esc(words(c.disposition))+'</span></div>'+
    '<div class="guidance-prices"><span>Reference ask / share<strong>'+money(p.entryLimitCents)+'</strong></span><span>Stop trigger / share<strong>'+money(p.stopTriggerCents)+'</strong></span><span>Target / share<strong>'+money(p.targetExitCents)+'</strong></span></div>'+
    '<p class="hint">1 contract · Premium '+money(e?.premiumCents)+' · Planned net risk '+money(p.netRiskCents)+' · Net target '+money(p.netTargetCents)+' · Full-premium stress '+(e?.stressLossCents===null?money(e?.premiumCents)+' + unknown costs':money(e?.stressLossCents))+'</p>'+
    '<p class="hint">Quote '+esc(timestamp(q.updatedAt))+' · Bid / ask '+money(q.bidCents)+' / '+money(q.askCents)+' · Delta '+esc(q.delta??"Unknown")+'</p>'+
    (c.blockers.length?'<ul class="blocker-list">'+c.blockers.slice(0,4).map(b=>'<li>'+esc(words(b))+'</li>').join("")+'</ul>':notice('Conditional research only. Review the current quote, your actual account and all plan assumptions before any manual decision.'))+
    (c.blockers.length>4?detail('All reasons for this decision',c.blockers):'')+'<p class="hint">'+esc(p.invalidation)+' '+esc(p.timeExit)+'</p>'+
    contractRationale(rationale)+'<button class="button secondary small" data-guidance-plan="'+esc(q.id)+'">Inspect in trade planner</button>'+detail('Exact economics and assumptions',c.feasibility)+'</article>';
}
export function guidancePage(s,ui={}) {
  const component=s.guidance,view=component?.data,r=view?.current;
  const header='<div class="page-heading"><div><p class="eyebrow">EVIDENCE BEFORE A TRADE</p><h1>Daily guidance</h1><p class="subtitle">GLD and IBIT · Long calls and puts · 14–45 days to expiry · A reason to act or wait.</p></div></div>';
  if(!r)return header+notice('Guidance unavailable: '+esc(component?.error??'No saved inputs')+'. Existing source and trade records remain separate.');
  const settings=r.settings,removed=settings.tradeBudget?.version==='OWNER_ALLOCATION_ONLY_V2',form=ui.guidanceSettingsDraft,note=view.interpretation,staleNote=note&&Date.parse(s.loadedAt)-Date.parse(note.assessedAt)>24*3600000;
  return header+notice('<strong>Current reassessment</strong> '+esc(timestamp(r.assessedAt))+' · Market capture '+esc(timestamp(r.marketCapturedAt))+'. Source clocks below decide freshness. This page checks local files every minute when idle; it does not fetch brokerage quotes.')+guidanceSessionPanel(r)+guidanceDeliveryPanel(s.guidanceDelivery)+
    '<div class="metrics"><div class="metric"><div class="metric-label">'+(settings.tradeBudget?'Per-trade allocation range':'Normal allocation')+'</div><strong>'+(settings.tradeBudget?money(settings.tradeBudget.minCents)+'–'+money(settings.tradeBudget.maxCents):money(Math.floor(settings.currentEquityCents*0.05)))+'</strong><small>'+(settings.tradeBudget?(removed?'Legacy loss caps removed · exposure still shown':'Declared range · independent loss caps remain'):'5% of declared equity · whole contracts')+'</small></div><div class="metric"><div class="metric-label">Illustrative premium stop</div><strong>'+(settings.stopLossBps/100)+'%</strong><small>A trigger cannot guarantee the exit loss</small></div><div class="metric"><div class="metric-label">Net reward target</div><strong>'+(settings.rewardMultipleMilliR/1000)+'R</strong><small>Requires declared fees and slippage</small></div><div class="metric"><div class="metric-label">Win probability</div><strong>Unverified</strong><small>No 80% claim or automatic size increase</small></div></div>'+
    (removed?notice('<strong>Current owner policy: legacy loss caps removed.</strong> '+esc(r.policy)+' Earlier analyst text below is dated context; it cannot reinstate the old caps.'):'')+capitalPolicyPanel(s.capitalPolicy?.data)+candidateChecksPanel(s.candidateChecks,ui)+'<div class="grid-two guidance-assets">'+r.assets.map(a=>{
      const n=note?.assets.find(n=>n.symbol===a.symbol),qualifying=a.candidates.filter(c=>c.disposition==="CONDITIONAL_RESEARCH").length,rationale=view.rationale?.assets.find(x=>x.symbol===a.symbol);
      return '<section class="card guidance-asset"><div class="card-head"><div><p class="eyebrow">'+a.symbol+'</p><h2>'+esc(words(a.disposition))+'</h2></div><span class="tag '+(a.trend.direction==="UP"?"green":a.trend.direction==="DOWN"?"red":"amber")+'">'+esc(words(a.trend.direction))+'</span></div>'+
        '<p>Latest observed ETF price <strong>'+dollars(a.equity?.price)+'</strong> · '+esc(timestamp(a.equity?.sourceAt))+'</p><p>'+esc(a.trend.reason)+'</p>'+
        '<p class="hint">'+qualifying+' conditional candidates / '+a.candidates.length+' sampled contracts. Ordered by feasibility then cash exposure, not expected profitability.</p>'+rationaleDimensions(rationale)+
        '<ul class="blocker-list">'+a.blockers.map(b=>'<li>'+esc(words(b))+'</li>').join("")+'</ul>'+
        (n?'<section class="analyst-note"><h3>Analyst interpretation '+(staleNote?'· Older than 24 hours':'')+'</h3><p><strong>'+esc(words(n.bias))+'</strong> · '+esc(n.summary)+'</p><h4>Supporting evidence</h4><ul>'+n.supporting.map(v=>'<li>'+esc(v)+'</li>').join("")+'</ul><h4>Opposing evidence</h4><ul>'+n.opposing.map(v=>'<li>'+esc(v)+'</li>').join("")+'</ul><p><strong>Invalidation:</strong> '+esc(n.invalidation)+'</p><p><strong>Event plan:</strong> '+esc(n.eventPlan)+'</p><ul>'+sourceLinks(n.sources)+'</ul><p class="hint">Attributed analyst interpretation · '+esc(timestamp(note.assessedAt))+' · Does not override the checks above.</p></section>':notice('No attributed analyst interpretation has been saved yet. Missing news interpretation is not neutral evidence.'))+
        detail('Official closes behind the descriptive trend',a.trend)+
        (a.candidates.length?a.candidates.slice(0,3).map(c=>candidate(c,rationale?.contracts.find(x=>x.id===c.contract.id))).join("")+(a.candidates.length>3?'<details data-disclosure-key="other-contracts-'+esc(a.symbol)+'"><summary>Show '+(a.candidates.length-3)+' other sampled contracts</summary>'+a.candidates.slice(3).map(c=>candidate(c,rationale?.contracts.find(x=>x.id===c.contract.id))).join("")+'</details>':""):notice('No captured candidate contracts. The next authorized market read will populate this list.'))+'</section>';
    }).join("")+'</div>'+
    '<section class="card section-space"><div class="card-head"><div><h2>Important events and decision posture</h2><p>Before major releases: wait. After timed releases: allow at least 30 minutes and require fresh evidence. FOMC date-only coverage does not invent an intraday release time.</p></div></div>'+
    (r.events.length?'<div class="table-scroll"><table><thead><tr><th>Event</th><th>Scheduled time / dates</th><th>Posture</th></tr></thead><tbody>'+r.events.map(e=>'<tr><td>'+esc(e.title)+'<small>'+esc(e.source)+'</small></td><td>'+esc(e.scheduledAt?timestamp(e.scheduledAt):e.startDate+' – '+e.endDate+' · time unknown')+'</td><td>'+esc(words(e.posture))+'</td></tr>').join("")+'</tbody></table></div>':notice('No available calendar entries. This does not establish an event-free session.'))+'</section>'+
    '<section class="card section-space"><h2>Declared planning assumptions</h2><p>These are local scenarios. Alpha does not read your account balances or verify brokerage fees. Blank costs remain unknown and block a net-R plan.</p><form id="guidance-settings-form" class="form-grid">'+(removed?'<input type="hidden" name="budgetVersion" value="OWNER_ALLOCATION_ONLY_V2">':'')+
    [['currentEquityCents','Account equity'],['settledCashCents','Settled cash'],['roundTripFeesCents','Round-trip fees per contract'],['slippageReserveCents','Exit slippage reserve per contract']].map(([k,label])=>'<label>'+label+' (USD)<input name="'+k+'" inputmode="decimal" value="'+esc(form?.[k]??(settings[k]===null?'':(settings[k]/100).toFixed(2)))+'" '+(k.includes('Equity')||k.includes('Cash')?'required':'')+'></label>').join("")+
    [['budgetMin','Per-trade minimum','minCents'],['budgetMax','Per-trade maximum','maxCents']].map(([k,label,b])=>'<label>'+label+' (USD)<input name="'+k+'" inputmode="decimal" value="'+esc(form?.[k]??(settings.tradeBudget?(settings.tradeBudget[b]/100).toFixed(2):''))+'"><small>'+(removed?'Both required; minimum $100. Legacy loss caps removed.':'Both blank use the legacy 5% ceiling; loss caps stay separate.')+'</small></label>').join('')+'<label>Premium stop<select name="stopLossBps">'+[1000,1500,2000,2500].map(v=>'<option value="'+v+'"'+(Number(form?.stopLossBps??settings.stopLossBps)===v?' selected':'')+'>'+(v/100)+'%</option>').join("")+'</select></label><label>Net target<select name="rewardMultipleMilliR">'+[1500,2000].map(v=>'<option value="'+v+'"'+(Number(form?.rewardMultipleMilliR??settings.rewardMultipleMilliR)===v?' selected':'')+'>'+(v/1000)+'R</option>').join("")+'</select></label><div><button class="button secondary" type="button" id="preview-capital-policy">Preview capital limits</button> <button class="button primary" type="submit">Save local assumptions</button> <button class="button secondary" type="button" id="reset-guidance-assumptions">Discard changes</button></div></form><p id="guidance-settings-error" class="error-text" role="alert"></p><div id="capital-policy-preview">'+capitalPolicyPanel(ui.capitalPolicyPreview,{preview:true})+'</div></section>'+
    '<section class="card section-space"><h2>Issued recommendation history</h2><p>Every issued view keeps its original inputs and assessment clock. The current screen may differ as evidence ages. An issued recommendation is not a trade or a realized outcome.</p>'+
    (view.history.length?'<div class="table-scroll"><table><thead><tr><th>Issued</th><th>GLD</th><th>IBIT</th><th>Evidence</th></tr></thead><tbody>'+view.history.map(h=>'<tr><td>'+esc(timestamp(h.issuedAt))+'</td>'+h.assets.map(a=>'<td>'+esc(words(a.disposition))+'<small>'+esc(words(a.trend))+'</small></td>').join("")+'<td>'+detail('Saved reference',h)+'</td></tr>').join("")+'</tbody></table></div>':notice('No issued views yet. Reading this page does not issue or backdate a recommendation.'))+'</section>'+
    '<section class="card section-space"><h2>Connected context and gaps</h2><p>'+esc(r.coverage)+'</p><p>The separate <a href="#context">focused news view</a> adds Fed speeches, EIA energy and CoinDesk to the six original feeds, with daily attributed web review and explicit coverage gaps.</p>'+detail('Source refresh clocks',r.sourceHealth)+detail('Treasury and BTC context',r.context)+'<p class="hint">'+esc(r.policy)+'</p><p>Report actual entries and exits in <a href="#journal">Trade journal</a>; <a href="#reviews">Reviews & lessons</a> separates recorded results from unproven explanations.</p></section>';
}
