import {esc,words,cents,dollars,timestamp,safeLink} from "./model.js";
import {candidateChecksPanel} from './candidate-checks.js';
const money=v=>v===null||v===undefined?"Unknown":cents(v);
const notice=s=>'<div class="notice"><div>'+s+'</div></div>';
const detail=(label,data)=>'<details><summary>'+esc(label)+'</summary><pre>'+esc(JSON.stringify(data,null,2))+'</pre></details>';
const sourceLinks=sources=>(sources??[]).map(s=>{const url=safeLink(s.url);return url?'<li><a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+esc(s.title)+'</a> · '+esc(timestamp(s.publishedAt??s.retrievedAt))+'</li>':"";}).join("");
function candidate(c) {
  const q=c.contract,p=c.plan,e=c.feasibility.economics;
  return '<article class="guidance-contract"><div class="status-line"><strong>'+esc(q.symbol+' '+q.expiry+' '+q.strike+' '+q.type.toUpperCase())+'</strong><span class="tag '+(c.disposition==="NO_TRADE"?"amber":"blue")+'">'+esc(words(c.disposition))+'</span></div>'+
    '<div class="guidance-prices"><span>Reference ask / share<strong>'+money(p.entryLimitCents)+'</strong></span><span>Stop trigger / share<strong>'+money(p.stopTriggerCents)+'</strong></span><span>Target / share<strong>'+money(p.targetExitCents)+'</strong></span></div>'+
    '<p class="hint">1 contract · Premium '+money(e?.premiumCents)+' · Planned net risk '+money(p.netRiskCents)+' · Net target '+money(p.netTargetCents)+' · Full-premium stress '+(e?.stressLossCents===null?money(e?.premiumCents)+' + unknown costs':money(e?.stressLossCents))+'</p>'+
    '<p class="hint">Quote '+esc(timestamp(q.updatedAt))+' · Bid / ask '+money(q.bidCents)+' / '+money(q.askCents)+' · Delta '+esc(q.delta??"Unknown")+'</p>'+
    (c.blockers.length?'<ul class="blocker-list">'+c.blockers.slice(0,4).map(b=>'<li>'+esc(words(b))+'</li>').join("")+'</ul>':notice('Conditional research only. Review the current quote, your actual account and all plan assumptions before any manual decision.'))+
    (c.blockers.length>4?detail('All reasons for this decision',c.blockers):'')+'<p class="hint">'+esc(p.invalidation)+' '+esc(p.timeExit)+'</p>'+
    '<button class="button secondary small" data-guidance-plan="'+esc(q.id)+'">Inspect in trade planner</button>'+detail('Exact economics and assumptions',c.feasibility)+'</article>';
}
export function guidancePage(s,ui={}) {
  const component=s.guidance,view=component?.data,r=view?.current;
  const header='<div class="page-heading"><div><p class="eyebrow">EVIDENCE BEFORE A TRADE</p><h1>Daily guidance</h1><p class="subtitle">GLD and IBIT · Long calls and puts · 14–45 days to expiry · A reason to act or wait.</p></div></div>';
  if(!r)return header+notice('Guidance unavailable: '+esc(component?.error??'No saved inputs')+'. Existing source and trade records remain separate.');
  const settings=r.settings,form=ui.guidanceSettingsDraft,note=view.interpretation,staleNote=note&&Date.parse(s.loadedAt)-Date.parse(note.assessedAt)>24*3600000;
  return header+notice('<strong>Current reassessment</strong> '+esc(timestamp(r.assessedAt))+' · Market capture '+esc(timestamp(r.marketCapturedAt))+'. Source clocks below decide freshness. A scheduled reader updates the saved evidence; this page checks local files every minute when idle.')+
    '<div class="metrics"><div class="metric"><div class="metric-label">Normal allocation</div><strong>'+money(Math.floor(settings.currentEquityCents*0.05))+'</strong><small>5% of declared equity · whole contracts</small></div><div class="metric"><div class="metric-label">Illustrative premium stop</div><strong>'+(settings.stopLossBps/100)+'%</strong><small>A trigger cannot guarantee the exit loss</small></div><div class="metric"><div class="metric-label">Net reward target</div><strong>'+(settings.rewardMultipleMilliR/1000)+'R</strong><small>Requires declared fees and slippage</small></div><div class="metric"><div class="metric-label">Win probability</div><strong>Unverified</strong><small>No 80% claim or automatic size increase</small></div></div>'+
    candidateChecksPanel(s.candidateChecks,ui)+'<div class="grid-two guidance-assets">'+r.assets.map(a=>{
      const n=note?.assets.find(n=>n.symbol===a.symbol),qualifying=a.candidates.filter(c=>c.disposition==="CONDITIONAL_RESEARCH").length;
      return '<section class="card guidance-asset"><div class="card-head"><div><p class="eyebrow">'+a.symbol+'</p><h2>'+esc(words(a.disposition))+'</h2></div><span class="tag '+(a.trend.direction==="UP"?"green":a.trend.direction==="DOWN"?"red":"amber")+'">'+esc(words(a.trend.direction))+'</span></div>'+
        '<p>Latest observed ETF price <strong>'+dollars(a.equity?.price)+'</strong> · '+esc(timestamp(a.equity?.sourceAt))+'</p><p>'+esc(a.trend.reason)+'</p>'+
        '<p class="hint">'+qualifying+' conditional candidates / '+a.candidates.length+' sampled contracts. Ordered by feasibility then cash exposure, not expected profitability.</p>'+
        '<ul class="blocker-list">'+a.blockers.map(b=>'<li>'+esc(words(b))+'</li>').join("")+'</ul>'+
        (n?'<section class="analyst-note"><h3>Analyst interpretation '+(staleNote?'· Older than 24 hours':'')+'</h3><p><strong>'+esc(words(n.bias))+'</strong> · '+esc(n.summary)+'</p><h4>Supporting evidence</h4><ul>'+n.supporting.map(v=>'<li>'+esc(v)+'</li>').join("")+'</ul><h4>Opposing evidence</h4><ul>'+n.opposing.map(v=>'<li>'+esc(v)+'</li>').join("")+'</ul><p><strong>Invalidation:</strong> '+esc(n.invalidation)+'</p><p><strong>Event plan:</strong> '+esc(n.eventPlan)+'</p><ul>'+sourceLinks(n.sources)+'</ul><p class="hint">Attributed analyst interpretation · '+esc(timestamp(note.assessedAt))+' · Does not override the checks above.</p></section>':notice('No attributed analyst interpretation has been saved yet. Missing news interpretation is not neutral evidence.'))+
        detail('Official closes behind the descriptive trend',a.trend)+
        (a.candidates.length?a.candidates.slice(0,3).map(candidate).join("")+(a.candidates.length>3?'<details><summary>Show '+(a.candidates.length-3)+' other sampled contracts</summary>'+a.candidates.slice(3).map(candidate).join("")+'</details>':""):notice('No captured candidate contracts. The next authorized market read will populate this list.'))+'</section>';
    }).join("")+'</div>'+
    '<section class="card section-space"><div class="card-head"><div><h2>Important events and decision posture</h2><p>Before major releases: wait. After timed releases: allow at least 30 minutes and require fresh evidence. FOMC date-only coverage does not invent an intraday release time.</p></div></div>'+
    (r.events.length?'<div class="table-scroll"><table><thead><tr><th>Event</th><th>Scheduled time / dates</th><th>Posture</th></tr></thead><tbody>'+r.events.map(e=>'<tr><td>'+esc(e.title)+'<small>'+esc(e.source)+'</small></td><td>'+esc(e.scheduledAt?timestamp(e.scheduledAt):e.startDate+' – '+e.endDate+' · time unknown')+'</td><td>'+esc(words(e.posture))+'</td></tr>').join("")+'</tbody></table></div>':notice('No available calendar entries. This does not establish an event-free session.'))+'</section>'+
    '<section class="card section-space"><h2>Declared planning assumptions</h2><p>These are local scenarios. Alpha does not read your account balances or verify brokerage fees. Blank costs remain unknown and block a net-R plan.</p><form id="guidance-settings-form" class="form-grid">'+
    [['currentEquityCents','Account equity'],['settledCashCents','Settled cash'],['roundTripFeesCents','Round-trip fees per contract'],['slippageReserveCents','Exit slippage reserve per contract']].map(([k,label])=>'<label>'+label+' (USD)<input name="'+k+'" inputmode="decimal" value="'+esc(form?.[k]??(settings[k]===null?'':(settings[k]/100).toFixed(2)))+'" '+(k.includes('Equity')||k.includes('Cash')?'required':'')+'></label>').join("")+
    '<label>Premium stop<select name="stopLossBps">'+[1000,1500,2000,2500].map(v=>'<option value="'+v+'"'+(Number(form?.stopLossBps??settings.stopLossBps)===v?' selected':'')+'>'+(v/100)+'%</option>').join("")+'</select></label><label>Net target<select name="rewardMultipleMilliR">'+[1500,2000].map(v=>'<option value="'+v+'"'+(Number(form?.rewardMultipleMilliR??settings.rewardMultipleMilliR)===v?' selected':'')+'>'+(v/1000)+'R</option>').join("")+'</select></label><div><button class="button primary" type="submit">Save local assumptions</button> <button class="button secondary" type="button" id="reset-guidance-assumptions">Discard changes</button></div></form><p id="guidance-settings-error" class="error-text" role="alert"></p></section>'+
    '<section class="card section-space"><h2>Issued recommendation history</h2><p>Every issued view keeps its original inputs and assessment clock. The current screen may differ as evidence ages. An issued recommendation is not a trade or a realized outcome.</p>'+
    (view.history.length?'<div class="table-scroll"><table><thead><tr><th>Issued</th><th>GLD</th><th>IBIT</th><th>Evidence</th></tr></thead><tbody>'+view.history.map(h=>'<tr><td>'+esc(timestamp(h.issuedAt))+'</td>'+h.assets.map(a=>'<td>'+esc(words(a.disposition))+'<small>'+esc(words(a.trend))+'</small></td>').join("")+'<td>'+detail('Saved reference',h)+'</td></tr>').join("")+'</tbody></table></div>':notice('No issued views yet. Reading this page does not issue or backdate a recommendation.'))+'</section>'+
    '<section class="card section-space"><h2>Connected context and gaps</h2><p>'+esc(r.coverage)+'</p><p>The separate <a href="#context">focused news view</a> adds Fed speeches, EIA energy and CoinDesk to the six original feeds, with daily attributed web review and explicit coverage gaps.</p>'+detail('Source refresh clocks',r.sourceHealth)+detail('Treasury and BTC context',r.context)+'<p class="hint">'+esc(r.policy)+'</p><p>Report actual entries and exits in <a href="#journal">Trade journal</a>; <a href="#reviews">Reviews & lessons</a> separates recorded results from unproven explanations.</p></section>';
}
