import {esc,words,timestamp,safeLink} from './model.js';
const fmt=(n,scale=100,places=2)=>n===null||n===undefined?'Unknown':(n/scale).toFixed(places);
const link=(url,label)=>{const u=safeLink(url);return u?'<a href="'+esc(u)+'" target="_blank" rel="noopener noreferrer">'+esc(label)+' ↗</a>':esc(label);};
const table=(heads,rows)=>'<div class="table-scroll"><table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
export function macroComparisonRequest(d) {
  const [forecastPath,period,metric]=(d.forecastKey??'').split('|');
  return {requestId:d.requestId,forecastPath,period,metric,actualValue:d.actualValue??'',seasonalAdjustment:d.seasonalAdjustment??'',releaseAt:d.releaseAt??'',sourceUrl:d.sourceUrl??''};
}
export function macroPreviewMatches(preview,d) {return !!preview&&JSON.stringify(preview.request)===JSON.stringify(macroComparisonRequest(d));}
export function macroComparisonResult(r) {
  return r?'<div class="notice"><div><strong>Actual minus saved model: '+esc(fmt(r.actualMinusModelHundredthsPp))+' percentage points</strong><p>Saved model '+esc(fmt(r.modelValueBps))+'% · Owner-reported actual '+esc(fmt(r.reportedActualValueBps))+'%. This is model forecast error, not market-consensus surprise.</p><p>Benchmark saved '+esc(timestamp(r.benchmarkRecordedAt))+' · Actual and release time remain owner-reported and unverified.</p></div></div>':'<p class="hint">Preview appears here after the release. No official actual or market consensus is supplied automatically.</p>';
}
export function macroContextPanel(component,ui={}) {
  const m=component?.state==='AVAILABLE'?component.data:null;
  if(!m)return '<section class="card section-space"><h2>Rates, dollar & inflation benchmarks</h2><p class="hint">Macro context unavailable. No current numerical coverage is established.</p></section>';
  const choices=m.forecasts.flatMap(f=>f.cells.filter(c=>c.valueBps!==null).map(c=>({key:[f.path,c.period,c.metric].join('|'),label:c.period+' '+words(c.metric)+' · '+c.seasonalAdjustment+' · '+fmt(c.valueBps)+'% · saved '+timestamp(f.recordedAt)})));
  ui.macroDraft??={requestId:'',forecastKey:'',actualValue:'',seasonalAdjustment:'SA',releaseAt:'',sourceUrl:''};const d=ui.macroDraft;
  const input=(name,label,hint='')=>'<label class="form-field">'+esc(label)+'<input name="'+name+'" value="'+esc(d[name]??'')+'" required maxlength="'+(name==='sourceUrl'?2000:80)+'"><small>'+esc(hint)+'</small></label>';
  return '<section class="card section-space" id="macro-context"><p class="eyebrow">OFFICIAL PUBLIC MACRO SOURCES</p><h2>Rates, dollar & inflation benchmarks</h2><p>Daily saved context, with three independent source reads after 17:00 New York while Alpha runs. Broad USD is not DXY; inflation nowcasts are model estimates, not official releases or consensus forecasts.</p>'+
    '<div class="source-grid macro-source-grid">'+m.sources.map(s=>{
      const evidence=s.latest?.status==='OK'?s.latest:s.lastKnown,data=evidence?.data;
      let rows='';
      if(data&&s.id==='nominal')rows=table(['Source date','2Y %','5Y %','10Y %','30Y %'],data.rows.map(r=>[r.sourceDate,...[2,5,10,30].map(t=>fmt(r.ratesBps[t]))]));
      if(data&&s.id==='dollar')rows='<p>H.10 release '+esc(data.releaseDate)+' · Daily observations published weekly</p>'+table(['Source date','Broad USD index','USD per EUR','JPY per USD'],data.rows.map(r=>[r.sourceDate,fmt(r.broadIndexE4,10000,4),fmt(r.usdPerEuroE4,10000,4),fmt(r.yenPerUsdE4,10000,4)]));
      if(data&&s.id==='nowcast')rows=table(['Period','Model measure','Value %','Adjustment','Update label'],data.rows.map(r=>[r.period,words(r.metric),fmt(r.valueBps),r.seasonalAdjustment,r.updatedMonthDay]))+'<p class="hint">Update label omits year and time; receipt time is tracked separately. Blank cells remain unknown. PPI is not provided.</p>';
      return '<div class="source"><h3>'+esc({nominal:'Treasury nominal yields',dollar:'Federal Reserve broad dollar',nowcast:'Cleveland Fed inflation nowcasts'}[s.id])+'</h3><p><strong>'+esc(words(s.status))+(s.refreshOverdue?' · Read overdue':'')+'</strong></p><p class="hint">Latest attempt '+esc(timestamp(s.latest?.receivedAt))+(s.latest?.errorCode?' · '+esc(s.latest.errorCode):'')+'</p>'+(evidence?'<p>'+link(evidence.url,'Official source')+' · Received '+esc(timestamp(evidence.receivedAt))+'</p>'+(s.status!=='OK'?'<p class="error-text">Historical last-known values below; latest source attempt failed.</p>':'')+rows:'<p class="hint">No saved source values.</p>')+'</div>';
    }).join('')+'</div><p class="hint">'+esc(m.parCurveComparison.meaning)+' '+(m.parCurveComparison.nominalMinusRealBps===null?'Not calculated: dates differ or data are missing.':'Same-date spread '+esc(m.parCurveComparison.nominalMinusRealBps)+' bp on '+esc(m.parCurveComparison.sourceDate)+'.')+'</p>'+
    '<details class="section-space"><summary>Compare a released actual with a saved pre-release model</summary><p>Use the first official release for the same period, measure and seasonal adjustment. The comparison records your reported number; it does not verify a release, establish consensus surprise or authorize a trade.</p>'+
    '<form id="macro-comparison-form"><div class="form-grid">'+input('requestId','Comparison ID','Unique lowercase letters, digits and hyphens. Reuse the same ID if a save reply is interrupted.')+
    '<label class="form-field">Saved model benchmark<select name="forecastKey" required><option value="">Select saved benchmark</option>'+choices.map(c=>'<option value="'+esc(c.key)+'"'+(d.forecastKey===c.key?' selected':'')+'>'+esc(c.label)+'</option>').join('')+'</select></label>'+input('actualValue','Reported official actual (%)','For example, 0.30 means 0.30%, not 30%. No default actual is supplied.')+
    '<label class="form-field">Actual seasonal adjustment<select name="seasonalAdjustment">'+['SA','NSA'].map(v=>'<option'+(d.seasonalAdjustment===v?' selected':'')+'>'+v+'</option>').join('')+'</select></label>'+input('releaseAt','Actual release time (UTC)','YYYY-MM-DDTHH:mm:ss.sssZ; must be after the saved benchmark and no later than now.')+input('sourceUrl','Official release link','CPI: bls.gov; PCE: bea.gov. A link alone does not verify the number.')+'</div><div class="form-actions"><button class="button secondary" type="submit" value="PREVIEW">Preview difference</button><button class="button primary" id="save-macro-comparison" type="submit" value="SAVE"'+(!macroPreviewMatches(ui.macroPreview,d)?' disabled':'')+'>Save comparison</button></div></form><p class="error-text" id="macro-comparison-error"></p><div id="macro-comparison-preview">'+macroComparisonResult(ui.macroPreview)+'</div></details>'+
    '<details class="section-space"><summary>Saved model comparisons ('+m.comparisons.length+')</summary>'+(m.comparisons.length?m.comparisons.map(r=>'<article class="headline"><strong>'+esc(r.request.period+' '+words(r.request.metric))+'</strong>'+macroComparisonResult(r)+'</article>').join(''):'<p class="hint">No actuals have been recorded. Future outcomes remain unknown.</p>')+'</details></section>';
}
