import {esc,words,cents,timestamp,decimalInteger,whole} from './model.js';

export function snapshotRequest(d){
  const clock=name=>{if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d(?::\d\d)?$/.test(d[name]??''))throw Error('Enter a complete UTC date and time.');return new Date(d[name]+'Z').toISOString();};
  return {id:d.id.trim(),contractId:d.contractId,selectionPath:d.selectionPath,settingsFingerprint:d.settingsFingerprint,decisionAt:clock('decisionAt'),entryDeadlineAt:clock('entryDeadlineAt'),timeExitAt:clock('timeExitAt'),quantity:whole(d.quantity),entryLimitCents:decimalInteger(d.entryLimit),entryFeeCents:decimalInteger(d.entryFee,2,true),exitFeeCents:decimalInteger(d.exitFee,2,true),exitSlippageCents:decimalInteger(d.slippage,2,true),maxSpreadCents:decimalInteger(d.maxSpread)};
}
export function snapshotResult(r){
  if(!r)return '<p class="hint">Preview checks and model assumptions before freezing this paper plan.</p>';
  return `<div class="notice"><div><strong>${esc(words(r.status))} · Assumption-only model</strong><p>${esc(words(r.timing))}. Source qualification remains open. ${r.fills.length} modeled fill(s); 0 actual trades.</p></div></div><div class="grid-equal"><p>Cash ledger: <strong>${cents(r.account.cashLedgerCents)}</strong></p><p>Net modeled PnL: <strong>${cents(r.account.netPnlCents)}</strong></p><p>Open premium exposure: <strong>${cents(r.account.openPremiumExposureCents)}</strong></p></div>
    <p class="hint">Sale proceeds are unconfirmed as settled. Missing paths can contain an earlier stop or target. A modeled stop does not guarantee the loss.</p>
    ${r.fills.length?'<div class="table-scroll"><table><thead><tr><th>Modeled event</th><th>Received / source UTC</th><th>Price / fee</th><th>Cash after</th></tr></thead><tbody>'+r.fills.map(f=>`<tr><td>${esc(f.kind)} · ${esc(words(f.reason))}</td><td>${esc(f.receivedAt)}<br>${esc(f.sourceAt)}</td><td>${cents(f.priceCents)} / ${cents(f.feeCents)}</td><td>${cents(f.cashAfterCents)}</td></tr>`).join('')+'</tbody></table></div>':''}
    <details><summary>Quote decisions and raw clocks (${r.diagnostics.length})</summary><pre>${esc(JSON.stringify(r.diagnostics,null,2))}</pre></details>
    <h4>Candidate review notebook</h4><ul>${r.candidateLessons.map(l=>`<li>${esc(l.text)}</li>`).join('')}${(r.review?.candidateLessons??[]).map(l=>`<li>${esc(l.observation)} ${esc(l.nextCheck)}</li>`).join('')}</ul>${r.review?'<p>'+esc(r.review.outcome)+' · '+esc(r.review.hypotheses.join(' '))+'</p>':''}`;
}
export function snapshotPaperPanel(component,ui={}){
  if(component?.state!=='AVAILABLE')return '<section class="card section-space"><h2>Paper validation</h2><p>Saved source recovery is unavailable.</p></section>';
  const d=component.data,latest=d.latest;
  if(!ui.snapshotDraft){ui.snapshotChoices=structuredClone(latest?.quotes??[]);ui.snapshotDraft={id:'',contractId:'',selectionPath:latest?.path??'',decisionAt:'',entryDeadlineAt:'',timeExitAt:'',quantity:'1',entryLimit:'',entryFee:'',exitFee:'',slippage:'',maxSpread:'',settingsFingerprint:d.settingsFingerprint};}
  const v=ui.snapshotDraft,field=(name,label,type='text')=>`<label class="form-field">${label}<input name="${name}" type="${type}" value="${esc(v[name])}" ${['entryFee','exitFee','slippage'].includes(name)?'':'required'}></label>`;
  return `<section class="card section-space" id="paper-validation"><p class="eyebrow">THREE EVIDENCE GATES</p><h2>Paper validation</h2><div class="grid-equal"><p><strong>1. Qualified quotes: Open</strong><br>Source evidence incomplete.</p><p><strong>2. Adapter: Local implementation</strong><br>Assumption-only snapshots.</p><p><strong>3. Qualified full lifecycle: Open</strong><br>No qualified completed trade.</p></div><details><summary>What still prevents qualification</summary><ul>${d.sourceGaps.map(t=>'<li>'+esc(t)+'</li>').join('')}</ul></details>
    <p>Latest capture: ${esc(timestamp(latest?.capturedAt))} · ${latest?.quotes.filter(q=>q.usableSnapshot).length??0}/${latest?.quotes.length??0} snapshots pass receipt-time numerical checks. ${latest?.missingQuoteIds?.length??0} requested quote(s) missing. This is not execution qualification.</p>
    <details><summary>Latest quote quality and precise clocks</summary><div class="table-scroll"><table><thead><tr><th>Contract</th><th>Quote source UTC / receipt UTC</th><th>Receipt-time checks</th><th>Current freshness</th></tr></thead><tbody>${(latest?.quotes??[]).map(q=>`<tr><td>${esc(q.contract.symbol)} ${esc(q.contract.expiry)} ${esc(q.contract.strike)} ${esc(q.contract.type)}</td><td>${esc(q.sourceAt)}<br>${esc(q.receivedAt)}</td><td>${esc(q.blockers.map(words).join('; ')||'Numerical checks passed')}</td><td>${q.staleNow?'Stale':'Within 60s'}</td></tr>`).join('')}</tbody></table></div></details>
    <details><summary>Create an assumption-only paper plan</summary><p>Choose a future regular-session window or explicitly test a retrospective declaration. All form times are UTC. Freeze copies the active capital policy. Fees and slippage apply only to this paper plan; blanks stay unknown.</p><form id="snapshot-paper-form" class="form-grid">
    ${field('id','Unique plan ID (lowercase letters, numbers, hyphens)')}<label class="form-field">Contract<select name="contractId" required><option value="">Choose…</option>${(ui.snapshotChoices??[]).map(({contract:q})=>`<option value="${esc(q.id)}"${v.contractId===q.id?' selected':''}>${esc(q.symbol+' '+q.expiry+' '+q.strike+' '+q.type)}</option>`).join('')}</select></label><input type="hidden" name="selectionPath" value="${esc(v.selectionPath)}"><input type="hidden" name="settingsFingerprint" value="${esc(v.settingsFingerprint)}">
    ${field('decisionAt','Decision time (UTC)','datetime-local')}${field('entryDeadlineAt','Entry deadline (UTC)','datetime-local')}${field('timeExitAt','Time exit (UTC)','datetime-local')}${field('quantity','Whole contracts')}${field('entryLimit','Entry limit per share ($)')}${field('maxSpread','Maximum entry spread per share ($)')}${field('entryFee','Total entry fee ($, blank = unknown)')}${field('exitFee','Total exit fee ($, blank = unknown)')}${field('slippage','Exit slippage per share ($, blank = unknown)')}
    <div class="form-actions"><button class="button secondary" type="button" id="preview-snapshot-paper">Preview paper plan</button><button class="button" type="button" id="freeze-snapshot-paper"${ui.snapshotPreview?'':' disabled'}>Freeze local plan</button><button class="button secondary" type="button" id="discard-snapshot-paper">Discard draft</button></div></form><div id="snapshot-paper-preview">${snapshotResult(ui.snapshotPreview)}</div></details>
    <h3>Frozen plans and saved outcomes</h3>${d.cases.length?d.cases.map(c=>`<details><summary>${esc(c.plan.id)} · ${esc(words(c.current.status))} · ${c.snapshots.length} saved snapshot(s)</summary><p>Registered ${esc(timestamp(c.plan.createdAt))} · ${esc(c.plan.contract.symbol)} ${esc(c.plan.contract.expiry)} ${esc(c.plan.contract.strike)} ${esc(c.plan.contract.type)}</p><button class="button secondary small" data-snapshot-save="${esc(c.plan.id)}">Save observed result and review</button>${snapshotResult(c.current)}<details><summary>Immutable saved reports</summary>${c.snapshots.map(s=>'<p>'+esc(timestamp(s.recordedAt))+' · '+esc(words(s.report.status))+' · Independently recomputed</p><code>'+esc(s.path)+'</code>').join('')}</details></details>`).join(''):'<p class="hint">No local plans saved yet.</p>'}</section>`;
}
