import {esc,words,cents,timestamp,decimalInteger,whole} from './model.js';

export function snapshotRequest(d){
  const clock=name=>{if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d(?::\d\d)?$/.test(d[name]??''))throw Error('Enter a complete UTC date and time.');return new Date(d[name]+'Z').toISOString();};
  if(d.modelVersion==='V2'&&d.feeBasis==='ROBINHOOD_REVIEWED_20260910'&&((d.entryFee??'').trim()||(d.exitFee??'').trim()))throw Error('Leave manual fees blank for the reviewed fee model, or select manual fees.');
  return {...(d.modelVersion==='V2'?{modelVersion:'V2',feeBasis:d.feeBasis}:{}),id:d.id.trim(),contractId:d.contractId,selectionPath:d.selectionPath,settingsFingerprint:d.settingsFingerprint,decisionAt:clock('decisionAt'),entryDeadlineAt:clock('entryDeadlineAt'),timeExitAt:clock('timeExitAt'),quantity:whole(d.quantity),entryLimitCents:decimalInteger(d.entryLimit),entryFeeCents:decimalInteger(d.entryFee,2,true),exitFeeCents:decimalInteger(d.exitFee,2,true),exitSlippageCents:decimalInteger(d.slippage,2,true),maxSpreadCents:decimalInteger(d.maxSpread)};
}
export function snapshotResult(r){
  if(!r)return '<p class="hint">Preview checks and model assumptions before freezing this paper plan.</p>';
  return `<div class="notice"><div><strong>${esc(words(r.paperStage??r.status))} · Assumption-only model</strong><p>${esc(words(r.timing))}. ${r.paperStage?'Practical paper workflow; execution qualification is separate.':'Source qualification remains open.'} ${r.fills.length} modeled fill(s); 0 actual trades.</p></div></div><div class="grid-equal"><p>Cash ledger: <strong>${cents(r.account.cashLedgerCents)}</strong></p><p>Net modeled PnL: <strong>${cents(r.account.netPnlCents)}</strong></p><p>Open premium exposure: <strong>${cents(r.account.openPremiumExposureCents)}</strong></p></div>
    ${r.paperStage?`<p>Planned session closes at <strong>${esc(r.marketSession.closeLocal)} New York</strong> on ${esc(r.marketSession.date)} (${r.marketSession.lateCloseApplied?'saved chain enables late close':'standard close model'}). Fee basis: <strong>${esc(words(r.feeAssumption.id))}</strong>. Exit slippage: ${cents(r.exitSlippageCents)} per share, rounded down to the exit quote tick.</p><p class="hint">${r.feeAssumption.id==='DECLARED_FEES'?'Manual fee assumptions; blanks remain unknown.':'Assumes nonprofessional status and one execution per side. Fees are calculated at modeled entry and exit; actual broker fees and trade-date applicability are unverified.'}</p>`:''}
    <p class="hint">Sale proceeds are unconfirmed as settled. Missing paths can contain an earlier stop or target. A modeled stop does not guarantee the loss.</p>
    ${r.fills.length?'<div class="table-scroll"><table><thead><tr><th>Modeled event</th><th>Received / source UTC</th><th>Price / fee</th><th>Cash after</th></tr></thead><tbody>'+r.fills.map(f=>`<tr><td>${esc(f.kind)} · ${esc(words(f.reason))}</td><td>${esc(f.receivedAt)}<br>${esc(f.sourceAt)}</td><td>${cents(f.priceCents)} / ${cents(f.feeCents)}</td><td>${cents(f.cashAfterCents)}</td></tr>`).join('')+'</tbody></table></div>':''}
    <details><summary>Quote decisions and raw clocks (${r.diagnostics.length})</summary><pre>${esc(JSON.stringify(r.diagnostics,null,2))}</pre></details>
    <h4>Candidate review notebook</h4><ul>${r.candidateLessons.map(l=>`<li>${esc(l.text)}</li>`).join('')}${(r.review?.candidateLessons??[]).map(l=>`<li>${esc(l.observation)} ${esc(l.nextCheck)}</li>`).join('')}</ul>${r.review?'<p>'+esc(r.review.outcome)+' · '+esc(r.review.hypotheses.join(' '))+'</p>':''}`;
}
function observationControls(c,d){
  const o=d.observations?.rows.find(r=>r.planId===c.plan.id);
  if(!o)return c.plan.version==='OPTIONS_SNAPSHOT_PAPER_PLAN_V2'&&c.plan.decisionAt>d.assessedAt?`<p>Not enrolled. Enrollment must precede the decision time.</p><button class="button secondary small" data-paper-enroll="${esc(c.plan.id)}">Enroll paper observation</button>`:'<p class="hint">Not enrolled; prospective V2 enrollment closes at the decision time.</p>';
  const active=['AWAITING_WINDOW','OBSERVING','FINALIZATION_PENDING'].includes(o.state);
  return `<div class="notice"><div><strong>Observation: ${esc(words(o.state))}</strong><p>${o.purpose==='PIPELINE_REHEARSAL_NOT_SIGNAL'?'Engineering pipeline rehearsal; this is not a directional recommendation.':'Owner-declared paper research; not a qualified trading signal.'}</p><p>Enrolled ${esc(timestamp(o.enrolledAt))}; cutoff ${esc(timestamp(o.monitorUntilAt))}. Tracking: ${esc(words(o.tracking))}. Automatic reports: ${o.automaticReports}.</p><p>${o.lastAutomaticReport?'Last saved '+esc(timestamp(o.lastAutomaticReport.recordedAt))+' · '+esc(words(o.lastAutomaticReport.status)):'No automatic report yet. Enrollment is not evidence of a completed capture.'}</p></div></div>${savedProcessReview(o.lastAutomaticReport)}${active?`<button class="button secondary small" data-paper-cancel="${esc(c.plan.id)}">Cancel paper observation</button><p class="hint">Cancellation stops observation. It does not close a modeled position or change saved reports.</p>`:''}`;
}
export function savedProcessReview(saved){
  const r=saved?.processReview;if(!r)return '';
  return `<section class="lesson-card"><h4>Saved observation review</h4><p>${esc(r.explanation)}</p><p>Source cutoff: ${esc(saved.trigger.cutoffAt)}. Saved at: ${esc(saved.recordedAt)}. This saved result is separate from the current reassessment below.</p><p>${r.modeledFills} modeled fill(s); ${r.inWindowQuoteCount} entry-window quote(s). Net modeled PnL: ${cents(r.netPnlCents)}. Open premium exposure: ${cents(r.openPremiumExposureCents)}.</p>${r.blockerCounts.length?'<ul>'+r.blockerCounts.map(b=>'<li>'+esc(words(b.code))+' · '+b.count+' observation(s)</li>').join('')+'</ul>':''}<p><strong>Next check:</strong> ${esc(r.nextCheck)}</p><p class="hint">Candidate process lesson only. Cause and strategy benefit are not established.</p></section>`;
}
export function localPaperServicePanel(s){
  if(!s)return '';
  const failed=s.status==='FAILED'||s.status==='PARTIAL';
  return `<div class="notice"><div><strong>Local paper finalization: ${esc(words(s.enabled?s.status:'DISABLED'))}</strong><p>Last check: ${esc(timestamp(s.checkedAt))}. ${s.enabled?'The running local service checks expired enrollments on its existing minute cycle, after any active pass finishes.':'No local background check is active in this server.'} It reads saved evidence only; no quote requests or orders.</p>${failed?'<p>Paper recovery needs attention. Existing reports and public collection are preserved. '+esc(s.error??'One or more plans could not be finalized.')+'</p>':''}${(s.results??[]).filter(r=>r.error).map(r=>'<p>'+esc(r.planId)+' · '+esc(r.error)+'</p>').join('')}</div></div>`;
}
function frozenPaperTerms(p){return `<p>Frozen entry window: <strong>${esc(timestamp(p.decisionAt))} – ${esc(timestamp(p.entryDeadlineAt))}</strong>. Modeled time exit: <strong>${esc(timestamp(p.timeExitAt))}</strong>.</p><p>${p.quantity} contract(s); entry limit ${cents(p.entryLimitCents)} per share; maximum entry spread ${cents(p.maxSpreadCents)} per share. Premium stop: ${p.settings.stopLossBps/100}% below modeled entry; net target: ${p.settings.rewardMultipleMilliR/1000} R. Actual exit depends on later eligible quotes.</p>`;}
export function snapshotPaperPanel(component,ui={},localService=null){
  const servicePanel=localPaperServicePanel(localService);
  if(component?.state!=='AVAILABLE')return '<section class="card section-space"><h2>Paper validation</h2>'+servicePanel+'<p>Saved source recovery is unavailable.</p></section>';
  const d=component.data,latest=d.latest;
  if(!ui.snapshotDraft){ui.snapshotChoices=structuredClone(latest?.quotes??[]);ui.snapshotDraft={modelVersion:'V2',feeBasis:'ROBINHOOD_REVIEWED_20260910',id:'',contractId:'',selectionPath:latest?.path??'',decisionAt:'',entryDeadlineAt:'',timeExitAt:'',quantity:'1',entryLimit:'',entryFee:'',exitFee:'',slippage:'',maxSpread:'',settingsFingerprint:d.settingsFingerprint};}
  const v=ui.snapshotDraft,field=(name,label,type='text')=>`<label class="form-field">${label}<input name="${name}" type="${type}" value="${esc(v[name])}" ${['entryFee','exitFee','slippage'].includes(name)?'':'required'}></label>`;
  return `<section class="card section-space" id="paper-validation"><p class="eyebrow">PRACTICAL PAPER WORKFLOW</p><h2>Paper validation</h2>${servicePanel}<p>The local snapshot model is available. Freeze an explicit plan, then use later saved quotes to model entry, exit and a review. Valid snapshots can enter this model while strict execution qualification remains separate.</p><p class="hint">Enroll a future V2 plan to follow its contract through existing bounded Host captures. Each new capture saves an independent result and candidate review. This desk does not run continuous quote polling. Missing observations remain gaps; expired windows finalize through the running local service or the next Host publication.</p><details><summary>Strict execution qualification (separate)</summary><div class="grid-equal"><p><strong>1. Qualified quotes: Open</strong><br>Source evidence incomplete.</p><p><strong>2. Adapter: Local implementation</strong><br>Assumption-only snapshots.</p><p><strong>3. Qualified full lifecycle: Open</strong><br>No qualified completed trade.</p></div><details><summary>What still prevents qualification</summary><ul>${d.sourceGaps.map(t=>'<li>'+esc(t)+'</li>').join('')}</ul></details></details>
    <p>Latest capture: ${esc(timestamp(latest?.capturedAt))} · ${latest?.quotes.filter(q=>q.usableSnapshot).length??0}/${latest?.quotes.length??0} snapshots pass receipt-time numerical checks. ${latest?.missingQuoteIds?.length??0} requested quote(s) missing. This is not execution qualification.</p>
    <details><summary>Latest quote quality and precise clocks</summary><div class="table-scroll"><table><thead><tr><th>Contract</th><th>Quote source UTC / receipt UTC</th><th>Receipt-time checks</th><th>Source session / current freshness</th></tr></thead><tbody>${(latest?.quotes??[]).map(q=>`<tr><td>${esc(q.contract.symbol)} ${esc(q.contract.expiry)} ${esc(q.contract.strike)} ${esc(q.contract.type)}</td><td>${esc(q.sourceAt)}<br>${esc(q.receivedAt)}</td><td>${esc(q.blockers.map(words).join('; ')||'Numerical checks passed')}</td><td>${esc(q.session?.closeLocal??'Unknown')} New York close<br>${q.staleNow?'Stale':'Within 60s'}</td></tr>`).join('')}</tbody></table></div></details>
    <details><summary>Create an assumption-only paper plan</summary><p>Choose a future supported-session window or explicitly test a retrospective declaration. All form times are UTC. Freeze copies the active capital policy. Fees and slippage apply only to this paper plan. Choose the dated fee model or enter manual fees. Slippage is required for a modeled entry; blank stays unknown.</p><form id="snapshot-paper-form" class="form-grid"><input type="hidden" name="modelVersion" value="V2"><label class="form-field">Paper fee assumption<select name="feeBasis"><option value="ROBINHOOD_REVIEWED_20260910"${v.feeBasis==='ROBINHOOD_REVIEWED_20260910'?' selected':''}>Robinhood reviewed September 10, 2026 (estimated)</option><option value="DECLARED_FEES"${v.feeBasis==='DECLARED_FEES'?' selected':''}>Manual fees (blank = unknown)</option></select></label><p class="hint">Reviewed model: nonprofessional, one execution per side; charges may differ. <a href="https://robinhood.com/us/en/support/articles/trading-fees-on-robinhood/" target="_blank" rel="noreferrer">Fee source</a>. Leave both manual fee fields blank when using this model.</p>
    ${field('id','Unique plan ID (lowercase letters, numbers, hyphens)')}<label class="form-field">Contract<select name="contractId" required><option value="">Choose…</option>${(ui.snapshotChoices??[]).map(({contract:q})=>`<option value="${esc(q.id)}"${v.contractId===q.id?' selected':''}>${esc(q.symbol+' '+q.expiry+' '+q.strike+' '+q.type)}</option>`).join('')}</select></label><input type="hidden" name="selectionPath" value="${esc(v.selectionPath)}"><input type="hidden" name="settingsFingerprint" value="${esc(v.settingsFingerprint)}">
    ${field('decisionAt','Decision time (UTC)','datetime-local')}${field('entryDeadlineAt','Entry deadline (UTC)','datetime-local')}${field('timeExitAt','Time exit (UTC)','datetime-local')}${field('quantity','Whole contracts')}${field('entryLimit','Entry limit per share ($)')}${field('maxSpread','Maximum entry spread per share ($)')}${field('entryFee','Manual total entry fee ($)')}${field('exitFee','Manual total exit fee ($)')}${field('slippage','Exit slippage per share ($, blank = unknown)')}
    <div class="form-actions"><button class="button secondary" type="button" id="preview-snapshot-paper">Preview paper plan</button><button class="button" type="button" id="freeze-snapshot-paper"${ui.snapshotPreview?'':' disabled'}>Freeze local plan</button><button class="button secondary" type="button" id="discard-snapshot-paper">Discard draft</button></div></form><div id="snapshot-paper-preview">${snapshotResult(ui.snapshotPreview)}</div></details>
    <h3>Frozen plans and saved outcomes</h3>${d.cases.length?d.cases.map(c=>`<details data-disclosure-key="paper-plan-${esc(c.plan.id)}"><summary>${esc(c.plan.id)} · ${esc(words(c.current.paperStage??c.current.status))} · ${c.snapshots.length} saved snapshot(s)</summary><p>Registered ${esc(timestamp(c.plan.createdAt))} · ${esc(c.plan.contract.symbol)} ${esc(c.plan.contract.expiry)} ${esc(c.plan.contract.strike)} ${esc(c.plan.contract.type)}</p>${frozenPaperTerms(c.plan)}${observationControls(c,d)}<button class="button secondary small" data-snapshot-save="${esc(c.plan.id)}">Save observed result and review</button>${snapshotResult(c.current)}<details><summary>Immutable saved reports</summary>${c.snapshots.map(s=>'<p>'+esc(timestamp(s.recordedAt))+' · '+esc(words(s.report.status))+' · '+(s.observation?'Automatic '+esc(words(s.observation.kind)):'Manual snapshot')+' · Independently recomputed</p><code>'+esc(s.path)+'</code>').join('')}</details></details>`).join(''):'<p class="hint">No local plans saved yet.</p>'}</section>`;
}
