import {esc,timestamp} from './model.js';
import {lookupWorldModel} from './world-model-lookup.js';
import {worldKnowledgeCard} from './world-model.js';
import {STORY_CHANGES,storylinePreviewMatches} from './storyline-model.js';

const list=xs=>'<ul>'+xs.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';
const option=(v,label,current)=>'<option value="'+esc(v)+'"'+(v===current?' selected':'')+'>'+esc(label)+'</option>';
export function newStorylineDraft(news,linkId){return {linkId,newsRef:news.newsRef,newsFingerprint:news.newsFingerprint,themes:[],knowledgeIds:[],reviewedBy:{kind:'OWNER',name:'Owner'},humanConfirmed:false,linkReason:'',storyChangeType:'NOT_CLASSIFIED',limitations:[],supersedes:''};}
export function storylineNewsChoices(data){
  const map=new Map((data?.news??[]).map(n=>[n.key,n]));for(const r of data?.records??[])if(r.news&&!map.has(r.news.key))map.set(r.news.key,r.news);return [...map.values()];
}
export function storylineSummary(summary,c){
  const n=summary.news;
  return '<article class="story-summary"><h3>Reading context · '+esc(summary.outcome)+'</h3><p><strong>News:</strong> '+esc(n?.title??'Original news reference unavailable')+'</p><p>'+esc(n?.coverageType??summary.coverageType??'UNKNOWN')+' · published '+esc(timestamp(n?.publishedAt??summary.publishedAt))+' · received '+esc(timestamp(n?.receivedAt??summary.receivedAt))+'</p>'+
    '<p><strong>Linked themes:</strong> '+esc(summary.themes.join(', ')||'None')+'</p><h4>Existing structure · selected approved knowledge</h4>'+
    (summary.knowledge.map(i=>(i.knowledgeType==='CONFLICT'?'<p class="notice">UNRESOLVED CONFLICT — both claims remain; no canonical winner.</p>':'')+worldKnowledgeCard(i,c)).join('')||'<p>No relevant approved knowledge selected.</p>')+
    '<h4>What this news adds</h4><p>Source material only; linking does not verify its meaning or novelty.</p><p>'+esc(n?.text??'Original material unavailable; no replacement was substituted.')+'</p><h4>What remains unknown / limitations</h4>'+list(summary.limitations)+'<p><strong>No trade implication.</strong> Human selection does not upgrade evidence. No current-state fact is created.</p></article>';
}
export function storylinePanel(state,ui){
  const data=state.storylines?.data,c=state.macroWorldModel?.data;
  if(!data||!c)return '<section class="card section-space" id="macro-storyline"><h2>Macro storyline</h2><p>Saved news or approved catalog unavailable. No automatic fallback.</p></section>';
  const choices=storylineNewsChoices(data),d=ui.storyDraft,n=choices.find(n=>n.key===ui.storyNewsKey),filters=ui.storyFilters??{},hasQuery=Object.values(filters).some(Boolean);
  const found=hasQuery?lookupWorldModel(c,filters):{items:[],edges:[]},matches=[...found.items,...found.edges];
  const suggestedThemes=c.themes.filter(t=>found.items.some(i=>i.themeId===t.themeId));
  const selected=(d?.knowledgeIds??[]).map(id=>[...c.items,...c.edges].find(i=>i.id===id)).filter(Boolean);
  const records=data.records.filter(r=>!n||r.newsId===n.newsId&&r.newsSource===n.newsSource);
  return '<section class="card section-space" id="macro-storyline"><h2>Macro storyline</h2><p>Saved news → explicit search → reviewer selection → preview → explicit save. Context only; no automatic classification.</p><label class="form-field">Saved news / source material<select id="story-news">'+option('','Select a saved item',ui.storyNewsKey)+choices.map(x=>option(x.key,x.newsSource+' · '+x.title+' · '+x.coverageType,ui.storyNewsKey)).join('')+'</select></label><p class="hint">Up to 500 recent saved materials; '+data.omittedNews+' omitted from this selector. Existing links retain their exact source references.</p>'+
    (n&&d?'<p><strong>'+esc(n.title)+'</strong> · '+esc(n.coverageType)+'</p><p class="hint wm-id">Source '+esc(n.newsSource)+' · published '+esc(timestamp(n.publishedAt))+' · received '+esc(timestamp(n.receivedAt))+'<br>News fingerprint '+esc(n.newsFingerprint)+'</p><div class="story-search"><label class="form-field">Search approved context<input id="story-query" maxlength="160" value="'+esc(filters.keyword??'')+'" placeholder="Enter an explicit keyword or actor from this material"></label><div class="wm-filters"><label class="form-field">Suggestion theme filter<select id="story-theme-filter">'+option('','All',filters.theme)+c.themes.map(t=>option(t.themeId,t.title,filters.theme)).join('')+'</select></label><label class="form-field">Suggestion type filter<select id="story-type-filter">'+option('','All',filters.knowledgeType)+c.knowledgeTypes.map(t=>option(t,t,filters.knowledgeType)).join('')+'</select></label></div><p><strong>SUGGESTED_NOT_CONFIRMED</strong> · '+matches.length+' matches. Exact entered query; catalog order, no semantic ranking.</p><p>Suggested themes: '+esc(suggestedThemes.map(t=>t.themeId+' '+t.title).join(' · ')||'No suggestion / limited coverage')+'. Themes are never selected automatically; an edge never adds another theme.</p></div>'+
    '<form id="storyline-form"><fieldset><legend>Manual theme selection (zero is allowed)</legend>'+c.themes.map(t=>'<label class="check-row"><input type="checkbox" name="theme" value="'+t.themeId+'"'+(d.themes.includes(t.themeId)?' checked':'')+'>'+esc(t.themeId+' · '+t.title)+'</label>').join('')+'</fieldset><fieldset><legend>Suggested approved knowledge — choose manually</legend>'+matches.map(i=>'<label class="check-row"><input type="checkbox" name="knowledge" value="'+esc(i.id)+'"'+(d.knowledgeIds.includes(i.id)?' checked':'')+'><span>'+esc(i.reviewLabel+' · '+(i.title??(i.fromTheme+' → '+i.toTheme)))+'<small>'+esc((i.knowledgeType??'EDGE')+' · '+i.evidenceStatus)+'</small></span></label>').join('')+(!matches.length?'<p>No suggestion / limited coverage. Search manually or save a reviewed zero-link outcome.</p>':'')+'</fieldset><details data-disclosure-key="story-selection" open><summary>Selected knowledge ('+selected.length+') · evidence and provenance</summary>'+selected.map(i=>'<div>'+(i.knowledgeType==='CONFLICT'?'<p class="notice">UNRESOLVED CONFLICT — no canonical winner.</p>':'')+worldKnowledgeCard(i,c)+'<button type="button" class="link-button" data-story-remove="'+esc(i.id)+'">Remove '+esc(i.reviewLabel)+'</button></div>').join('')+'</details>'+
    '<label class="form-field">What changed? (reviewer choice)<select name="storyChangeType">'+STORY_CHANGES.map(x=>option(x,x,d.storyChangeType)).join('')+'</select></label><label class="form-field">Link reason<textarea name="linkReason" maxlength="1200" rows="3" required>'+esc(d.linkReason)+'</textarea></label><p class="hint">'+(ui.storyReasonDraft?'DRAFT_REASON — review and edit before accepting.':'Reviewer-authored reason; not fact authentication.')+'</p><button class="link-button" type="button" id="story-draft-reason">Draft reason from selected references</button><label class="form-field">Remaining unknowns / limitations (one per line)<textarea name="limitations" rows="3">'+esc(d.limitations.join('\n'))+'</textarea></label><div class="wm-filters"><label class="form-field">Reviewer role<select name="reviewerKind">'+option('OWNER','Owner',d.reviewedBy.kind)+option('HUMAN_REVIEWER','Human reviewer',d.reviewedBy.kind)+'</select></label><label class="form-field">Reviewer name<input name="reviewerName" maxlength="100" value="'+esc(d.reviewedBy.name)+'" required></label></div><label class="check-row"><input type="checkbox" name="humanConfirmed"'+(d.humanConfirmed?' checked':'')+'>I personally reviewed this selection and accept the reason. This is context, not causal verification.</label><p class="hint">Host-generated suggestions cannot attest human review. Review time is the actual save time. Revision of '+esc(d.supersedes||'None')+'.</p><details><summary>Reasoning boundaries applied to every link</summary>'+list(c.guardrails.filter(g=>g.disposition==='REJECT_FROM_RUNTIME').map(g=>g.reviewLabel+': '+g.reason))+'</details><div class="form-actions"><button class="button secondary" value="PREVIEW">Preview link</button><button id="story-save" class="button primary" value="SAVE"'+(!d.humanConfirmed||!storylinePreviewMatches(ui.storyPreview,d)?' disabled':'')+'>Save reviewed link</button></div></form><div id="story-preview">'+(ui.storyPreview?'<p>SUGGESTED_NOT_CONFIRMED · preview only</p>'+storylineSummary(ui.storyPreview.summary,c):'')+'</div>':'')+
    '<p id="story-error" class="error-text"></p><h3>Saved links / revisions</h3>'+records.map(r=>'<details data-disclosure-key="story-saved-'+esc(r.linkId)+'"><summary>'+esc(r.linkId+' · v'+r.version+' · '+r.outcome)+'</summary><p>'+esc(r.status)+' · '+esc(r.reviewedBy.kind+': '+r.reviewedBy.name)+' · '+esc(timestamp(r.reviewedAt))+'</p><p>Reviewer-attested; not machine authentication. Recovery: '+esc(r.recovery)+'</p><p class="wm-id">News fingerprint '+esc(r.newsFingerprint)+'<br>Supersedes '+esc(r.supersedes||'None')+'</p><p>What changed: '+esc(r.storyChangeType)+'<br>Reason: '+esc(r.linkReason)+'</p>'+storylineSummary(r,c)+'<button class="button secondary" data-story-revise="'+esc(r.linkId)+'"'+(!r.news?' disabled':'')+'>Append revision</button></details>').join('')+(!records.length?'<p>No reviewed link saved for this selection. Suggestions are not saved links.</p>':'')+list(data.errors)+'</section>';
}
