import {journalForm,registerDefaults,buildCommand} from './forms.js';
import {esc,words,timestamp} from './model.js';
import {sourceBackrefs} from './source-comparison.js';

export const conditionDefaults=(kind,id)=>({id,kind,basis:'',checkAt:'',missingAction:'',target:'',comparator:'',threshold:'',warningThreshold:'',confirmation:'',confirmationMinutes:'',confirmationCount:'',bufferUsd:'',eventKey:'',metric:'',period:'',unit:'',releaseVersion:'',releaseAt:'',expectationRef:'',expectationValue:'',source:'',invalidation:''});
export const thesisDefaults=()=>({version:'OPTIONS_TRADE_THESIS_V1',template:'CUSTOM',decisionId:'',tradeDate:'',realizationStartAt:'',realizationEndAt:'',nextCheckAt:'',holdThroughEvent:'',manualFallback:'',conditions:[]});
export const eventEntryDefaults=()=>({phase:'',conditionId:'',calendarVerifiedAt:'',calendarSource:'',expectationStatus:'',expectationBasis:'',differenceBasis:'',supportingScenario:'',neutralScenario:'',reverseScenario:'',counterexample:'',reviewer:'',gapRiskAccepted:false,closedMarketRiskAccepted:false});
const field=(name,label,value='',hint='')=>`<label>${label}<input name="${esc(name)}" value="${esc(value)}" autocomplete="off"><small>${esc(hint)}</small></label>`;
const choice=(name,label,value,options)=>`<label>${label}<select name="${esc(name)}">${options.map(([k,v])=>`<option value="${esc(k)}"${k===value?' selected':''}>${esc(v)}</option>`).join('')}</select></label>`;
const time=(name,label,value)=>field(name,label,value,'Explicit UTC ISO time (…Z); session checks/display use America/New_York. No time is chosen for you.');
const compareFields=(p,c)=>choice(p+'comparator','Invalidate when',c.comparator,[['','Choose comparison'],['AT_OR_BELOW','At or below'],['AT_OR_ABOVE','At or above']])+field(p+'threshold','Invalidation boundary',c.threshold)+field(p+'warningThreshold','Optional warning boundary',c.warningThreshold,'Blank = no warning threshold.');
export function eventEntrySummary(r){
  if(!r)return '<p>Default major-event waiting applies. No saved event approach has been assessed.</p>';
  return `<div class="notice" data-event-entry-summary><div><strong>Event approach: ${r.researchApproach==='PRE_EVENT'?'Pre-event anticipation':r.phase==='POST_EVENT'?'Post-event confirmation':'Not configured — conservative default'}</strong><p>${esc(r.explanation)}</p><p>${esc(r.kind)} · Assessed ${esc(timestamp(r.assessedAt))} · Next manual check ${esc(timestamp(r.nextCheckAt))}</p>${r.blockers.length?'<ul>'+r.blockers.map(x=>'<li><code>'+esc(x)+'</code></li>').join('')+'</ul>':''}<p>${r.risks.map(esc).join('<br>')}</p><p>Fact review starts after actual publication. Option-price exits need qualified tradable quotes; opening review is not a fill guarantee. No automatic opening monitoring.</p></div></div>`;
}
function eventEntryFields(t){
  const e=t.eventEntry??eventEntryDefaults();
  return `<details data-disclosure-key="event-entry" open><summary>Event approach and entry confirmation</summary>${choice('entry.phase','Event approach',e.phase,[['','Not configured — default wait'],['PRE_EVENT','Pre-event anticipation'],['POST_EVENT','Post-event confirmation']])}<p>Research exposure alone grants no exception. Saved legacy records retain their original behavior. Paper PRE_EVENT (exit before release) is a separate, unchanged workflow.</p>${e.phase==='PRE_EVENT'?`<div class="form-grid">${choice('entry.conditionId','Original event condition',e.conditionId,[['','Choose enabled condition'],...t.conditions.filter(c=>c.kind!=='PRICE').map(c=>[c.id,c.id])])}${time('entry.calendarVerifiedAt','Official schedule actually checked at',e.calendarVerifiedAt)}${field('entry.calendarSource','Official schedule reference',e.calendarSource)}${choice('entry.expectationStatus','Reliable expectation available?',e.expectationStatus,[['','Not recorded'],['AVAILABLE','Available — cite saved version'],['UNAVAILABLE','No reliable expectation — explicitly recorded']])}${[['expectationBasis','Expectation source, period, units and update time; or documented absence'],['differenceBasis','Evidence for the differing thesis; leave blank if unknown'],['supportingScenario','Supporting outcome'],['neutralScenario','Neutral / no-surprise outcome'],['reverseScenario','Reverse outcome'],['counterexample','Strongest counterexample, including option economics'],['reviewer','Who will perform fact / opening checks and manual fallback']].map(([k,label])=>field('entry.'+k,label,e[k])).join('')}<label class="check-row"><input type="checkbox" name="entry.gapRiskAccepted"${e.gapRiskAccepted?' checked':''}> I accept overnight / gap exposure under this original plan.</label><label class="check-row"><input type="checkbox" name="entry.closedMarketRiskAccepted"${e.closedMarketRiskAccepted?' checked':''}> I understand no stop execution is possible while the option market is closed.</label></div><p>Reuse the original thesis, event identity, realization window, stop, target, latest exit and data-interruption arrangement below. No thresholds are supplied. Text completeness is not semantic authentication or predictive edge.</p>`:''}</details>`;
}
export function thesisPlannerPanel(s,ui){
  const t=ui.thesisDraft??thesisDefaults(),f=ui.thesisFields??{...registerDefaults(),includePlan:true};
  const raw=journalForm('register',{trades:[]},f),base=raw.slice(raw.indexOf('<div class="form-grid">')+'<div class="form-grid">'.length,raw.indexOf('</div><div class="form-actions">'));
  const records=s.manual?.data?.planRecords??[],frozen=new Set(s.manual?.data?.trades.map(t=>t.tradeId)??[]),drafts=new Map();
  for(const r of records)if(r.command.type==='SAVE_PLAN_DRAFT'&&!frozen.has(r.command.tradeId))drafts.set(r.command.tradeId,r);
  return `<section class="card section-space"><h2>Trade thesis & invalidation</h2><p>Optional for new plans. Save an incomplete draft, then review and freeze before entry. Existing plans remain unchanged. <a href="#macro-playbook">Use the existing Macro playbook worksheet →</a></p>
    ${!s.manual?.data?'<p class="error-text">Initialize or recover the existing journal before saving.</p>':''}
    <form id="thesis-plan-form"><details data-disclosure-key="thesis-contract" open><summary>Original contract, thesis and exit fields</summary><p>These are the existing journal fields. Stop, target and latest exit are stored once. Use the risk calculation above or enter your explicitly confirmed plan.</p><div class="form-grid">${base}</div></details>
    <div class="form-grid">${choice('thesis.template','Timing preference',t.template,[['CUSTOM','Custom'],['CLOSE_ENTRY_OPEN_REVIEW','Prefer closing entry; review exits after opening']])}${field('thesis.decisionId','Optional decision / note ID',t.decisionId)}${field('thesis.tradeDate','Planned entry trading date',t.tradeDate,'YYYY-MM-DD; separate from realization window and contract expiry.')}${time('thesis.realizationStartAt','Expected realization starts',t.realizationStartAt)}${time('thesis.realizationEndAt','Expected realization deadline',t.realizationEndAt)}${time('thesis.nextCheckAt','Next manual check',t.nextCheckAt)}${choice('thesis.holdThroughEvent','Hold across the relevant release?',t.holdThroughEvent,[['','Not configured'],['YES','Yes — explicitly planned'],['NO','No'],['NOT_APPLICABLE','No relevant event declared']])}${field('thesis.manualFallback','Data interruption / manual verification arrangement',t.manualFallback)}</div>
    <p class="hint">Preference only: enter only when independently qualified; no daily trade obligation and no mandatory next-open liquidation. Other exit triggers still apply at other times. No automatic opening collector or alert is enabled. No timing advantage is claimed.</p>
    ${eventEntryFields(t)}${eventEntrySummary((s.eventEntryPlans?.data??[]).find(r=>r.tradeId===f.tradeId))}<p class="hint">Assessment refers to the last saved version. Save edited drafts to refresh its missing conditions.</p>
    ${[['PRICE','price','Price boundary'],['EVENT_NUMERIC','event','Numeric event release'],['OWNER_CONFIRMED','owner','Source-based manual condition']].map(([kind,id,label])=>{
      const c=t.conditions.find(c=>c.id===id),v=c??conditionDefaults(kind,id),p='condition.'+id+'.';
      return `<details data-disclosure-key="thesis-${id}"${c?' open':''}><summary>${label}</summary><label class="check-row"><input type="checkbox" name="enable.${id}"${c?' checked':''}> Enable ${label.toLowerCase()}</label>${c?`<div class="form-grid">${field(p+'basis','Evidence / rationale',v.basis)}${time(p+'checkAt','Condition check starts',v.checkAt)}${field(p+'missingAction','If evidence is missing',v.missingAction)}${kind==='PRICE'?choice(p+'target','Price identity',v.target,[['','Choose identity'],['ETF','This traded ETF'],['OPTION_BID','This exact option contract bid']])+compareFields(p,v)+choice(p+'confirmation','Trigger method',v.confirmation,[['','Choose method'],['TOUCH','Qualified saved price crosses boundary'],['CLOSE','Completed ETF closes']])+field(p+'confirmationMinutes','Close interval in minutes',v.confirmationMinutes,'Existing validator supports 5 only; required only for Close.')+field(p+'confirmationCount','Required consecutive closes',v.confirmationCount,'Required only for Close; no default.')+field(p+'bufferUsd','Optional explicit dollar buffer',v.bufferUsd,'Blank = no buffer configured; never inferred from volatility.'):kind==='EVENT_NUMERIC'?field(p+'eventKey','Event identity',v.eventKey)+field(p+'metric','Metric / seasonal-adjustment identity',v.metric)+field(p+'period','Observation period',v.period)+field(p+'unit','Exact unit',v.unit)+field(p+'releaseVersion','Release vintage / version',v.releaseVersion)+time(p+'releaseAt','Declared release time',v.releaseAt)+field(p+'expectationRef','Pre-release expectation version / reference',v.expectationRef)+field(p+'expectationValue','Pre-release expected value',v.expectationValue)+field(p+'source','Expected release source',v.source)+compareFields(p,v):(t.eventEntry?.phase==='PRE_EVENT'?field(p+'eventKey','Event identity',v.eventKey)+time(p+'releaseAt','Scheduled release time',v.releaseAt):'')+field(p+'invalidation','Exact factual condition that invalidates the thesis',v.invalidation)+field(p+'source','Evidence source to check',v.source)}</div>`:''}</details>`;
    }).join('')}<div class="form-actions"><button type="submit" value="DRAFT" class="button secondary" formnovalidate>Save plan draft</button><button type="submit" value="PREVIEW" class="button secondary" formnovalidate>Preview frozen plan</button><button type="submit" value="CONFIRM" class="button primary" formnovalidate${ui.thesisPreview?'':' disabled'}>Confirm & freeze plan</button></div><p id="thesis-plan-error" class="error-text" role="alert"></p></form>
    <div id="thesis-plan-preview">${ui.thesisPreview?'<p>Configuration checked. Confirm to freeze the exact snapshot. This is plan completeness, not entry approval.</p><p>'+esc(ui.thesisPreview.command.plan.thesis)+' · '+t.conditions.length+' enabled condition(s). Entry deadline '+esc(timestamp(ui.thesisPreview.command.plan.entryDeadlineAt))+' · Latest exit '+esc(timestamp(ui.thesisPreview.command.plan.timeExitAt))+'</p><details><summary>Exact plan to freeze</summary><pre>'+esc(JSON.stringify(ui.thesisPreview.command,null,2))+'</pre></details>':'<p class="hint">Missing required configuration is saved as a draft, never an executable complete plan.</p>'}</div>
    <details data-disclosure-key="thesis-drafts"><summary>Saved drafts (${drafts.size}) and frozen plans</summary>${[...drafts.values()].map(r=>`<p><button class="link-button" data-thesis-draft="${esc(r.command.tradeId)}">Resume ${esc(r.command.tradeId)}</button> · saved ${esc(timestamp(r.savedAt))}</p>`).join('')}${(s.manual?.data?.trades??[]).filter(t=>t.plan?.invalidation).map(t=>`<p>${esc(t.tradeId)} · Frozen ${esc(timestamp(t.registeredAt))} · ${esc(words(t.planTiming))} · <a href="#journal">Review in journal →</a></p>`).join('')}</details>${sourceBackrefs(s.sourceComparisons?.data)}</section>`;
}
export function updateThesisDraft(ui,name,value){
  ui.thesisDraft??=thesisDefaults();ui.thesisFields??={...registerDefaults(),includePlan:true};
  if(name.startsWith('entry.')){ui.thesisDraft.eventEntry??=eventEntryDefaults();ui.thesisDraft.eventEntry[name.slice(6)]=value;}
  else if(name.startsWith('thesis.'))ui.thesisDraft[name.slice(7)]=value;
  else if(name.startsWith('enable.')){const id=name.slice(7);ui.thesisDraft.conditions=ui.thesisDraft.conditions.filter(c=>c.id!==id);if(value)ui.thesisDraft.conditions.push(conditionDefaults({price:'PRICE',event:'EVENT_NUMERIC',owner:'OWNER_CONFIRMED'}[id],id));}
  else if(name.startsWith('condition.')){const [,id,key]=name.split('.');const c=ui.thesisDraft.conditions.find(c=>c.id===id);if(c)c[key]=value;}
  else ui.thesisFields[name]=value;
  ui.thesisPreview=null;ui.thesisRequestId=null;
}
export function thesisPlanCommand(ui,mode,requestId){
  const fields=structuredClone(ui.thesisFields??{...registerDefaults(),includePlan:true}),thesis=structuredClone(ui.thesisDraft??thesisDefaults());
  if(mode==='DRAFT')return {type:'SAVE_PLAN_DRAFT',requestId,tradeId:fields.tradeId,draft:{fields,thesis}};
  const c=buildCommand('register',fields,requestId);if(!c.plan)throw Error('Include the original plan and exits before confirmation.');c.plan.invalidation=thesis;return c;
}
const actionLabel={EXIT_CONDITION_TRIGGERED:'Exit condition triggered — manual action required',HOLD_UNDER_ORIGINAL_PLAN:'Hold under original plan',MANUAL_VERIFICATION_REQUIRED:'Manual verification required'};
export function thesisWatchDetails(row){
  const r=row.thesis,t=row.plan?.invalidation;if(!t)return '<p class="hint">Trade thesis & invalidation: Not configured. Legacy exits remain independent.</p>';
  return `<section><h4>${esc(actionLabel[r.action])}</h4><p>Thesis: <strong>${esc(r.thesisStatus)}</strong> · Evaluated ${esc(timestamp(r.assessedAt))}. ${esc(r.coverage)}</p>${r.triggered.length?'<p class="error-text">'+esc(r.triggered.map(words).join(' · '))+'</p>':''}<p>Trading date ${esc(t.tradeDate)} · Realization ${esc(timestamp(t.realizationStartAt))} – ${esc(timestamp(t.realizationEndAt))} · Latest exit ${esc(timestamp(row.plan.timeExitAt))} · Contract expiry ${esc(row.contract.expiry)}</p><p>Realization window: ${esc(words(r.realizationCheck))}. This review point does not invent a new exit threshold.</p><p>Original next check: ${esc(timestamp(t.nextCheckAt))} · If data is unavailable: ${esc(t.manualFallback)}</p>
    <details data-disclosure-key="thesis-watch-${esc(row.tradeId)}" open><summary>Original conditions and evidence</summary><p>${esc(row.plan.thesis)} · ${esc(words(r.preEntryTiming))}</p>${r.checks.map(c=>`<p><strong>${esc(c.id)}: ${esc(words(c.status))}</strong> — ${esc(c.reason)}<br>Source ${esc(timestamp(c.sourceAt))} · received ${esc(timestamp(c.receivedAt))} · ${esc(words(c.provenance))} · ${esc(c.reference??'No evidence')}</p>`).join('')}<p>${esc([...r.issues,...r.marketGaps].map(words).join(' · '))}</p><details><summary>Frozen plan record</summary><pre>${esc(JSON.stringify(t,null,2))}</pre></details></details></section>`;
}
export function thesisReviewForm(row,d={},comparisons=[]){
  const conditions=row.plan?.invalidation?.conditions;if(!conditions)return '';
  const events=conditions.filter(c=>c.kind!=='PRICE');
  return `<details data-disclosure-key="review-save-${esc(row.tradeId)}"><summary>Save evaluation / Owner confirmation / correction</summary><p>Explicit save only. Saved triggers survive refresh and later rebounds. Corrections append an explanation; they do not erase the previous trigger. A reported action is not a reported fill.</p><form data-thesis-review="${esc(row.tradeId)}" class="form-grid">
    ${events.length?`<details class="full" data-disclosure-key="owner-evidence-${esc(row.tradeId)}"><summary>Optional source-confirmed event evidence</summary><p>News interpretation stays manual. Numeric values are compared only after you confirm their identity and source.</p>${comparisons.filter(r=>events.some(c=>c.kind==='EVENT_NUMERIC'&&c.metric===r.request.metric&&c.period===r.request.period)).map(r=>`<button type="button" class="link-button" data-thesis-comparison="${esc(r.request.requestId)}" data-thesis-trade="${esc(row.tradeId)}">Use saved ${esc(r.request.metric+' '+r.request.period)} comparison</button>`).join('')}<div class="form-grid">${choice('conditionId','Optional Owner-confirmed condition',d.conditionId??'',[['','No new Owner evidence'],...events.map(c=>[c.id,c.id+' — '+c.kind])])}${field('source','Actual source reference',d.source)}${time('sourceAt','Actual publication / evidence time',d.sourceAt)}${time('receivedAt','Actual received time',d.receivedAt)}${field('eventKey','Actual event identity',d.eventKey)}${field('metric','Actual metric / adjustment',d.metric)}${field('period','Actual period',d.period)}${field('unit','Actual unit',d.unit)}${field('releaseVersion','Actual release vintage',d.releaseVersion)}${field('value','Numeric actual value',d.value)}${choice('judgment','Manual factual judgment (manual conditions only)',d.judgment??'',[['','No manual judgment'],['SUPPORTED','Supported'],['WARNING','Warning'],['INVALIDATED','Invalidated']])}${field('explanation','Why this evidence meets the original condition',d.explanation)}${field('comparisonRef','Optional existing macro-comparison reference',d.comparisonRef,'Copied saved comparison; verified locally without fetching.')}<label class="check-row full"><input type="checkbox" name="ownerConfirmed"${d.ownerConfirmed?' checked':''}> I checked the source and confirm the new evidence.</label></div></details>`:''}
    ${field('note','Process / correction note',d.note)}${choice('reportedAction','Action report',d.reportedAction??'NO_ACTION_REPORTED',[['NO_ACTION_REPORTED','No action reported'],['OWNER_REPORTS_ACTION','Owner reports action; no fill inferred']])}${field('correctionOf','Optional previous review request ID',d.correctionOf)}<div class="form-actions"><button type="submit" value="PREVIEW_REVIEW" class="button secondary">Preview evaluation</button><button type="submit" value="SAVE_REVIEW" class="button primary">Save evaluation snapshot</button></div></form><p data-thesis-review-error="${esc(row.tradeId)}" class="error-text"></p><div data-thesis-review-preview="${esc(row.tradeId)}"></div></details>
    ${thesisReviewHistory(row)}`;
}
export function thesisReviewHistory(row){
  return `<details data-disclosure-key="review-history-${esc(row.tradeId)}"><summary>Saved evaluations (${row.reviewHistory?.length??0})</summary>${(row.reviewHistory??[]).map(h=>`<article><p>${esc(h.requestId)} · Saved ${esc(timestamp(h.savedAt))} · Evaluated ${esc(timestamp(h.assessedAt))}</p><p>${esc(actionLabel[h.result.action])} · ${esc(h.result.thesisStatus)} · ${esc(h.result.triggered.join(' · '))}</p><p>${esc(words(h.reportedAction))} · ${esc(h.note)} · Correction of ${esc(h.correctionOf||'None')}</p><details><summary>Frozen evidence and evaluation</summary><pre>${esc(JSON.stringify(h,null,2))}</pre></details></article>`).join('')}</details>`;
}
export function thesisReviewRequest(id,d,cost,action,requestId){
  let evidence=null;if(d.conditionId){if(!d.ownerConfirmed)throw Error('Confirm that you checked the cited source.');const keys=['conditionId','source','sourceAt','receivedAt','eventKey','metric','period','unit','releaseVersion','value','judgment','explanation','comparisonRef'];evidence=Object.fromEntries(keys.map(k=>[k,String(d[k]??'').trim()]));}
  return {action,requestId,tradeId:id,exitCostUsd:cost||null,evidence,note:d.note??'',reportedAction:d.reportedAction||'NO_ACTION_REPORTED',correctionOf:d.correctionOf??''};
}
