import {esc,words,cents,timestamp} from './model.js';
const codes=xs=>'<ul>'+xs.map(x=>'<li>'+esc(words(x))+'</li>').join('')+'</ul>';
function observationPanel(o,collection){
  if(!o)return '';
  const c=o.coverage,x=o.exit,next=collection?.wakes.find(w=>!w.alreadyPassed&&['ROUTINE','PAPER_REHEARSAL','EVENT_CONDITIONAL'].includes(w.basis));
  return '<p><strong>'+esc(words(o.classification))+'</strong> · '+c.timely+' / '+c.due+' due close observations usable ('+c.required+' required for the full window)</p>'+
    '<p>Latest ETF receipt '+esc(timestamp(c.lastSourceReceiptAt))+' · completed bar '+esc(timestamp(c.lastBarEndAt))+'</p>'+
    (c.missing.length?'<details><summary>'+c.missing.length+' missing or unusable close observations</summary><p>'+c.missing.map(t=>esc(timestamp(t))).join(' · ')+'</p>'+codes(c.qualityCodes)+'</details>':'')+
    (o.entryDeadlineAt?'<p>Independent entry receipt deadline '+esc(timestamp(o.entryDeadlineAt))+' · planned time exit '+esc(timestamp(x.plannedAt))+'</p>':'')+
    '<p>Latest selected-contract quote '+esc(timestamp(x.latestSelectedQuoteAt))+' · accepted independent quote after entry '+esc(timestamp(x.independentQuoteAt))+' · received '+esc(timestamp(x.independentReceiptAt))+'</p>'+
    (x.entryAt?'<p>Modeled entry '+esc(timestamp(x.entryAt))+' · modeled exit '+esc(timestamp(x.modeledExitAt))+' · '+esc(words(x.reason??'UNRESOLVED'))+'</p>':'')+
    (x.lateExitSeconds>0?'<p class="notice">Exit evidence arrived '+x.lateExitSeconds+' seconds after the planned exit. The model uses that later receipt, not the planned exit time or price.</p>':'')+
    (x.overdueUnresolved?'<p class="notice">Time exit is overdue; no admissible exit has been observed. Exposure remains unresolved.</p>':'')+
    (x.monitoringInterrupted?'<p class="notice">Independent exit monitoring is interrupted or unusable; recent repeated quotes do not repair coverage.</p>':'')+
    (x.pathUnknown?'<p>Unobserved price path: an earlier stop, target or worse exit may have been missed.</p>':'')+
    (x.latestRejectionCodes.length?'<details><summary>Latest quote rejection</summary>'+codes(x.latestRejectionCodes)+'</details>':'')+
    (collection?'<p>Next nominal quote within this plan date: '+esc(timestamp(next?.wakeAt))+' · '+esc(words(next?.basis??'NONE_REMAINING'))+'. A scheduled wake does not guarantee this contract is returned.</p>':'');
}
function contractPanel(a,o,tracking){
  if(!a.decision)return '<p>No recorded first signal. Missing data is not evidence that no market signal occurred.</p>';
  return '<p>First signal '+esc(timestamp(a.decision.signal.at))+' · observed '+esc(timestamp(a.decision.at))+' · '+esc(words(a.decision.signal.side))+'</p>'+codes(a.decision.blockers)+
    '<p>Host contract tracking: '+esc(words(tracking??'NOT_SELECTED'))+'. Existing event / enrolled paper IDs retain priority; six tracked IDs total.</p>'+
    '<details><summary>Contract screening ('+a.decision.candidates.length+')</summary><p>Rank is within this saved sample, not the full chain. Passing filters or ranking first does not establish better returns. Holding deadline is the planned intraday exit; DTE describes expiry, not intended holding time.</p>'+a.decision.candidates.map((c,i)=>{
      const d=o?.candidates?.[i];
      return '<p><strong>#'+(i+1)+' '+esc(c.contract.expiry+' $'+c.contract.strike+' '+c.contract.type)+'</strong> · '+esc(words(d?.screening??(c.blockers.length?'REJECTED':'PASSED_FILTERS')))+(d?.selected?' · Selected, not filled':'')+'</p>'+
        '<p>'+c.dte+' DTE · delta '+esc(c.contract.delta??'Unknown')+' · bid / ask '+cents(c.contract.bidCents)+' / '+cents(c.contract.askCents)+' · spread '+cents(c.spreadCents)+'</p>'+
        '<p>Quote '+esc(timestamp(c.contract.updatedAt))+' · age at decision '+esc(d?.quoteAgeSeconds??'Unknown')+' seconds · full premium at ask '+cents(d?.premiumAtAskCents??null)+'</p>'+
        '<p>Estimated entry fee '+cents(d?.entryFeeEstimateCents??null)+' · exit fee reserve '+cents(d?.exitFeeReserveEstimateCents??null)+' · exit allowance per share '+cents(d?.exitAllowancePerShareCents??null)+'. Full premium may be lost; a planned stop is not a guaranteed fill.</p>'+codes(c.blockers);
    }).join('')+'<p>Underlying target / IV scenario and pre-expiry valuation: NOT ASSESSED. The frozen premium stop, net-R target and time exit remain the only modeled exits. ETF range failure is a warning. This is post-price-confirmation research; it does not test anticipation before a news event.</p></details>';
}
export function trendStudyPanel(component,service){
  if(!component)return '';
  if(!component.data)return '<section class="card section-space"><h2>Prospective trend study</h2><p role="alert">'+esc(component.error??'Study unavailable')+'</p></section>';
  const desk=component.data;
  return '<section class="card section-space" id="trend-study"><div class="card-head"><div><h2>Prospective trend study</h2><p>Frozen rules → future observations → independent option outcomes</p></div><span class="tag amber">Untested research</span></div>'+
    '<p class="notice">'+esc(desk.collectionGap)+'</p>'+(service?'<p class="hint">Local saved-evidence checks: '+esc(words(service.status))+' · '+esc(timestamp(service.checkedAt))+(service.error?' · '+esc(service.error):'')+'</p>':'')+
    (desk.studies.length?desk.studies.map(({study,days,counts,observationCounts={},nextNominalQuote,calendarState,collectionProposal})=>'<article><h3>'+esc(study.id)+'</h3><p>Registered '+esc(timestamp(study.registeredAt))+' · '+esc(study.dates[0])+' through '+esc(study.dates.at(-1))+'</p><p><strong>'+counts.sessions+' / '+study.dates.length+' session records · '+counts.signals+' first signals · '+counts.entries+' modeled entries · '+counts.closed+' closed</strong></p>'+
      '<p>ETF-session counts: '+(observationCounts.FULLY_OBSERVED_NO_SIGNAL??0)+' fully observed without a signal · '+(observationCounts.INSUFFICIENT_OBSERVATION??0)+' insufficient observation · '+(observationCounts.SIGNAL_BLOCKED??0)+' blocked signals · '+(observationCounts.OPEN_UNRESOLVED??0)+' unresolved entries. Dates and missing observations are not trade outcomes or a validation pass.</p>'+
      '<p>Next nominal Host quote '+esc(timestamp(nextNominalQuote?.wakeAt))+' · '+esc(words(nextNominalQuote?.basis??'NONE_REMAINING'))+' · calendar '+esc(words(calendarState??'UNKNOWN'))+'. Conditional event times require a verified current calendar and a running Host. ETF bars have no active collector.</p>'+
      (collectionProposal?'<details><summary>Required observation coverage — frequency proposal disabled</summary><p>Opening history '+esc(timestamp(collectionProposal.openingAt))+' through '+esc(timestamp(collectionProposal.baselineEndAt))+'. Completed ETF closes '+esc(timestamp(collectionProposal.startAt))+' through '+esc(timestamp(collectionProposal.endAt))+' every '+collectionProposal.intervalSeconds+' seconds; receipt and local processing within '+collectionProposal.maximumLatencySeconds+' seconds. Independent entry quote within '+collectionProposal.entryWindowSeconds+' seconds; time exit '+esc(timestamp(collectionProposal.timeExitAt))+'. Exit path observations must meet the frozen quote freshness checks.</p><p>'+esc(collectionProposal.requires)+' No timer or extra market request is enabled by this preview.</p></details>':'')+
      '<details data-disclosure-key="trend-rules-'+esc(study.id)+'"><summary>Inspect fixed entry, contract and exit rules</summary><p>09:30–10:30 New York: 3 / 12 close means and the final 30-minute range. Two subsequent completed five-minute closes beyond the range + 0.10%, within 0.50% of the trigger; second-bar volume at least 1.2× baseline mean. First match only, 10:40–14:30; early closes shorten the window.</p><p>One long call or put aligned with the observed direction; 14–45 DTE, absolute delta 0.35–0.70, spread no more than $0.10 and 10% of ask. Rank by distance to delta 0.50, 21 DTE, spread, then ID. Current declared allocation '+cents(study.settings.tradeBudget.minCents)+'–'+cents(study.settings.tradeBudget.maxCents)+'.</p><p>Selection is not a fill. A later quote must arrive within five minutes and meet the frozen limit. Saved premium stop '+(study.settings.stopLossBps/100)+'%; net reward '+study.settings.rewardMultipleMilliR/1000+'R; time exit 20 minutes before close. Dated estimated fees and one-tick exit allowance; actual costs unknown. Range failure is a separate warning.</p><p>These fixed choices are research assumptions, not optimized parameters or a win-rate claim. Canonical decisions and capital settings remain separate. Each ETF is an independent paper scenario, not a combined funded portfolio.</p></details>'+
      '<div class="table-scroll"><table><thead><tr><th>Session</th><th>GLD observation</th><th>IBIT observation</th><th>Signals / entries / closed</th></tr></thead><tbody>'+days.map(d=>'<tr><td>'+esc(d.date)+'</td><td>'+esc(words(d.observation?.assets[0]?.classification??d.report?.assets[0]?.status??d.status))+'</td><td>'+esc(words(d.observation?.assets[1]?.classification??d.report?.assets[1]?.status??d.status))+'</td><td>'+esc(d.report?[d.report.counts.signals,d.report.counts.entries,d.report.counts.closed].join(' / '):'—')+'</td></tr>').join('')+'</tbody></table></div>'+
      days.filter(d=>d.report).slice(-5).reverse().map(d=>'<details data-disclosure-key="trend-day-'+esc(study.id+'-'+d.date)+'"><summary>'+esc(d.date)+' evidence, exits and candidate lessons</summary><div class="grid-two">'+d.report.assets.map(a=>'<section class="decision-reference"><h4>'+esc(a.symbol)+' · '+esc(words(a.status))+'</h4><p>Source receipt '+esc(timestamp(a.latestSource))+' · last bar '+esc(timestamp(a.latestBar))+'</p>'+
        observationPanel(d.observation?.assets.find(o=>o.symbol===a.symbol),d.collectionPlans?.find(p=>p.planId===a.decision?.plan?.id))+
        contractPanel(a,d.observation?.assets.find(o=>o.symbol===a.symbol),desk.tracking?.error??desk.tracking?.rows.find(t=>t.planId===a.decision?.plan?.id)?.status)+
        '<p>Estimated net modeled outcome '+cents(a.paper?.account.netPnlCents??null)+' · '+esc(words(a.paper?.review?.outcome??'UNRESOLVED'))+'. Actual fees remain unknown.</p>'+
        '<p>Candidate lessons — unapproved; causes not established:</p>'+codes(a.lessons.map(l=>l.code))+'</section>').join('')+'</div><p class="hint">'+esc(d.report.outcomeMeaning)+'</p></details>').join('')+'</article>').join(''):'<p>No prospective study is registered.</p>')+
    '<button class="button secondary small" id="observe-trend-study">Record available evidence</button><p class="hint">Reads saved files only. The existing local service also checks while running. This does not request brokerage data or place orders.</p><p id="trend-study-error" class="error-text" role="alert"></p></section>';
}
