import {esc,words,cents,timestamp} from './model.js';
const codes=xs=>'<ul>'+xs.map(x=>'<li>'+esc(words(x))+'</li>').join('')+'</ul>';
export function trendStudyPanel(component,service){
  if(!component)return '';
  if(!component.data)return '<section class="card section-space"><h2>Prospective trend study</h2><p role="alert">'+esc(component.error??'Study unavailable')+'</p></section>';
  const desk=component.data;
  return '<section class="card section-space" id="trend-study"><div class="card-head"><div><h2>Prospective trend study</h2><p>Frozen rules → future observations → independent option outcomes</p></div><span class="tag amber">Untested research</span></div>'+
    '<p class="notice">'+esc(desk.collectionGap)+'</p>'+(service?'<p class="hint">Local saved-evidence checks: '+esc(words(service.status))+' · '+esc(timestamp(service.checkedAt))+(service.error?' · '+esc(service.error):'')+'</p>':'')+
    (desk.studies.length?desk.studies.map(({study,days,counts})=>'<article><h3>'+esc(study.id)+'</h3><p>Registered '+esc(timestamp(study.registeredAt))+' · '+esc(study.dates[0])+' through '+esc(study.dates.at(-1))+'</p><p><strong>'+counts.sessions+' / '+study.dates.length+' sessions recorded · '+counts.signals+' first signals · '+counts.entries+' modeled entries · '+counts.closed+' closed</strong></p>'+
      '<details data-disclosure-key="trend-rules-'+esc(study.id)+'"><summary>Inspect fixed entry, contract and exit rules</summary><p>09:30–10:30 New York: 3 / 12 close means and the final 30-minute range. Two subsequent completed five-minute closes beyond the range + 0.10%, within 0.50% of the trigger; second-bar volume at least 1.2× baseline mean. First match only, 10:40–14:30; early closes shorten the window.</p><p>One long call or put aligned with the observed direction; 14–45 DTE, absolute delta 0.35–0.70, spread no more than $0.10 and 10% of ask. Rank by distance to delta 0.50, 21 DTE, spread, then ID. Current declared allocation '+cents(study.settings.tradeBudget.minCents)+'–'+cents(study.settings.tradeBudget.maxCents)+'.</p><p>Selection is not a fill. A later quote must arrive within five minutes and meet the frozen limit. Saved premium stop '+(study.settings.stopLossBps/100)+'%; net reward '+study.settings.rewardMultipleMilliR/1000+'R; time exit 20 minutes before close. Dated estimated fees and one-tick exit allowance; actual costs unknown. Range failure is a separate warning.</p><p>These fixed choices are research assumptions, not optimized parameters or a win-rate claim. Canonical decisions and capital settings remain separate. Each ETF is an independent paper scenario, not a combined funded portfolio.</p></details>'+
      '<div class="table-scroll"><table><thead><tr><th>Session</th><th>GLD</th><th>IBIT</th><th>Signals / entries / closed</th></tr></thead><tbody>'+days.map(d=>'<tr><td>'+esc(d.date)+'</td><td>'+esc(words(d.report?.assets[0]?.status??d.status))+'</td><td>'+esc(words(d.report?.assets[1]?.status??d.status))+'</td><td>'+esc(d.report?[d.report.counts.signals,d.report.counts.entries,d.report.counts.closed].join(' / '):'—')+'</td></tr>').join('')+'</tbody></table></div>'+
      days.filter(d=>d.report).slice(-5).reverse().map(d=>'<details data-disclosure-key="trend-day-'+esc(study.id+'-'+d.date)+'"><summary>'+esc(d.date)+' evidence, exits and candidate lessons</summary><div class="grid-two">'+d.report.assets.map(a=>'<section class="decision-reference"><h4>'+esc(a.symbol)+' · '+esc(words(a.status))+'</h4><p>Source receipt '+esc(timestamp(a.latestSource))+' · last bar '+esc(timestamp(a.latestBar))+'</p>'+
        (a.decision?'<p>First signal '+esc(timestamp(a.decision.signal.at))+' · observed '+esc(timestamp(a.decision.at))+' · '+esc(words(a.decision.signal.side))+'</p>'+codes(a.decision.blockers)+'<details><summary>Contract screening ('+a.decision.candidates.length+')</summary>'+a.decision.candidates.map(c=>'<p>'+esc(c.contract.expiry+' $'+c.contract.strike+' '+c.contract.type)+' · bid / ask '+cents(c.contract.bidCents)+' / '+cents(c.contract.askCents)+'</p>'+codes(c.blockers)).join('')+'</details>':'<p>No recorded first signal. Missing data is not evidence that no market signal occurred.</p>')+
        '<p>Independent quote '+esc(timestamp(a.monitor.lastQuoteAt))+' · estimated net outcome '+cents(a.paper?.account.netPnlCents??null)+' · '+esc(words(a.paper?.review?.outcome??'UNRESOLVED'))+'</p>'+
        (a.monitor.unusableWhileOpen?'<p class="notice">The latest exit quote failed quality checks.</p>':'')+
        (a.monitor.staleWhileOpen?'<p class="notice">Exit monitoring is stale; the position remains unresolved.</p>':'')+(a.monitor.overdueTimeExit?'<p class="notice">Time exit is overdue. No exit fill is assumed.</p>':'')+(a.monitor.pathGap?'<p>Price path between quotes is unobserved.</p>':'')+
        '<p>Candidate lessons — unapproved; causes not established:</p>'+codes(a.lessons.map(l=>l.code))+'</section>').join('')+'</div><p class="hint">'+esc(d.report.outcomeMeaning)+'</p></details>').join('')+'</article>').join(''):'<p>No prospective study is registered.</p>')+
    '<button class="button secondary small" id="observe-trend-study">Record available evidence</button><p class="hint">Reads saved files only. The existing local service also checks while running. This does not request brokerage data or place orders.</p><p id="trend-study-error" class="error-text" role="alert"></p></section>';
}
