import {focusedContext} from './focused-news.js';
import {esc,words,dollars,cents,number,timestamp,filterChain,collectLessons,lesson,safeLink} from './model.js';
import {plannerForm,journalForm} from './forms.js';
import {guidancePage} from './guidance.js';
import {eventResearchPage} from './event-research.js';
export const tag=(text,tone='gray')=>`<span class="tag ${tone}">${esc(text)}</span>`;
export const detail=(label,data)=>`<details><summary>${esc(label)}</summary><pre>${esc(JSON.stringify(data,null,2))}</pre></details>`;
export const notice=(text,tone='')=>`<div class="notice ${tone}"><span aria-hidden="true">ⓘ</span><div>${text}</div></div>`;
export const empty=(title,text,action='')=>`<div class="empty"><div class="empty-icon" aria-hidden="true">◇</div><h2>${esc(title)}</h2><p>${esc(text)}</p>${action}</div>`;
const heading=(eyebrow,title,subtitle,action='')=>`<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="subtitle">${subtitle}</p></div>${action}</div>`;
const metric=(title,value,note,accent=false)=>`<div class="metric${accent?' accent':''}"><div class="metric-label">${title}</div><strong>${value}</strong><small>${note}</small></div>`;
export const table=(heads,rows)=>`<div class="table-scroll"><table><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
const options=(values,selected,all)=>`<option value="">${all}</option>`+values.map(v=>`<option value="${esc(v)}"${v===selected?' selected':''}>${esc(v)}</option>`).join('');
const problem=c=>c?.state==='AVAILABLE'?'':notice(`<strong>${esc(c?.state??'Unavailable')}</strong> · ${esc(c?.error??'No saved data')}. Reload saved data after the source is available.`,'error');
const sectionHead=(title,subtitle,action='')=>`<div class="card-head"><div><h2>${title}</h2><p>${subtitle}</p></div>${action}</div>`;
function progressDetails(p){return `<details><summary>All workstreams and the six real-price gates</summary>${table(['Workstream','Acceptance'],p.workstreams.map(w=>`<tr><td>${esc(w.name)}<small>${esc(w.detail)}</small></td><td>${esc(words(w.status))}</td></tr>`))}<h3>First real-price paper flow</h3>${table(['Required gate','Status'],p.firstPaperFlow.gates.map(g=>`<tr><td>${esc(g.name)}</td><td>${esc(words(g.status))}</td></tr>`))}<p class="hint">Named local acceptance counts are not an overall completion percentage or market validation.</p></details>`;}
const showDate=e=>e.precision==='DATE_ONLY'?`${e.startDate} – ${e.endDate} · time unknown`:e.localScheduledTime;
const events=s=>(s.calendar.data?.groups??[]).flatMap(g=>[...g.dateOnlyEntries,...g.scheduledTimeEntries]);
function eventRows(items){return items.map(e=>`<div class="event"><div class="date-box">${esc(new Date(e.startDate+'T12:00:00Z').toLocaleString('en-US',{month:'short',timeZone:'UTC'}).toUpperCase())}<b>${esc(e.startDate.slice(-2))}</b></div><div><h3>${esc(e.title)}</h3><p>${esc(showDate(e))}</p><p>${esc(e.source)} · ${e.precision==='DATE_ONLY'?'Listed meeting dates':'Scheduled release; actual values not collected'}</p></div></div>`).join('');}
export function overview(s){
  const manual=s.manual.data,rows=s.chain.data?.chain.rows,p=s.progress.data,a=s.activity.data,lessons=collectLessons(s);
  const asset=symbol=>{const list=rows?.filter(r=>r.symbol===symbol);return `<div class="card"><div class="asset-head"><div class="asset-logo ${symbol==='IBIT'?'btc':''}">${symbol==='GLD'?'Au':'₿'}</div><div><h3>${symbol}</h3><p>${symbol==='GLD'?'SPDR Gold Shares':'iShares Bitcoin Trust'}</p></div></div><div class="asset-values"><div><span>Saved contracts</span><strong>${number(list?.length)}</strong></div><div><span>Activity candidates</span><strong>${number(list?.filter(r=>r.reviewCandidate).length)}</strong></div></div><div class="asset-foot"><span>Quote dates: ${esc([...new Set(list?.map(r=>r.quoteRefreshDateNewYork)??[])].filter(Boolean).join(', ')||'Unknown')}</span><button class="link-button" data-asset="${symbol}">Explore options →</button></div></div>`;};
  return heading('YOUR CAPITAL, IN FOCUS','A clearer view. A steadier plan.','Your GLD and IBIT research, risk checks and trade records in one place.',`<a class="button primary" href="#planner">＋ Build a trade plan</a>`)+
  `<div class="metrics">${metric('Planning baseline','$1,000','Declared scenario · not a broker balance',true)}${metric('Normal allocation ceiling','$50','5% of the $1,000 planning baseline')}${metric('Reported open positions',number(manual?.counts.openTrades),manual?`${number(manual.counts.trades)} registered trades · owner reported`:'Ledger unavailable')}${metric('Study follow-up',a?`${a.counts.observedSessions} / ${a.counts.scheduledSessions}`:'—','Saved close boards · research only')}</div>`+
  notice('<strong>Saved evidence, with its original clocks.</strong> Quotes below are dated snapshots. Reloading this workspace reads local files; it does not request new market prices.')+
  problem(s.chain)+problem(s.manual)+`<div class="grid-two"><div><div class="grid-equal">${asset('GLD')}${asset('IBIT')}</div><section class="card section-space">${sectionHead('Your next steps','Keep the decision and its evidence together.')}<ol class="workflow"><li><span class="step done">1</span><div><h3>Review context and quote quality</h3><p>Check the source time, spread, contract and upcoming events.</p></div></li><li><span class="step">2</span><div><h3>Calculate the downside first</h3><p>Use declared costs, whole contracts, a time exit and net R.</p></div></li><li><span class="step">3</span><div><h3>Record what actually happened</h3><p>Enter your reported fills, then review costs and plan deviations.</p></div></li></ol></section></div><section class="card">${sectionHead('On the calendar','New York time · saved official calendars',`<a class="link-button" href="#context">View all →</a>`)}${problem(s.calendar)}${eventRows(events(s).slice(0,4))||'<p class="hint">No saved entries in this calendar horizon. This does not establish an event-free session.</p>'}</section></div>`+
  `<div class="grid-two"><section class="card">${sectionHead('System readiness','Local engineering acceptance and market validation are tracked separately.')}${problem(s.progress)}${p?`<div class="chart-bars" aria-label="4 locally validated, 3 partial, 3 not validated">${p.workstreams.map(w=>`<span class="${w.status==='LOCAL_VALIDATED'?'complete':w.status==='PARTIAL'?'partial':''}"></span>`).join('')}</div><div class="count-key"><span>${p.currentCounts.LOCAL_VALIDATED} local validated</span><span>${p.currentCounts.PARTIAL} partial</span><span>${p.currentCounts.NOT_VALIDATED} not validated</span></div>${progressDetails(p)}</section>`:'</section>'}<section class="card">${sectionHead('Reviews worth revisiting','Candidate lessons require evidence and review.')}<p class="detail-money">${number(lessons.length)} <span class="hint">candidate notes across separate evidence origins</span></p><p class="hint">Recorded outcomes can reveal process problems. They do not identify institutions, prove a market cause or establish a strategy win rate.</p><a href="#reviews" class="button secondary">Open reviews & lessons →</a></section></div>`;
}
export function chainView(s,ui){
  const all=s.chain.data?.chain.rows??[],f=ui.chain,result=filterChain(all,f),exps=[...new Set(all.filter(r=>!f.symbol||r.symbol===f.symbol).map(r=>r.expiry))].sort();
  return heading('THE OPTIONS UNIVERSE','Options & activity','Explore saved contracts and the activity worth researching.',`<button class="button secondary" data-export="chain">↓ Export displayed source</button>`)+
  `<label class="form-field">Saved board<select id="board-select">${(s.catalog.data??[]).map(b=>`<option value="${esc(b.id)}"${b.id===s.selectedBoardId?' selected':''}>${esc(b.id)} · ${esc(b.createdAt?timestamp(b.createdAt):b.state)}</option>`).join('')}</select></label>`+problem(s.catalog)+problem(s.chain)+
  `<div class="tabs" aria-label="Option table scope"><button data-chain-scope="all" class="${!f.flagged?'active':''}" aria-pressed="${!f.flagged}">All contracts ${number(all.length)}</button><button data-chain-scope="flagged" class="${f.flagged?'active':''}" aria-pressed="${f.flagged}">Activity candidates ${number(all.filter(r=>r.reviewCandidate).length)}</button></div>`+
  `<div class="toolbar"><label>ETF<select data-chain-filter="symbol">${options(['GLD','IBIT'],f.symbol,'Both ETFs')}</select></label><label>Expiration<select data-chain-filter="expiry">${options(exps,f.expiry,'All dates')}</select></label><label>Option type<select data-chain-filter="type">${options(['call','put'],f.type,'Calls & puts')}</select></label><label class="grow">Search contract<input id="chain-search" placeholder="Strike, date or symbol" value="${esc(f.search)}"></label><label>Sort by<select data-chain-filter="sort">${[['volume','Volume'],['openInterest','Open interest'],['strike','Strike'],['ask','Ask']].map(([v,l])=>`<option value="${v}"${f.sort===v?' selected':''}>${l}</option>`).join('')}</select></label><button class="button secondary small" id="sort-direction" aria-label="Toggle sort direction">${f.direction==='asc'?'↑ Ascending':'↓ Descending'}</button><button id="clear-filters" class="link-button">Reset filters</button></div>`+
  `<p class="hint">Volume session and open-interest dates are unverified. Flags are descriptive research candidates; trade direction and institution identity are unknown.</p>`+
  (result.total?table(['Contract','Strike','Bid / Ask','Volume','Open interest','Evidence'],result.rows.map(r=>`<tr><td><button class="link-button" data-contract="${r.id}">${r.symbol} ${words(r.type)}</button><small>${r.expiry}</small></td><td class="numeric">${dollars(r.strike)}</td><td class="numeric">${dollars(r.bid)} / ${dollars(r.ask)}<small>${r.bidSize??'—'} / ${r.askSize??'—'} contracts</small></td><td class="numeric">${number(r.volume)}</td><td class="numeric">${number(r.openInterest)}</td><td>${tag(r.reviewCandidate?'Activity candidate':'Below activity filter',r.reviewCandidate?'amber':'gray')}<small>${esc(timestamp(r.quoteUpdatedAt))} · saved quote</small></td></tr>`)):empty('No matching contracts','Try another expiry, option type or strike. A missing match is not evidence that the contract does not exist.'))+
  `<div class="pagination"><span>${number(result.total)} matching contracts · 25 per page</span><div><button class="button secondary small" data-page="-1"${result.page===1?' disabled':''}>← Previous</button><span>${result.page} / ${result.pages}</span><button class="button secondary small" data-page="1"${result.page===result.pages?' disabled':''}>Next →</button></div></div>`;
}
export function contractDetail(r,s){
  const a=s.activity.data?.cases.find(c=>c.candidate.id===r.id);
  const primary=a?.outcomes.find(o=>o.primary&&o.costScenario==='ILLUSTRATIVE_BASE');
  return `<div class="status-line">${tag(r.symbol,'green')}${tag(words(r.type))}${tag(r.reviewCandidate?'Activity candidate':'Below filter','amber')}</div><p class="detail-money">${dollars(r.strike)} <span class="hint">strike · expires ${r.expiry}</span></p><dl class="result-grid"><div><dt>Saved bid / ask</dt><dd>${dollars(r.bid)} / ${dollars(r.ask)}</dd></div><div><dt>Displayed bid / ask size</dt><dd>${number(r.bidSize)} / ${number(r.askSize)}</dd></div><div><dt>Reported volume</dt><dd>${number(r.volume)}</dd></div><div><dt>Reported open interest</dt><dd>${number(r.openInterest)}</dd></div></dl>`+
  notice(`<strong>Quote refreshed ${esc(r.quoteUpdatedAt??'unknown')}.</strong> This saved observation is not a current executable price.`)+
  `<h3>What the activity can tell us</h3><p class="hint">${esc(r.interpretation)}</p><ul class="rule-list">${r.activityFlags.map(flag=>`<li>${esc(words(flag))}</li>`).join('')}</ul><h3>Possible explanations — unconfirmed</h3>${r.possibleExplanations.length?`<ul class="rule-list">${r.possibleExplanations.map(x=>`<li>${esc(typeof x==='string'?x:JSON.stringify(x))}</li>`).join('')}</ul>`:'<p class="hint">No cause has been established from the saved counters.</p>'}
  ${a?`<h3>Frozen study comparison</h3><p class="hint">Control strike: ${a.control?dollars(a.control.strike):'Unmatched'}. Cohort: ${esc(words(a.cohort))}.</p>${detail('Primary reference outcome and gaps',primary)}`:''}${detail('Original contract, clocks, quality and evidence needed',r)}<button class="button primary" data-plan-contract="${r.id}">Use as a declared planning scenario →</button>`;
}
export function planner(s,ui){return heading('DOWNSIDE BEFORE UPSIDE','Trade planner','Compare a declared long-option scenario using the existing risk engine.')+
  `<div class="grid-two"><section class="card">${sectionHead('Build your scenario','All figures are declarations, not verified account or order inputs.')}${ui.planningSource?notice(`Based on a saved ${esc(ui.planningSource.symbol)} contract. Quote clock: ${esc(ui.planningSource.quoteUpdatedAt)}. Verify and edit the inputs before use.`):''}${plannerForm(ui.plannerDraft)}<p id="planner-error" class="error-text" role="alert"></p></section><section class="card sticky-card" id="planner-result">${plannerResult(ui.plannerResult)}</section></div>`;}
export function plannerResult(r){if(!r)return `${sectionHead('Risk diagnostic','Calculate a scenario to see its costs and limits.')}<div class="empty"><div class="empty-icon">◇</div><h3>Start with what you can lose</h3><p>One contract means 100 shares. A premium stop does not guarantee the maximum loss.</p></div><p class="hint">The existing engine retains a 5% normal allocation ceiling, 0.5% planned account-risk ceiling and a separate $25 full-premium stress cap for the $1,000 scenario.</p>`;
  const e=r.economics;return sectionHead('Scenario result','Deterministic calculation · manual scenario',tag(r.status==='NO_TRADE'?'Blocked scenario':'Economically feasible',r.status==='NO_TRADE'?'red':'green'))+
  (e?`<dl class="result-grid"><div><dt>Premium</dt><dd>${cents(e.premiumCents)}</dd></div><div><dt>Full-premium stress</dt><dd>${cents(e.stressLossCents)}</dd></div><div><dt>Planned loss, including costs</dt><dd>${cents(e.plannedStopCents)}</dd></div><div><dt>Requested net target</dt><dd>${cents(e.netProfitTargetCents)}</dd></div><div><dt>Indicative exit / share</dt><dd>${cents(e.indicativeExitLimitPerShareCents)}</dd></div><div><dt>Net target after tick rounding</dt><dd>${cents(e.roundedNetProfitTargetCents)}</dd></div></dl>`:'')+
  notice('Scenario feasibility does not grant execution permission. Account eligibility, quote quality and total portfolio risk still require evidence.','info')+
  `<ul class="rule-list">${r.blockers.map(b=>`<li>${esc(b.message)}<code>${esc(b.code)}</code></li>`).join('')}</ul>${detail('Full calculation, assumptions and remaining requirements',r)}${e&&r.scenario&&e.plannedStopCents!==null?'<button id="plan-to-journal" class="button secondary">Prepare a recorded plan →</button><p class="hint">Records a declaration only; it creates no fill.</p>':''}`;
}
export function journal(s,ui){const manual=s.manual.data;
  return heading('EVERY FILL HAS A HISTORY','Trade journal','Your reported records, preserved with exact costs and correction history.',`<button class="button secondary" data-export="manual">↓ Export ledger report</button>`)+problem(s.manual)+
  (s.manual.state==='MISSING'?empty('Initialize your local ledger','This creates an empty owner-reported ledger. It does not read a broker account.','<button id="initialize-ledger" class="button primary">Create empty ledger</button>'):'')+
  (manual?`<div class="metrics">${metric('Registered trades',number(manual.counts.trades),esc(words(manual.origin)))}${metric('Open positions',number(manual.counts.openTrades),'Unresolved positions retain exposure')}${metric('Closed trades',number(manual.counts.closedTrades),'Reported outcomes, not a calibrated win rate')}${metric('Candidate notes',number(manual.counts.candidateLessons),'Review the evidence behind each note')}</div>`+
  `<div class="grid-two"><section class="card">${sectionHead('Record a plan or execution','Enter information from your own completed trade records.')}<div class="tabs" aria-label="Record type">${[['register','Register trade'],['fill','Record fill'],['correct','Correct / void']].map(([k,v])=>`<button data-journal-mode="${k}" class="${ui.journalMode===k?'active':''}" aria-pressed="${ui.journalMode===k}">${v}</button>`).join('')}</div>${journalForm(ui.journalMode,manual,ui.journalDraft)}<p id="journal-error" class="error-text" role="alert"></p></section><section class="card sticky-card">${sectionHead('Recorded positions','Select a trade to inspect its accounting.')}${manual.trades.length?table(['Trade','Position','Realized net'],manual.trades.map(t=>`<tr><td><button class="link-button" data-trade="${esc(t.tradeId)}">${t.contract.symbol} ${words(t.contract.optionType)}</button><small>${t.contract.expiry} · ${dollars(t.contract.strikeUsd)}</small></td><td>${t.openContracts}<small>${esc(words(t.status))}</small></td><td>${dollars(t.realizedNetPnlUsd)}<small>${t.status==='CLOSED'?'Closed result':'Closed portion only'}</small></td></tr>`)):empty('No reported trades yet','Register a plan or trade, then record each actual fill. Synthetic quotes never become entries here.')}</section></div>`:'');
}
export function tradeDetail(t,manual){return `<p class="eyebrow">${esc(t.tradeId)}</p><p class="detail-money">${t.contract.symbol} ${words(t.contract.optionType)} ${dollars(t.contract.strikeUsd)}</p><p class="hint">Expires ${t.contract.expiry} · ${esc(words(t.planTiming))} · ${esc(words(manual.origin))}</p><dl class="result-grid"><div><dt>Open contracts</dt><dd>${t.openContracts}</dd></div><div><dt>Realized net</dt><dd>${dollars(t.realizedNetPnlUsd)}</dd></div><div><dt>Remaining cost basis</dt><dd>${dollars(t.remainingCostBasisUsd)}</dd></div><div><dt>Closed trade net</dt><dd>${dollars(t.closedTradeNetPnlUsd)}</dd></div></dl><p class="hint">Cost basis is not current market value. Missing fees remain unknown.</p><h3>Reported fills and corrections</h3>${table(['Fill / revision','Action / quantity','Price / fee'],t.effectiveFills.map(f=>`<tr><td>${esc(f.fillId)}<small>Revision ${f.revision}</small></td><td>${f.value?`${words(f.value.action)} × ${f.value.quantity}`:'Voided'}<small>${esc(f.value?.executedAt??'Original retained')}</small></td><td>${dollars(f.value?.pricePerShareUsd)}<small>Fee ${dollars(f.value?.feesUsd)}</small></td></tr>`))}<h3 class="section-space">Review candidates</h3>${t.candidateLessons.map(l=>`<div class="lesson-card"><h3>${esc(lesson(l.code)[0])}</h3><p>${esc(lesson(l.code)[1])}</p></div>`).join('')||'<p class="hint">No listed diagnostic. This does not authenticate execution.</p>'}${detail('Original plan, matching and reconciliation',t)}${detail('Original events and corrections',(manual.events??[]).filter(e=>e.command.tradeId===t.tradeId))}`;}
export function reviews(s,ui){
  let body='';const scope=ui.reviewScope;
  if(scope==='lessons'){
    const all=collectLessons(s),filtered=all.filter(l=>(!ui.lessonOrigin||l.origin===ui.lessonOrigin)&&`${l.title} ${l.code} ${l.support}`.toLowerCase().includes(ui.reviewSearch.toLowerCase()));
    body=`<div class="toolbar"><label>Evidence origin<select id="lesson-origin">${options([...new Set(all.map(l=>l.origin))],ui.lessonOrigin,'All origins')}</select></label><label class="grow">Search lessons<input id="review-search" value="${esc(ui.reviewSearch)}" placeholder="Observation, trade or code"></label></div><p class="hint">${filtered.length} of ${all.length} notes. Candidates are not approved rules and cannot change a strategy.</p><section class="card">${filtered.length?filtered.map(l=>`<article class="lesson-card"><div class="status-line">${tag(l.origin)}${tag('Candidate','amber')}</div><h3 class="section-space">${esc(l.title)}</h3><p>${esc(l.nextCheck)}</p><small>${esc(l.support||'See supporting report')} · ${esc(l.code)}</small>${detail('Supporting candidate record',l)}</article>`).join(''):empty('No matching lessons','Try another origin or search term. Missing evidence does not establish error-free execution.')}</section>`;
  }else if(scope==='activity'){
    const a=s.activity.data;body=problem(s.activity)+(a?`<div class="metrics">${metric('Frozen candidates',a.counts.candidates,'Retained before future closes')}${metric('Matched controls',a.counts.matched,`${a.counts.unmatched} unmatched cases retained`)}${metric('Saved close boards',`${a.counts.observedSessions} / ${a.counts.scheduledSessions}`,'Local evidence only')}${metric('Evaluable primary cases',a.counts.primaryEvaluableCandidates,'Zero is not a failed-return result')}</div>`+notice('Primary design: September 8 closing Ask to September 9 closing Bid. Fees and adverse allowances are illustrative. References do not prove fills, institutional intent or an investable edge.')+table(['Candidate','Control','Cohort','Primary reference'],a.cases.map(c=>{const o=c.outcomes.find(x=>x.primary&&x.costScenario==='ILLUSTRATIVE_BASE');return `<tr><td>${c.candidate.symbol} ${words(c.candidate.type)} ${dollars(c.candidate.strike)}<small>${c.candidate.expiry}</small></td><td>${c.control?dollars(c.control.strike):'Unmatched'}</td><td>${esc(words(c.cohort))}</td><td>${detail('Outcome and unavailable reasons',o)}</td></tr>`;}))+detail('All saved comparisons and study evidence',a):'');
  }else{
    const trades=s.manual.data?.trades??[];body=problem(s.manual)+`<section class="card">${sectionHead('Owner-reported reviews','Open and partially closed positions remain visible.')}${trades.length?table(['Trade','Status','Closed net','Review'],trades.map(t=>`<tr><td><button class="link-button" data-trade="${esc(t.tradeId)}">${t.contract.symbol} ${words(t.contract.optionType)} ${dollars(t.contract.strikeUsd)}</button><small>${esc(t.tradeId)}</small></td><td>${esc(words(t.status))}</td><td>${dollars(t.closedTradeNetPnlUsd)}</td><td>${t.candidateLessons.length} notes<small>Cause unconfirmed</small></td></tr>`)):empty('Your reviews will appear here','Once fills are recorded, Alpha recomputes their costs and plan deviations.')}</section>`+problem(s.outcomes);
    for(const id of ['paper','historical']){const component=s.outcomes.data?.components[id],a=component?.audit;body+=`<section class="card section-space">${sectionHead(id==='paper'?'Paper simulation reviews':'Independent historical research','Separate evidence origin · not the owner account')}${a?table(['Case','Disposition','Modeled net','Evidence'],a.cases.map(c=>`<tr><td>${esc(c.id)}<small>${esc(c.symbol)} · ${esc(words(c.origin))}</small></td><td>${esc(words(c.status))}</td><td>${cents(c.review?.input.netPnlCents)}</td><td>${detail('Original review and blockers',c)}</td></tr>`)):notice(`Saved component ${esc(component?.state??'unavailable')}.`)}${a?detail('Descriptive metrics and original audit',a.metrics):''}</section>`;}
  }
  return heading('LEARN FROM THE RECORD','Reviews & lessons','Separate what happened, what is known and what still needs evidence.',`<button class="button secondary" data-export="reviews">↓ Export review evidence</button>`)+`<div class="tabs">${[['trades','Trade reviews'],['lessons','Mistake notebook'],['activity','Activity study']].map(([k,l])=>`<button data-review-scope="${k}" class="${scope===k?'active':''}" aria-pressed="${scope===k}">${l}</button>`).join('')}</div>`+body;
}
export function context(s,ui){return focusedContext(s,ui);}
export const routes={overview,chain:chainView,planner,journal,reviews,context,guidance:guidancePage,'event-research':eventResearchPage};
