import {esc,safeLink} from './model.js';
import {lookupWorldModel} from './world-model-lookup.js';

const list=xs=>`<ul>${xs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const name=k=>k.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,x=>x.toUpperCase());
function value(v){if(v===null)return 'Unknown / not supplied';if(Array.isArray(v))return list(v);if(typeof v==='object')return `<dl>${Object.entries(v).map(([k,x])=>`<dt>${esc(name(k))}</dt><dd>${value(x)}</dd>`).join('')}</dl>`;return esc(v);}
function provenance(i,c){return `<details data-disclosure-key="wm-source-${esc(i.id)}"><summary>Provenance and approval</summary><p class="hint wm-id">Candidate: ${esc(i.candidateId)} · version ${i.version}<br>Owner approval recorded: ${esc(i.approvedAt)}<br>${esc(i.approvalRef)}<br>Review: ${esc(i.reviewRef)}</p>${i.canonicalRefs?.length?`<p>Existing canonical references (scope remains unchanged):</p>${list(i.canonicalRefs)}`:''}${i.originalReview?`<details><summary>Original review wording and scope limits</summary>${value(i.originalReview)}</details>`:''}<p>Dossier sections:</p>${list(i.dossierRefs.map(r=>r.path+'#'+r.anchor+' · section '+r.section))}<p>Saved source map:</p>${i.sourceRefs.map(id=>{const s=c.sourceMap.find(x=>x.sourceRef===id);return `<div class="wm-source"><strong>${esc(id)}</strong><p>${esc(s?.savedCitation??'Source mapping unavailable')}</p><p class="hint">Saved coverage: ${esc(s?.savedSupportAndLimitations??'Unknown')}. This stage did not reopen the source.</p>${(s?.urls??[]).map(url=>safeLink(url)?`<a href="${esc(safeLink(url))}" target="_blank" rel="noopener noreferrer">Open original source</a>`:'').join(' · ')}</div>`;}).join('')}</details>`;}
function item(i,c){return `<details class="wm-item" data-disclosure-key="wm-${esc(i.id)}"><summary>${esc(i.reviewLabel)} · ${esc(i.title)} <span class="tag amber">${esc(i.evidenceStatus)}</span>${i.status&&i.status!==i.evidenceStatus?` <span class="tag amber">${esc(i.status)}</span>`:''}</summary><p class="eyebrow">${esc(i.knowledgeType)}</p>${i.knowledgeType==='HYPOTHESIS_ONLY_CONTEXT'?'<p class="notice">Hypothesis only — requires current evidence. No signal, score, probability or trade permission.</p>':''}${i.knowledgeType==='WATCH_QUESTION'?'<p class="notice">Question, not assertion.</p>':''}<p>${esc(i.statement)}</p><p><strong>Limitations</strong></p>${list(i.limitations)}${i.details?`<dl>${Object.entries(i.details).map(([k,v])=>`<dt>${esc(name(k))}</dt><dd>${value(v)}</dd>`).join('')}</dl>`:''}${provenance(i,c)}</details>`;}
function edge(e,c){return `<details data-disclosure-key="wm-${esc(e.id)}"><summary>${esc(e.reviewLabel)} · ${esc(e.fromTheme)} → ${esc(e.toTheme)} <span class="tag amber">${esc(e.evidenceStatus)}</span></summary><p>${esc(e.statement)}</p><p>Mechanism: <span class="wm-id">${esc(e.mechanismRef)}</span> · ${esc(e.timeHorizon)}</p><p>Counterforces:</p>${list(e.counterforces)}${list(e.limitations)}${provenance(e,c)}</details>`;}
const groups=[['Core boundaries / structure',['STRUCTURAL_FACT','CONCEPTUAL_BOUNDARY','EVIDENCE_TIME_RULE','HISTORICAL_FACT','ACTOR_RELATION','STRUCTURAL_FLOW_RELATION']],['Measurement frameworks',['MEASUREMENT_FRAMEWORK']],['Mechanisms',['MECHANISM']],['Watch questions',['WATCH_QUESTION']],['Open questions',['OPEN_QUESTION']],['Hypothesis-only context',['HYPOTHESIS_ONLY_CONTEXT']],['Conflicts',['CONFLICT']]];
export function worldKnowledgeCard(i,c){return i.knowledgeType?item(i,c):edge(i,c);}
function group(title,items,c,key){return `<details data-disclosure-key="wm-group-${esc(key)}"><summary>${esc(title)} · ${items.length}</summary>${items.map(i=>item(i,c)).join('')||'<p>No approved items in this group.</p>'}</details>`;}
const select=(id,label,values,current)=>`<label class="form-field">${label}<select id="${id}"><option value="">All</option>${values.map(([v,l])=>`<option value="${esc(v)}"${v===current?' selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
export function worldModelPanel(component,ui={}){
 const c=component?.data;
 if(!c)return '<section class="card section-space" id="macro-world-model"><h2>Macro World Model — Batches 1–2</h2><p class="notice">Approved catalog unavailable. Reload saved data after the current workbench version is loaded. No research fallback is used.</p></section>';
 const filters={keyword:ui.worldKeyword??'',theme:ui.worldTheme??'',knowledgeType:ui.worldType??'',evidenceStatus:ui.worldEvidence??''};
 const result=lookupWorldModel(c,filters),filtered=Object.values(filters).some(Boolean);
 return `<section class="card section-space" id="macro-world-model"><h2>Macro World Model — Batches 1–2</h2><p>Owner-approved reference · ${c.items.length} items · ${c.edges.length} cross-theme links. Does not influence trading decisions.</p><p class="hint">${esc(c.evidenceNotice)}</p><p class="notice"><strong>Current state:</strong> ${esc(c.currentStateNotice)}</p><details data-disclosure-key="wm-catalog"><summary>Browse or search approved knowledge</summary><label class="form-field">Search World Model<input id="world-model-keyword" maxlength="160" value="${esc(filters.keyword)}" placeholder="SWIFT, one China, AI power, debt trap"></label><div class="wm-filters">${select('world-model-theme','Theme',c.themes.map(t=>[t.themeId,t.title]),filters.theme)}${select('world-model-type','Knowledge type',c.knowledgeTypes.map(t=>[t,t]),filters.knowledgeType)}${select('world-model-evidence','Evidence status',c.evidenceStatuses.map(t=>[t,t]),filters.evidenceStatus)}</div><p role="status">${result.items.length} items · ${result.edges.length} links match.</p>${filtered?`<div id="world-model-results">${result.items.map(i=>item(i,c)).join('')}${result.edges.map(e=>edge(e,c)).join('')}${!result.items.length&&!result.edges.length?'<p>No approved matches. Unknowns are not filled automatically.</p>':''}</div>`:c.themes.map(t=>{const matching=c.items.filter(i=>i.themeId===t.themeId||i.themeLinks.includes(t.themeId)),edges=c.edges.filter(e=>e.fromTheme===t.themeId||e.toTheme===t.themeId);return `<details data-disclosure-key="wm-theme-${t.themeId}"><summary>${esc(t.title)} · ${matching.length} items (shared references included)</summary>${groups.map(([label,types])=>group(label,matching.filter(i=>types.includes(i.knowledgeType)),c,t.themeId+'-'+label)).join('')}<details data-disclosure-key="wm-links-${t.themeId}"><summary>Cross-theme links · ${edges.length}</summary>${edges.map(e=>edge(e,c)).join('')||'<p>No approved cross-theme link.</p>'}</details></details>`;}).join('')}</details><details data-disclosure-key="wm-guardrails"><summary>Rejected interpretations and dossier-only boundaries · ${c.guardrails.length}</summary><p>Reasoning guardrails, not affirmative facts or proof of their opposites. Excluded from knowledge search results.</p>${c.guardrails.map(g=>`<details data-disclosure-key="wm-guard-${g.id}"><summary>${esc(g.reviewLabel)} · ${esc(g.disposition)}</summary><p>${esc(g.interpretation)}</p><p>${esc(g.reason)}</p><p class="hint wm-id">${esc(g.id)} · ${esc(g.reviewRef)}</p>${list(g.dossierRefs.map(r=>r.path+'#'+r.anchor))}</details>`).join('')}</details></section>`;
}
