import { createExportManifest as create, validateExportManifest as validate, exportFingerprint, exportSourcePolicy, type ExportFile, type ExportManifest } from "./OptionsEvidenceExportEngine";
const at = "2026-09-07T05:00:00.000Z", study = "test-study", id = "test-package", hash = "a".repeat(64);
const plan = (): ExportFile => ({ sourcePath: `data/runtime/options-robinhood-data/studies/${study}/plan.json`, payloadName: "payload-0001.bin", component: "study", bytes: 100, sha256: hash });
const fixture = () => create(id, study, at, at, [plan()]);
const eq = (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw Error(`Expected ${JSON.stringify(b)}; received ${JSON.stringify(a)}`); };
const ok = (value: unknown) => { if (!value) throw Error("Expected truthy value"); };
function throws(work: () => unknown, code = "OPTIONS_EXPORT_") { let error; try { work(); } catch (e) { error = e; } if (!(error instanceof Error) || !error.message.includes(code)) throw Error("Expected " + code); }
function alter(change: (value: ExportManifest) => void) { const value = structuredClone(fixture()); change(value); const { manifestSha256, ...body } = value; value.manifestSha256 = exportFingerprint(body); return value; }
let passed = 0;
function test(name: string, work: () => void) { work(); passed++; console.log(`PASS ${name}`); }
test("exact selected plan mapping retains missing components and actual clocks", () => { const r = fixture(); eq(r.files[0]!.sourcePath, plan().sourcePath); eq(r.totalBytes, 100); eq(r.missingComponents, ["paper", "historical", "imports", "headlines", "treasury", "btc", "attempts", "closeout"]); eq(r.startedAt, at); eq(r.completedAt, at); eq(r, validate(r)); });
test("fixed journal policy includes reviews and context without arbitrary file access", () => { eq(exportSourcePolicy(study, "data/runtime/options-paper/sessions.ndjson"), { component: "paper", maxBytes: 16777216 }); eq(exportSourcePolicy(study, "data/runtime/options-treasury-rates/retrievals.ndjson").maxBytes, 33554432); for (const path of [".env", "data/runtime/options-paper/secret.json", "C:/private", "data/runtime/options-robinhood-data/captures/raw.json", "data/runtime/options-robinhood-data/studies/other/plan.json"]) throws(() => exportSourcePolicy(study, path), "SOURCE_SCOPE"); });
test("numbered frames, safe attempts and exact closeout hashes have separate mappings", () => { eq(exportSourcePolicy(study, `data/runtime/options-robinhood-data/studies/${study}/frame-0001.json`).component, "study"); eq(exportSourcePolicy(study, `data/runtime/options-robinhood-data/collection-attempts/${study}/attempt-1.json`).component, "attempts"); eq(exportSourcePolicy(study, `data/runtime/options-robinhood-data/collection-reports/${study}/report-${hash}.json`).component, "closeout"); });
test("traversal, nested paths, backslashes and lock files cannot become source entries", () => { for (const suffix of ["../plan.json", "nested/frame-0001.json", "writer.lock", "frame-1.json", "frame-0001.json:stream", "..\\plan.json"]) throws(() => exportSourcePolicy(study, `data/runtime/options-robinhood-data/studies/${study}/${suffix}`)); });
test("package and study IDs reject Windows device names and user paths", () => { for (const bad of ["../other", "con", "nul", "COM1", "lpt1", "x", "name with spaces", "x".repeat(81), "https://a.invalid"]) { throws(() => create(bad, study, at, at, [plan()]), "ID"); throws(() => create(id, bad, at, at, [plan()]), "ID"); } });
test("source and payload order must be canonical and unique", () => { for (const mutate of [(v: ExportManifest) => { v.files[0]!.payloadName = "../outside"; }, (v: ExportManifest) => { v.files.push({ ...v.files[0]! }); }]) throws(() => validate(alter(mutate)), "FILE_MAPPING"); });
test("declared component cannot mislabel a source", () => { throws(() => validate(alter(v => { v.files[0]!.component = "paper"; })), "FILE_MAPPING"); });
test("selected plan is mandatory even when all other sources are missing", () => { throws(() => create(id, study, at, at, [])); throws(() => create(id, study, at, at, [{ ...plan(), sourcePath: plan().sourcePath.replace("plan.json", "frame-0001.json") }]), "PLAN_REQUIRED"); });
test("file byte lengths are nonnegative safe integers within their source limit", () => { for (const bytes of [-1, 0.5, Number.MAX_SAFE_INTEGER + 1, 2097153]) throws(() => validate(alter(v => { v.files[0]!.bytes = bytes; })), "FILE_METADATA"); const zero = create(id, study, at, at, [{ ...plan(), bytes: 0 }]); eq(zero.totalBytes, 0); });
test("bounded metadata rejects malformed hashes and unknown fields", () => { throws(() => validate(alter(v => { v.files[0]!.sha256 = "bad"; })), "FILE_METADATA"); throws(() => validate({ ...fixture(), extra: true } as ExportManifest), "SHAPE"); throws(() => validate(alter(v => { Object.assign(v.files[0]!, { url: "private" }); })), "SHAPE"); });
test("reported total and missing component coverage cannot hide omitted data", () => { throws(() => validate(alter(v => { v.totalBytes = 0; })), "TOTAL_BYTES"); throws(() => validate(alter(v => { v.missingComponents = []; })), "MISSING_COMPONENTS"); });
test("aggregate source size limit is enforced even when individual files fit", () => {
  const files: ExportFile[] = [
    { sourcePath: "data/runtime/options-paper/sessions.ndjson", component: "paper", bytes: 16777216, sha256: hash, payloadName: "" },
    { sourcePath: "data/runtime/options-historical-replay/runs.ndjson", component: "historical", bytes: 16777216, sha256: hash, payloadName: "" },
    { sourcePath: "data/runtime/options-treasury-rates/retrievals.ndjson", component: "treasury", bytes: 33554432, sha256: hash, payloadName: "" }, plan(),
  ];
  files.sort((a,b) => a.sourcePath < b.sourcePath ? -1 : 1).forEach((file,index) => { file.payloadName = `payload-${String(index+1).padStart(4,"0")}.bin`; });
  throws(() => create(id, study, at, at, files), "TOTAL_BYTES");
});
test("excess files are rejected before iterating untrusted entries", () => { throws(() => create(id, study, at, at, Array.from({ length: 401 }, plan)), "FILE_COUNT"); });
test("actual package clocks cannot be invalid or regress", () => { for (const time of ["bad", "2026-09-31T05:00:00.000Z", "2026-09-07T05:00:00Z"]) throws(() => create(id, study, time, at, [plan()]), "CLOCK"); throws(() => create(id, study, at, "2026-09-07T04:59:59.000Z", [plan()]), "CLOCK_ORDER"); });
test("hash detects body edits without suggesting source authentication", () => { const changed = structuredClone(fixture()); changed.completedAt = "2026-09-07T05:00:01.000Z"; throws(() => validate(changed), "MANIFEST_HASH"); eq(fixture().semanticValidationPerformed, false); });
test("export cannot claim atomicity, off-device backup, source-write or trade authority", () => { for (const patch of [{ semanticValidationPerformed: true }, { offDeviceBackup: true }, { sourceWritesAllowed: true }, { executionAllowed: true }, { consistency: "ATOMIC" }, { version: "other" }]) throws(() => validate(alter(v => Object.assign(v, patch)))); });
test("manifest cloning and freezing keep input bytes and declarations stable", () => { const file = plan(), r = create(id, study, at, at, [file]); file.bytes = 50; eq(r.files[0]!.bytes, 100); ok(Object.isFrozen(r.files[0])); ok(Object.isFrozen(r.missingComponents)); eq(r, fixture()); });
console.log(`${passed}/${passed} tests passed.`);
