import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  AIAuditActorType, AIAuditRecordType, AIAuditRetentionClassification, AIAuditSourceSubsystem,
  ANALOGY_SCORE_SCALE, AnalogyAppendStatus, AnalogyBiasRiskType, AnalogyComparisonMethod,
  AnalogyDimensionType, AnalogyDimensionValueType, AnalogyMissingDataPolicy, AnalogyNormalizationPolicy,
  AnalogyQualityClassification, AnalogyReviewDecision, AnalogyRiskSeverity, AnalogyScoreMethod,
  AnalogyWeightProfileStatus, HistoricalAnalogyAuditOperationType, HistoricalAnalogyExportDestination,
  HistoricalAnalogyExportFormat, HistoricalAnalogyExportStatus, HistoricalAnalogyStatus,
  HistoricalAssetClass, HistoricalCandidateType, HistoricalEventStatus, HistoricalPatternStatus,
  PrivacyLevel, historicalAnalogyFingerprint, validateAnalogyDimensionValue, validateAnalogyScore,
  validateAnalogyWeightProfile, validateHistoricalCandidate, weightProfileFingerprint,
  type AnalogyAmendment, type AnalogyBiasRisk, type AnalogyFilter, type AnalogyReview, type AnalogySupersession,
  type AnalogyWeightProfile, type CurrentSituationSnapshot, type HistoricalAnalogyAuditRecord,
  type HistoricalAnalogyRequest, type HistoricalCandidateReference,
} from "../../contracts";
import { InMemoryHistoricalAnalogyRepository, LocalNdjsonHistoricalAnalogyRepository } from "../../repositories";
import { HistoricalAnalogyEngine, auditRecordFromHistoricalAnalogy, defaultAnalogyBiasRisks, exportHistoricalAnalogies, type HistoricalAnalogyClock } from ".";

interface TestCase { readonly name: string; readonly run: () => void; }
function assertEqual<T>(actual: T, expected: T, message: string): void { if (!Object.is(actual, expected)) throw new Error(`${message}: expected ${String(expected)}, received ${String(actual)}.`); }
function assertTrue(value: boolean, message: string): void { if (!value) throw new Error(message); }
function assertDeepEqual(actual: unknown, expected: unknown, message: string): void { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(`${message}: ${JSON.stringify(actual)} !== ${JSON.stringify(expected)}`); }
function expectError(action: () => void, expected?: string): void { try { action(); } catch (error: unknown) { const message = error instanceof Error ? error.message : String(error); if (expected !== undefined) assertTrue(message.toLowerCase().includes(expected.toLowerCase()), `Expected "${expected}", received "${message}".`); return; } throw new Error(`Expected error${expected === undefined ? "" : ` containing ${expected}`}.`); }
class FixedClock implements HistoricalAnalogyClock { now(): string { return "2026-07-19T22:00:00.000Z"; } }

const category = (value: string) => ({ valueType: AnalogyDimensionValueType.Category, normalizedValue: value, missing: false }) as const;
const missingCategory = () => ({ valueType: AnalogyDimensionValueType.Category, missing: true }) as const;
function snapshot(overrides: Partial<CurrentSituationSnapshot> = {}): CurrentSituationSnapshot {
  return { snapshotId: "current-situation:day6-t4", schemaVersion: "1.0", snapshotVersion: "v1", asOfTimestamp: "2026-07-19T21:00:00.000Z", marketDataTimestampReferences: ["market-snapshot:v1"], geography: ["US"], markets: ["US"], assetClasses: [HistoricalAssetClass.Equity], eventCategories: ["LIQUIDITY_STRESS"], factualObservations: ["Supplied liquidity conditions are stressed."], quantitativeObservations: ["Supplied volatility index is elevated."], regime: { regimeId: "current-regime-1", summary: "Stressed liquidity and contracting growth.", dimensions: [{ featureId: "feature-liquidity", dimension: AnalogyDimensionType.Liquidity, value: category("STRESSED"), observedAt: "2026-07-19T21:00:00.000Z", evidenceReferenceIds: ["research-evidence-1"], confidence: 9000, disputed: false }, { featureId: "feature-growth", dimension: AnalogyDimensionType.Growth, value: category("CONTRACTING"), evidenceReferenceIds: ["research-evidence-2"], confidence: 8000, disputed: false }, { featureId: "feature-credit", dimension: AnalogyDimensionType.Credit, value: category("TIGHT"), evidenceReferenceIds: ["research-evidence-3"], confidence: 7000, disputed: false }] }, macroContext: ["Growth is contracting."], monetaryPolicyContext: ["Policy supplied by caller."], fiscalPolicyContext: [], inflationContext: [], growthContext: ["Contracting"], liquidityContext: ["Stressed"], creditContext: ["Tight"], volatilityContext: ["Elevated"], valuationContext: [], currencyContext: [], commodityContext: [], marketConcentration: [], positioning: [], catalysts: ["Policy response"], knownRisks: ["Regime mismatch"], uncertainties: ["Positioning unavailable"], disputedInterpretations: [], missingDimensions: [AnalogyDimensionType.InvestorPositioning], researchReferences: [{ researchId: "research-1", researchVersion: "v1", frozenStatus: "FINALIZED" }], sourceReferences: [{ referenceId: "research-evidence-1", referenceType: "RESEARCH_EVIDENCE", version: "v1", resolved: true }], privacyLevel: PrivacyLevel.Internal, retention: AIAuditRetentionClassification.Permanent, correlationId: "correlation-analogy-1", traceId: "trace-analogy-1", metadata: { fixture: true }, ...overrides };
}
function candidate(overrides: Partial<HistoricalCandidateReference> = {}): HistoricalCandidateReference {
  return { candidateType: HistoricalCandidateType.Event, recordId: "historical-event:analogue-one", recordVersion: "v1", lifecycleStatus: HistoricalEventStatus.Finalized, title: "Synthetic historical liquidity event", summary: "A historical liquidity event used only for deterministic comparison evidence.", applicablePeriod: "2008", regimeSummary: "Stressed liquidity, contracting growth, and tight credit.", dimensionValues: [{ dimension: AnalogyDimensionType.Liquidity, value: category("STRESSED"), evidenceReferenceIds: ["historical-evidence-1"], confidence: 9000 }, { dimension: AnalogyDimensionType.Growth, value: category("CONTRACTING"), evidenceReferenceIds: ["historical-evidence-2"], confidence: 8000 }, { dimension: AnalogyDimensionType.Credit, value: category("TIGHT"), evidenceReferenceIds: ["historical-evidence-3"], confidence: 7000 }], evidenceReferenceIds: ["historical-evidence-1", "historical-evidence-2", "historical-evidence-3"], sourceCount: 2, supportingEventCount: 1, limitations: ["Selected historical evidence may contain hindsight bias."], superseded: false, historicalOutcomeEvidence: [{ outcomeId: "historical-outcome-1", observation: "The supplied historical index declined during the observation window.", evidenceReferenceIds: ["historical-evidence-1"], explicitlyNotForecast: true }], qualityScore: 8000, ...overrides };
}
function profile(overrides: Partial<AnalogyWeightProfile> = {}): AnalogyWeightProfile {
  const base = { profileId: "analogy-weight-profile:macro-v1", schemaVersion: "1.0" as const, version: "v1", title: "Macro comparison profile", purpose: "Compare supplied current and historical regimes deterministically.", applicableComparisonType: "CURRENT_TO_HISTORICAL", weights: [{ dimension: AnalogyDimensionType.Liquidity, weight: 4000, comparisonMethod: AnalogyComparisonMethod.Exact }, { dimension: AnalogyDimensionType.Growth, weight: 3000, comparisonMethod: AnalogyComparisonMethod.Exact }, { dimension: AnalogyDimensionType.Credit, weight: 3000, comparisonMethod: AnalogyComparisonMethod.Exact }], requiredDimensions: [AnalogyDimensionType.Liquidity, AnalogyDimensionType.Growth], optionalDimensions: [AnalogyDimensionType.Credit], excludedDimensions: [], missingDataPolicy: AnalogyMissingDataPolicy.FailClosed, normalizationPolicy: AnalogyNormalizationPolicy.SumToScale, normalizationScale: ANALOGY_SCORE_SCALE as 10000, minimumEvidenceReferences: 1, minimumCandidateQuality: 5000, highQualityThreshold: 8000, moderateQualityThreshold: 6000, ownerApprovalReference: "owner-approval:d6-t4-profile-v1", ownerApproverActorType: "OWNER" as const, status: AnalogyWeightProfileStatus.Active, effectiveAt: "2026-07-19T20:00:00.000Z", policyVersion: "analogy-policy-v1" };
  const merged = { ...base, ...overrides, fingerprint: "" };
  const { fingerprint: _fingerprint, ...payload } = merged;
  return { ...payload, fingerprint: weightProfileFingerprint(payload) };
}
function request(candidateValue = candidate(), profileValue = profile(), overrides: Partial<HistoricalAnalogyRequest> = {}): HistoricalAnalogyRequest { return { requestId: "analogy-request:day6-t4", schemaVersion: "1.0", requestVersion: "v1", createdAt: "2026-07-19T21:30:00.000Z", currentSnapshotId: "current-situation:day6-t4", candidateReferences: [candidateValue], weightProfileId: profileValue.profileId, weightProfileVersion: profileValue.version, maximumResultCount: 10, requireCurrentCandidates: true, researchReference: { researchId: "research-1", researchVersion: "v1", frozenStatus: "FINALIZED" }, privacyLevel: PrivacyLevel.Internal, retention: AIAuditRetentionClassification.Permanent, correlationId: "correlation-analogy-1", traceId: "trace-analogy-1", metadata: { fixture: true }, ...overrides }; }
function setup(options: { readonly snapshot?: CurrentSituationSnapshot; readonly candidate?: HistoricalCandidateReference; readonly profile?: AnalogyWeightProfile; readonly request?: Partial<HistoricalAnalogyRequest> } = {}) { const repository = new InMemoryHistoricalAnalogyRepository(); const engine = new HistoricalAnalogyEngine(repository, undefined, new FixedClock()); const snapshotValue = options.snapshot ?? snapshot(); const candidateValue = options.candidate ?? candidate(); const profileValue = options.profile ?? profile(); engine.freezeSnapshot(snapshotValue); engine.registerWeightProfile(profileValue); engine.createRequest(request(candidateValue, profileValue, options.request)); return { repository, engine, snapshot: snapshotValue, candidate: candidateValue, profile: profileValue }; }
function complete(engine: HistoricalAnalogyEngine, candidateId = "historical-event:analogue-one", analogyId = "historical-analogy:comparison-one", extra: Partial<Parameters<HistoricalAnalogyEngine["complete"]>[0]> = {}) { return engine.complete({ analogyId, recordVersion: "v1", requestId: "analogy-request:day6-t4", candidateId, ...extra }).record; }
function review(id: string): AnalogyReview { return { reviewId: `${id}:review:1`, analogyId: id, createdAt: "2026-07-19T22:10:00.000Z", reviewer: "owner-1", reviewerActorType: "OWNER", decision: AnalogyReviewDecision.Useful, rationale: "Useful as bounded Research evidence, not a forecast.", acceptedSimilarityIds: [], acceptedDifferenceIds: [], unresolvedQuestionIds: [] }; }
function amendment(id: string, overrides: Partial<AnalogyAmendment> = {}): AnalogyAmendment { return { amendmentId: `${id}:amendment:1`, analogyId: id, createdAt: "2026-07-19T22:15:00.000Z", reason: "Append interpretation clarification without rewriting score.", changedInterpretationFields: ["limitations"], addedLimitations: [], authorReference: "owner-1", ...overrides }; }
function supersession(prior: string, successor: string): AnalogySupersession { return { supersessionId: `${prior}:supersession:1`, priorAnalogyId: prior, successorAnalogyId: successor, createdAt: "2026-07-19T22:20:00.000Z", reason: "Current snapshot changed.", changedSnapshot: true, changedCandidateVersion: false, changedWeightProfile: false, changedScoringMethod: false, ownerReference: "owner-1" }; }

const tests: ReadonlyArray<TestCase> = [
  { name: "valid current-situation snapshot", run: () => assertEqual(setup().snapshot.snapshotId, "current-situation:day6-t4", "snapshot") },
  { name: "future current-situation snapshot is rejected", run: () => expectError(() => setup({ snapshot: snapshot({ asOfTimestamp: "2027-01-01T00:00:00.000Z" }) }), "future") },
  { name: "valid Historical Event candidate", run: () => assertEqual(validateHistoricalCandidate(candidate()).valid, true, "event candidate") },
  { name: "valid Historical Pattern candidate", run: () => assertEqual(validateHistoricalCandidate(candidate({ candidateType: HistoricalCandidateType.Pattern, recordId: "historical-pattern:analogue-one", lifecycleStatus: HistoricalPatternStatus.Reviewed, supportingEventCount: 3 })).valid, true, "pattern candidate") },
  { name: "draft candidate rejected", run: () => assertEqual(validateHistoricalCandidate(candidate({ lifecycleStatus: HistoricalEventStatus.Proposed })).valid, false, "draft") },
  { name: "candidate without evidence rejected", run: () => assertEqual(validateHistoricalCandidate(candidate({ evidenceReferenceIds: [], sourceCount: 0 })).valid, false, "evidence") },
  { name: "superseded current-only candidate rejected", run: () => assertEqual(validateHistoricalCandidate(candidate({ superseded: true })).valid, false, "superseded") },
  { name: "frozen candidate version preserved", run: () => assertEqual(complete(setup().engine).candidateReference.recordVersion, "v1", "version") },
  { name: "valid weight profile", run: () => assertEqual(validateAnalogyWeightProfile(profile()).valid, true, "profile") },
  { name: "negative weight rejected", run: () => assertEqual(validateAnalogyWeightProfile(profile({ weights: [{ dimension: AnalogyDimensionType.Liquidity, weight: -1, comparisonMethod: AnalogyComparisonMethod.Exact }] })).valid, false, "negative") },
  { name: "duplicate dimension rejected", run: () => assertEqual(validateAnalogyWeightProfile(profile({ weights: [{ dimension: AnalogyDimensionType.Liquidity, weight: 5000, comparisonMethod: AnalogyComparisonMethod.Exact }, { dimension: AnalogyDimensionType.Liquidity, weight: 5000, comparisonMethod: AnalogyComparisonMethod.Exact }] })).valid, false, "duplicate") },
  { name: "required and excluded conflict rejected", run: () => assertEqual(validateAnalogyWeightProfile(profile({ excludedDimensions: [AnalogyDimensionType.Liquidity] })).valid, false, "conflict") },
  { name: "weight normalization validation", run: () => assertEqual(validateAnalogyWeightProfile(profile({ weights: [{ dimension: AnalogyDimensionType.Liquidity, weight: 9999, comparisonMethod: AnalogyComparisonMethod.Exact }] })).valid, false, "normalization") },
  { name: "AI actor cannot activate weight profile", run: () => { const value = profile(); const invalid = { ...value, ownerApproverActorType: undefined } as unknown as AnalogyWeightProfile; assertEqual(validateAnalogyWeightProfile(invalid).valid, false, "owner") } },
  { name: "weight profile fingerprint is deterministic", run: () => assertEqual(profile().fingerprint, profile().fingerprint, "fingerprint") },
  { name: "missing-data fail-closed behavior", run: () => { const value = candidate({ dimensionValues: candidate().dimensionValues.filter((item) => item.dimension !== AnalogyDimensionType.Growth) }); expectError(() => complete(setup({ candidate: value }).engine), "missing") } },
  { name: "missing-data exclusion behavior", run: () => { const value = candidate({ dimensionValues: candidate().dimensionValues.filter((item) => item.dimension !== AnalogyDimensionType.Growth) }); const record = complete(setup({ candidate: value, profile: profile({ missingDataPolicy: AnalogyMissingDataPolicy.ExcludeDimension }) }).engine); assertEqual(record.score.completenessScore, 7000, "completeness"); assertEqual(record.score.normalizedSimilarityScore, 10000, "similarity") } },
  { name: "missing-data penalty behavior", run: () => { const value = candidate({ dimensionValues: candidate().dimensionValues.filter((item) => item.dimension !== AnalogyDimensionType.Growth) }); const record = complete(setup({ candidate: value, profile: profile({ missingDataPolicy: AnalogyMissingDataPolicy.PenalizeScore }) }).engine); assertEqual(record.score.normalizedSimilarityScore, 7000, "penalty") } },
  { name: "missing-data review behavior", run: () => { const value = candidate({ dimensionValues: candidate().dimensionValues.filter((item) => item.dimension !== AnalogyDimensionType.Growth) }); const record = complete(setup({ candidate: value, profile: profile({ missingDataPolicy: AnalogyMissingDataPolicy.RequireReview }) }).engine); assertEqual(record.reviewRequired, true, "review") } },
  { name: "missing data never becomes neutral similarity", run: () => { const value = candidate({ dimensionValues: candidate().dimensionValues.map((item) => item.dimension === AnalogyDimensionType.Growth ? { ...item, value: missingCategory() } : item) }); const record = complete(setup({ candidate: value, profile: profile({ missingDataPolicy: AnalogyMissingDataPolicy.PenalizeScore }) }).engine); assertEqual(record.dimensionResults.find((item) => item.dimension === AnalogyDimensionType.Growth)?.similarityContribution, 0, "missing similarity") } },
  { name: "valid dimension comparison", run: () => assertEqual(complete(setup().engine).dimensionResults.length, 3, "dimensions") },
  { name: "similarity contribution calculation", run: () => assertEqual(complete(setup().engine).score.similarityPoints, 10000, "similarity points") },
  { name: "difference contribution calculation", run: () => { const value = candidate({ dimensionValues: candidate().dimensionValues.map((item) => item.dimension === AnalogyDimensionType.Growth ? { ...item, value: category("EXPANDING") } : item) }); assertEqual(complete(setup({ candidate: value }).engine).score.differencePoints, 3000, "difference points") } },
  { name: "numeric distance scoring", run: () => { const numeric = (value: number) => ({ valueType: AnalogyDimensionValueType.Number, numericValue: value, missing: false }) as const; const snap = snapshot({ regime: { ...snapshot().regime, dimensions: [{ featureId: "feature-liquidity", dimension: AnalogyDimensionType.Liquidity, value: numeric(100), evidenceReferenceIds: ["research-evidence-1"], confidence: 9000, disputed: false }] } }); const cand = candidate({ dimensionValues: [{ dimension: AnalogyDimensionType.Liquidity, value: numeric(90), evidenceReferenceIds: ["historical-evidence-1"], confidence: 9000 }] }); const prof = profile({ weights: [{ dimension: AnalogyDimensionType.Liquidity, weight: 10000, comparisonMethod: AnalogyComparisonMethod.NumericDistance }], requiredDimensions: [AnalogyDimensionType.Liquidity], optionalDimensions: [] }); assertEqual(complete(setup({ snapshot: snap, candidate: cand, profile: prof }).engine).score.normalizedSimilarityScore, 9000, "numeric score") } },
  { name: "set-overlap scoring", run: () => { const set = (values: ReadonlyArray<string>) => ({ valueType: AnalogyDimensionValueType.Set, setValues: values, missing: false }) as const; const snap = snapshot({ regime: { ...snapshot().regime, dimensions: [{ featureId: "feature-geography", dimension: AnalogyDimensionType.Geography, value: set(["US", "EU"]), evidenceReferenceIds: ["research-evidence-1"], confidence: 9000, disputed: false }] } }); const cand = candidate({ dimensionValues: [{ dimension: AnalogyDimensionType.Geography, value: set(["US", "ASIA"]), evidenceReferenceIds: ["historical-evidence-1"], confidence: 9000 }] }); const prof = profile({ weights: [{ dimension: AnalogyDimensionType.Geography, weight: 10000, comparisonMethod: AnalogyComparisonMethod.SetOverlap }], requiredDimensions: [AnalogyDimensionType.Geography], optionalDimensions: [] }); assertEqual(complete(setup({ snapshot: snap, candidate: cand, profile: prof }).engine).score.normalizedSimilarityScore, 3333, "set score") } },
  { name: "no division by zero", run: () => assertEqual(validateAnalogyScore({ scale: 10000, totalEligibleWeight: 0, comparedWeight: 0, missingWeight: 0, similarityPoints: 0, differencePoints: 0, normalizedSimilarityScore: 0, normalizedDifferenceScore: 10000, completenessScore: 0, evidenceQualityScore: 0, candidateQualityScore: 0, components: [] }).valid, false, "zero") },
  { name: "non-finite dimension value rejected", run: () => assertEqual(validateAnalogyDimensionValue({ valueType: AnalogyDimensionValueType.Number, numericValue: Number.NaN, missing: false }).valid, false, "finite") },
  { name: "non-finite score rejected", run: () => assertEqual(validateAnalogyScore({ ...complete(setup().engine).score, normalizedSimilarityScore: Number.NaN }).valid, false, "finite score") },
  { name: "similarity and completeness remain separate", run: () => { const value = candidate({ dimensionValues: candidate().dimensionValues.filter((item) => item.dimension !== AnalogyDimensionType.Credit) }); const record = complete(setup({ candidate: value, profile: profile({ missingDataPolicy: AnalogyMissingDataPolicy.ExcludeDimension }) }).engine); assertEqual(record.score.normalizedSimilarityScore, 10000, "similarity"); assertEqual(record.score.completenessScore, 7000, "completeness") } },
  { name: "evidence quality and similarity remain separate", run: () => { const value = candidate({ dimensionValues: candidate().dimensionValues.map((item) => ({ ...item, confidence: 3000 })) }); const record = complete(setup({ candidate: value }).engine); assertEqual(record.score.normalizedSimilarityScore, 10000, "similarity"); assertEqual(record.score.evidenceQualityScore, 3000, "evidence") } },
  { name: "low completeness prevents high quality", run: () => { const value = candidate({ dimensionValues: candidate().dimensionValues.slice(0, 1) }); const prof = profile({ missingDataPolicy: AnalogyMissingDataPolicy.ExcludeDimension, requiredDimensions: [AnalogyDimensionType.Liquidity] }); assertTrue(complete(setup({ candidate: value, profile: prof }).engine).quality.classification !== AnalogyQualityClassification.High, "quality") } },
  { name: "deterministic scoring", run: () => assertDeepEqual(complete(setup().engine).score, complete(setup().engine).score, "score") },
  { name: "deterministic rounding", run: () => { const record = complete(setup().engine); assertTrue(Number.isSafeInteger(record.score.normalizedSimilarityScore), "integer rounding") } },
  { name: "deterministic ranking", run: () => { const { engine } = setup(); complete(engine, undefined, "historical-analogy:a"); complete(engine, undefined, "historical-analogy:b"); assertDeepEqual(engine.rank().map((item) => item.analogyId), ["historical-analogy:a", "historical-analogy:b"], "rank") } },
  { name: "stable candidate tie-breaking", run: () => { const first = candidate({ recordId: "historical-event:z" }); const second = candidate({ recordId: "historical-event:a" }); const prof = profile(); const repository = new InMemoryHistoricalAnalogyRepository(); const engine = new HistoricalAnalogyEngine(repository, undefined, new FixedClock()); engine.freezeSnapshot(snapshot()); engine.registerWeightProfile(prof); engine.createRequest(request(first, prof, { candidateReferences: [first, second] })); complete(engine, first.recordId, "historical-analogy:z"); complete(engine, second.recordId, "historical-analogy:a"); assertEqual(engine.rank()[0]?.candidateReference.recordId, second.recordId, "tie") } },
  { name: "strongest similarities preserved", run: () => assertTrue(complete(setup().engine).strongestSimilarities.length > 0, "similarities") },
  { name: "strongest differences preserved", run: () => { const value = candidate({ dimensionValues: candidate().dimensionValues.map((item) => ({ ...item, value: category("DIFFERENT") })) }); assertTrue(complete(setup({ candidate: value }).engine).strongestDifferences.length > 0, "differences") } },
  { name: "historical outcomes remain observations not forecasts", run: () => assertEqual(complete(setup().engine).historicalOutcomeEvidence[0]?.explicitlyNotForecast, true, "outcome") },
  { name: "guaranteed-recurrence language rejected", run: () => expectError(() => complete(setup({ candidate: candidate({ summary: "History will repeat and gains are guaranteed." }) }).engine), "guaranteed") },
  { name: "trading recommendation output rejected", run: () => expectError(() => complete(setup({ candidate: candidate({ summary: "Buy this trading signal now." }) }).engine), "trading") },
  { name: "bias risks preserved", run: () => { const risks = defaultAnalogyBiasRisks("historical-analogy:comparison-one"); assertEqual(complete(setup().engine, undefined, undefined, { biasRisks: risks }).biasRisks.length, 3, "bias") } },
  { name: "critical regime mismatch preserved", run: () => { const risk: AnalogyBiasRisk = { riskId: "bias-critical-1", riskType: AnalogyBiasRiskType.RegimeMismatch, severity: AnalogyRiskSeverity.Critical, statement: "Policy regime materially differs.", evidenceReferenceIds: [], requiresReview: true }; const record = complete(setup().engine, undefined, undefined, { biasRisks: [risk] }); assertEqual(record.reviewRequired, true, "critical") } },
  { name: "comparison quality is not profitability", run: () => assertTrue(complete(setup().engine).limitations.some((item) => item.statement.includes("not trading profitability")), "profitability boundary") },
  { name: "valid lifecycle transitions", run: () => assertDeepEqual(complete(setup().engine).history.map((item) => item.toStatus), [HistoricalAnalogyStatus.Validating, HistoricalAnalogyStatus.Completed], "lifecycle") },
  { name: "invalid reverse transition rejected", run: () => { const { engine } = setup(); const record = complete(engine); engine.archive(record.analogyId, "2026-07-19T23:00:00.000Z", "Archive."); expectError(() => engine.review(review(record.analogyId)), "lifecycle") } },
  { name: "review before completion rejected", run: () => expectError(() => setup().engine.review(review("historical-analogy:missing")), "does not exist") },
  { name: "amendment preserves original", run: () => { const { engine } = setup(); const record = complete(engine); engine.amend(amendment(record.analogyId)); assertEqual(engine.history(record.analogyId)?.amendments.length, 1, "amendment"); assertEqual(engine.get(record.analogyId)?.score.normalizedSimilarityScore, record.score.normalizedSimilarityScore, "score") } },
  { name: "self-referential amendment rejected", run: () => { const { engine } = setup(); const record = complete(engine); expectError(() => engine.amend(amendment(record.analogyId, { parentAmendmentId: `${record.analogyId}:amendment:1` })), "self-reference") } },
  { name: "supersession preserves prior", run: () => { const { engine } = setup(); const first = complete(engine, undefined, "historical-analogy:first"); complete(engine, undefined, "historical-analogy:second"); engine.supersede(supersession(first.analogyId, "historical-analogy:second")); assertEqual(engine.get(first.analogyId)?.status, HistoricalAnalogyStatus.Superseded, "status") } },
  { name: "self-supersession rejected", run: () => { const { engine } = setup(); const record = complete(engine); expectError(() => engine.supersede(supersession(record.analogyId, record.analogyId)), "itself") } },
  { name: "cyclic supersession rejected", run: () => { const { engine } = setup(); complete(engine, undefined, "historical-analogy:first"); complete(engine, undefined, "historical-analogy:second"); engine.supersede(supersession("historical-analogy:first", "historical-analogy:second")); expectError(() => engine.supersede(supersession("historical-analogy:second", "historical-analogy:first")), "cyclic") } },
  { name: "archive preserves record", run: () => { const { engine } = setup(); const record = complete(engine); engine.archive(record.analogyId, "2026-07-19T23:00:00.000Z", "Archive without deletion."); assertEqual(engine.get(record.analogyId)?.status, HistoricalAnalogyStatus.Archived, "archive") } },
  { name: "query by current snapshot", run: () => assertEqual(setupAndQuery({ currentSnapshotId: "current-situation:day6-t4" }), 1, "query") },
  { name: "query by Historical Event", run: () => assertEqual(setupAndQuery({ historicalEventId: "historical-event:analogue-one" }), 1, "query") },
  { name: "query by Historical Pattern", run: () => { const cand = candidate({ candidateType: HistoricalCandidateType.Pattern, recordId: "historical-pattern:analogue-one", lifecycleStatus: HistoricalPatternStatus.Finalized }); const { engine } = setup({ candidate: cand }); complete(engine, cand.recordId); assertEqual(engine.query({ filter: { historicalPatternId: cand.recordId } }).length, 1, "query") } },
  { name: "query by weight profile", run: () => assertEqual(setupAndQuery({ weightProfileId: "analogy-weight-profile:macro-v1" }), 1, "query") },
  { name: "query by Research reference", run: () => assertEqual(setupAndQuery({ researchId: "research-1" }), 1, "query") },
  { name: "query by quality", run: () => assertEqual(setupAndQuery({ qualityClassifications: [AnalogyQualityClassification.High] }), 1, "query") },
  { name: "query by score range", run: () => assertEqual(setupAndQuery({ minimumSimilarityScore: 9000, maximumSimilarityScore: 10000 }), 1, "query") },
  { name: "query by completeness range", run: () => assertEqual(setupAndQuery({ minimumCompletenessScore: 9000, maximumCompletenessScore: 10000 }), 1, "query") },
  { name: "ranked result limit", run: () => { const { engine } = setup(); complete(engine, undefined, "historical-analogy:a"); complete(engine, undefined, "historical-analogy:b"); assertEqual(engine.rank({}, 1).length, 1, "limit") } },
  { name: "deterministic pagination", run: () => { const { engine } = setup(); complete(engine, undefined, "historical-analogy:a"); complete(engine, undefined, "historical-analogy:b"); assertEqual(engine.query({ offset: 1, limit: 1 })[0]?.analogyId, "historical-analogy:b", "page") } },
  { name: "invalid pagination rejected", run: () => expectError(() => setup().engine.query({ offset: -1 }), "pagination") },
  { name: "deterministic statistics", run: () => { const { engine } = setup(); complete(engine); assertDeepEqual(engine.statistics(), engine.statistics(), "statistics") } },
  { name: "statistics preserve explicit sample size", run: () => { const { engine } = setup(); complete(engine); assertEqual(engine.statistics().sampleSize, 1, "sample") } },
  { name: "deterministic export", run: () => { const { repository, engine } = setup(); complete(engine); const requestValue = { exportId: "analogy-export-1", requestedAt: "2026-07-19T23:00:00.000Z", query: {}, format: HistoricalAnalogyExportFormat.Ndjson, destination: HistoricalAnalogyExportDestination.LocalSnapshot }; const policy = { allowExternalExports: false, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: [] }; assertEqual(exportHistoricalAnalogies(repository, requestValue, policy).content, exportHistoricalAnalogies(repository, requestValue, policy).content, "export") } },
  { name: "LOCAL_ONLY export restriction", run: () => { const { repository, engine } = setup({ request: { privacyLevel: PrivacyLevel.LocalOnly } }); complete(engine); const value = exportHistoricalAnalogies(repository, { exportId: "analogy-export-local", requestedAt: "2026-07-19T23:00:00.000Z", query: {}, format: HistoricalAnalogyExportFormat.Json, destination: HistoricalAnalogyExportDestination.ExternalTransfer }, { allowExternalExports: true, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: [] }); assertEqual(value.status, HistoricalAnalogyExportStatus.Rejected, "status") } },
  { name: "SENSITIVE export authorization", run: () => { const { repository, engine } = setup({ request: { privacyLevel: PrivacyLevel.Sensitive } }); complete(engine); const value = { exportId: "analogy-export-sensitive", requestedAt: "2026-07-19T23:00:00.000Z", query: {}, format: HistoricalAnalogyExportFormat.Json, destination: HistoricalAnalogyExportDestination.ExternalTransfer }; const policy = { allowExternalExports: true, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: ["owner-export-1"] }; assertEqual(exportHistoricalAnalogies(repository, value, policy).status, HistoricalAnalogyExportStatus.Rejected, "reject"); assertEqual(exportHistoricalAnalogies(repository, { ...value, sensitiveAuthorizationReference: "owner-export-1" }, policy).status, HistoricalAnalogyExportStatus.Exported, "allow") } },
  { name: "secret metadata rejection", run: () => expectError(() => setup({ snapshot: snapshot({ metadata: { api_key: "forbidden" } }) }), "secret") },
  { name: "input immutability", run: () => { const value = snapshot(); const before = JSON.stringify(value); setup({ snapshot: value }); assertEqual(JSON.stringify(value), before, "input") } },
  { name: "defensive copies", run: () => { const { engine } = setup(); const record = complete(engine); const read = engine.get(record.analogyId) as typeof record; (read.candidateReference as { title: string }).title = "Mutated"; assertEqual(engine.get(record.analogyId)?.candidateReference.title, record.candidateReference.title, "copy") } },
  { name: "identical append idempotency", run: () => { const repository = new InMemoryHistoricalAnalogyRepository(); const engine = new HistoricalAnalogyEngine(repository, undefined, new FixedClock()); const value = snapshot(); assertEqual(engine.freezeSnapshot(value).status, AnalogyAppendStatus.Appended, "first"); assertEqual(engine.freezeSnapshot(value).status, AnalogyAppendStatus.Replayed, "replay") } },
  { name: "conflicting duplicate rejection", run: () => { const repository = new InMemoryHistoricalAnalogyRepository(); const engine = new HistoricalAnalogyEngine(repository, undefined, new FixedClock()); const value = snapshot(); engine.freezeSnapshot(value); expectError(() => engine.freezeSnapshot({ ...value, markets: ["EU"] }), "conflict") } },
  { name: "corrupt NDJSON fails closed", run: () => { const directory = mkdtempSync(join(tmpdir(), "analogy-corrupt-")); try { writeFileSync(join(directory, "historical-analogy-engine-v1.ndjson"), "{}"); expectError(() => new LocalNdjsonHistoricalAnalogyRepository(directory), "truncated"); } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "local reload preserves records", run: () => { const directory = mkdtempSync(join(tmpdir(), "analogy-reload-")); try { const repository = new LocalNdjsonHistoricalAnalogyRepository(directory); const engine = new HistoricalAnalogyEngine(repository, undefined, new FixedClock()); const snap = snapshot(); const prof = profile(); engine.freezeSnapshot(snap); engine.registerWeightProfile(prof); engine.createRequest(request(candidate(), prof)); const record = complete(engine); assertEqual(new LocalNdjsonHistoricalAnalogyRepository(directory).getAnalogyById(record.analogyId)?.analogyId, record.analogyId, "reload"); } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "durable append does not rewrite history", run: () => { const directory = mkdtempSync(join(tmpdir(), "analogy-append-")); try { const repository = new LocalNdjsonHistoricalAnalogyRepository(directory); const engine = new HistoricalAnalogyEngine(repository, undefined, new FixedClock()); engine.freezeSnapshot(snapshot()); const before = readFileSync(repository.getStoragePath(), "utf8"); engine.registerWeightProfile(profile()); const after = readFileSync(repository.getStoragePath(), "utf8"); assertTrue(after.startsWith(before) && after.length > before.length, "append") } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "path traversal rejected", run: () => { const directory = mkdtempSync(join(tmpdir(), "analogy-path-")); try { expectError(() => new LocalNdjsonHistoricalAnalogyRepository(directory, "../escape"), "path traversal"); } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "audit translation deterministic", run: () => { const source: HistoricalAnalogyAuditRecord = { auditId: "analogy-audit-1", operationType: HistoricalAnalogyAuditOperationType.AnalogyCompleted, sourceRecordId: "historical-analogy:comparison-one", recordVersion: "v1", timestamp: "2026-07-19T22:00:00.000Z", status: "COMPLETED", reasonCodes: ["COMPARISON COMPLETED"], requestId: "analogy-request:day6-t4", snapshotId: "current-situation:day6-t4", candidateId: "historical-event:analogue-one", profileId: "analogy-weight-profile:macro-v1", profileVersion: "v1", scoringMethodVersion: "1.0", score: complete(setup().engine).score, limitations: ["Not predictive"], privacyLevel: PrivacyLevel.Internal, retention: AIAuditRetentionClassification.Permanent, correlationId: "correlation-analogy-1", traceId: "trace-analogy-1", policyVersions: { analogy: "v1" }, metadata: { fixture: true } }; const context = { idempotencyKey: "analogy-audit-idempotency-1", actor: { type: AIAuditActorType.Owner, actorId: "owner-1" }, parentAuditRecordIds: [], relatedAuditRecordIds: [] }; const first = auditRecordFromHistoricalAnalogy(source, context); assertDeepEqual(first, auditRecordFromHistoricalAnalogy(source, context), "audit"); assertEqual(first.recordType, AIAuditRecordType.HistoricalAnalogy, "record type"); assertEqual(first.sourceSubsystem, AIAuditSourceSubsystem.HistoricalAnalogyEngine, "source") } },
  { name: "historical records are not mutated", run: () => { const source = candidate(); const before = JSON.stringify(source); complete(setup({ candidate: source }).engine); assertEqual(JSON.stringify(source), before, "historical") } },
  { name: "Research records are not mutated", run: () => { const source = { researchId: "research-1", status: "FINALIZED" }; const before = JSON.stringify(source); complete(setup().engine); assertEqual(JSON.stringify(source), before, "research") } },
  { name: "Prediction records are not mutated", run: () => { const source = { predictionId: "prediction-1", status: "LOCKED" }; const before = JSON.stringify(source); complete(setup().engine); assertEqual(JSON.stringify(source), before, "prediction") } },
  { name: "Strategy records are not mutated", run: () => { const source = { strategyId: "strategy-1", status: "ACTIVE" }; const before = JSON.stringify(source); complete(setup().engine); assertEqual(JSON.stringify(source), before, "strategy") } },
  { name: "repository exposes no update overwrite or delete", run: () => { const repository: object = new InMemoryHistoricalAnalogyRepository(); assertTrue(!("update" in repository) && !("overwrite" in repository) && !("delete" in repository), "mutable API") } },
  { name: "score method version is frozen", run: () => assertEqual(complete(setup().engine).scoringMethod, AnalogyScoreMethod.WeightedDimensionV1, "method") },
  { name: "weight profile version is frozen", run: () => assertEqual(complete(setup().engine).weightProfileReference.profileVersion, "v1", "profile") },
  { name: "Research reference is frozen", run: () => assertEqual(complete(setup().engine).researchReference?.researchVersion, "v1", "research") },
  { name: "Event Replay is compatibility-only", run: () => assertEqual(complete(setup().engine).replayCompatibilityReferences.length, 0, "replay") },
  { name: "no prediction is created", run: () => assertEqual(complete(setup().engine).predictionReferences.length, 0, "prediction") },
  { name: "no strategy is created", run: () => assertEqual(complete(setup().engine).strategyReferences.length, 0, "strategy") },
  { name: "no random identity generation", run: () => assertEqual(complete(setup().engine).analogyId, "historical-analogy:comparison-one", "identity") },
  { name: "fingerprints are not signatures", run: () => assertTrue(historicalAnalogyFingerprint(snapshot()).startsWith("fnv1a64:"), "fingerprint") },
];

function setupAndQuery(filter: AnalogyFilter): number { const { engine } = setup(); complete(engine); return engine.query({ filter }).length; }
let passed = 0;
for (const test of tests) { try { test.run(); passed += 1; } catch (error: unknown) { const message = error instanceof Error ? error.message : String(error); console.error(`FAIL: ${test.name}: ${message}`); throw error; } }
console.log(`Historical Analogy Engine: ${String(passed)}/${String(tests.length)} tests passed.`);
