import {psychologyKnowledge,psychologyReview,psychologySources,psychologyRevision} from './MacroPsychologyCatalog';
// Educational references only. Nothing here is an executable trading rule.
export const MACRO_PLAYBOOK_VERSION = 'OPTIONS_MACRO_PLAYBOOK_V1';
export type KnowledgeStatus = 'PROCESS_GUIDE' | 'MECHANICS_REFERENCE' | 'CANDIDATE_UNTESTED' | 'ILLUSTRATION_ONLY';
export interface KnowledgeItem {
  id: string; group: string; title: string; status: KnowledgeStatus; sources: string[];
  topics: string[]; principle: string; application: string; limits: string; destination: string;
}
export const macroSources = [
  {id:'owner',title:'Owner-supplied trader experience and 13 conceptual images',url:null,coverage:'Supplied prose and illustrations reviewed; author attribution and performance unverified.'},
  {id:'course',title:'Macro trading course — syllabus',url:'https://macro-trading.pages.dev/',coverage:'Full syllabus reviewed. This is a 16-chapter course; other chapter bodies are not all reviewed.'},
  {id:'thesis',title:'Course chapter 11 — scenarios and thesis',url:'https://macro-trading.pages.dev/12-第11章-情景分析与论点构建/',coverage:'Chapter body reviewed as educational opinion; historical anecdotes and numerical examples not independently verified.'},
  {id:'review',title:'Course chapter 16 — uncertainty and review',url:'https://macro-trading.pages.dev/17-第16章-不确定错误复盘与进化/',coverage:'Chapter body reviewed; causal and psychological labels require independent evidence.'},
  {id:'spread',title:'OIC — bull call spread',url:'https://www.optionseducation.org/strategies/all-strategies/bull-call-spread-debit-call-spread',coverage:'Payoff, volatility, assignment and expiration mechanics checked.'},
  {id:'stops',title:'FINRA — stop orders during volatile markets',url:'https://www.finra.org/investors/insights/stop-orders-factors-consider-during-volatile-markets',coverage:'Trigger, execution price and stop-limit nonexecution distinctions checked.'},
  {id:'greeks',title:'OIC — understanding options Greeks',url:'https://www.optionseducation.org/advancedconcepts/understanding-options-greeks',coverage:'Theoretical sensitivities, not exact future premium predictions.'},
  {id:'theta',title:'OIC — theta',url:'https://www.optionseducation.org/advancedconcepts/theta',coverage:'Conditional time decay and moneyness dependence checked.'},
  {id:'vega',title:'OIC — vega',url:'https://www.optionseducation.org/advancedconcepts/vega',coverage:'Sensitivity to implied volatility checked.'},
];
const item = (id:string,group:string,title:string,status:KnowledgeStatus,sources:string[],topics:string[],principle:string,application:string,limits:string,destination:string):KnowledgeItem =>
  ({id,group,title,status,sources,topics,principle,application,limits,destination});
export const macroKnowledge: KnowledgeItem[] = [
  item('research','Macro reasoning','Broaden the evidence base','PROCESS_GUIDE',['owner','course'],['Travel','Reading','History','English'],
    'Use diverse viewpoints, original language sources and historical comparisons to challenge a preferred explanation.',
    'Record source dates and translation uncertainty; compare the historical regime with the current GLD/IBIT context.',
    'Travel anecdotes are selective observations. Historical resemblance and language fluency do not establish predictive power. These are personal research practices, not return factors.','context'),
  item('expectations','Macro reasoning','From a macro story to a testable hypothesis','PROCESS_GUIDE',['owner','course','thesis'],['Economics','Policy transmission','Consensus','Scenario analysis'],
    'Describe a causal chain, competing outcomes and the difference between your view and documented market expectations.',
    'Separate event expectations, verified actuals, rates/USD transmission and observed GLD/IBIT prices. Label subjective probabilities; leave unsupported probabilities unknown.',
    'Neither a correct policy forecast nor a made-up scenario probability establishes an option opportunity. Correlations and policy reactions vary by regime.','context'),
  item('horizons','Macro reasoning','Direction needs a horizon','PROCESS_GUIDE',['owner','owner-psychology-20260923'],['Scalper','Day trader','Swing trader','Position trader','Long-term investor','Investor research cadence','Trader research cadence'],
    'Keep the macro thesis horizon, ETF signal timeframe, intended holding period and option expiration separate. Investors may research a business or macro thesis deeply up front and reassess periodically; traders need more frequent relevant updates, including overnight changes.',
    'Explain how a five-minute setup fits the intended holding window and why the contract has sufficient time for the thesis. Before acting as a trader, refresh the thesis, risk and position using source-dated evidence; an investor need not react to every intraday move.',
    'Neither style is inherently superior. Long-term conviction cannot justify holding an expiring option indefinitely, and constant monitoring cannot turn stale or weak sources into certainty. The five trader types are approximate; current collection cadence does not support reliable scalping.','guidance'),
  item('styles','Macro reasoning','Style is a research lens','PROCESS_GUIDE',['owner'],['Value','Contrarian','Catalyst / speculative','Fundamental / growth','Macro','Narrative'],
    'Identify whether the idea rests on valuation, disputed consensus, a catalyst, business growth, macro transmission or changing beliefs.',
    'For GLD/IBIT, explain the underlying exposure and ETF link; do not import operating-company valuation assumptions without a model.',
    'Styles overlap. Contrarian does not mean automatically opposing consensus; a compelling narrative or catalyst does not establish a favorable price or probability.','guidance'),
  item('mechanisms','Macro reasoning','Mechanisms need evidence','MECHANICS_REFERENCE',['owner','greeks'],['Dealer hedging','Liquidity','Positioning','Open interest','Delta','Gamma','Theta','Vega'],
    'Greeks describe model sensitivities; liquidity and positioning can affect how a macro view is expressed.',
    'Use the saved sensitivities with their clocks, bid/ask and contract identity. Distinguish a possible mechanism from an observed one.',
    'Open interest and volume alone do not identify dealer direction. Delta is not a profit peak or a verified win probability. No dealer-flow detector is introduced.','guidance'),
  item('journal','Decision process','Write before knowing the result','PROCESS_GUIDE',['owner','thesis','review','owner-psychology-20260926'],['Trading journal','Invalidation','Counterevidence','Review','Exit before entry'],
    'Retain the original reasoning, source references and later updates as separate records.',
    'Before entry document where/how to exit if wrong, how/where profit is taken if right, and what evidence invalidates the thesis. Reuse invalidation, deadline, costs, counterevidence and existing planned stop/target fields; use the trade journal for reported executions and fees.',
    'A note labeled pre-trade is not proof it preceded a fill. Text coverage does not validate its logic. New notes do not backfill the frozen trend cohort.','journal'),
  item('uncertainty','Decision process','Update when evidence changes','PROCESS_GUIDE',['owner','review'],['Uncertainty','Imperfection','Mistakes'],
    'Keep an alternative explanation and a clear observation that would contradict the thesis.',
    'Record what changed and which evidence was available at the decision time.',
    'Loss alone does not prove a bad decision; profit does not prove skill. Do not automatically attribute a loss to luck, fear, manipulation or a broker.','reviews'),
  item('patience','Decision process','Waiting is a valid decision','PROCESS_GUIDE',['owner','course','owner-psychology-20260926'],['Boredom','No trade','Selectivity','Cash','Optionality'],
    'Document missing evidence and the observation that would justify another review. Choosing not to trade is a valid option with unclear direction, poor risk/reward, low liquidity, noisy structure, missing evidence or voluntarily reported insufficient attention/readiness.',
    'Keep WATCH, NO_TRADE or cash when no opportunity qualifies. Cash can preserve low market exposure, liquidity, buying power, optionality and the ability to wait; capital need not be forced into a position.',
    'Fewer trades alone do not improve expectancy. Cash is not risk-free in every sense; there is no allocation target or automatic capital movement. Readiness is voluntary reflection, never inferred health or an automatic psychological gate. Patience does not cancel a defined exit or monitoring obligation.','guidance'),
  item('balance','Decision process','Make the monitoring plan sustainable','PROCESS_GUIDE',['owner','owner-psychology-20260926'],['Leisure','Sleep and rest','Exercise','Meals','Meditation','Work/life balance','Microscopic trading','Monitoring capacity'],
    'Choose a review cadence compatible with the strategy and record who can monitor the position.',
    'Include a contingency for being away, a stopped collector or unavailable quotes before relying on a short-lived option setup. Voluntarily consider attention, monitoring capacity and time away; constant watching when planned work is complete, no opportunity exists or markets are closed is not automatically productive.',
    'No lifestyle behavior is prescribed and no health or relationship information is collected or inferred. Lifestyle examples are not a diagnosis or proven edge. Quiet Mondays, midday breaks, open-for-exits and close-for-entries are not universal rules; existing exit obligations remain.','planner'),
  item('mechanical','Exit and exposure','Mechanical stop example','CANDIDATE_UNTESTED',['owner','stops'],['Mechanical stop','Stock -7%'],
    'The supplied -7% threshold is an author-specific stock example.',
    'Compare any proposed trigger with ETF volatility, option sensitivities, costs and expected execution.',
    'Do not transfer -7% to options or replace the frozen study stop. A triggered stop does not guarantee its execution price.','planner'),
  item('size','Exit and exposure','Reducing exposure','PROCESS_GUIDE',['owner','owner-psychology-20260926'],['Positional stop','Partial reduction','Shared market factor','Total directional exposure','Emotional sizing'],
    'A smaller position changes future dollar exposure; it does not fix the original thesis.',
    'Reassess remaining whole contracts and total account exposure using capital policy, defined maximum loss, instrument economics, evidence quality and current risk constraints. Different tickers need not be independent: technology, semiconductors, high beta, small caps and long calls can share a factor. Ask how many positions might lose together if that factor moves against the idea.',
    'Size changes need a new documented decision. Excitement, anger, revenge, recent wins or a hot-hand belief cannot increase allowed size; confidence is not a sizing multiplier. Correlations are not assumed static; no correlation engine, anecdotal portfolio score or automatic reduction is implemented. A smaller loss or later recovery is not guaranteed.','planner'),
  item('thesis-stop','Exit and exposure','Distinguish challenged and invalidated','PROCESS_GUIDE',['owner','thesis','owner-psychology-20260923','owner-psychology-20260926'],['Thesis stop','Do not rewrite the reason','PRICE_ADVERSE_BUT_THESIS_NOT_INVALIDATED','THESIS_CORE_VARIABLE_CHANGED','Capital survival','LOSS_AVERSION_STOP_DRIFT'],
    'PRICE_ADVERSE_BUT_THESIS_NOT_INVALIDATED names an adverse price move without verified invalidation; loss alone does not prove the macro thesis wrong. THESIS_CORE_VARIABLE_CHANGED names a verified change in an original core variable that requires reassessment.',
    'Before entry identify the relevant war, sanctions, energy, central-bank policy, rates, dollar, liquidity or other original macro variable and its evidence source. Document independent exits for wrong/right outcomes and thesis invalidation before entry. Compare new facts with the saved thesis, then apply price, time, capital and contract exits; preserving capital protects future participation.',
    'These terms are educational, not an automatic state machine. A compelling story cannot override an independent exit. Moving a stop farther away solely to avoid realizing a loss is LOSS_AVERSION_STOP_DRIFT; the plan remains frozen after entry except already predefined exceptions supported by new verified information. No new stop percentage. Neither hedge nor averaging repairs a broken thesis or erases a loss; requiring both price and thesis damage is not a universal rule.','journal'),
  item('technical-stop','Exit and exposure','Technical exits need specified inputs','CANDIDATE_UNTESTED',['owner'],['Support','MACD','RSI','Bollinger bands','50 / 200 moving averages','Vortex','Gap fill'],
    'An indicator-based exit requires a timeframe, formula, threshold and observable trigger.',
    'Use qualified traded-ETF bars and register a separate prospective rule before measuring it.',
    'Several correlated indicators are not independent confirmations. A gap need not fill. These indicators are not newly implemented trading gates.','guidance'),
  item('time-stop','Exit and exposure','A thesis has a deadline','PROCESS_GUIDE',['owner','theta','owner-psychology-20260926'],['Time-based stop','Catalyst deadline'],
    'Specify when the expected development must occur and a separate option exit deadline.',
    'Before entry record catalyst timing, review time, expiration and the action if the expected response does not appear; retain the original independent stop, profit-taking and thesis-invalidation plan.',
    'Waiting consumes option time; a deadline does not guarantee an executable exit. Preserve existing frozen deadlines.','journal'),
  item('spread-risk','Exit and exposure','Defined payoff is not a guaranteed exit','MECHANICS_REFERENCE',['owner','spread'],['Built-in stop','Call debit spread','Put debit spread','Credit spreads','Iron condor'],
    'For a standard intact equal-quantity, same-expiry bull call spread, gross terminal loss is the net debit; maximum gross gain is strike width less debit.',
    'Include the multiplier, all legs and costs. Call terminal breakeven is long strike plus debit; describe exercise and assignment handling separately.',
    'Operational exposure can change through legging, assignment or expiration. Long calls/puts already limit premium loss before exercise. Other structures need their own payoff models; this catalog does not enable them.','planner'),
  item('volatility','Exit and exposure','Direction and volatility are different bets','MECHANICS_REFERENCE',['owner','vega','theta'],['Volatility stop','IV crush','Near expiration'],
    'Option values also depend on implied volatility and remaining time. Direction alone is insufficient.',
    'Review contract-level IV and net sensitivities across every leg; identify what evidence supports a volatility scenario.',
    'High IV alone is not an automatic ban or selling signal. Theta depends on moneyness and other inputs; it is not a fixed daily bill. No IV history or exit trigger is invented.','guidance'),
  item('overnight','Exit and exposure','Decide overnight exposure in advance','PROCESS_GUIDE',['owner','stops'],['Overnight stop','Gap risk','Event risk'],
    'Consider what can happen while the instrument cannot be traded and how much exposure remains.',
    'Write a pre-close decision and next-session contingency; BTC trading overnight does not make IBIT options continuously executable.',
    'A stop cannot guarantee protection across a gap. Buying another option introduces costs and may not cover the intended scenario.','planner'),
  item('hedge','Exit and exposure','Test the whole hedge','PROCESS_GUIDE',['owner','owner-psychology-20260923','owner-psychology-20260926'],['Hedging stop','Call plus put','Cross-asset hedge','Basis risk','Net exposure','Decision time'],
    'A hedge may reduce portfolio sensitivity and buy decision time during uncertain macro news, but it cannot repair an invalid original thesis.',
    'State the hedging instrument, exact risk, horizon, ratio or quantity, cost, basis risk, remaining net exposure and hedge exit condition. Compare combined payoff and net sensitivities under direction, IV and time scenarios; reassess whether the thesis failed, entry was early, the move is temporary or the regime changed.',
    'Hedging buys time only conditionally: it costs money, adds basis risk and may also lose. Opposite directions alone do not demonstrate protection; a hedge cannot fix invalidation or waive an independent exit. No automatic hedge, new SPY/QQQ/sector strategy or broader trading universe is enabled.','planner'),
  item('cost','Exit and exposure','Evaluate all-in costs before entry','PROCESS_GUIDE',['owner','stops'],['Cost control','Limit order','Premium','Position size'],
    'Compare entry cost, spread, exit costs and full-premium exposure before evaluating a target.',
    'Use the existing cost desk and whole-contract calculations; distinguish declared assumptions from actual fees.',
    'A limit order controls the acceptable price but may not fill. A cheap premium does not establish good value, and waiting for a lower entry may change the signal.','planner'),
  item('stop-hunting','Exit and exposure','Do not infer intent from a reversal','CANDIDATE_UNTESTED',['owner','stops'],['Stop hunting','Closing confirmation','Wider stops'],
    'A reversal after a stop is an observed path, not proof someone targeted the order.',
    'If testing close confirmation or volatility-based exits, predefine the rule and evaluate its added exposure.',
    'Wider or delayed stops can increase loss. No recommendation to hide stops, abandon them or wait for a rebound is activated.','reviews'),
  item('thirty-thirty','Exit and exposure','30/30 is an untested personal heuristic','CANDIDATE_UNTESTED',['owner'],['30% remaining time','30% option loss'],
    'The author proposes a time-or-loss review once the thesis begins to weaken.',
    'Any future test must freeze the time anchor, original remaining life, loss denominator and priority among exits.',
    'Challenged is not invalidated. This heuristic cannot grant extra waiting after a hard exit. No 30% threshold becomes an active rule.','reviews'),
  item('adding','Exit and exposure','Re-entry is a fresh exposure decision','CANDIDATE_UNTESTED',['owner','owner-psychology-20260923','owner-psychology-20260926'],['One loss addition','Adding winners','Re-entering','Fresh-cash test','Rolling','Debit spread conversion'],
    'Repeated emotional additions to a loser are not justified by sunk cost. The Owner preference to consider at most one planned, disciplined loss addition with fresh evidence remains an untested candidate, not an active risk rule.',
    'Ask: If I had no position and fresh cash today, would I buy this exact exposure? Lower price alone is not a reason to add. Any addition needs a prospective condition/price, quantity, maximum number of additions, total position ceiling, maximum loss and thesis-validity check. Reassess time, strike, expiry, current premium, combined exposure and costs under the authoritative allocation policy.',
    'Lower average cost is not risk management by itself; second or third rescue additions have no sunk-cost justification. An 80% option loss or later 35% rebound from the depressed premium is not a threshold or recovery proof; theta, IV and expiry can defeat a correct direction. Rolling closes or realizes the old position and opens new exposure without erasing the loss. A debit spread changes the payoff structure and requires separate assessment. No automatic averaging, roll or spread conversion.','planner'),
  item('windfall','Profit and curves','Windfall and rapid profit','CANDIDATE_UNTESTED',['owner'],['Lottery profit curve','90% exit / 10% runner','Images 1'],
    'Rapid gains are a reason to revisit a previously written exit plan.',
    'Check the executable quote and exact number of whole contracts that a partial exit would require.',
    '90/10 is an untested split, not an optimum. One contract cannot be split; do not increase size to manufacture a runner. Delta does not identify the peak.','journal'),
  item('loss-curves','Profit and curves','Loss paths do not prove the next move','ILLUSTRATION_ONLY',['owner'],['Catastrophic loss curve','Turbulent loss curve','Images 2, 11'],
    'These drawings illustrate possible adverse outcomes without numerical market evidence.',
    'Evaluate the original invalidation, current tradability and remaining exposure.',
    'A drawing cannot establish that recovery is unlikely or that holding will recover the loss. Do not wait for near-total loss before checking the original exit.','reviews'),
  item('recovery-curves','Profit and curves','A recovery and a trap can look alike early','ILLUSTRATION_ONLY',['owner'],['Standard curve','Bull trap','Technical confirmation','Turbulent gain','Images 3, 5, 6, 10, 12'],
    'The same early PnL path can precede different outcomes. Confirmations need independently specified ETF evidence.',
    'Record what was visible at the time, rather than labeling the path with its eventual ending.',
    'Profit crossing zero is not technical confirmation. No curve classifier, buy/sell trigger or future rebound prediction is implemented.','reviews'),
  item('giveback','Profit and curves','Compare exit alternatives prospectively','CANDIDATE_UNTESTED',['owner'],['Standard curve variant','30–50% profit','80–100% profit','Images 4'],
    'The proposed profit thresholds can be recorded as research alternatives to a frozen exit plan.',
    'A future comparison would need separately registered rules, independent quotes, costs and complete adverse outcomes.',
    'These percentages are not validated optima. A trade giving back profit is not automatically a process failure if its original plan was followed.','reviews'),
  item('catalyst-runner','Profit and curves','Partial exits require exact quantities','CANDIDATE_UNTESTED',['owner'],['Narrative / catalyst confirmation','+100% sell 50%','+200% sell 25%','25% runner','Images 7, 8'],
    'The proposed ladder must specify original versus remaining quantities and a gross or net profit basis.',
    'At an exact doubling, selling half recovers gross entry premium only when whole-contract quantities and fills permit it; fees still matter.',
    '50/25/25 usually requires at least four original contracts. Do not round or buy more to fit. Remaining contracts have market value and can lose it; they are not free risk.','planner'),
  item('expiry-curve','Profit and curves','Near expiry changes the problem','ILLUSTRATION_ONLY',['owner','theta'],['Near-term general profit curve','Images 9'],
    'As expiration approaches, reassess time sensitivity, tradability and exercise obligations.',
    'Keep an explicit time exit and consider how much time value remains on each leg.',
    'A drawn plateau cannot identify an optimal sale time. Expiration pressure varies with moneyness and structure; an in-the-money contract need not decay to zero.','journal'),
  item('emotion-curve','Profit and curves','Record feelings without inferring them','ILLUSTRATION_ONLY',['owner'],['Excitement','Panic','Images 13'],
    'The image is a prompt to record self-reported reactions and the action taken.',
    'Use a voluntary note alongside the original plan and observed execution evidence.',
    'The drawing does not diagnose the owner. A manual sale after a loss is not proof of panic, nor evidence of a brokerage liquidation.','reviews'),
  item('quality','Decision process','Process adherence and PnL are separate','PROCESS_GUIDE',['owner','review'],['Confidence formula','Outcome bias','Good process / loss','Poor process / profit'],
    'Review process against the original plan and then separately record the financial outcome.',
    'Keep both assessments unknown when supporting evidence is absent; inspect assumptions even when execution followed the plan.',
    'Successes divided by failures is an illustrative confidence metaphor, not a calibrated statistic. Adherence to an unprofitable strategy does not validate it. Do not automatically label outcomes deserved or lucky.','reviews'),
];

export const macroWorksheetFields = [
  {id:'horizons',label:'Horizon and holding period',prompt:'Separate macro horizon, ETF signal timeframe, intended holding period and option expiry.'},
  {id:'sources',label:'Sources and clocks',prompt:'Source IDs/links, observation time, receipt time, revisions and known data gaps.'},
  {id:'expectations',label:'Expectations and surprise',prompt:'What is documented consensus, what is your view, and what is still unknown?'},
  {id:'transmission',label:'Causal chain and alternatives',prompt:'How does the event reach GLD or IBIT? What else could explain the move?'},
  {id:'confirmation',label:'ETF entry evidence',prompt:'Specify the traded ETF trigger and available bars; do not substitute an option curve or spot/futures price.'},
  {id:'contract',label:'Contract and volatility fit',prompt:'Identity, expiry, strike, every leg, IV/Greeks clocks, liquidity and why this structure fits the horizon.'},
  {id:'exposure',label:'Combined exposure and hedge',prompt:'Total cost and worst-case assumptions across positions; which shared factor could cause losses together, and which risk does a proposed hedge offset?'},
  {id:'invalidation',label:'Thesis and price exits',prompt:'Before entry: where/how to exit if wrong, what observable evidence invalidates the thesis and which independent price/exposure trigger applies; state precedence.'},
  {id:'deadline',label:'Catalyst and time exit',prompt:'Before entry: catalyst date/time/zone, review deadline and option exit deadline; avoid indefinite extensions.'},
  {id:'monitoring',label:'Overnight and monitoring contingency',prompt:'What happens during gaps, unavailable quotes or time away? Who can act and when?'},
  {id:'costs',label:'Costs and whole-contract exits',prompt:'Before entry: planned profit-taking/target where supported, fees known/unknown, bid/ask, slippage, integer quantities and gross versus net target basis.'},
  {id:'counterevidence',label:'Counterevidence and no-trade condition',prompt:'What would change your mind? What missing evidence is enough to wait rather than enter?'},
];
export function macroCatalog() {
  return structuredClone({version:MACRO_PLAYBOOK_VERSION,contentRevision:psychologyRevision,reviewedDateNewYork:'2026-09-26',sources:[...macroSources,...psychologySources],items:[...macroKnowledge,...psychologyKnowledge],fields:macroWorksheetFields,psychology:psychologyReview,
    strategyStatus:'UNVALIDATED',activeRuleCount:0,executionAllowed:false,
    boundary:'Educational references and owner-authored notes. No new trading rule, source collection or study enrollment.'});
}
