import type {KnowledgeItem} from './MacroKnowledgeCatalog';

// Reviewed paraphrases of supplied experience. These are never execution inputs.
export const psychologyRevision = 'OWNER_PSYCHOLOGY_20260917_V1';
export const psychologySources = [
  {id:'owner-psychology',title:'Owner-supplied psychology batch and two reference images',url:null,coverage:'Prose, cognitive-bias chart and Thirty-Six Stratagems image reviewed as supplied experience. Author performance, statistics, historical allegations and clinical claims are unverified.'},
  {id:'behavior-summary',title:'SEC-hosted Library of Congress behavioral research summary',url:'https://www.sec.gov/investor/tools/behaviorialpatterns.htm',coverage:'Summary reviewed: active trading, disposition effect, familiarity and costs. It is not validation of every bias in the supplied chart or of this Owner; the findings are those of the report author.'},
  {id:'ownership-book',title:'Macmillan — Extreme Ownership',url:'https://us.macmillan.com/books/9781250183866/extremeownership/',coverage:'Publisher page confirms Jocko Willink and Leif Babin and the leadership subject. Full book not reviewed; the supplied trading analogy is not a tested strategy.'},
  {id:'darwin-book',title:'Columbia University Press — What I Learned About Investing from Darwin',url:'https://cup.columbia.edu/book/what-i-learned-about-investing-from-darwin/9780231203487/',coverage:'Publisher search description confirms Pulak Prasad and patient long-term investing. Full book not reviewed; detailed chapter interpretations remain Owner-supplied.'},
  {id:'social-reference',title:'Supplied Truth Social profile reference',url:'https://truthsocial.com/@realDonaldTrump',coverage:'Public page opened, but no readable post body was returned. No individual post, policy claim or price effect verified; no account created or followed and no collector added.'},
  {id:'covered-call',title:'OIC — covered call',url:'https://www.optionseducation.org/strategies/all-strategies/covered-call-buy-write',coverage:'Downside exposure checked: premium income does not remove substantial stock-loss risk.'},
];
const entry=(id:string,title:string,status:KnowledgeItem['status'],topics:string[],principle:string,application:string,limits:string,destination='reviews',sources=['owner-psychology']):KnowledgeItem=>
  ({id,group:'Psychology and evidence',title,status,topics,principle,application,limits,destination,sources});

export const psychologyKnowledge:KnowledgeItem[] = [
  entry('psych-entry-comfort','Entry comfort is not entry evidence','PROCESS_GUIDE',['$11 / $13 / $12 example','Breakeven fixation','Entry discomfort'],
    'Separate the discomfort of an early loss from evidence that an entry has become invalid.',
    'Before entry, record a prospective ETF confirmation and what would contradict it. During review, compare actions with that plan rather than the purchase price alone.',
    'The later rise in the example is hindsight. Buying a pullback at $12 is not inherently safer than $11; a higher price or immediate profit does not prove confirmation.','journal'),
  entry('psych-revenge','Do not ask the next trade to repay the last','PROCESS_GUIDE',['Revenge trading','FOMO','Recovery pressure','Missed opportunity'],
    'Treat each proposed entry as a fresh decision with its own evidence, costs and exposure.',
    'Ask whether the same idea would be considered without the recent loss, missed rally or someone else\'s reported profit. Record waiting as an available choice.',
    'A loss is still a financial loss when described as a strategic retreat. Prior profit is not free risk capital. No automatic cooldown or emotion-triggered trade ban is introduced.','planner'),
  entry('psych-confidence','Confidence needs calibration, not a sizing multiplier','PROCESS_GUIDE',['Confidence formula','High conviction','Guru confidence','Hot streak','Tenfold opportunity'],
    'Keep personal conviction, process adherence and independently measured results separate.',
    'Record evidence and alternatives before relying on a trader, AI or a winning streak. Evaluate costs and uncertainty over prospective observations.',
    'Successes/failures is not a calibrated probability; zero failures does not imply infinite skill. Fewer trades need not improve the ratio or expectancy. Confidence and future extreme winners do not authorize larger allocations.','reviews'),
  entry('psych-direction','Closing one direction does not establish the opposite','PROCESS_GUIDE',['Direction switch','No longer bearish','Neutral','Options sideways decay'],
    'An exit and an opposite entry answer different questions.',
    'State independent evidence for a new direction, contract fit and exits. Include remaining positions if both directions would coexist.',
    'A price that stops falling has not necessarily begun an uptrend. Neutral is valid; opposing option premiums can both lose value.','guidance'),
  entry('psych-tactical','Observe again without rewriting the original plan','PROCESS_GUIDE',['Tactical awareness','Regime change','Uncertainty','Chart limitations'],
    'Compare current evidence with the original expectations, source clocks and predefined exits.',
    'Separate observations, interpretations, actions and remaining unknowns. A proposed strategy revision needs a new prospective version and must preserve earlier decisions.',
    'Adaptability is not permission to discard a losing trade\'s limits. Incomplete information does not waive required data gates. Current sparse captures do not provide continuous tactical monitoring.','guidance'),
  entry('psych-news','Cross-check claims, not political averages','PROCESS_GUIDE',['Multilingual news','Political bias','Narrative','Manipulation allegations','Independent sources'],
    'Check the original claim, time and context; distinguish reporting, commentary, official statements and observed market reactions.',
    'Seek independent corroboration and counterevidence. Multiple translations of one wire story count as one origin; write the transmission to GLD or IBIT separately.',
    'Truth is not necessarily midway between opposing views. No permanent left/right reliability scores, unsupported insider allegations or claim that news never affects prices is adopted. Intent requires evidence.','context'),
  entry('psych-social','A political post is a source claim, not a trade signal','PROCESS_GUIDE',['Trump','Truth Social','Policy event','Publication and receipt clocks'],
    'A verified original post can establish what its author said; implementation and market consequences are separate propositions.',
    'Record the exact post, publication and receipt times, revisions, official policy confirmation and independent ETF evidence before using it in a thesis.',
    'No post content was verified in this review. One person does not determine every asset price. The excerpt\'s instruction to create an account is not an Owner instruction to register, follow or monitor.','context',['owner-psychology','social-reference']),
  entry('psych-72-hours','72 hours is a research proposal','CANDIDATE_UNTESTED',['72-hour rule','Earnings','Rescue news','Waiting period'],
    'The supplied fixed delay after news is an author heuristic without a tested definition here.',
    'A future proposal would need event receipt time, calendar versus trading hours, eligible instruments, exceptions and independent comparison outcomes.',
    'A blanket wait can outlast a short-dated option. It cannot delay an existing risk or expiry exit. No 72-hour timer or entry gate is installed.','event-research'),
  entry('psych-30-30','Two 30/30 versions remain unresolved','CANDIDATE_UNTESTED',['30/30 conflict','30% elapsed life','30% value loss','Rolling'],
    'Batch one starts a clock when the thesis weakens, using 30% of then-remaining life. Batch two says 30% of option time consumed and separately conditions the loss rule on a broken thesis.',
    'Keep both statements. Before any separate test, define the time origin, denominator, thesis state, loss basis, exit priority and whether a roll is permitted.',
    'These versions are not equivalent and have not been merged. Rolling closes an old position and opens new exposure with costs; it does not erase the old result. Neither variant overrides frozen exits.','reviews'),
  entry('psych-breakout-clock','A retest requires a defined observation','CANDIDATE_UNTESTED',['Support / resistance flip','True / false breakout','Last 30 seconds','Open / close hour'],
    'A support/resistance retest can be formulated as a hypothesis with a timeframe and failure condition.',
    'Specify qualified ETF bars, close rules, volume/liquidity checks and when the evidence becomes available before comparing outcomes.',
    'The last 30 seconds or opening/closing hour is not universally decisive. A transient rebound does not establish a durable reversal. No new pattern detector or capture cadence.','guidance'),
  entry('psych-returns','Reject universal return and win-rate promises','PROCESS_GUIDE',['2% every week','60% losses','Guaranteed gains','Survivorship'],
    'Treat universal performance claims as unsupported until their population, sample, costs and method are known.',
    'For scale only: 1.02^52 - 1 is about 180% compounded annual gain if every week earns exactly 2%, before costs. This arithmetic is not a forecast or target.',
    'Everyone can earn 2% weekly, most traders lose 60%+, and everyone eventually catches a huge winner are not established by these anecdotes. A sustainable process can still have losing weeks.','reviews'),
  entry('psych-options-choice','Options are a tool, not compulsory insurance','MECHANICS_REFERENCE',['Earnings 50% claim','Principal protection','Covered calls','Insurance analogy'],
    'Protection depends on the exact structure, strike, expiration, quantity and premium paid.',
    'Review the full payoff, fees and exercise/assignment exposure. Distinguish a hedge from income generation and compare with taking less exposure.',
    'An earnings outcome is not automatically a 50/50 crash bet. Options and covered-call income do not guarantee principal; an option can expire worthless. No new strategy, ticker or broker is enabled.','planner',['owner-psychology','spread','theta','covered-call']),
  entry('psych-responsibility','Own controllable decisions; investigate actual causes','PROCESS_GUIDE',['Extreme Ownership','Self-attribution','Account management','Journal'],
    'Record what you decided, what was observable, what you controlled and what remains unexplained.',
    'Review a specific deviation and a proposed prevention step against the original plan; preserve source outages, execution records and contrary evidence.',
    'Responsibility does not mean every loss is your fault or all external failures are excuses. A leadership book is not evidence of market edge. One review cannot approve a permanent lesson.','reviews',['owner-psychology','ownership-book']),
  entry('psych-wellbeing','Reflect on pressure without judging the person','PROCESS_GUIDE',['Sleep','Fatigue','Spending','Bills','Emotional position size','Weekend learning'],
    'Voluntarily describe whether pressure, tiredness or attention limits are affecting the intended decision.',
    'Consider reviewing exposure, waiting on a new entry or obtaining help with an existing monitoring obligation. Keep the financial plan separate from self-worth.',
    'Distress has many possible causes and does not prove a position is too large. Health, diagnosis, culture, consumption or wealth do not determine discipline or earning ability. No health data is required and no capital settings change.','planner'),
  entry('psych-ticker','Reassess a familiar ticker from current evidence','PROCESS_GUIDE',['Ticker magnetism','Attachment','Endowment','Past winner'],
    'Ask whether a fresh decision would be supported without the memory of an earlier win or the wish to recover a loss.',
    'Compare current evidence and alternatives; retain unknowns rather than repeatedly retelling the same narrative.',
    'Attachment is a reflection prompt, not a clinical diagnosis. A prior winner is neither automatically good nor banned; stories do not necessarily occur only once. The GLD/IBIT scope remains unchanged.','reviews',['owner-psychology','behavior-summary']),
  entry('psych-second-order','Trace second-order effects and offsetting channels','PROCESS_GUIDE',['Oil / airlines / JETS','Rates / small caps / IWM','War / insurance','Market ecosystem'],
    'Map an event through prices, costs, demand and balance sheets; identify who might benefit and which opposing channel could dominate.',
    'Airlines may face weaker demand despite cheaper fuel; small firms differ in financing; insurance claims can outweigh higher premiums. Apply the same branching questions to GLD/IBIT.',
    'These are conditional examples, not trades or fixed correlations. Greeks are model sensitivities rather than physical laws. No holdings in named companies or new ticker coverage are inferred.','context'),
  entry('psych-long-horizon','Long-term investing lessons need a horizon boundary','PROCESS_GUIDE',['Darwin','Pulak Prasad','Quality companies','DCF precision','History / economics / English'],
    'Use the supplied book summary to question catastrophic exposure, business quality and false precision in long forecasts.',
    'Separate learning from strategy selection. Record what evidence would transfer to the chosen instrument and what would not.',
    'Patient ownership of a business is not an instruction to hold an expiring option indefinitely. The full book and detailed chapter summary were not independently reviewed. No cultural explanation of trading ability is adopted.','reviews',['owner-psychology','darwin-book']),
  entry('psych-tools','Evaluate tools by a documented need','PROCESS_GUIDE',['IBKR','DAS Trader','TradingView','OptionStrat','Barchart','Referral links'],
    'Define the missing capability, evidence of benefit, total cost and available alternatives before considering a tool.',
    'Keep execution quality, routing, quote availability and workflow cost as separate questions. Author preferences are not verified product comparisons.',
    'Current prices, broker quality, free features and gamma estimates were not checked. Supplied referral URLs are not recommendations. No installation, subscription, login or migration is performed.','context'),
  entry('psych-metaphors','Extract questions from metaphors, not trading commands','ILLUSTRATION_ONLY',['Thirty-Six Stratagems','Guerrilla maxims','Battlefield','Parking fine','Opportunity cost'],
    'Preserving resources, observing and considering opportunity cost can inspire neutral decision questions.',
    'Translate the metaphor into evidence, permitted actions, cost and alternative scenarios before it enters a worksheet.',
    'Military sayings are not market laws or buy/add signals. A fine is not permission or a complete cost estimate. Market manipulation allegations and claims that all wealth is plunder remain unsupported.','reviews'),
  entry('psych-sample-review','Evaluate the framework beyond one result','PROCESS_GUIDE',['Sample size','Expectancy','Independent outcomes','Hindsight','Outcome bias'],
    'Compare the original decision process and independent financial result across prospective observations.',
    'Retain missing sessions, rejected ideas, fees, drawdowns, dependence and regime differences. Inspect profitable deviations as well as compliant losses.',
    'Dozens or hundreds of trades is not an automatic pass; correlated bets are not independent replications. The frozen 20-session study is not a profit qualification or permission to manufacture trades.','reviews',['owner-psychology','behavior-summary']),
];

export const psychologyBiases = [
  ['confirmation','Confirmation','Judgment','What contrary observation did I actively seek, and what did it show?'],
  ['anchoring','Anchoring','Judgment','Would this decision change if I did not know my purchase price?'],
  ['narrative','Narrative','Judgment','Which part of this story is observed, and which causal link is still a hypothesis?'],
  ['loss-aversion','Loss aversion','Losses','Am I changing an exit because of new evidence or because realizing a loss feels difficult?'],
  ['sunk-cost','Sunk cost','Losses','Ignoring past money and effort, is the remaining exposure justified now?'],
  ['disposition','Disposition effect','Losses','Are my winner and loser exits consistent with their original plans rather than relief or regret?'],
  ['endowment','Endowment','Losses','Would I choose this exposure if I did not already own it?'],
  ['overconfidence','Overconfidence','Success','What is uncertain despite recent wins, and what could invalidate my estimate?'],
  ['self-attribution','Self-attribution','Success','Did I use the same evidence standard when explaining gains and losses?'],
  ['hot-hand','Hot-hand belief','Success','Does the next trade have evidence beyond the fact that the last trades won?'],
  ['herding','Herding','Groups','What is my independent reason beyond what the crowd or a favored trader is doing?'],
  ['fomo','FOMO','Groups','Would this still qualify without a deadline to catch up with someone else?'],
  ['availability','Availability','Groups','Is repeated coverage one source being repeated, or independent evidence?'],
  ['recency','Recency','Time and probability','How does the recent event compare with the relevant longer sample and current regime?'],
  ['hindsight','Hindsight','Time and probability','What does the original dated note say I knew before the result?'],
  ['gamblers-fallacy','Gambler\'s fallacy','Time and probability','What supports a reversal beyond a run of losses? Market returns need not be independent coin flips.'],
  ['outcome','Outcome bias','Process and result','Would I assess the same decision process differently if the financial outcome were reversed?'],
].map(([id,title,group,prompt])=>({id,title,group,prompt,source:'owner-psychology',status:'REFLECTION_ONLY_NOT_DIAGNOSIS'}));

export const psychologyPrompts = [
  {id:'entry-urge',stage:'Before entry',title:'Recovery or opportunity?',text:'Am I trying to recover a loss or catch a missed move? What fresh evidence would support this entry if the previous trade had not happened?'},
  {id:'entry-independent',stage:'Before entry',title:'Whose conviction?',text:'If I held no position and had not seen another trader\'s call, would I choose this exposure? What independent evidence and contrary evidence support my decision?'},
  {id:'entry-risk',stage:'Before entry',title:'Dollars before upside',text:'What can the combined position lose under the stated assumptions, including costs and expiry? What is unknown, and can the monitoring plan actually support it?'},
  {id:'holding-anchor',stage:'While holding',title:'Price anchor or changed evidence?',text:'Am I waiting only to get back to my entry price? Which original exit conditions are met, and what evidence has actually changed?'},
  {id:'holding-change',stage:'While holding',title:'Adding, rolling or flipping?',text:'What new evidence justifies this change, what old result will be realized, and what total exposure and costs follow? Closing one direction does not confirm the opposite.'},
  {id:'holding-pressure',stage:'While holding',title:'Attention and deadline',text:'Is pressure or fatigue affecting this decision? What is the original time exit, and what happens if I cannot monitor? No personal health details are needed.'},
  {id:'review-process',stage:'After a decision',title:'Process apart from PnL',text:'Against the original dated plan, what did I follow or deviate from? Record the financial result separately; a profit does not prove good process and a loss does not prove poor process.'},
  {id:'review-cause',stage:'After a decision',title:'Evidence before blame',text:'Which decisions were controllable, which external problems are documented, and what remains unknown? What specific improvement could be tested prospectively?'},
  {id:'review-no-trade',stage:'After a decision',title:'Review waiting too',text:'What evidence supported waiting or rejecting this idea at the time? Do not rewrite that decision because the asset later rose or fell.'},
];

export const psychologyReview = {
  revision:psychologyRevision,
  boundary:'Voluntary reflection only. No score, diagnosis, inferred emotion, position change or automatic save. Question selection is not an admission of a bias.',
  biases:psychologyBiases,prompts:psychologyPrompts,
  adoption:[
    {status:'USE_AS_REFLECTION',title:'Use as questions',text:'Counterevidence, independent judgment, original-plan comparison, recovery pressure, ticker attachment, costs, monitoring and separate process/outcome review.'},
    {status:'CANDIDATE_UNTESTED',title:'Keep as inactive proposals',text:'72 hours, both conflicting 30/30 versions, one loser addition, adding winners, breakout/retest timing and final-30-second claims. None is an active rule.'},
    {status:'NOT_ADOPTED_AS_FACT',title:'Do not adopt as facts or targets',text:'Universal weekly returns, unsupported win rates, guaranteed options protection, personality or cultural judgments, and unverified manipulation accusations.'},
  ],
};
