import { appendFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  AIAuditActorType, AIAuditRetentionClassification, PrivacyLevel,
  StrategyAppendStatus, StrategyApprovalDecision, StrategyApproverType,
  StrategyAuditOperationType, StrategyAuthorType, StrategyCategory,
  StrategyChangeType, StrategyComparisonClassification, StrategyExportDestination,
  StrategyExportFormat, StrategyExportStatus, StrategyMetricAvailability,
  StrategyMetricGroup, StrategyReferenceResolution, StrategyReferenceType,
  StrategySemanticImpact, StrategyStatus, StrategyValidationOutcome,
  createStrategyDefinitionId, createStrategyVersionId, type StrategyActivation,
  type StrategyApproval, type StrategyDefinitionSnapshot, type StrategyEvidenceGraph, type StrategyEvidenceReference,
  type StrategyPerformanceSummary, type StrategyRetirement, type StrategySuspension,
  type StrategyValidationResult, type StrategyVersion, type StrategyVersionSnapshot,
} from "../../contracts";
import { InMemoryStrategyRepository, LocalNdjsonStrategyRepository } from "../../repositories";
import { StrategyVersioning, auditRecordFromStrategy, exportStrategies, type StrategyClock } from ".";

interface TestCase { readonly name: string; readonly run: () => void; }
function assertEqual<T>(actual: T, expected: T, message: string): void { if (!Object.is(actual, expected)) throw new Error(`${message}: expected ${String(expected)}, received ${String(actual)}.`); }
function assertTrue(value: boolean, message: string): void { if (!value) throw new Error(message); }
function assertDeepEqual(actual: unknown, expected: unknown, message: string): void { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(message); }
function expectError(action: () => void, expected: string): void { try { action(); } catch (error: unknown) { const message = error instanceof Error ? error.message : String(error); assertTrue(message.includes(expected), `Expected "${expected}", received "${message}".`); return; } throw new Error(`Expected error containing "${expected}".`); }
class FixedClock implements StrategyClock { now(): string { return "2026-07-18T22:00:00.000Z"; } }

const auditReference = (id: string) => ({ referenceId: id, recordType: StrategyReferenceType.Audit, resolution: StrategyReferenceResolution.Resolved, version: "v1", frozenStatus: "APPENDED" }) as const;
const evidence = <T extends StrategyReferenceType>(id: string, type: T): StrategyEvidenceReference & { readonly recordType: T } => ({ referenceId: id, recordType: type, resolution: StrategyReferenceResolution.Resolved, version: "v1", frozenStatus: "FINALIZED" });
function references(): StrategyEvidenceGraph {
  return {
    research: [evidence("research-1", StrategyReferenceType.Research)], predictions: [evidence("prediction-1", StrategyReferenceType.Prediction)], journals: [evidence("journal-1", StrategyReferenceType.Journal)],
    decisions: [], risks: [], trades: [], audits: [auditReference("audit-evidence-1")],
    backtests: [{ referenceId: "backtest-future-1", recordType: StrategyReferenceType.Backtest, resolution: StrategyReferenceResolution.Unresolved }], validations: [], eventReplay: [],
  };
}
function definitionSnapshot(overrides: Partial<StrategyDefinitionSnapshot> = {}): StrategyDefinitionSnapshot {
  return { schemaVersion: "1.0", createdAt: "2026-07-18T10:00:00.000Z", title: "Synthetic allocation discipline", category: StrategyCategory.CapitalAllocation, ownerReference: "owner-1", objective: { statement: "Allocate synthetic capital consistently.", successMeasure: "Process adherence improves without breaching risk boundaries." }, scope: { included: ["Synthetic decisions"], excluded: ["Execution"], markets: ["US"], assetTypes: ["EQUITY"], capitalStages: ["ALLOCATION"] }, privacyLevel: PrivacyLevel.Internal, retention: AIAuditRetentionClassification.Permanent, tags: ["synthetic", "strategy"], correlationId: "correlation-1", traceId: "trace-1", policyVersions: { strategy: "strategy-v1", risk: "risk-v1" }, metadata: { source: "synthetic", verified: true }, ...overrides };
}
function versionSnapshot(definitionId: string, overrides: Partial<StrategyVersionSnapshot> = {}): StrategyVersionSnapshot {
  return { schemaVersion: "1.0", definitionId, semanticVersion: "1.0.0", createdAt: "2026-07-18T11:00:00.000Z", effectiveAt: "2026-07-18T12:00:00.000Z", title: "Synthetic allocation v1", category: StrategyCategory.CapitalAllocation, objective: { statement: "Allocate synthetic capital consistently.", successMeasure: "Process adherence improves without breaching risk boundaries." }, scope: { included: ["Synthetic decisions"], excluded: ["Execution"], markets: ["US"], assetTypes: ["EQUITY"], capitalStages: ["ALLOCATION"] }, rules: [{ ruleId: "rule-1", name: "Synthetic threshold", condition: "score >= 80", action: "mark eligible", priority: 1, enabled: true }], parameters: [{ parameterId: "parameter-1", name: "Minimum score", value: 80, valueType: "NUMBER", unit: "points", description: "Synthetic eligibility threshold." }], constraints: [{ constraintId: "constraint-1", statement: "Never bypass risk policy.", hardConstraint: true, policyReference: "risk-v1" }], assumptions: [{ assumptionId: "assumption-1", statement: "Synthetic inputs are stable.", confidence: 80, invalidationCondition: "Input integrity fails." }], risks: [{ riskId: "risk-1", statement: "Synthetic overfitting.", boundary: "No capital authorization.", mitigation: "Require owner review." }], invalidationConditions: [{ conditionId: "condition-1", statement: "Risk policy mismatch.", requiredAction: "Suspend strategy." }], expectedBehavior: "Produce a deterministic eligibility marker only.", minimumDataRequirements: ["Validated synthetic score"], references: references(), riskPolicyReference: "risk-v1", authorType: StrategyAuthorType.Owner, privacyLevel: PrivacyLevel.Internal, retention: AIAuditRetentionClassification.Permanent, tags: ["synthetic", "strategy"], correlationId: "correlation-1", traceId: "trace-1", policyVersions: { strategy: "strategy-v1", risk: "risk-v1" }, metadata: { source: "synthetic", verified: true }, ...overrides };
}
function change(impact: StrategySemanticImpact, type: StrategyChangeType = StrategyChangeType.RuleModified) { return { changeId: `change-${impact.toLowerCase()}`, fieldReference: "rules.rule-1.condition", previousValue: "score >= 80", newValue: "score >= 85", changeType: type, semanticImpact: impact, reason: "Synthetic controlled change.", evidenceReferences: impact === StrategySemanticImpact.Patch ? [] : [evidence("research-change-1", StrategyReferenceType.Research)], expectedEffect: "Narrow eligibility.", riskIntroduced: "May reduce sample size.", reversible: true, ownerNote: "Owner review required." }; }
function nextSnapshot(prior: StrategyVersion, semanticVersion: string, impact: StrategySemanticImpact, type: StrategyChangeType = StrategyChangeType.RuleModified, overrides: Partial<StrategyVersionSnapshot> = {}): StrategyVersionSnapshot {
  const selectedChange = change(impact, type); return { ...versionSnapshot(prior.definitionId), semanticVersion, createdAt: "2026-07-18T11:30:00.000Z", title: `Synthetic allocation ${semanticVersion}`, priorVersionId: prior.versionId, changeReason: "Controlled synthetic revision.", changeSet: { changeSetId: `changes-${semanticVersion}`, classification: impact, changes: [selectedChange] }, rules: [{ ...prior.rules[0]!, condition: selectedChange.newValue }], parameters: prior.parameters, ...overrides };
}
function validation(versionId: string, overrides: Partial<StrategyValidationResult> = {}): StrategyValidationResult { return { validationId: `${versionId}:validation:1`, versionId, testType: "SYNTHETIC_REPLAY", testedAt: "2026-07-18T14:00:00.000Z", datasetReference: evidence("dataset-1", StrategyReferenceType.Validation), sampleSize: 20, period: "synthetic-window-1", assumptions: ["Fixture is deterministic."], metrics: [{ metricId: "validation-process-1", group: StrategyMetricGroup.Process, name: "rule adherence", availability: StrategyMetricAvailability.Available, value: 100, unit: "percent", sampleSize: 20, sourceReferences: [] }], outcome: StrategyValidationOutcome.Passed, limitations: ["Synthetic data only."], reviewer: "owner-1", auditReference: auditReference("audit-validation-1"), ...overrides }; }
function approval(versionId: string, overrides: Partial<StrategyApproval> = {}): StrategyApproval { return { approvalId: `${versionId}:approval:1`, versionId, ownerReference: "owner-1", approverType: StrategyApproverType.Owner, decision: StrategyApprovalDecision.Approved, decidedAt: "2026-07-18T15:00:00.000Z", conditions: ["Keep risk controls active."], reason: "Owner approved synthetic strategy.", auditReference: auditReference("audit-approval-1"), ...overrides }; }
function activation(versionId: string, approvalId: string, overrides: Partial<StrategyActivation> = {}): StrategyActivation { return { activationId: `${versionId}:activation:1`, versionId, activatedAt: "2026-07-18T16:00:00.000Z", ownerApprovalId: approvalId, ownerReference: "owner-1", actorType: StrategyApproverType.Owner, reason: "Owner-directed activation.", auditReference: auditReference("audit-activation-1"), ...overrides }; }
function suspension(versionId: string, overrides: Partial<StrategySuspension> = {}): StrategySuspension { return { suspensionId: `${versionId}:suspension:1`, versionId, suspendedAt: "2026-07-18T17:00:00.000Z", reason: "Synthetic boundary review.", existingPlansMayContinue: true, newPlansProhibited: true, evidenceReferences: [evidence("research-suspend-1", StrategyReferenceType.Research)], auditReference: auditReference("audit-suspension-1"), ...overrides }; }
function retirement(versionId: string, overrides: Partial<StrategyRetirement> = {}): StrategyRetirement { return { retirementId: `${versionId}:retirement:1`, versionId, retiredAt: "2026-07-18T18:00:00.000Z", reason: "Synthetic strategy retired.", auditReference: auditReference("audit-retirement-1"), ...overrides }; }
function performance(versionId: string, overrides: Partial<StrategyPerformanceSummary> = {}): StrategyPerformanceSummary { const metric = (id: string, group: StrategyMetricGroup) => ({ metricId: id, group, name: `${group.toLowerCase()} metric`, availability: StrategyMetricAvailability.Available, value: 75, unit: "percent", sampleSize: 8, sourceReferences: [] }); return { performanceId: `${versionId}:performance:1`, versionId, recordedAt: "2026-07-18T20:00:00.000Z", periodStart: "2026-07-01T00:00:00.000Z", periodEnd: "2026-07-18T19:00:00.000Z", completePeriod: false, sampleSize: 8, predictionMetrics: [metric("prediction-metric-1", StrategyMetricGroup.Prediction)], tradingMetrics: [metric("trading-metric-1", StrategyMetricGroup.Trading)], processMetrics: [metric("process-metric-1", StrategyMetricGroup.Process)], limitations: ["Small synthetic sample."], auditReference: auditReference("audit-performance-1"), ...overrides }; }
function setup(snapshot = definitionSnapshot()): { repository: InMemoryStrategyRepository; lab: StrategyVersioning; definitionId: string; version: StrategyVersion } { const repository = new InMemoryStrategyRepository(); const lab = new StrategyVersioning(repository, new FixedClock()); const definitionId = lab.createDefinition(snapshot).record.definitionId; return { repository, lab, definitionId, version: lab.proposeVersion(versionSnapshot(definitionId)).record }; }
function validateAndApprove(lab: StrategyVersioning, version: StrategyVersion): StrategyApproval { lab.beginValidation(version.versionId, "2026-07-18T13:00:00.000Z", "Begin deterministic validation."); lab.appendValidation(validation(version.versionId)); return lab.decide(approval(version.versionId)).record; }
function makeActive(): ReturnType<typeof setup> & { ownerApproval: StrategyApproval } { const value = setup(); const ownerApproval = validateAndApprove(value.lab, value.version); value.lab.activate(activation(value.version.versionId, ownerApproval.approvalId)); return { ...value, ownerApproval }; }

const tests: ReadonlyArray<TestCase> = [
  { name: "01 definition appends with deterministic ID", run: () => { const value = definitionSnapshot(); assertEqual(setup(value).definitionId, createStrategyDefinitionId(value), "definition ID"); } },
  { name: "02 initial version appends as PROPOSED", run: () => assertEqual(setup().version.status, StrategyStatus.Proposed, "status") },
  { name: "03 conflicting duplicate definition ID is rejected", run: () => { const { repository, lab } = setup(); const stored = lab.getDefinition(repository.listDefinitions()[0]!.definitionId)!; expectError(() => repository.appendDefinition({ ...stored, title: "Conflict" }, new FixedClock().now()), "IDEMPOTENCY_CONFLICT"); } },
  { name: "04 conflicting duplicate version ID is rejected", run: () => { const { repository, version } = setup(); expectError(() => repository.appendVersion({ ...version, title: "Conflict" }, new FixedClock().now()), "IDEMPOTENCY_CONFLICT"); } },
  { name: "05 duplicate semantic version is rejected", run: () => { const { lab, version } = setup(); expectError(() => lab.proposeVersion(nextSnapshot(version, "1.0.0", StrategySemanticImpact.Patch, StrategyChangeType.DocumentationOnly)), "INVALID_SEMANTIC_VERSION"); } },
  { name: "06 identical definition append is replayed", run: () => { const repo = new InMemoryStrategyRepository(); const lab = new StrategyVersioning(repo, new FixedClock()); const value = definitionSnapshot(); lab.createDefinition(value); assertEqual(lab.createDefinition(value).status, StrategyAppendStatus.Replayed, "replay"); } },
  { name: "07 identical version append is replayed", run: () => { const { repository, version } = setup(); assertEqual(repository.appendVersion(version, new FixedClock().now()).status, StrategyAppendStatus.Replayed, "replay"); } },
  { name: "08 stored definition is immutable", run: () => { const { lab, definitionId } = setup(); const value = lab.getDefinition(definitionId)!; (value as { title: string }).title = "Mutated"; assertTrue(lab.getDefinition(definitionId)?.title !== "Mutated", "definition mutated"); } },
  { name: "09 PATCH increment is enforced", run: () => { const { lab, version } = setup(); assertEqual(lab.proposeVersion(nextSnapshot(version, "1.0.1", StrategySemanticImpact.Patch, StrategyChangeType.DocumentationOnly, { rules: version.rules })).record.semanticVersion, "1.0.1", "patch"); } },
  { name: "10 MINOR increment is enforced", run: () => { const { lab, version } = setup(); assertEqual(lab.proposeVersion(nextSnapshot(version, "1.1.0", StrategySemanticImpact.Minor, StrategyChangeType.RuleAdded)).record.semanticVersion, "1.1.0", "minor"); } },
  { name: "11 MAJOR increment is enforced", run: () => { const { lab, version } = setup(); assertEqual(lab.proposeVersion(nextSnapshot(version, "2.0.0", StrategySemanticImpact.Major, StrategyChangeType.RiskBoundaryChanged)).record.semanticVersion, "2.0.0", "major"); } },
  { name: "12 incorrect semantic increment is rejected", run: () => { const { lab, version } = setup(); expectError(() => lab.proposeVersion(nextSnapshot(version, "1.1.0", StrategySemanticImpact.Patch, StrategyChangeType.DocumentationOnly)), "INVALID_SEMANTIC_VERSION"); } },
  { name: "13 missing prior version is rejected", run: () => { const { lab, definitionId } = setup(); expectError(() => lab.proposeVersion({ ...versionSnapshot(definitionId), semanticVersion: "1.0.1", priorVersionId: "missing", changeReason: "Missing lineage.", changeSet: { changeSetId: "missing", classification: StrategySemanticImpact.Patch, changes: [change(StrategySemanticImpact.Patch, StrategyChangeType.DocumentationOnly)] } }), "INVALID_LINEAGE"); } },
  { name: "14 wrong definition lineage is rejected", run: () => { const one = setup(); const otherId = one.lab.createDefinition(definitionSnapshot({ createdAt: "2026-07-18T10:01:00.000Z", title: "Other", correlationId: "correlation-2", traceId: "trace-2" })).record.definitionId; expectError(() => one.lab.proposeVersion(nextSnapshot(one.version, "1.1.0", StrategySemanticImpact.Minor, StrategyChangeType.RuleAdded, { definitionId: otherId })), "INVALID_LINEAGE"); } },
  { name: "15 lifecycle progresses deterministically", run: () => { const value = makeActive(); assertDeepEqual(value.lab.getVersion(value.version.versionId)?.history.map((item) => item.toStatus), [StrategyStatus.Proposed, StrategyStatus.Validating, StrategyStatus.Approved, StrategyStatus.Active], "lifecycle"); } },
  { name: "16 invalid reverse transition is rejected", run: () => { const value = makeActive(); expectError(() => value.lab.beginValidation(value.version.versionId, "2026-07-18T17:00:00.000Z", "Reverse."), "INVALID_LIFECYCLE"); } },
  { name: "17 approval before validation is rejected", run: () => { const { lab, version } = setup(); expectError(() => lab.decide(approval(version.versionId)), "INVALID_LIFECYCLE"); } },
  { name: "18 AI approval is rejected", run: () => { const { lab, version } = setup(); lab.beginValidation(version.versionId, "2026-07-18T13:00:00.000Z", "Validate."); lab.appendValidation(validation(version.versionId)); expectError(() => lab.decide(approval(version.versionId, { approverType: StrategyApproverType.Ai })), "INVALID_APPROVAL"); } },
  { name: "19 owner-approved version activates", run: () => { const value = makeActive(); assertEqual(value.lab.getVersion(value.version.versionId)?.status, StrategyStatus.Active, "active"); } },
  { name: "20 activation without owner approval is rejected", run: () => { const { lab, version } = setup(); lab.beginValidation(version.versionId, "2026-07-18T13:00:00.000Z", "Validate."); lab.appendValidation(validation(version.versionId)); expectError(() => lab.activate(activation(version.versionId, "missing")), "INVALID_LIFECYCLE"); } },
  { name: "21 concurrent active version is rejected", run: () => { const value = makeActive(); const next = value.lab.proposeVersion(nextSnapshot(value.version, "1.1.0", StrategySemanticImpact.Minor, StrategyChangeType.RuleAdded)).record; const nextApproval = validateAndApprove(value.lab, next); expectError(() => value.lab.activate(activation(next.versionId, nextApproval.approvalId, { activationId: `${next.versionId}:activation:2` })), "ACTIVE_VERSION_CONFLICT"); } },
  { name: "22 suspension prohibits new plan snapshots", run: () => { const value = makeActive(); value.lab.suspend(suspension(value.version.versionId)); expectError(() => value.lab.freezeForTradePlan(value.version.versionId, "2026-07-18T16:30:00.000Z"), "INACTIVE_STRATEGY"); } },
  { name: "23 retired version remains retrievable", run: () => { const value = makeActive(); value.lab.retire(retirement(value.version.versionId)); assertEqual(value.lab.getVersion(value.version.versionId)?.status, StrategyStatus.Retired, "retired"); } },
  { name: "24 active version freezes into trade-plan contract", run: () => { const value = makeActive(); const frozen = value.lab.freezeForTradePlan(value.version.versionId, "2026-07-18T16:30:00.000Z"); assertEqual(frozen.versionId, value.version.versionId, "version"); assertTrue(frozen.rulesetFingerprint.startsWith("fnv1a64:"), "fingerprint"); } },
  { name: "25 later version cannot mutate frozen plan snapshot", run: () => { const value = makeActive(); const frozen = value.lab.freezeForTradePlan(value.version.versionId, "2026-07-18T16:30:00.000Z"); value.lab.proposeVersion(nextSnapshot(value.version, "1.1.0", StrategySemanticImpact.Minor, StrategyChangeType.RuleAdded)); assertEqual(frozen.parameters[0]?.value, 80, "frozen parameter"); } },
  { name: "26 explicit change set preserves before and after", run: () => { const { lab, version } = setup(); const next = lab.proposeVersion(nextSnapshot(version, "1.1.0", StrategySemanticImpact.Minor)).record; assertEqual(next.changeSet?.changes[0]?.previousValue, "score >= 80", "before"); assertEqual(next.changeSet?.changes[0]?.newValue, "score >= 85", "after"); } },
  { name: "27 material change without evidence is rejected", run: () => { const { lab, version } = setup(); const selected = { ...change(StrategySemanticImpact.Minor), evidenceReferences: [] }; expectError(() => lab.proposeVersion(nextSnapshot(version, "1.1.0", StrategySemanticImpact.Minor, StrategyChangeType.RuleModified, { changeSet: { changeSetId: "no-evidence", classification: StrategySemanticImpact.Minor, changes: [selected] } })), "MATERIAL_EVIDENCE_REQUIRED"); } },
  { name: "28 research evidence is typed and frozen", run: () => assertEqual(setup().version.references.research[0]?.recordType, StrategyReferenceType.Research, "research") },
  { name: "29 prediction evidence is typed and frozen", run: () => assertEqual(setup().version.references.predictions[0]?.frozenStatus, "FINALIZED", "prediction") },
  { name: "30 journal evidence is typed and frozen", run: () => assertEqual(setup().version.references.journals[0]?.version, "v1", "journal") },
  { name: "31 validation records are append-only", run: () => { const { lab, version } = setup(); lab.beginValidation(version.versionId, "2026-07-18T13:00:00.000Z", "Validate."); const value = validation(version.versionId); assertEqual(lab.appendValidation(value).status, StrategyAppendStatus.Appended, "append"); assertEqual(lab.appendValidation(value).status, StrategyAppendStatus.Replayed, "replay"); } },
  { name: "32 approval records are append-only", run: () => { const { lab, version } = setup(); const value = validateAndApprove(lab, version); assertEqual(lab.getVersion(version.versionId)?.status, StrategyStatus.Approved, "approved"); assertEqual(value.decision, StrategyApprovalDecision.Approved, "decision"); } },
  { name: "33 comparison detects rule differences", run: () => { const { lab, version } = setup(); const next = lab.proposeVersion(nextSnapshot(version, "1.1.0", StrategySemanticImpact.Minor)).record; assertTrue(lab.compare(version.versionId, next.versionId).changed.some((item) => item.path.startsWith("rules")), "rule difference"); } },
  { name: "34 comparison detects parameter differences", run: () => { const { lab, version } = setup(); const parameters = [{ ...version.parameters[0]!, value: 85 }]; const next = lab.proposeVersion(nextSnapshot(version, "1.1.0", StrategySemanticImpact.Minor, StrategyChangeType.ParameterChanged, { parameters })).record; assertTrue(lab.compare(version.versionId, next.versionId).changed.some((item) => item.path.startsWith("parameters")), "parameter difference"); } },
  { name: "35 comparison detects risk differences", run: () => { const { lab, version } = setup(); const risks = [{ ...version.risks[0]!, boundary: "Stricter synthetic boundary." }]; const next = lab.proposeVersion(nextSnapshot(version, "2.0.0", StrategySemanticImpact.Major, StrategyChangeType.RiskBoundaryChanged, { risks })).record; assertEqual(lab.compare(version.versionId, next.versionId).riskClassification, StrategyComparisonClassification.Incompatible, "risk classification"); } },
  { name: "36 comparison output is deterministic", run: () => { const { lab, version } = setup(); const next = lab.proposeVersion(nextSnapshot(version, "1.1.0", StrategySemanticImpact.Minor)).record; assertDeepEqual(lab.compare(version.versionId, next.versionId), lab.compare(version.versionId, next.versionId), "comparison"); } },
  { name: "37 rollback creates a new version", run: () => { const { lab, version } = setup(); const failed = lab.proposeVersion(nextSnapshot(version, "2.0.0", StrategySemanticImpact.Major, StrategyChangeType.RiskBoundaryChanged)).record; const rollback = nextSnapshot(failed, "3.0.0", StrategySemanticImpact.Major, StrategyChangeType.RiskBoundaryChanged, { rules: version.rules, parameters: version.parameters, rollbackReference: { trustedVersionId: version.versionId, failedVersionId: failed.versionId, reason: "Restore trusted rules explicitly." } }); const restored = lab.proposeRollback(failed.versionId, version.versionId, rollback).record; assertTrue(restored.versionId !== version.versionId && restored.versionId !== failed.versionId, "rollback was not new"); } },
  { name: "38 performance keeps prediction trading and process separate", run: () => { const value = setup(); const stored = value.lab.appendPerformance(performance(value.version.versionId)).record; assertDeepEqual(stored.predictionMetrics.map((item) => item.group), [StrategyMetricGroup.Prediction], "prediction"); assertDeepEqual(stored.tradingMetrics.map((item) => item.group), [StrategyMetricGroup.Trading], "trading"); assertDeepEqual(stored.processMetrics.map((item) => item.group), [StrategyMetricGroup.Process], "process"); } },
  { name: "39 missing metric cannot invent a value", run: () => { const value = setup(); const bad = performance(value.version.versionId, { processMetrics: [{ metricId: "missing-1", group: StrategyMetricGroup.Process, name: "missing", availability: StrategyMetricAvailability.Missing, value: 1, sampleSize: 0, sourceReferences: [] }] }); expectError(() => value.lab.appendPerformance(bad), "INVALID_RECORD"); } },
  { name: "40 small sample is preserved as a limitation", run: () => { const value = setup(); const stored = value.lab.appendPerformance(performance(value.version.versionId, { sampleSize: 1, limitations: ["Sample size is one."] })).record; assertEqual(stored.sampleSize, 1, "sample"); assertEqual(stored.limitations[0], "Sample size is one.", "limitation"); } },
  { name: "41 query filters category", run: () => assertEqual(setup().lab.query({ filter: { categories: [StrategyCategory.CapitalAllocation] } }).length, 1, "category") },
  { name: "42 query filters status", run: () => assertEqual(setup().lab.query({ filter: { statuses: [StrategyStatus.Proposed] } }).length, 1, "status") },
  { name: "43 query filters active only", run: () => assertEqual(makeActive().lab.query({ filter: { activeOnly: true } }).length, 1, "active") },
  { name: "44 lineage is ordered by semantic version", run: () => { const { lab, version } = setup(); lab.proposeVersion(nextSnapshot(version, "1.1.0", StrategySemanticImpact.Minor)); assertDeepEqual(lab.lineage(version.definitionId).map((item) => item.semanticVersion), ["1.0.0", "1.1.0"], "lineage"); } },
  { name: "45 query filters research reference", run: () => assertEqual(setup().lab.query({ filter: { researchId: "research-1" } }).length, 1, "research") },
  { name: "46 query filters prediction reference", run: () => assertEqual(setup().lab.query({ filter: { predictionId: "prediction-1" } }).length, 1, "prediction") },
  { name: "47 query pagination is deterministic", run: () => { const { lab, version } = setup(); lab.proposeVersion(nextSnapshot(version, "1.1.0", StrategySemanticImpact.Minor)); assertEqual(lab.query({ offset: 1, limit: 1 })[0]?.semanticVersion, "1.1.0", "page"); } },
  { name: "48 statistics summarize definitions versions validation and performance", run: () => { const { lab, version } = setup(); lab.proposeVersion(nextSnapshot(version, "1.1.0", StrategySemanticImpact.Minor)); const stats = lab.statistics(); assertEqual(stats.versionCount, 2, "versions"); assertEqual(stats.definitionsByCategory[StrategyCategory.CapitalAllocation], 1, "definitions"); assertEqual(stats.byCategory[StrategyCategory.CapitalAllocation], 2, "version category"); assertEqual(stats.validationCompletionRate, 0, "validation rate"); assertEqual(stats.performanceReferenceCounts[version.versionId], 0, "performance references"); } },
  { name: "49 export ordering is deterministic", run: () => { const { repository } = setup(); const request = { exportId: "export-1", requestedAt: new FixedClock().now(), query: {}, format: StrategyExportFormat.Json, destination: StrategyExportDestination.LocalSnapshot } as const; const policy = { allowExternalExports: false, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: [] }; const first = exportStrategies(repository, request, policy); const second = exportStrategies(repository, request, policy); assertEqual(first.content, second.content, "export order"); assertTrue(first.content?.includes("definitionId") === true, "content"); } },
  { name: "50 LOCAL_ONLY external export is restricted", run: () => { const repository = new InMemoryStrategyRepository(); const lab = new StrategyVersioning(repository, new FixedClock()); const definitionId = lab.createDefinition(definitionSnapshot({ privacyLevel: PrivacyLevel.LocalOnly })).record.definitionId; lab.proposeVersion(versionSnapshot(definitionId, { privacyLevel: PrivacyLevel.LocalOnly })); const result = exportStrategies(repository, { exportId: "export-2", requestedAt: new FixedClock().now(), query: {}, format: StrategyExportFormat.Ndjson, destination: StrategyExportDestination.ExternalTransfer }, { allowExternalExports: true, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: [] }); assertEqual(result.status, StrategyExportStatus.Rejected, "LOCAL_ONLY export"); } },
  { name: "51 secret-bearing metadata is rejected", run: () => expectError(() => setup(definitionSnapshot({ metadata: { api_key: "forbidden" } })), "SECRET_METADATA") },
  { name: "52 corrupt local repository is rejected", run: () => { const root = mkdtempSync(join(tmpdir(), "alpha-strategy-corrupt-")); try { writeFileSync(join(root, "store.ndjson"), "{broken}\n"); expectError(() => new LocalNdjsonStrategyRepository(root, "store"), "malformed JSON"); } finally { rmSync(root, { recursive: true, force: true }); } } },
  { name: "53 local repository reloads deterministically", run: () => { const root = mkdtempSync(join(tmpdir(), "alpha-strategy-reload-")); try { const repo = new LocalNdjsonStrategyRepository(root, "store"); const lab = new StrategyVersioning(repo, new FixedClock()); const id = lab.createDefinition(definitionSnapshot()).record.definitionId; lab.proposeVersion(versionSnapshot(id)); const reloaded = new LocalNdjsonStrategyRepository(root, "store"); assertEqual(reloaded.listVersions(id).length, 1, "reload"); } finally { rmSync(root, { recursive: true, force: true }); } } },
  { name: "54 local repository is append-only", run: () => { const root = mkdtempSync(join(tmpdir(), "alpha-strategy-append-")); try { const repo = new LocalNdjsonStrategyRepository(root, "store"); const lab = new StrategyVersioning(repo, new FixedClock()); const id = lab.createDefinition(definitionSnapshot()).record.definitionId; const before = readFileSync(repo.getStoragePath(), "utf8"); lab.proposeVersion(versionSnapshot(id)); assertTrue(readFileSync(repo.getStoragePath(), "utf8").startsWith(before), "prior bytes changed"); } finally { rmSync(root, { recursive: true, force: true }); } } },
  { name: "55 local path traversal is rejected", run: () => { const root = mkdtempSync(join(tmpdir(), "alpha-strategy-path-")); try { expectError(() => new LocalNdjsonStrategyRepository(root, "../escape"), "path traversal"); } finally { rmSync(root, { recursive: true, force: true }); } } },
  { name: "56 inputs are not mutated", run: () => { const repository = new InMemoryStrategyRepository(); const lab = new StrategyVersioning(repository, new FixedClock()); const input = definitionSnapshot(); const before = JSON.stringify(input); lab.createDefinition(input); assertEqual(JSON.stringify(input), before, "input"); } },
  { name: "57 defensive version copies are returned", run: () => { const { lab, version } = setup(); const returned = lab.getVersion(version.versionId)!; (returned.rules[0] as { condition: string }).condition = "mutated"; assertEqual(lab.getVersion(version.versionId)?.rules[0]?.condition, "score >= 80", "defensive copy"); } },
  { name: "58 strategy audit translation is deterministic", run: () => { const source = { auditId: "audit-strategy-1", operationType: StrategyAuditOperationType.VersionProposed, sourceRecordId: "version-1", definitionId: "definition-1", versionId: "version-1", semanticVersion: "1.0.0", timestamp: "2026-07-18T11:00:00.000Z", status: "PROPOSED", reasonCodes: ["OWNER PROPOSED"], evidenceReferences: ["research-1"], privacyLevel: PrivacyLevel.Internal, retention: AIAuditRetentionClassification.Permanent, correlationId: "correlation-1", traceId: "trace-1", policyVersions: { strategy: "v1" }, metadata: { source: "synthetic" } } as const; const context = { idempotencyKey: "strategy-audit-key-1", actor: { type: AIAuditActorType.Owner, actorId: "owner-1" }, parentAuditRecordIds: [], relatedAuditRecordIds: [] } as const; assertDeepEqual(auditRecordFromStrategy(source, context), auditRecordFromStrategy(source, context), "audit"); } },
  { name: "59 prediction source object is not mutated", run: () => { const prediction = { predictionId: "prediction-1", status: "FINALIZED" }; const before = JSON.stringify(prediction); setup(); assertEqual(JSON.stringify(prediction), before, "prediction"); } },
  { name: "60 journal source object is not mutated", run: () => { const journal = { entryId: "journal-1", status: "FINALIZED" }; const before = JSON.stringify(journal); setup(); assertEqual(JSON.stringify(journal), before, "journal"); } },
  { name: "61 research source object is not mutated", run: () => { const research = { researchId: "research-1", status: "FINALIZED" }; const before = JSON.stringify(research); setup(); assertEqual(JSON.stringify(research), before, "research"); } },
  { name: "62 no provider network credential live-market Python or AI activation boundary", run: () => { const { repository, lab, version } = setup(); const approved = validateAndApprove(lab, version); expectError(() => lab.activate({ ...activation(version.versionId, approved.approvalId), actorType: StrategyApproverType.Ai } as unknown as StrategyActivation), "INVALID_APPROVAL"); const boundary: object = repository; assertTrue(!("execute" in boundary) && !("callProvider" in boundary) && !("placeTrade" in boundary) && !("fetchMarketData" in boundary), "forbidden integration method"); } },
  { name: "63 repository exposes no update overwrite or delete", run: () => { const repo: object = new InMemoryStrategyRepository(); assertTrue(!("update" in repo) && !("overwrite" in repo) && !("delete" in repo), "mutable method"); } },
  { name: "64 rejection remains visible", run: () => { const { lab, version } = setup(); lab.beginValidation(version.versionId, "2026-07-18T13:00:00.000Z", "Validate."); lab.appendValidation(validation(version.versionId)); lab.decide(approval(version.versionId, { decision: StrategyApprovalDecision.Rejected, reason: "Owner rejected." })); assertEqual(lab.getVersion(version.versionId)?.status, StrategyStatus.Rejected, "rejected"); } },
  { name: "65 failed validation cannot be approved", run: () => { const { lab, version } = setup(); lab.beginValidation(version.versionId, "2026-07-18T13:00:00.000Z", "Validate."); lab.appendValidation(validation(version.versionId, { outcome: StrategyValidationOutcome.Failed })); expectError(() => lab.decide(approval(version.versionId)), "VALIDATION_REQUIRED"); } },
  { name: "66 expired approval cannot activate", run: () => { const { lab, version } = setup(); lab.beginValidation(version.versionId, "2026-07-18T13:00:00.000Z", "Validate."); lab.appendValidation(validation(version.versionId)); const approved = lab.decide(approval(version.versionId, { expiresAt: "2026-07-18T15:30:00.000Z" })).record; expectError(() => lab.activate(activation(version.versionId, approved.approvalId)), "APPROVAL_REQUIRED"); } },
  { name: "67 suspension preserves an already frozen snapshot", run: () => { const value = makeActive(); const frozen = value.lab.freezeForTradePlan(value.version.versionId, "2026-07-18T16:30:00.000Z"); value.lab.suspend(suspension(value.version.versionId)); assertEqual(frozen.versionId, value.version.versionId, "snapshot"); } },
  { name: "68 archive follows retirement", run: () => { const value = makeActive(); value.lab.retire(retirement(value.version.versionId)); value.lab.archive(value.version.versionId, "2026-07-18T19:00:00.000Z", "Archive retained evidence."); assertEqual(value.lab.getVersion(value.version.versionId)?.status, StrategyStatus.Archived, "archived"); } },
  { name: "69 truncated local record is rejected", run: () => { const root = mkdtempSync(join(tmpdir(), "alpha-strategy-truncated-")); try { const repo = new LocalNdjsonStrategyRepository(root, "store"); appendFileSync(repo.getStoragePath(), "{}"); expectError(() => new LocalNdjsonStrategyRepository(root, "store"), "truncated final record"); } finally { rmSync(root, { recursive: true, force: true }); } } },
  { name: "70 external export obeys privacy policy", run: () => { const { repository } = setup(); const result = exportStrategies(repository, { exportId: "export-3", requestedAt: new FixedClock().now(), query: {}, format: StrategyExportFormat.Json, destination: StrategyExportDestination.ExternalTransfer }, { allowExternalExports: false, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: [] }); assertEqual(result.status, StrategyExportStatus.Rejected, "restricted export"); } },
];

let passed = 0;
for (const test of tests) { try { test.run(); passed += 1; } catch (error: unknown) { const message = error instanceof Error ? error.message : String(error); console.error(`FAIL: ${test.name}: ${message}`); throw error; } }
console.log(`Strategy Versioning: ${String(passed)}/${String(tests.length)} tests passed.`);
