import { appendFileSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  AIAuditActorType,
  AIAuditRecordType,
  AIAuditRetentionClassification,
  AIAuditSourceSubsystem,
  DevelopmentActorType,
  DevelopmentAppendStatus,
  DevelopmentDefectSeverity,
  DevelopmentDefectStatus,
  DevelopmentExportDestination,
  DevelopmentExportFormat,
  DevelopmentExportStatus,
  DevelopmentFollowUpStatus,
  DevelopmentOwnerDecision,
  DevelopmentPushStatus,
  DevelopmentRiskDecision,
  DevelopmentTaskStatus,
  DevelopmentTestResult,
  DevelopmentValidationCheckResult,
  DevelopmentValidationRecordType,
  DevelopmentWorkingTreeState,
  PrivacyLevel,
  type DevelopmentOwnerApproval,
  type DevelopmentTestRun,
  type DevelopmentValidationRecord,
  type DevelopmentValidationRecordSnapshot,
} from "../../contracts";
import { InMemoryDevelopmentValidationRepository, LocalNdjsonDevelopmentValidationRepository } from "../../repositories";
import { DevelopmentValidationLog, auditRecordFromDevelopmentValidation, exportDevelopmentValidation, type DevelopmentValidationClock } from ".";

interface TestCase { readonly name: string; readonly run: () => void; }
function assertEqual<T>(actual: T, expected: T, message: string): void { if (!Object.is(actual, expected)) throw new Error(`${message}: expected ${String(expected)}, received ${String(actual)}.`); }
function assertTrue(value: boolean, message: string): void { if (!value) throw new Error(message); }
function assertDeepEqual(actual: unknown, expected: unknown, message: string): void { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(message); }
function expectError(action: () => void, expected: string): void { try { action(); } catch (error: unknown) { const message = error instanceof Error ? error.message : String(error); assertTrue(message.includes(expected), `Expected "${expected}", received "${message}".`); return; } throw new Error(`Expected error containing "${expected}".`); }
class FixedClock implements DevelopmentValidationClock { now(): string { return "2026-07-18T23:59:00.000Z"; } }

const BASE_COMMIT = "50686a955930a182b49d6d9b02381d74974c71e2";
const RESULT_COMMIT = "60686a955930a182b49d6d9b02381d74974c71e3";

function baseSnapshot(overrides: Partial<DevelopmentValidationRecordSnapshot> = {}): DevelopmentValidationRecordSnapshot {
  return {
    recordId: "development-record:d5-t5:1", schemaVersion: "1.0", taskId: "D5-T5", taskTitle: "Development Validation Log Foundation", projectDay: "Day5", recordType: DevelopmentValidationRecordType.TaskCreated, timestamp: "2026-07-18T20:00:00.000Z", actorType: DevelopmentActorType.AiAgent,
    requestedGoal: "Implement deterministic development engineering memory.", approvedScope: { summary: "Development Validation Log foundation only.", allowedPaths: ["docs/", "src/contracts/", "src/engines/development-validation/", "src/repositories/"], restrictions: ["No commit or push."], nonGoals: ["No Day 6 work."] },
    filesCreated: [], filesModified: [], filesDeleted: [], fileChanges: [], implementationSummary: "Task request recorded without changing business logic.", testsRequested: ["TypeScript strict typecheck"], testRuns: [], validationChecks: [], failures: [], defects: [], environmentWarnings: [], risks: [], assumptions: [], followUps: [], lessons: [], nonCodeTask: false,
    correlationId: "correlation-d5-t5", traceId: "trace-d5-t5", privacyLevel: PrivacyLevel.Internal, retention: AIAuditRetentionClassification.Permanent, status: DevelopmentTaskStatus.Planned, sourceAuditReferences: [], policyVersions: { development: "development-validation-v1" }, metadata: { source: "synthetic", verified: true }, ...overrides,
  };
}

function passedRun(id = "test-run-pass"): DevelopmentTestRun { return { testRunId: id, logicalName: "TypeScript aggregate suite", command: "npm test", suite: "aggregate", subsystem: "TypeScript", startedAt: "2026-07-18T21:00:00.000Z", completedAt: "2026-07-18T21:01:00.000Z", result: DevelopmentTestResult.Passed, passedCount: 648, failedCount: 0, skippedCount: 0, environment: "Windows Node", warnings: [], evidenceReference: "local:test-output", blocksApproval: false }; }
function failedRun(id = "test-run-fail"): DevelopmentTestRun { return { testRunId: id, logicalName: "Synthetic failing suite", suite: "focused", subsystem: "DevelopmentValidation", startedAt: "2026-07-18T21:00:00.000Z", completedAt: "2026-07-18T21:01:00.000Z", result: DevelopmentTestResult.Failed, passedCount: 1, failedCount: 1, skippedCount: 0, environment: "Windows Node", warnings: [], failureSummary: "Synthetic assertion failed.", evidenceReference: "local:failure-output", blocksApproval: true }; }
function setup(): { repository: InMemoryDevelopmentValidationRepository; log: DevelopmentValidationLog; first: DevelopmentValidationRecord } { const repository = new InMemoryDevelopmentValidationRepository(); const log = new DevelopmentValidationLog(repository, new FixedClock()); return { repository, log, first: log.append(baseSnapshot()).record }; }
function next(log: DevelopmentValidationLog, type: DevelopmentValidationRecordType, status: DevelopmentTaskStatus, sequence: number, overrides: Partial<DevelopmentValidationRecordSnapshot> = {}): DevelopmentValidationRecord { const history = log.history("D5-T5")!; return log.append(baseSnapshot({ recordId: `development-record:d5-t5:${String(sequence)}`, recordType: type, timestamp: `2026-07-18T${String(20 + Math.min(sequence, 3)).padStart(2, "0")}:${String(sequence).padStart(2, "0")}:00.000Z`, status, priorRecordId: history.records.at(-1)!.recordId, ...overrides })).record; }
function implement(log: DevelopmentValidationLog): DevelopmentValidationRecord { next(log, DevelopmentValidationRecordType.InspectionCompleted, DevelopmentTaskStatus.InProgress, 2, { implementationSummary: "Repository patterns inspected." }); return next(log, DevelopmentValidationRecordType.ImplementationCompleted, DevelopmentTaskStatus.Implemented, 3, { implementationSummary: "Foundation implementation completed.", filesCreated: ["src/contracts/DevelopmentValidation.ts"], fileChanges: [{ path: "src/contracts/DevelopmentValidation.ts", changeType: "CREATED", summary: "Added contracts." }] }); }
function validate(log: DevelopmentValidationLog, sequence = 4): DevelopmentValidationRecord { return next(log, DevelopmentValidationRecordType.ValidationPassed, DevelopmentTaskStatus.Validated, sequence, { testRuns: [passedRun(`test-run-pass-${String(sequence)}`)], validationChecks: [{ checkId: `check-pass-${String(sequence)}`, name: "git diff --check", result: DevelopmentValidationCheckResult.Passed, summary: "No whitespace errors.", blocksApproval: false }] }); }
function review(log: DevelopmentValidationLog, sequence = 5): DevelopmentValidationRecord { return next(log, DevelopmentValidationRecordType.OwnerReview, DevelopmentTaskStatus.OwnerReviewed, sequence, { actorType: DevelopmentActorType.Owner, ownerReference: "owner-1", ownerReview: { reviewId: `owner-review-${String(sequence)}`, reviewedTaskId: "D5-T5", reviewedAt: "2026-07-18T23:05:00.000Z", reviewedFiles: ["src/contracts/DevelopmentValidation.ts"], diffReference: "git:working-tree", decision: DevelopmentOwnerDecision.Approved, conditions: [], concerns: [], acceptedRiskIds: [], requiredFollowUpIds: [], ownerReference: "owner-1", gitReference: BASE_COMMIT } }); }
function approvalValue(reviewId: string, overrides: Partial<DevelopmentOwnerApproval> = {}): DevelopmentOwnerApproval { return { approvalId: "owner-approval-1", taskId: "D5-T5", decidedAt: "2026-07-18T23:10:00.000Z", ownerReference: "owner-1", decision: DevelopmentOwnerDecision.Approved, conditions: [], reason: "Owner approved validated scope.", reviewId, gitReference: BASE_COMMIT, ...overrides }; }
function approve(log: DevelopmentValidationLog, sequence = 6, overrides: Partial<DevelopmentValidationRecordSnapshot> = {}): DevelopmentValidationRecord { const ownerReview = [...log.history("D5-T5")!.records].reverse().find((record) => record.ownerReview !== undefined)!.ownerReview!; return next(log, DevelopmentValidationRecordType.OwnerApproval, DevelopmentTaskStatus.Approved, sequence, { actorType: DevelopmentActorType.Owner, ownerReference: "owner-1", ownerApproval: approvalValue(ownerReview.reviewId), ...overrides }); }
function commitGit() { return { branch: "main", baseCommit: BASE_COMMIT, workingTreeState: DevelopmentWorkingTreeState.Clean, remote: "origin", milestoneTag: "Day5", commit: { commitHash: RESULT_COMMIT, commitMessage: "Day5: Implement Development Validation Log Foundation", branch: "main", baseCommit: BASE_COMMIT, createdAt: "2026-07-18T23:20:00.000Z" } } as const; }
function pushGit() { return { ...commitGit(), push: { remote: "origin", branch: "main", status: DevelopmentPushStatus.Succeeded, pushedAt: "2026-07-18T23:30:00.000Z", localCommit: RESULT_COMMIT, remoteCommit: RESULT_COMMIT, synchronized: true } } as const; }
function fullApproved(): { repository: InMemoryDevelopmentValidationRepository; log: DevelopmentValidationLog } { const { repository, log } = setup(); implement(log); validate(log); review(log); approve(log); return { repository, log }; }

const tests: ReadonlyArray<TestCase> = [
  { name: "01 valid task record appends", run: () => assertEqual(setup().first.status, DevelopmentTaskStatus.Planned, "status") },
  { name: "02 duplicate ID is rejected", run: () => { const { repository, first } = setup(); expectError(() => repository.append({ ...baseSnapshot(), implementationSummary: "Conflict" }, first.timestamp), "IDEMPOTENCY_CONFLICT"); } },
  { name: "03 identical append is idempotent", run: () => { const { log } = setup(); assertEqual(log.append(baseSnapshot()).status, DevelopmentAppendStatus.Replayed, "replay"); } },
  { name: "04 conflicting duplicate append is rejected", run: () => { const { log } = setup(); expectError(() => log.append(baseSnapshot({ requestedGoal: "Conflicting goal." })), "IDEMPOTENCY_CONFLICT"); } },
  { name: "05 lifecycle transitions work", run: () => { const { log } = fullApproved(); next(log, DevelopmentValidationRecordType.CommitCreated, DevelopmentTaskStatus.Committed, 7, { gitReference: commitGit() }); next(log, DevelopmentValidationRecordType.PushCompleted, DevelopmentTaskStatus.Pushed, 8, { gitReference: pushGit() }); next(log, DevelopmentValidationRecordType.HandoffCompleted, DevelopmentTaskStatus.HandedOff, 9, { gitReference: pushGit(), handoffReference: { handoffId: "handoff-1", documentPath: "docs/HANDOFF.md", completedAt: "2026-07-18T23:40:00.000Z", summary: "Milestone handed off." } }); assertEqual(log.history("D5-T5")?.currentStatus, DevelopmentTaskStatus.HandedOff, "lifecycle"); } },
  { name: "06 invalid reverse transition is rejected", run: () => { const { log } = setup(); next(log, DevelopmentValidationRecordType.InspectionCompleted, DevelopmentTaskStatus.InProgress, 2); expectError(() => next(log, DevelopmentValidationRecordType.AssumptionRecorded, DevelopmentTaskStatus.Planned, 3, { assumptions: [{ assumptionId: "assumption-1", statement: "Reverse", rationale: "Test", validated: false, invalidationCondition: "Never" }] }), "INVALID_LIFECYCLE"); } },
  { name: "07 validation before implementation is rejected", run: () => { const { log } = setup(); expectError(() => next(log, DevelopmentValidationRecordType.ValidationPassed, DevelopmentTaskStatus.Validated, 2, { testRuns: [passedRun()] }), "INVALID_LIFECYCLE"); } },
  { name: "08 approval before review is rejected", run: () => { const { log } = setup(); implement(log); validate(log); expectError(() => next(log, DevelopmentValidationRecordType.OwnerApproval, DevelopmentTaskStatus.Approved, 5, { actorType: DevelopmentActorType.Owner, ownerReference: "owner-1", ownerApproval: approvalValue("missing-review") }), "INVALID_LIFECYCLE"); } },
  { name: "09 AI cannot approve as owner", run: () => { const { log } = setup(); implement(log); validate(log); const reviewed = review(log); expectError(() => next(log, DevelopmentValidationRecordType.OwnerApproval, DevelopmentTaskStatus.Approved, 6, { actorType: DevelopmentActorType.AiAgent, ownerReference: "owner-1", ownerApproval: approvalValue(reviewed.ownerReview!.reviewId) }), "INVALID_OWNER_DECISION"); } },
  { name: "10 commit before approval is rejected", run: () => { const { log } = setup(); implement(log); validate(log); review(log); expectError(() => next(log, DevelopmentValidationRecordType.CommitCreated, DevelopmentTaskStatus.Committed, 6, { gitReference: commitGit() }), "INVALID_LIFECYCLE"); } },
  { name: "11 push before commit is rejected", run: () => { const { log } = fullApproved(); expectError(() => next(log, DevelopmentValidationRecordType.PushCompleted, DevelopmentTaskStatus.Pushed, 7, { gitReference: pushGit() }), "INVALID_LIFECYCLE"); } },
  { name: "12 failed validation blocks approval by default", run: () => { const { log } = setup(); implement(log); next(log, DevelopmentValidationRecordType.ValidationFailed, DevelopmentTaskStatus.Implemented, 4, { testRuns: [failedRun()] }); validate(log, 5); const reviewed = review(log, 6); expectError(() => next(log, DevelopmentValidationRecordType.OwnerApproval, DevelopmentTaskStatus.Approved, 7, { actorType: DevelopmentActorType.Owner, ownerReference: "owner-1", ownerApproval: approvalValue(reviewed.ownerReview!.reviewId) }), "APPROVAL_REQUIRED"); } },
  { name: "13 explicit accepted exception is preserved", run: () => { const { log } = setup(); implement(log); next(log, DevelopmentValidationRecordType.ValidationFailed, DevelopmentTaskStatus.Implemented, 4, { testRuns: [failedRun()] }); validate(log, 5); const reviewed = review(log, 6); const acceptedValidationException = { exceptionId: "exception-1", acceptedByOwner: "owner-1", acceptedAt: "2026-07-18T23:09:00.000Z", validationIds: ["test-run-fail"], reason: "Known environment-specific failure accepted.", followUpReference: "follow-up-1" }; const stored = next(log, DevelopmentValidationRecordType.OwnerApproval, DevelopmentTaskStatus.Approved, 7, { actorType: DevelopmentActorType.Owner, ownerReference: "owner-1", ownerApproval: approvalValue(reviewed.ownerReview!.reviewId, { acceptedValidationException }) }); assertEqual(stored.ownerApproval?.acceptedValidationException?.exceptionId, "exception-1", "exception"); } },
  { name: "14 test counts validate", run: () => { const { log } = setup(); implement(log); expectError(() => next(log, DevelopmentValidationRecordType.ValidationFailed, DevelopmentTaskStatus.Implemented, 4, { testRuns: [{ ...failedRun(), failedCount: -1 }] }), "INVALID_COUNTS"); } },
  { name: "15 environment warning remains distinct from failure", run: () => { const { log } = setup(); implement(log); const record = next(log, DevelopmentValidationRecordType.EnvironmentWarning, DevelopmentTaskStatus.Implemented, 4, { environmentWarnings: [{ warningId: "warning-1", warningType: "PATH", message: "npm is not on PATH.", environment: "Windows", evidenceReference: "shell:command-not-found" }] }); assertEqual(record.failures.length, 0, "failure count"); assertEqual(record.environmentWarnings.length, 1, "warning count"); } },
  { name: "16 defect record appends", run: () => { const { log } = setup(); implement(log); const record = next(log, DevelopmentValidationRecordType.DefectFound, DevelopmentTaskStatus.Implemented, 4, { defects: [{ defectId: "defect-1", severity: DevelopmentDefectSeverity.Medium, affectedSubsystem: "DevelopmentValidation", description: "Synthetic defect.", reproductionEvidence: "fixture:defect", status: DevelopmentDefectStatus.Open, blocking: false }] }); assertEqual(record.defects[0]?.status, DevelopmentDefectStatus.Open, "defect"); } },
  { name: "17 risk acceptance record appends", run: () => { const { log } = setup(); implement(log); const record = next(log, DevelopmentValidationRecordType.RiskIdentified, DevelopmentTaskStatus.Implemented, 4, { risks: [{ riskId: "risk-1", description: "Local storage is unencrypted.", impact: "Local evidence exposure.", likelihood: 20, decision: DevelopmentRiskDecision.Accepted, blocking: false, mitigation: "Keep runtime data local and ignored.", ownerDecision: "Accepted for development." }] }); assertEqual(record.risks[0]?.decision, DevelopmentRiskDecision.Accepted, "risk"); } },
  { name: "18 follow-up record appends", run: () => { const { log } = setup(); implement(log); const record = next(log, DevelopmentValidationRecordType.FollowUpRequired, DevelopmentTaskStatus.Implemented, 4, { followUps: [{ followUpId: "follow-up-1", taskReference: "Day6-future", priority: "MEDIUM", reason: "Define future reporting standard.", recommendedProjectDay: "Day6", status: DevelopmentFollowUpStatus.Pending }] }); assertEqual(record.followUps[0]?.status, DevelopmentFollowUpStatus.Pending, "follow-up"); } },
  { name: "19 Git commit reference is preserved", run: () => { const { log } = fullApproved(); const record = next(log, DevelopmentValidationRecordType.CommitCreated, DevelopmentTaskStatus.Committed, 7, { gitReference: commitGit() }); assertEqual(record.gitReference?.commit?.commitHash, RESULT_COMMIT, "commit"); } },
  { name: "20 push synchronization status is preserved", run: () => { const { log } = fullApproved(); next(log, DevelopmentValidationRecordType.CommitCreated, DevelopmentTaskStatus.Committed, 7, { gitReference: commitGit() }); const pushed = next(log, DevelopmentValidationRecordType.PushCompleted, DevelopmentTaskStatus.Pushed, 8, { gitReference: pushGit() }); assertEqual(pushed.gitReference?.push?.synchronized, true, "sync"); } },
  { name: "21 task history ordering is deterministic", run: () => { const { log } = setup(); implement(log); assertDeepEqual(log.history("D5-T5")?.records.map((record) => record.sequence), [1, 2, 3], "ordering"); } },
  { name: "22 query by task ID works", run: () => assertEqual(setup().log.query({ filter: { taskId: "D5-T5" } }).length, 1, "task query") },
  { name: "23 query by project day works", run: () => assertEqual(setup().log.query({ filter: { projectDay: "Day5" } }).length, 1, "day query") },
  { name: "24 query failed validations works", run: () => { const { log } = setup(); implement(log); next(log, DevelopmentValidationRecordType.ValidationFailed, DevelopmentTaskStatus.Implemented, 4, { testRuns: [failedRun()] }); assertEqual(log.query({ filter: { failedValidationsOnly: true } }).length, 1, "failed query"); } },
  { name: "25 query open defects works", run: () => { const { log } = setup(); implement(log); next(log, DevelopmentValidationRecordType.DefectFound, DevelopmentTaskStatus.Implemented, 4, { defects: [{ defectId: "defect-1", severity: DevelopmentDefectSeverity.Low, affectedSubsystem: "Fixture", description: "Open", reproductionEvidence: "fixture", status: DevelopmentDefectStatus.Open, blocking: false }] }); assertEqual(log.query({ filter: { openDefectsOnly: true } }).length, 1, "defect query"); } },
  { name: "26 query pending follow-ups works", run: () => { const { log } = setup(); implement(log); next(log, DevelopmentValidationRecordType.FollowUpRequired, DevelopmentTaskStatus.Implemented, 4, { followUps: [{ followUpId: "follow-up-1", taskReference: "future", priority: "LOW", reason: "Later", status: DevelopmentFollowUpStatus.Pending }] }); assertEqual(log.query({ filter: { pendingFollowUpsOnly: true } }).length, 1, "follow-up query"); } },
  { name: "27 statistics are deterministic", run: () => { const { log } = setup(); implement(log); validate(log); assertDeepEqual(log.statistics(), log.statistics(), "statistics"); assertEqual(log.statistics().validationsPassed, 2, "validations"); } },
  { name: "28 export ordering is deterministic", run: () => { const { repository } = setup(); const request = { exportId: "export-1", requestedAt: new FixedClock().now(), query: {}, format: DevelopmentExportFormat.Json, destination: DevelopmentExportDestination.LocalSnapshot } as const; const policy = { allowExternalExports: false, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: [] }; assertEqual(exportDevelopmentValidation(repository, request, policy).content, exportDevelopmentValidation(repository, request, policy).content, "export"); } },
  { name: "29 LOCAL_ONLY export restriction is enforced", run: () => { const repository = new InMemoryDevelopmentValidationRepository(); const log = new DevelopmentValidationLog(repository, new FixedClock()); log.append(baseSnapshot({ privacyLevel: PrivacyLevel.LocalOnly })); const result = exportDevelopmentValidation(repository, { exportId: "export-2", requestedAt: new FixedClock().now(), query: {}, format: DevelopmentExportFormat.Ndjson, destination: DevelopmentExportDestination.ExternalTransfer }, { allowExternalExports: true, requireSensitiveAuthorization: false, sensitiveAuthorizationReferences: [] }); assertEqual(result.status, DevelopmentExportStatus.Rejected, "export status"); } },
  { name: "30 secret metadata is rejected", run: () => expectError(() => new DevelopmentValidationLog(new InMemoryDevelopmentValidationRepository(), new FixedClock()).append(baseSnapshot({ metadata: { api_key: "forbidden" } })), "SECRET_METADATA") },
  { name: "31 inputs are not mutated", run: () => { const value = baseSnapshot(); const before = JSON.stringify(value); new DevelopmentValidationLog(new InMemoryDevelopmentValidationRepository(), new FixedClock()).append(value); assertEqual(JSON.stringify(value), before, "input"); } },
  { name: "32 defensive copies are returned", run: () => { const { log, first } = setup(); const value = log.get(first.recordId)!; (value as { taskTitle: string }).taskTitle = "Mutated"; assertTrue(log.get(first.recordId)?.taskTitle !== "Mutated", "stored record mutated"); } },
  { name: "33 corrupt NDJSON fails closed", run: () => { const root = mkdtempSync(join(tmpdir(), "alpha-development-corrupt-")); try { writeFileSync(join(root, "store.ndjson"), "{broken}\n"); expectError(() => new LocalNdjsonDevelopmentValidationRepository(root, "store"), "malformed JSON"); } finally { rmSync(root, { recursive: true, force: true }); } } },
  { name: "34 local repository reload preserves records", run: () => { const root = mkdtempSync(join(tmpdir(), "alpha-development-reload-")); try { const repo = new LocalNdjsonDevelopmentValidationRepository(root, "store"); new DevelopmentValidationLog(repo, new FixedClock()).append(baseSnapshot()); assertEqual(new LocalNdjsonDevelopmentValidationRepository(root, "store").allRecords().length, 1, "reload"); } finally { rmSync(root, { recursive: true, force: true }); } } },
  { name: "35 durable append does not rewrite prior history", run: () => { const root = mkdtempSync(join(tmpdir(), "alpha-development-append-")); try { const repo = new LocalNdjsonDevelopmentValidationRepository(root, "store"); const log = new DevelopmentValidationLog(repo, new FixedClock()); log.append(baseSnapshot()); const before = readFileSync(repo.getStoragePath(), "utf8"); next(log, DevelopmentValidationRecordType.InspectionCompleted, DevelopmentTaskStatus.InProgress, 2); assertTrue(readFileSync(repo.getStoragePath(), "utf8").startsWith(before), "prior bytes changed"); } finally { rmSync(root, { recursive: true, force: true }); } } },
  { name: "36 path traversal is rejected", run: () => { const root = mkdtempSync(join(tmpdir(), "alpha-development-path-")); try { expectError(() => new LocalNdjsonDevelopmentValidationRepository(root, "../escape"), "path traversal"); } finally { rmSync(root, { recursive: true, force: true }); } } },
  { name: "37 audit translation is deterministic", run: () => { const { first } = setup(); const context = { idempotencyKey: "development-audit-key", actor: { type: AIAuditActorType.AlphaSubsystem, actorId: "development-validation" }, parentAuditRecordIds: [], relatedAuditRecordIds: [] } as const; const translated = auditRecordFromDevelopmentValidation(first, context); assertDeepEqual(translated, auditRecordFromDevelopmentValidation(first, context), "audit"); assertEqual(translated.recordType, AIAuditRecordType.DevelopmentValidation, "record type"); assertEqual(translated.sourceSubsystem, AIAuditSourceSubsystem.DevelopmentValidation, "subsystem"); } },
  { name: "38 Git history is not mutated", run: () => { const git = commitGit(); const before = JSON.stringify(git); const { log } = fullApproved(); next(log, DevelopmentValidationRecordType.CommitCreated, DevelopmentTaskStatus.Committed, 7, { gitReference: git }); assertEqual(JSON.stringify(git), before, "Git input"); const repository: object = new InMemoryDevelopmentValidationRepository(); assertTrue(!("commit" in repository) && !("push" in repository) && !("executeGit" in repository), "Git method exposed"); } },
  { name: "39 Strategy Versioning boundary remains reference-only", run: () => assertTrue(!("activateStrategy" in (new InMemoryDevelopmentValidationRepository() as object)), "strategy method exposed") },
  { name: "40 Research Lab boundary remains reference-only", run: () => assertTrue(!("finalizeResearch" in (new InMemoryDevelopmentValidationRepository() as object)), "research method exposed") },
  { name: "41 Alpha Journal boundary remains reference-only", run: () => assertTrue(!("writeJournal" in (new InMemoryDevelopmentValidationRepository() as object)), "journal method exposed") },
  { name: "42 Prediction Log boundary remains reference-only", run: () => assertTrue(!("lockPrediction" in (new InMemoryDevelopmentValidationRepository() as object)), "prediction method exposed") },
  { name: "43 AI Infrastructure remains provider-neutral", run: () => { const repository: object = new InMemoryDevelopmentValidationRepository(); assertTrue(!("callProvider" in repository) && !("fetch" in repository), "provider method exposed"); } },
  { name: "44 aggregate suite exposes focused development tests", run: () => { const packageText = readFileSync("package.json", "utf8"); assertTrue(packageText.includes("test:development-validation") && packageText.includes("DevelopmentValidationLog.test.ts"), "aggregate exposure missing"); } },
  { name: "45 repository has no overwrite or delete methods", run: () => { const repository: object = new InMemoryDevelopmentValidationRepository(); assertTrue(!("update" in repository) && !("overwrite" in repository) && !("delete" in repository), "mutable method exposed"); } },
  { name: "46 runtime validation data path is Git-ignored", run: () => assertTrue(readFileSync(".gitignore", "utf8").includes("data/runtime/development-validation/"), "ignore rule") },
  { name: "47 no provider network broker or Python implementation exists", run: () => { const source = ["DevelopmentValidationLog.ts", "DevelopmentValidationExports.ts", "DevelopmentValidationAuditTranslations.ts"].map((name) => readFileSync(join("src/engines/development-validation", name), "utf8")).join("\n"); assertTrue(!/fetch\s*\(|axios|node:https|brokerClient|openai|anthropic/i.test(source), "forbidden implementation"); } },
  { name: "48 Day 6 development standard remains documentation-only", run: () => { assertTrue(existsSync("docs/CODEX_DEVELOPMENT_STANDARD.md"), "D6 standard missing"); assertTrue(!existsSync("src/engines/codex-development-standard"), "runtime implementation exists"); } },
];

let passed = 0;
for (const test of tests) { try { test.run(); passed += 1; } catch (error: unknown) { const message = error instanceof Error ? error.message : String(error); console.error(`FAIL: ${test.name}: ${message}`); throw error; } }
console.log(`Development Validation Log: ${String(passed)}/${String(tests.length)} tests passed.`);
