"""Decision thresholds used by the Alpha strategy engine."""


# Stock position rules
STOCK_REVIEW_LOSS_PERCENTAGE = -10.0
STOCK_PARTIAL_TAKE_PROFIT_PERCENTAGE = 30.0


# Event contract rules
EVENT_REVIEW_LOSS_PERCENTAGE = -20.0
EVENT_PARTIAL_TAKE_PROFIT_PERCENTAGE = 20.0
EVENT_TAKE_PROFIT_PERCENTAGE = 40.0
EVENT_STRONG_TAKE_PROFIT_PERCENTAGE = 100.0