import {
  HistoricalAppendStatus, HistoricalEventStatus, HistoricalPatternErrorCategory, HistoricalPatternStatus,
  PrivacyLevel,
  canonicalizeHistoricalValue, historicalFingerprint, throwIfInvalidHistorical,
  validateHistoricalEvent, validateHistoricalEventAmendment, validateHistoricalEventHistory,
  validateHistoricalEventReview, validateHistoricalPattern, validateHistoricalPatternAmendment,
  validateHistoricalPatternHistory, validateHistoricalPatternQuery, validateHistoricalPatternReview,
  validateHistoricalPatternSupersession,
  type HistoricalAppendResult, type HistoricalEvent, type HistoricalEventAmendment,
  type HistoricalEventHistory, type HistoricalEventRecordHistory, type HistoricalEventReview,
  type HistoricalPattern, type HistoricalPatternAmendment, type HistoricalPatternHistory,
  type HistoricalPatternHistoryEntry, type HistoricalPatternQuery, type HistoricalPatternRepository,
  type HistoricalPatternReview, type HistoricalPatternSupersession,
} from "../contracts";
import { matchesHistoricalEventQuery, matchesHistoricalPatternQuery, type HistoricalRepositoryEvent } from "./HistoricalPatternRepository";

const clone = <T>(value: T): T => structuredClone(value);
const privacyRank: Readonly<Record<PrivacyLevel, number>> = { [PrivacyLevel.Public]: 0, [PrivacyLevel.Internal]: 1, [PrivacyLevel.Sensitive]: 2, [PrivacyLevel.LocalOnly]: 3 };
function fail(category: HistoricalPatternErrorCategory, message: string): never { const value = new Error(`${category}: ${message}`); Object.assign(value, { category }); throw value; }
type EventInput = HistoricalRepositoryEvent extends infer T ? T extends HistoricalRepositoryEvent ? Omit<T, "sequence" | "fingerprint"> : never : never;

export class InMemoryHistoricalPatternRepository implements HistoricalPatternRepository {
  private readonly originalEvents = new Map<string, HistoricalEvent>(); private readonly currentEvents = new Map<string, HistoricalEvent>(); private readonly eventSequences = new Map<string, number>();
  private readonly originalPatterns = new Map<string, HistoricalPattern>(); private readonly currentPatterns = new Map<string, HistoricalPattern>(); private readonly patternSequences = new Map<string, number>();
  private readonly eventAmendments = new Map<string, HistoricalEventAmendment>(); private readonly eventAmendmentSequences = new Map<string, number>();
  private readonly patternAmendments = new Map<string, HistoricalPatternAmendment>(); private readonly patternAmendmentSequences = new Map<string, number>();
  private readonly eventReviews = new Map<string, HistoricalEventReview>(); private readonly eventReviewSequences = new Map<string, number>(); private readonly reviewedEvents = new Set<string>();
  private readonly patternReviews = new Map<string, HistoricalPatternReview>(); private readonly patternReviewSequences = new Map<string, number>(); private readonly reviewedPatterns = new Set<string>();
  private readonly supersessions = new Map<string, HistoricalPatternSupersession>(); private readonly supersessionSequences = new Map<string, number>(); private readonly supersessionByPrior = new Map<string, HistoricalPatternSupersession>();
  private readonly eventArchives = new Map<string, number>(); private readonly patternArchives = new Map<string, number>(); private readonly events: HistoricalRepositoryEvent[] = [];

  constructor(seedEvents: ReadonlyArray<HistoricalRepositoryEvent> = []) { for (const event of seedEvents) this.applySeed(clone(event)); }
  protected persistEvent(_event: Readonly<HistoricalRepositoryEvent>): void {}
  private nextSequence(): number { const value = this.events.length + 1; if (!Number.isSafeInteger(value)) fail(HistoricalPatternErrorCategory.RepositoryCorrupt, "repository sequence overflow."); return value; }
  private envelope<T extends EventInput>(input: T): T & Pick<HistoricalRepositoryEvent, "sequence" | "fingerprint"> { const withSequence = { ...input, sequence: this.nextSequence() }; return { ...withSequence, fingerprint: historicalFingerprint(withSequence) } as T & Pick<HistoricalRepositoryEvent, "sequence" | "fingerprint">; }
  private commit(event: HistoricalRepositoryEvent, persist: boolean): void { if (event.sequence !== this.nextSequence() || event.fingerprint !== historicalFingerprint({ ...event, fingerprint: undefined })) fail(HistoricalPatternErrorCategory.RepositoryCorrupt, "repository sequence or fingerprint is invalid."); if (persist) this.persistEvent(clone(event)); this.events.push(clone(event)); }
  private applySeed(event: HistoricalRepositoryEvent): void { switch (event.eventType) { case "HISTORICAL_EVENT_FINALIZED": this.applyEvent(event.record, event, false); break; case "HISTORICAL_PATTERN_FINALIZED": this.applyPattern(event.record, event, false); break; case "EVENT_AMENDMENT_APPENDED": this.applyEventAmendment(event.amendment, event, false); break; case "PATTERN_AMENDMENT_APPENDED": this.applyPatternAmendment(event.amendment, event, false); break; case "EVENT_REVIEW_APPENDED": this.applyEventReview(event.review, event.history, event, false); break; case "PATTERN_REVIEW_APPENDED": this.applyPatternReview(event.review, event.history, event, false); break; case "PATTERN_SUPERSESSION_APPENDED": this.applySupersession(event.supersession, event.history, event, false); break; case "EVENT_ARCHIVED": this.applyEventArchive(event.history, event, false); break; case "PATTERN_ARCHIVED": this.applyPatternArchive(event.history, event, false); break; default: fail(HistoricalPatternErrorCategory.RepositoryCorrupt, "unsupported repository event."); } }

  appendEvent(record: HistoricalEvent, acceptedAt: string): HistoricalAppendResult<HistoricalEvent> { const existing = this.originalEvents.get(record.eventId); if (existing !== undefined) return this.replay(existing, record, this.eventSequences.get(record.eventId), "event ID conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "HISTORICAL_EVENT_FINALIZED", acceptedAt, record: clone(record) }); return this.applyEvent(record, event, true); }
  private applyEvent(record: HistoricalEvent, envelope: Extract<HistoricalRepositoryEvent, { eventType: "HISTORICAL_EVENT_FINALIZED" }>, persist: boolean): HistoricalAppendResult<HistoricalEvent> { if (this.originalEvents.has(record.eventId)) fail(HistoricalPatternErrorCategory.RepositoryCorrupt, "duplicate event in history."); throwIfInvalidHistorical(validateHistoricalEvent(record)); if (this.relatedEventCycle(record.eventId, record.relatedEventIds)) fail(HistoricalPatternErrorCategory.InvalidReference, "cyclic related-event graph is forbidden."); this.commit(envelope, persist); this.originalEvents.set(record.eventId, clone(record)); this.currentEvents.set(record.eventId, clone(record)); this.eventSequences.set(record.eventId, envelope.sequence); return { status: HistoricalAppendStatus.Appended, record: clone(record), repositorySequence: envelope.sequence }; }

  appendPattern(record: HistoricalPattern, acceptedAt: string): HistoricalAppendResult<HistoricalPattern> { const existing = this.originalPatterns.get(record.patternId); if (existing !== undefined) return this.replay(existing, record, this.patternSequences.get(record.patternId), "pattern ID conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "HISTORICAL_PATTERN_FINALIZED", acceptedAt, record: clone(record) }); return this.applyPattern(record, event, true); }
  private applyPattern(record: HistoricalPattern, envelope: Extract<HistoricalRepositoryEvent, { eventType: "HISTORICAL_PATTERN_FINALIZED" }>, persist: boolean): HistoricalAppendResult<HistoricalPattern> { if (this.originalPatterns.has(record.patternId)) fail(HistoricalPatternErrorCategory.RepositoryCorrupt, "duplicate pattern in history."); throwIfInvalidHistorical(validateHistoricalPattern(record)); if (record.sourceEventIds.some((id) => { const event = this.currentEvents.get(id); return event === undefined || ![HistoricalEventStatus.Finalized, HistoricalEventStatus.Reviewed].includes(event.status); })) fail(HistoricalPatternErrorCategory.MissingSupportingEvent, "pattern source events must exist and be current finalized evidence."); if (record.sourceEventIds.some((id) => privacyRank[record.privacyLevel] < privacyRank[(this.currentEvents.get(id) as HistoricalEvent).privacyLevel])) fail(HistoricalPatternErrorCategory.InvalidPrivacy, "pattern privacy cannot downgrade source-event privacy."); if (this.relatedPatternCycle(record.patternId, record.relatedPatternIds)) fail(HistoricalPatternErrorCategory.InvalidReference, "cyclic related-pattern graph is forbidden."); this.commit(envelope, persist); this.originalPatterns.set(record.patternId, clone(record)); this.currentPatterns.set(record.patternId, clone(record)); this.patternSequences.set(record.patternId, envelope.sequence); return { status: HistoricalAppendStatus.Appended, record: clone(record), repositorySequence: envelope.sequence }; }

  appendEventAmendment(value: HistoricalEventAmendment, acceptedAt: string): HistoricalAppendResult<HistoricalEventAmendment> { const existing = this.eventAmendments.get(value.amendmentId); if (existing !== undefined) return this.replay(existing, value, this.eventAmendmentSequences.get(value.amendmentId), "event amendment conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "EVENT_AMENDMENT_APPENDED", acceptedAt, amendment: clone(value) }); return this.applyEventAmendment(value, event, true); }
  private applyEventAmendment(value: HistoricalEventAmendment, envelope: Extract<HistoricalRepositoryEvent, { eventType: "EVENT_AMENDMENT_APPENDED" }>, persist: boolean): HistoricalAppendResult<HistoricalEventAmendment> { throwIfInvalidHistorical(validateHistoricalEventAmendment(value, this.currentEvents.get(value.eventId))); this.validateAmendmentParent(value.amendmentId, value.parentAmendmentId, value.eventId, this.eventAmendments, "eventId"); this.commit(envelope, persist); this.eventAmendments.set(value.amendmentId, clone(value)); this.eventAmendmentSequences.set(value.amendmentId, envelope.sequence); return { status: HistoricalAppendStatus.Appended, record: clone(value), repositorySequence: envelope.sequence }; }

  appendPatternAmendment(value: HistoricalPatternAmendment, acceptedAt: string): HistoricalAppendResult<HistoricalPatternAmendment> { const existing = this.patternAmendments.get(value.amendmentId); if (existing !== undefined) return this.replay(existing, value, this.patternAmendmentSequences.get(value.amendmentId), "pattern amendment conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "PATTERN_AMENDMENT_APPENDED", acceptedAt, amendment: clone(value) }); return this.applyPatternAmendment(value, event, true); }
  private applyPatternAmendment(value: HistoricalPatternAmendment, envelope: Extract<HistoricalRepositoryEvent, { eventType: "PATTERN_AMENDMENT_APPENDED" }>, persist: boolean): HistoricalAppendResult<HistoricalPatternAmendment> { throwIfInvalidHistorical(validateHistoricalPatternAmendment(value, this.currentPatterns.get(value.patternId))); this.validateAmendmentParent(value.amendmentId, value.parentAmendmentId, value.patternId, this.patternAmendments, "patternId"); this.commit(envelope, persist); this.patternAmendments.set(value.amendmentId, clone(value)); this.patternAmendmentSequences.set(value.amendmentId, envelope.sequence); return { status: HistoricalAppendStatus.Appended, record: clone(value), repositorySequence: envelope.sequence }; }

  appendEventReview(value: HistoricalEventReview, history: HistoricalEventHistory, acceptedAt: string): HistoricalAppendResult<HistoricalEventReview> { const existing = this.eventReviews.get(value.reviewId); if (existing !== undefined) return this.replay(existing, value, this.eventReviewSequences.get(value.reviewId), "event review conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "EVENT_REVIEW_APPENDED", acceptedAt, review: clone(value), history: clone(history) }); return this.applyEventReview(value, history, event, true); }
  private applyEventReview(value: HistoricalEventReview, history: HistoricalEventHistory, envelope: Extract<HistoricalRepositoryEvent, { eventType: "EVENT_REVIEW_APPENDED" }>, persist: boolean): HistoricalAppendResult<HistoricalEventReview> { const record = this.currentEvents.get(value.eventId); throwIfInvalidHistorical(validateHistoricalEventReview(value, record)); if (record === undefined) fail(HistoricalPatternErrorCategory.RecordNotFound, "event does not exist."); if (this.reviewedEvents.has(value.eventId)) fail(HistoricalPatternErrorCategory.DuplicateId, "event already reviewed."); throwIfInvalidHistorical(validateHistoricalEventHistory(history, record)); if (history.toStatus !== HistoricalEventStatus.Reviewed || history.referenceId !== value.reviewId) fail(HistoricalPatternErrorCategory.InvalidLifecycle, "event review history is invalid."); this.commit(envelope, persist); this.eventReviews.set(value.reviewId, clone(value)); this.eventReviewSequences.set(value.reviewId, envelope.sequence); this.reviewedEvents.add(value.eventId); this.currentEvents.set(value.eventId, { ...clone(record), status: HistoricalEventStatus.Reviewed, history: [...record.history.map(clone), clone(history)] }); return { status: HistoricalAppendStatus.Appended, record: clone(value), repositorySequence: envelope.sequence }; }

  appendPatternReview(value: HistoricalPatternReview, history: HistoricalPatternHistoryEntry, acceptedAt: string): HistoricalAppendResult<HistoricalPatternReview> { const existing = this.patternReviews.get(value.reviewId); if (existing !== undefined) return this.replay(existing, value, this.patternReviewSequences.get(value.reviewId), "pattern review conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "PATTERN_REVIEW_APPENDED", acceptedAt, review: clone(value), history: clone(history) }); return this.applyPatternReview(value, history, event, true); }
  private applyPatternReview(value: HistoricalPatternReview, history: HistoricalPatternHistoryEntry, envelope: Extract<HistoricalRepositoryEvent, { eventType: "PATTERN_REVIEW_APPENDED" }>, persist: boolean): HistoricalAppendResult<HistoricalPatternReview> { const record = this.currentPatterns.get(value.patternId); throwIfInvalidHistorical(validateHistoricalPatternReview(value, record)); if (record === undefined) fail(HistoricalPatternErrorCategory.RecordNotFound, "pattern does not exist."); if (this.reviewedPatterns.has(value.patternId)) fail(HistoricalPatternErrorCategory.DuplicateId, "pattern already reviewed."); throwIfInvalidHistorical(validateHistoricalPatternHistory(history, record)); if (history.toStatus !== HistoricalPatternStatus.Reviewed || history.referenceId !== value.reviewId) fail(HistoricalPatternErrorCategory.InvalidLifecycle, "pattern review history is invalid."); this.commit(envelope, persist); this.patternReviews.set(value.reviewId, clone(value)); this.patternReviewSequences.set(value.reviewId, envelope.sequence); this.reviewedPatterns.add(value.patternId); this.currentPatterns.set(value.patternId, { ...clone(record), status: HistoricalPatternStatus.Reviewed, history: [...record.history.map(clone), clone(history)] }); return { status: HistoricalAppendStatus.Appended, record: clone(value), repositorySequence: envelope.sequence }; }

  appendSupersession(value: HistoricalPatternSupersession, history: HistoricalPatternHistoryEntry, acceptedAt: string): HistoricalAppendResult<HistoricalPatternSupersession> { const existing = this.supersessions.get(value.supersessionId); if (existing !== undefined) return this.replay(existing, value, this.supersessionSequences.get(value.supersessionId), "supersession conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "PATTERN_SUPERSESSION_APPENDED", acceptedAt, supersession: clone(value), history: clone(history) }); return this.applySupersession(value, history, event, true); }
  private applySupersession(value: HistoricalPatternSupersession, history: HistoricalPatternHistoryEntry, envelope: Extract<HistoricalRepositoryEvent, { eventType: "PATTERN_SUPERSESSION_APPENDED" }>, persist: boolean): HistoricalAppendResult<HistoricalPatternSupersession> { const prior = this.currentPatterns.get(value.priorPatternId); const successor = this.currentPatterns.get(value.successorPatternId); throwIfInvalidHistorical(validateHistoricalPatternSupersession(value, prior, successor)); if (prior === undefined || successor === undefined) fail(HistoricalPatternErrorCategory.RecordNotFound, "supersession pattern missing."); if (this.supersessionByPrior.has(value.priorPatternId)) fail(HistoricalPatternErrorCategory.DuplicateId, "prior pattern already superseded."); let cursor: string | undefined = value.successorPatternId; const visited = new Set<string>(); while (cursor !== undefined) { if (cursor === value.priorPatternId) fail(HistoricalPatternErrorCategory.InvalidReference, "cyclic supersession is forbidden."); if (visited.has(cursor)) fail(HistoricalPatternErrorCategory.InvalidReference, "existing supersession cycle detected."); visited.add(cursor); cursor = this.supersessionByPrior.get(cursor)?.successorPatternId; } throwIfInvalidHistorical(validateHistoricalPatternHistory(history, prior)); if (history.toStatus !== HistoricalPatternStatus.Superseded || history.referenceId !== value.supersessionId) fail(HistoricalPatternErrorCategory.InvalidLifecycle, "supersession history is invalid."); this.commit(envelope, persist); this.supersessions.set(value.supersessionId, clone(value)); this.supersessionSequences.set(value.supersessionId, envelope.sequence); this.supersessionByPrior.set(value.priorPatternId, clone(value)); this.currentPatterns.set(value.priorPatternId, { ...clone(prior), status: HistoricalPatternStatus.Superseded, history: [...prior.history.map(clone), clone(history)] }); return { status: HistoricalAppendStatus.Appended, record: clone(value), repositorySequence: envelope.sequence }; }

  appendEventArchive(history: HistoricalEventHistory, acceptedAt: string): HistoricalAppendResult<HistoricalEventHistory> { const sequence = this.eventArchives.get(history.eventId); if (sequence !== undefined) { const existing = this.currentEvents.get(history.eventId)?.history.find((value) => value.toStatus === HistoricalEventStatus.Archived); return this.replay(existing, history, sequence, "event archive conflict."); } const event = this.envelope({ schemaVersion: "1.0", eventType: "EVENT_ARCHIVED", acceptedAt, history: clone(history) }); return this.applyEventArchive(history, event, true); }
  private applyEventArchive(history: HistoricalEventHistory, envelope: Extract<HistoricalRepositoryEvent, { eventType: "EVENT_ARCHIVED" }>, persist: boolean): HistoricalAppendResult<HistoricalEventHistory> { const record = this.currentEvents.get(history.eventId); if (record === undefined) fail(HistoricalPatternErrorCategory.RecordNotFound, "event does not exist."); throwIfInvalidHistorical(validateHistoricalEventHistory(history, record)); if (history.toStatus !== HistoricalEventStatus.Archived) fail(HistoricalPatternErrorCategory.InvalidLifecycle, "event archive status is invalid."); this.commit(envelope, persist); this.eventArchives.set(history.eventId, envelope.sequence); this.currentEvents.set(history.eventId, { ...clone(record), status: HistoricalEventStatus.Archived, history: [...record.history.map(clone), clone(history)] }); return { status: HistoricalAppendStatus.Appended, record: clone(history), repositorySequence: envelope.sequence }; }

  appendPatternArchive(history: HistoricalPatternHistoryEntry, acceptedAt: string): HistoricalAppendResult<HistoricalPatternHistoryEntry> { const sequence = this.patternArchives.get(history.patternId); if (sequence !== undefined) { const existing = this.currentPatterns.get(history.patternId)?.history.find((value) => value.toStatus === HistoricalPatternStatus.Archived); return this.replay(existing, history, sequence, "pattern archive conflict."); } const event = this.envelope({ schemaVersion: "1.0", eventType: "PATTERN_ARCHIVED", acceptedAt, history: clone(history) }); return this.applyPatternArchive(history, event, true); }
  private applyPatternArchive(history: HistoricalPatternHistoryEntry, envelope: Extract<HistoricalRepositoryEvent, { eventType: "PATTERN_ARCHIVED" }>, persist: boolean): HistoricalAppendResult<HistoricalPatternHistoryEntry> { const record = this.currentPatterns.get(history.patternId); if (record === undefined) fail(HistoricalPatternErrorCategory.RecordNotFound, "pattern does not exist."); throwIfInvalidHistorical(validateHistoricalPatternHistory(history, record)); if (history.toStatus !== HistoricalPatternStatus.Archived) fail(HistoricalPatternErrorCategory.InvalidLifecycle, "pattern archive status is invalid."); this.commit(envelope, persist); this.patternArchives.set(history.patternId, envelope.sequence); this.currentPatterns.set(history.patternId, { ...clone(record), status: HistoricalPatternStatus.Archived, history: [...record.history.map(clone), clone(history)] }); return { status: HistoricalAppendStatus.Appended, record: clone(history), repositorySequence: envelope.sequence }; }

  getEventById(id: string): HistoricalEvent | undefined { const value = this.currentEvents.get(id); return value === undefined ? undefined : clone(value); }
  getPatternById(id: string): HistoricalPattern | undefined { const value = this.currentPatterns.get(id); return value === undefined ? undefined : clone(value); }
  getEventHistory(id: string): HistoricalEventRecordHistory | undefined { const record = this.getEventById(id); if (record === undefined) return undefined; return { record, lifecycle: record.history.map(clone), amendments: this.sorted(this.eventAmendments, this.eventAmendmentSequences, (value) => value.eventId === id), reviews: this.sorted(this.eventReviews, this.eventReviewSequences, (value) => value.eventId === id) }; }
  getPatternHistory(id: string): HistoricalPatternHistory | undefined { const record = this.getPatternById(id); if (record === undefined) return undefined; return { record, lifecycle: record.history.map(clone), amendments: this.sorted(this.patternAmendments, this.patternAmendmentSequences, (value) => value.patternId === id), reviews: this.sorted(this.patternReviews, this.patternReviewSequences, (value) => value.patternId === id), supersessions: this.sorted(this.supersessions, this.supersessionSequences, (value) => value.priorPatternId === id || value.successorPatternId === id) }; }
  queryEvents(query: HistoricalPatternQuery = {}): ReadonlyArray<HistoricalEvent> { throwIfInvalidHistorical(validateHistoricalPatternQuery(query)); return this.paged([...this.currentEvents.values()].filter((value) => matchesHistoricalEventQuery(value, query)), this.eventSequences, (value) => value.eventId, query); }
  queryPatterns(query: HistoricalPatternQuery = {}): ReadonlyArray<HistoricalPattern> { throwIfInvalidHistorical(validateHistoricalPatternQuery(query)); return this.paged([...this.currentPatterns.values()].filter((value) => matchesHistoricalPatternQuery(value, query)), this.patternSequences, (value) => value.patternId, query); }
  listRelatedEvents(id: string): ReadonlyArray<HistoricalEvent> { const record = this.currentEvents.get(id); if (record === undefined) return []; return [...this.currentEvents.values()].filter((value) => value.eventId !== id && (record.relatedEventIds.includes(value.eventId) || value.relatedEventIds.includes(id))).sort((a, b) => (this.eventSequences.get(a.eventId) as number) - (this.eventSequences.get(b.eventId) as number)).map(clone); }
  listRelatedPatterns(id: string): ReadonlyArray<HistoricalPattern> { const record = this.currentPatterns.get(id); if (record === undefined) return []; return [...this.currentPatterns.values()].filter((value) => value.patternId !== id && (record.relatedPatternIds.includes(value.patternId) || value.relatedPatternIds.includes(id))).sort((a, b) => (this.patternSequences.get(a.patternId) as number) - (this.patternSequences.get(b.patternId) as number)).map(clone); }
  allEvents(): ReadonlyArray<HistoricalRepositoryEvent> { return this.events.map(clone); }

  private replay<T>(existing: T | undefined, incoming: T, sequence: number | undefined, message: string): HistoricalAppendResult<T> { if (existing !== undefined && sequence !== undefined && canonicalizeHistoricalValue(existing) === canonicalizeHistoricalValue(incoming)) return { status: HistoricalAppendStatus.Replayed, record: clone(existing), repositorySequence: sequence }; fail(HistoricalPatternErrorCategory.IdempotencyConflict, message); }
  private sorted<T>(values: Map<string, T>, sequences: Map<string, number>, include: (value: T) => boolean): T[] { return [...values.entries()].filter(([, value]) => include(value)).sort(([a], [b]) => (sequences.get(a) as number) - (sequences.get(b) as number)).map(([, value]) => clone(value)); }
  private paged<T>(values: T[], sequences: Map<string, number>, id: (value: T) => string, query: HistoricalPatternQuery): T[] { const offset = query.offset ?? 0; return values.sort((a, b) => (sequences.get(id(a)) as number) - (sequences.get(id(b)) as number)).slice(offset, offset + (query.limit ?? Number.MAX_SAFE_INTEGER)).map(clone); }
  private validateAmendmentParent<T extends { readonly amendmentId: string; readonly parentAmendmentId?: string }>(id: string, parentId: string | undefined, ownerId: string, values: Map<string, T>, ownerKey: keyof T): void { if (parentId === undefined) return; let cursor = values.get(parentId); const visited = new Set([id]); while (cursor !== undefined) { if (cursor[ownerKey] !== ownerId) fail(HistoricalPatternErrorCategory.InvalidReference, "amendment parent belongs to another record."); if (visited.has(cursor.amendmentId)) fail(HistoricalPatternErrorCategory.InvalidReference, "cyclic amendment chain is forbidden."); visited.add(cursor.amendmentId); cursor = cursor.parentAmendmentId === undefined ? undefined : values.get(cursor.parentAmendmentId); } if (!values.has(parentId)) fail(HistoricalPatternErrorCategory.InvalidReference, "amendment parent does not exist."); }
  private relatedEventCycle(id: string, related: ReadonlyArray<string>): boolean { return this.graphCycle(id, related, (next) => this.currentEvents.get(next)?.relatedEventIds ?? []); }
  private relatedPatternCycle(id: string, related: ReadonlyArray<string>): boolean { return this.graphCycle(id, related, (next) => this.currentPatterns.get(next)?.relatedPatternIds ?? []); }
  private graphCycle(id: string, related: ReadonlyArray<string>, edges: (id: string) => ReadonlyArray<string>): boolean { const visit = (node: string, seen: Set<string>): boolean => { if (node === id) return true; if (seen.has(node)) return false; const next = new Set(seen); next.add(node); return edges(node).some((child) => visit(child, next)); }; return related.some((node) => visit(node, new Set())); }
}
