import {
  StrategyAppendStatus, StrategyApprovalDecision, StrategyErrorCategory, StrategyStatus,
  canonicalizeStrategyValue, compareStrategyVersions, strategyFingerprint,
  throwIfInvalidStrategy, validateStrategyActivation, validateStrategyApproval,
  validateStrategyDefinition, validateStrategyHistory, validateStrategyPerformance,
  validateStrategyQuery, validateStrategyRetirement, validateStrategySuspension,
  validateStrategyValidationResult, validateStrategyVersion, validateStrategyVersionLineage,
  type StrategyActivation, type StrategyAppendResult, type StrategyApproval,
  type StrategyDefinition, type StrategyHistory, type StrategyHistoryBundle,
  type StrategyPerformanceSummary, type StrategyQuery, type StrategyRetirement,
  type StrategySuspension, type StrategyValidationResult, type StrategyVersion,
} from "../contracts";
import { matchesStrategyQuery, type StrategyRepository, type StrategyRepositoryEvent } from "./StrategyVersionRepository";

const clone = <T>(value: T): T => structuredClone(value);
function fail(category: StrategyErrorCategory, message: string): never { throw new Error(`${category}: ${message}`); }
type EventInput = StrategyRepositoryEvent extends infer T ? T extends StrategyRepositoryEvent ? Omit<T, "sequence" | "fingerprint"> : never : never;

export class InMemoryStrategyRepository implements StrategyRepository {
  private readonly definitions = new Map<string, StrategyDefinition>(); private readonly definitionSequences = new Map<string, number>();
  private readonly originalVersions = new Map<string, StrategyVersion>(); private readonly currentVersions = new Map<string, StrategyVersion>(); private readonly versionSequences = new Map<string, number>();
  private readonly validations = new Map<string, StrategyValidationResult>(); private readonly validationSequences = new Map<string, number>();
  private readonly approvals = new Map<string, StrategyApproval>(); private readonly approvalSequences = new Map<string, number>();
  private readonly activations = new Map<string, StrategyActivation>(); private readonly activationSequences = new Map<string, number>();
  private readonly suspensions = new Map<string, StrategySuspension>(); private readonly suspensionSequences = new Map<string, number>();
  private readonly retirements = new Map<string, StrategyRetirement>(); private readonly retirementSequences = new Map<string, number>();
  private readonly performance = new Map<string, StrategyPerformanceSummary>(); private readonly performanceSequences = new Map<string, number>();
  private readonly historySequences = new Map<string, number>(); private readonly archiveSequences = new Map<string, number>();
  private readonly events: StrategyRepositoryEvent[] = [];

  constructor(seedEvents: ReadonlyArray<StrategyRepositoryEvent> = []) { for (const event of seedEvents) this.applySeed(clone(event)); }
  protected persistEvent(_event: Readonly<StrategyRepositoryEvent>): void {}
  private nextSequence(): number { const value = this.events.length + 1; if (!Number.isSafeInteger(value)) fail(StrategyErrorCategory.RepositoryCorrupt, "repository sequence overflow."); return value; }
  private makeEvent<T extends EventInput>(input: T): T & Pick<StrategyRepositoryEvent, "sequence" | "fingerprint"> { const withSequence = { ...input, sequence: this.nextSequence() }; return { ...withSequence, fingerprint: strategyFingerprint({ ...withSequence, fingerprint: undefined }) } as T & Pick<StrategyRepositoryEvent, "sequence" | "fingerprint">; }
  private commit(event: StrategyRepositoryEvent, persist: boolean): void { if (event.sequence !== this.nextSequence()) fail(StrategyErrorCategory.RepositoryCorrupt, "repository sequence is not contiguous."); if (event.fingerprint !== strategyFingerprint({ ...event, fingerprint: undefined })) fail(StrategyErrorCategory.RepositoryCorrupt, "event fingerprint is invalid."); if (persist) this.persistEvent(clone(event)); this.events.push(clone(event)); }
  private applySeed(event: StrategyRepositoryEvent): void { switch (event.eventType) { case "DEFINITION_APPENDED": this.applyDefinition(event.definition, event.acceptedAt, event, false); break; case "VERSION_PROPOSED": this.applyVersion(event.version, event.acceptedAt, event, false); break; case "VALIDATION_STARTED": this.applyValidationStart(event.history, event.acceptedAt, event, false); break; case "VALIDATION_APPENDED": this.applyValidation(event.validation, event.acceptedAt, event, false); break; case "APPROVAL_APPENDED": this.applyApproval(event.approval, event.history, event.acceptedAt, event, false); break; case "ACTIVATION_APPENDED": this.applyActivation(event.activation, event.history, event.acceptedAt, event, false); break; case "SUSPENSION_APPENDED": this.applySuspension(event.suspension, event.history, event.acceptedAt, event, false); break; case "RETIREMENT_APPENDED": this.applyRetirement(event.retirement, event.history, event.acceptedAt, event, false); break; case "PERFORMANCE_APPENDED": this.applyPerformance(event.performance, event.acceptedAt, event, false); break; case "VERSION_ARCHIVED": this.applyArchive(event.history, event.acceptedAt, event, false); break; default: fail(StrategyErrorCategory.RepositoryCorrupt, "unsupported strategy event type."); } }

  appendDefinition(definition: StrategyDefinition, acceptedAt: string): StrategyAppendResult<StrategyDefinition> { const existing = this.definitions.get(definition.definitionId); if (existing !== undefined) { if (canonicalizeStrategyValue(existing) === canonicalizeStrategyValue(definition)) return { status: StrategyAppendStatus.Replayed, record: clone(existing), repositorySequence: this.definitionSequences.get(definition.definitionId) as number }; fail(StrategyErrorCategory.IdempotencyConflict, "definition ID conflict."); } const event = this.makeEvent({ schemaVersion: "1.0", eventType: "DEFINITION_APPENDED", acceptedAt, definition: clone(definition) }); return this.applyDefinition(definition, acceptedAt, event, true); }
  private applyDefinition(definition: StrategyDefinition, acceptedAt: string, event: Extract<StrategyRepositoryEvent, { eventType: "DEFINITION_APPENDED" }>, persist: boolean): StrategyAppendResult<StrategyDefinition> { if (this.definitions.has(definition.definitionId)) fail(StrategyErrorCategory.RepositoryCorrupt, "duplicate definition in history."); throwIfInvalidStrategy(validateStrategyDefinition(definition, acceptedAt)); this.commit(event, persist); this.definitions.set(definition.definitionId, clone(definition)); this.definitionSequences.set(definition.definitionId, event.sequence); return { status: StrategyAppendStatus.Appended, record: clone(definition), repositorySequence: event.sequence }; }

  appendVersion(version: StrategyVersion, acceptedAt: string): StrategyAppendResult<StrategyVersion> { const existing = this.originalVersions.get(version.versionId); if (existing !== undefined) { if (canonicalizeStrategyValue(existing) === canonicalizeStrategyValue(version)) return { status: StrategyAppendStatus.Replayed, record: clone(existing), repositorySequence: this.versionSequences.get(version.versionId) as number }; fail(StrategyErrorCategory.IdempotencyConflict, "version ID conflict."); } const event = this.makeEvent({ schemaVersion: "1.0", eventType: "VERSION_PROPOSED", acceptedAt, version: clone(version) }); return this.applyVersion(version, acceptedAt, event, true); }
  private applyVersion(version: StrategyVersion, acceptedAt: string, event: Extract<StrategyRepositoryEvent, { eventType: "VERSION_PROPOSED" }>, persist: boolean): StrategyAppendResult<StrategyVersion> { if (this.originalVersions.has(version.versionId)) fail(StrategyErrorCategory.RepositoryCorrupt, "duplicate version in history."); const definition = this.definitions.get(version.definitionId); if (definition === undefined) fail(StrategyErrorCategory.DefinitionNotFound, "version requires an existing definition."); const prior = this.getLatestVersion(version.definitionId); throwIfInvalidStrategy(validateStrategyVersion(version, acceptedAt)); throwIfInvalidStrategy(validateStrategyVersionLineage(version, definition, prior)); if (this.listVersions(version.definitionId).some((value) => value.semanticVersion === version.semanticVersion)) fail(StrategyErrorCategory.DuplicateId, "semantic version already exists in this definition."); if (version.rollbackReference !== undefined) { const trusted = this.currentVersions.get(version.rollbackReference.trustedVersionId); const failed = this.currentVersions.get(version.rollbackReference.failedVersionId); if (trusted === undefined || failed === undefined || trusted.definitionId !== version.definitionId || failed.definitionId !== version.definitionId) fail(StrategyErrorCategory.InvalidLineage, "rollback references must exist in the same definition."); }
    const visited = new Set<string>([version.versionId]); let cursor = prior; while (cursor !== undefined) { if (visited.has(cursor.versionId)) fail(StrategyErrorCategory.InvalidLineage, "cyclic version lineage is forbidden."); visited.add(cursor.versionId); cursor = cursor.priorVersionId === undefined ? undefined : this.currentVersions.get(cursor.priorVersionId); }
    this.commit(event, persist); this.originalVersions.set(version.versionId, clone(version)); this.currentVersions.set(version.versionId, clone(version)); this.versionSequences.set(version.versionId, event.sequence); return { status: StrategyAppendStatus.Appended, record: clone(version), repositorySequence: event.sequence }; }

  appendValidationStart(history: StrategyHistory, acceptedAt: string): StrategyAppendResult<StrategyHistory> { const existingSequence = this.historySequences.get(history.historyId); if (existingSequence !== undefined) { const existing = this.currentVersions.get(history.versionId)?.history.find((value) => value.historyId === history.historyId); if (existing !== undefined && canonicalizeStrategyValue(existing) === canonicalizeStrategyValue(history)) return { status: StrategyAppendStatus.Replayed, record: clone(existing), repositorySequence: existingSequence }; fail(StrategyErrorCategory.IdempotencyConflict, "validation-start history conflict."); } const event = this.makeEvent({ schemaVersion: "1.0", eventType: "VALIDATION_STARTED", acceptedAt, history: clone(history) }); return this.applyValidationStart(history, acceptedAt, event, true); }
  private applyValidationStart(history: StrategyHistory, acceptedAt: string, event: Extract<StrategyRepositoryEvent, { eventType: "VALIDATION_STARTED" }>, persist: boolean): StrategyAppendResult<StrategyHistory> { const version = this.currentVersions.get(history.versionId); if (version === undefined) fail(StrategyErrorCategory.VersionNotFound, "validation start requires an existing version."); throwIfInvalidStrategy(validateStrategyHistory(history, version, acceptedAt)); if (history.toStatus !== StrategyStatus.Validating) fail(StrategyErrorCategory.InvalidLifecycle, "validation start must transition to VALIDATING."); this.commit(event, persist); this.historySequences.set(history.historyId, event.sequence); this.advance(version, history); return { status: StrategyAppendStatus.Appended, record: clone(history), repositorySequence: event.sequence }; }

  appendValidation(value: StrategyValidationResult, acceptedAt: string): StrategyAppendResult<StrategyValidationResult> { const replay = this.replay(this.validations, this.validationSequences, value.validationId, value, "validation"); if (replay !== undefined) return replay; const event = this.makeEvent({ schemaVersion: "1.0", eventType: "VALIDATION_APPENDED", acceptedAt, validation: clone(value) }); return this.applyValidation(value, acceptedAt, event, true); }
  private applyValidation(value: StrategyValidationResult, acceptedAt: string, event: Extract<StrategyRepositoryEvent, { eventType: "VALIDATION_APPENDED" }>, persist: boolean): StrategyAppendResult<StrategyValidationResult> { if (this.validations.has(value.validationId)) fail(StrategyErrorCategory.RepositoryCorrupt, "duplicate validation in history."); const version = this.currentVersions.get(value.versionId); if (version === undefined) fail(StrategyErrorCategory.VersionNotFound, "validation requires an existing version."); throwIfInvalidStrategy(validateStrategyValidationResult(value, version, acceptedAt)); this.commit(event, persist); this.validations.set(value.validationId, clone(value)); this.validationSequences.set(value.validationId, event.sequence); return { status: StrategyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }

  appendApproval(value: StrategyApproval, history: StrategyHistory, acceptedAt: string): StrategyAppendResult<StrategyApproval> { const replay = this.replay(this.approvals, this.approvalSequences, value.approvalId, value, "approval"); if (replay !== undefined) return replay; const event = this.makeEvent({ schemaVersion: "1.0", eventType: "APPROVAL_APPENDED", acceptedAt, approval: clone(value), history: clone(history) }); return this.applyApproval(value, history, acceptedAt, event, true); }
  private applyApproval(value: StrategyApproval, history: StrategyHistory, acceptedAt: string, event: Extract<StrategyRepositoryEvent, { eventType: "APPROVAL_APPENDED" }>, persist: boolean): StrategyAppendResult<StrategyApproval> { if (this.approvals.has(value.approvalId) || this.getLatestApproval(value.versionId) !== undefined) fail(StrategyErrorCategory.DuplicateId, "version already has an approval decision or ID is duplicated."); const version = this.currentVersions.get(value.versionId); if (version === undefined) fail(StrategyErrorCategory.VersionNotFound, "approval requires existing version."); throwIfInvalidStrategy(validateStrategyApproval(value, version, this.listValidations(value.versionId), acceptedAt)); throwIfInvalidStrategy(validateStrategyHistory(history, version, acceptedAt)); const expected = value.decision === StrategyApprovalDecision.Approved ? StrategyStatus.Approved : StrategyStatus.Rejected; if (history.toStatus !== expected || history.referenceId !== value.approvalId) fail(StrategyErrorCategory.InvalidLifecycle, "approval history is invalid."); this.commit(event, persist); this.approvals.set(value.approvalId, clone(value)); this.approvalSequences.set(value.approvalId, event.sequence); this.historySequences.set(history.historyId, event.sequence); this.advance(version, history); return { status: StrategyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }

  appendActivation(value: StrategyActivation, history: StrategyHistory, acceptedAt: string): StrategyAppendResult<StrategyActivation> { const replay = this.replay(this.activations, this.activationSequences, value.activationId, value, "activation"); if (replay !== undefined) return replay; const event = this.makeEvent({ schemaVersion: "1.0", eventType: "ACTIVATION_APPENDED", acceptedAt, activation: clone(value), history: clone(history) }); return this.applyActivation(value, history, acceptedAt, event, true); }
  private applyActivation(value: StrategyActivation, history: StrategyHistory, acceptedAt: string, event: Extract<StrategyRepositoryEvent, { eventType: "ACTIVATION_APPENDED" }>, persist: boolean): StrategyAppendResult<StrategyActivation> { if (this.activations.has(value.activationId)) fail(StrategyErrorCategory.RepositoryCorrupt, "duplicate activation."); const version = this.currentVersions.get(value.versionId); if (version === undefined) fail(StrategyErrorCategory.VersionNotFound, "activation requires existing version."); const active = this.getCurrentActiveVersion(version.definitionId); if (active !== undefined && active.versionId !== version.versionId) fail(StrategyErrorCategory.ActiveVersionConflict, "definition already has an active version."); throwIfInvalidStrategy(validateStrategyActivation(value, version, this.getLatestApproval(value.versionId), this.listValidations(value.versionId), acceptedAt)); throwIfInvalidStrategy(validateStrategyHistory(history, version, acceptedAt)); if (history.toStatus !== StrategyStatus.Active || history.referenceId !== value.activationId) fail(StrategyErrorCategory.InvalidLifecycle, "activation history is invalid."); this.commit(event, persist); this.activations.set(value.activationId, clone(value)); this.activationSequences.set(value.activationId, event.sequence); this.historySequences.set(history.historyId, event.sequence); this.advance(version, history); return { status: StrategyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }

  appendSuspension(value: StrategySuspension, history: StrategyHistory, acceptedAt: string): StrategyAppendResult<StrategySuspension> { const replay = this.replay(this.suspensions, this.suspensionSequences, value.suspensionId, value, "suspension"); if (replay !== undefined) return replay; const event = this.makeEvent({ schemaVersion: "1.0", eventType: "SUSPENSION_APPENDED", acceptedAt, suspension: clone(value), history: clone(history) }); return this.applySuspension(value, history, acceptedAt, event, true); }
  private applySuspension(value: StrategySuspension, history: StrategyHistory, acceptedAt: string, event: Extract<StrategyRepositoryEvent, { eventType: "SUSPENSION_APPENDED" }>, persist: boolean): StrategyAppendResult<StrategySuspension> { if (this.suspensions.has(value.suspensionId)) fail(StrategyErrorCategory.RepositoryCorrupt, "duplicate suspension."); const version = this.currentVersions.get(value.versionId); if (version === undefined) fail(StrategyErrorCategory.VersionNotFound, "suspension requires existing version."); throwIfInvalidStrategy(validateStrategySuspension(value, version, acceptedAt)); throwIfInvalidStrategy(validateStrategyHistory(history, version, acceptedAt)); if (history.toStatus !== StrategyStatus.Suspended || history.referenceId !== value.suspensionId) fail(StrategyErrorCategory.InvalidLifecycle, "suspension history is invalid."); this.commit(event, persist); this.suspensions.set(value.suspensionId, clone(value)); this.suspensionSequences.set(value.suspensionId, event.sequence); this.historySequences.set(history.historyId, event.sequence); this.advance(version, history); return { status: StrategyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }

  appendRetirement(value: StrategyRetirement, history: StrategyHistory, acceptedAt: string): StrategyAppendResult<StrategyRetirement> { const replay = this.replay(this.retirements, this.retirementSequences, value.retirementId, value, "retirement"); if (replay !== undefined) return replay; const event = this.makeEvent({ schemaVersion: "1.0", eventType: "RETIREMENT_APPENDED", acceptedAt, retirement: clone(value), history: clone(history) }); return this.applyRetirement(value, history, acceptedAt, event, true); }
  private applyRetirement(value: StrategyRetirement, history: StrategyHistory, acceptedAt: string, event: Extract<StrategyRepositoryEvent, { eventType: "RETIREMENT_APPENDED" }>, persist: boolean): StrategyAppendResult<StrategyRetirement> { if (this.retirements.has(value.retirementId)) fail(StrategyErrorCategory.RepositoryCorrupt, "duplicate retirement."); const version = this.currentVersions.get(value.versionId); if (version === undefined) fail(StrategyErrorCategory.VersionNotFound, "retirement requires existing version."); throwIfInvalidStrategy(validateStrategyRetirement(value, version, acceptedAt)); throwIfInvalidStrategy(validateStrategyHistory(history, version, acceptedAt)); if (history.toStatus !== StrategyStatus.Retired || history.referenceId !== value.retirementId) fail(StrategyErrorCategory.InvalidLifecycle, "retirement history is invalid."); this.commit(event, persist); this.retirements.set(value.retirementId, clone(value)); this.retirementSequences.set(value.retirementId, event.sequence); this.historySequences.set(history.historyId, event.sequence); this.advance(version, history); return { status: StrategyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }

  appendPerformance(value: StrategyPerformanceSummary, acceptedAt: string): StrategyAppendResult<StrategyPerformanceSummary> { const replay = this.replay(this.performance, this.performanceSequences, value.performanceId, value, "performance"); if (replay !== undefined) return replay; const event = this.makeEvent({ schemaVersion: "1.0", eventType: "PERFORMANCE_APPENDED", acceptedAt, performance: clone(value) }); return this.applyPerformance(value, acceptedAt, event, true); }
  private applyPerformance(value: StrategyPerformanceSummary, acceptedAt: string, event: Extract<StrategyRepositoryEvent, { eventType: "PERFORMANCE_APPENDED" }>, persist: boolean): StrategyAppendResult<StrategyPerformanceSummary> { if (this.performance.has(value.performanceId)) fail(StrategyErrorCategory.RepositoryCorrupt, "duplicate performance record."); const version = this.currentVersions.get(value.versionId); if (version === undefined) fail(StrategyErrorCategory.VersionNotFound, "performance requires existing version."); throwIfInvalidStrategy(validateStrategyPerformance(value, version, acceptedAt)); this.commit(event, persist); this.performance.set(value.performanceId, clone(value)); this.performanceSequences.set(value.performanceId, event.sequence); return { status: StrategyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }

  appendArchive(history: StrategyHistory, acceptedAt: string): StrategyAppendResult<StrategyHistory> { const existing = this.archiveSequences.get(history.versionId); if (existing !== undefined) { const stored = this.currentVersions.get(history.versionId)?.history.find((value) => value.toStatus === StrategyStatus.Archived); if (stored !== undefined && canonicalizeStrategyValue(stored) === canonicalizeStrategyValue(history)) return { status: StrategyAppendStatus.Replayed, record: clone(stored), repositorySequence: existing }; fail(StrategyErrorCategory.IdempotencyConflict, "archive conflict."); } const event = this.makeEvent({ schemaVersion: "1.0", eventType: "VERSION_ARCHIVED", acceptedAt, history: clone(history) }); return this.applyArchive(history, acceptedAt, event, true); }
  private applyArchive(history: StrategyHistory, acceptedAt: string, event: Extract<StrategyRepositoryEvent, { eventType: "VERSION_ARCHIVED" }>, persist: boolean): StrategyAppendResult<StrategyHistory> { const version = this.currentVersions.get(history.versionId); if (version === undefined) fail(StrategyErrorCategory.VersionNotFound, "archive requires existing version."); throwIfInvalidStrategy(validateStrategyHistory(history, version, acceptedAt)); if (history.toStatus !== StrategyStatus.Archived) fail(StrategyErrorCategory.InvalidLifecycle, "archive history is invalid."); this.commit(event, persist); this.archiveSequences.set(history.versionId, event.sequence); this.historySequences.set(history.historyId, event.sequence); this.advance(version, history); return { status: StrategyAppendStatus.Appended, record: clone(history), repositorySequence: event.sequence }; }

  private replay<T extends object>(records: Map<string, T>, sequences: Map<string, number>, id: string, value: T, label: string): StrategyAppendResult<T> | undefined { const existing = records.get(id); if (existing === undefined) return undefined; if (canonicalizeStrategyValue(existing) === canonicalizeStrategyValue(value)) return { status: StrategyAppendStatus.Replayed, record: clone(existing), repositorySequence: sequences.get(id) as number }; fail(StrategyErrorCategory.IdempotencyConflict, `${label} ID conflict.`); }
  private advance(version: StrategyVersion, history: StrategyHistory): void { this.currentVersions.set(version.versionId, { ...clone(version), status: history.toStatus, history: [...version.history.map(clone), clone(history)] }); }
  getDefinition(id: string): StrategyDefinition | undefined { const value = this.definitions.get(id); return value === undefined ? undefined : clone(value); }
  getVersion(id: string): StrategyVersion | undefined { const value = this.currentVersions.get(id); return value === undefined ? undefined : clone(value); }
  getValidation(id: string): StrategyValidationResult | undefined { const value = this.validations.get(id); return value === undefined ? undefined : clone(value); }
  getApproval(id: string): StrategyApproval | undefined { const value = this.approvals.get(id); return value === undefined ? undefined : clone(value); }
  getLatestApproval(versionId: string): StrategyApproval | undefined { return [...this.approvals.values()].filter((value) => value.versionId === versionId).sort((a, b) => (this.approvalSequences.get(b.approvalId) as number) - (this.approvalSequences.get(a.approvalId) as number)).map(clone)[0]; }
  getActivation(id: string): StrategyActivation | undefined { const value = this.activations.get(id); return value === undefined ? undefined : clone(value); }
  getCurrentActiveVersion(definitionId: string): StrategyVersion | undefined { return this.listVersions(definitionId).find((value) => value.status === StrategyStatus.Active); }
  getLatestVersion(definitionId: string): StrategyVersion | undefined { return [...this.listVersions(definitionId)].sort((a, b) => compareStrategyVersions(b.semanticVersion, a.semanticVersion))[0]; }
  listDefinitions(): ReadonlyArray<StrategyDefinition> { return [...this.definitions.values()].sort((a, b) => (this.definitionSequences.get(a.definitionId) as number) - (this.definitionSequences.get(b.definitionId) as number)).map(clone); }
  listVersions(definitionId: string): ReadonlyArray<StrategyVersion> { return [...this.currentVersions.values()].filter((value) => value.definitionId === definitionId).sort((a, b) => compareStrategyVersions(a.semanticVersion, b.semanticVersion)).map(clone); }
  listValidations(versionId: string): ReadonlyArray<StrategyValidationResult> { return [...this.validations.values()].filter((value) => value.versionId === versionId).sort((a, b) => (this.validationSequences.get(a.validationId) as number) - (this.validationSequences.get(b.validationId) as number)).map(clone); }
  listPerformance(versionId: string): ReadonlyArray<StrategyPerformanceSummary> { return [...this.performance.values()].filter((value) => value.versionId === versionId).sort((a, b) => (this.performanceSequences.get(a.performanceId) as number) - (this.performanceSequences.get(b.performanceId) as number)).map(clone); }
  query(query: StrategyQuery = {}): ReadonlyArray<StrategyVersion> { throwIfInvalidStrategy(validateStrategyQuery(query)); const offset = query.offset ?? 0; return [...this.currentVersions.values()].filter((value) => matchesStrategyQuery(value, query)).sort((a, b) => (this.versionSequences.get(a.versionId) as number) - (this.versionSequences.get(b.versionId) as number)).slice(offset, offset + (query.limit ?? Number.MAX_SAFE_INTEGER)).map(clone); }
  getStrategyHistory(definitionId: string): StrategyHistoryBundle | undefined {
    const definition = this.getDefinition(definitionId); if (definition === undefined) return undefined;
    const versions = this.listVersions(definitionId); const ids = new Set(versions.map((value) => value.versionId));
    const bySequence = <T>(values: Iterable<T>, sequences: Map<string, number>, versionId: (value: T) => string, recordId: (value: T) => string): T[] => [...values].filter((value) => ids.has(versionId(value))).sort((a, b) => (sequences.get(recordId(a)) as number) - (sequences.get(recordId(b)) as number)).map(clone);
    return { definition, versions,
      validations: bySequence(this.validations.values(), this.validationSequences, (value) => value.versionId, (value) => value.validationId),
      approvals: bySequence(this.approvals.values(), this.approvalSequences, (value) => value.versionId, (value) => value.approvalId),
      activations: bySequence(this.activations.values(), this.activationSequences, (value) => value.versionId, (value) => value.activationId),
      suspensions: bySequence(this.suspensions.values(), this.suspensionSequences, (value) => value.versionId, (value) => value.suspensionId),
      retirements: bySequence(this.retirements.values(), this.retirementSequences, (value) => value.versionId, (value) => value.retirementId),
      performance: bySequence(this.performance.values(), this.performanceSequences, (value) => value.versionId, (value) => value.performanceId)
    };
  }
  allEvents(): ReadonlyArray<StrategyRepositoryEvent> { return this.events.map(clone); }
}
