import {
  AnalogyAppendStatus,
  AnalogyQualityClassification,
  HistoricalAnalogyErrorCategory,
  HistoricalAnalogyStatus,
  canonicalizeHistoricalAnalogyValue,
  historicalAnalogyFingerprint,
  throwIfInvalidHistoricalAnalogy,
  validateAnalogyAmendment,
  validateAnalogyLifecycle,
  validateAnalogyQuery,
  validateAnalogyReview,
  validateAnalogySupersession,
  validateAnalogyWeightProfile,
  validateCurrentSituationSnapshot,
  validateHistoricalAnalogyRecord,
  validateHistoricalAnalogyRequest,
  type AnalogyAmendment,
  type AnalogyHistory,
  type AnalogyQuery,
  type AnalogyReview,
  type AnalogySupersession,
  type AnalogyWeightProfile,
  type CurrentSituationSnapshot,
  type HistoricalAnalogyAppendResult,
  type HistoricalAnalogyLifecycle,
  type HistoricalAnalogyRecord,
  type HistoricalAnalogyRepository,
  type HistoricalAnalogyRequest,
} from "../contracts";
import { compareHistoricalAnalogyRank, matchesHistoricalAnalogyQuery, type HistoricalAnalogyRepositoryEvent } from "./HistoricalAnalogyRepository";

const clone = <T>(value: T): T => structuredClone(value);
type EventInput = HistoricalAnalogyRepositoryEvent extends infer T ? T extends HistoricalAnalogyRepositoryEvent ? Omit<T, "sequence" | "fingerprint"> : never : never;
function fail(category: HistoricalAnalogyErrorCategory, message: string): never { const error = new Error(`${category}: ${message}`); Object.assign(error, { category }); throw error; }

export class InMemoryHistoricalAnalogyRepository implements HistoricalAnalogyRepository {
  private readonly requestRecords = new Map<string, HistoricalAnalogyRequest>(); private readonly requestSequences = new Map<string, number>();
  private readonly snapshots = new Map<string, CurrentSituationSnapshot>(); private readonly snapshotSequences = new Map<string, number>();
  private readonly profiles = new Map<string, AnalogyWeightProfile>(); private readonly profileSequences = new Map<string, number>();
  private readonly originalAnalogies = new Map<string, HistoricalAnalogyRecord>(); private readonly currentAnalogies = new Map<string, HistoricalAnalogyRecord>(); private readonly analogySequences = new Map<string, number>();
  private readonly reviews = new Map<string, AnalogyReview>(); private readonly reviewSequences = new Map<string, number>();
  private readonly amendments = new Map<string, AnalogyAmendment>(); private readonly amendmentSequences = new Map<string, number>();
  private readonly supersessions = new Map<string, AnalogySupersession>(); private readonly supersessionSequences = new Map<string, number>(); private readonly supersessionByPrior = new Map<string, AnalogySupersession>();
  private readonly archives = new Map<string, number>(); private readonly events: HistoricalAnalogyRepositoryEvent[] = [];

  constructor(seedEvents: ReadonlyArray<HistoricalAnalogyRepositoryEvent> = []) { for (const event of seedEvents) this.applySeed(clone(event)); }
  protected persistEvent(_event: Readonly<HistoricalAnalogyRepositoryEvent>): void {}
  private nextSequence(): number { const next = this.events.length + 1; if (!Number.isSafeInteger(next)) fail(HistoricalAnalogyErrorCategory.RepositoryCorrupt, "Repository sequence overflow."); return next; }
  private envelope<T extends EventInput>(input: T): T & Pick<HistoricalAnalogyRepositoryEvent, "sequence" | "fingerprint"> { const withSequence = { ...input, sequence: this.nextSequence() }; return { ...withSequence, fingerprint: historicalAnalogyFingerprint(withSequence) } as T & Pick<HistoricalAnalogyRepositoryEvent, "sequence" | "fingerprint">; }
  private commit(event: HistoricalAnalogyRepositoryEvent, persist: boolean): void { if (event.sequence !== this.nextSequence() || event.fingerprint !== historicalAnalogyFingerprint({ ...event, fingerprint: undefined })) fail(HistoricalAnalogyErrorCategory.RepositoryCorrupt, "Repository sequence or fingerprint is invalid."); if (persist) this.persistEvent(clone(event)); this.events.push(clone(event)); }
  private key(id: string, version: string): string { return `${id}@${version}`; }
  private replay<T>(existing: T | undefined, incoming: T, sequence: number | undefined, message: string): HistoricalAnalogyAppendResult<T> { if (existing !== undefined && sequence !== undefined && canonicalizeHistoricalAnalogyValue(existing) === canonicalizeHistoricalAnalogyValue(incoming)) return { status: AnalogyAppendStatus.Replayed, record: clone(existing), repositorySequence: sequence }; fail(HistoricalAnalogyErrorCategory.IdempotencyConflict, message); }
  private applySeed(event: HistoricalAnalogyRepositoryEvent): void { switch (event.eventType) { case "REQUEST_APPENDED": this.applyRequest(event.request, event, false); break; case "SNAPSHOT_APPENDED": this.applySnapshot(event.snapshot, event, false); break; case "WEIGHT_PROFILE_APPENDED": this.applyProfile(event.profile, event, false); break; case "ANALOGY_APPENDED": this.applyAnalogy(event.analogy, event, false); break; case "REVIEW_APPENDED": this.applyReview(event.review, event.history, event, false); break; case "AMENDMENT_APPENDED": this.applyAmendment(event.amendment, event, false); break; case "SUPERSESSION_APPENDED": this.applySupersession(event.supersession, event.history, event, false); break; case "ARCHIVE_APPENDED": this.applyArchive(event.history, event, false); break; default: fail(HistoricalAnalogyErrorCategory.RepositoryCorrupt, "Unsupported repository event."); } }

  appendRequest(value: HistoricalAnalogyRequest, acceptedAt: string): HistoricalAnalogyAppendResult<HistoricalAnalogyRequest> { const existing = this.requestRecords.get(value.requestId); if (existing !== undefined) return this.replay(existing, value, this.requestSequences.get(value.requestId), "Request ID conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "REQUEST_APPENDED", acceptedAt, request: clone(value) }); return this.applyRequest(value, event, true); }
  private applyRequest(value: HistoricalAnalogyRequest, event: Extract<HistoricalAnalogyRepositoryEvent, { eventType: "REQUEST_APPENDED" }>, persist: boolean): HistoricalAnalogyAppendResult<HistoricalAnalogyRequest> { if (this.requestRecords.has(value.requestId)) fail(HistoricalAnalogyErrorCategory.RepositoryCorrupt, "Duplicate request in history."); throwIfInvalidHistoricalAnalogy(validateHistoricalAnalogyRequest(value)); this.commit(event, persist); this.requestRecords.set(value.requestId, clone(value)); this.requestSequences.set(value.requestId, event.sequence); return { status: AnalogyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }
  appendSnapshot(value: CurrentSituationSnapshot, acceptedAt: string): HistoricalAnalogyAppendResult<CurrentSituationSnapshot> { const existing = this.snapshots.get(value.snapshotId); if (existing !== undefined) return this.replay(existing, value, this.snapshotSequences.get(value.snapshotId), "Snapshot ID conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "SNAPSHOT_APPENDED", acceptedAt, snapshot: clone(value) }); return this.applySnapshot(value, event, true); }
  private applySnapshot(value: CurrentSituationSnapshot, event: Extract<HistoricalAnalogyRepositoryEvent, { eventType: "SNAPSHOT_APPENDED" }>, persist: boolean): HistoricalAnalogyAppendResult<CurrentSituationSnapshot> { if (this.snapshots.has(value.snapshotId)) fail(HistoricalAnalogyErrorCategory.RepositoryCorrupt, "Duplicate snapshot in history."); throwIfInvalidHistoricalAnalogy(validateCurrentSituationSnapshot(value, event.acceptedAt)); this.commit(event, persist); this.snapshots.set(value.snapshotId, clone(value)); this.snapshotSequences.set(value.snapshotId, event.sequence); return { status: AnalogyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }
  appendWeightProfile(value: AnalogyWeightProfile, acceptedAt: string): HistoricalAnalogyAppendResult<AnalogyWeightProfile> { const key = this.key(value.profileId, value.version); const existing = this.profiles.get(key); if (existing !== undefined) return this.replay(existing, value, this.profileSequences.get(key), "Weight profile identity conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "WEIGHT_PROFILE_APPENDED", acceptedAt, profile: clone(value) }); return this.applyProfile(value, event, true); }
  private applyProfile(value: AnalogyWeightProfile, event: Extract<HistoricalAnalogyRepositoryEvent, { eventType: "WEIGHT_PROFILE_APPENDED" }>, persist: boolean): HistoricalAnalogyAppendResult<AnalogyWeightProfile> { const key = this.key(value.profileId, value.version); if (this.profiles.has(key)) fail(HistoricalAnalogyErrorCategory.RepositoryCorrupt, "Duplicate weight profile in history."); throwIfInvalidHistoricalAnalogy(validateAnalogyWeightProfile(value)); this.commit(event, persist); this.profiles.set(key, clone(value)); this.profileSequences.set(key, event.sequence); return { status: AnalogyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }
  appendAnalogy(value: HistoricalAnalogyRecord, acceptedAt: string): HistoricalAnalogyAppendResult<HistoricalAnalogyRecord> { const existing = this.originalAnalogies.get(value.analogyId); if (existing !== undefined) return this.replay(existing, value, this.analogySequences.get(value.analogyId), "Analogy ID conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "ANALOGY_APPENDED", acceptedAt, analogy: clone(value) }); return this.applyAnalogy(value, event, true); }
  private applyAnalogy(value: HistoricalAnalogyRecord, event: Extract<HistoricalAnalogyRepositoryEvent, { eventType: "ANALOGY_APPENDED" }>, persist: boolean): HistoricalAnalogyAppendResult<HistoricalAnalogyRecord> { if (this.originalAnalogies.has(value.analogyId)) fail(HistoricalAnalogyErrorCategory.RepositoryCorrupt, "Duplicate analogy in history."); throwIfInvalidHistoricalAnalogy(validateHistoricalAnalogyRecord(value)); if (!this.requestRecords.has(value.requestId) || !this.snapshots.has(value.currentSnapshotReference.snapshotId) || !this.profiles.has(this.key(value.weightProfileReference.profileId, value.weightProfileReference.profileVersion))) fail(HistoricalAnalogyErrorCategory.InvalidReference, "Analogy frozen request, snapshot, or weight profile is missing."); this.commit(event, persist); this.originalAnalogies.set(value.analogyId, clone(value)); this.currentAnalogies.set(value.analogyId, clone(value)); this.analogySequences.set(value.analogyId, event.sequence); return { status: AnalogyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }

  appendReview(value: AnalogyReview, history: HistoricalAnalogyLifecycle, acceptedAt: string): HistoricalAnalogyAppendResult<AnalogyReview> { const existing = this.reviews.get(value.reviewId); if (existing !== undefined) return this.replay(existing, value, this.reviewSequences.get(value.reviewId), "Review ID conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "REVIEW_APPENDED", acceptedAt, review: clone(value), history: clone(history) }); return this.applyReview(value, history, event, true); }
  private applyReview(value: AnalogyReview, history: HistoricalAnalogyLifecycle, event: Extract<HistoricalAnalogyRepositoryEvent, { eventType: "REVIEW_APPENDED" }>, persist: boolean): HistoricalAnalogyAppendResult<AnalogyReview> { const current = this.currentAnalogies.get(value.analogyId); throwIfInvalidHistoricalAnalogy(validateAnalogyReview(value, current)); if (current === undefined) fail(HistoricalAnalogyErrorCategory.RecordNotFound, "Analogy not found."); if ([...this.reviews.values()].some((item) => item.analogyId === value.analogyId)) fail(HistoricalAnalogyErrorCategory.DuplicateId, "Analogy already reviewed."); throwIfInvalidHistoricalAnalogy(validateAnalogyLifecycle(history, current)); if (history.toStatus !== HistoricalAnalogyStatus.Reviewed || history.referenceId !== value.reviewId) fail(HistoricalAnalogyErrorCategory.InvalidLifecycle, "Review lifecycle evidence is invalid."); this.commit(event, persist); this.reviews.set(value.reviewId, clone(value)); this.reviewSequences.set(value.reviewId, event.sequence); this.currentAnalogies.set(value.analogyId, { ...clone(current), status: HistoricalAnalogyStatus.Reviewed, history: [...current.history.map(clone), clone(history)] }); return { status: AnalogyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }
  appendAmendment(value: AnalogyAmendment, acceptedAt: string): HistoricalAnalogyAppendResult<AnalogyAmendment> { const existing = this.amendments.get(value.amendmentId); if (existing !== undefined) return this.replay(existing, value, this.amendmentSequences.get(value.amendmentId), "Amendment ID conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "AMENDMENT_APPENDED", acceptedAt, amendment: clone(value) }); return this.applyAmendment(value, event, true); }
  private applyAmendment(value: AnalogyAmendment, event: Extract<HistoricalAnalogyRepositoryEvent, { eventType: "AMENDMENT_APPENDED" }>, persist: boolean): HistoricalAnalogyAppendResult<AnalogyAmendment> { const current = this.currentAnalogies.get(value.analogyId); throwIfInvalidHistoricalAnalogy(validateAnalogyAmendment(value, current)); this.validateAmendmentParent(value); this.commit(event, persist); this.amendments.set(value.amendmentId, clone(value)); this.amendmentSequences.set(value.amendmentId, event.sequence); return { status: AnalogyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }
  appendSupersession(value: AnalogySupersession, history: HistoricalAnalogyLifecycle, acceptedAt: string): HistoricalAnalogyAppendResult<AnalogySupersession> { const existing = this.supersessions.get(value.supersessionId); if (existing !== undefined) return this.replay(existing, value, this.supersessionSequences.get(value.supersessionId), "Supersession ID conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "SUPERSESSION_APPENDED", acceptedAt, supersession: clone(value), history: clone(history) }); return this.applySupersession(value, history, event, true); }
  private applySupersession(value: AnalogySupersession, history: HistoricalAnalogyLifecycle, event: Extract<HistoricalAnalogyRepositoryEvent, { eventType: "SUPERSESSION_APPENDED" }>, persist: boolean): HistoricalAnalogyAppendResult<AnalogySupersession> { const prior = this.currentAnalogies.get(value.priorAnalogyId); const successor = this.currentAnalogies.get(value.successorAnalogyId); throwIfInvalidHistoricalAnalogy(validateAnalogySupersession(value, prior, successor)); if (prior === undefined || successor === undefined) fail(HistoricalAnalogyErrorCategory.RecordNotFound, "Supersession analogy missing."); if (this.supersessionByPrior.has(value.priorAnalogyId)) fail(HistoricalAnalogyErrorCategory.DuplicateId, "Prior analogy already superseded."); let cursor: string | undefined = value.successorAnalogyId; const visited = new Set<string>(); while (cursor !== undefined) { if (cursor === value.priorAnalogyId) fail(HistoricalAnalogyErrorCategory.InvalidReference, "Cyclic supersession is forbidden."); if (visited.has(cursor)) fail(HistoricalAnalogyErrorCategory.InvalidReference, "Existing supersession cycle detected."); visited.add(cursor); cursor = this.supersessionByPrior.get(cursor)?.successorAnalogyId; } throwIfInvalidHistoricalAnalogy(validateAnalogyLifecycle(history, prior)); if (history.toStatus !== HistoricalAnalogyStatus.Superseded || history.referenceId !== value.supersessionId) fail(HistoricalAnalogyErrorCategory.InvalidLifecycle, "Supersession lifecycle evidence is invalid."); this.commit(event, persist); this.supersessions.set(value.supersessionId, clone(value)); this.supersessionSequences.set(value.supersessionId, event.sequence); this.supersessionByPrior.set(value.priorAnalogyId, clone(value)); this.currentAnalogies.set(value.priorAnalogyId, { ...clone(prior), status: HistoricalAnalogyStatus.Superseded, history: [...prior.history.map(clone), clone(history)] }); return { status: AnalogyAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }
  appendArchive(history: HistoricalAnalogyLifecycle, acceptedAt: string): HistoricalAnalogyAppendResult<HistoricalAnalogyLifecycle> { const existingSequence = this.archives.get(history.analogyId); if (existingSequence !== undefined) { const existing = this.currentAnalogies.get(history.analogyId)?.history.find((item) => item.toStatus === HistoricalAnalogyStatus.Archived); return this.replay(existing, history, existingSequence, "Archive conflict."); } const event = this.envelope({ schemaVersion: "1.0", eventType: "ARCHIVE_APPENDED", acceptedAt, history: clone(history) }); return this.applyArchive(history, event, true); }
  private applyArchive(history: HistoricalAnalogyLifecycle, event: Extract<HistoricalAnalogyRepositoryEvent, { eventType: "ARCHIVE_APPENDED" }>, persist: boolean): HistoricalAnalogyAppendResult<HistoricalAnalogyLifecycle> { const current = this.currentAnalogies.get(history.analogyId); if (current === undefined) fail(HistoricalAnalogyErrorCategory.RecordNotFound, "Analogy not found."); throwIfInvalidHistoricalAnalogy(validateAnalogyLifecycle(history, current)); if (history.toStatus !== HistoricalAnalogyStatus.Archived) fail(HistoricalAnalogyErrorCategory.InvalidLifecycle, "Archive status is invalid."); this.commit(event, persist); this.archives.set(history.analogyId, event.sequence); this.currentAnalogies.set(history.analogyId, { ...clone(current), status: HistoricalAnalogyStatus.Archived, history: [...current.history.map(clone), clone(history)] }); return { status: AnalogyAppendStatus.Appended, record: clone(history), repositorySequence: event.sequence }; }

  getRequestById(id: string): HistoricalAnalogyRequest | undefined { const value = this.requestRecords.get(id); return value === undefined ? undefined : clone(value); }
  getSnapshotById(id: string): CurrentSituationSnapshot | undefined { const value = this.snapshots.get(id); return value === undefined ? undefined : clone(value); }
  getWeightProfile(id: string, version: string): AnalogyWeightProfile | undefined { const value = this.profiles.get(this.key(id, version)); return value === undefined ? undefined : clone(value); }
  getAnalogyById(id: string): HistoricalAnalogyRecord | undefined { const value = this.currentAnalogies.get(id); return value === undefined ? undefined : clone(value); }
  getHistory(id: string): AnalogyHistory | undefined { const record = this.getAnalogyById(id); if (record === undefined) return undefined; return { record, lifecycle: record.history.map(clone), reviews: this.sorted(this.reviews, this.reviewSequences, (item) => item.analogyId === id), amendments: this.sorted(this.amendments, this.amendmentSequences, (item) => item.analogyId === id), supersessions: this.sorted(this.supersessions, this.supersessionSequences, (item) => item.priorAnalogyId === id || item.successorAnalogyId === id) }; }
  query(query: AnalogyQuery = {}): ReadonlyArray<HistoricalAnalogyRecord> { throwIfInvalidHistoricalAnalogy(validateAnalogyQuery(query)); const offset = query.offset ?? 0; return [...this.currentAnalogies.values()].filter((item) => matchesHistoricalAnalogyQuery(item, query)).sort((a, b) => (this.analogySequences.get(a.analogyId) as number) - (this.analogySequences.get(b.analogyId) as number)).slice(offset, offset + (query.limit ?? Number.MAX_SAFE_INTEGER)).map(clone); }
  rank(query: AnalogyQuery = {}, maximumResultCount = 10): ReadonlyArray<HistoricalAnalogyRecord> { if (!Number.isSafeInteger(maximumResultCount) || maximumResultCount <= 0 || maximumResultCount > 1000) fail(HistoricalAnalogyErrorCategory.InvalidPagination, "Rank limit must be from 1 through 1,000."); const { offset: _offset, limit: _limit, ...unpaged } = query; return this.query(unpaged).filter((item) => item.quality.eligibleForRanking && item.quality.classification !== AnalogyQualityClassification.Invalid && item.status !== HistoricalAnalogyStatus.Rejected).sort(compareHistoricalAnalogyRank).slice(0, maximumResultCount).map(clone); }
  listRequests(): ReadonlyArray<HistoricalAnalogyRequest> { return [...this.requestRecords.entries()].sort(([a], [b]) => (this.requestSequences.get(a) as number) - (this.requestSequences.get(b) as number)).map(([, item]) => clone(item)); }
  listWeightProfiles(): ReadonlyArray<AnalogyWeightProfile> { return [...this.profiles.entries()].sort(([a], [b]) => (this.profileSequences.get(a) as number) - (this.profileSequences.get(b) as number)).map(([, item]) => clone(item)); }
  allEvents(): ReadonlyArray<HistoricalAnalogyRepositoryEvent> { return this.events.map(clone); }

  private sorted<T>(values: Map<string, T>, sequences: Map<string, number>, include: (value: T) => boolean): T[] { return [...values.entries()].filter(([, value]) => include(value)).sort(([a], [b]) => (sequences.get(a) as number) - (sequences.get(b) as number)).map(([, value]) => clone(value)); }
  private validateAmendmentParent(value: AnalogyAmendment): void { if (value.parentAmendmentId === undefined) return; let cursor = this.amendments.get(value.parentAmendmentId); const visited = new Set([value.amendmentId]); while (cursor !== undefined) { if (cursor.analogyId !== value.analogyId) fail(HistoricalAnalogyErrorCategory.InvalidReference, "Amendment parent belongs to another analogy."); if (visited.has(cursor.amendmentId)) fail(HistoricalAnalogyErrorCategory.InvalidReference, "Cyclic amendment chain is forbidden."); visited.add(cursor.amendmentId); cursor = cursor.parentAmendmentId === undefined ? undefined : this.amendments.get(cursor.parentAmendmentId); } if (!this.amendments.has(value.parentAmendmentId)) fail(HistoricalAnalogyErrorCategory.InvalidReference, "Amendment parent does not exist."); }
}
