import {
  EventReplayAppendStatus,
  EventReplayErrorCategory,
  EventReplayLifecycleStatus,
  canonicalizeEventReplayValue,
  eventReplayFingerprint,
  throwIfInvalidEventReplay,
  validateReplayLifecycle,
  validateReplayQuery,
  validateReplayReview,
  validateReplaySession,
  validateReplaySupersession,
  validateReplayTimeline,
  type EventReplayAppendResult,
  type EventReplayRepository,
  type ReplayHistory,
  type ReplayLifecycleRecord,
  type ReplayQuery,
  type ReplayReview,
  type ReplaySession,
  type ReplaySupersession,
  type ReplayTimeline,
} from "../contracts";
import { matchesEventReplayQuery, type EventReplayRepositoryEvent } from "./EventReplayRepository";

const clone = <T>(value: T): T => structuredClone(value);
type EventInput = EventReplayRepositoryEvent extends infer T ? T extends EventReplayRepositoryEvent ? Omit<T, "sequence" | "fingerprint"> : never : never;
function fail(category: EventReplayErrorCategory, message: string): never { const error = new Error(`${category}: ${message}`); Object.assign(error, { category }); throw error; }

export class InMemoryEventReplayRepository implements EventReplayRepository {
  private readonly timelines = new Map<string, ReplayTimeline>(); private readonly timelineSequences = new Map<string, number>();
  private readonly originalSessions = new Map<string, ReplaySession>(); private readonly currentSessions = new Map<string, ReplaySession>(); private readonly sessionSequences = new Map<string, number>();
  private readonly reviews = new Map<string, ReplayReview>(); private readonly reviewSequences = new Map<string, number>();
  private readonly supersessions = new Map<string, ReplaySupersession>(); private readonly supersessionSequences = new Map<string, number>(); private readonly supersessionByPrior = new Map<string, ReplaySupersession>();
  private readonly archives = new Map<string, number>(); private readonly events: EventReplayRepositoryEvent[] = [];

  constructor(seedEvents: ReadonlyArray<EventReplayRepositoryEvent> = []) { for (const event of seedEvents) this.applySeed(clone(event)); }
  protected persistEvent(_event: Readonly<EventReplayRepositoryEvent>): void {}
  private nextSequence(): number { const next = this.events.length + 1; if (!Number.isSafeInteger(next)) fail(EventReplayErrorCategory.RepositoryCorrupt, "Repository sequence overflow."); return next; }
  private envelope<T extends EventInput>(input: T): T & Pick<EventReplayRepositoryEvent, "sequence" | "fingerprint"> { const withSequence = { ...input, sequence: this.nextSequence() }; return { ...withSequence, fingerprint: eventReplayFingerprint(withSequence) } as T & Pick<EventReplayRepositoryEvent, "sequence" | "fingerprint">; }
  private commit(event: EventReplayRepositoryEvent, persist: boolean): void { if (event.sequence !== this.nextSequence() || event.fingerprint !== eventReplayFingerprint({ ...event, fingerprint: undefined })) fail(EventReplayErrorCategory.RepositoryCorrupt, "Repository sequence or fingerprint is invalid."); if (persist) this.persistEvent(clone(event)); this.events.push(clone(event)); }
  private replay<T>(existing: T | undefined, incoming: T, sequence: number | undefined, message: string): EventReplayAppendResult<T> { if (existing !== undefined && sequence !== undefined && canonicalizeEventReplayValue(existing) === canonicalizeEventReplayValue(incoming)) return { status: EventReplayAppendStatus.Replayed, record: clone(existing), repositorySequence: sequence }; fail(EventReplayErrorCategory.IdempotencyConflict, message); }
  private applySeed(event: EventReplayRepositoryEvent): void { switch (event.eventType) { case "TIMELINE_APPENDED": this.applyTimeline(event.timeline, event, false); break; case "SESSION_APPENDED": this.applySession(event.session, event, false); break; case "REVIEW_APPENDED": this.applyReview(event.review, event.history, event, false); break; case "SUPERSESSION_APPENDED": this.applySupersession(event.supersession, event.history, event, false); break; case "ARCHIVE_APPENDED": this.applyArchive(event.history, event, false); break; default: fail(EventReplayErrorCategory.RepositoryCorrupt, "Unsupported replay repository event."); } }

  appendTimeline(value: ReplayTimeline, acceptedAt: string): EventReplayAppendResult<ReplayTimeline> { const existing = this.timelines.get(value.timelineId); if (existing !== undefined) return this.replay(existing, value, this.timelineSequences.get(value.timelineId), "Timeline ID conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "TIMELINE_APPENDED", acceptedAt, timeline: clone(value) }); return this.applyTimeline(value, event, true); }
  private applyTimeline(value: ReplayTimeline, event: Extract<EventReplayRepositoryEvent, { eventType: "TIMELINE_APPENDED" }>, persist: boolean): EventReplayAppendResult<ReplayTimeline> { if (this.timelines.has(value.timelineId)) fail(EventReplayErrorCategory.RepositoryCorrupt, "Duplicate timeline in history."); throwIfInvalidEventReplay(validateReplayTimeline(value)); this.commit(event, persist); this.timelines.set(value.timelineId, clone(value)); this.timelineSequences.set(value.timelineId, event.sequence); return { status: EventReplayAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }

  appendSession(value: ReplaySession, acceptedAt: string): EventReplayAppendResult<ReplaySession> { const existing = this.originalSessions.get(value.sessionId); if (existing !== undefined) return this.replay(existing, value, this.sessionSequences.get(value.sessionId), "Session ID conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "SESSION_APPENDED", acceptedAt, session: clone(value) }); return this.applySession(value, event, true); }
  private applySession(value: ReplaySession, event: Extract<EventReplayRepositoryEvent, { eventType: "SESSION_APPENDED" }>, persist: boolean): EventReplayAppendResult<ReplaySession> { if (this.originalSessions.has(value.sessionId)) fail(EventReplayErrorCategory.RepositoryCorrupt, "Duplicate session in history."); throwIfInvalidEventReplay(validateReplaySession(value)); const timeline = this.timelines.get(value.timelineReference.timelineId); if (timeline === undefined || timeline.timelineVersion !== value.timelineReference.timelineVersion) fail(EventReplayErrorCategory.InvalidReference, "Replay session references a missing or mismatched timeline."); if (value.orderedEventIds.some((id) => !timeline.events.some((eventValue) => eventValue.eventId === id)) || value.checkpointIds.some((id) => !timeline.checkpoints.some((checkpoint) => checkpoint.checkpointId === id))) fail(EventReplayErrorCategory.InvalidReference, "Replay session references timeline content that does not exist."); this.commit(event, persist); this.originalSessions.set(value.sessionId, clone(value)); this.currentSessions.set(value.sessionId, clone(value)); this.sessionSequences.set(value.sessionId, event.sequence); return { status: EventReplayAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }

  appendReview(value: ReplayReview, history: ReplayLifecycleRecord, acceptedAt: string): EventReplayAppendResult<ReplayReview> { const existing = this.reviews.get(value.reviewId); if (existing !== undefined) return this.replay(existing, value, this.reviewSequences.get(value.reviewId), "Review ID conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "REVIEW_APPENDED", acceptedAt, review: clone(value), history: clone(history) }); return this.applyReview(value, history, event, true); }
  private applyReview(value: ReplayReview, history: ReplayLifecycleRecord, event: Extract<EventReplayRepositoryEvent, { eventType: "REVIEW_APPENDED" }>, persist: boolean): EventReplayAppendResult<ReplayReview> { const current = this.currentSessions.get(value.sessionId); throwIfInvalidEventReplay(validateReplayReview(value, current)); if (current === undefined) fail(EventReplayErrorCategory.RecordNotFound, "Replay session not found."); if ([...this.reviews.values()].some((item) => item.sessionId === value.sessionId)) fail(EventReplayErrorCategory.DuplicateId, "Replay session already reviewed."); throwIfInvalidEventReplay(validateReplayLifecycle(history, current)); if (history.toStatus !== EventReplayLifecycleStatus.Reviewed || history.referenceId !== value.reviewId) fail(EventReplayErrorCategory.InvalidLifecycle, "Review lifecycle evidence is invalid."); this.commit(event, persist); this.reviews.set(value.reviewId, clone(value)); this.reviewSequences.set(value.reviewId, event.sequence); this.currentSessions.set(value.sessionId, { ...clone(current), status: EventReplayLifecycleStatus.Reviewed, history: [...current.history.map(clone), clone(history)] }); return { status: EventReplayAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }

  appendSupersession(value: ReplaySupersession, history: ReplayLifecycleRecord, acceptedAt: string): EventReplayAppendResult<ReplaySupersession> { const existing = this.supersessions.get(value.supersessionId); if (existing !== undefined) return this.replay(existing, value, this.supersessionSequences.get(value.supersessionId), "Supersession ID conflict."); const event = this.envelope({ schemaVersion: "1.0", eventType: "SUPERSESSION_APPENDED", acceptedAt, supersession: clone(value), history: clone(history) }); return this.applySupersession(value, history, event, true); }
  private applySupersession(value: ReplaySupersession, history: ReplayLifecycleRecord, event: Extract<EventReplayRepositoryEvent, { eventType: "SUPERSESSION_APPENDED" }>, persist: boolean): EventReplayAppendResult<ReplaySupersession> { const prior = this.currentSessions.get(value.priorSessionId); const successor = this.currentSessions.get(value.successorSessionId); throwIfInvalidEventReplay(validateReplaySupersession(value, prior, successor)); if (prior === undefined || successor === undefined) fail(EventReplayErrorCategory.RecordNotFound, "Supersession replay session missing."); if (this.supersessionByPrior.has(value.priorSessionId)) fail(EventReplayErrorCategory.DuplicateId, "Prior replay session already superseded."); let cursor: string | undefined = value.successorSessionId; const visited = new Set<string>(); while (cursor !== undefined) { if (cursor === value.priorSessionId) fail(EventReplayErrorCategory.InvalidReference, "Cyclic replay supersession is forbidden."); if (visited.has(cursor)) fail(EventReplayErrorCategory.InvalidReference, "Existing replay supersession cycle detected."); visited.add(cursor); cursor = this.supersessionByPrior.get(cursor)?.successorSessionId; } throwIfInvalidEventReplay(validateReplayLifecycle(history, prior)); if (history.toStatus !== EventReplayLifecycleStatus.Superseded || history.referenceId !== value.supersessionId) fail(EventReplayErrorCategory.InvalidLifecycle, "Supersession lifecycle evidence is invalid."); this.commit(event, persist); this.supersessions.set(value.supersessionId, clone(value)); this.supersessionSequences.set(value.supersessionId, event.sequence); this.supersessionByPrior.set(value.priorSessionId, clone(value)); this.currentSessions.set(value.priorSessionId, { ...clone(prior), status: EventReplayLifecycleStatus.Superseded, history: [...prior.history.map(clone), clone(history)] }); return { status: EventReplayAppendStatus.Appended, record: clone(value), repositorySequence: event.sequence }; }

  appendArchive(history: ReplayLifecycleRecord, acceptedAt: string): EventReplayAppendResult<ReplayLifecycleRecord> { const existingSequence = this.archives.get(history.sessionId); if (existingSequence !== undefined) { const existing = this.currentSessions.get(history.sessionId)?.history.find((item) => item.toStatus === EventReplayLifecycleStatus.Archived); return this.replay(existing, history, existingSequence, "Archive conflict."); } const event = this.envelope({ schemaVersion: "1.0", eventType: "ARCHIVE_APPENDED", acceptedAt, history: clone(history) }); return this.applyArchive(history, event, true); }
  private applyArchive(history: ReplayLifecycleRecord, event: Extract<EventReplayRepositoryEvent, { eventType: "ARCHIVE_APPENDED" }>, persist: boolean): EventReplayAppendResult<ReplayLifecycleRecord> { const current = this.currentSessions.get(history.sessionId); if (current === undefined) fail(EventReplayErrorCategory.RecordNotFound, "Replay session not found."); throwIfInvalidEventReplay(validateReplayLifecycle(history, current)); if (history.toStatus !== EventReplayLifecycleStatus.Archived) fail(EventReplayErrorCategory.InvalidLifecycle, "Archive status is invalid."); this.commit(event, persist); this.archives.set(history.sessionId, event.sequence); this.currentSessions.set(history.sessionId, { ...clone(current), status: EventReplayLifecycleStatus.Archived, history: [...current.history.map(clone), clone(history)] }); return { status: EventReplayAppendStatus.Appended, record: clone(history), repositorySequence: event.sequence }; }

  getTimelineById(id: string): ReplayTimeline | undefined { const value = this.timelines.get(id); return value === undefined ? undefined : clone(value); }
  getSessionById(id: string): ReplaySession | undefined { const value = this.currentSessions.get(id); return value === undefined ? undefined : clone(value); }
  getHistory(id: string): ReplayHistory | undefined { const session = this.getSessionById(id); if (session === undefined) return undefined; return { session, lifecycle: session.history.map(clone), reviews: this.sorted(this.reviews, this.reviewSequences, (item) => item.sessionId === id), supersessions: this.sorted(this.supersessions, this.supersessionSequences, (item) => item.priorSessionId === id || item.successorSessionId === id) }; }
  query(query: ReplayQuery = {}): ReadonlyArray<ReplaySession> { throwIfInvalidEventReplay(validateReplayQuery(query)); const offset = query.offset ?? 0; return [...this.currentSessions.values()].filter((item) => matchesEventReplayQuery(item, query)).sort((a, b) => (this.sessionSequences.get(a.sessionId) as number) - (this.sessionSequences.get(b.sessionId) as number)).slice(offset, offset + (query.limit ?? Number.MAX_SAFE_INTEGER)).map(clone); }
  listTimelines(): ReadonlyArray<ReplayTimeline> { return [...this.timelines.entries()].sort(([a], [b]) => (this.timelineSequences.get(a) as number) - (this.timelineSequences.get(b) as number)).map(([, item]) => clone(item)); }
  listSessions(): ReadonlyArray<ReplaySession> { return this.query(); }
  allEvents(): ReadonlyArray<EventReplayRepositoryEvent> { return this.events.map(clone); }
  private sorted<T>(values: Map<string, T>, sequences: Map<string, number>, include: (value: T) => boolean): T[] { return [...values.entries()].filter(([, value]) => include(value)).sort(([a], [b]) => (sequences.get(a) as number) - (sequences.get(b) as number)).map(([, value]) => clone(value)); }
}
