import { closeSync, existsSync, fsyncSync, mkdirSync, openSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, sep } from "node:path";
import { HistoricalAnalogyErrorCategory, canonicalizeHistoricalAnalogyValue } from "../contracts";
import { InMemoryHistoricalAnalogyRepository } from "./InMemoryHistoricalAnalogyRepository";
import type { HistoricalAnalogyRepositoryEvent } from "./HistoricalAnalogyRepository";

const STORE_ID = /^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$/;
export class HistoricalAnalogyRepositoryCorruptionError extends Error { readonly category = HistoricalAnalogyErrorCategory.RepositoryCorrupt; constructor(message: string) { super(message); this.name = "HistoricalAnalogyRepositoryCorruptionError"; } }
export class HistoricalAnalogyRepositoryPathError extends Error { readonly category = HistoricalAnalogyErrorCategory.InvalidPath; constructor(message: string) { super(message); this.name = "HistoricalAnalogyRepositoryPathError"; } }
function safePath(rootDirectory: string, storeId: string): string { if (!STORE_ID.test(storeId)) throw new HistoricalAnalogyRepositoryPathError("Invalid analogy store ID: path traversal is forbidden."); const root = resolve(rootDirectory); const file = resolve(root, `${storeId}.ndjson`); if (!file.startsWith(`${root}${sep}`)) throw new HistoricalAnalogyRepositoryPathError("Invalid analogy path: resolved path escaped root."); return file; }
function load(rootDirectory: string, storeId: string): { readonly filePath: string; readonly events: ReadonlyArray<HistoricalAnalogyRepositoryEvent> } { const filePath = safePath(rootDirectory, storeId); mkdirSync(resolve(rootDirectory), { recursive: true }); if (!existsSync(filePath)) { const descriptor = openSync(filePath, "a"); try { fsyncSync(descriptor); } finally { closeSync(descriptor); } return { filePath, events: [] }; } const content = readFileSync(filePath, "utf8"); if (content.length === 0) return { filePath, events: [] }; if (!content.endsWith("\n")) throw new HistoricalAnalogyRepositoryCorruptionError("Corrupt analogy repository: truncated final record."); const events: HistoricalAnalogyRepositoryEvent[] = []; const lines = content.slice(0, -1).split("\n"); for (let index = 0; index < lines.length; index += 1) { const line = lines[index]; if (line === undefined || line.length === 0) throw new HistoricalAnalogyRepositoryCorruptionError(`Corrupt analogy repository: empty line ${String(index + 1)}.`); let parsed: unknown; try { parsed = JSON.parse(line); } catch { throw new HistoricalAnalogyRepositoryCorruptionError(`Corrupt analogy repository: malformed JSON at line ${String(index + 1)}.`); } if (canonicalizeHistoricalAnalogyValue(parsed) !== line) throw new HistoricalAnalogyRepositoryCorruptionError(`Corrupt analogy repository: non-canonical line ${String(index + 1)}.`); const event = parsed as HistoricalAnalogyRepositoryEvent; if (event.schemaVersion !== "1.0" || event.sequence !== index + 1) throw new HistoricalAnalogyRepositoryCorruptionError(`Corrupt analogy repository: invalid envelope at line ${String(index + 1)}.`); events.push(event); } return { filePath, events }; }

export class LocalNdjsonHistoricalAnalogyRepository extends InMemoryHistoricalAnalogyRepository {
  private readonly filePath: string;
  constructor(rootDirectory: string, storeId = "historical-analogy-engine-v1") { const loaded = load(rootDirectory, storeId); super(loaded.events); this.filePath = loaded.filePath; }
  getStoragePath(): string { return this.filePath; }
  protected override persistEvent(event: Readonly<HistoricalAnalogyRepositoryEvent>): void { const descriptor = openSync(this.filePath, "a"); try { writeFileSync(descriptor, `${canonicalizeHistoricalAnalogyValue(event)}\n`); fsyncSync(descriptor); } finally { closeSync(descriptor); } }
}
