import { closeSync, existsSync, fsyncSync, mkdirSync, openSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, sep } from "node:path";
import { StrategyErrorCategory, canonicalizeStrategyValue } from "../contracts";
import { InMemoryStrategyRepository } from "./InMemoryStrategyRepository";
import type { StrategyRepositoryEvent } from "./StrategyVersionRepository";

const STORE_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$/;
export class StrategyRepositoryCorruptionError extends Error { readonly category = StrategyErrorCategory.RepositoryCorrupt; constructor(message: string) { super(message); this.name = "StrategyRepositoryCorruptionError"; } }
export class StrategyRepositoryPathError extends Error { readonly category = StrategyErrorCategory.InvalidPath; constructor(message: string) { super(message); this.name = "StrategyRepositoryPathError"; } }
function safePath(rootDirectory: string, storeId: string): string { if (!STORE_ID_PATTERN.test(storeId)) throw new StrategyRepositoryPathError("Invalid strategy store ID: path traversal is forbidden."); const root = resolve(rootDirectory); const file = resolve(root, `${storeId}.ndjson`); if (!file.startsWith(`${root}${sep}`)) throw new StrategyRepositoryPathError("Invalid strategy path: resolved path escaped root."); return file; }
function loadEvents(rootDirectory: string, storeId: string): { readonly filePath: string; readonly events: ReadonlyArray<StrategyRepositoryEvent> } { const filePath = safePath(rootDirectory, storeId); mkdirSync(resolve(rootDirectory), { recursive: true }); if (!existsSync(filePath)) { const descriptor = openSync(filePath, "a"); try { fsyncSync(descriptor); } finally { closeSync(descriptor); } return { filePath, events: [] }; } const content = readFileSync(filePath, "utf8"); if (content.length === 0) return { filePath, events: [] }; if (!content.endsWith("\n")) throw new StrategyRepositoryCorruptionError("Corrupt strategy repository: truncated final record."); const events: StrategyRepositoryEvent[] = []; const lines = content.slice(0, -1).split("\n"); for (let index = 0; index < lines.length; index += 1) { const line = lines[index]; if (line === undefined || line.length === 0) throw new StrategyRepositoryCorruptionError(`Corrupt strategy repository: empty line ${String(index + 1)}.`); let parsed: unknown; try { parsed = JSON.parse(line); } catch { throw new StrategyRepositoryCorruptionError(`Corrupt strategy repository: malformed JSON at line ${String(index + 1)}.`); } if (canonicalizeStrategyValue(parsed) !== line) throw new StrategyRepositoryCorruptionError(`Corrupt strategy repository: non-canonical line ${String(index + 1)}.`); const event = parsed as StrategyRepositoryEvent; if (event.schemaVersion !== "1.0" || event.sequence !== index + 1) throw new StrategyRepositoryCorruptionError(`Corrupt strategy repository: invalid envelope at line ${String(index + 1)}.`); events.push(event); } return { filePath, events }; }
export class LocalNdjsonStrategyRepository extends InMemoryStrategyRepository { private readonly filePath: string; constructor(rootDirectory: string, storeId = "strategy-versioning-v1") { const loaded = loadEvents(rootDirectory, storeId); super(loaded.events); this.filePath = loaded.filePath; } getStoragePath(): string { return this.filePath; } protected override persistEvent(event: Readonly<StrategyRepositoryEvent>): void { const descriptor = openSync(this.filePath, "a"); try { writeFileSync(descriptor, `${canonicalizeStrategyValue(event)}\n`); fsyncSync(descriptor); } finally { closeSync(descriptor); } } }
