import type { PersonalCandidateStatus } from "./PersonalCandidateScan";
import type { VerifiedMarketEvidenceStatus, VerifiedMarketSnapshotStatus } from "./VerifiedMarketSnapshot";

export const PERSONAL_DAILY_SCAN_SCHEMA_VERSION = "1.0" as const;
export enum PersonalDailyScanMode { DryRun = "DRY_RUN", Fixture = "FIXTURE", LiveReadonly = "LIVE_READONLY" }
export enum PersonalDailyScanIntent { Structural = "STRUCTURAL_SCAN", EventSensitive = "EVENT_SENSITIVE_SCAN", LeveragedDecision = "LEVERAGED_DECISION" }
export enum PersonalDailyScanRunStatus { Completed = "COMPLETED", Blocked = "BLOCKED", DryRun = "DRY_RUN" }
export enum PersonalDailyScanDisplayStatus { Ready = "READY", WatchTrigger = "WATCH_TRIGGER", Excluded = "EXCLUDED" }
/** A deterministic gate applied after Candidate Scan; it is not a Candidate Scan status. */
export enum PersonalDailyScanEligibilityStatus { Eligible = "ELIGIBLE", Blocked = "BLOCKED" }
/** Derived from Canonical Instrument plus approved PersonalWatchlistMapping metadata, never ticker spelling. */
export enum PersonalDailyScanInstrumentClassification { Ordinary = "ORDINARY", LeveragedLong = "LEVERAGED_LONG", LeveragedInverse = "LEVERAGED_INVERSE", Inverse = "INVERSE", AnalysisUnderlying = "ANALYSIS_UNDERLYING", Benchmark = "BENCHMARK" }
export interface PersonalDailyScanCandidateOutput { readonly candidateId: string; readonly analysisInstrument: string; readonly tradeVehicle: string; readonly tradeVehicleClassification: PersonalDailyScanInstrumentClassification; readonly internalStatus: PersonalCandidateStatus; readonly structuralStatus: PersonalCandidateStatus; readonly eligibilityStatus: PersonalDailyScanEligibilityStatus; readonly productDisplayStatus: PersonalDailyScanDisplayStatus; readonly blockingReasons: readonly string[]; readonly reasons: readonly string[]; readonly completedSessionBarValidity: "VALID" | "UNAVAILABLE"; readonly quoteFreshness: "CURRENT" | "STALE" | "UNAVAILABLE"; readonly liquidityEvidenceStatus: "SUFFICIENT" | "INSUFFICIENT" | "UNAVAILABLE"; }
export interface PersonalDailyScanOwnerOutput { readonly schemaVersion: typeof PERSONAL_DAILY_SCAN_SCHEMA_VERSION; readonly runId: string; readonly asOf: string; readonly mode: PersonalDailyScanMode; readonly intent: PersonalDailyScanIntent; readonly status: PersonalDailyScanRunStatus; readonly dataHealth: "HEALTHY" | "BLOCKED" | "DRY_RUN"; readonly snapshotStatus: VerifiedMarketSnapshotStatus | "NOT_COMPOSED"; readonly providerProvenanceStatus: VerifiedMarketEvidenceStatus; readonly benchmarkStatus: VerifiedMarketEvidenceStatus; readonly macroEvidenceStatus: VerifiedMarketEvidenceStatus; readonly volatilityEvidenceStatus: VerifiedMarketEvidenceStatus; readonly blockingReasons: readonly string[]; readonly candidates: readonly PersonalDailyScanCandidateOutput[]; readonly networkRequests: 0; readonly persistenceWrites: 0; readonly automatedExecutionAllowed: false; readonly deterministic: true; readonly readOnly: true; }
