import { AIAuditRetentionClassification } from "./AIAuditRepository";
import { PrivacyLevel } from "./AIRouter";
import {
  DEFAULT_STRATEGY_LIFECYCLE, StrategyApprovalDecision, StrategyApproverType, StrategyAuthorType,
  StrategyCategory, StrategyChangeType, StrategyErrorCategory, StrategyMetricAvailability,
  StrategyMetricGroup, StrategyReferenceResolution, StrategyReferenceType, StrategySemanticImpact,
  StrategyStatus, StrategyValidationOutcome, type StrategyActivation, type StrategyApproval,
  type StrategyChange, type StrategyDefinition, type StrategyDefinitionSnapshot, type StrategyError,
  type StrategyEvidenceReference, type StrategyHistory, type StrategyMetric, type StrategyPerformanceSummary,
  type StrategyQuery, type StrategyRetirement, type StrategySuspension, type StrategyValidation,
  type StrategyValidationResult, type StrategyVersion, type StrategyVersionSnapshot,
} from "./StrategyVersion";

const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,199}$/;
const SEMVER_PATTERN = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/;
const SECRET_KEY_PATTERN = /(api.?key|secret|password|credential|authorization|bearer|private.?key|access.?token)/i;

export function canonicalizeStrategyValue(value: unknown): string {
  if (value === null) return "null"; if (value === undefined) return '"[Undefined]"';
  if (typeof value === "number") return Number.isFinite(value) ? JSON.stringify(value) : JSON.stringify(`[${String(value)}]`);
  if (typeof value === "string" || typeof value === "boolean") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalizeStrategyValue).join(",")}]`;
  if (typeof value === "object") return `{${Object.entries(value).filter(([, entry]) => entry !== undefined).sort(([left], [right]) => left.localeCompare(right)).map(([key, entry]) => `${JSON.stringify(key)}:${canonicalizeStrategyValue(entry)}`).join(",")}}`;
  return JSON.stringify(String(value));
}
function fnv1a64(value: string): string { let hash = 0xcbf29ce484222325n; for (let index = 0; index < value.length; index += 1) { hash ^= BigInt(value.charCodeAt(index)); hash = BigInt.asUintN(64, hash * 0x100000001b3n); } return hash.toString(16).padStart(16, "0"); }
export function strategyFingerprint(value: unknown): string { return `fnv1a64:${fnv1a64(canonicalizeStrategyValue(value))}`; }
export function createStrategyDefinitionId(snapshot: StrategyDefinitionSnapshot): string { const value = snapshot as StrategyDefinitionSnapshot & Partial<Pick<StrategyDefinition, "definitionId">>; const { definitionId: _definitionId, ...identity } = value; return `strategy-definition:${fnv1a64(canonicalizeStrategyValue(identity))}`; }
export function createStrategyVersionId(snapshot: StrategyVersionSnapshot): string { const value = snapshot as StrategyVersionSnapshot & Partial<Pick<StrategyVersion, "versionId" | "status" | "history">>; const { versionId: _versionId, status: _status, history: _history, ...identity } = value; return `strategy-version:${fnv1a64(canonicalizeStrategyValue(identity))}`; }
export function createStrategyRulesetFingerprint(version: Pick<StrategyVersionSnapshot, "rules" | "parameters" | "constraints" | "risks" | "invalidationConditions">): string { return strategyFingerprint({ rules: version.rules, parameters: version.parameters, constraints: version.constraints, risks: version.risks, invalidationConditions: version.invalidationConditions }); }

export interface ParsedStrategyVersion { readonly major: number; readonly minor: number; readonly patch: number; }
export function parseStrategyVersion(value: string): ParsedStrategyVersion | undefined { const match = SEMVER_PATTERN.exec(value); if (match === null) return undefined; const major = Number(match[1]); const minor = Number(match[2]); const patch = Number(match[3]); return Number.isSafeInteger(major) && Number.isSafeInteger(minor) && Number.isSafeInteger(patch) ? { major, minor, patch } : undefined; }
export function compareStrategyVersions(left: string, right: string): number { const a = parseStrategyVersion(left); const b = parseStrategyVersion(right); if (a === undefined || b === undefined) throw new Error(`${StrategyErrorCategory.InvalidSemanticVersion}: malformed semantic version.`); return a.major - b.major || a.minor - b.minor || a.patch - b.patch; }
export function expectedNextStrategyVersion(prior: string, impact: StrategySemanticImpact): string { const parsed = parseStrategyVersion(prior); if (parsed === undefined) throw new Error(`${StrategyErrorCategory.InvalidSemanticVersion}: malformed prior semantic version.`); if (impact === StrategySemanticImpact.Major) return `${String(parsed.major + 1)}.0.0`; if (impact === StrategySemanticImpact.Minor) return `${String(parsed.major)}.${String(parsed.minor + 1)}.0`; return `${String(parsed.major)}.${String(parsed.minor)}.${String(parsed.patch + 1)}`; }

function add(errors: StrategyError[], category: StrategyErrorCategory, message: string, field?: string): void { errors.push(field === undefined ? { category, message } : { category, message, field }); }
function nonEmpty(errors: StrategyError[], field: string, value: string): void { if (typeof value !== "string" || value.trim().length === 0) add(errors, StrategyErrorCategory.InvalidRecord, `${field} must be non-empty.`, field); }
function identifier(errors: StrategyError[], field: string, value: string): void { nonEmpty(errors, field, value); if (typeof value === "string" && !ID_PATTERN.test(value)) add(errors, StrategyErrorCategory.InvalidId, `${field} contains unsupported characters.`, field); }
function timestamp(errors: StrategyError[], field: string, value: string, now: string, allowFuture = false): void { const parsed = Date.parse(value); if (!Number.isFinite(parsed) || !/(Z|[+-]\d{2}:\d{2})$/.test(value)) add(errors, StrategyErrorCategory.InvalidTimestamp, `${field} must be an ISO-8601 timestamp with timezone.`, field); else if (!allowFuture && parsed > Date.parse(now)) add(errors, StrategyErrorCategory.FutureTimestamp, `${field} cannot be in the future.`, field); }
function strings(errors: StrategyError[], field: string, values: ReadonlyArray<string>): void { if (!Array.isArray(values)) { add(errors, StrategyErrorCategory.InvalidRecord, `${field} must be an array.`); return; } for (const value of values) nonEmpty(errors, field, value); if (new Set(values).size !== values.length) add(errors, StrategyErrorCategory.DuplicateId, `${field} contains duplicates.`); }
function score(errors: StrategyError[], field: string, value: number): void { if (!Number.isFinite(value) || value < 0 || value > 100) add(errors, StrategyErrorCategory.InvalidRecord, `${field} must be between 0 and 100.`); }
function metadata(errors: StrategyError[], values: Readonly<Record<string, unknown>>): void { for (const [key, value] of Object.entries(values)) { identifier(errors, "metadata key", key); if (SECRET_KEY_PATTERN.test(key)) add(errors, StrategyErrorCategory.SecretMetadata, "secret-bearing metadata keys are prohibited.", `metadata.${key}`); if (value !== null && typeof value !== "string" && typeof value !== "boolean" && !(typeof value === "number" && Number.isSafeInteger(value))) add(errors, StrategyErrorCategory.InvalidRecord, "metadata values must be scalar and finite."); } }
function privacy(errors: StrategyError[], level: PrivacyLevel, retention: AIAuditRetentionClassification): void { if (!Object.values(PrivacyLevel).includes(level) || level === PrivacyLevel.Public) add(errors, StrategyErrorCategory.InvalidPrivacy, "strategy evidence cannot default to PUBLIC."); if (!Object.values(AIAuditRetentionClassification).includes(retention)) add(errors, StrategyErrorCategory.InvalidRecord, "retention is invalid."); }
function scope(errors: StrategyError[], value: StrategyDefinitionSnapshot["scope"]): void { strings(errors, "scope.included", value.included); strings(errors, "scope.excluded", value.excluded); strings(errors, "scope.markets", value.markets); strings(errors, "scope.assetTypes", value.assetTypes); strings(errors, "scope.capitalStages", value.capitalStages); }

function reference(errors: StrategyError[], value: StrategyEvidenceReference, field: string): void { identifier(errors, `${field}.referenceId`, value.referenceId); if (!Object.values(StrategyReferenceType).includes(value.recordType)) add(errors, StrategyErrorCategory.InvalidReference, `${field}.recordType is invalid.`); if (!Object.values(StrategyReferenceResolution).includes(value.resolution)) add(errors, StrategyErrorCategory.InvalidReference, `${field}.resolution is invalid.`); if (value.resolution === StrategyReferenceResolution.Resolved && (value.version === undefined || value.frozenStatus === undefined)) add(errors, StrategyErrorCategory.InvalidReference, "resolved evidence must freeze version and status.", field); }
function references(errors: StrategyError[], snapshot: StrategyVersionSnapshot): void {
  const groups: ReadonlyArray<readonly [string, ReadonlyArray<StrategyEvidenceReference>, StrategyReferenceType]> = [["research", snapshot.references.research, StrategyReferenceType.Research], ["predictions", snapshot.references.predictions, StrategyReferenceType.Prediction], ["journals", snapshot.references.journals, StrategyReferenceType.Journal], ["decisions", snapshot.references.decisions, StrategyReferenceType.Decision], ["risks", snapshot.references.risks, StrategyReferenceType.Risk], ["trades", snapshot.references.trades, StrategyReferenceType.Trade], ["audits", snapshot.references.audits, StrategyReferenceType.Audit], ["backtests", snapshot.references.backtests, StrategyReferenceType.Backtest], ["validations", snapshot.references.validations, StrategyReferenceType.Validation], ["eventReplay", snapshot.references.eventReplay, StrategyReferenceType.EventReplay]];
  for (const [name, values, expected] of groups) { const ids = new Set<string>(); for (const value of values) { reference(errors, value, `references.${name}`); if (value.recordType !== expected) add(errors, StrategyErrorCategory.InvalidReference, `references.${name} contains a mismatched typed reference.`); const id = `${value.referenceId}:${value.version ?? ""}`; if (ids.has(id)) add(errors, StrategyErrorCategory.InvalidReference, `references.${name} contains a duplicate reference.`); ids.add(id); } }
}

export function validateStrategyDefinitionSnapshot(snapshot: StrategyDefinitionSnapshot, now: string): StrategyValidation {
  const errors: StrategyError[] = []; if (snapshot.schemaVersion !== "1.0") add(errors, StrategyErrorCategory.InvalidRecord, "schemaVersion must be 1.0."); timestamp(errors, "createdAt", snapshot.createdAt, now); nonEmpty(errors, "title", snapshot.title); if (!Object.values(StrategyCategory).includes(snapshot.category)) add(errors, StrategyErrorCategory.InvalidRecord, "category is invalid."); identifier(errors, "ownerReference", snapshot.ownerReference); nonEmpty(errors, "objective.statement", snapshot.objective.statement); nonEmpty(errors, "objective.successMeasure", snapshot.objective.successMeasure); scope(errors, snapshot.scope); privacy(errors, snapshot.privacyLevel, snapshot.retention); strings(errors, "tags", snapshot.tags); identifier(errors, "correlationId", snapshot.correlationId); identifier(errors, "traceId", snapshot.traceId); for (const [key, value] of Object.entries(snapshot.policyVersions)) { identifier(errors, "policyVersions key", key); identifier(errors, `policyVersions.${key}`, value); } metadata(errors, snapshot.metadata); return { valid: errors.length === 0, errors };
}
export function validateStrategyDefinition(definition: StrategyDefinition, now: string): StrategyValidation { const base = validateStrategyDefinitionSnapshot(definition, now); const errors = [...base.errors]; identifier(errors, "definitionId", definition.definitionId); if (definition.definitionId !== createStrategyDefinitionId(definition)) add(errors, StrategyErrorCategory.InvalidId, "definitionId does not match deterministic content."); return { valid: errors.length === 0, errors }; }

function validateChange(errors: StrategyError[], change: StrategyChange): void { identifier(errors, "change.changeId", change.changeId); nonEmpty(errors, "change.fieldReference", change.fieldReference); nonEmpty(errors, "change.newValue", change.newValue); if (!Object.values(StrategyChangeType).includes(change.changeType)) add(errors, StrategyErrorCategory.InvalidRecord, "change type is invalid."); if (!Object.values(StrategySemanticImpact).includes(change.semanticImpact)) add(errors, StrategyErrorCategory.InvalidSemanticVersion, "semantic impact is invalid."); nonEmpty(errors, "change.reason", change.reason); nonEmpty(errors, "change.expectedEffect", change.expectedEffect); if (change.changeType === StrategyChangeType.DocumentationOnly && change.semanticImpact !== StrategySemanticImpact.Patch) add(errors, StrategyErrorCategory.InvalidSemanticVersion, "documentation-only changes require PATCH impact."); if ([StrategyChangeType.RuleRemoved, StrategyChangeType.RiskBoundaryChanged].includes(change.changeType) && change.semanticImpact !== StrategySemanticImpact.Major) add(errors, StrategyErrorCategory.InvalidSemanticVersion, "rule removal and risk-boundary changes require MAJOR impact."); if (change.semanticImpact !== StrategySemanticImpact.Patch && change.evidenceReferences.length === 0) add(errors, StrategyErrorCategory.MaterialEvidenceRequired, "material change requires evidence."); for (const value of change.evidenceReferences) reference(errors, value, "change.evidenceReferences"); }
function maxImpact(changes: ReadonlyArray<StrategyChange>): StrategySemanticImpact | undefined { const order = { [StrategySemanticImpact.Patch]: 0, [StrategySemanticImpact.Minor]: 1, [StrategySemanticImpact.Major]: 2 }; return changes.reduce<StrategySemanticImpact | undefined>((highest, change) => highest === undefined || order[change.semanticImpact] > order[highest] ? change.semanticImpact : highest, undefined); }

export function validateStrategyVersionSnapshot(snapshot: StrategyVersionSnapshot, now: string): StrategyValidation {
  const errors: StrategyError[] = []; if (snapshot.schemaVersion !== "1.0") add(errors, StrategyErrorCategory.InvalidRecord, "schemaVersion must be 1.0."); identifier(errors, "definitionId", snapshot.definitionId); if (parseStrategyVersion(snapshot.semanticVersion) === undefined) add(errors, StrategyErrorCategory.InvalidSemanticVersion, "semanticVersion must be MAJOR.MINOR.PATCH."); timestamp(errors, "createdAt", snapshot.createdAt, now); timestamp(errors, "effectiveAt", snapshot.effectiveAt, now, true); nonEmpty(errors, "title", snapshot.title); if (!Object.values(StrategyCategory).includes(snapshot.category)) add(errors, StrategyErrorCategory.InvalidRecord, "category is invalid."); nonEmpty(errors, "objective.statement", snapshot.objective.statement); nonEmpty(errors, "objective.successMeasure", snapshot.objective.successMeasure); scope(errors, snapshot.scope); nonEmpty(errors, "expectedBehavior", snapshot.expectedBehavior); strings(errors, "minimumDataRequirements", snapshot.minimumDataRequirements); strings(errors, "tags", snapshot.tags); identifier(errors, "riskPolicyReference", snapshot.riskPolicyReference); identifier(errors, "correlationId", snapshot.correlationId); identifier(errors, "traceId", snapshot.traceId); if (!Object.values(StrategyAuthorType).includes(snapshot.authorType)) add(errors, StrategyErrorCategory.InvalidRecord, "authorType is invalid."); privacy(errors, snapshot.privacyLevel, snapshot.retention); metadata(errors, snapshot.metadata); references(errors, snapshot);
  const ruleIds = new Set<string>(); for (const rule of snapshot.rules) { identifier(errors, "rules.ruleId", rule.ruleId); if (ruleIds.has(rule.ruleId)) add(errors, StrategyErrorCategory.DuplicateId, "duplicate rule ID."); ruleIds.add(rule.ruleId); nonEmpty(errors, "rules.name", rule.name); nonEmpty(errors, "rules.condition", rule.condition); nonEmpty(errors, "rules.action", rule.action); if (!Number.isSafeInteger(rule.priority) || rule.priority < 0) add(errors, StrategyErrorCategory.InvalidRecord, "rule priority must be a non-negative integer."); }
  const parameterIds = new Set<string>(); for (const parameter of snapshot.parameters) { identifier(errors, "parameters.parameterId", parameter.parameterId); if (parameterIds.has(parameter.parameterId)) add(errors, StrategyErrorCategory.DuplicateId, "duplicate parameter ID."); parameterIds.add(parameter.parameterId); nonEmpty(errors, "parameters.name", parameter.name); nonEmpty(errors, "parameters.description", parameter.description); const actual = typeof parameter.value === "string" ? "STRING" : typeof parameter.value === "number" ? "NUMBER" : "BOOLEAN"; if (actual !== parameter.valueType || (typeof parameter.value === "number" && !Number.isFinite(parameter.value))) add(errors, StrategyErrorCategory.InvalidRecord, "parameter value does not match valueType."); }
  const nestedGroups: ReadonlyArray<readonly [string, ReadonlyArray<readonly [string, unknown]>]> = [
    ["constraints", snapshot.constraints.map((value) => [value.constraintId, value])],
    ["assumptions", snapshot.assumptions.map((value) => [value.assumptionId, value])],
    ["risks", snapshot.risks.map((value) => [value.riskId, value])],
    ["invalidationConditions", snapshot.invalidationConditions.map((value) => [value.conditionId, value])]
  ];
  for (const [name, values] of nestedGroups) { const ids = new Set<string>(); for (const [id] of values) { identifier(errors, `${name}.identity`, id); if (ids.has(id)) add(errors, StrategyErrorCategory.DuplicateId, `${name} contains duplicate IDs.`); ids.add(id); } }
  for (const assumption of snapshot.assumptions) { nonEmpty(errors, "assumptions.statement", assumption.statement); score(errors, "assumptions.confidence", assumption.confidence); nonEmpty(errors, "assumptions.invalidationCondition", assumption.invalidationCondition); }
  const initial = snapshot.priorVersionId === undefined; if (initial) { if (snapshot.semanticVersion !== "1.0.0") add(errors, StrategyErrorCategory.InvalidSemanticVersion, "initial version must be 1.0.0."); if (snapshot.changeSet !== undefined || snapshot.changeReason !== undefined || snapshot.rollbackReference !== undefined) add(errors, StrategyErrorCategory.InvalidLineage, "initial version cannot contain change or rollback lineage."); } else { identifier(errors, "priorVersionId", snapshot.priorVersionId); if (snapshot.changeSet === undefined) add(errors, StrategyErrorCategory.InvalidLineage, "noninitial version requires a change set."); if (snapshot.changeReason === undefined || snapshot.changeReason.trim().length === 0) add(errors, StrategyErrorCategory.MaterialEvidenceRequired, "noninitial version requires a change reason."); }
  if (snapshot.supersedesVersionId !== undefined) { identifier(errors, "supersedesVersionId", snapshot.supersedesVersionId); if (snapshot.supersedesVersionId === snapshot.priorVersionId && snapshot.rollbackReference !== undefined) add(errors, StrategyErrorCategory.InvalidLineage, "rollback trusted version cannot be represented as direct supersession ambiguity."); }
  if (snapshot.rollbackReference !== undefined) { identifier(errors, "rollbackReference.trustedVersionId", snapshot.rollbackReference.trustedVersionId); identifier(errors, "rollbackReference.failedVersionId", snapshot.rollbackReference.failedVersionId); nonEmpty(errors, "rollbackReference.reason", snapshot.rollbackReference.reason); if (snapshot.rollbackReference.trustedVersionId === snapshot.rollbackReference.failedVersionId) add(errors, StrategyErrorCategory.InvalidLineage, "rollback trusted and failed versions must differ."); }
  if (snapshot.changeSet !== undefined) { identifier(errors, "changeSet.changeSetId", snapshot.changeSet.changeSetId); if (snapshot.changeSet.changes.length === 0) add(errors, StrategyErrorCategory.InvalidRecord, "change set cannot be empty."); const ids = new Set<string>(); for (const change of snapshot.changeSet.changes) { validateChange(errors, change); if (ids.has(change.changeId)) add(errors, StrategyErrorCategory.DuplicateId, "duplicate change ID."); ids.add(change.changeId); } if (maxImpact(snapshot.changeSet.changes) !== snapshot.changeSet.classification) add(errors, StrategyErrorCategory.InvalidSemanticVersion, "change-set classification must equal maximum semantic impact."); }
  return { valid: errors.length === 0, errors };
}

export function validateStrategyVersionLineage(snapshot: StrategyVersionSnapshot, definition: StrategyDefinition, prior: StrategyVersion | undefined): StrategyValidation { const errors: StrategyError[] = []; if (snapshot.definitionId !== definition.definitionId || snapshot.category !== definition.category) add(errors, StrategyErrorCategory.InvalidLineage, "version must belong to the referenced definition and category."); if (prior === undefined) { if (snapshot.priorVersionId !== undefined) add(errors, StrategyErrorCategory.InvalidLineage, "prior version does not exist."); } else { if (snapshot.priorVersionId !== prior.versionId || prior.definitionId !== definition.definitionId) add(errors, StrategyErrorCategory.InvalidLineage, "version must directly reference the latest version in its definition."); if (snapshot.changeSet === undefined) add(errors, StrategyErrorCategory.InvalidLineage, "change set is required."); else if (snapshot.semanticVersion !== expectedNextStrategyVersion(prior.semanticVersion, snapshot.changeSet.classification)) add(errors, StrategyErrorCategory.InvalidSemanticVersion, "semantic version increment does not match the change set."); } return { valid: errors.length === 0, errors }; }
export function validateStrategyVersion(version: StrategyVersion, now: string): StrategyValidation { const base = validateStrategyVersionSnapshot(version, now); const errors = [...base.errors]; identifier(errors, "versionId", version.versionId); if (version.versionId !== createStrategyVersionId(version)) add(errors, StrategyErrorCategory.InvalidId, "versionId does not match deterministic content."); if (version.status !== StrategyStatus.Proposed || version.history.length !== 1) add(errors, StrategyErrorCategory.InvalidLifecycle, "new authoritative version must begin PROPOSED."); const first = version.history[0]; if (first === undefined || first.versionId !== version.versionId || first.lifecycleSequence !== 1 || first.fromStatus !== StrategyStatus.Draft || first.toStatus !== StrategyStatus.Proposed) add(errors, StrategyErrorCategory.InvalidLifecycle, "initial lifecycle history is invalid."); if ([version.priorVersionId, version.supersedesVersionId, version.rollbackReference?.trustedVersionId, version.rollbackReference?.failedVersionId].some((value) => value === version.versionId)) add(errors, StrategyErrorCategory.InvalidLineage, "strategy version cannot reference itself."); return { valid: errors.length === 0, errors }; }
export function validateStrategyHistory(history: StrategyHistory, version: StrategyVersion, now: string): StrategyValidation { const errors: StrategyError[] = []; identifier(errors, "historyId", history.historyId); if (history.versionId !== version.versionId || history.lifecycleSequence !== version.history.length + 1 || history.fromStatus !== version.status || !DEFAULT_STRATEGY_LIFECYCLE.allowedTransitions[version.status].includes(history.toStatus)) add(errors, StrategyErrorCategory.InvalidLifecycle, "strategy lifecycle transition is invalid."); timestamp(errors, "history.occurredAt", history.occurredAt, now); if (Date.parse(history.occurredAt) < Date.parse(version.history.at(-1)?.occurredAt ?? version.createdAt)) add(errors, StrategyErrorCategory.InvalidLifecycle, "lifecycle timestamps cannot move backward."); nonEmpty(errors, "history.reason", history.reason); return { valid: errors.length === 0, errors }; }

function validateMetric(errors: StrategyError[], metric: StrategyMetric, group: StrategyMetricGroup): void { identifier(errors, "metric.metricId", metric.metricId); if (metric.group !== group || !Object.values(StrategyMetricGroup).includes(metric.group)) add(errors, StrategyErrorCategory.InvalidRecord, "metric group is invalid."); nonEmpty(errors, "metric.name", metric.name); if (!Object.values(StrategyMetricAvailability).includes(metric.availability)) add(errors, StrategyErrorCategory.InvalidRecord, "metric availability is invalid."); if (metric.availability === StrategyMetricAvailability.Available && (metric.value === undefined || !Number.isFinite(metric.value))) add(errors, StrategyErrorCategory.InvalidRecord, "available metric requires a finite value."); if (metric.availability !== StrategyMetricAvailability.Available && metric.value !== undefined) add(errors, StrategyErrorCategory.InvalidRecord, "missing/not-applicable metric cannot invent a value."); if (!Number.isSafeInteger(metric.sampleSize) || metric.sampleSize < 0) add(errors, StrategyErrorCategory.InvalidRecord, "metric sample size is invalid."); for (const value of metric.sourceReferences) reference(errors, value, "metric.sourceReferences"); }
export function validateStrategyValidationResult(value: StrategyValidationResult, version: StrategyVersion, now: string): StrategyValidation { const errors: StrategyError[] = []; identifier(errors, "validationId", value.validationId); if (value.versionId !== version.versionId) add(errors, StrategyErrorCategory.InvalidReference, "validation version reference does not match."); if (version.status !== StrategyStatus.Validating) add(errors, StrategyErrorCategory.InvalidLifecycle, "validation result requires VALIDATING status."); timestamp(errors, "testedAt", value.testedAt, now); nonEmpty(errors, "testType", value.testType); if (!Number.isSafeInteger(value.sampleSize) || value.sampleSize < 0) add(errors, StrategyErrorCategory.InvalidRecord, "validation sample size is invalid."); nonEmpty(errors, "period", value.period); strings(errors, "validation.assumptions", value.assumptions); strings(errors, "validation.limitations", value.limitations); if (!Object.values(StrategyValidationOutcome).includes(value.outcome)) add(errors, StrategyErrorCategory.InvalidRecord, "validation outcome is invalid."); nonEmpty(errors, "reviewer", value.reviewer); if (value.datasetReference !== undefined) reference(errors, value.datasetReference, "datasetReference"); for (const metric of value.metrics) validateMetric(errors, metric, metric.group); reference(errors, value.auditReference, "auditReference"); return { valid: errors.length === 0, errors }; }
export function validateStrategyApproval(value: StrategyApproval, version: StrategyVersion, validations: ReadonlyArray<StrategyValidationResult>, now: string): StrategyValidation { const errors: StrategyError[] = []; identifier(errors, "approvalId", value.approvalId); if (value.versionId !== version.versionId) add(errors, StrategyErrorCategory.InvalidReference, "approval version reference does not match."); if (version.status !== StrategyStatus.Validating) add(errors, StrategyErrorCategory.InvalidLifecycle, "approval requires VALIDATING status."); if (!validations.some((result) => result.outcome === StrategyValidationOutcome.Passed)) add(errors, StrategyErrorCategory.ValidationRequired, "passed validation is required before approval."); identifier(errors, "ownerReference", value.ownerReference); if (value.approverType !== StrategyApproverType.Owner) add(errors, StrategyErrorCategory.InvalidApproval, "only the owner may approve or reject strategy versions."); if (!Object.values(StrategyApprovalDecision).includes(value.decision)) add(errors, StrategyErrorCategory.InvalidApproval, "approval decision is invalid."); timestamp(errors, "decidedAt", value.decidedAt, now); if (value.expiresAt !== undefined) { timestamp(errors, "expiresAt", value.expiresAt, now, true); if (Date.parse(value.expiresAt) <= Date.parse(value.decidedAt)) add(errors, StrategyErrorCategory.InvalidApproval, "approval expiration must follow decision time."); } strings(errors, "conditions", value.conditions); nonEmpty(errors, "reason", value.reason); reference(errors, value.auditReference, "auditReference"); return { valid: errors.length === 0, errors }; }
export function validateStrategyActivation(value: StrategyActivation, version: StrategyVersion, approval: StrategyApproval | undefined, validations: ReadonlyArray<StrategyValidationResult>, now: string): StrategyValidation { const errors: StrategyError[] = []; identifier(errors, "activationId", value.activationId); if (value.versionId !== version.versionId) add(errors, StrategyErrorCategory.InvalidReference, "activation version reference does not match."); if (version.status !== StrategyStatus.Approved) add(errors, StrategyErrorCategory.InvalidLifecycle, "activation requires APPROVED status."); if (approval === undefined || approval.decision !== StrategyApprovalDecision.Approved || approval.approvalId !== value.ownerApprovalId || approval.approverType !== StrategyApproverType.Owner || approval.ownerReference !== value.ownerReference) add(errors, StrategyErrorCategory.ApprovalRequired, "valid matching owner approval is required for activation."); if (value.actorType !== StrategyApproverType.Owner) add(errors, StrategyErrorCategory.InvalidApproval, "AI and system actors cannot activate strategy versions."); if (!validations.some((result) => result.outcome === StrategyValidationOutcome.Passed)) add(errors, StrategyErrorCategory.ValidationRequired, "passed validation is required for activation."); timestamp(errors, "activatedAt", value.activatedAt, now); if (Date.parse(value.activatedAt) < Date.parse(version.effectiveAt)) add(errors, StrategyErrorCategory.InvalidLifecycle, "activation cannot precede effectiveAt."); if (approval?.expiresAt !== undefined && Date.parse(value.activatedAt) >= Date.parse(approval.expiresAt)) add(errors, StrategyErrorCategory.ApprovalRequired, "owner approval expired before activation."); identifier(errors, "ownerApprovalId", value.ownerApprovalId); identifier(errors, "ownerReference", value.ownerReference); nonEmpty(errors, "reason", value.reason); reference(errors, value.auditReference, "auditReference"); return { valid: errors.length === 0, errors }; }
export function validateStrategySuspension(value: StrategySuspension, version: StrategyVersion, now: string): StrategyValidation { const errors: StrategyError[] = []; identifier(errors, "suspensionId", value.suspensionId); if (value.versionId !== version.versionId) add(errors, StrategyErrorCategory.InvalidReference, "suspension version reference does not match."); if (version.status !== StrategyStatus.Active) add(errors, StrategyErrorCategory.InvalidLifecycle, "suspension requires ACTIVE status."); timestamp(errors, "suspendedAt", value.suspendedAt, now); nonEmpty(errors, "reason", value.reason); if (value.newPlansProhibited !== true) add(errors, StrategyErrorCategory.InvalidRecord, "suspension must prohibit new plans."); for (const evidence of value.evidenceReferences) reference(errors, evidence, "suspension.evidenceReferences"); reference(errors, value.auditReference, "auditReference"); return { valid: errors.length === 0, errors }; }
export function validateStrategyRetirement(value: StrategyRetirement, version: StrategyVersion, now: string): StrategyValidation { const errors: StrategyError[] = []; identifier(errors, "retirementId", value.retirementId); if (value.versionId !== version.versionId) add(errors, StrategyErrorCategory.InvalidReference, "retirement version reference does not match."); if (![StrategyStatus.Active, StrategyStatus.Suspended, StrategyStatus.Approved].includes(version.status)) add(errors, StrategyErrorCategory.InvalidLifecycle, "retirement requires APPROVED, ACTIVE, or SUSPENDED status."); timestamp(errors, "retiredAt", value.retiredAt, now); nonEmpty(errors, "reason", value.reason); if (value.successorVersionId !== undefined) identifier(errors, "successorVersionId", value.successorVersionId); reference(errors, value.auditReference, "auditReference"); return { valid: errors.length === 0, errors }; }
export function validateStrategyPerformance(value: StrategyPerformanceSummary, version: StrategyVersion, now: string): StrategyValidation { const errors: StrategyError[] = []; identifier(errors, "performanceId", value.performanceId); if (value.versionId !== version.versionId) add(errors, StrategyErrorCategory.InvalidReference, "performance version reference does not match."); timestamp(errors, "recordedAt", value.recordedAt, now); timestamp(errors, "periodStart", value.periodStart, now); timestamp(errors, "periodEnd", value.periodEnd, now); if (Date.parse(value.periodStart) > Date.parse(value.periodEnd)) add(errors, StrategyErrorCategory.InvalidTimestamp, "performance period is invalid."); if (!Number.isSafeInteger(value.sampleSize) || value.sampleSize < 0) add(errors, StrategyErrorCategory.InvalidRecord, "performance sample size is invalid."); for (const metric of value.predictionMetrics) validateMetric(errors, metric, StrategyMetricGroup.Prediction); for (const metric of value.tradingMetrics) validateMetric(errors, metric, StrategyMetricGroup.Trading); for (const metric of value.processMetrics) validateMetric(errors, metric, StrategyMetricGroup.Process); strings(errors, "performance.limitations", value.limitations); reference(errors, value.auditReference, "auditReference"); return { valid: errors.length === 0, errors }; }
export function validateStrategyQuery(query: StrategyQuery): StrategyValidation { const errors: StrategyError[] = []; const offset = query.offset ?? 0; const limit = query.limit ?? Number.MAX_SAFE_INTEGER; if (!Number.isSafeInteger(offset) || offset < 0 || !Number.isSafeInteger(limit) || limit <= 0) add(errors, StrategyErrorCategory.InvalidRecord, "query pagination is invalid."); const from = query.filter?.fromCreatedAt; const to = query.filter?.toCreatedAt; if (from !== undefined && !Number.isFinite(Date.parse(from))) add(errors, StrategyErrorCategory.InvalidTimestamp, "query from timestamp is invalid."); if (to !== undefined && !Number.isFinite(Date.parse(to))) add(errors, StrategyErrorCategory.InvalidTimestamp, "query to timestamp is invalid."); if (from !== undefined && to !== undefined && Date.parse(from) > Date.parse(to)) add(errors, StrategyErrorCategory.InvalidTimestamp, "query timestamp range is invalid."); return { valid: errors.length === 0, errors }; }
export function throwIfInvalidStrategy(validation: StrategyValidation): void { if (!validation.valid) { const first = validation.errors[0]; throw new Error(`${first?.category ?? StrategyErrorCategory.InvalidRecord}: ${first?.message ?? "strategy validation failed."}`); } }
