import type { AIAuditActor, AIAuditMetadata, AIAuditRecordInput, AIAuditRetentionClassification } from "./AIAuditRepository";
import type { PrivacyLevel } from "./AIRouter";

export type StrategyDefinitionId = string;
export type StrategyVersionId = string;
export type StrategyVersionNumber = string;
export type StrategyParameterValue = string | number | boolean;

export enum StrategyCategory {
  CapitalAllocation = "CAPITAL_ALLOCATION", PortfolioRisk = "PORTFOLIO_RISK", StockSelection = "STOCK_SELECTION",
  EtfSelection = "ETF_SELECTION", EventContract = "EVENT_CONTRACT", Entry = "ENTRY", Exit = "EXIT",
  TakeProfit = "TAKE_PROFIT", StopLoss = "STOP_LOSS", PositionSizing = "POSITION_SIZING", CashReserve = "CASH_RESERVE",
  Rebalancing = "REBALANCING", Catalyst = "CATALYST", Earnings = "EARNINGS", SectorRotation = "SECTOR_ROTATION",
  RelativeStrength = "RELATIVE_STRENGTH", MacroRegime = "MACRO_REGIME", Research = "RESEARCH",
  Prediction = "PREDICTION", AiRouting = "AI_ROUTING", AiCostControl = "AI_COST_CONTROL", SystemValidation = "SYSTEM_VALIDATION",
}

export enum StrategyStatus { Draft = "DRAFT", Proposed = "PROPOSED", Validating = "VALIDATING", Approved = "APPROVED", Active = "ACTIVE", Suspended = "SUSPENDED", Retired = "RETIRED", Rejected = "REJECTED", Archived = "ARCHIVED" }
export enum StrategyAuthorType { Owner = "OWNER", AlphaSubsystem = "ALPHA_SUBSYSTEM", AiAdvisory = "AI_ADVISORY", System = "SYSTEM" }
export enum StrategyApproverType { Owner = "OWNER", Ai = "AI", System = "SYSTEM" }
export enum StrategyApprovalDecision { Approved = "APPROVED", Rejected = "REJECTED" }
export enum StrategyValidationOutcome { Passed = "PASSED", Failed = "FAILED", Inconclusive = "INCONCLUSIVE" }
export enum StrategyReferenceResolution { Resolved = "RESOLVED", Unresolved = "UNRESOLVED" }
export enum StrategyReferenceType { Research = "RESEARCH", Prediction = "PREDICTION", Journal = "JOURNAL", Decision = "DECISION", Risk = "RISK", Trade = "TRADE", Audit = "AUDIT", Backtest = "BACKTEST", Validation = "VALIDATION", EventReplay = "EVENT_REPLAY" }
export enum StrategyChangeType { RuleAdded = "RULE_ADDED", RuleRemoved = "RULE_REMOVED", RuleModified = "RULE_MODIFIED", ParameterAdded = "PARAMETER_ADDED", ParameterRemoved = "PARAMETER_REMOVED", ParameterChanged = "PARAMETER_CHANGED", ConstraintChanged = "CONSTRAINT_CHANGED", RiskBoundaryChanged = "RISK_BOUNDARY_CHANGED", ScopeChanged = "SCOPE_CHANGED", EvidenceUpdated = "EVIDENCE_UPDATED", AssumptionChanged = "ASSUMPTION_CHANGED", InvalidationChanged = "INVALIDATION_CONDITION_CHANGED", DocumentationOnly = "DOCUMENTATION_ONLY" }
export enum StrategySemanticImpact { Patch = "PATCH", Minor = "MINOR", Major = "MAJOR" }
export enum StrategyAppendStatus { Appended = "APPENDED", Replayed = "REPLAYED" }
export enum StrategyMetricAvailability { Available = "AVAILABLE", Missing = "MISSING", NotApplicable = "NOT_APPLICABLE" }
export enum StrategyMetricGroup { Prediction = "PREDICTION", Trading = "TRADING", Process = "PROCESS" }
export enum StrategyExportFormat { Json = "JSON", Ndjson = "NDJSON" }
export enum StrategyExportDestination { LocalSnapshot = "LOCAL_SNAPSHOT", ExternalTransfer = "EXTERNAL_TRANSFER" }
export enum StrategyExportStatus { Exported = "EXPORTED", Rejected = "REJECTED" }
export enum StrategyComparisonClassification { None = "NONE", NonBehavioral = "NON_BEHAVIORAL", BackwardCompatible = "BACKWARD_COMPATIBLE", Incompatible = "INCOMPATIBLE" }
export enum StrategyAuditOperationType { DefinitionCreated = "STRATEGY_DEFINITION_CREATED", VersionProposed = "STRATEGY_VERSION_PROPOSED", ValidationStarted = "VALIDATION_STARTED", ValidationAppended = "VALIDATION_APPENDED", OwnerApprovalAppended = "OWNER_APPROVAL_APPENDED", StrategyActivated = "STRATEGY_ACTIVATED", StrategySuspended = "STRATEGY_SUSPENDED", StrategyRetired = "STRATEGY_RETIRED", StrategyRejected = "STRATEGY_REJECTED", ComparisonGenerated = "COMPARISON_GENERATED", RollbackVersionCreated = "ROLLBACK_VERSION_CREATED", Archived = "STRATEGY_ARCHIVED", Exported = "EXPORTED", ValidationRejected = "VALIDATION_REJECTED" }
export enum StrategyErrorCategory { InvalidRecord = "INVALID_RECORD", InvalidId = "INVALID_ID", InvalidTimestamp = "INVALID_TIMESTAMP", FutureTimestamp = "FUTURE_TIMESTAMP", DuplicateId = "DUPLICATE_ID", IdempotencyConflict = "IDEMPOTENCY_CONFLICT", DefinitionNotFound = "DEFINITION_NOT_FOUND", VersionNotFound = "VERSION_NOT_FOUND", InvalidSemanticVersion = "INVALID_SEMANTIC_VERSION", InvalidLineage = "INVALID_LINEAGE", InvalidLifecycle = "INVALID_LIFECYCLE", ValidationRequired = "VALIDATION_REQUIRED", ApprovalRequired = "APPROVAL_REQUIRED", InvalidApproval = "INVALID_APPROVAL", ActiveVersionConflict = "ACTIVE_VERSION_CONFLICT", InactiveStrategy = "INACTIVE_STRATEGY", MaterialEvidenceRequired = "MATERIAL_EVIDENCE_REQUIRED", InvalidReference = "INVALID_REFERENCE", InvalidPrivacy = "INVALID_PRIVACY", ExportRestricted = "EXPORT_RESTRICTED", SensitiveExportUnauthorized = "SENSITIVE_EXPORT_UNAUTHORIZED", SecretMetadata = "SECRET_METADATA", IncompatibleComparison = "INCOMPATIBLE_COMPARISON", RepositoryCorrupt = "REPOSITORY_CORRUPT", InvalidPath = "INVALID_PATH" }

export interface StrategyObjective { readonly statement: string; readonly successMeasure: string; }
export interface StrategyScope { readonly included: ReadonlyArray<string>; readonly excluded: ReadonlyArray<string>; readonly markets: ReadonlyArray<string>; readonly assetTypes: ReadonlyArray<string>; readonly capitalStages: ReadonlyArray<string>; }
export interface StrategyRule { readonly ruleId: string; readonly name: string; readonly condition: string; readonly action: string; readonly priority: number; readonly enabled: boolean; }
export interface StrategyParameter { readonly parameterId: string; readonly name: string; readonly value: StrategyParameterValue; readonly valueType: "STRING" | "NUMBER" | "BOOLEAN"; readonly unit?: string; readonly description: string; }
export interface StrategyConstraint { readonly constraintId: string; readonly statement: string; readonly hardConstraint: boolean; readonly policyReference?: string; }
export interface StrategyAssumption { readonly assumptionId: string; readonly statement: string; readonly confidence: number; readonly invalidationCondition: string; }
export interface StrategyRisk { readonly riskId: string; readonly statement: string; readonly boundary: string; readonly mitigation: string; }
export interface StrategyInvalidationCondition { readonly conditionId: string; readonly statement: string; readonly requiredAction: string; }

export interface StrategyEvidenceReference { readonly referenceId: string; readonly recordType: StrategyReferenceType; readonly resolution: StrategyReferenceResolution; readonly version?: string; readonly frozenStatus?: string; readonly summary?: string; }
export interface StrategyResearchReference extends StrategyEvidenceReference { readonly recordType: StrategyReferenceType.Research; }
export interface StrategyPredictionReference extends StrategyEvidenceReference { readonly recordType: StrategyReferenceType.Prediction; }
export interface StrategyJournalReference extends StrategyEvidenceReference { readonly recordType: StrategyReferenceType.Journal; }
export interface StrategyDecisionReference extends StrategyEvidenceReference { readonly recordType: StrategyReferenceType.Decision; }
export interface StrategyRiskReference extends StrategyEvidenceReference { readonly recordType: StrategyReferenceType.Risk; }
export interface StrategyTradeReference extends StrategyEvidenceReference { readonly recordType: StrategyReferenceType.Trade; }
export interface StrategyAuditReference extends StrategyEvidenceReference { readonly recordType: StrategyReferenceType.Audit; }
export interface StrategyBacktestReference extends StrategyEvidenceReference { readonly recordType: StrategyReferenceType.Backtest; }
export interface StrategyValidationReference extends StrategyEvidenceReference { readonly recordType: StrategyReferenceType.Validation; }
export interface StrategyEventReplayReference extends StrategyEvidenceReference { readonly recordType: StrategyReferenceType.EventReplay; }
export interface StrategyEvidenceGraph { readonly research: ReadonlyArray<StrategyResearchReference>; readonly predictions: ReadonlyArray<StrategyPredictionReference>; readonly journals: ReadonlyArray<StrategyJournalReference>; readonly decisions: ReadonlyArray<StrategyDecisionReference>; readonly risks: ReadonlyArray<StrategyRiskReference>; readonly trades: ReadonlyArray<StrategyTradeReference>; readonly audits: ReadonlyArray<StrategyAuditReference>; readonly backtests: ReadonlyArray<StrategyBacktestReference>; readonly validations: ReadonlyArray<StrategyValidationReference>; readonly eventReplay: ReadonlyArray<StrategyEventReplayReference>; }

export interface StrategyChange { readonly changeId: string; readonly fieldReference: string; readonly previousValue?: string; readonly newValue: string; readonly changeType: StrategyChangeType; readonly semanticImpact: StrategySemanticImpact; readonly reason: string; readonly evidenceReferences: ReadonlyArray<StrategyEvidenceReference>; readonly expectedEffect: string; readonly riskIntroduced: string; readonly reversible: boolean; readonly ownerNote: string; }
export interface StrategyChangeSet { readonly changeSetId: string; readonly classification: StrategySemanticImpact; readonly changes: ReadonlyArray<StrategyChange>; }
export interface StrategyRollbackReference { readonly trustedVersionId: StrategyVersionId; readonly failedVersionId: StrategyVersionId; readonly reason: string; }

export interface StrategyDefinitionSnapshot { readonly schemaVersion: "1.0"; readonly createdAt: string; readonly title: string; readonly category: StrategyCategory; readonly ownerReference: string; readonly objective: StrategyObjective; readonly scope: StrategyScope; readonly privacyLevel: PrivacyLevel; readonly retention: AIAuditRetentionClassification; readonly tags: ReadonlyArray<string>; readonly correlationId: string; readonly traceId: string; readonly policyVersions: Readonly<Record<string, string>>; readonly metadata: AIAuditMetadata; }
export interface StrategyDefinition extends StrategyDefinitionSnapshot { readonly definitionId: StrategyDefinitionId; }

export interface StrategyVersionSnapshot { readonly schemaVersion: "1.0"; readonly definitionId: StrategyDefinitionId; readonly semanticVersion: StrategyVersionNumber; readonly createdAt: string; readonly effectiveAt: string; readonly title: string; readonly category: StrategyCategory; readonly objective: StrategyObjective; readonly scope: StrategyScope; readonly rules: ReadonlyArray<StrategyRule>; readonly parameters: ReadonlyArray<StrategyParameter>; readonly constraints: ReadonlyArray<StrategyConstraint>; readonly assumptions: ReadonlyArray<StrategyAssumption>; readonly risks: ReadonlyArray<StrategyRisk>; readonly invalidationConditions: ReadonlyArray<StrategyInvalidationCondition>; readonly expectedBehavior: string; readonly minimumDataRequirements: ReadonlyArray<string>; readonly references: StrategyEvidenceGraph; readonly priorVersionId?: StrategyVersionId; readonly supersedesVersionId?: StrategyVersionId; readonly rollbackReference?: StrategyRollbackReference; readonly changeSet?: StrategyChangeSet; readonly changeReason?: string; readonly riskPolicyReference: string; readonly authorType: StrategyAuthorType; readonly privacyLevel: PrivacyLevel; readonly retention: AIAuditRetentionClassification; readonly tags: ReadonlyArray<string>; readonly correlationId: string; readonly traceId: string; readonly policyVersions: Readonly<Record<string, string>>; readonly metadata: AIAuditMetadata; }
export interface StrategyHistory { readonly historyId: string; readonly versionId: StrategyVersionId; readonly lifecycleSequence: number; readonly fromStatus: StrategyStatus; readonly toStatus: StrategyStatus; readonly occurredAt: string; readonly reason: string; readonly referenceId?: string; }
export interface StrategyVersion extends StrategyVersionSnapshot { readonly versionId: StrategyVersionId; readonly status: StrategyStatus; readonly history: ReadonlyArray<StrategyHistory>; }

export interface StrategyValidationResult { readonly validationId: string; readonly versionId: StrategyVersionId; readonly testType: string; readonly testedAt: string; readonly datasetReference?: StrategyEvidenceReference; readonly sampleSize: number; readonly period: string; readonly assumptions: ReadonlyArray<string>; readonly metrics: ReadonlyArray<StrategyMetric>; readonly outcome: StrategyValidationOutcome; readonly limitations: ReadonlyArray<string>; readonly reviewer: string; readonly auditReference: StrategyAuditReference; }
export interface StrategyApproval { readonly approvalId: string; readonly versionId: StrategyVersionId; readonly ownerReference: string; readonly approverType: StrategyApproverType; readonly decision: StrategyApprovalDecision; readonly decidedAt: string; readonly conditions: ReadonlyArray<string>; readonly reason: string; readonly expiresAt?: string; readonly gitOrDocumentationReference?: string; readonly auditReference: StrategyAuditReference; }
export interface StrategyActivation { readonly activationId: string; readonly versionId: StrategyVersionId; readonly activatedAt: string; readonly ownerApprovalId: string; readonly ownerReference: string; readonly actorType: StrategyApproverType.Owner; readonly reason: string; readonly auditReference: StrategyAuditReference; }
export interface StrategySuspension { readonly suspensionId: string; readonly versionId: StrategyVersionId; readonly suspendedAt: string; readonly reason: string; readonly existingPlansMayContinue: boolean; readonly newPlansProhibited: true; readonly evidenceReferences: ReadonlyArray<StrategyEvidenceReference>; readonly auditReference: StrategyAuditReference; }
export interface StrategyRetirement { readonly retirementId: string; readonly versionId: StrategyVersionId; readonly retiredAt: string; readonly reason: string; readonly successorVersionId?: StrategyVersionId; readonly auditReference: StrategyAuditReference; }

export interface StrategyMetric { readonly metricId: string; readonly group: StrategyMetricGroup; readonly name: string; readonly availability: StrategyMetricAvailability; readonly value?: number; readonly unit?: string; readonly sampleSize: number; readonly sourceReferences: ReadonlyArray<StrategyEvidenceReference>; }
export interface StrategyPerformanceSummary { readonly performanceId: string; readonly versionId: StrategyVersionId; readonly recordedAt: string; readonly periodStart: string; readonly periodEnd: string; readonly completePeriod: boolean; readonly sampleSize: number; readonly predictionMetrics: ReadonlyArray<StrategyMetric>; readonly tradingMetrics: ReadonlyArray<StrategyMetric>; readonly processMetrics: ReadonlyArray<StrategyMetric>; readonly limitations: ReadonlyArray<string>; readonly auditReference: StrategyAuditReference; }

export interface StrategyTradePlanSnapshot { readonly definitionId: StrategyDefinitionId; readonly versionId: StrategyVersionId; readonly semanticVersion: StrategyVersionNumber; readonly rulesetFingerprint: string; readonly parameters: ReadonlyArray<StrategyParameter>; readonly riskPolicyReference: string; readonly decisionTimestamp: string; readonly ownerApprovalId: string; }
export interface StrategyVersionDifference { readonly path: string; readonly before?: string; readonly after?: string; }
export interface StrategyComparison { readonly comparisonId: string; readonly definitionId: StrategyDefinitionId; readonly leftVersionId: StrategyVersionId; readonly rightVersionId: StrategyVersionId; readonly generatedAt: string; readonly added: ReadonlyArray<StrategyVersionDifference>; readonly removed: ReadonlyArray<StrategyVersionDifference>; readonly changed: ReadonlyArray<StrategyVersionDifference>; readonly behavioralClassification: StrategyComparisonClassification; readonly riskClassification: StrategyComparisonClassification; readonly evidenceChanged: boolean; readonly validationDifference: string; readonly performanceDifference: string; }

export interface StrategyFilter { readonly definitionId?: string; readonly categories?: ReadonlyArray<StrategyCategory>; readonly statuses?: ReadonlyArray<StrategyStatus>; readonly market?: string; readonly assetType?: string; readonly capitalStage?: string; readonly researchId?: string; readonly predictionId?: string; readonly journalId?: string; readonly tags?: ReadonlyArray<string>; readonly fromCreatedAt?: string; readonly toCreatedAt?: string; readonly correlationId?: string; readonly traceId?: string; readonly activeOnly?: boolean; }
export interface StrategyQuery { readonly filter?: StrategyFilter; readonly offset?: number; readonly limit?: number; }
export interface StrategyStatistics { readonly generatedAt: string; readonly definitionCount: number; readonly versionCount: number; readonly activeCount: number; readonly approvedCount: number; readonly rejectedCount: number; readonly suspendedCount: number; readonly retiredCount: number; readonly validatedCount: number; readonly validationCompletionRate: number; readonly researchLinkedCount: number; readonly predictionLinkedCount: number; readonly journalLinkedCount: number; readonly definitionsByCategory: Readonly<Partial<Record<StrategyCategory, number>>>; readonly byCategory: Readonly<Partial<Record<StrategyCategory, number>>>; readonly byStatus: Readonly<Partial<Record<StrategyStatus, number>>>; readonly versionsPerDefinition: Readonly<Record<string, number>>; readonly changeCounts: Readonly<Partial<Record<StrategySemanticImpact, number>>>; readonly performanceReferenceCounts: Readonly<Record<string, number>>; readonly performanceSampleSizes: Readonly<Record<string, number>>; }
export interface StrategyHistoryBundle { readonly definition: StrategyDefinition; readonly versions: ReadonlyArray<StrategyVersion>; readonly validations: ReadonlyArray<StrategyValidationResult>; readonly approvals: ReadonlyArray<StrategyApproval>; readonly activations: ReadonlyArray<StrategyActivation>; readonly suspensions: ReadonlyArray<StrategySuspension>; readonly retirements: ReadonlyArray<StrategyRetirement>; readonly performance: ReadonlyArray<StrategyPerformanceSummary>; }
export interface StrategyError { readonly category: StrategyErrorCategory; readonly message: string; readonly field?: string; }
export interface StrategyValidation { readonly valid: boolean; readonly errors: ReadonlyArray<StrategyError>; }
export interface StrategyAppendResult<T> { readonly status: StrategyAppendStatus; readonly record: T; readonly repositorySequence: number; }
export interface StrategyExportRequest { readonly exportId: string; readonly requestedAt: string; readonly query: StrategyQuery; readonly format: StrategyExportFormat; readonly destination: StrategyExportDestination; readonly sensitiveAuthorizationReference?: string; }
export interface StrategyExportResult { readonly status: StrategyExportStatus; readonly exportId: string; readonly exportedAt: string; readonly format: StrategyExportFormat; readonly recordCount: number; readonly content?: string; readonly error?: StrategyError; }
export interface StrategyExportPolicy { readonly allowExternalExports: boolean; readonly requireSensitiveAuthorization: boolean; readonly sensitiveAuthorizationReferences: ReadonlyArray<string>; }
export interface StrategyAuditRecord { readonly auditId: string; readonly operationType: StrategyAuditOperationType; readonly sourceRecordId: string; readonly definitionId?: string; readonly versionId?: string; readonly semanticVersion?: string; readonly ownerApprovalId?: string; readonly timestamp: string; readonly status: string; readonly reasonCodes: ReadonlyArray<string>; readonly evidenceReferences: ReadonlyArray<string>; readonly privacyLevel: PrivacyLevel; readonly retention: AIAuditRetentionClassification; readonly correlationId: string; readonly traceId: string; readonly policyVersions: Readonly<Record<string, string>>; readonly metadata: AIAuditMetadata; }
export interface StrategyAuditTranslationContext { readonly idempotencyKey: string; readonly actor: AIAuditActor; readonly parentAuditRecordIds: ReadonlyArray<string>; readonly relatedAuditRecordIds: ReadonlyArray<string>; }
export type StrategyAuditTranslation = (source: Readonly<StrategyAuditRecord>, context: Readonly<StrategyAuditTranslationContext>) => AIAuditRecordInput;

export interface StrategyLifecycle { readonly authoritativeInitialStatus: StrategyStatus.Proposed; readonly allowedTransitions: Readonly<Record<StrategyStatus, ReadonlyArray<StrategyStatus>>>; }
export const DEFAULT_STRATEGY_LIFECYCLE: StrategyLifecycle = { authoritativeInitialStatus: StrategyStatus.Proposed, allowedTransitions: { [StrategyStatus.Draft]: [StrategyStatus.Proposed], [StrategyStatus.Proposed]: [StrategyStatus.Validating], [StrategyStatus.Validating]: [StrategyStatus.Approved, StrategyStatus.Rejected], [StrategyStatus.Approved]: [StrategyStatus.Active, StrategyStatus.Retired], [StrategyStatus.Active]: [StrategyStatus.Suspended, StrategyStatus.Retired], [StrategyStatus.Suspended]: [StrategyStatus.Retired], [StrategyStatus.Retired]: [StrategyStatus.Archived], [StrategyStatus.Rejected]: [StrategyStatus.Archived], [StrategyStatus.Archived]: [] } };
