import { freezeOptionsActivityStudy as freeze, evaluateOptionsActivityStudy as evaluate } from "./OptionsActivityStudy";
import { activityStudyFixture as fixture } from "./OptionsActivityStudyFixtures";

let passed = 0;
const eq = (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw Error("VALUES_DIFFER " + JSON.stringify([a, b])); };
const ok = (a: unknown) => { if (!a) throw Error("EXPECTED_TRUE"); };
const throws = (fn: () => unknown, code: string) => { let err: unknown; try { fn(); } catch (e) { err = e; } if (!(err instanceof Error) || !err.message.includes(code)) throw Error("EXPECTED_ERROR " + code); };
function test(name: string, fn: () => void) { fn(); passed++; console.log("PASS " + name); }
const baselineAt = "2026-09-07T20:22:00.000Z", registeredAt = "2026-09-08T01:00:00.000Z", reportAt = "2026-09-09T20:22:00.000Z";
const freezeFixture = (f = fixture(), at = registeredAt) => freeze(JSON.stringify(f), baselineAt, at);
const snapshots = () => ["2026-09-08", "2026-09-09"].map(sessionDate => ({ sessionDate, sourceText: JSON.stringify(fixture(sessionDate)), assessedAt: sessionDate + "T20:22:00.000Z" }));
const run = (s = snapshots(), f = fixture(), at = reportAt) => evaluate(JSON.stringify(f), baselineAt, registeredAt, s, at);
const primary = (r = run(), n = 0, scenario = "ILLUSTRATIVE_BASE") => r.cases[n]!.outcomes.find(o => o.primary && o.costScenario === scenario)!;
function mutated(fn: (f: any) => void, index = 1) { const s = snapshots(), f = JSON.parse(s[index]!.sourceText); fn(f); s[index]!.sourceText = JSON.stringify(f); return s; }
test("all flagged cases frozen with nearest distinct controls", () => { const s = freezeFixture(); eq(s.counts, { baselineContracts: 12, candidates: 4, matched: 4, unmatched: 0 }); eq(s.candidates.map(c => c.control!.strike), ["403", "402", "403", "402"]); eq(new Set(s.candidates.map(c => c.control!.id)).size, 4); eq(s.validatedEdge, false); });
test("candidate ordering independent of source result order", () => { const f = fixture(); f.quotes[0].batches[0].response.data.results.reverse(); f.instruments[0].pages[0].response.data.instruments.reverse(); eq(freezeFixture(f).candidates, freezeFixture().candidates); });
test("same moneyness constraint may leave valid candidates unmatched", () => { const f = fixture(); f.equities.response.data.results[0].close.price = "404.5"; const s = freezeFixture(f); eq(s.candidates[1]!.control, null); eq(s.counts.candidates, 4); });
for (const [name, change] of [
  ["interpolated", (f: any) => f.equities.response.data.results[0].close.interpolated = true],
  ["wrong-date", (f: any) => f.equities.response.data.results[0].close.date = "2026-09-03"],
  ["missing", (f: any) => f.equities = null],
  ["future-receipt", (f: any) => f.equities.receivedAt = "2026-09-09 20:21:00 UTC"],
] as const) test(name + " underlying reference never invents a match", () => { const f = fixture(); change(f); eq(freezeFixture(f).candidates[0]!.control, null); });
test("controls beyond 3 percent distance excluded", () => { const f = fixture(); for (const g of f.instruments) for (const [i, c] of g.pages[0].response.data.instruments.entries()) if (i < 4) c.strike_price = String(300 + i); eq(freezeFixture(f).counts.unmatched, 4); });
test("missing peer quotes do not become below-filter controls", () => { const f = fixture(); f.quotes[0].batches[0].response.data.results.pop(); eq(freezeFixture(f).candidates[0]!.control, null); });
test("late and backdated registrations fail", () => { throws(() => freezeFixture(fixture(), "2026-09-08T19:45:00.000Z"), "REGISTRATION_CLOCK"); throws(() => freezeFixture(fixture(), "2026-09-07T20:00:00.000Z"), "REGISTRATION_CLOCK"); });
test("actual zero close reports retain all cases and unknown outcomes", () => { const r = run([], fixture(), registeredAt); eq(r.counts.primaryEvaluableCandidates, 0); eq(r.cases.length, 4); eq(r.status, "AWAITING_FUTURE_CLOSES"); eq(primary(r).candidate.reason, "ENTRY_AWAITING_SESSION_BOARD"); eq(r.executionAllowed, false); eq(r.winProbability, null); });
test("exact ask-bid costs produce a known gain and paired comparison", () => { const o = primary(); eq(o.candidate.grossReferenceChangeUsd, "8.000000"); eq(o.candidate.entryDebitUsd, "13.500000"); eq(o.candidate.netReferenceChangeUsd, "5.000000"); eq(o.candidate.netReturnBpsTruncated, 3703); eq(o.control!.netReferenceChangeUsd, "-4.000000"); eq(o.pairedDifferenceBps, 6665); eq(o.affordablePair, true); });
test("losing cases remain in outcomes and notebook", () => { const r = run(), o = primary(r, 1); eq(o.candidate.netReferenceChangeUsd, "-7.000000"); eq(o.candidate.result, "NEGATIVE"); ok(r.candidateLessons.some(l => l.code === "NEGATIVE_REFERENCE_OUTCOME")); });
test("positive gross gain erased by declared costs is recorded", () => { const r = run(mutated(f => f.quotes[0].batches[0].response.data.results[4].quote.bid_price = "0.13")); eq(primary(r).candidate.netReferenceChangeUsd, "-2.000000"); ok(r.candidateLessons.some(l => l.code === "DECLARED_COSTS_ERODE_GROSS_GAIN")); });
test("benchmark base and stress remain distinct assumptions", () => { const r = run(); eq(primary(r, 0, "SPREAD_ONLY").candidate.netReferenceChangeUsd, "8.000000"); eq(primary(r, 0, "ILLUSTRATIVE_STRESS").candidate.netReferenceChangeUsd, "2.000000"); });
test("entry after known baseline prevents historical mark entry", () => { const f = fixture(); f.quotes[0].batches[0].response.data.results[4].quote.ask_price = "8"; eq(primary(run(snapshots(), f)).candidate.entryAsk, "0.12"); });
test("affordability includes assumed fee and adverse allowance", () => { const r = run(mutated(f => f.quotes[0].batches[0].response.data.results[4].quote.ask_price = "0.49", 0)); eq(primary(r).candidate.entryDebitUsd, "50.500000"); eq(primary(r).candidate.affordableUnder50Usd, false); eq(r.cases.length, 4); });
test("expiry-day reference does not become a settlement or fill", () => { const s = snapshots(), f = fixture(); for (const x of [f, ...s.map(x => JSON.parse(x.sourceText))]) { for (const c of x.chains) c.response.data.chains[0].expiration_dates = ["2026-09-09"]; for (const g of x.instruments) { g.expirations = ["2026-09-09"]; g.pages[0].request.expiration_dates = "2026-09-09"; for (const i of g.pages[0].response.data.instruments) i.expiration_date = "2026-09-09"; } const day = x.capturedAt.slice(0,10); const input = s.find(s => s.sessionDate === day); if (input) input.sourceText = JSON.stringify(x); } eq(primary(run(s, f)).candidate.reason, "EXIT_EXPIRY_ON_OR_BEFORE_REFERENCE_SESSION"); });
for (const [name, mutate, reason] of [
  ["old-source", (q: any) => q.updated_at = "2026-09-04T20:14:59Z", "WRONG_OR_UNKNOWN_QUOTE_SESSION"],
  ["too-early", (q: any) => q.updated_at = "2026-09-09T19:44:59.999999999Z", "OUTSIDE_DECLARED_CLOSE_REFERENCE_WINDOW"],
  ["too-late", (q: any) => q.updated_at = "2026-09-09T20:15:00.000000001Z", "OUTSIDE_DECLARED_CLOSE_REFERENCE_WINDOW"],
  ["future", (q: any) => q.updated_at = "2026-09-09T20:22:59Z", "FUTURE_QUOTE_CLOCK"],
  ["zero-size", (q: any) => q.bid_size = 0, "DISPLAYED_SIZE_INSUFFICIENT"],
  ["crossed", (q: any) => q.bid_price = "5", "MISSING_ZERO_OR_CROSSED_PRICE"],
  ["zero-bid", (q: any) => q.bid_price = "0", "MISSING_ZERO_OR_CROSSED_PRICE"],
  ["allowance", (q: any) => q.bid_price = "0.01", "EXIT_ALLOWANCE_CONSUMES_BID"],
] as const) test(name + " fails indicative price qualification", () => { const r = run(mutated(f => mutate(f.quotes[0].batches[0].response.data.results[4].quote))); eq(primary(r).candidate.reason, reason.startsWith("EXIT_") ? reason : "EXIT_" + reason); eq(primary(r).candidate.netReferenceChangeUsd, null); });
test("exact close-window boundaries are accepted only as reference evidence", () => { for (const time of ["19:45:00", "20:15:00"]) { const r = run(mutated(f => f.quotes[0].batches[0].response.data.results[4].quote.updated_at = "2026-09-09T" + time + "Z")); eq(primary(r).candidate.result, "POSITIVE"); eq(primary(r).candidate.actualFill, false); } });
test("missing quote stays unknown and candidate remains", () => { const r = run(mutated(f => f.quotes[0].batches[0].response.data.results.splice(4, 1))); eq(primary(r).candidate.result, "UNKNOWN"); eq(r.cases.length, 4); });
test("missing entry never moves to a more favorable later entry", () => { const r = run(snapshots().slice(1)); eq(primary(r).candidate.reason, "ENTRY_SESSION_BOARD_MISSING"); });
test("contract identity cannot change across snapshots", () => { throws(() => run(mutated(f => f.instruments[0].pages[0].response.data.instruments[4].strike_price = "999")), "CONTRACT_IDENTITY_CHANGED"); });
test("duplicate sessions and future assessed knowledge fail", () => { const s = snapshots(); throws(() => run([s[0]!, s[0]!]), "SESSION_DUPLICATE"); s[1]!.assessedAt = "2026-09-10T20:22:00.000Z"; throws(() => run(s), "SNAPSHOT_KNOWLEDGE_CLOCK"); });
test("future or backfilled captured sessions rejected", () => { throws(() => run(mutated(f => f.capturedAt = "2026-09-10 20:21:00 UTC")), "CHAIN_SURVEY_"); throws(() => run(mutated(f => f.capturedAt = "2026-09-09 22:01:00 UTC"), fixture(), "2026-09-09T23:00:00.000Z"), "CHAIN_SURVEY_"); });
test("later recording stays labeled and doesn't become earlier knowledge", () => { const s = snapshots(); s[1]!.assessedAt = "2026-09-10T20:22:00.000Z"; const r = run(s, fixture(), "2026-09-10T20:22:00.000Z"); eq(r.inputSnapshots[1]!.recordedAfterCaptureSession, true); });
test("secondary horizons never replace missing primary", () => { const s = snapshots().slice(0, 1); s.push({sessionDate:"2026-09-10",sourceText:JSON.stringify(fixture("2026-09-10")),assessedAt:"2026-09-10T20:22:00.000Z"}); const r = run(s, fixture(), "2026-09-10T20:22:00.000Z"); eq(primary(r).candidate.result, "UNKNOWN"); eq(r.counts.primaryEvaluableCandidates, 0); });
test("summary denominator includes gaps and matching unknowns", () => { const r = run(); const s = r.summaries.find(s => s.symbol === "GLD" && s.cohort === "SEPTEMBER_18_COMPARISON" && s.primary && s.costScenario === "ILLUSTRATIVE_BASE")!; eq(s.candidates, 2); eq(s.positive, 1); eq(s.negative, 1); eq(s.independentSampleCount, null); eq(s.evaluablePairs, 2); });
test("micro-dollar prices survive whole-contract arithmetic exactly", () => { const s = mutated(f => f.quotes[0].batches[0].response.data.results[4].quote.ask_price = "0.120001", 0); const o = primary(run(s)); eq(o.candidate.entryDebitUsd, "13.500100"); eq(o.candidate.netReferenceChangeUsd, "4.999900"); });
test("excessive return projections fail without unsafe numeric precision", () => { const s = mutated(f => { const q = f.quotes[0].batches[0].response.data.results[4].quote; q.bid_price = q.ask_price = "0.000001"; }, 0); const f = JSON.parse(s[1]!.sourceText); f.quotes[0].batches[0].response.data.results[4].quote.bid_price = f.quotes[0].batches[0].response.data.results[4].quote.ask_price = "99999999"; s[1]!.sourceText = JSON.stringify(f); throws(() => run(s), "RETURN_RATIO_BOUND"); });
test("source provenance cannot mix fixture and host observations", () => { throws(() => run(mutated(f => f.origin = "HOST_MARKET_TOOL_RESPONSES")), "SNAPSHOT_SCOPE_OR_ORIGIN"); });
test("snapshot expiration scope must name the declared session", () => { throws(() => run(mutated(f => f.scope.expirationStart = "2026-09-08")), "SNAPSHOT_SCOPE_OR_ORIGIN"); });
test("capture outside accepted close window fails even when assessed later", () => { const s = snapshots(), f = JSON.parse(s[1]!.sourceText); f.capturedAt = "2026-09-09 22:01:00 UTC"; s[1]!.sourceText = JSON.stringify(f); s[1]!.assessedAt = "2026-09-09T22:02:00.000Z"; throws(() => run(s, fixture(), "2026-09-09T22:02:00.000Z"), "SNAPSHOT_CAPTURE_WINDOW"); });
test("quote receipt before close acquisition window does not qualify", () => { const s = mutated(f => { for (const c of f.chains) c.requestedAt = c.receivedAt = "2026-09-09 20:19:00 UTC"; for (const g of f.instruments) g.pages[0].requestedAt = g.pages[0].receivedAt = "2026-09-09 20:19:00 UTC"; f.quotes[0].batches[0].requestedAt = f.quotes[0].batches[0].receivedAt = "2026-09-09 20:19:59 UTC"; }); eq(primary(run(s)).candidate.reason, "EXIT_RECEIPT_OUTSIDE_CLOSE_CAPTURE_WINDOW"); });
test("future volume changes do not reseat frozen candidates or controls", () => { const r = run(mutated(f => { for (const q of f.quotes[0].batches[0].response.data.results) q.quote.volume = 900000; })); eq(r.cases.map(c => [c.candidate.id, c.control?.id]), run().cases.map(c => [c.candidate.id, c.control?.id])); });
console.log(`${passed}/${passed} tests passed.`);
