import { assessRobinhoodChainSurvey as assess, parseChainSurveyJson } from "./RobinhoodChainSurvey";
import { compareRobinhoodChainSurveys as compare } from "./RobinhoodChainComparison";
import { chainSurveyFixture } from "./RobinhoodChainSurveyFixtures";

const equal = (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw Error("VALUES_DIFFER"); };
const assert = Object.assign((v: unknown) => { if (!v) throw Error("EXPECTED_TRUTHY"); }, { equal, deepEqual: equal,
  throws(work: () => unknown, pattern: RegExp) { let error: unknown; try { work(); } catch (e) { error = e; } if (!(error instanceof Error) || !pattern.test(error.message)) throw Error("EXPECTED_ERROR " + pattern); } });

const at = "2026-09-08T20:21:10.000Z";
const fixture = (): any => chainSurveyFixture();
const run = (f = fixture()) => assess(JSON.stringify(f), at);
let passed = 0; function test(name: string, work: () => void) { work(); passed++; console.log("PASS " + name); }
test("complete all-case snapshot never grants trade or win probability", () => { const r = run(); assert.equal(r.instrumentCount, 12); assert.equal(r.quoteCount, 12); assert.equal(r.flaggedCount, 4); assert.equal(r.winProbability, null); assert.equal(r.executionAllowed, false); assert.equal(r.historicalAnomalyConfirmed, false); assert.equal(r.rows[0]!.bid, "0.100001"); });
test("thresholds use exact positive median and preserve below-filter cases", () => { const r = run(); assert.deepEqual(r.rows[0]!.positivePeerMedian, { numerator: 50, denominator: 2 }); assert.equal(r.rows.filter(r => !r.reviewCandidate).length, 8); assert(r.rows[5]!.activityFlags.includes("VOLUME_AT_LEAST_1000")); assert(r.rows[4]!.activityFlags.includes("VOLUME_AT_LEAST_3X_REPORTED_OI")); });
test("zero OI is unknown ratio, never infinite evidence", () => { const f = fixture(); f.quotes[0].batches[0].response.data.results[4].quote.open_interest = 0; const r = run(f).rows[4]!; assert.equal(r.volumeOiRatio, null); assert(!r.activityFlags.includes("VOLUME_AT_LEAST_3X_REPORTED_OI")); });
test("missing counters remain unknown and don't become zero", () => { const f = fixture(); delete f.quotes[0].batches[0].response.data.results[0].quote.volume; f.quotes[0].batches[0].response.data.results[0].quote.open_interest = null; const r = run(f); assert.equal(r.rows[0]!.volume, null); assert.equal(r.expirations[0]!.reportedVolumeSum, null); });
test("missing quote disables peer screen without deleting contract", () => { const f = fixture(); f.quotes[0].batches[0].response.data.results.pop(); const r = run(f); assert.equal(r.instrumentCount, 12); assert.equal(r.quoteCount, 11); assert.equal(r.rows[5]!.volume, null); assert.equal(r.rows[0]!.peerScreenEligible, false); assert.equal(r.status, "PARTIAL_CAPTURE_REVIEW"); });
test("no quote request is a missing-data gap", () => { const f = fixture(); f.quotes[0].batches = []; assert.equal(run(f).quoteCount, 6); });
test("source ordering does not control quote identity", () => { const f = fixture(); f.quotes[0].batches[0].response.data.results.reverse(); assert.deepEqual(run(f).rows, run().rows); assert.equal(run(f).rows[5]!.volume, 1000); });
for (const [name, mutate] of [
  ["wrong quote UUID", (f: any) => f.quotes[0].batches[0].response.data.results[0].quote.instrument_id = f.quotes[1].batches[0].request.instrument_ids[0]],
  ["duplicate quote", (f: any) => f.quotes[0].batches[0].response.data.results[1] = f.quotes[0].batches[0].response.data.results[0]],
  ["duplicate instrument", (f: any) => f.instruments[0].pages[0].response.data.instruments[1] = f.instruments[0].pages[0].response.data.instruments[0]],
  ["unexpected expiration", (f: any) => f.instruments[0].pages[0].response.data.instruments[0].expiration_date = "2026-09-18"],
  ["negative counter", (f: any) => f.quotes[0].batches[0].response.data.results[0].quote.volume = -1],
  ["oversized count", (f: any) => f.quotes[0].batches[0].response.data.results[0].quote.volume = 1e10],
  ["future receipt", (f: any) => f.quotes[0].batches[0].receivedAt = "2026-09-09 20:21:00 UTC"],
  ["wrong request count", (f: any) => f.quotes[0].totalRequested = 0],
  ["foreign account scope", (f: any) => f.accountAccessed = true],
  ["unknown root field", (f: any) => f.order = {}],
] as const) test(name + " fails closed", () => { const f = fixture(); mutate(f); assert.throws(() => run(f), /CHAIN_SURVEY_/); });
test("partial pagination preserves rows and removes peer authority", () => { const f = fixture(); f.instruments[0].pages[0].response.data.next = f.instruments[0].next = "https://example.invalid/?cursor=next"; const r = run(f); assert(r.issues.includes("GLD_INSTRUMENT_PAGINATION_INCOMPLETE")); assert.equal(r.rows[0]!.peerScreenEligible, false); });
test("complete pagination requires exact chained cursor and clocks", () => { const f = fixture(), g = f.instruments[0], p = structuredClone(g.pages[0]); g.pages[0].response.data.instruments.splice(3); g.pages[0].response.data.next = "https://example.invalid/?cursor=next%2B1"; p.request.cursor = "next+1"; p.response.data.instruments.splice(0, 3); g.pages.push(p); assert.equal(run(f).instrumentCount, 12); p.request.cursor = "wrong"; assert.throws(() => run(f), /PAGE_REQUEST/); });
test("expired same-session contracts remain despite absent active chain date", () => { const f = fixture(), g = structuredClone(f.instruments[0]); g.expirations = ["2026-09-08"]; g.pages[0].request.state = "expired"; g.pages[0].request.expiration_dates = "2026-09-08"; const i = g.pages[0].response.data.instruments[0]; i.id = "00000000-0000-4000-8000-000000000999"; i.expiration_date = "2026-09-08"; i.state = "expired"; i.tradability = "untradable"; g.pages[0].response.data.instruments = [i]; f.instruments.push(g); f.quotes[0].totalRequested++; const r = run(f); assert.equal(r.instrumentCount, 13); assert.equal(r.expirations[0]!.expiry, "2026-09-08"); assert(r.rows[0]!.quality.includes("CONTRACT_NOT_STANDARD_ACTIVE_TRADABLE")); });
test("expired query cannot request a future or unrelated session", () => { const f = fixture(); f.instruments[0].pages[0].request.state = "expired"; assert.throws(() => run(f), /EXPIRATION_SCOPE/); });
test("invalid future stale and same-second nanosecond clocks are distinct", () => { const f = fixture(), q = f.quotes[0].batches[0].response.data.results; q[0].quote.updated_at = "bad"; q[1].quote.updated_at = "2026-09-08T20:21:01.000000001Z"; q[2].quote.updated_at = "2026-09-04T20:00:00Z"; q[3].quote.updated_at = "2026-09-08T20:21:00.999999999Z"; const r = run(f).rows; assert(r[0]!.quality.includes("QUOTE_CLOCK_UNKNOWN")); assert(r[1]!.quality.includes("QUOTE_AFTER_RECEIPT_SECOND")); assert(r[2]!.quality.includes("STALE_AT_ASSESSMENT")); assert(!r[3]!.quality.includes("QUOTE_AFTER_RECEIPT_SECOND")); });
test("crossed and zero quotes remain unusable price evidence", () => { const f = fixture(), q = f.quotes[0].batches[0].response.data.results; q[0].quote.bid_price = "1"; q[1].quote.bid_price = "0"; q[1].quote.bid_size = 0; const r = run(f); assert(r.rows[0]!.quality.includes("CROSSED_QUOTE")); assert(r.rows[1]!.quality.includes("ONE_SIDED_OR_CLOSED_QUOTE")); });
test("duplicate decoded keys and prototype keys fail strict JSON", () => { for (const s of ['{"a":1,"\\u0061":2}', '{"__proto__":{}}', '{"constructor":1}']) assert.throws(() => parseChainSurveyJson(s), /JSON_KEY/); });
test("JSON depth and malformed input fail", () => { assert.throws(() => parseChainSurveyJson("[".repeat(25) + "0" + "]".repeat(25)), /DEPTH/); assert.throws(() => parseChainSurveyJson('{"a":}'), /JSON/); });
function later(f: any) { const next = structuredClone(f); next.capturedAt = "2026-09-09 20:21:00 UTC"; return next; }
test("unchanged quote clocks suppress changes even when counters change", () => { const a = fixture(), b = later(a); b.quotes[0].batches[0].response.data.results[0].quote.volume = 100; const r = compare(JSON.stringify(a), at, JSON.stringify(b), "2026-09-09T20:21:10.000Z"); assert.equal(r.rows[0]!.reportedVolumeDifference, null); assert.equal(r.counts.unchangedQuoteClock, 12); });
test("advancing dates produce descriptive counter differences with unknown session", () => { const a = fixture(), b = later(a); const batch = b.quotes[0].batches[0]; batch.requestedAt = batch.receivedAt = b.capturedAt; batch.response.data.results[0].quote.updated_at = "2026-09-09T20:20:59Z"; batch.response.data.results[0].quote.volume = 2; const r = compare(JSON.stringify(a), at, JSON.stringify(b), "2026-09-09T20:21:10.000Z"); assert.equal(r.rows[0]!.reportedVolumeDifference, -8); assert.equal(r.rows[0]!.verifiedVolumeSession, false); });
test("comparison rejects reversed chronology", () => { const a = JSON.stringify(fixture()); assert.throws(() => compare(a, at, a, at), /COMPARISON_ORDER/); });
test("future-clock candidate cannot use valid peers for relative evidence", () => { const f = fixture(); const q = f.quotes[0].batches[0].response.data.results[5].quote; q.updated_at = "2026-09-08T20:21:01Z"; const r = run(f).rows[5]!; assert.equal(r.peerScreenEligible, false); assert(!r.activityFlags.includes("VOLUME_AT_LEAST_5X_POSITIVE_PEER_MEDIAN")); });
console.log(`${passed}/${passed} tests passed.`);
