import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  AIAuditActorType, AIAuditRecordType, AIAuditRetentionClassification, AIAuditSourceSubsystem,
  HistoricalAmendmentType, HistoricalAppendStatus, HistoricalAssetClass, HistoricalAuditOperationType,
  HistoricalClaimClassification, HistoricalDatePrecision, HistoricalEventStatus, HistoricalEventType,
  HistoricalExportDestination, HistoricalExportFormat, HistoricalExportStatus, HistoricalMissingDataState,
  HistoricalPatternStatus, HistoricalPatternType, HistoricalReactionDirection, HistoricalRecordKind,
  HistoricalReferenceResolution, HistoricalReferenceType, HistoricalRegimeState, HistoricalRegimeType,
  HistoricalReviewQuality, HistoricalSourceType, HistoricalTimeHorizon, PrivacyLevel,
  historicalFingerprint, validateHistoricalAssetReaction,
  type HistoricalAssetReaction, type HistoricalAuditRecord, type HistoricalEventAmendment,
  type HistoricalEventReview, type HistoricalPatternAmendment, type HistoricalPatternReview,
  type HistoricalPatternSupersession,
} from "../../contracts";
import { InMemoryHistoricalPatternRepository, LocalNdjsonHistoricalPatternRepository } from "../../repositories";
import {
  HistoricalPatternLibrary, auditRecordFromHistoricalPattern, exportHistoricalPatterns,
  sortHistoricalObservationWindows, type HistoricalEventFinalization,
  type HistoricalPatternClock, type HistoricalPatternFinalization,
} from ".";

interface TestCase { readonly name: string; readonly run: () => void; }
function assertEqual<T>(actual: T, expected: T, message: string): void { if (!Object.is(actual, expected)) throw new Error(`${message}: expected ${String(expected)}, received ${String(actual)}.`); }
function assertTrue(value: boolean, message: string): void { if (!value) throw new Error(message); }
function assertDeepEqual(actual: unknown, expected: unknown, message: string): void { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(message); }
function expectError(action: () => void, expected?: string): void { try { action(); } catch (error: unknown) { const message = error instanceof Error ? error.message : String(error); if (expected !== undefined) assertTrue(message.toLowerCase().includes(expected.toLowerCase()), `Expected "${expected}", received "${message}".`); return; } throw new Error(`Expected error${expected === undefined ? "" : ` containing "${expected}"`}.`); }
class FixedClock implements HistoricalPatternClock { now(): string { return "2026-07-19T20:00:00.000Z"; } }

const knownDimension = (dimension: HistoricalRegimeType, value: string) => ({ dimension, state: HistoricalRegimeState.Known, value, evidenceReferenceIds: ["evidence-fact-1"], confidence: 80, period: { value: "2008", precision: HistoricalDatePrecision.Year } }) as const;
const auditReference = (id: string) => ({ referenceId: id, recordType: HistoricalReferenceType.Audit, resolution: HistoricalReferenceResolution.Resolved, version: "v1" }) as const;
function references() {
  return {
    research: [{ referenceId: "research-1", recordType: HistoricalReferenceType.Research, resolution: HistoricalReferenceResolution.Resolved, version: "v1", frozenStatus: "FINALIZED" }],
    journals: [{ referenceId: "journal-1", recordType: HistoricalReferenceType.Journal, resolution: HistoricalReferenceResolution.Resolved, version: "v1" }],
    predictions: [{ referenceId: "prediction-1", recordType: HistoricalReferenceType.Prediction, resolution: HistoricalReferenceResolution.Resolved, version: "v1", frozenStatus: "LOCKED" }],
    strategies: [{ referenceId: "strategy-1", recordType: HistoricalReferenceType.Strategy, resolution: HistoricalReferenceResolution.Resolved, version: "1.0.0" }],
    audits: [auditReference("audit-1")],
  } as const;
}
function window(horizon = HistoricalTimeHorizon.OneMonth) { return { windowId: `window-${horizon.toLowerCase()}`, horizon, start: { value: "2008-09-15", precision: HistoricalDatePrecision.ExactDate }, end: { value: "2008-10-15", precision: HistoricalDatePrecision.ExactDate }, tradingDayBasis: "NYSE calendar" } as const; }
function reaction(overrides: Partial<HistoricalAssetReaction> = {}): HistoricalAssetReaction {
  return { reactionId: "reaction-1", assetClass: HistoricalAssetClass.Equity, marketIndex: { referenceId: "index-spx", market: "US", indexName: "Synthetic Broad Index", currency: "USD" }, observationWindow: window(), startValue: { dataReferenceId: "data-start", value: 100, unit: "points", currency: "USD", observedAt: "2008-09-15T20:00:00.000Z", sourceReferenceId: "source-1", missing: false }, endValue: { dataReferenceId: "data-end", value: 90, unit: "points", currency: "USD", observedAt: "2008-10-15T20:00:00.000Z", sourceReferenceId: "source-1", missing: false }, absoluteChange: -10, percentageChange: -10, maximumDrawdown: -15, maximumGain: 2, realizedVolatility: 45, direction: HistoricalReactionDirection.Down, recoveryDuration: "18 months", sourceDataTimestamp: "2008-10-15T20:00:00.000Z", dataSourceReferenceIds: ["source-1"], missingDataState: HistoricalMissingDataState.Complete, calculationMethodReference: "method:simple-return-v1", ...overrides };
}

function eventInput(overrides: Partial<HistoricalEventFinalization> = {}): HistoricalEventFinalization {
  const inflation = knownDimension(HistoricalRegimeType.Inflation, "ELEVATED"); const growth = knownDimension(HistoricalRegimeType.Growth, "CONTRACTING"); const liquidity = knownDimension(HistoricalRegimeType.Liquidity, "STRESSED"); const credit = knownDimension(HistoricalRegimeType.Credit, "TIGHT"); const volatility = knownDimension(HistoricalRegimeType.Volatility, "HIGH"); const monetary = knownDimension(HistoricalRegimeType.MonetaryPolicy, "EASING");
  return {
    eventId: "historical-event:synthetic-crisis-2008", schemaVersion: "1.0", recordVersion: "v1", title: "Synthetic 2008 liquidity crisis",
    eventCategories: [HistoricalEventType.LiquidityCrisis, HistoricalEventType.MarketCrash], start: { value: "2008-09-01", precision: HistoricalDatePrecision.Approximate }, peak: { value: "2008-09-15", precision: HistoricalDatePrecision.ExactDate }, end: { value: "2009-03", precision: HistoricalDatePrecision.Month }, openEnded: false,
    geography: ["US", "GLOBAL"], affectedMarkets: ["US"], affectedAssetClasses: [HistoricalAssetClass.Equity, HistoricalAssetClass.Credit], scope: { included: ["Synthetic historical evidence"], excluded: ["Live data", "Prediction"] }, factualDescription: "A synthetic liquidity disruption coincided with a broad market decline.",
    causes: [{ causeId: "cause-1", statement: "Funding markets tightened according to the supplied source.", classification: HistoricalClaimClassification.SourceClaim, evidenceReferenceIds: ["evidence-fact-1"], confidence: 80 }],
    outcomes: [{ outcomeId: "outcome-1", statement: "The supplied broad index observation declined.", classification: HistoricalClaimClassification.QuantitativeObservation, evidenceReferenceIds: ["evidence-fact-1"], horizon: HistoricalTimeHorizon.OneMonth }], contributingFactors: ["Synthetic leverage pressure"],
    policyContext: { monetaryPolicy: monetary, responses: ["Synthetic liquidity support"] }, macroContext: { inflation, growth }, liquidityContext: { dimension: liquidity, observations: ["Funding stress"] }, creditContext: { dimension: credit, observations: ["Spreads widened"] }, volatilityContext: { dimension: volatility, observations: ["Volatility rose"] },
    marketRegime: { regimeId: "regime-2008", dimensions: [monetary, inflation, growth, liquidity, credit, volatility], summary: "Contracting growth, tight credit, stressed liquidity, and high volatility." }, observationWindows: [window()], assetReactions: [reaction()],
    sources: [{ sourceReferenceId: "source-1", sourceType: HistoricalSourceType.Dataset, title: "Synthetic historical dataset", publisherOrOwner: "Alpha", publishedAt: "2009-01-01T00:00:00.000Z", locationReference: "local:synthetic-history", privacyLevel: PrivacyLevel.Internal, reliabilityScore: 90, contentIntegrityReference: "fnv1a64:synthetic" }],
    dataReferences: [{ dataReferenceId: "data-start", value: 100, unit: "points", currency: "USD", observedAt: "2008-09-15T20:00:00.000Z", sourceReferenceId: "source-1", missing: false }, { dataReferenceId: "data-end", value: 90, unit: "points", currency: "USD", observedAt: "2008-10-15T20:00:00.000Z", sourceReferenceId: "source-1", missing: false }],
    evidence: [{ evidenceId: "evidence-fact-1", classification: HistoricalClaimClassification.HistoricalFact, statement: "The supplied index reference moved from 100 to 90 over the observation window.", sourceReferenceIds: ["source-1"], dataReferenceIds: ["data-start", "data-end"], confidence: 95, competingInterpretationIds: [] }],
    uncertainties: ["The fixture is intentionally narrow."], disputedInterpretations: [{ evidenceId: "evidence-disputed-1", classification: HistoricalClaimClassification.DisputedClaim, statement: "The primary causal weight is disputed.", sourceReferenceIds: ["source-1"], dataReferenceIds: [], confidence: 50, competingInterpretationIds: ["interpretation-a", "interpretation-b"] }], relatedEventIds: [], references: references(), tags: ["synthetic", "liquidity"], privacyLevel: PrivacyLevel.Internal, retention: AIAuditRetentionClassification.Permanent, correlationId: "correlation-1", traceId: "trace-1", policyVersions: { historical: "v1" }, metadata: { fixture: true }, ...overrides,
  };
}
function patternInput(eventId: string, overrides: Partial<HistoricalPatternFinalization> = {}): HistoricalPatternFinalization {
  const causal = { evidenceId: "pattern-causal-1", classification: HistoricalClaimClassification.Inference, statement: "Forced balance-sheet contraction may transmit funding stress to asset prices.", sourceReferenceIds: ["source-1"], dataReferenceIds: [], confidence: 70, competingInterpretationIds: [] } as const;
  return { patternId: "historical-pattern:synthetic-liquidity-stress", schemaVersion: "1.0", recordVersion: "v1", title: "Synthetic liquidity stress", patternType: HistoricalPatternType.CreditStress, description: "A reusable evidence-backed sequence in which funding stress and deleveraging coincide with repricing.", qualifyingConditions: ["Funding conditions are stressed", "Evidence is owner reviewed"], causalMechanism: causal, typicalSequence: ["Funding stress", "Deleveraging", "Asset repricing"], features: [{ featureId: "feature-1", name: "Funding stress", description: "Supplied funding evidence weakens.", classification: HistoricalClaimClassification.QuantitativeObservation, evidenceReferenceIds: ["pattern-evidence-1"] }], dimensions: [{ dimensionId: "dimension-1", name: "Liquidity", required: true, expectedValues: ["STRESSED"], evidenceReferenceIds: ["pattern-evidence-1"] }], sourceEventIds: [eventId], evidence: [{ evidenceId: "pattern-evidence-1", classification: HistoricalClaimClassification.SourceClaim, statement: "The source event contains supplied evidence of stress.", sourceReferenceIds: ["source-1"], dataReferenceIds: [], confidence: 80, competingInterpretationIds: [] }], counterexamples: [], knownExceptions: ["Policy response and valuation may materially differ."], regimeDependencies: [knownDimension(HistoricalRegimeType.Liquidity, "STRESSED")], typicalAssetReactions: [reaction({ reactionId: "pattern-reaction-1" })], confidence: { score: 65, rationale: "One synthetic event supports only a low-sample foundation." }, limitations: [{ limitationId: "limitation-1", statement: "Single synthetic supporting event.", material: true, evidenceReferenceIds: ["pattern-evidence-1"] }], invalidationConditions: [{ conditionId: "invalidation-1", statement: "Source event evidence is retracted.", evidenceRequired: ["pattern-evidence-1"] }], minimumSupportingEventCount: 1, ownerApprovalReference: "owner-approval-1", relatedPatternIds: [], references: references(), tags: ["synthetic", "credit-stress"], privacyLevel: PrivacyLevel.Internal, retention: AIAuditRetentionClassification.Permanent, correlationId: "correlation-1", traceId: "trace-1", policyVersions: { historical: "v1" }, metadata: { fixture: true }, ...overrides };
}
function setup(event = eventInput()): { repository: InMemoryHistoricalPatternRepository; library: HistoricalPatternLibrary; event: ReturnType<HistoricalPatternLibrary["finalizeEvent"]>["record"] } { const repository = new InMemoryHistoricalPatternRepository(); const library = new HistoricalPatternLibrary(repository, new FixedClock()); return { repository, library, event: library.finalizeEvent(event).record }; }
function eventAmendment(id: string, overrides: Partial<HistoricalEventAmendment> = {}): HistoricalEventAmendment { return { amendmentId: `${id}:amendment:1`, eventId: id, createdAt: "2026-07-19T20:05:00.000Z", amendmentType: HistoricalAmendmentType.AdditionalEvidence, reason: "Preserve added evidence without rewriting history.", changedFields: ["evidence"], evidence: [], authorReference: "owner-1", auditReference: auditReference("audit-event-amendment-1"), ...overrides }; }
function patternAmendment(id: string, overrides: Partial<HistoricalPatternAmendment> = {}): HistoricalPatternAmendment { return { amendmentId: `${id}:amendment:1`, patternId: id, createdAt: "2026-07-19T20:05:00.000Z", amendmentType: HistoricalAmendmentType.ChangedConfidence, reason: "Preserve revised confidence separately.", changedFields: ["confidence"], evidence: [], confidence: { score: 60, rationale: "Additional review." }, authorReference: "owner-1", auditReference: auditReference("audit-pattern-amendment-1"), ...overrides }; }
function eventReview(id: string): HistoricalEventReview { return { reviewId: `${id}:review:1`, eventId: id, createdAt: "2026-07-19T20:10:00.000Z", reviewer: "owner-1", sourceQuality: HistoricalReviewQuality.Good, evidenceCompleteness: HistoricalReviewQuality.Mixed, hindsightBiasRisk: HistoricalReviewQuality.Mixed, survivorshipBiasRisk: HistoricalReviewQuality.Mixed, selectionBiasRisk: HistoricalReviewQuality.Mixed, regimeClassificationQuality: HistoricalReviewQuality.Good, causalInferenceQuality: HistoricalReviewQuality.Mixed, calculationQuality: HistoricalReviewQuality.Good, missingDataImpact: "Synthetic sample limits generalization.", applicabilityLimitations: ["Not predictive"], futureResearchQuestions: ["Which counterexamples matter?"], auditReference: auditReference("audit-event-review-1") }; }
function patternReview(id: string): HistoricalPatternReview { const { eventId: _eventId, ...base } = eventReview("placeholder"); return { ...base, reviewId: `${id}:review:1`, patternId: id, auditReference: auditReference("audit-pattern-review-1") }; }
function supersession(prior: string, successor: string): HistoricalPatternSupersession { return { supersessionId: `${prior}:supersession:1`, priorPatternId: prior, successorPatternId: successor, createdAt: "2026-07-19T20:15:00.000Z", reason: "Methodology changed materially.", changedEvidence: ["Additional event"], changedMethodology: ["Revised qualifying conditions"], ownerReference: "owner-1", auditReference: auditReference("audit-supersession-1") }; }

const tests: ReadonlyArray<TestCase> = [
  { name: "valid historical event append", run: () => assertEqual(setup().event.status, HistoricalEventStatus.Finalized, "status") },
  { name: "valid historical pattern append", run: () => { const { library, event } = setup(); assertEqual(library.finalizePattern(patternInput(event.eventId)).record.status, HistoricalPatternStatus.Finalized, "status"); } },
  { name: "event without evidence is rejected at finalization", run: () => expectError(() => setup(eventInput({ evidence: [] })), "factual source evidence") },
  { name: "pattern without supporting events is rejected", run: () => { const { library } = setup(); expectError(() => library.finalizePattern(patternInput("historical-event:missing", { sourceEventIds: [] })), "supporting events") } },
  { name: "duplicate ID behavior rejects conflicting event", run: () => { const { repository, event } = setup(); expectError(() => repository.appendEvent({ ...event, title: "Conflict" }, "2026-07-19T20:00:00.000Z"), "conflict") } },
  { name: "identical append is idempotent", run: () => { const repository = new InMemoryHistoricalPatternRepository(); const library = new HistoricalPatternLibrary(repository, new FixedClock()); assertEqual(library.finalizeEvent(eventInput()).status, HistoricalAppendStatus.Appended, "first"); assertEqual(library.finalizeEvent(eventInput()).status, HistoricalAppendStatus.Replayed, "second"); } },
  { name: "conflicting duplicate pattern is rejected", run: () => { const { repository, library, event } = setup(); const pattern = library.finalizePattern(patternInput(event.eventId)).record; expectError(() => repository.appendPattern({ ...pattern, title: "Conflict" }, "2026-07-19T20:00:00.000Z"), "conflict") } },
  { name: "invalid date range is rejected", run: () => expectError(() => setup(eventInput({ start: { value: "2010", precision: HistoricalDatePrecision.Year }, end: { value: "2009", precision: HistoricalDatePrecision.Year } })), "precede") },
  { name: "approximate date precision is preserved", run: () => assertEqual(setup().event.start.precision, HistoricalDatePrecision.Approximate, "precision") },
  { name: "multi-category event is preserved", run: () => assertDeepEqual(setup().event.eventCategories, [HistoricalEventType.LiquidityCrisis, HistoricalEventType.MarketCrash], "categories") },
  { name: "regime unknown state is preserved", run: () => { const value = eventInput(); const unknown = { dimension: HistoricalRegimeType.InvestorPositioning, state: HistoricalRegimeState.Unknown, evidenceReferenceIds: [], confidence: 0, period: { precision: HistoricalDatePrecision.Unknown } } as const; assertEqual(setup(eventInput({ marketRegime: { ...value.marketRegime, dimensions: [...value.marketRegime.dimensions, unknown] } })).event.marketRegime.dimensions.at(-1)?.state, HistoricalRegimeState.Unknown, "state"); } },
  { name: "disputed interpretation is preserved", run: () => assertEqual(setup().event.disputedInterpretations[0]?.classification, HistoricalClaimClassification.DisputedClaim, "classification") },
  { name: "fact and inference remain structurally distinct", run: () => { const value = eventInput(); const inference = { ...value.evidence[0]!, evidenceId: "evidence-inference-1", classification: HistoricalClaimClassification.Inference, statement: "The supplied observation may reflect stress." }; const record = setup(eventInput({ evidence: [...value.evidence, inference] })).event; assertDeepEqual(record.evidence.map((item) => item.classification), [HistoricalClaimClassification.HistoricalFact, HistoricalClaimClassification.Inference], "classifications"); } },
  { name: "counterevidence is preserved", run: () => { const value = eventInput(); const counter = { ...value.evidence[0]!, evidenceId: "evidence-counter-1", classification: HistoricalClaimClassification.Counterevidence, statement: "The sample contains a contrary observation." }; assertTrue(setup(eventInput({ evidence: [...value.evidence, counter] })).event.evidence.some((item) => item.classification === HistoricalClaimClassification.Counterevidence), "counterevidence missing"); } },
  { name: "asset reaction validation accepts deterministic calculation", run: () => assertEqual(validateHistoricalAssetReaction(reaction()).valid, true, "reaction") },
  { name: "invalid zero-denominator percentage is rejected", run: () => assertEqual(validateHistoricalAssetReaction(reaction({ startValue: { dataReferenceId: "zero", value: 0, currency: "USD", sourceReferenceId: "source-1", missing: false }, endValue: { dataReferenceId: "end", value: 1, currency: "USD", sourceReferenceId: "source-1", missing: false }, percentageChange: 100 })).valid, false, "validation") },
  { name: "missing market data remains missing", run: () => { const { startValue: _start, endValue: _end, absoluteChange: _absolute, percentageChange: _percentage, maximumDrawdown: _drawdown, maximumGain: _gain, realizedVolatility: _volatility, calculationMethodReference: _method, ...base } = reaction(); const missing: HistoricalAssetReaction = { ...base, direction: HistoricalReactionDirection.Unknown, missingDataState: HistoricalMissingDataState.Missing }; assertEqual(validateHistoricalAssetReaction(missing).valid, true, "missing"); } },
  { name: "observation-window ordering is deterministic", run: () => assertDeepEqual(sortHistoricalObservationWindows([window(HistoricalTimeHorizon.OneYear), window(HistoricalTimeHorizon.EventDay)]).map((item) => item.horizon), [HistoricalTimeHorizon.EventDay, HistoricalTimeHorizon.OneYear], "order") },
  { name: "valid lifecycle transitions are preserved", run: () => assertDeepEqual(setup().event.history.map((item) => item.toStatus), [HistoricalEventStatus.Validating, HistoricalEventStatus.Finalized], "history") },
  { name: "invalid reverse lifecycle transition is rejected", run: () => { const { library, event } = setup(); library.archiveEvent(event.eventId, "2026-07-19T20:30:00.000Z", "Archive after review period."); expectError(() => library.reviewEvent(eventReview(event.eventId)), "finalized event") } },
  { name: "review before finalization is rejected", run: () => expectError(() => new HistoricalPatternLibrary(new InMemoryHistoricalPatternRepository(), new FixedClock()).reviewEvent(eventReview("historical-event:missing")), "does not exist") },
  { name: "amendment preserves original", run: () => { const { library, event } = setup(); library.amendEvent(eventAmendment(event.eventId)); assertEqual(library.eventHistoryById(event.eventId)?.amendments.length, 1, "amendments"); assertEqual(library.getEvent(event.eventId)?.title, event.title, "original"); } },
  { name: "supersession preserves prior record", run: () => { const { library, event } = setup(); const first = library.finalizePattern(patternInput(event.eventId)).record; const second = library.finalizePattern(patternInput(event.eventId, { patternId: "historical-pattern:synthetic-liquidity-stress-v2", recordVersion: "v2", title: "Synthetic liquidity stress v2" })).record; library.supersedePattern(supersession(first.patternId, second.patternId)); assertEqual(library.getPattern(first.patternId)?.status, HistoricalPatternStatus.Superseded, "status"); assertEqual(library.getPattern(first.patternId)?.patternId, first.patternId, "prior"); } },
  { name: "self-supersession is rejected", run: () => { const { library, event } = setup(); const pattern = library.finalizePattern(patternInput(event.eventId)).record; expectError(() => library.supersedePattern(supersession(pattern.patternId, pattern.patternId)), "itself") } },
  { name: "cyclic supersession lineage is rejected", run: () => { const { library, event } = setup(); const first = library.finalizePattern(patternInput(event.eventId)).record; const second = library.finalizePattern(patternInput(event.eventId, { patternId: "historical-pattern:lineage-two", title: "Lineage two" })).record; library.supersedePattern(supersession(first.patternId, second.patternId)); expectError(() => library.supersedePattern(supersession(second.patternId, first.patternId))) } },
  { name: "Research reference is preserved", run: () => assertEqual(setup().event.references.research[0]?.referenceId, "research-1", "research") },
  { name: "Journal reference is preserved", run: () => assertEqual(setup().event.references.journals[0]?.referenceId, "journal-1", "journal") },
  { name: "Prediction reference is preserved", run: () => assertEqual(setup().event.references.predictions[0]?.referenceId, "prediction-1", "prediction") },
  { name: "Strategy reference is preserved", run: () => assertEqual(setup().event.references.strategies[0]?.referenceId, "strategy-1", "strategy") },
  { name: "future Analogy input boundary is preserved", run: () => { const { library, event } = setup(); const pattern = library.finalizePattern(patternInput(event.eventId)).record; const input = { candidateEventIds: [event.eventId], candidatePatternIds: [pattern.patternId], currentEventFeatureReferences: ["current-feature-1"], comparisonDimensions: ["liquidity"], requiredRegimeDimensions: [HistoricalRegimeType.Liquidity], observationHorizons: [HistoricalTimeHorizon.OneMonth], similarityWeightProfileReference: "weights:v1", excludedDimensions: [], missingDataPolicy: "REPORT" as const, evidenceRequirements: ["source-backed"] }; assertDeepEqual(library.prepareAnalogyInput(input), input, "boundary"); } },
  { name: "query by event category", run: () => assertEqual(setup().library.queryEvents({ filter: { eventCategories: [HistoricalEventType.MarketCrash] } }).length, 1, "count") },
  { name: "query by pattern type", run: () => { const { library, event } = setup(); library.finalizePattern(patternInput(event.eventId)); assertEqual(library.queryPatterns({ filter: { patternTypes: [HistoricalPatternType.CreditStress] } }).length, 1, "count"); } },
  { name: "query by date or period", run: () => assertEqual(setup().library.queryEvents({ filter: { fromDate: "2008-01-01T00:00:00.000Z", toDate: "2008-12-31T23:59:59.999Z" } }).length, 1, "count") },
  { name: "query by geography", run: () => assertEqual(setup().library.queryEvents({ filter: { geography: "GLOBAL" } }).length, 1, "count") },
  { name: "query by asset class", run: () => assertEqual(setup().library.queryEvents({ filter: { assetClass: HistoricalAssetClass.Credit } }).length, 1, "count") },
  { name: "query by regime", run: () => assertEqual(setup().library.queryEvents({ filter: { regimeDimension: HistoricalRegimeType.Liquidity, regimeValue: "STRESSED" } }).length, 1, "count") },
  { name: "query by supporting event", run: () => { const { library, event } = setup(); library.finalizePattern(patternInput(event.eventId)); assertEqual(library.queryPatterns({ filter: { sourceEventId: event.eventId } }).length, 1, "count"); } },
  { name: "related-event query", run: () => { const repository = new InMemoryHistoricalPatternRepository(); const library = new HistoricalPatternLibrary(repository, new FixedClock()); const first = library.finalizeEvent(eventInput({ relatedEventIds: ["historical-event:related-two"] })).record; library.finalizeEvent(eventInput({ eventId: "historical-event:related-two", title: "Related event", relatedEventIds: [] })); assertEqual(library.relatedEvents(first.eventId)[0]?.eventId, "historical-event:related-two", "related"); } },
  { name: "related-pattern query", run: () => { const { library, event } = setup(); const first = library.finalizePattern(patternInput(event.eventId, { relatedPatternIds: ["historical-pattern:related-two"] })).record; library.finalizePattern(patternInput(event.eventId, { patternId: "historical-pattern:related-two", title: "Related two" })); assertEqual(library.relatedPatterns(first.patternId)[0]?.patternId, "historical-pattern:related-two", "related"); } },
  { name: "current versus superseded query", run: () => { const { library, event } = setup(); const first = library.finalizePattern(patternInput(event.eventId)).record; const second = library.finalizePattern(patternInput(event.eventId, { patternId: "historical-pattern:current-two", title: "Current two" })).record; library.supersedePattern(supersession(first.patternId, second.patternId)); assertDeepEqual(library.queryPatterns({ filter: { currentOnly: true } }).map((item) => item.patternId), [second.patternId], "current"); } },
  { name: "deterministic pagination", run: () => { const repository = new InMemoryHistoricalPatternRepository(); const library = new HistoricalPatternLibrary(repository, new FixedClock()); library.finalizeEvent(eventInput()); library.finalizeEvent(eventInput({ eventId: "historical-event:page-two", title: "Page two" })); assertEqual(library.queryEvents({ offset: 1, limit: 1 })[0]?.eventId, "historical-event:page-two", "page"); } },
  { name: "deterministic statistics", run: () => { const { library, event } = setup(); library.finalizePattern(patternInput(event.eventId)); assertDeepEqual(library.statistics(), library.statistics(), "statistics"); assertEqual(library.statistics().eventCount, 1, "events"); } },
  { name: "deterministic export ordering", run: () => { const { repository, library, event } = setup(); library.finalizePattern(patternInput(event.eventId)); const request = { exportId: "export-1", requestedAt: "2026-07-19T21:00:00.000Z", query: {}, format: HistoricalExportFormat.Ndjson, destination: HistoricalExportDestination.LocalSnapshot }; const policy = { allowExternalExports: false, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: [] }; assertEqual(exportHistoricalPatterns(repository, request, policy).content, exportHistoricalPatterns(repository, request, policy).content, "export"); } },
  { name: "LOCAL_ONLY export restriction", run: () => { const { repository } = setup(eventInput({ privacyLevel: PrivacyLevel.LocalOnly })); const result = exportHistoricalPatterns(repository, { exportId: "export-local", requestedAt: "2026-07-19T21:00:00.000Z", query: {}, format: HistoricalExportFormat.Json, destination: HistoricalExportDestination.ExternalTransfer }, { allowExternalExports: true, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: [] }); assertEqual(result.status, HistoricalExportStatus.Rejected, "status"); } },
  { name: "SENSITIVE export authorization", run: () => { const { repository } = setup(eventInput({ privacyLevel: PrivacyLevel.Sensitive })); const request = { exportId: "export-sensitive", requestedAt: "2026-07-19T21:00:00.000Z", query: {}, format: HistoricalExportFormat.Json, destination: HistoricalExportDestination.ExternalTransfer }; const policy = { allowExternalExports: true, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: ["approval-1"] }; assertEqual(exportHistoricalPatterns(repository, request, policy).status, HistoricalExportStatus.Rejected, "rejected"); assertEqual(exportHistoricalPatterns(repository, { ...request, sensitiveAuthorizationReference: "approval-1" }, policy).status, HistoricalExportStatus.Exported, "allowed"); } },
  { name: "secret metadata rejection", run: () => expectError(() => setup(eventInput({ metadata: { api_key: "forbidden" } })), "secret") },
  { name: "input immutability", run: () => { const value = eventInput(); const before = JSON.stringify(value); setup(value); assertEqual(JSON.stringify(value), before, "input"); } },
  { name: "defensive copies", run: () => { const { library, event } = setup(); const read = library.getEvent(event.eventId) as typeof event; (read as { title: string }).title = "Mutated"; assertEqual(library.getEvent(event.eventId)?.title, event.title, "copy"); } },
  { name: "corrupt NDJSON fails closed", run: () => { const directory = mkdtempSync(join(tmpdir(), "historical-corrupt-")); try { writeFileSync(join(directory, "historical-pattern-library-v1.ndjson"), "{}"); expectError(() => new LocalNdjsonHistoricalPatternRepository(directory), "truncated"); } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "reload preserves records", run: () => { const directory = mkdtempSync(join(tmpdir(), "historical-reload-")); try { const repository = new LocalNdjsonHistoricalPatternRepository(directory); const library = new HistoricalPatternLibrary(repository, new FixedClock()); const event = library.finalizeEvent(eventInput()).record; library.amendEvent(eventAmendment(event.eventId)); assertEqual(new LocalNdjsonHistoricalPatternRepository(directory).getEventHistory(event.eventId)?.amendments.length, 1, "reload"); } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "durable append does not rewrite history", run: () => { const directory = mkdtempSync(join(tmpdir(), "historical-append-")); try { const repository = new LocalNdjsonHistoricalPatternRepository(directory); const library = new HistoricalPatternLibrary(repository, new FixedClock()); const event = library.finalizeEvent(eventInput()).record; const before = readFileSync(repository.getStoragePath(), "utf8"); library.amendEvent(eventAmendment(event.eventId)); const after = readFileSync(repository.getStoragePath(), "utf8"); assertTrue(after.startsWith(before) && after.length > before.length, "append only"); } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "path traversal is rejected", run: () => { const directory = mkdtempSync(join(tmpdir(), "historical-path-")); try { expectError(() => new LocalNdjsonHistoricalPatternRepository(directory, "../escape"), "path traversal"); } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "audit translation is deterministic", run: () => { const source: HistoricalAuditRecord = { auditId: "historical-audit-1", operationType: HistoricalAuditOperationType.EventFinalized, sourceRecordId: "historical-event:synthetic-crisis-2008", recordId: "historical-event:synthetic-crisis-2008", recordVersion: "v1", recordKind: HistoricalRecordKind.Event, timestamp: "2026-07-19T20:00:00.000Z", status: "FINALIZED", reasonCodes: ["EVENT FINALIZED"], sourceReferenceIds: ["source-1"], evidenceReferenceIds: ["evidence-fact-1"], privacyLevel: PrivacyLevel.Internal, retention: AIAuditRetentionClassification.Permanent, correlationId: "correlation-1", traceId: "trace-1", policyVersions: { historical: "v1" }, metadata: { fixture: true } }; const context = { idempotencyKey: "audit-idempotency-1", actor: { type: AIAuditActorType.Owner, actorId: "owner-1" }, parentAuditRecordIds: [], relatedAuditRecordIds: [] }; const first = auditRecordFromHistoricalPattern(source, context); assertDeepEqual(first, auditRecordFromHistoricalPattern(source, context), "translation"); assertEqual(first.recordType, AIAuditRecordType.HistoricalRecord, "record type"); assertEqual(first.sourceSubsystem, AIAuditSourceSubsystem.HistoricalPatternLibrary, "subsystem"); } },
  { name: "Research records are not mutated", run: () => { const source = { researchId: "research-1", status: "FINALIZED" }; const before = JSON.stringify(source); setup(eventInput({ references: { ...references(), research: [{ referenceId: source.researchId, recordType: HistoricalReferenceType.Research, resolution: HistoricalReferenceResolution.Resolved, version: "v1" }] } })); assertEqual(JSON.stringify(source), before, "research"); } },
  { name: "Journal records are not mutated", run: () => { const source = { entryId: "journal-1", status: "FINALIZED" }; const before = JSON.stringify(source); setup(); assertEqual(JSON.stringify(source), before, "journal"); } },
  { name: "Prediction records are not mutated", run: () => { const source = { predictionId: "prediction-1", status: "LOCKED" }; const before = JSON.stringify(source); setup(); assertEqual(JSON.stringify(source), before, "prediction"); } },
  { name: "Strategy records are not mutated", run: () => { const source = { versionId: "strategy-1", status: "ACTIVE" }; const before = JSON.stringify(source); setup(); assertEqual(JSON.stringify(source), before, "strategy"); } },
  { name: "unresolved reference cannot claim a version", run: () => { const value = references(); expectError(() => setup(eventInput({ references: { ...value, research: [{ referenceId: "research-1", recordType: HistoricalReferenceType.Research, resolution: HistoricalReferenceResolution.Unresolved, version: "v1" }] } })), "unresolved") } },
  { name: "guaranteed recurrence language is rejected", run: () => { const { library, event } = setup(); expectError(() => library.finalizePattern(patternInput(event.eventId, { description: "This pattern will always recur." })), "guaranteed") } },
  { name: "cross-currency aggregation requires conversion evidence", run: () => { const value = reaction({ startValue: { dataReferenceId: "start", value: 100, currency: "USD", sourceReferenceId: "source-1", missing: false }, endValue: { dataReferenceId: "end", value: 90, currency: "EUR", sourceReferenceId: "source-1", missing: false } }); assertEqual(validateHistoricalAssetReaction(value).valid, false, "currency"); } },
  { name: "non-finite numeric values are rejected", run: () => assertEqual(validateHistoricalAssetReaction(reaction({ realizedVolatility: Number.NaN })).valid, false, "finite") },
  { name: "cyclic related-event links are rejected", run: () => { const repository = new InMemoryHistoricalPatternRepository(); const library = new HistoricalPatternLibrary(repository, new FixedClock()); library.finalizeEvent(eventInput({ relatedEventIds: ["historical-event:cycle-two"] })); expectError(() => library.finalizeEvent(eventInput({ eventId: "historical-event:cycle-two", title: "Cycle two", relatedEventIds: ["historical-event:synthetic-crisis-2008"] })), "cyclic") } },
  { name: "cyclic related-pattern links are rejected", run: () => { const { library, event } = setup(); library.finalizePattern(patternInput(event.eventId, { relatedPatternIds: ["historical-pattern:cycle-two"] })); expectError(() => library.finalizePattern(patternInput(event.eventId, { patternId: "historical-pattern:cycle-two", title: "Cycle two", relatedPatternIds: ["historical-pattern:synthetic-liquidity-stress"] })), "cyclic") } },
  { name: "archive preserves record instead of deleting", run: () => { const { library, event } = setup(); library.archiveEvent(event.eventId, "2026-07-19T22:00:00.000Z", "Retention classification remains metadata."); assertEqual(library.getEvent(event.eventId)?.status, HistoricalEventStatus.Archived, "archive"); } },
  { name: "repository exposes no update overwrite or delete", run: () => { const repository: object = new InMemoryHistoricalPatternRepository(); assertTrue(!("update" in repository) && !("overwrite" in repository) && !("delete" in repository), "mutable method exposed"); } },
  { name: "fingerprinting is deterministic and not a signature", run: () => { const first = historicalFingerprint(eventInput()); assertEqual(first, historicalFingerprint(eventInput()), "fingerprint"); assertTrue(first.startsWith("fnv1a64:"), "algorithm marker"); } },
  { name: "factual evidence requires a source", run: () => { const value = eventInput(); expectError(() => setup(eventInput({ evidence: [{ ...value.evidence[0]!, sourceReferenceIds: [] }] })), "require a source") } },
  { name: "pattern privacy cannot downgrade source-event privacy", run: () => { const { library, event } = setup(eventInput({ privacyLevel: PrivacyLevel.Sensitive })); expectError(() => library.finalizePattern(patternInput(event.eventId, { privacyLevel: PrivacyLevel.Internal })), "privacy") } },
];

let passed = 0;
for (const test of tests) { try { test.run(); passed += 1; } catch (error: unknown) { const message = error instanceof Error ? error.message : String(error); console.error(`FAIL: ${test.name}: ${message}`); throw error; } }
console.log(`Historical Pattern Library: ${String(passed)}/${String(tests.length)} tests passed.`);
