import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,cpSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {assessEtfSetup,validateEtfBars,validateEtfSetupPlan,etfMicroUsd} from '../src/engines/options-daily-guidance/OptionsEtfSetup.ts';
import {assessDailyGuidance} from '../src/engines/options-daily-guidance/OptionsDailyGuidance.ts';
import {importEtfBars,registerEtfSetup,verifyEtfSetup,saveEtfSetupAssessment,etfSetupView} from './lib/options-etf-setup-io.mjs';
import {etfSetupPanel,etfSetupRequest} from '../apps/options-workbench/etf-setup.js';
import {startOptionsWorkbench} from './options-workbench.mjs';

let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
const at='2026-09-17T14:05:01.000Z',registered='2026-09-17T13:45:00.000Z';
const uuid=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
const temp=()=>mkdtempSync(join(tmpdir(),'alpha-etf-setup-'));
function cleanup(root){const p=resolve(root);assert.ok(p.startsWith(resolve(tmpdir())+sep)&&p.includes('alpha-etf-setup-'));rmSync(p,{recursive:true,force:true});}
function plan(){return {version:'OPTIONS_ETF_SETUP_PLAN_V1',id:'fixture-only',symbol:'IBIT',side:'BULLISH',setup:'BREAKOUT',activeFrom:'2026-09-17T14:00:00.000Z',timeExit:'2026-09-17T15:00:00.000Z',lower:'42.50',upper:'43.40',invalidation:'42.40',fastBars:3,slowBars:5,bufferBps:10,chaseBps:50,volumeRatioBps:12000,expiryBufferDays:7,targetDeltaBps:5000};}
function bars(){const values=['43.00','43.05','43.10','43.15','43.20','43.455000'];const start=Date.parse('2026-09-17T13:35:00.000Z');return {version:'OPTIONS_ETF_BARS_V1',symbol:'IBIT',intervalMinutes:5,currency:'USD',session:'REGULAR',adjustment:'RAW',volumeUnit:'SHARES',source:'SYNTHETIC_TEST_ONLY',receivedAt:at,windowStart:new Date(start).toISOString(),windowEnd:'2026-09-17T14:05:00.000Z',bars:values.map((v,i)=>({start:new Date(start+i*300000).toISOString(),end:new Date(start+(i+1)*300000).toISOString(),open:v,high:(Number(v)+0.01).toFixed(6),low:(Number(v)-0.01).toFixed(6),close:v,volume:i===5?200:100,complete:true,interpolated:false}))};}
function guidance(){return {version:'OPTIONS_DAILY_GUIDANCE_INPUT_V2',at,captureAt:at,captureOrigin:'HOST_MARKET_TOOL_RESPONSES',captureComplete:true,
 quotes:[{id:uuid(1),symbol:'IBIT',expiry:'2026-10-16',type:'call',strike:'43',multiplier:100,bidCents:145,askCents:150,tickCents:1,bidSize:10,askSize:10,delta:0.5,updatedAt:at,receivedAt:at}],equities:[{symbol:'IBIT',price:'43.455000',sourceAt:at,close:{date:'2026-09-16',price:'43'}}],closeHistory:['2026-09-10','2026-09-11','2026-09-14','2026-09-15','2026-09-16'].map((date,i)=>({symbol:'IBIT',date,price:String(39+i)})),events:[],calendarAvailable:true,headlinesAvailable:true,sourceHealth:[],headlines:[],context:{treasury:null,btc:null},
 settings:{currentEquityCents:100000,settledCashCents:100000,roundTripFeesCents:10,slippageReserveCents:10,stopLossBps:2000,rewardMultipleMilliR:2000,tradeBudget:{version:'OWNER_ALLOCATION_ONLY_V2',minCents:10000,maxCents:50000}},analyst:{assessedAt:at,assets:[{symbol:'IBIT',bias:'BULLISH',summary:'Fixture only',sources:[{url:'https://example.test/',retrievedAt:at}]}]}};}
function input(){return {at,bars:bars(),plan:{registeredAt:registered,value:plan()},guidance:guidance()};}
function later(i,close,{low=Number(close)-0.01,high=Number(close)+0.01}={}){const start=i.bars.windowEnd,end=new Date(Date.parse(start)+300000).toISOString();i.at=new Date(Date.parse(end)+1000).toISOString();i.guidance.at=i.at;i.bars.receivedAt=i.at;i.bars.windowEnd=end;i.bars.bars.push({start,end,open:String(close),close:String(close),low:Number(low).toFixed(6),high:Number(high).toFixed(6),volume:200,complete:true,interpolated:false});}

await test('fractional ETF prices and explicit declared-data match preserve canonical guidance',()=>{const i=input(),before=JSON.stringify(i),canonical=assessDailyGuidance(i.guidance),r=assessEtfSetup(i);assert.equal(etfMicroUsd('43.455000'),43455000n);assert.equal(r.status,'RULE_MATCH_OBSERVED');assert.equal(r.triggerPrice,'43.443400');assert.equal(r.triggerAt,'2026-09-17T14:05:00.000Z');assert.equal(r.trend.direction,'UP');assert.equal(r.source.qualification,'IMPORTED_UNVERIFIED');assert.equal(r.executionAllowed,false);assert.equal(r.winProbability,null);assert.deepEqual(assessDailyGuidance(i.guidance),canonical);assert.equal(JSON.stringify(i),before);assert.ok(r.rows[0].blockers.includes('IMPORTED_SOURCE_NOT_AUTHENTICATED'));});
await test('empty desk never manufactures prices, direction or a plan',()=>{const r=assessEtfSetup({...input(),bars:null,plan:null});assert.equal(r.status,'NOT_ASSESSABLE');assert.equal(r.trend.approximateBarVwap,null);assert.deepEqual(r.rows,[]);assert.ok(r.gaps.includes('ETF_OHLCV_MISSING'));});
for(const [label,change] of [
 ['wrong asset',b=>b.symbol='BTC'],['wrong unit',b=>b.volumeUnit='CONTRACTS'],['unknown adjustment',b=>b.adjustment='UNKNOWN'],['future receipt',b=>b.receivedAt='2026-09-17T15:00:00.000Z'],['incomplete',b=>b.bars[0].complete=false],['unknown interpolation',b=>b.bars[0].interpolated=null],['interpolated',b=>b.bars[0].interpolated=true],['missing bar',b=>b.bars.splice(2,1)],['duplicate bar',b=>b.bars[2]=structuredClone(b.bars[1])],['invalid OHLC',b=>b.bars[0].low='45'],['fractional share volume',b=>b.bars[0].volume=1.5],['off-grid',b=>b.bars[0].start='2026-09-17T13:35:01.000Z'],['future final bar',b=>b.receivedAt='2026-09-17T14:04:00.000Z'],['extra fields',b=>b.approved=true]
])await test('reject '+label,()=>{const b=bars();change(b);assert.throws(()=>validateEtfBars(b,at),/ETF_SETUP_/);});
await test('holiday and early-close boundaries reject bars outside the reviewed session',()=>{for(const [date,hour] of [['2026-09-07','13'],['2026-11-27','18']]){const b=bars();for(const bar of b.bars)for(const k of ['start','end'])bar[k]=date+'T'+hour+bar[k].slice(13);b.windowStart=b.bars[0].start;b.windowEnd=b.bars.at(-1).end;b.receivedAt=date+'T23:00:00.000Z';assert.throws(()=>validateEtfBars(b,b.receivedAt),/ETF_SETUP_/);}});
await test('no retroactive registration, invalid levels or wrong same-session exit',()=>{assert.throws(()=>validateEtfSetupPlan(plan(),at),/PROSPECTIVE/);for(const patch of [{invalidation:'43.8'},{timeExit:'2026-09-18T15:00:00.000Z'},{fastBars:5,slowBars:3},{targetDeltaBps:9999}])assert.throws(()=>validateEtfSetupPlan({...plan(),...patch},registered),/ETF_SETUP_/);});
await test('future activation can wait without reading later data',()=>{const i=input();i.at=registered;i.guidance.at=registered;i.guidance.captureAt=registered;i.guidance.quotes=[];i.bars=null;const r=assessEtfSetup(i);assert.equal(r.triggerAt,null);assert.equal(r.status,'NOT_ASSESSABLE');});
await test('one-bar invalidation wins when the bar also crosses the bullish trigger',()=>{const i=input();i.bars.bars[5].low='42.30';const r=assessEtfSetup(i);assert.equal(r.status,'INVALIDATED');assert.equal(r.triggerAt,null);});
await test('a later failed break is retained; the first match is not erased',()=>{const i=input();later(i,43.25);const r=assessEtfSetup(i);assert.equal(r.status,'FAILED_BREAK');assert.equal(r.triggerAt,'2026-09-17T14:05:00.000Z');assert.equal(r.invalidatedAt,'2026-09-17T14:10:00.000Z');});
await test('trend baseline is frozen before activation; later upside cannot rewrite it',()=>{const i=input(),first=assessEtfSetup(i);later(i,48);assert.deepEqual(assessEtfSetup(i).trend.fastMean,first.trend.fastMean);assert.equal(assessEtfSetup(i).trend.baselineEnd,'2026-09-17T14:00:00.000Z');});
await test('insufficient trigger volume and excess chase do not match',()=>{const i=input();i.bars.bars[5].volume=110;assert.equal(assessEtfSetup(i).triggerAt,null);i.bars.bars[5].volume=200;i.plan.value.chaseBps=1;assert.equal(assessEtfSetup(i).status,'CHASE_LIMIT_EXCEEDED');});
await test('pullback requires a held zone in an earlier bar before resumption',()=>{const i=input();i.plan.value.setup='PULLBACK';assert.equal(assessEtfSetup(i).triggerAt,null);i.bars.bars[5]={...i.bars.bars[5],open:'43.3',high:'43.35',low:'43.2',close:'43.3'};later(i,43.46);assert.equal(assessEtfSetup(i).status,'RULE_MATCH_OBSERVED');});
await test('bearish breakout follows declining completed bars',()=>{const i=input();i.plan.value={...i.plan.value,side:'BEARISH',lower:'43',upper:'43.7',invalidation:'43.8'};for(const [j,b] of i.bars.bars.entries()){const c=j===5?42.945:43.6-j*0.1;b.open=b.close=c.toFixed(6);b.high=(c+0.01).toFixed(6);b.low=(c-0.01).toFixed(6);}const r=assessEtfSetup(i);assert.equal(r.trend.direction,'DOWN');assert.equal(r.status,'RULE_MATCH_OBSERVED');assert.ok(r.rows[0].mechanicalBlockers.includes('OPPOSES_DECLARED_SIDE'));});
await test('key-level resolution uses declared level without pretending a trend exists',()=>{const i=input();i.plan.value.setup='KEY_LEVEL';for(const b of i.bars.bars.slice(0,5)){b.open=b.close='43.2';b.low='43.1';b.high='43.3';}const r=assessEtfSetup(i);assert.equal(r.trend.direction,'RANGE');assert.equal(r.status,'RULE_MATCH_OBSERVED');});
await test('expired window and stale bars cannot become a current entry',()=>{const i=input();i.at='2026-09-17T15:00:00.000Z';i.guidance.at=i.at;const r=assessEtfSetup(i);assert.equal(r.status,'TIME_WINDOW_ENDED');assert.ok(r.limitations.includes('ETF_BARS_NOT_FRESH'));assert.ok(r.limitations.includes('SETUP_WINDOW_CLOSED'));});
await test('missing costs, budget, expiry and source blockers survive contract ranking',()=>{const i=input();i.guidance.settings.roundTripFeesCents=null;i.plan.value.expiryBufferDays=45;i.guidance.quotes[0].askCents=600;const r=assessEtfSetup(i).rows[0];assert.ok(r.blockers.includes('COSTS_UNKNOWN'));assert.ok(r.blockers.includes('EXPIRY_BEFORE_HORIZON_AND_BUFFER'));assert.ok(r.blockers.some(v=>v.includes('BUDGET')));});
await test('delta-fit outranks a cheaper but less aligned contract; input order is irrelevant',()=>{const i=input(),q=i.guidance.quotes[0];i.guidance.quotes.push({...q,id:uuid(2),delta:0.36,bidCents:110,askCents:115});const first=assessEtfSetup(i);assert.equal(first.rows[0].contract.id,uuid(1));i.guidance.quotes.reverse();assert.deepEqual(assessEtfSetup(i).rows,first.rows);});
await test('cross-symbol bars cannot supply setup confirmation',()=>{const i=input();i.bars.symbol='GLD';assert.throws(()=>assessEtfSetup(i),/SYMBOL_MISMATCH/);});
await test('durable plan/import/snapshot recovers from copies with no original sources',()=>{const root=temp(),isolated=temp();try{const p=registerEtfSetup(root,plan(),registered);assert.throws(()=>registerEtfSetup(root,plan(),registered),/PLAN_ID_EXISTS/);const b=importEtfBars(root,bars(),at);const r=saveEtfSetupAssessment(root,guidance(),plan().id,at);for(const saved of [p,b,r])verifyEtfSetup(root,saved.path);const target=join(isolated,r.path);mkdirSync(resolve(target,'..'),{recursive:true});cpSync(join(root,r.path),target);const recovered=verifyEtfSetup(isolated,r.path);assert.equal(recovered.report.status,'RULE_MATCH_OBSERVED');const bad=JSON.parse(readFileSync(target,'utf8'));bad.input.bars.bars[0].close='999';writeFileSync(target,JSON.stringify(bad));assert.throws(()=>verifyEtfSetup(isolated,r.path),/INTEGRITY/);}finally{cleanup(root);cleanup(isolated);}});
await test('real frontend component preserves gaps and escapes source text',()=>{const root=temp();try{const d=etfSetupView(root,guidance(),at);assert.equal(d.assets[0].symbol,'GLD');assert.equal(d.assets[1].symbol,'IBIT');d.sourceCapability='<img src=x onerror=alert(1)>';const html=etfSetupPanel({data:d});assert.ok(html.includes('No ETF OHLCV evidence saved'));assert.ok(html.includes('Freeze local research rule'));assert.ok(!html.includes('<img'));assert.ok(html.includes('&lt;img'));}finally{cleanup(root);}});
await test('form uses explicit device times and preserves ETF fractional levels',()=>{const p=plan(),f={...p,activeFrom:p.activeFrom,timeExit:p.timeExit};const r=etfSetupRequest(f);assert.equal(r.activeFrom,p.activeFrom);assert.equal(r.upper,p.upper);assert.throws(()=>etfSetupRequest({...f,activeFrom:''}),/valid/);});
await test('static module is served and research writes require existing session protection',async()=>{const app=await startOptionsWorkbench({port:0,refreshContext:false});try{const r=await fetch(app.url+'/etf-setup.js');assert.equal(r.status,200);const denied=await fetch(app.url+'/api/etf-setup',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});assert.equal(denied.status,403);}finally{await app.close();}});
await test('a later extended price fails the chase limit even after an earlier match',()=>{const i=input();later(i,44);const r=assessEtfSetup(i);assert.equal(r.status,'CHASE_LIMIT_EXCEEDED');assert.ok(r.triggerAt);assert.deepEqual(r.referenceIds,[]);});
await test('authenticated local API saves a frozen rule and preserves failures with no brokerage calls',async()=>{
  const root=temp();let time=registered;const app=await startOptionsWorkbench({port:0,refreshContext:false,workspaceRoot:root,now:()=>time});
  try{
    const state=await (await fetch(app.url+'/api/state')).json();
    const post=async(action,request)=>fetch(app.url+'/api/etf-setup',{method:'POST',headers:{origin:app.url,'content-type':'application/json','x-alpha-session':state.session},body:JSON.stringify({action,request})});
    const p=await post('REGISTER',plan());assert.equal(p.status,200);const stored=await p.json();verifyEtfSetup(root,stored.path);
    const repeated=await post('REGISTER',plan());assert.equal(repeated.status,409);
    time=at;const b=await post('IMPORT',bars());assert.equal(b.status,200);
    const report=await post('SNAPSHOT',plan().id);assert.equal(report.status,200);const saved=await report.json();assert.equal(verifyEtfSetup(root,saved.path).report.status,'RULE_MATCH_OBSERVED');
    const bad=bars();bad.bars[0].interpolated=null;const rejected=await post('IMPORT',bad);assert.equal(rejected.status,409);assert.match(JSON.stringify(await rejected.json()),/ETF_SETUP_BAR_FLAGS/);
  }finally{await app.close();cleanup(root);}
});
console.log(`ETF setup: ${passed}/${passed} tests passed.`);
