import assert from "node:assert/strict";
import fs from "node:fs";
import { syncBuiltinESMExports } from "node:module";
import { appendFileSync, existsSync, linkSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, truncateSync, unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { isAbsolute, join, relative, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { runOptionsEvidenceExportCommand as run } from "./options-evidence-export.mjs";
import { exportFingerprint } from "../src/engines/options-evidence-export/OptionsEvidenceExportEngine.ts";
const root=resolve(import.meta.dirname,".."),at="2026-09-07T05:00:00.000Z",study="test-study",id="test-package";
const planPath=`data/runtime/options-robinhood-data/studies/${study}/plan.json`,paperPath="data/runtime/options-paper/sessions.ndjson",base=`data/runtime/options-evidence-exports/${id}`;
const execute=(directory,args,now=()=>at)=>run(args,{workspaceRoot:directory,now});
const create=directory=>execute(directory,["--create",study,id]),verify=directory=>execute(directory,["--verify",id]);
function write(directory,path,bytes){mkdirSync(join(directory,path,".."),{recursive:true});writeFileSync(join(directory,path),bytes);}
function seed(directory){write(directory,planPath,Buffer.from('{"sourceClock":"2026-09-04T14:00:00Z"}\r\n'));write(directory,paperPath,Buffer.from('{"review":"synthetic retained bytes"}\n'));}
async function temporary(work){const directory=mkdtempSync(join(tmpdir(),"alpha-export-test-"));try{await work(directory);}finally{const rel=relative(tmpdir(),directory);if(isAbsolute(rel)||rel.startsWith("..")||!rel.startsWith("alpha-export-test-"))throw Error("UNSAFE_TEST_CLEANUP");rmSync(directory,{recursive:true});}}
function manifest(directory){return JSON.parse(readFileSync(join(directory,base,"manifest.json"),"utf8"));}
function changeManifest(directory,change,rehash=true){const m=manifest(directory);change(m);if(rehash){const{manifestSha256,...body}=m;m.manifestSha256=exportFingerprint(body);}writeFileSync(join(directory,base,"manifest.json"),JSON.stringify(m,null,2)+"\n");}
let passed=0;async function test(name,work){await work();passed++;console.log(`PASS ${name}`);}
await test("exact bytes, CRLF and embedded source clocks survive create and independent verify",()=>temporary(directory=>{seed(directory);const original=readFileSync(join(directory,planPath)),r=create(directory),m=manifest(directory),entry=m.files.find(f=>f.sourcePath===planPath);assert.deepEqual(readFileSync(join(directory,base,entry.payloadName)),original);assert.deepEqual(readFileSync(join(directory,planPath)),original);assert.equal(r.fileCount,2);assert.equal(verify(directory).sourceStoresRead,false);assert.equal(r.manifestSha256,verify(directory).manifestSha256);}));
await test("missing optional stores are recorded without creating them",()=>temporary(directory=>{write(directory,planPath,"original");const r=create(directory);assert(r.missingComponents.includes("paper"));assert.equal(existsSync(join(directory,"data/runtime/options-paper")),false);assert.equal(r.semanticValidationPerformed,false);}));
await test("missing selected study cannot create an apparently valid package",()=>temporary(directory=>{assert.throws(()=>create(directory),/PLAN_REQUIRED/);assert.equal(existsSync(join(directory,"data/runtime/options-evidence-exports")),false);}));
await test("verification remains independent after current source data changes or disappears",()=>temporary(directory=>{seed(directory);create(directory);const before=verify(directory).manifestSha256;writeFileSync(join(directory,paperPath),"new source");unlinkSync(join(directory,planPath));assert.equal(verify(directory).manifestSha256,before);}));
await test("existing valid or partial package IDs cannot be overwritten or resumed",()=>temporary(directory=>{seed(directory);create(directory);const bytes=readFileSync(join(directory,base,"manifest.json"));assert.throws(()=>create(directory),/ALREADY_EXISTS/);assert.deepEqual(readFileSync(join(directory,base,"manifest.json")),bytes);unlinkSync(join(directory,base,"manifest.json"));assert.throws(()=>create(directory),/ALREADY_EXISTS/);assert.throws(()=>verify(directory));}));
await test("source locks block export without removing or reading their contents",()=>temporary(directory=>{seed(directory);const lock="data/runtime/options-paper/writer.lock";write(directory,lock,"PRIVATE_LOCK");assert.throws(()=>create(directory),/SOURCE_LOCKED/);assert.equal(readFileSync(join(directory,lock),"utf8"),"PRIVATE_LOCK");assert.equal(existsSync(join(directory,base)),false);}));
await test("study and closeout writer locks also prevent a mixed snapshot",()=>temporary(directory=>{seed(directory);for(const kind of ["studies","collection-attempts","collection-reports"]){const lock=`data/runtime/options-robinhood-data/${kind}/${study}/writer.lock`;write(directory,lock,"");assert.throws(()=>create(directory),/SOURCE_LOCKED/);unlinkSync(join(directory,lock));}}));
await test("source hard links and directory junctions cannot escape the allowlist",()=>temporary(directory=>{seed(directory);linkSync(join(directory,paperPath),join(directory,"paper-alias"));assert.throws(()=>create(directory),/UNSAFE_FILE/);unlinkSync(join(directory,"paper-alias"));const other=join(directory,"other");mkdirSync(other);symlinkSync(other,join(directory,"data/runtime/options-evidence-exports"),"junction");assert.throws(()=>create(directory),/UNSAFE_PATH/);assert.deepEqual(readdirSync(other),[]);}));
await test("unrecognized study entries block instead of silently omitting partial evidence",()=>temporary(directory=>{seed(directory);write(directory,planPath.replace("plan.json","pending.tmp"),"partial");assert.throws(()=>create(directory),/SOURCE_SCOPE/);}));
await test("source inspection never follows filenames embedded in JSON bodies",()=>temporary(directory=>{seed(directory);writeFileSync(join(directory,planPath),'{"path":"../../.env","instruction":"DELETE_HISTORY"}');writeFileSync(join(directory,".env"),"DO_NOT_READ");const r=create(directory);assert.equal(r.fileCount,2);assert(!JSON.stringify(manifest(directory)).includes(".env"));assert.equal(readFileSync(join(directory,".env"),"utf8"),"DO_NOT_READ");}));
await test("byte archives explicitly preserve corrupt source records without certifying recovery",()=>temporary(directory=>{seed(directory);writeFileSync(join(directory,paperPath),Buffer.from([0xff,0x00,0x7b]));const r=create(directory),m=manifest(directory);assert.equal(r.semanticValidationPerformed,false);const entry=m.files.find(f=>f.sourcePath===paperPath);assert.deepEqual(readFileSync(join(directory,base,entry.payloadName)),Buffer.from([0xff,0x00,0x7b]));}));
await test("per-source size bounds reject before package creation",()=>temporary(directory=>{seed(directory);truncateSync(join(directory,planPath),2*1024*1024+1);assert.throws(()=>create(directory),/UNSAFE_FILE/);assert.equal(existsSync(join(directory,base)),false);}));
await test("source inventory changes during copying leave no final manifest",()=>temporary(directory=>{seed(directory);const original=fs.writeFileSync;let changed=false;fs.writeFileSync=(file,bytes,...rest)=>{original(file,bytes,...rest);if(!changed){changed=true;original(join(directory,planPath),"changed during export");}};syncBuiltinESMExports();try{assert.throws(()=>create(directory),/SOURCE_CHANGED/);}finally{fs.writeFileSync=original;syncBuiltinESMExports();}assert(existsSync(join(directory,base)));assert.equal(existsSync(join(directory,base,"manifest.json")),false);}));
await test("new source entries during copying are detected at the second inventory",()=>temporary(directory=>{seed(directory);const original=fs.writeFileSync;let changed=false;fs.writeFileSync=(file,bytes,...rest)=>{original(file,bytes,...rest);if(!changed){changed=true;original(join(directory,planPath.replace("plan.json","frame-0001.json")),"new frame");}};syncBuiltinESMExports();try{assert.throws(()=>create(directory),/SOURCE_CHANGED/);}finally{fs.writeFileSync=original;syncBuiltinESMExports();}assert.equal(existsSync(join(directory,base,"manifest.json")),false);}));
await test("fsync failure preserves incomplete payload without an automatic retry",()=>temporary(directory=>{seed(directory);const original=fs.fsyncSync;fs.fsyncSync=()=>{throw Error("TEST_SYNC_FAILURE");};syncBuiltinESMExports();try{assert.throws(()=>create(directory),/TEST_SYNC_FAILURE/);}finally{fs.fsyncSync=original;syncBuiltinESMExports();}assert.equal(existsSync(join(directory,base,"manifest.json")),false);assert.throws(()=>create(directory),/ALREADY_EXISTS/);assert.equal(readFileSync(join(directory,paperPath),"utf8"),'{"review":"synthetic retained bytes"}\n');}));
await test("changed, missing and extra payloads cannot verify",()=>temporary(directory=>{seed(directory);create(directory);const path=join(directory,base,manifest(directory).files[0].payloadName),original=readFileSync(path);writeFileSync(path,"changed");assert.throws(()=>verify(directory),/PAYLOAD_MISMATCH/);writeFileSync(path,original);writeFileSync(join(directory,base,"extra.bin"),"");assert.throws(()=>verify(directory),/PACKAGE_ENTRIES/);unlinkSync(join(directory,base,"extra.bin"));unlinkSync(path);assert.throws(()=>verify(directory),/PACKAGE_ENTRIES/);}));
await test("manifest source mapping cannot be redirected even with a new checksum",()=>temporary(directory=>{seed(directory);create(directory);changeManifest(directory,m=>{m.files[0].sourcePath=".env";});assert.throws(()=>verify(directory),/SOURCE_SCOPE/);}));
await test("manifest hash and canonical bytes detect edits and duplicate keys",()=>temporary(directory=>{seed(directory);create(directory);const path=join(directory,base,"manifest.json"),original=readFileSync(path,"utf8");changeManifest(directory,m=>{m.completedAt="2026-09-07T05:00:00.001Z";},false);assert.throws(()=>verify(directory),/MANIFEST_HASH/);writeFileSync(path,original.replace('"packageId": "test-package"','"packageId":"wrong","packageId": "test-package"'));assert.throws(()=>verify(directory),/MANIFEST_ENCODING/);}));
await test("package hard links are refused without following their targets",()=>temporary(directory=>{seed(directory);create(directory);const path=join(directory,base,manifest(directory).files[0].payloadName);linkSync(path,join(directory,"alias.bin"));assert.throws(()=>verify(directory),/UNSAFE_FILE/);}));
await test("actual export clocks record operation boundaries and verification time",()=>temporary(directory=>{seed(directory);let ticks=0;const r=execute(directory,["--create",study,id],()=>new Date(Date.parse(at)+ticks++).toISOString());assert(r.startedAt<r.completedAt);assert(r.completedAt<r.verifiedAt);assert.throws(()=>execute(directory,["--verify",id],()=>at),/VERIFICATION_CLOCK/);}));
await test("invalid IDs and unsafe commands cannot touch source or output paths",()=>temporary(directory=>{seed(directory);for(const args of [["--create",study,"../bad"],["--create","../bad",id],["--verify","con"],["--restore",id],["--create",study,id,"--overwrite"]])assert.throws(()=>execute(directory,args));assert.equal(existsSync(join(directory,base)),false);}));
await test("help and CLI errors expose no network, restore or source-writing capability",()=>{assert.match(run(["--help"],{workspaceRoot:"nonexistent"}).meaning,/No network/);for(const args of [["--restore",id],["--url","https://example.invalid"],["--verify","../bad"]]){const r=spawnSync(process.execPath,["node_modules/tsx/dist/cli.mjs","scripts/options-evidence-export.mjs",...args],{cwd:root,encoding:"utf8"});assert.equal(r.status,2);assert.equal(JSON.parse(r.stderr).executionAllowed,false);}});
console.log(`${passed}/${passed} tests passed.`);
