import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,writeFileSync,rmSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,relative,isAbsolute} from 'node:path';
import {runInNewContext} from 'node:vm';
import {assessPositionWatch,positionExitCost} from '../src/engines/options-manual-ledger/OptionsPositionWatch.ts';
import {reconcileManualLedger} from '../src/engines/options-manual-ledger/OptionsManualLedger.ts';
import {paperFingerprint} from '../src/engines/options-paper/OptionsPaperTradingEngine.ts';
import {watchClock as at,watchInput,watchCommands,watchFrame,watchId,watchQuote,seedPositionWatch} from './lib/options-position-watch-fixtures.mjs';
import {createWorkbenchData} from './lib/options-workbench-data.mjs';
import {readManualLedger} from './options-manual-ledger.mjs';
import {startOptionsWorkbench} from './options-workbench.mjs';
import {positionWatchRequest,positionWatchResult,positionWatchPanel,positionWatchPreviewMatches} from '../apps/options-workbench/position-watch.js';

let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
const run=(frame=watchFrame(),cost=null,input=watchInput(),clock=at(0))=>assessPositionWatch(reconcileManualLedger(input,clock),frame,clock,{[watchId]:cost});
const row=(...args)=>run(...args).rows[0];
async function temp(fn){const root=mkdtempSync(join(tmpdir(),'alpha-position-watch-'));try{await fn(root);}finally{const path=realpathSync(root),rel=relative(realpathSync(tmpdir()),path);if(isAbsolute(rel)||rel.startsWith('..')||!rel.startsWith('alpha-position-watch-'))throw Error('UNSAFE_TEST_CLEANUP');rmSync(path,{recursive:true,force:true});}}

await test('partial closes and all known historical fees count once in whole-trade net',()=>{
  const r=row(watchFrame(),'1.00');assert.equal(r.openContracts,2);assert.equal(r.realizedNetPnlUsd,'19.970000');assert.equal(r.remainingCostBasisUsd,'200.020000');assert.equal(r.netCashFlowUsd,'-180.050000');assert.equal(r.liquidationValueAtBidUsd,'300.000000');assert.equal(r.fullTradePnlBeforeFutureExitCostsUsd,'119.950000');assert.equal(r.estimatedFullTradeNetPnlUsd,'118.950000');assert.equal(r.checks.target,'OBSERVED_AT_OR_ABOVE_TARGET_UNDER_ASSUMPTION');assert.equal(r.actualExitConfirmed,false);
});
await test('unknown future costs retain a before-cost reference and unknown target',()=>{const r=row();assert.equal(r.estimatedFullTradeNetPnlUsd,null);assert.equal(r.assumedRemainingExitCostUsd,null);assert.equal(r.checks.target,'UNKNOWN_EXIT_COSTS');assert.equal(r.status,'CHECKS_INCOMPLETE');});
await test('unknown historical entry or partial-exit fees cannot produce net target evidence',()=>{for(const index of [1,2]){const c=watchCommands();c[index].fill.feesUsd=null;const r=row(watchFrame(),'0',watchInput(c));assert.equal(r.liquidationValueAtBidUsd,'300.000000');assert.equal(r.estimatedFullTradeNetPnlUsd,null);assert.equal(r.checks.target,'UNKNOWN_RECORDED_FEES');}});
await test('micro-dollar allocated fees and exact target boundary remain exact',()=>{const c=watchCommands();c[1].fill.feesUsd='0.000001';c[2].fill.feesUsd='0.000001';c[0].plan.targetNetProfitUsd='119.999998';const r=row(watchFrame(),'0',watchInput(c));assert.equal(r.estimatedFullTradeNetPnlUsd,'119.999998');assert(r.checks.target.startsWith('OBSERVED'));assert.equal(row(watchFrame(),'0.000001',watchInput(c)).checks.target,'NOT_OBSERVED');});
await test('stop boundary is inclusive and never creates a fill',()=>{const f=watchFrame();f.quotes[0].bidCents=80;f.quotes[0].askCents=81;const r=row(f,'0');assert.equal(r.checks.stop,'OBSERVED_AT_OR_BELOW_STOP');assert(r.attentionReasons.includes('STOP_REFERENCE_REACHED'));assert.equal(r.actualExitConfirmed,false);assert.equal(r.openContracts,2);f.quotes[0].bidCents=81;assert.equal(row(f,'0').checks.stop,'NOT_OBSERVED');});
await test('time exit remains due with missing and stale market evidence',()=>{for(const f of [null,watchFrame()]){const r=row(f,null,watchInput(),at(3600));assert.equal(r.checks.time,'DUE_UNRESOLVED');assert.equal(r.liquidationValueAtBidUsd,null);assert(r.attentionReasons.includes('TIME_EXIT_DUE'));assert.equal(r.status,'MANUAL_REVIEW_REQUIRED');}});
await test('expiry day and past expiry preserve the unresolved position',()=>{for(const [date,status]of [['2026-09-25','EXPIRY_DAY_REVIEW'],['2026-09-26','PAST_EXPIRY_UNRESOLVED']]){const r=row(null,null,watchInput(),date+'T14:00:00.000Z');assert.equal(r.checks.expiry,status);assert.equal(r.openContracts,2);assert.equal(r.actualExitConfirmed,false);}});
await test('missing plan does not acquire default stops or targets',()=>{const c=watchCommands();c[0].plan=null;const r=row(watchFrame(),'0',watchInput(c));assert.deepEqual([r.checks.stop,r.checks.target,r.checks.time],['NOT_DECLARED','NOT_DECLARED','NOT_DECLARED']);});
await test('exact strike formatting matches but different expiry, type or multiplier do not',()=>{assert(row().usableQuote);for(const [key,value]of [['strike','400.01'],['expiry','2026-09-24'],['type','put'],['multiplier',10]]){const f=watchFrame();f.quotes[0][key]=value;assert(row(f).quoteBlockers.includes('CONTRACT_NOT_IN_LATEST_CAPTURE'));}});
await test('duplicate instruments remain ambiguous instead of choosing the better bid',()=>{const f=watchFrame();f.quotes.push({...f.quotes[0],id:'another-id',bidCents:180});const r=row(f);assert.equal(r.quote,null);assert.equal(r.liquidationValueAtBidUsd,null);assert(r.quoteBlockers.includes('CONTRACT_IDENTITY_AMBIGUOUS'));});
await test('owner and synthetic origins cannot mix',()=>{const input=watchInput();input.origin='OWNER_REPORTED_UNVERIFIED';assert(row(watchFrame(),'0',input).quoteBlockers.includes('SOURCE_ORIGIN_MISMATCH'));const f=watchFrame();f.origin='HOST_MARKET_TOOL_RESPONSES';assert(row(f,'0',input).usableQuote);assert(row(f).quoteBlockers.includes('SOURCE_ORIGIN_MISMATCH'));});
await test('source current-age boundary uses exact nanoseconds and underlying freshness',()=>{assert(row(watchFrame(),'0',watchInput(),at(60)).usableQuote);const edge=watchFrame();edge.quotes[0].updatedAt='2026-09-08T13:59:59.999999999Z';const r=row(edge,'0',watchInput(),at(60));assert(r.quoteBlockers.includes('OPTION_STALE_NOW'));const f=watchFrame();f.quotes[0].underlyingAt=at(-1);assert(row(f,'0',watchInput(),at(60)).quoteBlockers.includes('UNDERLYING_STALE_NOW'));});
await test('freshness at receipt and source after receipt are independently blocked',()=>{for(const [value,code]of [[at(-61),'STALE_AT_RECEIPT'],[at(1),'SOURCE_AFTER_RECEIPT'],[null,'SOURCE_CLOCK_MISSING']]){const f=watchFrame();f.quotes[0].updatedAt=value;const r=row(f);assert(r.quoteBlockers.includes(code));assert.equal(r.estimatedFullTradeNetPnlUsd,null);}});
await test('future capture cannot establish an exit even with an older quote',()=>{const f=watchFrame();f.recordedAt=at(1);assert(row(f).quoteBlockers.includes('FUTURE_CAPTURE'));});
await test('quote must follow the latest reported partial execution',()=>{const f=watchFrame();f.quotes[0].updatedAt=at(-41);assert(row(f).quoteBlockers.includes('QUOTE_PRECEDES_REPORTED_EXECUTION'));});
await test('zero bid, insufficient displayed size and crossed prices cannot value all contracts',()=>{for(const patch of [{bidCents:0},{bidSize:1},{bidCents:152},{askSize:null}]){const f=watchFrame();Object.assign(f.quotes[0],patch);const r=row(f);assert(!r.usableQuote);assert.equal(r.liquidationValueAtBidUsd,null);}});
await test('current session, early close and unknown-year checks stay explicit',()=>{for(const clock of ['2026-09-08T20:15:00.000Z','2026-11-27T18:15:00.000Z','2027-09-08T14:00:00.000Z']){const f=watchFrame();const r=row(f,'0',watchInput(),clock);assert(r.quoteBlockers.includes('CURRENT_SESSION_CLOSED_OR_UNREVIEWED'));assert.equal(r.liquidationValueAtBidUsd,null);}});
await test('closed or voided positions disappear without source-driven ledger writes',()=>{for(const replace of [null,{...watchCommands()[2].fill,quantity:3}]){const c=watchCommands();if(replace===null)c.splice(2,1);c.push({type:'CORRECT_FILL',requestId:'correction',tradeId:watchId,fillId:replace===null?'buy-one':'sell-one',expectedRevision:1,reason:'Synthetic correction',replacement:replace});const input=watchInput(c),ledger=reconcileManualLedger(input,at(0)),before=paperFingerprint(input);const r=assessPositionWatch(ledger,watchFrame(),at(0));assert.equal(r.rows.length,0);assert.equal(paperFingerprint(input),before);assert.equal(r.executionAllowed,false);}});
await test('cost and clock inputs reject unknown trades and invalid monetary assumptions',()=>{for(const v of ['-1','1e2',{},undefined,'1000001'])assert.throws(()=>positionExitCost(v));assert.equal(positionExitCost('0'),'0.000000');const ledger=reconcileManualLedger(watchInput(),at(0));assert.throws(()=>assessPositionWatch(ledger,null,at(1)),/LEDGER_CLOCK/);assert.throws(()=>assessPositionWatch(ledger,null,at(0),{other:'0'}),/COST_FIELDS/);});
await test('frontend labels estimates, preserves unknowns and escapes source text',()=>{const r=run(),html=positionWatchPanel({data:r});assert(html.includes('Unknown'));assert(html.includes('UNKNOWN')===false);assert(html.includes('Position exit checks'));assert(html.includes('Nothing is saved'));const x=structuredClone(r.rows[0]);x.source.path='<script>bad</script>';assert(!positionWatchPanel({data:{...r,rows:[x]}}).includes('<script>'));assert.equal(positionWatchRequest(watchId,' ').exitCostUsd,null);assert.equal(positionWatchRequest(watchId,'0').exitCostUsd,'0');assert.throws(()=>positionWatchRequest(watchId,'1.001'));});
await test('editing an exit-cost draft clears its prior result without mutating other drafts',()=>{const app=readFileSync(new URL('../apps/options-workbench/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf('function updateDraft(el){'),app.indexOf('function prepareContract(row){'));const r=run(),ui={positionCostPreviews:{[watchId]:{old:true},other:{kept:true}}},panel={innerHTML:'Old assumption'},state={positionWatch:{data:r}};const form={dataset:{positionCost:watchId}};runInNewContext(code+'\nupdateDraft(el);',{el:{name:'exitCostUsd',value:'1.00',closest:()=>form},ui,state,positionWatchResult,document:{querySelector:()=>panel}});assert.equal(ui.positionCostDrafts[watchId],'1.00');assert.equal(ui.positionCostPreviews[watchId],undefined);assert(ui.positionCostPreviews.other);assert.equal(panel.innerHTML,positionWatchResult(r.rows[0],r.assessedAt));});
await test('saved-source state and protected preview use the same ledger without mutations',()=>temp(async root=>{
  await seedPositionWatch(root);const options={workspaceRoot:root,ledgerId:'synthetic-watch',now:()=>at(0)},before=readManualLedger(root,options.ledgerId,options.now).files.map(f=>({path:f.path,bytes:f.bytes}));
  const service=createWorkbenchData(options),state=await service.state();assert.equal(state.positionWatch.state,'AVAILABLE');assert.equal(state.positionWatch.data.rows[0].checks.target,'UNKNOWN_EXIT_COSTS');assert.equal(service.positionWatch({tradeId:watchId,exitCostUsd:'1'}).rows[0].estimatedFullTradeNetPnlUsd,'118.950000');
  const app=await startOptionsWorkbench({...options,port:0});try{const initial=await(await fetch(app.url+'/api/state')).json(),headers={'Origin':app.url,'Content-Type':'application/json','X-Alpha-Session':initial.session};const post=(body,extra={})=>fetch(app.url+'/api/position-watch',{method:'POST',headers:{...headers,...extra},body:JSON.stringify(body)});
    assert.equal((await post({tradeId:watchId,exitCostUsd:'1'},{'X-Alpha-Session':''})).status,403);assert.equal((await post({tradeId:watchId,exitCostUsd:'1'},{Origin:'https://example.com'})).status,403);
    const response=await post({tradeId:watchId,exitCostUsd:'1'});assert.equal(response.status,200);const result=await response.json();assert.equal(result.rows[0].estimatedFullTradeNetPnlUsd,'118.950000');assert.equal(result.executionAllowed,false);assert.equal(result.sourceRefresh,false);
    for(const body of [{tradeId:watchId,exitCostUsd:'1',save:true},{tradeId:'other',exitCostUsd:null},{tradeId:watchId,exitCostUsd:-1}])assert.equal((await post(body)).status,409);
  }finally{await app.close();}
  for(const f of before)assert.deepEqual(readFileSync(join(root,f.path)),f.bytes);assert.equal(readManualLedger(root,options.ledgerId,options.now).files.length,before.length);
}));
await test('GLD and IBIT puts and calls use the same exact contract identity',()=>{for(const symbol of ['GLD','IBIT'])for(const optionType of ['CALL','PUT']){const c=watchCommands();c[0].contract.symbol=symbol;c[0].contract.optionType=optionType;const f=watchFrame();f.quotes[0].symbol=symbol;f.quotes[0].type=optionType.toLowerCase();assert(row(f,'0',watchInput(c)).usableQuote);}});
await test('malformed quote clocks retain time checks while market values stay unknown',()=>{const f=watchFrame();f.quotes[0].updatedAt='bad';f.quotes[0].underlyingAt='bad';const r=row(f,null,watchInput(),at(3600));assert.equal(r.checks.time,'DUE_UNRESOLVED');assert.equal(r.liquidationValueAtBidUsd,null);assert(r.quoteBlockers.includes('SOURCE_CLOCK_MISSING'));});
await test('new quote provenance follows the preview but changed fill evidence rejects reuse',()=>{const base=run(),f=watchFrame(1),next=run(f,'1',watchInput(),at(1));assert(positionWatchPreviewMatches(base,next,watchId));const html=positionWatchPanel({data:base},{positionCostPreviews:{[watchId]:next}});assert(html.includes('watch-1.json'));assert(!html.includes('watch-0.json'));assert(!positionWatchPreviewMatches(base,{...next,ledgerEventsFingerprint:'changed'},watchId));assert(!positionWatchPreviewMatches(base,{...next,ledgerId:'other'},watchId));assert(!positionWatchPreviewMatches(base,{...next,rows:[]},watchId));});
await test('failed quote recovery cannot suppress a due time exit',()=>temp(async root=>{await seedPositionWatch(root);writeFileSync(join(root,watchFrame().path),'{}');const service=createWorkbenchData({workspaceRoot:root,ledgerId:'synthetic-watch',now:()=>at(3600)}),state=await service.state();assert.equal(state.snapshotPaper.state,'BLOCKED');assert.equal(state.positionWatch.state,'AVAILABLE');assert.equal(state.positionWatch.data.sourceRecovery,'UNAVAILABLE');assert.equal(state.positionWatch.data.rows[0].checks.time,'DUE_UNRESOLVED');assert.equal(service.positionWatch({tradeId:watchId,exitCostUsd:null}).rows[0].checks.time,'DUE_UNRESOLVED');}));
await test('valid trade IDs cannot inherit costs or previews from object prototypes',()=>{const commands=watchCommands();for(const c of commands)c.tradeId='constructor';const ledger=reconcileManualLedger(watchInput(commands),at(0)),r=assessPositionWatch(ledger,watchFrame(),at(0));assert.equal(r.rows[0].assumedRemainingExitCostUsd,null);assert(positionWatchPanel({data:r},{positionCostPreviews:{},positionCostDrafts:{}}).includes('Unknown Exit Costs'));assert.equal(assessPositionWatch(ledger,watchFrame(),at(0),{constructor:'1'}).rows[0].estimatedFullTradeNetPnlUsd,'118.950000');});
console.log(`Position watch tests passed: ${passed}/${passed}.`);
