import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve,relative,isAbsolute} from 'node:path';
import {evaluateOptionsPlanningFeasibility as evaluate,validateTradeBudget} from '../src/engines/options-retail-feasibility/OptionsTradeBudget.ts';
import {evaluateOptionsRetailFeasibility as legacy} from '../src/engines/options-retail-feasibility/OptionsRetailFeasibilityEngine.ts';
import {assessOptionsCapitalPolicy as preflight} from '../src/engines/options-retail-feasibility/OptionsCapitalPolicy.ts';
import {assessOptionsCostDesk as costDesk} from '../src/engines/options-retail-feasibility/OptionsCostDesk.ts';
import {assessDailyGuidance,defaultGuidanceSettings} from '../src/engines/options-daily-guidance/OptionsDailyGuidance.ts';
import {assessCandidateChecks} from '../src/engines/options-daily-guidance/OptionsCandidateChecks.ts';
import {assessEventResearch} from '../src/engines/options-event-research/OptionsEventResearch.ts';
import {saveGuidanceSettings,guidanceSettings} from './lib/options-guidance-io.mjs';
import {saveCandidateChecks,readCandidateChecks} from './lib/options-candidate-checks-io.mjs';
import {plannerDefaults,plannerBudgetDraft,buildScenario,tradeBudgetFromFields,plannerForm} from '../apps/options-workbench/forms.js';
import {policySettingsFromFields,capitalPolicyPanel} from '../apps/options-workbench/capital-policy.js';
import {guidancePage} from '../apps/options-workbench/guidance.js';
import {candidateChecksPanel,candidateCheckDetail} from '../apps/options-workbench/candidate-checks.js';
import {costDeskResult} from '../apps/options-workbench/cost-desk.js';
import {eventDraft,eventRequest} from '../apps/options-workbench/event-research.js';
import {runGuidanceCommand} from './options-daily-guidance.mjs';
import {startOptionsWorkbench} from './options-workbench.mjs';

const budget=()=>({version:'OWNER_ALLOCATION_ONLY_V2',minCents:10000,maxCents:50000});
const settings=()=>({...defaultGuidanceSettings(),roundTripFeesCents:0,slippageReserveCents:0,tradeBudget:budget()});
const base=()=>({...settings(),symbol:'GLD',strategy:'LONG_CALL',quantity:1,contractMultiplier:100,bidPerShareCents:199,askPerShareCents:200,minimumPriceTickCents:1,mode:'NORMAL'});
const codes=r=>r.blockers.map(b=>b.code),at='2026-09-08T14:00:00.000Z';
const quote=(n,symbol='GLD',type='call')=>({id:'00000000-0000-0000-0000-'+String(n).padStart(12,'0'),symbol,type,expiry:'2026-09-30',strike:'100',multiplier:100,bidCents:199,askCents:200,tickCents:1,bidSize:20,askSize:20,delta:type==='call'?0.5:-0.5,updatedAt:at,receivedAt:at});
function guidance(){return {version:'OPTIONS_DAILY_GUIDANCE_INPUT_V1',at,captureAt:at,captureOrigin:'HOST_MARKET_TOOL_RESPONSES',captureComplete:true,quotes:[quote(1)],equities:[{symbol:'GLD',price:'106',sourceAt:at,close:null}],closeHistory:['2026-08-31','2026-09-01','2026-09-02','2026-09-03','2026-09-04'].map((date,i)=>({symbol:'GLD',date,price:String(100+i)})),events:[],calendarAvailable:true,headlinesAvailable:true,sourceHealth:[],headlines:[],context:{treasury:null,btc:null},settings:settings(),analyst:{assessedAt:at,assets:[{symbol:'GLD',bias:'BULLISH',sources:[{title:'Synthetic test evidence',url:'https://example.com',retrievedAt:at}],summary:'Fixture',supporting:[],opposing:[],invalidation:'Fixture',eventPlan:'Fixture'}]}};}
const checks=input=>assessCandidateChecks({version:'OPTIONS_CANDIDATE_CHECKS_INPUT_V1',guidance:input,sourcePaths:[]});
let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
async function temp(fn){const root=mkdtempSync(resolve(tmpdir(),'alpha-owner-allocation-'));try{await fn(root);}finally{const p=realpathSync(root),r=relative(realpathSync(tmpdir()),p);if(isAbsolute(r)||r.startsWith('..')||!r.startsWith('alpha-owner-allocation-'))throw Error('UNSAFE_CLEANUP');rmSync(p,{recursive:true,force:true});}}

await test('current policy removes legacy thresholds but retains exact amounts',()=>{
  const s=base(),before=JSON.stringify(s),r=evaluate(s),{tradeBudget,...old}=s,e=legacy(old).economics;
  assert.equal(JSON.stringify(s),before);assert.equal(r.schemaVersion,'4.0');assert.equal(r.status,'ECONOMICALLY_FEASIBLE_SCENARIO');assert.equal(r.executionAllowed,false);assert.equal(r.legacyLossCapsEnforced,false);
  for(const k of ['premiumCents','capitalRequiredCents','plannedStopCents','stressLossCents','roundedNetProfitTargetCents','indicativeExitLimitPerShareCents'])assert.equal(r.economics[k],e[k],k);
  for(const k of ['plannedRiskBudgetBps','plannedRiskBudgetCents','legacyNormalMaxLossCents','legacyEventMaxLossCents','legacyAllocationBudgetCents'])assert.equal(r.economics[k],null,k);
  assert.equal(r.economics.plannedStopCents,4000);assert.equal(r.economics.stressLossCents,20000);assert(Object.isFrozen(r.economics));assert(!r.disclosures.join(' ').includes('capped at 0.5%'));
});
for(const [ask,expected] of [[99,'ALLOCATION_BELOW_MINIMUM'],[100,null],[200,null],[500,null],[501,'ALLOCATION_BUDGET_EXCEEDED']])await test('whole-contract all-in boundary '+ask,()=>{const r=evaluate({...base(),askPerShareCents:ask,bidPerShareCents:ask-1});assert.deepEqual(codes(r),expected?[expected]:[]);assert.equal(r.scenario.quantity,1);});
await test('fees count at both inclusive boundaries',()=>{assert.equal(evaluate({...base(),bidPerShareCents:98,askPerShareCents:99,roundTripFeesCents:100}).status,'ECONOMICALLY_FEASIBLE_SCENARIO');assert(codes(evaluate({...base(),bidPerShareCents:499,askPerShareCents:500,roundTripFeesCents:1})).includes('ALLOCATION_BUDGET_EXCEEDED'));});
for(const field of ['roundTripFeesCents','slippageReserveCents'])await test('unknown '+field+' still blocks cost assessment',()=>{const r=evaluate({...base(),[field]:null});assert(codes(r).includes('COSTS_UNKNOWN'));assert.equal(r.economics.plannedStopCents,null);assert.equal(r.economics.plannedRiskBudgetCents,null);});
for(const [change,code] of [[{settledCashCents:19999},'SETTLED_CASH_INSUFFICIENT'],[{currentEquityCents:19999},'ACCOUNT_EQUITY_EXCEEDED'],[{bidPerShareCents:100},'STOP_BUDGET_NOT_EXECUTABLE'],[{bidPerShareCents:201},'INVALID_INPUT'],[{quantity:1.5},'INVALID_INPUT'],[{symbol:'SPY'},'INVALID_INPUT'],[{roundTripFeesCents:4000,slippageReserveCents:4000},'PROFIT_TARGET_CAP_EXCEEDED']])await test('independent '+code+' remains',()=>assert(codes(evaluate({...base(),...change})).includes(code)));
await test('claimed probability cannot enlarge allocation or quantity',()=>{const r=evaluate({...base(),mode:'CONDITIONAL',claimedWinProbabilityBps:9900});assert.deepEqual(codes(r),[]);assert.equal(r.economics.applicableAllocationBudgetCents,50000);assert.equal(r.scenario.quantity,1);assert.equal(r.executionAllowed,false);});
await test('current minimum cannot fall below owner instruction',()=>{assert.throws(()=>validateTradeBudget({...budget(),minCents:9999}),/TRADE_BUDGET/);assert.equal(validateTradeBudget({...budget(),version:'OWNER_TRADE_BUDGET_V1',minCents:1}).minCents,1);});
await test('preflight removes caps without turning unknown costs into known losses',()=>{const r=preflight({...settings(),roundTripFeesCents:null,slippageReserveCents:null});assert.equal(r.version,'OPTIONS_CAPITAL_POLICY_V2');assert.equal(r.status,'NO_PROVEN_CAPITAL_CONFLICT');assert.equal(r.constraints.necessaryUpperBoundCents,50000);assert.equal(r.constraints.plannedCapitalUpperBoundCents,null);assert.deepEqual(r.conflicts,[]);assert.equal(r.rows[0].plannedLossCents,null);assert.equal(r.rows[0].plannedLossLowerBoundCents,2000);assert(r.rows.every(x=>x.plannedLossExceedsCap===null&&x.stressExceedsCap===null));assert(capitalPolicyPanel(r).includes('Not capped'));});
await test('preflight still diagnoses cash and total-equity shortfalls',()=>{assert(preflight({...settings(),settledCashCents:9999}).conflicts.some(x=>x.code==='MINIMUM_EXCEEDS_CASH'));const r=preflight({...settings(),currentEquityCents:9999});assert(r.conflicts.some(x=>x.code==='MINIMUM_EXCEEDS_EQUITY'));assert(r.rows.every(x=>x.equityExceeded));});
await test('cost comparison retains costs once and removes headroom comparisons',()=>{const r=costDesk({scenario:base(),feeBasis:'DECLARED_FEES'});assert.equal(r.version,'OPTIONS_COST_DESK_V2');assert(r.rows.every(x=>x.plannedRiskHeadroomCents===null&&x.result.status==='ECONOMICALLY_FEASIBLE_SCENARIO'));assert.equal(r.rows[1].result.economics.plannedStopCents,4100);assert.equal(r.rows[1].result.economics.roundedNetProfitTargetCents,8200);assert(costDeskResult(r).includes('Not capped'));assert(!costDeskResult(r).includes('cap also remains'));});
await test('new guidance can become conditional only when independent evidence passes',()=>{const input=guidance(),r=assessDailyGuidance(input),c=checks(input);assert.equal(r.version,'OPTIONS_DAILY_GUIDANCE_V3');assert.equal(r.assets[0].candidates[0].disposition,'CONDITIONAL_RESEARCH');assert.equal(c.version,'OPTIONS_CANDIDATE_CHECKS_V3');assert.equal(c.rows[0].checks.find(x=>x.id==='stress').status,'NOT_ENFORCED');assert(!c.rows[0].nextActions.includes(''));assert.equal(r.winProbability,null);assert.equal(r.executionAllowed,false);input.settings.tradeBudget.version='OWNER_TRADE_BUDGET_V1';assert.equal(assessDailyGuidance(input).assets[0].candidates[0].disposition,'NO_TRADE');});
for(const [name,mutate,code] of [['stale',x=>x.quotes[0].updatedAt='2026-09-08T13:00:00.000Z','OPTION_QUOTE_NOT_FRESH'],['missing calendar',x=>x.calendarAvailable=false,'CALENDAR_COVERAGE_UNAVAILABLE'],['major event',x=>x.events=[{title:'Producer Price Index',source:'BLS',startDate:'2026-09-08',endDate:'2026-09-08',scheduledAt:'2026-09-08T14:30:00.000Z'}],'MAJOR_EVENT_WAIT'],['missing trend',x=>x.closeHistory=[],'DIRECTION_NOT_CONFIRMED']])await test(name+' still prevents a conditional candidate',()=>{const input=guidance();mutate(input);const r=assessDailyGuidance(input).assets[0].candidates[0];assert.equal(r.disposition,'NO_TRADE');assert(r.blockers.includes(code));});
await test('forms preserve policy through inheritance preview and clearing',()=>{const d=plannerBudgetDraft({...plannerDefaults(),bid:'1.99',ask:'2.00'},settings());assert.deepEqual(buildScenario(d).tradeBudget,budget());assert(plannerForm(d).includes('name="budgetVersion"'));assert.throws(()=>tradeBudgetFromFields({...d,budgetMin:'',budgetMax:''}),/required/);assert.throws(()=>tradeBudgetFromFields({...d,budgetMin:'99'}),/minimum/);const p=policySettingsFromFields({budgetVersion:d.budgetVersion,budgetMin:d.budgetMin,budgetMax:d.budgetMax,currentEquityCents:'1000',settledCashCents:'1000',roundTripFeesCents:'',slippageReserveCents:'',stopLossBps:'2000',rewardMultipleMilliR:'2000'});assert.deepEqual(p.tradeBudget,budget());assert.equal(p.roundTripFeesCents,null);});
await test('guidance and candidate text expose removed limits without disguising a pass',()=>{const input=guidance(),r=assessDailyGuidance(input),c=checks(input),component={data:{current:c,history:[]}};const page=guidancePage({loadedAt:at,guidance:{data:{current:r,history:[],interpretation:input.analyst}},candidateChecks:component,capitalPolicy:{data:preflight(settings())}});assert(page.includes('name="budgetVersion"'));assert(page.includes('Earlier analyst text'));assert(!page.includes('caps remain'));assert(candidateChecksPanel(component).includes('Not capped'));assert(candidateCheckDetail(c.rows[0],c).includes('Not Enforced'));});
function eventPlan(){return {version:'OPTIONS_EVENT_RESEARCH_PLAN_V1',id:'test-owner-ppi',title:'Isolated synthetic owner policy',createdAt:at,event:{title:'Producer Price Index',source:'BLS',startDate:'2026-09-10',endDate:'2026-09-10',scheduledAt:'2026-09-10T12:30:00.000Z'},selectionCapturePath:'data/runtime/options-daily-guidance/captures/2026-09-08/test.json',preContract:quote(1),postCall:quote(2,'IBIT'),postPut:quote(3,'IBIT','put'),settings:settings(),minimumMoveBps:20,preEntryAt:'2026-09-09T16:40:00.000Z',preExitAt:'2026-09-09T19:40:00.000Z',postEntryAt:'2026-09-10T13:40:00.000Z',postExitAt:'2026-09-10T19:40:00.000Z'};}
function frames(p){return [p.preEntryAt,p.preExitAt,p.postEntryAt,p.postExitAt].map((s,i)=>{const capturedAt=new Date(Date.parse(s)+600000).toISOString();return {path:'frame-'+i,origin:'HOST_MARKET_TOOL_RESPONSES',capturedAt,recordedAt:new Date(Date.parse(capturedAt)+1000).toISOString(),quotes:[p.preContract,p.postCall,p.postPut].map(q=>({...q,bidCents:i===1?180:i===3?240:199,askCents:i===1?181:i===3?241:200,updatedAt:capturedAt,receivedAt:capturedAt})),equities:['GLD','IBIT'].map(symbol=>({symbol,price:symbol==='IBIT'&&i>=2?'100.4':'100',sourceAt:capturedAt,close:null}))};});}
await test('new event comparisons preserve losses without hidden shared loss caps',()=>{const p=eventPlan(),r=assessEventResearch(p,frames(p),'2026-09-10T20:01:00.000Z'),c=r.comparisons.find(c=>c.mode==='COMBINED');assert.equal(r.version,'OPTIONS_EVENT_RESEARCH_REPORT_V2');assert.equal(r.eventRisk.plannedLossBudgetCents,null);assert.equal(r.eventRisk.fullLossStressBudgetCents,null);assert.equal(c.lossConsumedCents,2000);assert.equal(c.acceptedReferences,2);assert.equal(c.remainingEventLossCents,null);assert.equal(c.netReferencePnlCents,2000);assert.equal(r.actualTrades,0);});
await test('event policy still prevents reuse of unsettled proceeds',()=>{const p=eventPlan();p.settings.settledCashCents=30000;const r=assessEventResearch(p,frames(p),'2026-09-10T20:01:00.000Z');assert(r.comparisons.find(c=>c.mode==='COMBINED').steps[1].blockers.includes('UNSETTLED_PROCEEDS_NOT_REUSED'));});
await test('new event forms carry current settings without upgrading frozen plans',()=>{const p=eventPlan(),input=guidance();input.quotes=[p.preContract,p.postCall,p.postPut];input.events=[p.event];const draft=eventDraft({loadedAt:at,guidance:{data:{input,current:assessDailyGuidance(input),sourcePaths:[p.selectionCapturePath]}}},'test-event-new');assert.deepEqual(eventRequest(draft).settings.tradeBudget,budget());});
await test('old no-budget and V1 reports preserve their original constraints',()=>{const {tradeBudget,...s}=base();assert.deepEqual(evaluate(s),legacy(s));const old=evaluate({...s,tradeBudget:{...tradeBudget,version:'OWNER_TRADE_BUDGET_V1'}});assert(codes(old).includes('PLANNED_RISK_BUDGET_EXCEEDED'));assert(codes(old).includes('LEGACY_MAX_LOSS_LIMIT_EXCEEDED'));assert.equal(preflight({...settings(),tradeBudget:{...budget(),version:'OWNER_TRADE_BUDGET_V1'}}).constraints.necessaryUpperBoundCents,2500);});
await test('saved current policy rejects stale legacy rollback and preserves old snapshots',()=>temp(root=>{const old={...settings(),tradeBudget:{...budget(),version:'OWNER_TRADE_BUDGET_V1'}},path=saveGuidanceSettings(root,old),bytes=readFileSync(resolve(root,path)),input=guidance();input.settings=old;const prior=saveCandidateChecks(root,{input,sourcePaths:[]});saveGuidanceSettings(root,settings());assert.throws(()=>saveGuidanceSettings(root,old),/POLICY_DOWNGRADE/);assert.deepEqual(guidanceSettings(root),settings());assert.deepEqual(readFileSync(resolve(root,path)),bytes);assert.equal(readCandidateChecks(root,prior.path).report.version,'OPTIONS_CANDIDATE_CHECKS_V2');input.settings=settings();const now=saveCandidateChecks(root,{input,sourcePaths:[]});assert.equal(readCandidateChecks(root,now.path).report.version,'OPTIONS_CANDIDATE_CHECKS_V3');}));
await test('protected API saves previews evaluates and recovers the current policy',()=>temp(async root=>{let app=await startOptionsWorkbench({workspaceRoot:root,port:0});try{let state=await(await fetch(app.url+'/api/state')).json();const headers={'Content-Type':'application/json',Origin:app.url,'X-Alpha-Session':state.session};const post=(route,v)=>fetch(app.url+route,{method:'POST',headers,body:JSON.stringify(v)});assert.equal((await post('/api/guidance-settings',settings())).status,200);assert.equal((await post('/api/guidance-settings',defaultGuidanceSettings())).status,409);const result=await(await post('/api/evaluate',base())).json();const preview=await(await post('/api/capital-policy',settings())).json();assert.equal(preview.limits.fullPremiumStressCapCents,null);const brief=await runGuidanceCommand(['--host-brief'],{workspaceRoot:root});assert.equal(brief.capitalPolicy.legacyLossCapsEnforced,false);assert.deepEqual(brief.capitalPolicy.settings.tradeBudget,budget());assert.equal(result.economics.plannedRiskBudgetCents,null);assert.equal(result.status,'ECONOMICALLY_FEASIBLE_SCENARIO');await app.close();app=await startOptionsWorkbench({workspaceRoot:root,port:0});state=await(await fetch(app.url+'/api/state')).json();assert.deepEqual(state.guidance.data.current.settings,settings());assert.equal(state.capitalPolicy.data.limits.fullPremiumStressCapCents,null);assert.equal(state.executionAllowed,false);}finally{await app.close();}}));
console.log(passed+'/'+passed+' tests passed.');
