import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,copyFileSync,readFileSync,writeFileSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,dirname,sep} from 'node:path';
import {assessEtfObservation} from '../src/engines/options-daily-guidance/OptionsEtfObservation.ts';
import {assessDailyGuidance} from '../src/engines/options-daily-guidance/OptionsDailyGuidance.ts';
import {recordRobinhoodEtfBars,recordEtfSourceAudit,saveEtfObservation,verifyEtfSetup,etfSetupView} from './lib/options-etf-setup-io.mjs';
import {paperFingerprint} from '../src/engines/options-paper/OptionsPaperTradingEngine.ts';
import {etfObservationChart,etfObservationPanel} from '../apps/options-workbench/etf-setup.js';
import {runEtfSetup} from './options-etf-setup.mjs';

const at='2026-09-17T14:30:01.000Z';
const uuid=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
function guidance(){return {version:'OPTIONS_DAILY_GUIDANCE_INPUT_V2',at,captureAt:at,captureOrigin:'HOST_MARKET_TOOL_RESPONSES',captureComplete:true,
 quotes:[{id:uuid(1),symbol:'IBIT',expiry:'2026-10-16',type:'call',strike:'43',multiplier:100,bidCents:145,askCents:150,tickCents:1,bidSize:10,askSize:10,delta:0.5,updatedAt:at,receivedAt:at}],equities:[{symbol:'IBIT',price:'43.11',sourceAt:at,close:{date:'2026-09-16',price:'43'}}],closeHistory:['2026-09-10','2026-09-11','2026-09-14','2026-09-15','2026-09-16'].map((date,i)=>({symbol:'IBIT',date,price:String(39+i)})),events:[],calendarAvailable:true,headlinesAvailable:true,sourceHealth:[],headlines:[],context:{treasury:null,btc:null},
 settings:{currentEquityCents:100000,settledCashCents:100000,roundTripFeesCents:10,slippageReserveCents:10,stopLossBps:2000,rewardMultipleMilliR:2000,tradeBudget:{version:'OWNER_ALLOCATION_ONLY_V2',minCents:10000,maxCents:50000}},analyst:{assessedAt:at,assets:[{symbol:'IBIT',bias:'BULLISH',summary:'Synthetic test only',sources:[{url:'https://example.test/',retrievedAt:at}]}]}};}
function capture(interval='5minute',count=12){const fine=interval==='minute';return {tool:'get_equity_historicals',request:{symbols:['IBIT'],start_time:'2026-09-17T13:30:00Z',end_time:new Date(Date.parse('2026-09-17T13:30:00Z')+count*300000).toISOString(),interval,bounds:'regular',adjustment_type:'none'},requestedAt:at,receivedAt:at,response:{structuredContent:{data:{results:[{symbol:'IBIT',interval,bounds:'regular',bars:Array.from({length:count*(fine?5:1)},(_,i)=>{const p=43+Math.floor(i/(fine?5:1))/100;return {begins_at:new Date(Date.parse('2026-09-17T13:30:00Z')+i*(fine?60000:300000)).toISOString(),open_price:p.toFixed(6),high_price:(p+0.01).toFixed(6),low_price:(p-0.01).toFixed(6),close_price:p.toFixed(6),volume:fine?100:500,session:'reg'};})}]}}}};}
const input=()=>({at,sourceCapture:capture(),auditInput:null,guidance:guidance()});
const rows=c=>c.response.structuredContent.data.results[0].bars;
const asset=i=>assessEtfObservation(i).assets.find(a=>a.symbol==='IBIT');
function withAudit(){const i=input();i.auditInput={fiveMinuteCapture:structuredClone(i.sourceCapture),minuteCapture:capture('minute')};return i;}
const temp=()=>mkdtempSync(join(tmpdir(),'alpha-etf-observe-'));
function cleanup(root){const p=resolve(root);assert.ok(p.startsWith(resolve(tmpdir())+sep)&&p.includes('alpha-etf-observe-'));rmSync(p,{recursive:true,force:true});}
let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS '+name);}

await test('unknown flags permit exact descriptive values without changing canonical guidance',()=>{const i=input(),before=JSON.stringify(i),original=assessDailyGuidance(i.guidance),r=assessEtfObservation(i),a=asset(i);assert.equal(a.status,'OBSERVATIONS_AVAILABLE_UNQUALIFIED');assert.equal(a.momentum.direction,'RISING');assert.equal(a.momentum.fastMean,'43.100000');assert.equal(a.momentum.slowMean,'43.055000');assert.equal(a.candles.length,12);assert.ok(a.candles.every(b=>b.interpolated===null));assert.equal(a.sourceQualified,false);assert.equal(r.executionAllowed,false);assert.equal(r.winProbability,null);assert.equal(r.expectedReturn,null);assert.deepEqual(assessDailyGuidance(i.guidance),original);assert.equal(JSON.stringify(i),before);});
await test('open-to-last decline can coexist with rising late-window momentum',()=>{const i=input();rows(i.sourceCapture)[0].open_price='43.12';rows(i.sourceCapture)[0].high_price='43.13';const a=asset(i);assert.equal(a.observations.direction,'DOWN');assert.equal(a.momentum.direction,'RISING');});
await test('falling and mixed close patterns are distinguished',()=>{const i=input();for(const [n,b] of rows(i.sourceCapture).entries()){b.open_price=b.close_price=(43.2-n/100).toFixed(6);b.high_price='43.3';b.low_price='42.9';}assert.equal(asset(i).momentum.direction,'FALLING');for(const b of rows(i.sourceCapture))b.open_price=b.close_price='43';assert.equal(asset(i).momentum.direction,'MIXED');});
await test('missing source and short history cannot manufacture momentum',()=>{const i=input();i.sourceCapture=null;assert.equal(asset(i).momentum.direction,'NOT_ASSESSABLE');assert.equal(asset(i).referenceRange,null);i.sourceCapture=capture('5minute',5);assert.equal(asset(i).momentum.fastMean,null);assert.equal(asset(i).referenceRange,null);});
for(const [label,change] of [
 ['synthetic bar',b=>{b[0].interpolated=true;b[0].volume=0;}],['missing interval',b=>b.splice(2,1)],['duplicate interval',b=>b[1]=structuredClone(b[0])],['invalid price',b=>b[0].high_price='42'],['invalid session',b=>b[0].session='post']
])await test(label+' withholds observations and chart',()=>{const i=input();change(rows(i.sourceCapture));const a=asset(i);assert.equal(a.observations,null);assert.equal(a.momentum.direction,'NOT_ASSESSABLE');assert.deepEqual(a.candles,[]);});
await test('explicit false is retained but does not qualify strategy or source',()=>{const i=input();for(const b of rows(i.sourceCapture))b.interpolated=false;const a=asset(i);assert.equal(a.source.unknownInterpolation,0);assert.equal(a.sourceQualified,false);assert.ok(a.scenarios.every(s=>!s.entryConfirmed&&s.entryLimit===null));});
await test('matching audit keeps unqualified agreement and all assumptions visible',()=>{const a=asset(withAudit());assert.equal(a.auditStatus,'NUMERICALLY_MATCHED_UNQUALIFIED');assert.equal(a.referenceRange.high,'43.120000');assert.equal(a.referenceRange.low,'43.050000');assert.equal(a.sourceQualified,false);assert.ok(a.scenarios.every(s=>s.condition.includes('two future completed')));});
await test('a conflicting close withholds momentum instead of choosing a winner',()=>{const i=withAudit();rows(i.auditInput.minuteCapture)[4].close_price='43.000001';const a=asset(i);assert.equal(a.auditStatus,'DIFFERENCES_RETAINED');assert.equal(a.momentum.direction,'NOT_ASSESSABLE');assert.equal(a.momentum.fastMean,null);assert.equal(a.candles[0].close,'43.000000');assert.ok(a.candles[0].conflictFields.includes('close'));assert.ok(a.referenceRange);});
await test('relevant range conflicts withhold levels, older conflicts do not',()=>{const i=withAudit();rows(i.auditInput.minuteCapture)[0].high_price='43.02';assert.ok(asset(i).referenceRange);rows(i.auditInput.minuteCapture)[59].high_price='43.13';const a=asset(i);assert.equal(a.referenceRange,null);assert.equal(a.momentum.direction,'RISING');assert.ok(a.limits.includes('RANGE_CONFLICT_WITHHOLDS_LEVELS'));});
await test('unrelated audit cannot establish agreement or suppress source observations',()=>{const i=withAudit();rows(i.auditInput.fiveMinuteCapture)[0].volume=501;const a=asset(i);assert.equal(a.auditStatus,'DIFFERENT_SOURCE_CAPTURE');assert.deepEqual(a.conflictingIntervals,[]);assert.ok(a.limits.includes('CROSS_INTERVAL_COMPARISON_UNAVAILABLE'));});
await test('broken minute history remains explicitly not comparable',()=>{const i=withAudit();rows(i.auditInput.minuteCapture).pop();const a=asset(i);assert.equal(a.auditStatus,'NOT_COMPARABLE');assert.ok(a.limits.includes('CROSS_INTERVAL_COMPARISON_UNAVAILABLE'));});
await test('future source and audit receipts rejected',()=>{const i=withAudit();i.sourceCapture.receivedAt='2026-09-17T15:00:00.000Z';assert.throws(()=>asset(i),/RECEIPT_CLOCK/);i.sourceCapture=capture();i.auditInput.minuteCapture.receivedAt='2026-09-17T15:00:00.000Z';assert.throws(()=>asset(i),/ETF_AUDIT_/);});
await test('rank only same-side sample; delta fit can outrank cheapest and input order',()=>{const i=input(),q=i.guidance.quotes[0];i.guidance.quotes.push({...q,id:uuid(2),delta:0.36,bidCents:110,askCents:115},{...q,id:uuid(3),type:'put',delta:-0.5});const a=asset(i);assert.equal(a.scenarios[0].references[0].contract.id,uuid(1));assert.equal(a.scenarios[1].references.length,1);assert.equal(a.scenarios[1].references[0].contract.type,'put');i.guidance.quotes.reverse();assert.deepEqual(asset(i).scenarios,a.scenarios);});
await test('mechanical fit precedes ideal delta and never increases quantity',()=>{const i=input(),q=i.guidance.quotes[0];q.askCents=600;q.bidCents=595;i.guidance.quotes.push({...q,id:uuid(2),delta:0.4,bidCents:115,askCents:120});const s=asset(i).scenarios[0];assert.equal(s.references[0].contract.id,uuid(2));assert.equal(s.references[0].premiumCents,12000);assert.ok(s.references[1].sampleFitBlockers.includes('ALLOCATION_BUDGET_EXCEEDED'));assert.equal(s.entryLimit,null);});
await test('all original blockers, unknown costs and unknown target retained',()=>{const i=input();i.guidance.settings.roundTripFeesCents=null;const s=asset(i).scenarios[0],original=assessDailyGuidance(i.guidance).assets.find(a=>a.symbol==='IBIT').candidates[0];assert.equal(s.sampleFitCount,0);assert.deepEqual(s.references[0].originalBlockers,original.blockers);assert.ok(s.references[0].sampleFitBlockers.includes('COSTS_UNKNOWN'));assert.equal(s.references[0].plan.targetExitCents,null);});
await test('quotes before bar end and expired source are not current entry prices',()=>{const i=input();i.guidance.quotes[0].updatedAt='2026-09-17T14:20:00.000Z';i.at=i.guidance.at='2026-09-18T00:00:00.000Z';const a=asset(i);assert.ok(a.limits.includes('HISTORICAL_BAR_WINDOW'));assert.ok(a.scenarios[0].references[0].blockers.includes('OPTION_QUOTES_PRECEDE_BAR_WINDOW_END'));assert.ok(a.scenarios[0].references[0].blockers.includes('OPTION_QUOTE_NOT_FRESH'));assert.equal(a.scenarios[0].entryLimit,null);});
await test('mismatched assessment time and extra inputs rejected',()=>{assert.throws(()=>assessEtfObservation({...input(),approved:true}),/ETF_OBSERVATION_INPUT/);const i=input();i.guidance.at='2026-09-17T15:00:00.000Z';assert.throws(()=>asset(i),/ETF_OBSERVATION_INPUT/);});
await test('copied-only snapshot recovers and preserves originals without strict imports',async()=>{const root=temp(),copy=temp();try{const i=withAudit(),source=recordRobinhoodEtfBars(root,i.sourceCapture,at);recordEtfSourceAudit(root,i.auditInput,at);const original=readFileSync(join(root,source.path)),saved=saveEtfObservation(root,i.guidance,at),target=join(copy,saved.path);mkdirSync(dirname(target),{recursive:true});copyFileSync(join(root,saved.path),target);const recovered=verifyEtfSetup(copy,saved.path);assert.equal(recovered.report.assets.find(a=>a.symbol==='IBIT').auditStatus,'NUMERICALLY_MATCHED_UNQUALIFIED');assert.deepEqual(readFileSync(join(root,source.path)),original);assert.ok(!existsSync(join(root,'data/runtime/options-etf-setup/bars')));assert.ok(!existsSync(join(root,'data/runtime/options-etf-setup/plans')));assert.equal((await runEtfSetup(['--verify',saved.path],{workspaceRoot:copy,now:()=>at})).status,'VERIFIED');assert.equal(etfSetupView(root,i.guidance,at).observationSnapshots.length,1);const bad=JSON.parse(readFileSync(target,'utf8'));bad.report.executionAllowed=true;bad.reportFingerprint=paperFingerprint(bad.report);writeFileSync(target,JSON.stringify(bad));assert.throws(()=>verifyEtfSetup(copy,saved.path),/OBSERVATION_RECOMPUTE/);}finally{cleanup(root);cleanup(copy);}});
await test('frontend labels provenance, unknown targets and conflicts without unsafe text',()=>{const i=withAudit();rows(i.auditInput.minuteCapture)[0].volume++;i.guidance.settings.roundTripFeesCents=null;const r=assessEtfObservation(i),a=r.assets.find(a=>a.symbol==='IBIT');assert.ok(etfObservationChart(a).includes('<circle'));const html=etfObservationPanel(r);assert.ok(html.includes('Saved Robinhood API candles'));assert.ok(html.includes('Unknown per share'));assert.ok(html.includes('another data provider is optional'));assert.ok(html.includes('unconfirmed'));a.scenarios[0].condition='<img src=x>';assert.ok(!etfObservationPanel(r).includes('<img'));assert.ok(etfObservationPanel(r).includes('&lt;img'));assert.equal(etfObservationPanel(null),'');});
console.log(`ETF observation: ${passed}/${passed} tests passed.`);
