import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {runInNewContext} from 'node:vm';
import {collectSnapshotPaperMarket} from './lib/options-snapshot-paper-capture.mjs';
import {normalizeGuidanceCapture} from './lib/options-guidance-io.mjs';
import {mapSnapshotSource} from './lib/options-snapshot-paper-io.mjs';
import {paperFingerprint} from '../src/engines/options-paper/OptionsPaperTradingEngine.ts';
const target={id:'8f59fe6b-62c1-4c83-9993-faef95313b10',chainId:'f4b86825-a92b-4e23-8f93-1ee813d0ec15',symbol:'IBIT',expiry:'2026-10-16',type:'put',strike:'47.0000',multiplier:100};
const at='2026-09-30T14:15:01.000Z';
const instrument=()=>({id:target.id,chain_id:target.chainId,chain_symbol:'IBIT',expiration_date:target.expiry,type:'put',strike_price:'47.000000',state:'active',tradability:'tradable',underlying_type:'equity',trade_value_multiplier:'100',min_ticks:{above_tick:'0.05',below_tick:'0.01',cutoff_price:'3.00'}});
const response=(tool)=>tool==='get_option_chains'?{data:{chains:[{id:target.chainId,symbol:'IBIT',expiration_dates:[target.expiry],late_close_state:'enabled'}]}}:tool==='get_option_instruments'?{data:{instruments:[instrument()],next:null}}:tool==='get_equity_quotes'?{data:{results:['GLD','IBIT'].map(symbol=>({quote:{symbol,last_trade_price:'47.295000',venue_last_trade_time:at,last_non_reg_trade_price:null,venue_last_non_reg_trade_time:null}}))}}:{data:{results:[{quote:{instrument_id:target.id,bid_price:'1.22',ask_price:'1.24',bid_size:37,ask_size:80,delta:'-0.44',updated_at:at}}]}};
async function run(change=()=>{},collector=collectSnapshotPaperMarket){const calls=[];const result=await collector({contract:target,clock:async()=>at,call:async(tool,request)=>{calls.push({tool,request});const r=response(tool);const changed=await change(tool,r,calls);return changed??r;}});return {result,calls};}
let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
await test('single exact capture works after function serialization and retains original receipts',async()=>{
 const {result:r,calls}=await run(()=>{},runInNewContext('('+collectSnapshotPaperMarket.toString()+')'));assert.equal(r.status,'CAPTURED');assert.equal(calls.length,4);assert.deepEqual(calls.map(c=>c.tool),['get_option_chains','get_option_instruments','get_equity_quotes','get_option_quotes']);assert.equal(JSON.stringify(calls.at(-1).request),JSON.stringify({instrument_ids:[target.id]}));
 const input=JSON.parse(JSON.stringify(r.capture));input.origin='SYNTHETIC_FIXTURE';const report=normalizeGuidanceCapture(input);assert.equal(report.quotes.length,1);assert.equal(report.complete,false);const record={version:'OPTIONS_GUIDANCE_RECORD_V1',kind:'captures',recordedAt:at,input,report,inputFingerprint:paperFingerprint(input),reportFingerprint:paperFingerprint(report)};const utf8=JSON.stringify(record);const mapped=mapSnapshotSource({path:'data/runtime/options-daily-guidance/captures/2026-09-30/synthetic.json',sha256:createHash('sha256').update(utf8).digest('hex'),utf8},'V3');assert.equal(mapped.quotes[0].id,target.id);assert.equal(mapped.quotes[0].underlyingPriceUsd,'47.295000');assert.equal(mapped.origin,'SYNTHETIC_FIXTURE');assert.equal(mapped.quotes[0].updatedAt,at);assert.equal(r.attempt.accountAccessed,false);
});
await test('three instrument pages reserve both quote calls and never exceed six',async()=>{let page=0;const {result,calls}=await run((t,r)=>{if(t==='get_option_instruments'&&++page<3)r.data={instruments:[],next:page===1?'YWJjZA==':'ZWZnaA=='};});assert.equal(result.status,'CAPTURED');assert.equal(calls.length,6);});
await test('absent exact identity stops after three pages without substitute quote',async()=>{let page=0;const {result,calls}=await run((t,r)=>{if(t==='get_option_instruments')r.data={instruments:[],next:['YWJjZA==','ZWZnaA==','aWprbA=='][page++]};});assert.equal(result.status,'NO_CAPTURE');assert.equal(calls.length,4);assert.equal(result.capture,null);assert(result.attempt.failures.some(f=>f.code==='EXACT_CONTRACT_NOT_FOUND'));});
for(const [name,mutate] of [['type',i=>i.type='call'],['strike',i=>i.strike_price='48'],['multiplier',i=>i.trade_value_multiplier='10'],['tradability',i=>i.tradability='untradable']])await test('exact ID cannot hide changed '+name,async()=>{const {result,calls}=await run((t,r)=>{if(t==='get_option_instruments')mutate(r.data.instruments[0]);});assert.equal(result.status,'NO_CAPTURE');assert.equal(calls.length,2);});
await test('wrong chain stops before instrument calls',async()=>{const {result,calls}=await run((t,r)=>{if(t==='get_option_chains')r.data.chains[0].id=target.id;});assert.equal(result.status,'NO_CAPTURE');assert.equal(calls.length,1);});
await test('provider exception stops immediately with zero retries',async()=>{const {result,calls}=await run(()=>{throw Error('private provider detail');});assert.equal(calls.length,1);assert.equal(result.status,'NO_CAPTURE');assert(!JSON.stringify(result).includes('private provider detail'));});
await test('error reply retained unmodified without further calls',async()=>{const {result,calls}=await run(()=>({isError:true,content:[{type:'text',text:'sample sanitized error'}]}));assert.equal(calls.length,1);assert.equal(result.attempt.receipts[0].response.isError,true);assert.equal(result.status,'NO_CAPTURE');});
await test('missing selected quote remains no capture, never filled',async()=>{const {result,calls}=await run((t,r)=>{if(t==='get_option_quotes')r.data.results=[{quote:null}];});assert.equal(result.status,'NO_CAPTURE');assert.equal(calls.length,4);});
await test('foreign cursor URL never followed',async()=>{const {result,calls}=await run((t,r)=>{if(t==='get_option_instruments')r.data={instruments:[],next:'https://evil.example/secret'};});assert.equal(result.status,'NO_CAPTURE');assert.equal(calls.length,2);});
await test('repeated cursor stops without retry',async()=>{const {result,calls}=await run((t,r)=>{if(t==='get_option_instruments')r.data={instruments:[],next:'YWJjZA=='};});assert.equal(result.status,'NO_CAPTURE');assert.equal(calls.length,3);});
await test('elapsed time stops subsequent market calls and preserves received data',async()=>{let reads=0,calls=0;const r=await collectSnapshotPaperMarket({contract:target,clock:async()=>new Date(Date.parse(at)+(reads++<2?0:180000)).toISOString(),call:async t=>{calls++;return response(t);}});assert.equal(calls,1);assert.equal(r.status,'NO_CAPTURE');assert.equal(r.attempt.receipts.length,1);});
await test('clock reversal cannot produce a successful capture',async()=>{let reads=0,calls=0;await assert.rejects(()=>collectSnapshotPaperMarket({contract:target,clock:async()=>new Date(Date.parse(at)-(reads++<2?0:1)).toISOString(),call:async t=>{calls++;return response(t);}}),/CLOCK_REGRESSION/);assert.equal(calls,1);});
await test('malformed scope makes no market calls',async()=>{let calls=0;await assert.rejects(()=>collectSnapshotPaperMarket({contract:{...target,multiplier:10},clock:async()=>at,call:async()=>{calls++;}}),/SCOPE/);assert.equal(calls,0);});
console.log('Snapshot paper capture: '+passed+'/'+passed+' tests passed.');
