import assert from "node:assert/strict";
import { existsSync, linkSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { isAbsolute, join, relative, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { runOptionsManualLedgerCommand as run, readManualLedger } from "./options-manual-ledger.mjs";
import { manualDemoCommands } from "../src/engines/options-manual-ledger/OptionsManualLedgerFixtures.ts";
const at="2026-09-07T20:00:00.000Z", base="data/runtime/options-manual-ledger/test-ledger";
const opts=root=>({workspaceRoot:root,now:()=>at});
let passed=0;
function test(name,fn){fn();passed++;console.log("PASS "+name);}
export function manualTestTemp(fn){const root=mkdtempSync(join(tmpdir(),"alpha-manual-test-"));try{return fn(root);}finally{const rel=relative(realpathSync(tmpdir()),realpathSync(root));if(isAbsolute(rel)||rel.startsWith("..")||!rel.startsWith("alpha-manual-test-"))throw Error("UNSAFE_CLEANUP");rmSync(root,{recursive:true});}}
const temp=manualTestTemp;
function create(root){return run(["--create","test-ledger"],opts(root));}
function append(root,c){writeFileSync(join(root,"command.json"),JSON.stringify(c));return run(["--append","test-ledger","command.json"],opts(root));}
function seed(root,n=6){create(root);for(const c of manualDemoCommands().slice(0,n))append(root,c);return run(["--inspect","test-ledger"],opts(root));}
test("new owner ledger is empty and creation is exclusive",()=>temp(root=>{const r=create(root);assert.equal(r.origin,"OWNER_REPORTED_UNVERIFIED");assert.equal(r.tradeCount,0);assert.throws(()=>create(root),/EEXIST/);assert.equal(run(["--verify","test-ledger"],opts(root)).eventCount,0);}));
test("full lifecycle correction and fee reconciliation survive fresh process",()=>temp(root=>{const r=seed(root);assert.equal(r.trades[0].closedTradeNetPnlUsd,"4.960000");const child=spawnSync(process.execPath,["--import","tsx","--input-type=module","-e",`import {runOptionsManualLedgerCommand as run} from ${JSON.stringify(new URL('./options-manual-ledger.mjs',import.meta.url).href)};console.log(JSON.stringify(run(['--inspect','test-ledger'],{workspaceRoot:process.argv[1],now:()=> '${at}'})));`,root],{cwd:resolve(import.meta.dirname,".."),encoding:"utf8"});assert.equal(child.status,0,child.stderr);assert.equal(JSON.parse(child.stdout).reportFingerprint,r.reportFingerprint);assert.equal(readdirSync(join(root,base)).length,13);}));
test("identical request is a no-op even after subsequent corrections",()=>temp(root=>{seed(root);const before=run(["--verify","test-ledger"],opts(root));const r=append(root,manualDemoCommands()[1]);assert.equal(r.status,"MANUAL_REQUEST_ALREADY_RECORDED");assert.equal(run(["--verify","test-ledger"],opts(root)).headSha256,before.headSha256);}));
test("same request identity cannot change its contents",()=>temp(root=>{seed(root,2);const c=manualDemoCommands()[1];c.fill.quantity=4;assert.throws(()=>append(root,c),/REQUEST_ID_CONFLICT/);assert(!existsSync(join(root,base,"writer.lock")));assert.equal(run(["--verify","test-ledger"],opts(root)).eventCount,2);}));
test("external execution ref catches duplicate imports with fresh local IDs",()=>temp(root=>{seed(root,2);const c=manualDemoCommands()[1];c.fillId="different-fill";c.requestId="different-request";c.fill.executionSequence=2;assert.throws(()=>append(root,c),/DUPLICATE_EXECUTION_REF/);assert.equal(run(["--verify","test-ledger"],opts(root)).eventCount,2);}));
test("correction of opening quantity cannot erase existing sales",()=>temp(root=>{seed(root);const c=manualDemoCommands()[5];c.requestId="bad-correction";c.fillId="fixture-fill-1";c.replacement=null;assert.throws(()=>append(root,c),/OVERSELL/);assert.equal(run(["--verify","test-ledger"],opts(root)).eventCount,6);}));
test("old correction revision cannot overwrite a newer correction",()=>temp(root=>{seed(root);const c=manualDemoCommands()[5];c.requestId="stale-correction";assert.throws(()=>append(root,c),/STALE_CORRECTION/);}));
for(const file of ["manifest.json","000001.json","000001.receipt.json"])test("tampered "+file+" blocks recovery and append",()=>temp(root=>{seed(root,1);const p=join(root,base,file);writeFileSync(p,readFileSync(p,"utf8")+" ");assert.throws(()=>run(["--verify","test-ledger"],opts(root)));assert.throws(()=>append(root,manualDemoCommands()[1]));assert(!existsSync(join(root,base,"writer.lock")));}));
test("unknown stray journal files are not ignored",()=>temp(root=>{seed(root,1);writeFileSync(join(root,base,"surprise.json"),"{}");assert.throws(()=>run(["--verify","test-ledger"],opts(root)),/PARTIAL_OR_UNEXPECTED/);}));
test("partial payload without receipt stays blocked and untouched",()=>temp(root=>{seed(root,1);writeFileSync(join(root,base,"000002.json"),"{}");assert.throws(()=>append(root,manualDemoCommands()[1]));assert.equal(readFileSync(join(root,base,"000002.json"),"utf8"),"{}");assert(!existsSync(join(root,base,"000002.receipt.json")));}));
test("stale foreign writer lock is never cleared",()=>temp(root=>{create(root);writeFileSync(join(root,base,"writer.lock"),"foreign-lock");assert.throws(()=>run(["--verify","test-ledger"],opts(root)),/WRITER_LOCKED/);assert.throws(()=>append(root,manualDemoCommands()[0]),/EEXIST/);assert.equal(readFileSync(join(root,base,"writer.lock"),"utf8"),"foreign-lock");}));
test("hard-linked command is rejected without ledger writes",()=>temp(root=>{create(root);writeFileSync(join(root,"command.json"),JSON.stringify(manualDemoCommands()[0]));linkSync(join(root,"command.json"),join(root,"alias.json"));assert.throws(()=>run(["--append","test-ledger","command.json"],opts(root)),/UNSAFE_FILE/);assert.equal(readdirSync(join(root,base)).length,1);}));
test("hard-linked journal fails recovery",()=>temp(root=>{seed(root,1);linkSync(join(root,base,"000001.json"),join(root,"copy.json"));assert.throws(()=>run(["--verify","test-ledger"],opts(root)),/UNSAFE_FILE/);}));
test("unsafe paths and reserved ledger IDs fail before writing",()=>temp(root=>{for(const id of ["../escape","con","C:/escape"])assert.throws(()=>run(["--create",id],opts(root)));assert.equal(readdirSync(root).length,0);create(root);assert.throws(()=>run(["--append","test-ledger","../outside.json"],opts(root)));}));
for(const [name,bytes] of [["invalid UTF8",Buffer.from([255])],["UTF8 BOM",Buffer.from('\ufeff'+JSON.stringify(manualDemoCommands()[0]))],["duplicate JSON",Buffer.from('{"type":"REGISTER_TRADE","type":"CORRECT_FILL"}')]])test(name+" fails without partial history",()=>temp(root=>{create(root);writeFileSync(join(root,"command.json"),bytes);assert.throws(()=>run(["--append","test-ledger","command.json"],opts(root)));assert.equal(readdirSync(join(root,base)).length,1);}));
test("source bytes and receipt clocks are preserved",()=>temp(root=>{create(root);const text=JSON.stringify(manualDemoCommands()[0],null,4)+"\n";writeFileSync(join(root,"command.json"),text);run(["--append","test-ledger","command.json"],opts(root));const p=JSON.parse(readFileSync(join(root,base,"000001.json"),"utf8"));assert.equal(p.sourceText,text);const r=JSON.parse(readFileSync(join(root,base,"000001.receipt.json"),"utf8"));assert.equal(r.savedAt,at);assert.equal(readManualLedger(root,"test-ledger",()=>at).input.events[0].savedAt,at);}));
test("clock regression during save leaves a visible unaccepted prefix",()=>temp(root=>{create(root);writeFileSync(join(root,"command.json"),JSON.stringify(manualDemoCommands()[0]));let calls=0;assert.throws(()=>run(["--append","test-ledger","command.json"],{workspaceRoot:root,now:()=>++calls<3?at:"2026-09-07T19:59:59.000Z"}),/SAVE_CLOCK/);assert(existsSync(join(root,base,"000001.json")));assert(!existsSync(join(root,base,"000001.receipt.json")));assert(!existsSync(join(root,base,"writer.lock")));}));
test("fixture demo cannot populate a separate owner ledger",()=>temp(root=>{create(root);const r=run(["--demo","fixture-demo"],opts(root));assert.equal(r.origin,"SYNTHETIC_FIXTURE");assert.equal(r.counts.closedTrades,1);assert.equal(run(["--verify","test-ledger"],opts(root)).counts.trades,0);}));
test("history without original command files still recomputes",()=>temp(root=>{seed(root);writeFileSync(join(root,"command.json"),"unavailable original input");assert.equal(run(["--verify","test-ledger"],opts(root)).eventCount,6);}));
console.log(`${passed}/${passed} tests passed.`);
