import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync, existsSync, linkSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve, join, relative, isAbsolute } from "node:path";
import { spawnSync } from "node:child_process";
import { runOptionsChainReviewCommand as run } from "./options-chain-review.mjs";
import { runOptionsPaperPortfolioCommand } from "./options-paper-portfolio.mjs";
import { chainSurveyFixture } from "../src/engines/options-robinhood-data/RobinhoodChainSurveyFixtures.ts";
import { assessRobinhoodChainSurvey } from "../src/engines/options-robinhood-data/RobinhoodChainSurvey.ts";
import { collectChainClose, routeChainClose } from "./lib/options-chain-close-host.mjs";
import { renderChainReviewBoard } from "./lib/options-chain-review-render.mjs";

const at = "2026-09-08T20:21:10.000Z", opts = dir => ({ workspaceRoot: dir, now: () => at }), base = "data/runtime/options-chain-survey";
let passed = 0; async function test(name, work) { await work(); passed++; console.log("PASS " + name); }
async function temp(work) { const dir = mkdtempSync(join(tmpdir(), "alpha-chain-review-test-")); try { await work(dir); } finally { const rel = relative(realpathSync(tmpdir()), realpathSync(dir)); if (isAbsolute(rel) || rel.startsWith("..") || !rel.startsWith("alpha-chain-review-test-")) throw Error("UNSAFE_CLEANUP"); rmSync(dir, { recursive: true }); } }
function seed(dir) { writeFileSync(join(dir, "source.json"), JSON.stringify(chainSurveyFixture())); return run(["--build", "source.json", "test-board"], opts(dir)); }
await test("exclusive board build retains source and recovers in a fresh process", () => temp(dir => { const r = seed(dir); assert.equal(r.instrumentCount, 12); assert.equal(r.paperAttached, false); assert.deepEqual(readFileSync(join(dir, "source.json")), readFileSync(join(dir, base, "test-board/capture.json"))); const child = spawnSync(process.execPath, ["--import", "tsx", "--input-type=module", "-e", `import {runOptionsChainReviewCommand as run} from ${JSON.stringify(new URL("./options-chain-review.mjs", import.meta.url).href)}; console.log(JSON.stringify(run(['--verify','test-board'],{workspaceRoot:process.argv[1],now:()=> '${at}'})));`, dir], { cwd: resolve(import.meta.dirname, ".."), encoding: "utf8" }); assert.equal(child.status, 0, child.stderr); assert.equal(JSON.parse(child.stdout).reportFingerprint, r.reportFingerprint); assert(!existsSync(join(dir, "data/runtime/options-paper"))); }));
await test("existing board is never overwritten", () => temp(dir => { seed(dir); const bytes = readFileSync(join(dir, base, "test-board/report.json")); assert.throws(() => seed(dir), /EEXIST/); assert.deepEqual(readFileSync(join(dir, base, "test-board/report.json")), bytes); }));
for (const file of ["capture.json", "report.json", "index.html", "manifest.json"]) await test("tampered " + file + " fails recovery", () => temp(dir => { seed(dir); const p = join(dir, base, "test-board", file); writeFileSync(p, readFileSync(p, "utf8") + "X"); assert.throws(() => run(["--verify", "test-board"], opts(dir))); }));
await test("unsafe source paths and IDs rejected before output creation", () => temp(dir => { writeFileSync(join(dir, "source.json"), "{}"); for (const args of [["--build", "../source.json", "ok"], ["--build", "source.json", "../escape"], ["--verify", "../escape"]]) assert.throws(() => run(args, opts(dir))); assert(!existsSync(join(dir, "data"))); }));
await test("invalid UTF8 and duplicate source keys fail before save", () => temp(dir => { for (const bytes of [Buffer.from([0xff]), Buffer.from('{"version":1,"version":2}')]) { writeFileSync(join(dir, "source.json"), bytes); assert.throws(() => run(["--build", "source.json", "invalid"], opts(dir))); } assert(!existsSync(join(dir, "data"))); }));
await test("hard-linked source is rejected", () => temp(dir => { writeFileSync(join(dir, "source.json"), JSON.stringify(chainSurveyFixture())); linkSync(join(dir, "source.json"), join(dir, "alias.json")); assert.throws(() => run(["--build", "source.json", "bad"], opts(dir))); }));
await test("original paper reader recovers copied artifact and preserves source", () => temp(dir => { runOptionsPaperPortfolioCommand(["--demo", "--save", "paper-source"], opts(dir)); const path = join(dir, "data/runtime/options-paper-portfolio/paper-source.json"), before = readFileSync(path); writeFileSync(join(dir, "source.json"), JSON.stringify(chainSurveyFixture())); const r = run(["--build", "source.json", "with-paper", "--paper", "paper-source"], opts(dir)); assert.equal(r.paperAttached, true); assert.deepEqual(readFileSync(path), before); const copy = join(dir, base, "with-paper/paper/data/runtime/options-paper-portfolio/paper-source.json"); assert.deepEqual(readFileSync(copy), before); writeFileSync(copy, "{}"); assert.throws(() => run(["--verify", "with-paper"], opts(dir))); }));
await test("HTML escapes dynamic text with no script or order form", () => { const r = assessRobinhoodChainSurvey(JSON.stringify(chainSurveyFixture()), at); const html = renderChainReviewBoard({ createdAt: '<script>alert("x")</script>', chain: r, paper: null, reportFingerprint: "x" }); assert(!/<script|<form|onerror=/.test(html)); assert(html.includes("&lt;script&gt;")); assert(html.includes("default-src 'none'")); assert(html.includes("Complete report") || html.includes("Save complete report")); });
await test("comparison saves all cases and recomputes; tampering fails", () => temp(dir => { seed(dir); const f = chainSurveyFixture(); f.capturedAt = "2026-09-09 20:21:00 UTC"; writeFileSync(join(dir, "next.json"), JSON.stringify(f)); const nextOpts = { workspaceRoot: dir, now: () => "2026-09-09T20:21:10.000Z" }; run(["--build", "next.json", "next"], nextOpts); const r = run(["--compare", "test-board", "next", "changes"], nextOpts); assert.equal(r.counts.unchangedQuoteClock, 12); assert.equal(run(["--verify-comparison", "changes"], nextOpts).reportFingerprint, r.reportFingerprint); const path = join(dir, base, "changes.comparison.json"); const c = JSON.parse(readFileSync(path, "utf8")); c.report.rows[0].reportedVolumeDifference = 123; writeFileSync(path, JSON.stringify(c)); assert.throws(() => run(["--verify-comparison", "changes"], nextOpts), /COMPARISON_RECOMPUTATION/); }));
await test("time router isolates morning, close, weekend, before-start and end", () => { for (const [at, action] of [["2026-09-08T13:00:00.000Z", "DAILY_CONTEXT"], ["2026-09-08T13:30:00.000Z", "DAILY_CONTEXT"], ["2026-09-08T20:19:59.000Z", "YIELD"], ["2026-09-08T20:20:00.000Z", "CLOSE_CAPTURE"], ["2026-09-12T20:20:00.000Z", "YIELD"], ["2026-09-07T20:20:00.000Z", "YIELD"], ["2026-09-16T22:00:00.000Z", "RESTORE_V6"], ["2026-09-17T13:00:00.000Z", "RESTORE_V6"]]) assert.equal(routeChainClose(at).action, action); assert.equal(routeChainClose("2026-09-16T20:20:00.000Z").restoreAfterCapture, true); assert.equal(routeChainClose(at).developmentEnabled, false); });
function fakeMarket({ reject = false, expired = false } = {}) { const f = chainSurveyFixture(); return async (tool, req) => { if (reject && tool === "get_option_quotes") throw Error("PRIVATE_ERROR_NEVER_SAVED"); if (tool === "get_option_chains") return f.chains.find(c => c.symbol === req.underlying_symbol).response; if (tool === "get_option_instruments") { if (req.state === "expired") return { data: { instruments: expired ? [{ ...f.instruments[0].pages[0].response.data.instruments[0], id: "00000000-0000-4000-8000-000000000999", chain_id: req.chain_id, chain_symbol: req.chain_id === f.chains[0].response.data.chains[0].id ? "GLD" : "IBIT", expiration_date: "2026-09-08", state: "expired", tradability: "untradable" }] : [], next: null } }; return f.instruments.find(g => g.pages[0].request.chain_id === req.chain_id).pages[0].response; } if (tool === "get_option_quotes") return { data: { results: f.quotes.flatMap(q => q.batches[0].response.data.results).filter(r => req.instrument_ids.includes(r.quote.instrument_id)) } }; if (tool === "get_equity_quotes") return { data: { results: [] } }; throw Error("UNEXPECTED_TOOL"); }; }
const clock = async () => "2026-09-08 20:21:00 UTC";
await test("injectable collector uses only four market tools and queries expired state", async () => { const calls = []; const fake = fakeMarket(); const a = await collectChainClose({ sessionDate: "2026-09-08", clock, call: async (t, r) => { calls.push([t, r]); return fake(t, r); } }); assert.equal(a.failures.length, 0); assert.equal(a.expiredQueriesCompleted, 2); assert.equal(a.calls, 9); assert.equal(calls.filter(([, r]) => r.state === "expired").length, 2); assert(calls.filter(([t]) => t === "get_option_quotes").every(([, r]) => r.instrument_ids.length <= 20)); assert.equal(assessRobinhoodChainSurvey(JSON.stringify(a.capture), at).instrumentCount, 12); });
await test("collector errors stay sanitized and gaps stay missing", async () => { const a = await collectChainClose({ sessionDate: "2026-09-08", clock, call: fakeMarket({ reject: true }) }); assert.equal(a.failures.length, 2); assert(!JSON.stringify(a).includes("PRIVATE_ERROR")); assert.equal(assessRobinhoodChainSurvey(JSON.stringify(a.capture), at).quoteCount, 0); });
await test("collector rejects replay at a later date and before close", async () => { await assert.rejects(collectChainClose({ sessionDate: "2026-09-08", call: fakeMarket(), clock: async () => "2026-09-09 20:21:00 UTC" }), /WINDOW/); await assert.rejects(collectChainClose({ sessionDate: "2026-09-08", call: fakeMarket(), clock: async () => "2026-09-08 20:00:00 UTC" }), /WINDOW/); });
await test("host source works in an isolated function closure", async () => { const exported = run(["--host-source"]); const fn = new Function("return (" + exported.source + ");")(); const a = await fn({ sessionDate: "2026-09-08", clock, call: fakeMarket() }); assert.equal(a.calls, 9); });
await test("actual-time close receipt preserves failure and never claims verified daily volume", () => temp(async dir => { const a = await collectChainClose({ sessionDate: "2026-09-08", clock, call: fakeMarket({ reject: true }) }); writeFileSync(join(dir, "attempt.json"), JSON.stringify(a)); const r = run(["--record-close", "attempt.json", "close-20260908"], opts(dir)); assert.equal(r.sourceFailures, 2); assert.equal(r.completeSessionVolumeVerified, false); assert.equal(r.board.quoteCount, 0); assert.equal(run(["--close-status", "2026-09-08"], opts(dir)).existingEvidence, true); assert.throws(() => run(["--record-close", "attempt.json", "close-20260908"], opts(dir)), /EEXIST/); }));
console.log(`${passed}/${passed} tests passed.`);
