import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,realpathSync,readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {join,relative,isAbsolute} from 'node:path';
import {tmpdir} from 'node:os';
import {parseMacroSource,macroUrl,MACRO_MAX_BYTES} from '../src/engines/options-drivers/OptionsMacroContext.ts';
import {retrieveMacro,saveMacroBatch,verifyMacroBatch,macroContextView,previewMacroComparison,saveMacroComparison,verifyMacroComparison} from './lib/options-macro-context-io.mjs';
import {macroContextPanel,macroComparisonRequest,macroPreviewMatches} from '../apps/options-workbench/macro-context.js';
import {goldFrameworkView} from './lib/options-gold-framework.mjs';
import {contextRefreshSlots,runPublicContextOnce} from './options-context-service.mjs';
import {startOptionsWorkbench} from './options-workbench.mjs';
import {runGuidanceCommand} from './options-daily-guidance.mjs';
import {request as browserRequest} from '../apps/options-workbench/api.js';

let passed=0;async function test(n,f){await f();passed++;console.log('PASS '+n);}
async function temp(fn){const root=mkdtempSync(join(tmpdir(),'alpha-macro-test-'));try{await fn(root);}finally{const full=realpathSync(root),r=relative(realpathSync(tmpdir()),full);if(isAbsolute(r)||r.startsWith('..')||!r.startsWith('alpha-macro-test-'))throw Error('UNSAFE_TEST_CLEANUP');rmSync(full,{recursive:true,force:true});}}
const at='2026-09-08T21:00:00.000Z',after='2026-09-09T14:00:00.000Z';
const xml='<feed xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><title>DailyTreasuryYieldCurveRateData</title><entry><category term="TreasuryDataWarehouseModel.DailyTreasuryYieldCurveRateDatum"/><content><m:properties><d:Id>1</d:Id><d:NEW_DATE>2026-09-04T00:00:00</d:NEW_DATE>'+[2,5,10,30].map(t=>'<d:BC_'+t+'YEAR m:type="Edm.Double">4.50</d:BC_'+t+'YEAR>').join('')+'</m:properties></content></entry></feed>';
const tr=c=>'<tr>'+c.map(x=>'<td>'+x+'</td>').join('')+'</tr>';
const dollar='Release Date: September 8, 2026<table>'+tr(['COUNTRY','CURRENCY','Aug. 31','Sep. 1','Sep. 2','Sep. 3','Sep. 4'])+tr(['1) BROAD','JAN06=100','118.0000','118.5000','ND','118.3000','118.4000'])+tr(['*EMU MEMBERS','EURO','1.1000','1.2000','1.3000','1.4000','1.5000'])+tr(['JAPAN','YEN','151.0000','152.0000','153.0000','154.0000','155.0000'])+'</table>';
const nowcast=['month-over-month','year-over-year'].map(change=>'<table><caption>Inflation, '+change+' percent change</caption><thead>'+tr(['Month','CPI','Core CPI','PCE','Core PCE','Updated'])+'</thead><tbody>'+tr(['August 2026','0.30','0.20','','0.25','09/08'])+'</tbody></table>').join('');
const sourceTexts={nominal:xml,dollar,nowcast};
function inputs(clock=at){return Object.entries(sourceTexts).map(([id,sourceText])=>({id,url:macroUrl(id,clock),requestedAt:clock,receivedAt:clock,sourceText,errorCode:null}));}
function request(path,extra={}){return {requestId:'cpi-test-01',forecastPath:path,period:'2026-08',metric:'CPI_MOM',actualValue:'0.40',seasonalAdjustment:'SA',releaseAt:'2026-09-09T12:30:00.000Z',sourceUrl:'https://www.bls.gov/news.release/cpi.nr0.htm',...extra};}
await test('nominal yields parse into exact whole basis points',()=>assert.equal(parseMacroSource('nominal',xml,at).rows[0].ratesBps[10],450));
await test('nominal null is preserved rather than zero',()=>assert.equal(parseMacroSource('nominal',xml.replace('<d:BC_10YEAR m:type="Edm.Double">4.50','<d:BC_10YEAR m:type="Edm.Double" m:null="true">'),at).rows[0].ratesBps[10],null));
for(const [name,text] of [['wrong schema',xml.replaceAll('DailyTreasuryYieldCurveRateData','OtherData')],['duplicate date',xml.replace('</feed>',xml.match(/<entry>[\s\S]*<\/entry>/)[0]+'</feed>')],['future date',xml.replace('2026-09-04','2026-09-10')],['DTD','<!DOCTYPE feed>'+xml],['wrong namespace',xml.replace('http://www.w3.org/2005/Atom','https://example.com')],['missing tenor',xml.replace(/<d:BC_10YEAR.*?<\/d:BC_10YEAR>/,'')],['fraction precision',xml.replace('4.50','4.501')]])await test(name+' rejected',()=>assert.throws(()=>parseMacroSource('nominal',text,at)));
await test('H10 broad index is not DXY and FX units remain distinct',()=>{const r=parseMacroSource('dollar',dollar,at);assert.equal(r.kind,'H10_BROAD_DOLLAR_NOT_DXY');assert.equal(r.rows[4].broadIndexE4,1184000);assert.equal(r.rows[4].usdPerEuroE4,15000);assert.equal(r.rows[4].yenPerUsdE4,1550000);assert.equal(r.rows[2].broadIndexE4,null);assert.equal(r.publicationAt,null);});
await test('H10 New Year columns use the previous year only when necessary',()=>{const s=dollar.replace('September 8, 2026','January 5, 2027').replace('Aug. 31','Dec. 28').replace('Sep. 1','Dec. 29').replace('Sep. 2','Dec. 30').replace('Sep. 3','Dec. 31').replace('Sep. 4','Jan. 1');const r=parseMacroSource('dollar',s,'2027-01-05T20:00:00.000Z');assert.equal(r.rows[0].sourceDate,'2026-12-28');assert.equal(r.rows[4].sourceDate,'2027-01-01');});
for(const [name,text] of [['future release',dollar.replace('September 8','September 10')],['duplicate broad',dollar.replace('</table>',tr(['1) BROAD','JAN06=100','1','1','1','1','1'])+'</table>')],['ambiguous unit',dollar.replace('JAN06=100','DXY')],['duplicate date',dollar.replace('Sep. 4','Sep. 3')]])await test('H10 '+name+' rejected',()=>assert.throws(()=>parseMacroSource('dollar',text,at)));
await test('nowcast blank, units, periods and seasonal adjustment are explicit',()=>{const r=parseMacroSource('nowcast',nowcast,at);assert.equal(r.kind,'MODEL_NOWCAST_NOT_CONSENSUS');assert.equal(r.rows.find(x=>x.metric==='PCE_MOM').valueBps,null);assert.equal(r.rows.find(x=>x.metric==='CPI_YOY').seasonalAdjustment,'NSA');assert.equal(r.rows.find(x=>x.metric==='PCE_YOY').seasonalAdjustment,'SA');assert.equal(r.updateYearAndTimeKnown,false);assert.equal(r.ppiCoverage,'NOT_PROVIDED');});
for(const [name,text] of [['changed header',nowcast.replace('Core CPI','Other CPI')],['future month',nowcast.replaceAll('August 2026','October 2026')],['invalid update label',nowcast.replaceAll('09/08','13/01')],['duplicate table',nowcast+nowcast],['script inside data',nowcast.replace('0.30','<script>0.30</script>')]])await test('nowcast '+name+' rejected',()=>assert.throws(()=>parseMacroSource('nowcast',text,at)));
await test('source text and date limits reject unknown or oversized input',()=>{assert.throws(()=>parseMacroSource('other',xml,at));assert.throws(()=>parseMacroSource('dollar','x'.repeat(MACRO_MAX_BYTES+1),at));assert.throws(()=>parseMacroSource('dollar',dollar,'yesterday'));});
await test('three transports use fixed anonymous endpoints without following redirects',async()=>{for(const id of ['nominal','dollar','nowcast']){const r=await retrieveMacro(id,{clock:()=>at,fetchImplementation:async(url,o)=>{assert.equal(url,macroUrl(id,at));assert.equal(o.credentials,'omit');assert.equal(o.redirect,'manual');return new Response(sourceTexts[id],{headers:{'content-type':id==='nominal'?'text/xml':'text/html'}});}});assert.equal(r.errorCode,null);assert.equal(r.sourceText,sourceTexts[id]);}});
for(const [name,make,code] of [
  ['redirect',()=>new Response('',{status:302}),'HTTP_STATUS'],
  ['wrong content type',()=>new Response('body',{headers:{'content-type':'application/json'}}),'CONTENT_TYPE'],
  ['excess declared size',()=>new Response('body',{headers:{'content-type':'text/html','content-length':String(MACRO_MAX_BYTES+1)}}),'BODY_LIMIT'],
  ['excess actual size',()=>new Response('x'.repeat(MACRO_MAX_BYTES+1),{headers:{'content-type':'text/html'}}),'BODY_LIMIT'],
  ['invalid UTF8',()=>new Response(new Uint8Array([0xff]),{headers:{'content-type':'text/html'}}),'UTF8'],
  ['empty body',()=>new Response('',{headers:{'content-type':'text/html'}}),'BODY_MISSING'],
])await test('transport '+name+' is sanitized',async()=>{const r=await retrieveMacro('dollar',{clock:()=>at,fetchImplementation:async()=>make()});assert.equal(r.errorCode,code);assert.equal(r.sourceText,null);});
await test('deadline bounds a fetch that ignores cancellation',async()=>assert.equal((await retrieveMacro('dollar',{clock:()=>at,deadlineMs:5,fetchImplementation:()=>new Promise(()=>{})})).errorCode,'DEADLINE'));
await test('local permission errors are distinguished without leaking raw error text',async()=>{const r=await retrieveMacro('dollar',{clock:()=>at,fetchImplementation:async()=>{throw Object.assign(Error('PRIVATE URL SECRET'),{cause:{code:'EACCES'}});}});assert.equal(r.errorCode,'NETWORK_ACCESS_DENIED');assert(!JSON.stringify(r).includes('SECRET'));});
await test('empty store is read-only and exposes missing coverage',()=>temp(root=>{const r=macroContextView(root,at);assert(r.sources.every(s=>s.status==='NOT_REFRESHED'));assert.equal(r.forecasts.length,0);assert.deepEqual(readdirSync(root),[]);}));
await test('saved raw sources independently reparse and recover with as-of receipt limits',()=>temp(root=>{const s=saveMacroBatch(root,inputs(),at),v=verifyMacroBatch(root,s.path),before=readFileSync(join(root,s.path));assert.equal(v.batch.sources.length,3);assert.equal(macroContextView(root,'2026-09-08T20:59:59.999Z').recordsRead,0);const r=macroContextView(root,at);assert.equal(r.recordsRead,1);assert.equal(r.forecasts.length,1);assert(readFileSync(join(root,s.path)).equals(before));}));
await test('one failed source retains last-known values and latest failure separately',()=>temp(root=>{saveMacroBatch(root,inputs(),at);const next=inputs(after);next[1].sourceText=null;next[1].errorCode='HTTP_STATUS';saveMacroBatch(root,next,after);const s=macroContextView(root,after).sources.find(s=>s.id==='dollar');assert.equal(s.status,'FAILED');assert.equal(s.lastKnown.receivedAt,at);assert.equal(s.latest.receivedAt,after);}));
await test('parser failures preserve raw source for inspection and do not erase other sources',()=>temp(root=>{const x=inputs();x[2].sourceText='<html>changed</html>';const saved=saveMacroBatch(root,x,at),b=verifyMacroBatch(root,saved.path).batch;assert.equal(b.sources[2].errorCode,'SOURCE_SCHEMA');assert.equal(b.inputs[2].sourceText,'<html>changed</html>');assert.equal(b.sources[0].status,'OK');}));
await test('old source date cannot become synchronized intraday evidence',()=>temp(root=>{saveMacroBatch(root,inputs(),at);const real={latestRetrieval:{status:'OK',receivedAt:at},currentRow:{sourceDate:'2026-09-03',ratesBps:{10:200}}};assert.equal(macroContextView(root,at,real).parCurveComparison.nominalMinusRealBps,null);real.currentRow.sourceDate='2026-09-04';const r=macroContextView(root,at,real);assert.equal(r.parCurveComparison.nominalMinusRealBps,250);assert(r.parCurveComparison.meaning.includes('not fitted breakeven'));}));
await test('source and stored derived-value tampering are detected',()=>temp(root=>{const s=saveMacroBatch(root,inputs(),at),path=join(root,s.path),r=JSON.parse(readFileSync(path));r.batch.sources[0].data.rows[0].ratesBps[10]=999;writeFileSync(path,JSON.stringify(r));assert.throws(()=>verifyMacroBatch(root,s.path),/INTEGRITY/);}));
await test('unsafe paths and unexpected files do not disappear from recovery',()=>temp(root=>{assert.throws(()=>verifyMacroBatch(root,'../README.md'),/PATH/);const s=saveMacroBatch(root,inputs(),at);writeFileSync(join(root,s.path.replace(/[^/]+$/,'unexpected.txt')),'bad');assert.throws(()=>macroContextView(root,at),/CATALOG/);}));
await test('event comparison uses exact model error with explicit unverified actual',()=>temp(root=>{const s=saveMacroBatch(root,inputs(),at),r=previewMacroComparison(root,request(s.path),after);assert.equal(r.actualMinusModelHundredthsPp,10);assert.equal(r.comparisonKind,'MODEL_FORECAST_ERROR_NOT_CONSENSUS_SURPRISE');assert.equal(r.actualEvidence,'OWNER_REPORTED_UNVERIFIED');assert.equal(r.executionAllowed,false);}));
for(const [name,extra] of [['future release',{releaseAt:'2026-09-10T12:30:00.000Z'}],['same-clock forecast',{releaseAt:at}],['past release',{releaseAt:'2026-09-08T12:30:00.000Z'}],['mismatched period',{period:'2026-07'}],['PPI not provided',{metric:'PPI_MOM'}],['missing model cell',{metric:'PCE_MOM'}],['wrong adjustment',{seasonalAdjustment:'NSA'}],['wrong agency',{sourceUrl:'https://www.bea.gov/'}],['untrusted host',{sourceUrl:'https://bls.gov.example.com/'}],['URL credentials',{sourceUrl:'https://secret@www.bls.gov/'}],['invalid actual',{actualValue:'NaN'}],['unsafe ID',{requestId:'../outside'}]])await test('comparison blocks '+name,()=>temp(root=>{const s=saveMacroBatch(root,inputs(),at);assert.throws(()=>previewMacroComparison(root,request(s.path,extra),after));}));
await test('save is idempotent, conflicts cannot overwrite and history recomputes',()=>temp(root=>{const s=saveMacroBatch(root,inputs(),at),q=request(s.path),one=saveMacroComparison(root,q,after),bytes=readFileSync(join(root,one.path));assert.equal(saveMacroComparison(root,q,after).alreadyRecorded,true);assert.throws(()=>saveMacroComparison(root,{...q,actualValue:'0.50'},after),/CONFLICT/);assert(readFileSync(join(root,one.path)).equals(bytes));assert.equal(verifyMacroComparison(root,one.path).actualMinusModelHundredthsPp,10);assert.equal(macroContextView(root,at).comparisons.length,0);assert.equal(macroContextView(root,after).comparisons.length,1);}));
await test('macro scheduling preserves original slots and adds one separate after-17 claim',()=>{assert.equal(contextRefreshSlots('2026-09-08T20:59:00.000Z').some(s=>s.key.startsWith('macro-')),false);const s=contextRefreshSlots(at);assert.deepEqual(s[0].sources,['headlines','btc']);assert.deepEqual(s[1].sources,['treasury','bls','fomc']);assert.deepEqual(s.at(-1),{key:'macro-daily-2026-09-08',sources:['macro_context']});assert.equal(contextRefreshSlots('2026-11-09T21:59:00.000Z').some(s=>s.key.startsWith('macro-')),false);assert(contextRefreshSlots('2026-11-09T22:00:00.000Z').some(s=>s.key.startsWith('macro-')));});
await test('two workers and repeated same-day runs cannot duplicate the new source slot',()=>temp(async root=>{let count=0;const o={workspaceRoot:root,now:()=>at,issue:false,execute:async name=>{if(name==='macro_context')count++;return {status:'OK'};}};await Promise.all([runPublicContextOnce(o),runPublicContextOnce(o)]);await runPublicContextOnce({...o,now:()=>"2026-09-09T01:00:00.000Z"});assert.equal(count,1);await runPublicContextOnce({...o,now:()=>after.replace('14:00','22:00')});assert.equal(count,2);}));
await test('UI draft changes invalidate a preview and source markup is escaped',()=>temp(root=>{saveMacroBatch(root,inputs(),at);const v=macroContextView(root,at),f=v.forecasts[0],d={requestId:'cpi-test-01',forecastKey:[f.path,'2026-08','CPI_MOM'].join('|'),actualValue:'0.40',seasonalAdjustment:'SA',releaseAt:'2026-09-09T12:30:00.000Z',sourceUrl:'https://www.bls.gov/'};const p=previewMacroComparison(root,macroComparisonRequest(d),after);assert(macroPreviewMatches(p,d));assert(!macroPreviewMatches(p,{...d,actualValue:'0.50'}));const html=macroContextPanel({state:'AVAILABLE',data:v},{macroDraft:{...d,actualValue:'<img src=x>'}});assert(!html.includes('<img'));assert(html.includes('&lt;img'));assert(html.includes('Broad USD is not DXY'));assert(html.includes('Save comparison'));}));
await test('gold checklist shows broad USD and model coverage without a DXY or consensus claim',()=>temp(root=>{saveMacroBatch(root,inputs(),at);const v=goldFrameworkView({macroContext:{state:'AVAILABLE',data:macroContextView(root,at)}},at);assert.equal(v.counts.partialNumericalAreas,3);assert.equal(v.areas.find(a=>a.id==='real_rates').numericEvidence.tenYearNominalYieldBps,450);assert.equal(v.areas.find(a=>a.id==='dollar').numericEvidence.kind,'BROAD_USD_NOT_DXY');assert.equal(v.direction,'UNDETERMINED');}));
await test('browser allowlist and protected API expose preview/save without account or source routes',()=>temp(async root=>{const s=saveMacroBatch(root,inputs(),at),app=await startOptionsWorkbench({workspaceRoot:root,port:0,now:()=>after}),fetchBefore=globalThis.fetch,locationBefore=globalThis.location;try{assert.equal((await fetch(app.url+'/api/macro-comparison',{method:'POST',headers:{'content-type':'application/json'},body:'{}'})).status,403);globalThis.location={origin:app.url};globalThis.fetch=(path,o)=>fetchBefore(new URL(path,app.url),{...o,headers:{...o.headers,...(o.method==='POST'?{Origin:app.url}:{})}});const state=await browserRequest('/api/state');assert.equal(state.macroContext.state,'AVAILABLE');const body={action:'PREVIEW',request:request(s.path)};const p=await browserRequest('/api/macro-comparison',body);assert.equal(p.actualMinusModelHundredthsPp,10);const saved=await browserRequest('/api/macro-comparison',{...body,action:'SAVE'});assert.equal(saved.result.actualEvidence,'OWNER_REPORTED_UNVERIFIED');assert.equal((await fetchBefore(app.url+'/macro-context.js')).status,200);const brief=await runGuidanceCommand(['--host-brief'],{workspaceRoot:root,now:()=>after});assert.equal(brief.macroContext.version,'OPTIONS_MACRO_CONTEXT_V1');assert.equal((await fetchBefore(app.url+'/api/macro-refresh',{method:'POST'})).status,404);}finally{globalThis.fetch=fetchBefore;if(locationBefore===undefined)delete globalThis.location;else globalThis.location=locationBefore;await app.close();}}));
console.log(passed+'/'+passed+' tests passed.');
