import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,realpathSync,readFileSync} from 'node:fs';
import {join,relative,isAbsolute} from 'node:path';
import {tmpdir} from 'node:os';
import {assessScenarioEV,assessContractFit} from '../src/engines/options-retail-feasibility/OptionsScenarioResearch.ts';
import {blankScenario,scenarioResult,contractFitResult,scenarioResearchPanel} from '../apps/options-workbench/scenario-research.js';
import {seedExpectation,expectationPlan,expectationLater as at} from './lib/options-market-expectation-fixtures.mjs';
import {scenarioPlanContexts,previewScenario,saveScenario,verifyScenario,verifyNewPlanScenario,contractFitView} from './lib/options-scenario-research.mjs';
import {createWorkbenchData} from './lib/options-workbench-data.mjs';
import {startOptionsWorkbench} from './options-workbench.mjs';
import {registerDefaults} from '../apps/options-workbench/forms.js';
import {paperFingerprint as fp} from '../src/engines/options-paper/OptionsPaperTradingEngine.ts';
import {defaultGuidanceSettings} from '../src/engines/options-daily-guidance/OptionsDailyGuidance.ts';

let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
const exit='2026-09-09T19:00:00.000Z',expiry='2026-09-25';
function rows(){return ['50','30','20'].map((p,i)=>({...blankScenario('s-'+i),label:['Up','Flat','Down'][i],eventOutcome:'Isolated event',marketInterpretation:'Synthetic conditional response',probability:p,probabilitySource:'OWNER_ASSUMPTION',probabilityAsOf:at(1),probabilityEvidenceRef:'Isolated owner declaration',payoff:String([200,100,0][i]),payoffSource:'OWNER_SUPPLIED_PAYOFF',payoffAt:exit,payoffBasis:'PLANNED_EXIT',payoffEvidenceRef:'Isolated whole-position exit assumption',costs:{premiumUsd:'100',feesUsd:'2',slippageUsd:'3',evidenceRef:'Explicit isolated cost assumptions'},limitations:'Not a price model'}));}
const ev=r=>assessScenarioEV(r,at(50),exit,expiry,1);
await test('exact signed net arithmetic includes premium fees and slippage once',()=>{const r=ev(rows());assert.equal(r.assumptionEvUsd,'25.000000000000');assert.deepEqual(r.rows.map(x=>x.netPayoff),['95.000000','-5.000000','-105.000000']);assert.equal(r.rows[0].contributionUsd,'47.500000000000');assert.equal(r.validatedEv,'UNKNOWN');assert.equal(r.executionAllowed,false);assert.equal(r.quantity,1);assert.equal(r.positionSizingChanged,false);});
for(const [label,change,code] of [
  ['missing probability',r=>r[0].probability='','PROBABILITY_REQUIRED'],
  ['prose probability',r=>r[0].probability='likely','PROBABILITY_INVALID'],
  ['negative probability',r=>r[0].probability='-1','PROBABILITY_INVALID'],
  ['over 100 probability',r=>r[0].probability='101','PROBABILITY_INVALID'],
  ['sum below',r=>r[0].probability='49','PROBABILITY_SUM_INVALID'],
  ['sum above',r=>r[0].probability='51','PROBABILITY_SUM_INVALID'],
  ['unknown provenance',r=>r[0].probabilitySource='UNKNOWN','PROBABILITY_SOURCE_UNKNOWN'],
  ['unapproved calibrated label',r=>r[0].probabilitySource='CALIBRATED_MODEL','CALIBRATED_MODEL_NOT_APPROVED'],
  ['future probability',r=>r[0].probabilityAsOf=at(60),'PROBABILITY_PROVENANCE_REQUIRED'],
  ['missing payoff',r=>r[0].payoff='','PAYOFF_UNKNOWN'],
  ['unknown payoff source',r=>r[0].payoffSource='UNKNOWN','PAYOFF_UNKNOWN'],
  ['Greek shocks not option pricing',r=>r[0].payoffSource='EXISTING_DETERMINISTIC_CALCULATOR','PAYOFF_CALCULATOR_NOT_AVAILABLE'],
  ['expiry is not early exit',r=>r[0].payoffBasis='EXPIRATION','EXPIRY_PAYOFF_IS_NOT_EARLY_EXIT'],
  ['wrong exit horizon',r=>r[0].payoffAt=at(100),'PAYOFF_HORIZON_MISMATCH'],
  ['missing fees',r=>r[0].costs.feesUsd='','COST_UNKNOWN'],
  ['missing slippage',r=>r[0].costs.slippageUsd='','COST_UNKNOWN'],
  ['unattributed zero costs',r=>r[0].costs.evidenceRef='','COST_UNKNOWN'],
  ['different entry premiums',r=>r[0].costs.premiumUsd='90','PREMIUM_COST_INCONSISTENT']
])await test(label+' refuses EV without filling gaps',()=>{const r=rows();change(r);const before=fp(r),result=ev(r);assert.equal(result.status,'NOT_CALCULABLE');assert.equal(result.assumptionEvUsd,null);assert(result.reasons.some(s=>s.endsWith(code)));assert.equal(fp(r),before);});
await test('unattributed costs or payoff cannot produce a displayed net amount',()=>{const r=rows();r[0].costs.evidenceRef='';assert.equal(ev(r).rows[0].netPayoff,null);r[0]=rows()[0];r[0].payoffSource='UNKNOWN';assert.equal(ev(r).rows[0].netPayoff,null);});
await test('zero explicitly sourced costs and arbitrary scenario count are supported',()=>{const r=rows();for(const v of r)v.costs={premiumUsd:'100',feesUsd:'0',slippageUsd:'0',evidenceRef:'Explicit synthetic zero-cost assumption'};r.push({...r[2],scenarioId:'fourth',probability:'0'});assert.equal(ev(r).assumptionEvUsd,'30.000000000000');assert.equal(ev(r).rows.length,4);});
await test('two scenarios never become 50/50 and no quantity is selected',()=>{const r=[blankScenario('one'),blankScenario('two')];assert.equal(ev(r).probabilitySumPercent,0);assert.equal(assessScenarioEV(rows(),at(50),exit,expiry,null).assumptionEvUsd,null);});
await test('tiny exact percentages preserve exact contributions without floating rounding',()=>{const r=rows();r[0].probability='0.0001';r[1].probability='99.9999';r[2].probability='0';assert.equal(ev(r).assumptionEvUsd,'-4.999900000000');});

const quote=()=>({id:'00000000-0000-0000-0000-000000000001',symbol:'GLD',expiry,type:'call',strike:'400',multiplier:100,bidCents:98,askCents:100,tickCents:1,bidSize:20,askSize:20,delta:0.5,updatedAt:at(90),receivedAt:at(90)});
const settings=()=>({...defaultGuidanceSettings(),roundTripFeesCents:100,slippageReserveCents:100,tradeBudget:{version:'OWNER_ALLOCATION_ONLY_V2',minCents:10000,maxCents:50000}});
const fitInput=()=>({at:at(100),context:{key:'frozen:synthetic',tradeId:'synthetic',version:fp('plan'),kind:'FROZEN',registeredAt:at(80),contract:{symbol:'GLD',optionType:'CALL',expiry,strikeUsd:'400',multiplier:100},plan:{...expectationPlan(),maxEntryDebitUsd:'200',plannedRiskUsd:'50'}},quote:quote(),sensitivity:null,settings:settings(),originalBlockers:[],quantity:1});
const dim=(r,name)=>r.dimensions.find(d=>d.dimension===name);
await test('fresh within horizon and risk is research only without scores',()=>{const r=assessContractFit(fitInput());assert.equal(dim(r,'Event / thesis horizon').status,'WITHIN_PLAN');assert.equal(dim(r,'Quote freshness').status,'WITHIN_PLAN');assert.equal(dim(r,'Premium / maximum loss').status,'WITHIN_PLAN');assert.equal(r.executionAllowed,false);assert(!/score|rank|best/i.test(Object.keys(r).join(',')));assert.equal(r.quantity,1);assert.equal(r.dimensions.length,15);});
await test('expiration before realization or exit is outside plan',()=>{const x=fitInput();x.context.plan.timeExitAt='2026-09-28T19:00:00.000Z';const r=assessContractFit(x);assert.equal(dim(r,'Event / thesis horizon').status,'OUTSIDE_PLAN');assert(r.blockers.includes('CONTRACT_OUTSIDE_PLAN'));});
await test('unknown calendar and missing horizon cannot pass coverage',()=>{const x=fitInput();x.quote.expiry='2027-01-15';assert.equal(dim(assessContractFit(x),'Event / thesis horizon').status,'UNKNOWN');x.quote=quote();x.context.plan.timeExitAt=null;assert.equal(dim(assessContractFit(x),'Event / thesis horizon').status,'UNKNOWN');});
await test('stale source remains reference and never current valuation',()=>{const x=fitInput();x.originalBlockers=['OPTION_QUOTE_NOT_FRESH'];const r=assessContractFit(x);assert.equal(dim(r,'Quote freshness').value.reference,'STALE_REFERENCE');assert.equal(dim(r,'Premium / maximum loss').value.valuation,'REFERENCE_ONLY');assert.equal(r.status,'NOT_READY_FOR_CURRENT_COMPARISON');});
await test('future source or receipt fails and no quote retains independent event context',()=>{const x=fitInput();x.quote.receivedAt=at(101);assert.equal(dim(assessContractFit(x),'Quote freshness').status,'BLOCKED_BY_EXISTING_RULE');x.quote=null;const r=assessContractFit(x);assert(r.blockers.includes('QUOTE_EVIDENCE_MISSING'));assert.equal(dim(r,'Event gap risk').value.phase,'PRE_EVENT');});
await test('missing Greeks unknown; explicit IV is informational without 40% threshold',()=>{const x=fitInput();x.sensitivity={sourceAt:at(90),impliedVolatilityPercent:'45',metrics:{}};const r=assessContractFit(x);for(const name of ['Gamma','Theta','Vega'])assert.equal(dim(r,name).value,null);assert.equal(dim(r,'IV context').status,'UNKNOWN');assert.equal(dim(r,'IV context').value.currentPercent,'45');});
await test('wide spread no invented hard threshold; original policy blocker retained',()=>{const x=fitInput();x.quote.bidCents=10;const r=assessContractFit(x);assert.equal(dim(r,'Bid / ask spread').status,'UNKNOWN');assert.equal(dim(r,'Bid / ask spread').value.midpointCents,55);x.originalBlockers=['SPREAD_OR_PRICE_UNSUITABLE'];assert(assessContractFit(x).blockers.includes('SPREAD_OR_PRICE_UNSUITABLE'));});
await test('zero bid cannot produce valid spread or midpoint',()=>{const x=fitInput();x.quote.bidCents=0;assert.equal(dim(assessContractFit(x),'Bid / ask spread').value,null);});
await test('premium above existing allocation and explicit quantity remain blocked unchanged',()=>{const x=fitInput();x.quantity=6;const before=fp(x),r=assessContractFit(x);assert(r.blockers.includes('ALLOCATION_BUDGET_EXCEEDED'));assert(r.blockers.includes('PLAN_QUANTITY_UNDEFINED_OR_EXCEEDED'));assert.equal(r.quantity,6);assert.equal(fp(x),before);});
await test('per-contract guidance costs scale once into whole-position risk totals',()=>{const x=fitInput();x.quantity=2;const r=assessContractFit(x);assert.equal(r.risk.scenario.roundTripFeesCents,200);assert.equal(r.risk.scenario.slippageReserveCents,200);assert.equal(r.risk.economics.capitalRequiredCents,20200);assert(r.blockers.includes('PLAN_PREMIUM_LIMIT_EXCEEDED'));});
await test('PRE_EVENT retains gap, market closure and explicit manual coverage',()=>{const r=assessContractFit(fitInput()),d=dim(r,'Event gap risk');assert.equal(d.value.holdThroughEvent,'YES');assert.equal(d.value.nextScheduledTradableAt,'2026-09-09T13:30:00.000Z');assert(d.reason.includes('No stop execution'));assert.equal(dim(r,'Exit observability').value.coverage,'MANUAL_REVIEW_REQUIRED');});

async function temp(fn){const root=mkdtempSync(join(tmpdir(),'alpha-expectation-test-'));try{await fn(root);}finally{const full=realpathSync(root),rel=relative(realpathSync(tmpdir()),full);if(isAbsolute(rel)||rel.startsWith('..')||!rel.startsWith('alpha-expectation-test-'))throw Error('UNSAFE_TEST_CLEANUP');rmSync(full,{recursive:true,force:true});}}
async function fixture(root){
  const f=await seedExpectation(root),expectation=f.save({...f.request,id:'final-reference',stage:'FINAL_PRE_ENTRY',ownerConfirmed:true},at(10)),plan=expectationPlan();
  plan.invalidation.expectationSnapshot={path:expectation.path,fingerprint:expectation.fingerprint,frozenAt:expectation.savedAt};
  const fields={...registerDefaults(),tradeId:'synthetic-event-plan',symbol:'GLD',optionType:'CALL',expiry,strikeUsd:'400',includePlan:true};
  for(const [k,v] of Object.entries(plan))if(k!=='invalidation')fields[k]=v===null?'':String(v);
  const command={type:'SAVE_PLAN_DRAFT',requestId:'complete-draft',tradeId:fields.tradeId,draft:{fields,thesis:plan.invalidation}};
  f.setClock(at(20));const prev=f.service.preview(command);f.service.save({command,expectedHeadSha256:prev.headSha256});
  f.setClock(at(50));const state=await f.service.state(),p=scenarioPlanContexts(state.manual.data).find(p=>p.key==='draft:complete-draft');
  state.guidance={data:{input:{quotes:[{...quote(),updatedAt:at(40),receivedAt:at(40)}]},sourcePaths:[]}};
  const request={id:'scenario-fixture',scenarioSetVersion:1,supersedes:'',planKey:p.key,planVersion:p.version,expectationSnapshotId:expectation.id,contractId:quote().id,quantity:1,rows:rows(),note:'Isolated only'};
  return {...f,state,p,request,plan};
}
await test('save read restart idempotency and append revisions preserve original bytes',()=>temp(async root=>{const f=await fixture(root),p=previewScenario(root,f.ledgerId,f.request,f.state,at(50)),r=saveScenario(root,f.ledgerId,f.request,p.previewFingerprint,f.state,at(50)),bytes=readFileSync(join(root,r.path));assert.equal(r.payload.assessment.assumptionEvUsd,'25.000000000000');assert(saveScenario(root,f.ledgerId,f.request,p.previewFingerprint,f.state,at(55)).alreadyRecorded);assert.throws(()=>saveScenario(root,f.ledgerId,{...f.request,note:'changed'},p.previewFingerprint,f.state,at(55)),/RETRY_CHANGED/);const req={...f.request,id:'scenario-revision',scenarioSetVersion:2,supersedes:r.path};req.rows=rows();req.rows[0].payoff='300';const p2=previewScenario(root,f.ledgerId,req,f.state,at(60)),r2=saveScenario(root,f.ledgerId,req,p2.previewFingerprint,f.state,at(60));assert.equal(r2.payload.assessment.assumptionEvUsd,'75.000000000000');assert(readFileSync(join(root,r.path)).equals(bytes));const s=await createWorkbenchData({workspaceRoot:root,ledgerId:f.ledgerId,now:()=>at(70)}).state();assert.equal(s.scenarioResearch.data.records.length,2);assert.equal(s.manual.data.trades.length,0);assert.equal(s.sourceComparisons.data.records.filter(r=>r.kind==='scenario').length,0);}));
await test('plan freeze pins assumptions and original selection; changed plan or reference rejected',()=>temp(async root=>{const f=await fixture(root),p=previewScenario(root,f.ledgerId,f.request,f.state,at(50)),r=saveScenario(root,f.ledgerId,f.request,p.previewFingerprint,f.state,at(50));f.plan.invalidation.scenarioSet={path:r.path,fingerprint:r.fingerprint,savedAt:r.savedAt};const c={type:'REGISTER_TRADE',requestId:'freeze-scenarios',tradeId:f.p.tradeId,contract:f.p.contract,plan:f.plan,activityReference:null};f.setClock(at(80));const preview=f.service.preview(c);f.service.save({command:c,expectedHeadSha256:preview.headSha256});const s=await createWorkbenchData({workspaceRoot:root,ledgerId:f.ledgerId,now:()=>at(90)}).state();assert.equal(s.manual.data.trades[0].plan.invalidation.scenarioSet.fingerprint,r.fingerprint);assert.equal(s.manual.data.trades[0].openContracts,0);const changed=structuredClone(c);changed.plan.thesis='Later favorable rewrite';assert.throws(()=>verifyNewPlanScenario(root,f.ledgerId,changed,at(90)),/FROZEN_PLAN_MISMATCH/);changed.plan=c.plan;changed.plan.invalidation.scenarioSet.fingerprint=fp('tampered');assert.throws(()=>verifyNewPlanScenario(root,f.ledgerId,changed,at(90)),/FROZEN_PLAN_MISMATCH/);assert.equal(verifyScenario(root,r.path,f.ledgerId,at(90)).fingerprint,r.fingerprint);}));
await test('missing probabilities employment-like draft stays saveable and not calculable',()=>temp(async root=>{const f=await seedExpectation(root),state=await f.service.state(),request={id:'empty-research',scenarioSetVersion:1,supersedes:'',planKey:f.p.key,planVersion:f.p.version,expectationSnapshotId:'',contractId:'',quantity:null,rows:[],note:'Research gaps'};const p=previewScenario(root,f.ledgerId,request,state,at(50)),r=saveScenario(root,f.ledgerId,request,p.previewFingerprint,state,at(50));assert.equal(r.payload.assessment.status,'NOT_CALCULABLE');const fit=contractFitView({...state,loadedAt:at(50)},f.p.key,f.p.version,'',null);assert.equal(fit.status,'NOT_READY_FOR_CURRENT_COMPARISON');assert.equal(fit.contractId,null);assert.equal(state.manual.data.trades.length,0);}));
await test('protected API saves and restores without exposing source refresh or trade operations',()=>temp(async root=>{const f=await seedExpectation(root),server=await startOptionsWorkbench({workspaceRoot:root,ledgerId:f.ledgerId,port:0,refreshContext:false,now:()=>at(50)});try{const s=await fetch(server.url+'/api/state').then(r=>r.json());const request={id:'api-research',scenarioSetVersion:1,supersedes:'',planKey:f.p.key,planVersion:f.p.version,expectationSnapshotId:'',contractId:'',quantity:null,rows:[],note:'Isolated API'};const post=b=>fetch(server.url+'/api/scenario-research',{method:'POST',headers:{Origin:server.url,'Content-Type':'application/json','X-Alpha-Session':s.session},body:JSON.stringify(b)});assert.equal((await fetch(server.url+'/api/scenario-research',{method:'POST',body:'{}'})).status,403);const p=await post({action:'PREVIEW',request}).then(r=>r.json());assert.equal(p.assessment.status,'NOT_CALCULABLE');const saved=await post({action:'SAVE',request,previewFingerprint:p.previewFingerprint}).then(r=>r.json());assert.equal(saved.kind,'scenario');const reread=await fetch(server.url+'/api/state').then(r=>r.json());assert.equal(reread.scenarioResearch.data.records[0].fingerprint,saved.fingerprint);assert.equal(reread.manual.data.trades.length,0);assert.equal((await fetch(server.url+'/scenario-research.js')).status,200);}finally{await server.close();}}));
await test('English UI renders provenance costs versions and risk without recommending a contract',()=>{const e=scenarioResult(ev(rows())),f=contractFitResult(assessContractFit(fitInput()));for(const x of ['ASSUMPTION_EV','Validated EV: UNKNOWN','OWNER_ASSUMPTION','Positive assumption EV does not create trade permission'])assert(e.includes(x));assert(f.includes('No stop execution'));assert(!f.includes('BEST CONTRACT'));assert(scenarioResearchPanel({scenarioResearch:{data:{plans:[],records:[]}}},{}).includes('NOT_READY_FOR_CURRENT_COMPARISON'));});
await test('browser transport admits only the protected local scenario route and fields do not shadow form ID',async()=>{const previousFetch=globalThis.fetch,previousLocation=globalThis.location;let called=null;try{globalThis.location={origin:'http://127.0.0.1:4173'};globalThis.fetch=async(path,options)=>{called={path,options};return {ok:true,json:async()=>({executionAllowed:false})};};const {request}=await import('../apps/options-workbench/api.js');assert.equal((await request('/api/scenario-research',{action:'FIT'})).executionAllowed,false);assert.equal(called.path,'/api/scenario-research');assert.equal(called.options.method,'POST');await assert.rejects(()=>request('https://example.com/api/scenario-research',{}),/Unsupported/);const html=scenarioResearchPanel({scenarioResearch:{data:{plans:[],records:[]}}},{scenarioDraft:{id:'test',planKey:'test',planVersion:'test',scenarioSetVersion:1,rows:[],contractId:'',expectationSnapshotId:'',quantity:null,note:''}});assert(html.includes('name="scenarioSetId"'));assert(!html.includes('name="id"'));}finally{globalThis.fetch=previousFetch;if(previousLocation===undefined)delete globalThis.location;else globalThis.location=previousLocation;}});
console.log(`${passed}/${passed} tests passed`);
