import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtempSync,rmSync,readFileSync,writeFileSync,cpSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {assessReportedSpreads,saveReportedSpreadReview,readReportedSpreadReview,reportedSpreadView} from './lib/options-spread-review.mjs';
import {spreadReviewPanel,spreadCapitalNotice} from '../apps/options-workbench/spread-review.js';
import {collectLessons} from '../apps/options-workbench/model.js';
const image=Buffer.from([255,216,255,217]),sha=createHash('sha256').update(image).digest('hex');
function fixture(){return {version:'REPORTED_SPREAD_INPUT_V1',id:'synthetic-spread-review',recordedAt:'2026-09-17T14:00:00.000Z',origin:'OWNER_SUPPLIED_SCREENSHOTS',yearBasis:'CONVERSATION_CONTEXT',reportedCapital:{amountCents:25000,basis:'BUYING_POWER',reportedOn:'2026-09-17'},originalPlanText:null,ownerReportsClosed:false,evidence:[{name:'evidence-1.jpg',sha256:sha}],trades:[{id:'synthetic-call',symbol:'GLD',optionType:'CALL',expiry:'2026-09-25',filledMinute:'2026-09-15T15:00-04:00',quantity:2,multiplier:100,debitPerShareCents:40,estimatedFeesCents:16,estimatedCostCents:8016,longStrikeCents:41000,shortStrikeCents:41500,longPriceCents:70,shortPriceCents:30,evidenceName:'evidence-1.jpg'},{id:'synthetic-put',symbol:'GLD',optionType:'PUT',expiry:'2026-09-18',filledMinute:'2026-09-15T15:01-04:00',quantity:3,multiplier:100,debitPerShareCents:20,estimatedFeesCents:24,estimatedCostCents:6024,longStrikeCents:39000,shortStrikeCents:38500,longPriceCents:50,shortPriceCents:30,evidenceName:'evidence-1.jpg'}]};}
function temp(fn){const root=mkdtempSync(join(tmpdir(),'alpha-spread-test-'));try{return fn(root);}finally{assert(resolve(root).startsWith(resolve(tmpdir())+'\\')||resolve(root).startsWith(resolve(tmpdir())+'/'));rmSync(root,{recursive:true,force:true});}}
function closingFixture(){const priorInput=fixture();return {version:'REPORTED_SPREAD_CLOSING_INPUT_V2',id:'synthetic-closing-review',recordedAt:'2026-09-17T15:00:00.000Z',priorInput,priorInputSha256:createHash('sha256').update(JSON.stringify(priorInput,null,2)+'\n').digest('hex'),additionalOpenings:[],evidence:[{name:'evidence-2.jpg',sha256:sha}],closes:[{id:'close-call',tradeId:'synthetic-call',filledMinute:'2026-09-16T14:37-04:00',quantity:2,creditPerShareCents:20,estimatedFeesCents:16,estimatedCreditCents:3984,reportedRealizedPnlCents:-4000,longPriceCents:null,shortPriceCents:10,evidenceName:'evidence-2.jpg'},{id:'close-put',tradeId:'synthetic-put',filledMinute:'2026-09-17T09:30-04:00',quantity:3,creditPerShareCents:0,estimatedFeesCents:24,estimatedCreditCents:-24,reportedRealizedPnlCents:-6000,longPriceCents:0,shortPriceCents:0,evidenceName:'evidence-2.jpg'}]};}
test('unavailable spread evidence cannot silently remove the capital caution',()=>{assert(spreadCapitalNotice({state:'BLOCKED',data:null}).includes('Capital review unavailable'));});
function clarifiedFixture(){const priorInput=closingFixture();return {version:'REPORTED_SPREAD_CLARIFICATION_INPUT_V3',id:'synthetic-manual-review',recordedAt:'2026-09-17T15:15:00.000Z',priorInput,priorInputSha256:createHash('sha256').update(JSON.stringify(priorInput,null,2)+'\n').digest('hex'),ownerExitStatement:{reportedAt:'2026-09-17T15:14:00.000Z',mechanism:'OWNER_REPORTED_MANUAL',text:'Owner reports manually selling after observing losses.'}};}
test('manual exit clarification preserves monetary results and original cases',()=>temp(root=>{const f=clarifiedFixture();saveReportedSpreadReview(root,f.priorInput.priorInput,[image]);saveReportedSpreadReview(root,f.priorInput,[image,image]);const r=saveReportedSpreadReview(root,f,[image,image]);assert.equal(r.matchedGrossPnlCents,-10000);assert.equal(r.rows[0].close.mechanism,'OWNER_REPORTED_MANUAL');assert.equal(r.realizedNetPnlCents,null);assert(r.candidateLessons.some(n=>n.code==='OWNER_REPORTED_MANUAL_EXITS'));assert(!r.candidateLessons.some(n=>n.code==='EXIT_MECHANISM_UNVERIFIED'));const view=reportedSpreadView(root,f.recordedAt);assert.equal(view.cases.length,1);assert.equal(view.historicalCases.length,2);assert(spreadReviewPanel({state:'AVAILABLE',data:view}).includes('Owner-reported manual exits'));temp(copy=>{cpSync(join(root,'data/runtime/options-reported-spreads',f.id),join(copy,'data/runtime/options-reported-spreads',f.id),{recursive:true});assert.deepEqual(readReportedSpreadReview(copy,f.id),r);});}));
test('manual statement cannot backdate, assert broker verification or nest arbitrary revisions',()=>{for(const mutate of [f=>f.ownerExitStatement.reportedAt='2026-09-17T14:00:00.000Z',f=>f.ownerExitStatement.mechanism='BROKER_VERIFIED',f=>f.priorInput.version='REPORTED_SPREAD_CLARIFICATION_INPUT_V3']){const f=clarifiedFixture();mutate(f);assert.throws(()=>assessReportedSpreads(f));}});
test('matched closing spread results preserve gross versus estimated net and cropped legs',()=>{const r=assessReportedSpreads(closingFixture());assert.equal(r.matchedGrossPnlCents,-10000);assert.equal(r.estimatedClosedRoundTripFeesCents,80);assert.equal(r.estimatedClosedNetPnlCents,-10080);assert.equal(r.realizedNetPnlCents,null);assert.equal(r.rows[0].close.longPriceCents,null);assert.equal(r.rows[0].close.croppedLegPrices,true);assert.equal(r.rows[1].close.proceedsCents,0);assert.equal(r.matchedCloseCount,2);assert.equal(r.timeline.length,4);assert(r.candidateLessons.some(n=>n.code==='DIRECTIONAL_EXITS_STAGGERED'));assert(!r.candidateLessons.some(n=>n.code==='CLOSING_EVIDENCE_MISSING'));});
test('partial evidence is retained; unknown fee cannot produce net PnL',()=>{const f=closingFixture();f.closes.pop();f.closes[0].estimatedFeesCents=null;f.closes[0].estimatedCreditCents=null;const r=assessReportedSpreads(f);assert.equal(r.reviewStatus,'PARTIAL_CLOSING_EVIDENCE');assert.equal(r.matchedGrossPnlCents,-4000);assert.equal(r.estimatedClosedNetPnlCents,null);assert.equal(r.rows[1].close,null);assert(r.candidateLessons.some(n=>n.code==='CLOSING_EVIDENCE_MISSING'));});
test('close mismatches, duplicates, partial quantities and invalid chronology fail closed',()=>{for(const mutate of [f=>f.closes[0].quantity=1,f=>f.closes[0].quantity=3,f=>f.closes.push({...f.closes[0],id:'second-close'}),f=>f.closes[0].reportedRealizedPnlCents=-3000,f=>f.closes[0].estimatedCreditCents=4000,f=>f.closes[0].filledMinute='2026-09-14T14:37-04:00',f=>f.closes[0].filledMinute='2026-09-18T14:37-04:00',f=>f.closes[0].longPriceCents=35,f=>f.closes[0].tradeId='other-trade',f=>f.priorInput.trades[0].quantity=5]){const f=closingFixture();mutate(f);assert.throws(()=>assessReportedSpreads(f));}});
test('additional short-held entry after loss is descriptive, not a behavioral diagnosis',()=>{const f=closingFixture();f.additionalOpenings.push({...f.priorInput.trades[0],id:'new-entry',filledMinute:'2026-09-16T14:44-04:00',quantity:1,debitPerShareCents:10,longPriceCents:20,shortPriceCents:10,estimatedFeesCents:8,estimatedCostCents:1008,evidenceName:'evidence-2.jpg'});f.closes.push({...f.closes[0],id:'new-close',tradeId:'new-entry',filledMinute:'2026-09-16T14:47-04:00',quantity:1,creditPerShareCents:8,estimatedFeesCents:8,estimatedCreditCents:792,reportedRealizedPnlCents:-200});const r=assessReportedSpreads(f);assert.equal(r.rows[2].close.holdMinutes,3);const note=r.candidateLessons.find(n=>n.code==='NEW_ENTRY_SOON_AFTER_LOSS');assert(note.nextCheck.includes('7 minutes'));assert.equal(note.causalStatus,'NOT_ESTABLISHED');assert.equal(note.approvedRule,false);});
test('V2 supersedes display without changing V1, and recovers from its own copied sources',()=>temp(root=>{const f=closingFixture(),old=saveReportedSpreadReview(root,f.priorInput,[image]),oldBytes=readFileSync(join(root,'data/runtime/options-reported-spreads',f.priorInput.id,'report.json'));const r=saveReportedSpreadReview(root,f,[image,image]),view=reportedSpreadView(root,f.recordedAt);assert.equal(view.cases.length,1);assert.equal(view.historicalCases.length,1);assert.deepEqual(readReportedSpreadReview(root,f.priorInput.id),old);assert(oldBytes.equals(readFileSync(join(root,'data/runtime/options-reported-spreads',f.priorInput.id,'report.json'))));temp(copy=>{cpSync(join(root,'data/runtime/options-reported-spreads',f.id),join(copy,'data/runtime/options-reported-spreads',f.id),{recursive:true});assert.deepEqual(readReportedSpreadReview(copy,f.id),r);});}));
test('closing UI labels estimates and does not request nonexistent closing evidence',()=>{const r=assessReportedSpreads(closingFixture()),html=spreadReviewPanel({state:'AVAILABLE',data:{cases:[r]}});assert(html.includes('-$100.80'));assert(html.includes('actual fees unverified'));assert(!html.includes('Unknown — closing executions required'));assert(html.includes('2 of 2 full spread closes matched'));assert(html.includes('Reported opening and closing sequence'));});
test('capital caution keeps buying power separate from equity and leaves settings alone',()=>{const r=assessReportedSpreads(fixture()),html=spreadCapitalNotice({data:{cases:[r]}});assert(html.includes('Buying Power'));assert(html.includes('does not establish total equity or settled cash'));assert.equal(spreadCapitalNotice({data:{cases:[]}}),'');});
test('vertical openings reconcile both legs and do not create realized results',()=>{const r=assessReportedSpreads(fixture());assert.equal(r.totalPremiumCents,14000);assert.equal(r.estimatedOutlayCents,14040);assert.equal(r.rows[0].terminalBreakevenCents,41040);assert.equal(r.rows[1].terminalBreakevenCents,38980);assert.equal(r.rows[0].terminalMaxProfitBeforeFeesCents,92000);assert.equal(r.rows[1].terminalMaxLossBeforeFeesCents,6000);assert.equal(r.actualFeesCents,null);assert.equal(r.realizedNetPnlCents,null);assert.equal(r.legContracts,10);assert.equal(r.rows[0].calendarDteAtOpening,10);assert.equal(r.rows[1].calendarDteAtOpening,3);});
test('opposite expiries retain two separate conditional endpoints and no hedge credit',()=>{const r=assessReportedSpreads(fixture());assert.equal(r.pairs.length,1);assert.equal(r.pairs[0].differentExpiries,true);assert.equal(r.pairs[0].zeroIntrinsicConditions.call.expiry,'2026-09-25');assert.equal(r.pairs[0].zeroIntrinsicConditions.put.expiry,'2026-09-18');assert.equal(r.pairs[0].bothWorthlessPremiumLossCents,14000);assert(r.candidateLessons.every(x=>!x.approvedRule&&!x.approvedKnowledge&&x.causalStatus==='NOT_ESTABLISHED'));});
test('estimated charges and reported closing are not actual fees or closing fills',()=>{const f=fixture();f.ownerReportsClosed=true;f.trades[1].estimatedFeesCents=null;f.trades[1].estimatedCostCents=null;const r=assessReportedSpreads(f);assert.equal(r.estimatedOutlayCents,null);assert.equal(r.rows[0].currentPositionStatus,'CLOSE_REPORTED_AWAITING_EXECUTIONS');assert.equal(r.rows[0].realizedNetPnlCents,null);assert.equal(r.reportedCapital.basis,'BUYING_POWER');assert.equal(r.reviewStatus,'INCOMPLETE_OPENING_EVIDENCE_ONLY');});
test('reject inconsistent net debit, cost, multiplier, quantities and strike order',()=>{for(const change of [{debitPerShareCents:41},{estimatedCostCents:8000},{multiplier:10},{quantity:1.5},{longStrikeCents:42000},{shortQuantity:1}]){const f=fixture();Object.assign(f.trades[0],change);assert.throws(()=>assessReportedSpreads(f));}});
test('reject duplicate identity, missing source, future execution and invalid expiry',()=>{for(const mutate of [f=>f.trades.push({...f.trades[0],id:'different-id'}),f=>f.trades[0].evidenceName='missing.jpg',f=>f.trades[0].filledMinute='2026-09-18T10:00-04:00',f=>f.trades[0].expiry='2026-09-14',f=>f.trades[0].expiry='2026-02-30',f=>f.trades[0].filledMinute='2026-09-15T15:99-04:00']){const f=fixture();mutate(f);assert.throws(()=>assessReportedSpreads(f));}});
test('source manifest and report independently recover, and saved IDs cannot overwrite',()=>temp(root=>{const f=fixture(),r=saveReportedSpreadReview(root,f,[image]);assert.deepEqual(readReportedSpreadReview(root,f.id),r);assert.equal(reportedSpreadView(root,f.recordedAt).cases.length,1);assert.throws(()=>saveReportedSpreadReview(root,f,[image]),/EEXIST/);temp(copy=>{cpSync(join(root,'data'),join(copy,'data'),{recursive:true});assert.deepEqual(readReportedSpreadReview(copy,f.id),r);});}));
test('tampered screenshot and report fail recovery',()=>{for(const name of ['evidence-1.jpg','report.json'])temp(root=>{const f=fixture();saveReportedSpreadReview(root,f,[image]);const path=join(root,'data/runtime/options-reported-spreads',f.id,name);writeFileSync(path,Buffer.concat([readFileSync(path),Buffer.from('x')]));assert.throws(()=>readReportedSpreadReview(root,f.id),/FILE_HASH/);});});
test('missing store is empty; future catalog receipt and malformed input fail closed',()=>temp(root=>{assert.equal(reportedSpreadView(root,'2026-09-17T14:00:00.000Z').cases.length,0);saveReportedSpreadReview(root,fixture(),[image]);assert.throws(()=>reportedSpreadView(root,'2026-09-17T13:59:00.000Z'),/FUTURE_RECEIPT/);const f=fixture();f.realizedNetPnlCents=-100;assert.throws(()=>assessReportedSpreads(f),/SHAPE/);}));
test('UI and notebook show supplied spread evidence with escaped retrospective prose',()=>{const f=fixture();f.originalPlanText='<img src=x onerror=alert(1)>';const r=assessReportedSpreads(f),component={state:'AVAILABLE',data:{cases:[r]}},html=spreadReviewPanel(component);assert(!html.includes('<img'));assert(html.includes('&lt;img'));assert(html.includes('Unknown — closing executions required'));assert(html.includes('not included in the single-leg ledger'));assert(html.includes('not an early-exit target'));const lessons=collectLessons({manual:{data:null},outcomes:{data:null},activity:{data:null},reportedSpreads:component});assert.equal(lessons.length,r.candidateLessons.length);assert(lessons.some(x=>x.code==='OPPOSITE_DIRECTIONS_DIFFERENT_EXPIRIES'));});
