import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,realpathSync,readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {join,relative,isAbsolute} from 'node:path';
import {tmpdir} from 'node:os';
import {seedExpectation,expectationRows,expectationLater as at,expectationRelease,expectationPlan} from './lib/options-market-expectation-fixtures.mjs';
import {expectationRecords,verifyExpectation,previewExpectation,expectationForPlan,verifyNewPlanExpectation} from './lib/options-market-expectation-io.mjs';
import {expectationDifference,validateExpectationRequest,assessExpectationSnapshot} from '../src/engines/options-drivers/OptionsMarketExpectation.ts';
import {paperFingerprint as fp} from '../src/engines/options-paper/OptionsPaperTradingEngine.ts';
import {assessEventEntry} from '../src/engines/options-daily-guidance/OptionsEventEntry.ts';
import {eventEntryContexts} from './lib/options-candidate-checks-io.mjs';
import {createWorkbenchData} from './lib/options-workbench-data.mjs';
import {startOptionsWorkbench} from './options-workbench.mjs';
import {expectationSummary,expectationEditor} from '../apps/options-workbench/market-expectations.js';
import {macroContextView} from './lib/options-macro-context-io.mjs';

let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
async function temp(fn){const root=mkdtempSync(join(tmpdir(),'alpha-expectation-test-'));try{await fn(root);}finally{const full=realpathSync(root),rel=relative(realpathSync(tmpdir()),full);if(isAbsolute(rel)||rel.startsWith('..')||!rel.startsWith('alpha-expectation-test-'))throw Error('UNSAFE_TEST_CLEANUP');rmSync(full,{recursive:true,force:true});}}
const reference=r=>({path:r.path,fingerprint:r.fingerprint,frozenAt:r.savedAt});
const context=(s,extra={})=>({at:at(100),eventKey:s.request.eventKey,releaseAt:s.request.releaseAt,thesisFingerprint:s.thesisFingerprint,planFrozenAt:at(80),openedAt:null,...extra});
await test('source survey consensus saves with exact clocks, references and decimal difference',()=>temp(async root=>{const f=await seedExpectation(root),r=f.save(),v=verifyExpectation(root,r.path);assert.equal(v.savedAt,at(10));assert.equal(v.payload.request.rows[0].forecasts[0].type,'CONSENSUS');assert.equal(expectationDifference(v.payload.request.rows[0]).numericDifference,'-20');assert.equal(v.payload.ownerConfirmedAt,null);assert.equal(r.payload.request.comparisonFingerprint,f.comparison.fingerprint);assert.equal(macroContextView(root,at(20)).comparisons.length,0);}));
for(const type of ['SINGLE_FORECAST','MODEL_ESTIMATE','MARKET_IMPLIED','OWNER_EXPECTATION'])await test(type+' cannot become consensus or generate a numeric gap',()=>temp(async root=>{const f=await seedExpectation(root),r=structuredClone(f.request);r.rows[0].forecasts[0].type=type;r.rows[0].forecasts[0].consensusBasis='NOT_CONSENSUS';r.rows[0].selectedConsensusId='';const saved=f.save(r);assert.equal(expectationDifference(saved.payload.request.rows[0]).numericDifference,null);r.rows[0].selectedConsensusId='survey-one';assert.throws(()=>validateExpectationRequest(r,at(10)),/SELECTED_CONSENSUS/);}));
for(const [key,value] of [['unit','JOBS'],['period','2026-07'],['adjustment','UNKNOWN'],['releaseVersion','REVISED'],['eventKey','other'],['valueMeaning','LEVEL'],['metric','PRIVATE_PAYROLLS']])await test(key+' mismatch preserves evidence without calculating a gap',()=>{const row=expectationRows()[0];row.forecasts[0][key]=value;const r=expectationDifference(row);assert.equal(r.numericDifference,null);assert(r.issues.some(x=>x.endsWith(value==='UNKNOWN'?'_UNKNOWN':'_MISMATCH')));});
await test('multiple forecasts remain distinct; explicit source choice never averages',()=>{const row=expectationRows()[0];row.forecasts.push({...row.forecasts[0],id:'survey-two',value:'200'});row.selectedConsensusId='';assert.equal(expectationDifference(row).numericDifference,null);row.selectedConsensusId='survey-two';const r=expectationDifference(row);assert.equal(r.numericDifference,'-120');assert.deepEqual(r.forecasts.map(x=>x.value),['100','200']);});
await test('qualitative Owner judgment retains attribution without a fabricated numeric difference',()=>temp(async root=>{const f=await seedExpectation(root),r=structuredClone(f.request);r.rows[0].alpha.value=null;r.rows[0].alpha.qualitative='WEAKER_THAN_CONSENSUS';const saved=f.save(r);const d=expectationDifference(saved.payload.request.rows[0]);assert.equal(d.numericDifference,null);assert.equal(d.qualitative,'WEAKER_THAN_CONSENSUS');assert.equal(d.alpha.attribution,'OWNER');assert.equal(saved.payload.ownerConfirmedAt,null);}));
await test('append revisions are immutable, idempotent and recover after restart',()=>temp(async root=>{const f=await seedExpectation(root),one=f.save(),bytes=readFileSync(join(root,one.path));const two=f.save({...f.request,id:'expectation-revision',supersedes:one.path},at(20));assert.equal(two.payload.request.supersedes,one.path);assert(readFileSync(join(root,one.path)).equals(bytes));assert(f.save(f.request,at(30)).alreadyRecorded);assert.throws(()=>f.save({...f.request,note:'overwrite'},at(30)),/RETRY_CHANGED/);const state=await createWorkbenchData({workspaceRoot:root,ledgerId:f.ledgerId,now:()=>at(40)}).state();assert.equal(state.marketExpectations.data.records.length,2);assert.equal(state.manual.data.trades.length,0);assert.equal(state.marketExpectations.data.records[0].fingerprint,one.fingerprint);}));
await test('post-entry, same-clock freeze, late-release and changed-thesis snapshots fail closed',()=>temp(async root=>{const f=await seedExpectation(root),r=f.save({...f.request,stage:'FINAL_PRE_ENTRY',ownerConfirmed:true}),s=r.payload;for(const extra of [{openedAt:at(5)},{planFrozenAt:at(10)},{releaseAt:at(9)},{at:at(9)}])assert(assessExpectationSnapshot(s,context(s,extra)).blockers.includes('EXPECTATION_NOT_FROZEN_BEFORE_ENTRY'));assert(assessExpectationSnapshot(s,context(s,{thesisFingerprint:fp('changed')})).blockers.includes('EXPECTATION_THESIS_CHANGED'));assert.throws(()=>f.save({...f.request,id:'late-final',stage:'FINAL_PRE_ENTRY',ownerConfirmed:true},expectationRelease),/TIMING/);}));
await test('future receipt and publication clocks and fake consensus classification are rejected',()=>temp(async root=>{const f=await seedExpectation(root);for(const patch of [{receivedAt:at(20)},{publishedAt:at(20)},{consensusBasis:'NOT_CONSENSUS'}]){const r=structuredClone(f.request);Object.assign(r.rows[0].forecasts[0],patch);assert.throws(()=>f.save(r));}}));
await test('research remains saveable but new formal pre-event freeze requires a final confirmed reference',()=>temp(async root=>{const f=await seedExpectation(root),research=f.save(),p=expectationPlan();p.invalidation.expectationSnapshot=reference(research);const command={type:'REGISTER_TRADE',requestId:'freeze-new',tradeId:'synthetic-event-plan',contract:{symbol:'GLD',expiry:'2026-09-25',optionType:'CALL',strikeUsd:'400',multiplier:100},plan:p,activityReference:null};f.setClock(at(80));assert.throws(()=>f.service.preview(command),/FINAL_EXPECTATION/);assert.throws(()=>f.save({...f.request,id:'unconfirmed-final',stage:'FINAL_PRE_ENTRY'}),/CONFIRMATION/);const final=f.save({...f.request,id:'final-before-entry',stage:'FINAL_PRE_ENTRY',ownerConfirmed:true,supersedes:research.path},at(40));p.invalidation.expectationSnapshot=reference(final);const preview=f.service.preview(command);f.service.save({command,expectedHeadSha256:preview.headSha256});const state=await createWorkbenchData({workspaceRoot:root,ledgerId:f.ledgerId,now:()=>at(90)}).state();assert.equal(state.manual.data.trades.length,1);assert.equal(state.manual.data.trades[0].openContracts,0);assert.equal(state.manual.data.trades[0].plan.invalidation.expectationSnapshot.fingerprint,final.fingerprint);const ctx=eventEntryContexts(state)[0];assert.equal(ctx.expectation.status,'FINAL_REFERENCE_READY');assert(!ctx.expectation.blockers.length);}));
await test('missing, changed fingerprint and changed event time cannot qualify',()=>temp(async root=>{const f=await seedExpectation(root),r=f.save(),p=expectationPlan();assert(expectationForPlan(p,[r],at(20)).blockers.includes('FINAL_EXPECTATION_SNAPSHOT_MISSING'));p.invalidation.expectationSnapshot={...reference(r),fingerprint:fp('wrong')};assert.deepEqual(expectationForPlan(p,[r],at(20)).blockers,['EXPECTATION_REFERENCE_UNAVAILABLE']);p.invalidation.expectationSnapshot=reference(r);p.invalidation.conditions[0].releaseAt=at(200);assert(expectationForPlan(p,[r],at(20)).blockers.includes('EXPECTATION_EVENT_TIME_MISMATCH'));}));
await test('POST_EVENT and old frozen plans keep their original rules and fingerprints',()=>temp(async root=>{const f=await seedExpectation(root),plan=expectationPlan(),ctx={key:'frozen:test',version:fp(plan),kind:'FROZEN',symbol:'GLD',plan,contract:null,registeredAt:at(80),openedAt:null,calendar:[]};delete plan.invalidation.eventEntry;const original=assessEventEntry(ctx,at(90),false);assert.equal(Object.hasOwn(original,'expectation'),false);plan.invalidation.eventEntry={phase:'POST_EVENT',conditionId:'owner',calendarVerifiedAt:'',calendarSource:'',expectationStatus:'',expectationBasis:'',differenceBasis:'',supportingScenario:'',neutralScenario:'',reverseScenario:'',counterexample:'',reviewer:'',gapRiskAccepted:false,closedMarketRiskAccepted:false};const post=assessEventEntry({...ctx,expectation:{blockers:['CONSENSUS_EXPECTATION_UNKNOWN'],rows:[],status:'NOT_READY'}},at(90),false);assert.deepEqual(post.blockers,[]);verifyNewPlanExpectation(root,f.ledgerId,{type:'REGISTER_TRADE',plan},at(90));}));
await test('tampered saved snapshot is unavailable and does not fall back',()=>temp(async root=>{const f=await seedExpectation(root),r=f.save(),path=join(root,r.path),raw=JSON.parse(readFileSync(path));raw.payload.request.rows[0].forecasts[0].value='999';writeFileSync(path,JSON.stringify(raw));assert.throws(()=>verifyExpectation(root,r.path),/INTEGRITY/);const view=expectationRecords(root,f.ledgerId,at(20));assert.equal(view.records.length,0);assert.equal(view.errors.length,1);}));
await test('protected API saves and reopens the same snapshot; page exposes unknown and model separately',()=>temp(async root=>{const f=await seedExpectation(root),request=structuredClone(f.request);request.rows[0].selectedConsensusId='';request.rows[0].forecasts[0].type='MODEL_ESTIMATE';request.rows[0].forecasts[0].consensusBasis='NOT_CONSENSUS';const app=await startOptionsWorkbench({workspaceRoot:root,ledgerId:f.ledgerId,port:0,now:()=>at(30)});try{const state=await(await fetch(app.url+'/api/state')).json(),headers={Origin:app.url,'Content-Type':'application/json','X-Alpha-Session':state.session};const post=body=>fetch(app.url+'/api/source-comparison',{method:'POST',headers,body:JSON.stringify(body)});const b={action:'PREVIEW_EXPECTATION',request,previewFingerprint:null},preview=await(await post(b)).json();assert(preview.assessment.blockers.includes('CONSENSUS_EXPECTATION_UNKNOWN'));const savedResponse=await post({...b,action:'SAVE_EXPECTATION',previewFingerprint:preview.previewFingerprint});assert.equal(savedResponse.status,200);const saved=await savedResponse.json(),reloaded=await(await fetch(app.url+'/api/state')).json();assert.equal(reloaded.marketExpectations.data.records[0].fingerprint,saved.fingerprint);const html=expectationSummary(preview.assessment,'<script>bad</script>');assert(html.includes('Consensus UNKNOWN'));assert(html.includes('MODEL_ESTIMATE'));assert(!html.includes('<script>'));assert(expectationEditor(reloaded,{},'synthetic-event-plan').includes(saved.id));assert.equal((await fetch(app.url+'/market-expectations.js')).status,200);assert.equal(reloaded.backgroundContextRefreshEnabled,false);assert.equal(reloaded.manual.data.trades.length,0);assert.equal((await fetch(app.url+'/api/source-comparison',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)})).status,403);}finally{await app.close();}assert(!readdirSync(join(root,'data/runtime')).some(x=>x.includes('capture')||x.includes('automation')));}));
await test('snapshot form keeps native form identity and distinguishes unsaved preview clocks',()=>{const d={id:'snapshot-test',stage:'RESEARCH',planKey:'draft:test',planVersion:'v1',rows:[],note:'',ownerConfirmed:false};const html=expectationEditor({sourceComparisons:{data:{plans:[],records:[]}}},{expectationDraft:d},'test');assert(html.includes('name="snapshotId"'));assert(!html.includes('name="id"'));assert(html.includes('id="expectation-form"'));const preview=expectationSummary({stage:'RESEARCH',status:'NOT_READY',frozenAt:at(10),rows:[]},'',true);assert(preview.includes('Unsaved preview evaluated'));assert(!preview.includes(' · Frozen '));});
console.log(passed+'/'+passed+' tests passed.');
