import assert from "node:assert/strict";
import {mkdtempSync,rmSync,realpathSync,readFileSync} from "node:fs";
import {join,relative,isAbsolute} from "node:path";
import {tmpdir} from "node:os";
import {contextRefreshSlots,runPublicContextOnce,startPublicContextService} from "./options-context-service.mjs";
let passed=0;async function test(name,fn){await fn();passed++;console.log("PASS "+name);}
async function temp(fn){const root=mkdtempSync(join(tmpdir(),"alpha-context-service-test-"));try{await fn(root);}finally{const full=realpathSync(root),rel=relative(realpathSync(tmpdir()),full);if(isAbsolute(rel)||rel.startsWith("..")||!rel.startsWith("alpha-context-service-test-"))throw Error("UNSAFE_TEST_CLEANUP");rmSync(full,{recursive:true,force:true});}}
await test("hourly public context runs overnight and on weekends",()=>{assert.deepEqual(contextRefreshSlots("2026-09-12T04:20:00.000Z")[0].sources,["headlines","btc"]);});
await test("09:00 New York includes the remaining original daily sources",()=>{assert.deepEqual(contextRefreshSlots("2026-09-08T13:00:00.000Z")[1].sources,["treasury","bls","fomc"]);});
await test("daily sources follow New York across DST",()=>{assert.equal(contextRefreshSlots("2026-11-09T13:00:00.000Z").length,1);assert.equal(contextRefreshSlots("2026-11-09T14:00:00.000Z").length,2);});
await test("hourly claims survive process-independent repeated calls",()=>temp(async root=>{const names=[],options={workspaceRoot:root,now:()=>"2026-09-08T05:20:00.000Z",issue:false,execute:async(name,args)=>{names.push(name);assert.equal(args[0],"node_modules/tsx/dist/cli.mjs");assert.equal(args[2],"--refresh");return {status:"OK"};}};const a=await runPublicContextOnce(options),b=await runPublicContextOnce(options);assert.deepEqual(names,["headlines","btc"]);assert.equal(a.results[0].sources.length,2);assert.equal(b.results[0].status,"ALREADY_ATTEMPTED");}));
await test("source failures remain explicit and do not prevent other sources",()=>temp(async root=>{const r=await runPublicContextOnce({workspaceRoot:root,now:()=>"2026-09-08T13:20:00.000Z",issue:false,execute:async name=>{if(name==="headlines")throw Error("SECRET_ERROR_DETAIL");return {status:"OK"};}});assert.equal(r.results[0].sources[0].status,"FAILED");assert.equal(r.results[0].sources[1].status,"OK");assert.equal(r.results[1].sources.length,3);assert(!JSON.stringify(r).includes("SECRET"));}));
await test("the next hour may collect again without rewriting old receipts",()=>temp(async root=>{let at="2026-09-08T05:20:00.000Z",calls=0;const o={workspaceRoot:root,now:()=>at,issue:false,execute:async()=>{calls++;return {status:"OK"};}};await runPublicContextOnce(o);const path=join(root,"data/runtime/options-context-service/2026-09-08/hourly-2026-09-08T05.receipt.json"),before=readFileSync(path);at="2026-09-08T06:20:00.000Z";await runPublicContextOnce(o);assert.equal(calls,4);assert(readFileSync(path).equals(before));}));
await test("two workers cannot duplicate one hourly refresh",()=>temp(async root=>{let calls=0;const options={workspaceRoot:root,now:()=>"2026-09-08T05:20:00.000Z",issue:false,execute:async()=>{calls++;await new Promise(r=>setTimeout(r,5));return {status:"OK"};}};await Promise.all([runPublicContextOnce(options),runPublicContextOnce(options)]);assert.equal(calls,2);}));
await test("an active in-process tick never overlaps itself",()=>temp(async root=>{let finish,calls=0;const wait=new Promise(r=>finish=r),service=startPublicContextService({workspaceRoot:root,now:()=>"2026-09-08T05:20:00.000Z",issue:false,execute:async()=>{calls++;await wait;return {status:"OK"};}});await service.tick();assert.equal(calls,1);service.stop();finish();await new Promise(r=>setTimeout(r,20));assert.equal(calls,2);}));
console.log(passed+"/"+passed+" tests passed.");
