import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtempSync,rmSync,readFileSync,writeFileSync,cpSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {assessReportedSpreads,saveReportedSpreadReview,readReportedSpreadReview,reportedSpreadView} from './lib/options-spread-review.mjs';
import {spreadReviewPanel,spreadCapitalNotice} from '../apps/options-workbench/spread-review.js';
import {collectLessons} from '../apps/options-workbench/model.js';
const image=Buffer.from([255,216,255,217]),sha=createHash('sha256').update(image).digest('hex');
function fixture(){return {version:'REPORTED_SPREAD_INPUT_V1',id:'synthetic-spread-review',recordedAt:'2026-09-17T14:00:00.000Z',origin:'OWNER_SUPPLIED_SCREENSHOTS',yearBasis:'CONVERSATION_CONTEXT',reportedCapital:{amountCents:25000,basis:'BUYING_POWER',reportedOn:'2026-09-17'},originalPlanText:null,ownerReportsClosed:false,evidence:[{name:'evidence-1.jpg',sha256:sha}],trades:[{id:'synthetic-call',symbol:'GLD',optionType:'CALL',expiry:'2026-09-25',filledMinute:'2026-09-15T15:00-04:00',quantity:2,multiplier:100,debitPerShareCents:40,estimatedFeesCents:16,estimatedCostCents:8016,longStrikeCents:41000,shortStrikeCents:41500,longPriceCents:70,shortPriceCents:30,evidenceName:'evidence-1.jpg'},{id:'synthetic-put',symbol:'GLD',optionType:'PUT',expiry:'2026-09-18',filledMinute:'2026-09-15T15:01-04:00',quantity:3,multiplier:100,debitPerShareCents:20,estimatedFeesCents:24,estimatedCostCents:6024,longStrikeCents:39000,shortStrikeCents:38500,longPriceCents:50,shortPriceCents:30,evidenceName:'evidence-1.jpg'}]};}
function temp(fn){const root=mkdtempSync(join(tmpdir(),'alpha-spread-test-'));try{return fn(root);}finally{assert(resolve(root).startsWith(resolve(tmpdir())+'\\')||resolve(root).startsWith(resolve(tmpdir())+'/'));rmSync(root,{recursive:true,force:true});}}
test('capital caution keeps buying power separate from equity and leaves settings alone',()=>{const r=assessReportedSpreads(fixture()),html=spreadCapitalNotice({data:{cases:[r]}});assert(html.includes('Buying Power'));assert(html.includes('does not establish total equity or settled cash'));assert.equal(spreadCapitalNotice({data:{cases:[]}}),'');});
test('vertical openings reconcile both legs and do not create realized results',()=>{const r=assessReportedSpreads(fixture());assert.equal(r.totalPremiumCents,14000);assert.equal(r.estimatedOutlayCents,14040);assert.equal(r.rows[0].terminalBreakevenCents,41040);assert.equal(r.rows[1].terminalBreakevenCents,38980);assert.equal(r.rows[0].terminalMaxProfitBeforeFeesCents,92000);assert.equal(r.rows[1].terminalMaxLossBeforeFeesCents,6000);assert.equal(r.actualFeesCents,null);assert.equal(r.realizedNetPnlCents,null);assert.equal(r.legContracts,10);assert.equal(r.rows[0].calendarDteAtOpening,10);assert.equal(r.rows[1].calendarDteAtOpening,3);});
test('opposite expiries retain two separate conditional endpoints and no hedge credit',()=>{const r=assessReportedSpreads(fixture());assert.equal(r.pairs.length,1);assert.equal(r.pairs[0].differentExpiries,true);assert.equal(r.pairs[0].zeroIntrinsicConditions.call.expiry,'2026-09-25');assert.equal(r.pairs[0].zeroIntrinsicConditions.put.expiry,'2026-09-18');assert.equal(r.pairs[0].bothWorthlessPremiumLossCents,14000);assert(r.candidateLessons.every(x=>!x.approvedRule&&!x.approvedKnowledge&&x.causalStatus==='NOT_ESTABLISHED'));});
test('estimated charges and reported closing are not actual fees or closing fills',()=>{const f=fixture();f.ownerReportsClosed=true;f.trades[1].estimatedFeesCents=null;f.trades[1].estimatedCostCents=null;const r=assessReportedSpreads(f);assert.equal(r.estimatedOutlayCents,null);assert.equal(r.rows[0].currentPositionStatus,'CLOSE_REPORTED_AWAITING_EXECUTIONS');assert.equal(r.rows[0].realizedNetPnlCents,null);assert.equal(r.reportedCapital.basis,'BUYING_POWER');assert.equal(r.reviewStatus,'INCOMPLETE_OPENING_EVIDENCE_ONLY');});
test('reject inconsistent net debit, cost, multiplier, quantities and strike order',()=>{for(const change of [{debitPerShareCents:41},{estimatedCostCents:8000},{multiplier:10},{quantity:1.5},{longStrikeCents:42000},{shortQuantity:1}]){const f=fixture();Object.assign(f.trades[0],change);assert.throws(()=>assessReportedSpreads(f));}});
test('reject duplicate identity, missing source, future execution and invalid expiry',()=>{for(const mutate of [f=>f.trades.push({...f.trades[0],id:'different-id'}),f=>f.trades[0].evidenceName='missing.jpg',f=>f.trades[0].filledMinute='2026-09-18T10:00-04:00',f=>f.trades[0].expiry='2026-09-14',f=>f.trades[0].expiry='2026-02-30',f=>f.trades[0].filledMinute='2026-09-15T15:99-04:00']){const f=fixture();mutate(f);assert.throws(()=>assessReportedSpreads(f));}});
test('source manifest and report independently recover, and saved IDs cannot overwrite',()=>temp(root=>{const f=fixture(),r=saveReportedSpreadReview(root,f,[image]);assert.deepEqual(readReportedSpreadReview(root,f.id),r);assert.equal(reportedSpreadView(root,f.recordedAt).cases.length,1);assert.throws(()=>saveReportedSpreadReview(root,f,[image]),/EEXIST/);temp(copy=>{cpSync(join(root,'data'),join(copy,'data'),{recursive:true});assert.deepEqual(readReportedSpreadReview(copy,f.id),r);});}));
test('tampered screenshot and report fail recovery',()=>{for(const name of ['evidence-1.jpg','report.json'])temp(root=>{const f=fixture();saveReportedSpreadReview(root,f,[image]);const path=join(root,'data/runtime/options-reported-spreads',f.id,name);writeFileSync(path,Buffer.concat([readFileSync(path),Buffer.from('x')]));assert.throws(()=>readReportedSpreadReview(root,f.id),/FILE_HASH/);});});
test('missing store is empty; future catalog receipt and malformed input fail closed',()=>temp(root=>{assert.equal(reportedSpreadView(root,'2026-09-17T14:00:00.000Z').cases.length,0);saveReportedSpreadReview(root,fixture(),[image]);assert.throws(()=>reportedSpreadView(root,'2026-09-17T13:59:00.000Z'),/FUTURE_RECEIPT/);const f=fixture();f.realizedNetPnlCents=-100;assert.throws(()=>assessReportedSpreads(f),/SHAPE/);}));
test('UI and notebook show supplied spread evidence with escaped retrospective prose',()=>{const f=fixture();f.originalPlanText='<img src=x onerror=alert(1)>';const r=assessReportedSpreads(f),component={state:'AVAILABLE',data:{cases:[r]}},html=spreadReviewPanel(component);assert(!html.includes('<img'));assert(html.includes('&lt;img'));assert(html.includes('Unknown — closing executions required'));assert(html.includes('not included in the single-leg ledger'));assert(html.includes('not an early-exit target'));const lessons=collectLessons({manual:{data:null},outcomes:{data:null},activity:{data:null},reportedSpreads:component});assert.equal(lessons.length,r.candidateLessons.length);assert(lessons.some(x=>x.code==='OPPOSITE_DIRECTIONS_DIFFERENT_EXPIRIES'));});
