import assert from 'node:assert/strict';
import {existsSync,mkdirSync,mkdtempSync,readFileSync,realpathSync,renameSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {isAbsolute,join,relative,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {runOptionsReviewDeskCommand as desk} from './options-review-desk.mjs';
import {runOptionsManualLedgerCommand as manual} from './options-manual-ledger.mjs';
import {runOptionsChainReviewCommand as chain} from './options-chain-review.mjs';
import {runOptionsActivityStudyCommand as activity} from './options-activity-study.mjs';
import {activityStudyFixture} from '../src/engines/options-robinhood-data/OptionsActivityStudyFixtures.ts';
import {manualRegistration} from '../src/engines/options-manual-ledger/OptionsManualLedgerFixtures.ts';
const at='2026-09-08T02:00:00.000Z',base='data/runtime/options-review-desk/test-desk',opts=root=>({workspaceRoot:root,now:()=>at});
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
function temp(fn){const root=mkdtempSync(join(tmpdir(),'alpha-desk-test-'));try{return fn(root);}finally{const rel=relative(realpathSync(tmpdir()),realpathSync(root));if(isAbsolute(rel)||rel.startsWith('..')||!rel.startsWith('alpha-desk-test-'))throw Error('UNSAFE_CLEANUP');rmSync(root,{recursive:true});}}
function seed(root,linked=false,demo=false){
  mkdirSync(join(root,'docs'));writeFileSync(join(root,'docs/OPTIONS_MANUAL_LEDGER_GUIDE.md'),readFileSync(resolve(import.meta.dirname,'../docs/OPTIONS_MANUAL_LEDGER_GUIDE.md')));
  manual([demo?'--demo':'--create','test-ledger'],opts(root));
  if(!linked)return ['--build','test-ledger','test-desk'];
  writeFileSync(join(root,'source.json'),JSON.stringify(activityStudyFixture()));chain(['--build','source.json','baseline'],{workspaceRoot:root,now:()=> '2026-09-07T20:22:00.000Z'});
  activity(['--register','baseline','test-study'],{workspaceRoot:root,now:()=> '2026-09-08T01:00:00.000Z'});
  const report=activity(['--update','test-study'],opts(root));
  return ['--build','test-ledger','test-desk','--chain','baseline','--activity','test-study',report.reportId];
}
test('empty owner desk does not invent trades and is independently recoverable',()=>temp(root=>{const args=seed(root),r=desk(args,opts(root));assert.equal(r.manualCounts.trades,0);const html=readFileSync(join(root,r.path),'utf8');assert(html.includes('No owner-reported trades'));assert(html.includes('OWNER_REPORTED_UNVERIFIED'));const child=spawnSync(process.execPath,['--import','tsx','--input-type=module','-e',`import {runOptionsReviewDeskCommand as run} from ${JSON.stringify(new URL('./options-review-desk.mjs',import.meta.url).href)};console.log(JSON.stringify(run(['--verify','test-desk'],{workspaceRoot:process.argv[1],now:()=> '${at}'})));`,root],{cwd:resolve(import.meta.dirname,'..'),encoding:'utf8'});assert.equal(child.status,0,child.stderr);assert.equal(JSON.parse(child.stdout).reportFingerprint,r.reportFingerprint);}));
test('linked original chain/activity readers recover copied dependencies',()=>temp(root=>{const args=seed(root,true),r=desk(args,opts(root));assert.equal(r.activityCounts.candidates,4);for(const dir of ['options-chain-survey','options-activity-studies','options-manual-ledger'])renameSync(join(root,'data/runtime',dir),join(root,'data/runtime',dir+'-unavailable'));assert.equal(desk(['--verify','test-desk'],opts(root)).reportFingerprint,r.reportFingerprint);}));
test('fixture fills retain fixture label and corrected PnL in desk',()=>temp(root=>{const args=seed(root,false,true),r=desk(args,opts(root)),report=JSON.parse(readFileSync(join(root,base,'report.json'),'utf8'));assert.equal(report.manual.trades[0].closedTradeNetPnlUsd,'4.960000');assert.equal(r.manualCounts.closedTrades,1);assert(readFileSync(join(root,r.path),'utf8').includes('SYNTHETIC_FIXTURE'));}));
test('existing desk is exclusive and never overwritten',()=>temp(root=>{const args=seed(root);desk(args,opts(root));const before=readFileSync(join(root,base,'index.html'));assert.throws(()=>desk(args,opts(root)),/EEXIST/);assert.deepEqual(readFileSync(join(root,base,'index.html')),before);}));
for(const file of ['index.html','report.json','guide.md','manifest.json','dependencies/data/runtime/options-manual-ledger/test-ledger/manifest.json'])test('tampered '+file+' fails desk recovery',()=>temp(root=>{desk(seed(root),opts(root));const p=join(root,base,file);writeFileSync(p,readFileSync(p,'utf8')+' ');assert.throws(()=>desk(['--verify','test-desk'],opts(root)));}));
test('linked source corruption blocks build rather than dropping the source',()=>temp(root=>{const args=seed(root,true);writeFileSync(join(root,'data/runtime/options-chain-survey/baseline/report.json'),'{}');assert.throws(()=>desk(args,opts(root)));assert(!existsSync(join(root,base)));}));
test('owner input text is escaped with no executable HTML or order form',()=>temp(root=>{seed(root);const c=manualRegistration('hostile-text');c.plan.thesis='<script>alert(1)</script><img src=x onerror=alert(1)>';writeFileSync(join(root,'command.json'),JSON.stringify(c));manual(['--append','test-ledger','command.json'],opts(root));const r=desk(['--build','test-ledger','test-desk'],opts(root)),html=readFileSync(join(root,r.path),'utf8');assert(!/<script|<img|<form/.test(html));assert(html.includes('&lt;script&gt;'));assert(html.includes("default-src 'none'"));}));
test('traversal and duplicate optional arguments fail',()=>temp(root=>{seed(root);for(const args of [['--build','test-ledger','../escape'],['--verify','../escape'],['--build','test-ledger','test-desk','--chain','a','--chain','b']])assert.throws(()=>desk(args,opts(root)));}));
test('activity candidate links require original fingerprint and exact contract',()=>temp(root=>{const args=seed(root,true,true);const p=JSON.parse(readFileSync(join(root,'data/runtime/options-activity-studies/test-study/payload.json'),'utf8')),c=manualRegistration('linked-trade');c.contract.strikeUsd='404';c.activityReference={studyId:'test-study',studyFingerprint:p.study.studyFingerprint,candidateId:p.study.candidates[0].candidate.id};writeFileSync(join(root,'command.json'),JSON.stringify(c));manual(['--append','test-ledger','command.json'],opts(root));const r=desk(args,opts(root)),report=JSON.parse(readFileSync(join(root,base,'report.json'),'utf8'));assert(report.activity.rows[0].manualTradeIds.includes('linked-trade'));c.tradeId='wrong-trade';c.requestId='wrong-request';c.contract.strikeUsd='405';writeFileSync(join(root,'command.json'),JSON.stringify(c));assert.throws(()=>manual(['--append','test-ledger','command.json'],opts(root)),/ACTIVITY_LINK/);}));
test('synthetic study cannot be bound as owner-reported market evidence',()=>temp(root=>{seed(root,true);const p=JSON.parse(readFileSync(join(root,'data/runtime/options-activity-studies/test-study/payload.json'),'utf8')),c=manualRegistration();c.contract.strikeUsd='404';c.activityReference={studyId:'test-study',studyFingerprint:p.study.studyFingerprint,candidateId:p.study.candidates[0].candidate.id};writeFileSync(join(root,'command.json'),JSON.stringify(c));assert.throws(()=>manual(['--append','test-ledger','command.json'],opts(root)),/ACTIVITY_LINK/);}));
test('future-clock recovery is rejected',()=>temp(root=>{desk(seed(root),opts(root));assert.throws(()=>desk(['--verify','test-desk'],{workspaceRoot:root,now:()=> '2026-09-07T00:00:00.000Z'}),/CLOCK/);}));
test('extra artifact file is not silently ignored',()=>temp(root=>{desk(seed(root),opts(root));writeFileSync(join(root,base,'unexpected.txt'),'unexpected');assert.throws(()=>desk(['--verify','test-desk'],opts(root)),/UNEXPECTED_FILES/);}));
console.log(`${passed}/${passed} tests passed.`);
