import assert from "node:assert/strict";
import fs from "node:fs";
import { syncBuiltinESMExports } from "node:module";
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { tmpdir } from "node:os";
import { isAbsolute, join, relative, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { runOptionsEvidenceRehearsalCommand as run } from "./options-evidence-rehearsal.mjs";
import { runOptionsEvidenceExportCommand } from "./options-evidence-export.mjs";
import { runRobinhoodObserveCommand } from "./options-robinhood-observe.mjs";
import { optionsPaperDemoScenarios } from "../src/engines/options-paper/OptionsPaperFixtures.ts";
import { withOptionsPaperRepository } from "../src/repositories/LocalOptionsPaperRepository.ts";
const root=resolve(import.meta.dirname,".."),at="2026-09-07T05:00:00.000Z",id="test-package";
const config=JSON.parse(readFileSync(join(root,"fixtures/options-robinhood-data/observation-plan.synthetic.json"),"utf8")),study=config.studyId;
async function temporary(work){const directory=mkdtempSync(join(tmpdir(),"alpha-rehearsal-test-"));try{await work(directory);}finally{const rel=relative(tmpdir(),directory);if(isAbsolute(rel)||rel.startsWith("..")||!rel.startsWith("alpha-rehearsal-test-"))throw Error("UNSAFE_TEST_CLEANUP");rmSync(directory,{recursive:true});}}
function seed(directory,{corrupt=false,paper=true}={}){
  for(const [from,to] of [["observation-plan.synthetic.json","plan.json"],["capture.synthetic.json","source.json"]])copyFileSync(join(root,"fixtures/options-robinhood-data",from),join(directory,to));
  runRobinhoodObserveCommand(["--freeze","plan.json","--source","source.json"],{workspaceRoot:directory,now:()=>"2026-09-04T14:00:10.000Z"});
  if(paper)withOptionsPaperRepository(directory,r=>{for(const fixture of optionsPaperDemoScenarios())r.append(fixture);});
  if(corrupt)writeFileSync(join(directory,"data/runtime/options-paper/sessions.ndjson"),"PRIVATE_CORRUPT_BODY");
  runOptionsEvidenceExportCommand(["--create",study,id],{workspaceRoot:directory,now:()=>at});
}
const rehearse=(directory,args=["--rehearse",id],now=()=>at)=>run(args,{workspaceRoot:directory,temporaryParent:directory,now});
function hashes(directory){const out={};const walk=path=>{for(const item of readdirSync(path,{withFileTypes:true})){const p=join(path,item.name);if(item.isDirectory()){if(!item.name.startsWith("alpha-evidence-rehearsal-"))walk(p);}else out[relative(directory,p)]=createHash("sha256").update(readFileSync(p)).digest("hex");}};walk(directory);return out;}
let passed=0;async function test(name,work){await work();passed++;console.log(`PASS ${name}`);}
await test("isolated recovery retains five closed reviews and four candidate lessons",()=>temporary(async directory=>{seed(directory);const before=hashes(directory),r=await rehearse(directory);assert.equal(r.status,"RESTORED_COMPONENTS_READABLE");assert.equal(r.report.closedPaperReviewCoverage.closed,5);assert.equal(r.report.closedPaperReviewCoverage.reviewed,5);assert.equal(r.report.candidateNotebooks.paper,4);assert.equal(r.report.evidence.collection.state,"AVAILABLE");assert.deepEqual(hashes(directory),before);assert.equal(r.activeRuntimeRestored,false);assert.equal(r.restoredSourceBytesUnchanged,true);assert(existsSync(r.isolatedWorkspace));}));
await test("rehearsal reads the package when original paper history has changed",()=>temporary(async directory=>{seed(directory);writeFileSync(join(directory,"data/runtime/options-paper/sessions.ndjson"),"new active history");const before=hashes(directory),r=await rehearse(directory);assert.equal(r.report.closedPaperReviewCoverage.reviewed,5);assert.deepEqual(hashes(directory),before);}));
await test("corrupt source in a byte-valid package becomes a visible isolated component failure",()=>temporary(async directory=>{seed(directory,{corrupt:true});const r=await rehearse(directory);assert.equal(r.status,"REHEARSAL_HAS_BLOCKED_COMPONENTS");assert.deepEqual(r.report.blockedStores,["paper"]);assert.equal(r.report.evidence.collection.state,"AVAILABLE");assert(!JSON.stringify(r).includes("PRIVATE_CORRUPT_BODY"));assert.equal(readFileSync(join(r.isolatedWorkspace,"data/runtime/options-paper/sessions.ndjson"),"utf8"),"PRIVATE_CORRUPT_BODY");}));
await test("missing archived components remain missing and do not borrow active records",()=>temporary(async directory=>{seed(directory,{paper:false});withOptionsPaperRepository(directory,r=>{for(const fixture of optionsPaperDemoScenarios())r.append(fixture);});const r=await rehearse(directory);assert.equal(r.report.evidence.paper.state,"MISSING");assert.equal(r.report.closedPaperReviewCoverage,null);assert.equal(existsSync(join(r.isolatedWorkspace,"data/runtime/options-paper")),false);}));
await test("recovery never invokes HTTP or automatic collection",()=>temporary(async directory=>{seed(directory);const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw Error("NETWORK_FORBIDDEN");};try{const r=await rehearse(directory);assert.equal(calls,0);assert.equal(r.report.networkAccess,false);assert.equal(r.report.executionAllowed,false);}finally{globalThis.fetch=original;}}));
await test("fresh repeated rehearsals are isolated and never overwrite a previous copy",()=>temporary(async directory=>{seed(directory);const first=await rehearse(directory),before=readFileSync(join(first.isolatedWorkspace,"data/runtime/options-paper/sessions.ndjson"));const second=await rehearse(directory);assert.notEqual(first.isolatedWorkspace,second.isolatedWorkspace);assert.deepEqual(readFileSync(join(first.isolatedWorkspace,"data/runtime/options-paper/sessions.ndjson")),before);}));
await test("invalid package bytes fail before allocating a temporary workspace",()=>temporary(async directory=>{seed(directory);const path=join(directory,`data/runtime/options-evidence-exports/${id}/payload-0001.bin`);writeFileSync(path,"changed");await assert.rejects(rehearse(directory),/PAYLOAD_MISMATCH/);assert(!readdirSync(directory).some(name=>name.startsWith("alpha-evidence-rehearsal-")));}));
await test("failed isolated copy preserves its partial workspace and the original package",()=>temporary(async directory=>{seed(directory);const before=hashes(directory),original=fs.fsyncSync;fs.fsyncSync=()=>{throw Error("PRIVATE_FAILURE");};syncBuiltinESMExports();let error;try{await rehearse(directory);}catch(e){error=e;}finally{fs.fsyncSync=original;syncBuiltinESMExports();}assert.equal(error.message,"OPTIONS_REHEARSAL_LOCAL_FAILURE");assert(existsSync(error.isolatedWorkspace));assert.deepEqual(hashes(directory),before);}));
await test("completion and component checks keep actual sequential clocks",()=>temporary(async directory=>{seed(directory);let ticks=0;const r=await rehearse(directory,undefined,()=>new Date(Date.parse(at)+ticks++).toISOString());assert(r.startedAt<r.report.evidence.collection.checkedAt);assert(r.report.assessedAt<r.completedAt);assert.equal(r.report.snapshotAtomicAcrossStores,false);}));
await test("help and unsupported commands cannot create a restoration path",async()=>{assert.match((await run(["--help"],{workspaceRoot:"nonexistent"})).meaning,/No active restore/);for(const args of [["--restore",id],["--rehearse","../bad"],["--rehearse",id,"--destination","elsewhere"]]){const r=spawnSync(process.execPath,["node_modules/tsx/dist/cli.mjs","scripts/options-evidence-rehearsal.mjs",...args],{cwd:root,encoding:"utf8"});assert.equal(r.status,2);assert.equal(JSON.parse(r.stderr).executionAllowed,false);}});
console.log(`${passed}/${passed} tests passed.`);
