import { readFileSync } from "node:fs";
import { parseFomcCalendar as parse, assessFomcCalendar as assess, reportFomcCalendar as report, FOMC_CALENDAR_URL, type FomcCalendarInput } from "./FomcCalendarEngine";

const html = readFileSync("fixtures/options-fomc-calendar/calendar.synthetic.html", "utf8"), at = "2026-09-07T08:00:00.000Z", later = "2026-09-08T08:00:00.000Z";
const input = (sourceText = html, receivedAt = at): FomcCalendarInput => ({ requestedAt: receivedAt, receivedAt, url: FOMC_CALENDAR_URL, sourceText, errorCode: null });
const eq = (a: unknown, b: unknown) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw Error(`Expected ${JSON.stringify(b)}; received ${JSON.stringify(a)}`); };
const ok = (v: unknown) => { if (!v) throw Error("Expected truthy value"); };
function throws(work: () => unknown, code = "FOMC_CALENDAR_") { let error; try { work(); } catch (e) { error = e; } if (!(error instanceof Error) || !error.message.includes(code)) throw Error("Expected " + code); }
let passed = 0;
function test(name: string, work: () => void) { work(); passed++; console.log(`PASS ${name}`); }

test("selected panels preserve date precision projection marker and unknown intraday confirmation", () => { const r = parse(html, at); eq(r.selectedYears, [2026, 2027]); eq(r.meetings.length, 3); eq(r.meetings[1]!.startDate, "2026-09-15"); eq(r.meetings[1]!.endDate, "2026-09-16"); eq(r.meetings[1]!.projectionMarker, true); eq(r.meetings[1]!.intradayTime, null); eq(r.meetings[1]!.confirmationStatus, "NOT_INDEPENDENTLY_VERIFIED"); eq(r.tentativeUntilPrecedingMeetingNotePresent, true); });
test("page update date is distinct from actual request and receipt", () => { const r = assess(input()); eq(r.receivedAt, at); eq(r.calendar!.pageUpdatedDate, "2026-08-19"); eq(r.calendar!.originalPublicationTimesKnown, false); eq(r.journalAppendTimeKnown, false); });
test("current panel selection follows the New York receipt date at year rollover", () => { eq(parse(html, "2027-01-01T02:00:00.000Z").currentYearAtReceipt, 2026); eq(parse(html, "2027-01-01T05:00:00.000Z").selectedYears, [2027]); eq(parse(html, "2027-01-01T05:00:00.000Z").nextYearPanelPresent, false); });
test("missing next-year panel is explicit but missing current panel fails", () => { const one = html.replace(/<div class="panel panel-default"><div class="panel-heading"><h4><a id="101">[\s\S]*?<p>/, "<p>"); eq(parse(one, at).nextYearPanelPresent, false); throws(() => parse(one, "2027-09-07T08:00:00.000Z"), "SELECTED_YEAR_PANEL"); });
test("duplicate selected panels and missing projection legend cannot be silently ignored", () => { throws(() => parse(html.replace('</body>', html.slice(html.indexOf('<div class="panel panel-default">'), html.indexOf('<p>')) + '</body>'), at)); throws(() => parse(html.replaceAll("* Meeting associated with a Summary of Economic Projections.", "Unknown legend"), at), "PROJECTION_LEGEND"); });
test("adjacent cross-month labels retain exact calendar dates", () => { const r = parse(html.replace('<strong>January</strong>', '<strong>Jan/Feb</strong>').replace('27-28', '31-1'), at); eq(r.meetings[0]!.startDate, "2026-01-31"); eq(r.meetings[0]!.endDate, "2026-02-01"); });
test("cross-year date ranges advance only the end year", () => { const r = parse(html.replace('<strong>September</strong>', '<strong>Dec/Jan</strong>').replace('15-16*', '31-1*'), at); eq(r.meetings[1]!.endDate, "2027-01-01"); });
test("single-day notation votes and unscheduled labels are explicit kinds", () => { for (const [label, kind] of [['notation vote', 'NOTATION_VOTE'], ['unscheduled', 'UNSCHEDULED']]) { const r = parse(html.replace('15-16*', '15 (' + label + ')'), at); eq(r.meetings[1]!.kind, kind); eq(r.meetings[1]!.startDate, r.meetings[1]!.endDate); } });
test("invalid days non-adjacent months reversed or excessive ranges reject", () => { for (const [month, days] of [['February','30-31'], ['January','28-27'], ['Jan/Mar','31-1'], ['January','1-20'], ['January','15'], ['January','15-16 (notation vote)'], ['constructor','15-16'], ['January','0-1']]) throws(() => parse(html.replace('<strong>January</strong>', '<strong>' + month + '</strong>').replace('27-28', days!), at)); });
test("duplicate or overlapping meeting dates cannot become independent events", () => { throws(() => parse(html.replace('<strong>September</strong>', '<strong>January</strong>').replace('15-16*', '28-29*'), at), 'MEETING_ORDER_OR_OVERLAP'); throws(() => parse(html.replace('<strong>September</strong>', '<strong>Dec/Jan</strong>').replace('15-16*', '31-1*').replace('26-27', '1-2'), at), 'MEETING_ORDER_OR_OVERLAP'); });
test("duplicate missing or injected date cells reject instead of dropping rows", () => { for (const changed of [html.replace('15-16*', ''), html.replace('15-16*', '<span>15-16*</span>'), html.replace('15-16*', '15&amp;16'), html.replace('<div class="fomc-meeting__date col-xs-4">15-16*</div>', '<div class="fomc-meeting__date col-xs-4">15-16*</div><div class="fomc-meeting__date col-xs-4">17-18</div>')]) throws(() => parse(changed, at)); });
test("unexpected visibility or script attributes on selected rows reject", () => { throws(() => parse(html.replace('class="row fomc-meeting" ">', 'class="row fomc-meeting" hidden>'), at), 'ROW_ATTRIBUTES'); throws(() => parse(html.replace('class="fomc-meeting__date col-xs-4">', 'class="fomc-meeting__date col-xs-4" onclick="bad()">'), at)); });
test("scripts styles and comments cannot inject calendar rows or execute", () => { const row = '<div class="row fomc-meeting"><div class="fomc-meeting__month"><strong>Bad</strong></div></div>'; const source = html.replace('</head>', `<script>${row}</script><style>${row}</style><!--${row}--></head>`); eq(parse(source, at), parse(html, at)); });
test("unterminated executable markup entity declarations and invalid unicode fail", () => { for (const patch of ['<script>unclosed', '<!--unclosed', '<!ENTITY bad>', '\u0000', '\ud800']) throws(() => parse(html + patch, at)); });
test("source identity and byte limit reject unrelated or oversized pages", () => { throws(() => parse(html.replace('The Fed - Meeting calendars and information', 'Login'), at), 'PAGE_IDENTITY'); throws(() => parse(html + ' '.repeat(524288), at), 'BODY_TOO_LARGE'); });
test("missing update metadata remains null while malformed or future metadata rejects", () => { eq(parse(html.replace(/<div class='lastUpdate'[\s\S]*?<\/div>/, ''), at).pageUpdatedDate, null); for (const value of ['February 30, 2026', 'Tomorrow', 'December 19, 2026']) throws(() => parse(html.replace('August 19, 2026', value), at)); });
test("free-form dates outside selected year panels are not silently interpreted", () => { const r = parse(html.replace('<p>', '<p>January 25-26, 2028. '), at); eq(r.meetings.length, 3); eq(r.additionalDateNotesParsed, false); });
test("upcoming thirty-date horizon includes date overlap and never infers 14:00", () => { const r = report([input()], '2026-09-16T23:00:00.000Z'); eq(r.upcoming.length, 1); eq(r.overlappingToday.length, 1); eq(r.todayNewYork, '2026-09-16'); eq(r.horizonEndDateExclusive, '2026-10-16'); eq(r.tradingRiskWindow, null); });
test("meetings ending before the New York date are no longer upcoming", () => { const r = report([input()], '2026-09-17T04:00:00.000Z'); eq(r.upcoming.length, 0); eq(r.overlappingToday.length, 0); });
test("latest failed retrieval keeps last-known data separate from current dates", () => { const r = report([input(), {...input(html,later),sourceText:null,errorCode:'NETWORK_FAILED'}], later); eq(r.latestRetrieval!.status,'FAILED'); eq(r.upcoming,[]); eq(r.lastKnownSchedule!.fromLatestRetrieval,false); eq(r.comparison.available,false); });
test("date-key changes show added and absent keys without asserting rescheduling", () => { const r = report([input(),input(html.replace('15-16*','16-17*'),later)],later); eq(r.comparison.addedDateKeys.length,1); eq(r.comparison.absentDateKeys.length,1); eq(r.comparison.changed.length,0); eq(r.comparison.absenceMeansCancellation,false); eq(r.comparison.dateKeyChangesProveRescheduling,false); });
test("same-date projection corrections retain before after and receipt clocks", () => { const r = report([input(),input(html.replace('15-16*','15-16'),later)],later); eq(r.comparison.changed.length,1); eq(r.comparison.changed[0]!.observedAt,later); eq(r.comparison.changed[0]!.before.projectionMarker,true); eq(r.comparison.changed[0]!.after.projectionMarker,false); });
test("A to B to A schedule changes retain the later correction instead of deduping globally", () => { const end='2026-09-09T08:00:00.000Z'; const r=report([input(),input(html.replace('15-16*','16-17*'),later),input(html,end)],end); eq(r.retrievalCount,3); eq(r.comparison.addedDateKeys,['2026-09-15/2026-09-16/MEETING_DATE_RANGE']); eq(r.latestRetrieval!.receivedAt,end); });
test("year-scope rollover disables misleading comparison across different panels", () => { const end='2027-01-01T05:00:00.000Z'; const r=report([input(),input(html,end)],end); eq(r.comparison.issue,'SELECTED_YEAR_SCOPE_CHANGED'); eq(r.comparison.addedDateKeys,[]); });
test("current refresh age and unknown publisher freshness are separate", () => { const r=report([input()],'2026-09-09T08:00:00.000Z'); eq(r.refreshOverdue,true); eq(r.publisherFreshnessKnown,false); });
test("input scopes shapes clocks and fixed failure codes are enforced", () => { for(const v of [{...input(),url:'https://example.com'},{...input(),extra:1},{...input(),receivedAt:'2026-09-07T07:00:00.000Z'},{...input(),errorCode:'NETWORK_FAILED'},{...input(),sourceText:null,errorCode:'PRIVATE'}]) throws(()=>assess(v as FomcCalendarInput)); throws(()=>assess({...input(),requestedAt:'2026-09-07T08:00:00Z'}),'CLOCK'); });
test("future overlapping and excessive histories cannot enter a report", () => { throws(()=>report([input(html,later)],at),'HISTORY_CLOCK'); throws(()=>report([input(html,later),input()],later),'HISTORY_CLOCK'); throws(()=>report(Array.from({length:367},()=>input()),at),'HISTORY_LIMIT'); });
test("empty history retains unknown context and immutable reports grant no authority", () => { const empty=report([],at); eq(empty.latestRetrieval,null); eq(empty.upcoming,[]); const r=report([input()],at); eq(r,report([input()],at)); ok(Object.isFrozen(r.latestRetrieval!.calendar!.meetings)); eq(r.executionAllowed,false); eq(r.replayAllowed,false); eq(r.winProbability,null); eq(r.strategySignal,null); });
console.log(`${passed}/${passed} tests passed.`);
