import { OPTIONS_NEWS_DOMAIN_VERSION, NewsBudgetState, NewsEventStatus, NewsEvidenceRelation } from "../../contracts";
import type { EventEvidenceLink } from "../../contracts/OptionsNewsDomain";
import { OptionsNewsEvidenceJournalAdapter } from "../../repositories/OptionsNewsEvidenceJournalAdapter";
import { InMemoryOptionsNewsRepository } from "../../repositories/InMemoryOptionsNewsRepository";
import { buildCanonicalEvent, transition } from "./OptionsNewsProcessing";
import { DeterministicNewsSummaryProvider } from "./DeterministicNewsSummary";
import { OptionsNewsBudgetLedger } from "./OptionsNewsBudgetLedger";
import { fixtureHealth } from "./OptionsNewsHealth";
import { adapters, equal, fixture, request, TestHarness, throws, trueValue } from "./OptionsNewsTestSupport";

const h=new TestHarness();const all=adapters();const at="2026-08-08T12:00:00.000Z";const evidence=all.sec!.normalize(fixture("sec-edgar.json"),request("source:sec-edgar"))[0]!;const summary=new DeterministicNewsSummaryProvider().summarize({evidence:[evidence],generatedAtUtc:at});const event=buildCanonicalEvent([evidence],summary,at);const link:EventEvidenceLink={domainVersion:OPTIONS_NEWS_DOMAIN_VERSION,linkId:`${event.eventId}:link:test`,eventId:event.eventId,evidenceId:evidence.evidenceId,relation:NewsEvidenceRelation.Supports,relationshipReasonCode:"TEST",checkedFacts:["form"],createdAtUtc:at,ruleVersion:"1.0"};const tr=transition(event.eventId,null,NewsEventStatus.Discovered,"FIRST",[evidence.evidenceId],event.discoveredAtUtc);
function seeded():InMemoryOptionsNewsRepository{const r=new InMemoryOptionsNewsRepository();r.putEvidence(evidence);r.putEvent(event);r.putLink(link);r.putTransition(tr);return r;}
h.test("repository appends immutable evidence",()=>equal(new InMemoryOptionsNewsRepository().putEvidence(evidence),"APPENDED","append"));
h.test("repository replays identical evidence",()=>{const r=new InMemoryOptionsNewsRepository();r.putEvidence(evidence);equal(r.putEvidence(structuredClone(evidence)),"REPLAYED","replay");});
h.test("repository rejects evidence idempotency conflicts",()=>{const r=new InMemoryOptionsNewsRepository();r.putEvidence(evidence);throws(()=>r.putEvidence({...evidence,originalHeadlineEnglish:"changed"}),"IDEMPOTENCY_CONFLICT");});
h.test("repository replays identical canonical event",()=>{const r=seeded();equal(r.putEvent(structuredClone(event)),"REPLAYED","replay");});
h.test("repository updates same canonical identity",()=>{const r=seeded();equal(r.putEvent({...event,currentStateReasonCode:"NEW_EVIDENCE"}),"UPDATED","update");});
h.test("repository rejects link without references",()=>throws(()=>new InMemoryOptionsNewsRepository().putLink(link),"LINK_REFERENCE_NOT_FOUND"));
h.test("query by topic",()=>equal(seeded().queryEvents({topics:["TECH"]}).length,1,"query"));
h.test("query by entity",()=>equal(seeded().queryEvents({entityIds:["entity:acme"]}).length,1,"query"));
h.test("query by symbol",()=>equal(seeded().queryEvents({symbols:["ACME"]}).length,1,"query"));
h.test("query by event type and status",()=>equal(seeded().queryEvents({eventTypes:["SEC_FILING"],verificationStatuses:["VERIFIED"]}).length,1,"query"));
h.test("query by time range fails closed to no result",()=>equal(seeded().queryEvents({fromUtc:"2027-01-01T00:00:00.000Z"}).length,0,"query"));
h.test("repository returns complete evidence lineage",()=>equal(seeded().listEvidence(event.eventId)[0]!.rawPayloadHash,evidence.rawPayloadHash,"hash"));
h.test("repository returns transition history",()=>equal(seeded().listTransitions(event.eventId).length,1,"transitions"));
h.test("controlled Evidence Journal projection is read-only and namespaced",()=>{const r=seeded();const p=new OptionsNewsEvidenceJournalAdapter().project(event,r.listEvidence(event.eventId),r.listLinks(event.eventId),r.listTransitions(event.eventId));equal(p.namespace,"OPTIONS_NEWS","namespace");equal(p.readOnly,true,"read-only");});
h.test("projection retains raw payload provenance",()=>trueValue(new OptionsNewsEvidenceJournalAdapter().project(event,[evidence],[link],[tr]).provenance[0]!.includes("sha256="),"provenance"));
h.test("budget 79.99 remains NORMAL",()=>{const l=new OptionsNewsBudgetLedger();l.reserve("r1","p1",at,7999);equal(l.snapshot(at).state,NewsBudgetState.Normal,"state");});
h.test("budget 80.00 enters WARNING",()=>{const l=new OptionsNewsBudgetLedger();l.reserve("r1","p1",at,8000);equal(l.snapshot(at).state,NewsBudgetState.Warning,"state");});
h.test("budget 99.99 remains WARNING",()=>{const l=new OptionsNewsBudgetLedger();l.reserve("r1","p1",at,9999);equal(l.snapshot(at).state,NewsBudgetState.Warning,"state");});
h.test("budget 100.00 blocks subsequent consumption",()=>{const l=new OptionsNewsBudgetLedger();l.reserve("r1","p1",at,10000);equal(l.snapshot(at).state,NewsBudgetState.BlockedBudget,"state");throws(()=>l.reserve("r2","p1",at,1),NewsBudgetState.BlockedBudget);});
h.test("estimated hard-limit overflow is blocked before call",()=>{const l=new OptionsNewsBudgetLedger();l.reserve("r1","p1",at,9999);throws(()=>l.reserve("r2","p1",at,2),NewsBudgetState.BlockedBudget);});
h.test("unknown estimated cost fails closed",()=>throws(()=>new OptionsNewsBudgetLedger().reserve("r1","p1",at,null),NewsBudgetState.BlockedCostUnknown));
h.test("sequential concurrent reservations cannot exceed hard limit",()=>{const l=new OptionsNewsBudgetLedger();l.reserve("r1","p1",at,6000);throws(()=>l.reserve("r2","p2",at,5000),NewsBudgetState.BlockedBudget);equal(l.snapshot(at).reservedMinorUnits,6000,"reserved");});
h.test("failed request releases reservation",()=>{const l=new OptionsNewsBudgetLedger();l.reserve("r1","p1",at,9000);l.release("r1");equal(l.snapshot(at).reservedMinorUnits,0,"reserved");});
h.test("actual cost reconciliation replaces reservation",()=>{const l=new OptionsNewsBudgetLedger();l.reserve("r1","p1",at,500);l.reconcile("r1",400);equal(l.snapshot(at).committedMinorUnits,400,"committed");});
h.test("monthly budget boundary is UTC",()=>{const l=new OptionsNewsBudgetLedger();l.reserve("r1","p1","2026-08-31T23:59:59.000Z",9999);equal(l.snapshot("2026-09-01T00:00:00.000Z").state,NewsBudgetState.Normal,"new month");});
h.test("provider switching cannot reset combined budget",()=>{const l=new OptionsNewsBudgetLedger();l.reserve("r1","provider:a",at,7000);throws(()=>l.reserve("r2","provider:b",at,4000),NewsBudgetState.BlockedBudget);});
h.test("reservation replay is idempotent and conflicting reuse is rejected",()=>{const l=new OptionsNewsBudgetLedger();l.reserve("r1","p1",at,100);l.reserve("r1","p1",at,100);throws(()=>l.reserve("r1","p2",at,9999),"BUDGET_IDEMPOTENCY_CONFLICT");equal(l.snapshot(at).reservedMinorUnits,100,"reserved");});
h.test("health exposes fixture-only network and credential authority",()=>{const health=fixtureHealth({providerId:"p",adapterName:"a",adapterVersion:"1",atUtc:at,requestCount:1,parseCount:1,normalizeCount:1,verifyCount:1});equal(health.networkAuthority,"BLOCKED","network");equal(health.credentialAuthority,"NOT_READ","credentials");equal(health.dataFreshness,"FIXTURE_ONLY","freshness");});
h.test("health exposes budget breaker",()=>equal(fixtureHealth({providerId:"p",adapterName:"a",adapterVersion:"1",atUtc:at,requestCount:1,parseCount:1,normalizeCount:1,verifyCount:0,budgetState:NewsBudgetState.BlockedBudget}).state,"BLOCKED_BUDGET","health"));
h.test("health never claims live SLA from fixture data",()=>equal(fixtureHealth({providerId:"p",adapterName:"a",adapterVersion:"1",atUtc:at,requestCount:1,parseCount:1,normalizeCount:1,verifyCount:1}).latency.state,"UNMEASURED","latency"));
h.run("Options News persistence budget and health");
