import { NewsEventStatus, NewsSummaryProvider, NewsSummaryStatus } from "../../contracts/OptionsNewsDomain";
import { NewsTransportMode } from "../../contracts/OptionsNewsProvider";
import { OPTIONS_NEWS_SOURCE_REGISTRATIONS } from "../../integration/news/OptionsNewsSources";
import { DisabledLiveNewsTransport, DryRunNewsTransport } from "../../integration/news/NewsTransports";
import { DeterministicNewsSummaryProvider } from "./DeterministicNewsSummary";
import { buildCanonicalEvent, canonicalFingerprint, DeterministicEntityLinker, expiryDecision, formatEasternTime, transition } from "./OptionsNewsProcessing";
import { validateCanonicalNewsEvent, validateNewsEvidenceRecord } from "./OptionsNewsValidation";
import { adapters, deepEqual, equal, fixture, registry, request, TestHarness, throws, trueValue } from "./OptionsNewsTestSupport";

const h = new TestHarness(); const all = adapters();
h.test("registry contains four locked Phase 1 sources", () => equal(registry.list().length,4,"source count"));
h.test("registry fingerprint is stable SHA-256", () => equal(registry.fingerprint().length,64,"fingerprint length"));
h.test("registry returns defensive copies", () => { const a=registry.list(); const b=registry.list(); trueValue(a!==b && a[0]!==b[0],"defensive copy"); });
h.test("registry rejects adapter identity drift", () => throws(() => registry.assertAdapterIdentity("source:sec-edgar","provider:wrong","publisher:sec"),"REGISTRY_DRIFT"));
h.test("Tier 3 discovery source cannot masquerade as eligible", () => throws(() => new (registry.constructor as typeof import("./OptionsNewsSourceRegistry").OptionsNewsSourceRegistry)([{...OPTIONS_NEWS_SOURCE_REGISTRATIONS[0]!,sourceId:"source:social",tier:"TIER_3",eligibility:"ELIGIBLE"} as never]),"INVALID_SOURCE_ELIGIBILITY"));
h.test("normalized evidence satisfies strict contract", () => validateNewsEvidenceRecord(all.sec!.normalize(fixture("sec-edgar.json"),request("source:sec-edgar"))[0]));
h.test("unknown evidence fields are rejected", () => { const value={...all.sec!.normalize(fixture("sec-edgar.json"),request("source:sec-edgar"))[0]!,unknown:true}; throws(() => validateNewsEvidenceRecord(value),"INVALID_EVIDENCE"); });
h.test("timestamp reversal is rejected", () => { const value={...all.sec!.normalize(fixture("sec-edgar.json"),request("source:sec-edgar"))[0]!,normalizedAtUtc:"2026-08-07T17:00:00.000Z"}; throws(() => validateNewsEvidenceRecord(value),"timestamps are not chronological"); });
h.test("deterministic summary binds evidence", () => { const e=all.sec!.normalize(fixture("sec-edgar.json"),request("source:sec-edgar")); const s=new DeterministicNewsSummaryProvider().summarize({evidence:e,generatedAtUtc:"2026-08-08T12:00:00.000Z"}); equal(s.summaryStatus,NewsSummaryStatus.Generated,"summary status"); deepEqual(s.inputEvidenceIds,[e[0]!.evidenceId],"summary inputs"); });
h.test("empty summary is explicitly unavailable", () => { const s=new DeterministicNewsSummaryProvider().summarize({evidence:[],generatedAtUtc:"2026-08-08T12:00:00.000Z"}); equal(s.chineseSummary,null,"summary text"); equal(s.summaryProvider,NewsSummaryProvider.Deterministic,"provider"); });
h.test("entity mapping is point-in-time", () => { const linker=new DeterministicEntityLinker([{alias:"Acme",entityId:"entity:acme",symbol:"ACME",source:"fixture",version:"1.0",effectiveFromUtc:"2020-01-01T00:00:00.000Z",effectiveToUtc:null}]); equal(linker.resolve("acme","2026-01-01T00:00:00.000Z").symbol,"ACME","symbol"); });
h.test("unknown entity fails closed", () => throws(() => new DeterministicEntityLinker([]).resolve("Unknown","2026-01-01T00:00:00.000Z"),"UNKNOWN_ENTITY"));
h.test("ambiguous entity fails closed", () => { const m={alias:"Acme",entityId:"entity:a",symbol:"A",source:"fixture",version:"1",effectiveFromUtc:"2020-01-01T00:00:00.000Z",effectiveToUtc:null}; throws(() => new DeterministicEntityLinker([m,{...m,entityId:"entity:b",symbol:"B"}]).resolve("Acme","2026-01-01T00:00:00.000Z"),"AMBIGUOUS_ENTITY"); });
h.test("canonical fingerprint is deterministic", () => { const e=all.sec!.normalize(fixture("sec-edgar.json"),request("source:sec-edgar"))[0]!; equal(canonicalFingerprint(e),canonicalFingerprint(structuredClone(e)),"fingerprint"); });
h.test("Eastern display handles EDT", () => trueValue(formatEasternTime("2026-08-08T16:00:00.000Z").includes("12:00:00"),"EDT time"));
h.test("Eastern display handles EST", () => trueValue(formatEasternTime("2026-12-08T17:00:00.000Z").includes("12:00:00"),"EST time"));
h.test("expiry requires a versioned event policy", () => throws(() => expiryDecision("UNKNOWN","2026-01-01T00:00:00.000Z","2026-01-02T00:00:00.000Z",{}),"EXPIRY_POLICY_NOT_FOUND"));
h.test("expiry applies configured TTL", () => trueValue(expiryDecision("FLASH","2026-01-01T00:00:00.000Z","2026-01-01T00:01:01.000Z",{FLASH:60}),"expired"));
h.test("state machine rejects skipped normalization", () => throws(() => transition("event:1",NewsEventStatus.Discovered,NewsEventStatus.Verified,"skip",[],"2026-01-01T00:00:00.000Z"),"ILLEGAL_NEWS_TRANSITION"));
h.test("initial transition must be discovered", () => throws(() => transition("event:1",null,NewsEventStatus.Verifying,"bad",[],"2026-01-01T00:00:00.000Z"),"initial state"));
h.test("dry-run transport returns only a request plan", () => { const built=all.sec!.buildRequest(request("source:sec-edgar"),NewsTransportMode.DryRun); const result=new DryRunNewsTransport().execute(built) as {dryRun:boolean}; trueValue(result.dryRun,"dry run"); });
h.test("live transport is always blocked", () => throws(() => new DisabledLiveNewsTransport().execute({} as never),"NETWORK_BLOCKED"));
h.test("event validator rejects verified event without timestamp", () => { const evidence=all.sec!.normalize(fixture("sec-edgar.json"),request("source:sec-edgar")); const at="2026-08-08T12:00:00.000Z"; const summary=new DeterministicNewsSummaryProvider().summarize({evidence,generatedAtUtc:at}); const event=buildCanonicalEvent(evidence,summary,at); throws(() => validateCanonicalNewsEvent({...event,verifiedAtUtc:null}),"verified event requires"); });
h.run("Options News contracts and registry");
