import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  AIAuditActorType, AIAuditRecordType, AIAuditRetentionClassification, AIAuditSourceSubsystem,
  PrivacyLevel, ResearchAmendmentType, ResearchAppendStatus, ResearchAssumptionImportance,
  ResearchAuditOperationType, ResearchEvidenceType, ResearchExportDestination,
  ResearchExportFormat, ResearchExportStatus, ResearchObservationClassification,
  ResearchQuality, ResearchRecordType, ResearchReferenceResolution, ResearchReferenceType,
  ResearchScenarioType, ResearchSourceType, ResearchStatus, ResearchUncertaintyCategory,
  createResearchId, type ResearchAmendment, type ResearchAuditRecord,
  type ResearchRecord, type ResearchRecordSnapshot, type ResearchReview, type ResearchSupersession,
} from "../../contracts";
import { InMemoryResearchRepository, LocalNdjsonResearchRepository } from "../../repositories";
import { ResearchLab, auditRecordFromResearch, exportResearch, type ResearchClock } from ".";

interface TestCase { readonly name: string; readonly run: () => void; }
function assertEqual<T>(actual: T, expected: T, message: string): void { if (!Object.is(actual, expected)) throw new Error(`${message}: expected ${String(expected)}, received ${String(actual)}.`); }
function assertTrue(value: boolean, message: string): void { if (!value) throw new Error(message); }
function assertDeepEqual(actual: unknown, expected: unknown, message: string): void { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(message); }
function expectError(action: () => void, expected: string): void { try { action(); } catch (error: unknown) { const message = error instanceof Error ? error.message : String(error); assertTrue(message.includes(expected), `Expected "${expected}", received "${message}".`); return; } throw new Error(`Expected error containing "${expected}".`); }
class FixedClock implements ResearchClock { now(): string { return "2026-07-18T20:00:00.000Z"; } }

function references() {
  return {
    predictions: [{ referenceId: "prediction-1", recordType: ResearchReferenceType.Prediction, resolution: ResearchReferenceResolution.Resolved, version: "v1", frozenStatus: "LOCKED", summary: "Synthetic prediction" }],
    journals: [{ referenceId: "journal-1", recordType: ResearchReferenceType.Journal, resolution: ResearchReferenceResolution.Resolved, version: "v1" }],
    strategies: [{ referenceId: "strategy-1", recordType: ResearchReferenceType.Strategy, resolution: ResearchReferenceResolution.Unresolved }],
    portfolios: [{ referenceId: "portfolio-1", recordType: ResearchReferenceType.Portfolio, resolution: ResearchReferenceResolution.Unresolved }],
    audits: [{ referenceId: "audit-1", recordType: ResearchReferenceType.Audit, resolution: ResearchReferenceResolution.Resolved, version: "v1" }],
    historicalPatterns: [{ referenceId: "pattern-1", recordType: ResearchReferenceType.HistoricalPattern, resolution: ResearchReferenceResolution.Unresolved }],
    research: [], decisions: [], trades: [],
    developmentValidations: [{ referenceId: "validation-1", recordType: ResearchReferenceType.DevelopmentValidation, resolution: ResearchReferenceResolution.Unresolved }],
    marketSnapshots: [{ referenceId: "market-snapshot-1", recordType: ResearchReferenceType.MarketSnapshot, resolution: ResearchReferenceResolution.Unresolved, marketTimestamp: "2026-07-18T13:00:00.000Z" }],
    catalystEvents: [{ referenceId: "catalyst-event-1", recordType: ResearchReferenceType.CatalystEvent, resolution: ResearchReferenceResolution.Unresolved }],
    eventReplayTimelines: [{ referenceId: "timeline-1", recordType: ResearchReferenceType.EventReplay, resolution: ResearchReferenceResolution.Unresolved }],
  } as const;
}

function snapshot(overrides: Partial<ResearchRecordSnapshot> = {}): ResearchRecordSnapshot {
  return {
    schemaVersion: "1.0", researchVersion: "v1", createdAt: "2026-07-18T14:00:00.000Z", eventTimestamp: "2026-07-18T13:00:00.000Z", finalizedAt: "2026-07-18T15:00:00.000Z",
    researchType: ResearchRecordType.Stock, title: "Synthetic research", question: { statement: "Does synthetic evidence justify the stated thesis?" }, scope: { included: ["Synthetic evidence"], excluded: ["Live market data"] }, market: "US", ticker: "ALPHA", asset: "Synthetic Asset", company: "Alpha Synthetic", sector: "Technology", industry: "Software", theme: "Evidence discipline", timeHorizon: "30 days",
    factualObservations: ["Synthetic value increased."],
    sources: [{ sourceReferenceId: "source-1", sourceType: ResearchSourceType.Dataset, title: "Synthetic dataset", publisherOrOwner: "Alpha", observedAt: "2026-07-18T13:00:00.000Z", retrievedAt: "2026-07-18T13:30:00.000Z", version: "v1", locationReference: "local:synthetic", privacyLevel: PrivacyLevel.Internal, reliabilityScore: 90, freshnessScore: 95, contentIntegrityReference: "fnv1a64:synthetic" }],
    dataPoints: [{ dataPointId: "point-1", name: "Synthetic value", value: 42, unit: "points", observedAt: "2026-07-18T13:00:00.000Z", sourceReferenceId: "source-1" }],
    evidence: [
      { evidenceId: "evidence-fact-1", evidenceType: ResearchEvidenceType.Fact, classification: ResearchObservationClassification.Fact, statement: "Synthetic value was 42.", sourceReferenceIds: ["source-1"], dataPointReferences: ["point-1"] },
      { evidenceId: "evidence-inference-1", evidenceType: ResearchEvidenceType.Inference, classification: ResearchObservationClassification.Inference, statement: "The value may support the thesis.", sourceReferenceIds: ["source-1"], dataPointReferences: [], interpretation: "Inference is not confirmed fact." },
      { evidenceId: "evidence-counter-1", evidenceType: ResearchEvidenceType.Counterevidence, classification: ResearchObservationClassification.Fact, statement: "The sample is intentionally narrow.", sourceReferenceIds: ["source-1"], dataPointReferences: [] },
    ],
    hypotheses: [{ hypothesisId: "hypothesis-1", statement: "The synthetic signal persists.", supportingEvidenceIds: ["evidence-fact-1"], contradictingEvidenceIds: ["evidence-counter-1"] }],
    assumptions: [{ assumptionId: "assumption-1", statement: "The fixture is internally consistent.", importance: ResearchAssumptionImportance.High, confidence: 80, sourceReferenceIds: ["source-1"], testable: true, invalidationCondition: "Fixture inconsistency is discovered." }],
    uncertainties: [{ uncertaintyId: "uncertainty-1", category: ResearchUncertaintyCategory.MissingData, statement: "Persistence is unknown.", unknowns: ["Future behavior"], missingData: ["Future observations"], unresolvedQuestions: ["How long will it persist?"] }],
    counterarguments: ["A narrow sample may not generalize."], risks: [{ riskId: "risk-1", statement: "Overgeneralization risk.", likelihood: 40, impact: "Medium", evidenceReferences: ["evidence-counter-1"] }], catalysts: [{ catalystId: "catalyst-1", statement: "A second observation.", evidenceReferences: ["evidence-fact-1"] }],
    thesis: { statement: "The synthetic evidence conditionally supports the thesis.", supportingEvidenceIds: ["evidence-fact-1"], counterEvidenceIds: ["evidence-counter-1"] }, conclusion: { statement: "Continue observation; do not authorize capital action.", limitations: ["Synthetic evidence only"] }, confidence: { score: 72, rationale: "Evidence is coherent but narrow." },
    scenarios: [{ scenarioId: "scenario-base", scenarioType: ResearchScenarioType.Base, description: "Signal persists briefly.", probability: 60, catalysts: ["Second observation"], invalidationConditions: ["Signal reverses"], expectedMarketBehavior: "No live-market claim.", timeHorizon: "30 days", supportingEvidenceIds: ["evidence-fact-1"] }], invalidationConditions: ["Synthetic value reverses."], references: references(), tags: ["synthetic", "research"], authorType: ResearchAuthorType.Owner, ownerReference: "owner-1", privacyLevel: PrivacyLevel.Internal, retention: AIAuditRetentionClassification.Permanent, correlationId: "correlation-1", traceId: "trace-1", policyVersions: { research: "research-v1" }, metadata: { source: "synthetic", verified: true }, ...overrides,
  };
}

// Avoid widening the enum in the large fixture above.
import { ResearchAuthorType } from "../../contracts";
function setup(value = snapshot()): { repository: InMemoryResearchRepository; lab: ResearchLab; record: ResearchRecord } { const repository = new InMemoryResearchRepository(); const lab = new ResearchLab(repository, new FixedClock()); return { repository, lab, record: lab.finalize(value).record }; }
function amendment(id: string, overrides: Partial<ResearchAmendment> = {}): ResearchAmendment { return { amendmentId: `${id}:amendment:1`, researchId: id, createdAt: "2026-07-18T16:00:00.000Z", amendmentType: ResearchAmendmentType.Clarification, reason: "Clarify without replacing prior evidence.", changedFields: ["conclusion"], additionalEvidence: [], authorReference: "owner-1", auditReference: { referenceId: "audit-amendment-1", recordType: ResearchReferenceType.Audit, resolution: ResearchReferenceResolution.Resolved, version: "v1" }, ...overrides }; }
function review(id: string, overrides: Partial<ResearchReview> = {}): ResearchReview { return { reviewId: `${id}:review:1`, researchId: id, createdAt: "2026-07-18T17:00:00.000Z", reviewer: "owner-1", whatHeldUp: "Evidence classification held up.", whatFailed: "Persistence was uncertain.", correctAssumptions: ["Fixture consistency"], incorrectAssumptions: ["Persistence"], sourceQuality: ResearchQuality.Good, processQuality: ResearchQuality.Good, conclusionQuality: ResearchQuality.Mixed, predictionReferences: references().predictions, profitabilityReferences: [], lessons: ["Keep inference separate from fact."], futureResearchQuestions: ["How persistent is the signal?"], strategyChangeCandidate: "Candidate only", auditReference: { referenceId: "audit-review-1", recordType: ResearchReferenceType.Audit, resolution: ResearchReferenceResolution.Resolved, version: "v1" }, ...overrides }; }
function supersession(prior: string, next: string, overrides: Partial<ResearchSupersession> = {}): ResearchSupersession { return { supersessionId: `${prior}:supersession:1`, priorResearchId: prior, newResearchId: next, reason: "Material synthetic facts changed.", changedFacts: ["New observation"], changedAssumptions: ["Persistence"], changedMarketRegime: "Synthetic regime changed.", changedThesis: "Updated conditional thesis.", createdAt: "2026-07-18T19:00:00.000Z", ownerReference: "owner-1", auditReference: { referenceId: "audit-supersession-1", recordType: ResearchReferenceType.Audit, resolution: ResearchReferenceResolution.Resolved, version: "v1" }, ...overrides }; }
function addNext(lab: ResearchLab, prior: string): ResearchRecord { return lab.finalize(snapshot({ researchVersion: "v2", createdAt: "2026-07-18T16:00:00.000Z", finalizedAt: "2026-07-18T18:00:00.000Z", title: "Updated synthetic research", supersedesResearchId: prior })).record; }

const tests: ReadonlyArray<TestCase> = [
  { name: "valid finalized research appends", run: () => assertEqual(setup().record.status, ResearchStatus.Finalized, "status") },
  { name: "content-derived research IDs are stable", run: () => assertEqual(createResearchId(snapshot()), createResearchId(snapshot()), "ID") },
  { name: "empty research question is rejected", run: () => expectError(() => setup(snapshot({ question: { statement: "" } })), "EMPTY_QUESTION") },
  { name: "finalized research without evidence is rejected", run: () => expectError(() => setup(snapshot({ evidence: [] })), "EMPTY_EVIDENCE") },
  { name: "finalized research without conclusion is rejected", run: () => expectError(() => setup(snapshot({ conclusion: { statement: "", limitations: [] } })), "EMPTY_CONCLUSION") },
  { name: "identical append is idempotent", run: () => { const repository = new InMemoryResearchRepository(); const lab = new ResearchLab(repository, new FixedClock()); assertEqual(lab.finalize(snapshot()).status, ResearchAppendStatus.Appended, "first"); assertEqual(lab.finalize(snapshot()).status, ResearchAppendStatus.Replayed, "second"); } },
  { name: "conflicting duplicate research ID is rejected", run: () => { const { repository, record } = setup(); expectError(() => repository.appendFinalized({ ...record, title: "Conflict" }, "2026-07-18T20:00:00.000Z"), "IDEMPOTENCY_CONFLICT"); } },
  { name: "finalized research cannot be overwritten", run: () => { const { lab, record } = setup(); (record as { title: string }).title = "Mutated"; assertTrue(lab.get(record.researchId)?.title !== "Mutated", "stored record mutated"); } },
  { name: "repository exposes no update overwrite or delete", run: () => { const repository: object = new InMemoryResearchRepository(); assertTrue(!("update" in repository) && !("overwrite" in repository) && !("delete" in repository), "mutable method exposed"); } },
  { name: "full draft collection analysis finalization provenance is recorded", run: () => assertDeepEqual(setup().record.history.map((value) => value.toStatus), [ResearchStatus.Collecting, ResearchStatus.Analyzing, ResearchStatus.Finalized], "lifecycle") },
  { name: "invalid lifecycle provenance is rejected", run: () => { const { repository, record } = setup(); const other = { ...record, researchId: `${record.researchId}:bad`, history: record.history.slice(0, 1) }; expectError(() => repository.appendFinalized(other, "2026-07-18T20:00:00.000Z"), "INVALID_ID"); } },
  { name: "review before finalization is rejected", run: () => expectError(() => new ResearchLab(new InMemoryResearchRepository(), new FixedClock()).review(review("research:missing")), "RECORD_NOT_FOUND") },
  { name: "review appends and advances projection", run: () => { const { lab, record } = setup(); lab.review(review(record.researchId)); assertEqual(lab.get(record.researchId)?.status, ResearchStatus.Reviewed, "status"); } },
  { name: "review preserves original conclusion", run: () => { const { lab, record } = setup(); lab.review(review(record.researchId)); assertEqual(lab.history(record.researchId)?.record.conclusion.statement, record.conclusion.statement, "conclusion"); } },
  { name: "amendment preserves original record", run: () => { const { lab, record } = setup(); lab.amend(amendment(record.researchId)); assertEqual(lab.history(record.researchId)?.amendments.length, 1, "amendment"); assertEqual(lab.get(record.researchId)?.conclusion.statement, record.conclusion.statement, "original"); } },
  { name: "amendment before original is rejected", run: () => expectError(() => new ResearchLab(new InMemoryResearchRepository(), new FixedClock()).amend(amendment("research:missing")), "RECORD_NOT_FOUND") },
  { name: "identical amendment is replayed", run: () => { const { lab, record } = setup(); const value = amendment(record.researchId); lab.amend(value); assertEqual(lab.amend(value).status, ResearchAppendStatus.Replayed, "replay"); } },
  { name: "self-referential amendment is rejected", run: () => { const { lab, record } = setup(); const value = amendment(record.researchId); expectError(() => lab.amend({ ...value, parentAmendmentId: value.amendmentId }), "cannot reference itself"); } },
  { name: "supersession creates a new linked record", run: () => { const { lab, record } = setup(); const next = addNext(lab, record.researchId); lab.supersede(supersession(record.researchId, next.researchId)); assertEqual(lab.get(record.researchId)?.status, ResearchStatus.Superseded, "prior"); assertEqual(next.supersedesResearchId, record.researchId, "link"); } },
  { name: "self-supersession is rejected", run: () => { const { lab, record } = setup(); expectError(() => lab.supersede(supersession(record.researchId, record.researchId)), "cannot supersede itself"); } },
  { name: "supersession requires the prior record", run: () => { const { lab, record } = setup(); expectError(() => lab.supersede(supersession("research:missing", record.researchId)), "RECORD_NOT_FOUND"); } },
  { name: "prior superseded research remains retrievable", run: () => { const { lab, record } = setup(); const next = addNext(lab, record.researchId); lab.supersede(supersession(record.researchId, next.researchId)); assertEqual(lab.get(record.researchId)?.researchId, record.researchId, "prior"); } },
  { name: "conflicting supersession is rejected", run: () => { const { lab, record } = setup(); const next = addNext(lab, record.researchId); lab.supersede(supersession(record.researchId, next.researchId)); expectError(() => lab.supersede({ ...supersession(record.researchId, next.researchId), supersessionId: `${record.researchId}:supersession:2` }), "INVALID_LIFECYCLE"); } },
  { name: "context and source references remain immutable", run: () => { const value = snapshot(); const { lab, record } = setup(value); (value.sources[0] as { title: string }).title = "Mutated"; assertEqual(lab.get(record.researchId)?.sources[0]?.title, "Synthetic dataset", "source"); } },
  { name: "fact inference and assumption are structurally distinct", run: () => { const { record } = setup(); assertDeepEqual(record.evidence.slice(0, 2).map((value) => value.classification), [ResearchObservationClassification.Fact, ResearchObservationClassification.Inference], "classification"); assertEqual(record.assumptions.length, 1, "assumption"); } },
  { name: "fact encoded as inference is rejected", run: () => { const value = snapshot(); expectError(() => setup(snapshot({ evidence: [{ ...value.evidence[0]!, classification: ResearchObservationClassification.Inference }, ...value.evidence.slice(1)] })), "FACT evidence"); } },
  { name: "counterevidence is preserved", run: () => assertEqual(setup().record.evidence.some((value) => value.evidenceType === ResearchEvidenceType.Counterevidence), true, "counterevidence") },
  { name: "scenario probabilities validate", run: () => { const value = snapshot(); expectError(() => setup(snapshot({ scenarios: [{ ...value.scenarios[0]!, probability: 101 }] })), "INVALID_PROBABILITY"); } },
  { name: "qualitative scenarios need no probability", run: () => { const value = snapshot(); const { probability: _probability, ...scenario } = value.scenarios[0]!; assertEqual(setup(snapshot({ scenarios: [scenario] })).record.scenarios[0]?.probability, undefined, "probability"); } },
  { name: "typed Prediction reference is preserved", run: () => assertEqual(setup().record.references.predictions[0]?.referenceId, "prediction-1", "prediction") },
  { name: "typed Journal reference is preserved", run: () => assertEqual(setup().record.references.journals[0]?.referenceId, "journal-1", "journal") },
  { name: "typed Strategy reference is preserved", run: () => assertEqual(setup().record.references.strategies[0]?.referenceId, "strategy-1", "strategy") },
  { name: "Historical Pattern reference is supported", run: () => assertEqual(setup().record.references.historicalPatterns[0]?.referenceId, "pattern-1", "pattern") },
  { name: "future-system reference is explicitly unresolved", run: () => assertEqual(setup().record.references.eventReplayTimelines[0]?.resolution, ResearchReferenceResolution.Unresolved, "resolution") },
  { name: "resolved reference without version is rejected", run: () => { const value = snapshot(); expectError(() => setup(snapshot({ references: { ...value.references, predictions: [{ referenceId: "prediction-1", recordType: ResearchReferenceType.Prediction, resolution: ResearchReferenceResolution.Resolved }] } })), "freeze a version"); } },
  { name: "ticker is optional for macro research", run: () => { const value = snapshot(); const { ticker: _ticker, asset: _asset, company: _company, ...rest } = value; assertEqual(setup({ ...rest, researchType: ResearchRecordType.Macro }).record.ticker, undefined, "ticker"); } },
  { name: "query by category works", run: () => assertEqual(setup().lab.query({ filter: { researchTypes: [ResearchRecordType.Stock] } }).length, 1, "count") },
  { name: "query by ticker works", run: () => assertEqual(setup().lab.query({ filter: { ticker: "ALPHA" } }).length, 1, "count") },
  { name: "query by sector and theme works", run: () => assertEqual(setup().lab.query({ filter: { sector: "Technology", theme: "Evidence discipline" } }).length, 1, "count") },
  { name: "query by prediction reference works", run: () => assertEqual(setup().lab.query({ filter: { predictionId: "prediction-1" } }).length, 1, "count") },
  { name: "query by journal reference works", run: () => assertEqual(setup().lab.query({ filter: { journalId: "journal-1" } }).length, 1, "count") },
  { name: "query by tags works", run: () => assertEqual(setup().lab.query({ filter: { tags: ["synthetic", "research"] } }).length, 1, "count") },
  { name: "query by date range works", run: () => assertEqual(setup().lab.query({ filter: { fromEventTimestamp: "2026-07-18T12:00:00.000Z", toEventTimestamp: "2026-07-18T14:00:00.000Z" } }).length, 1, "count") },
  { name: "related research query works", run: () => { const { lab, record } = setup(); const next = addNext(lab, record.researchId); assertEqual(lab.related(record.researchId)[0]?.researchId, next.researchId, "related"); } },
  { name: "current versus superseded query works", run: () => { const { lab, record } = setup(); const next = addNext(lab, record.researchId); lab.supersede(supersession(record.researchId, next.researchId)); assertDeepEqual(lab.query({ filter: { currentOnly: true } }).map((value) => value.researchId), [next.researchId], "current"); } },
  { name: "pagination is deterministic", run: () => { const { lab, record } = setup(); const next = addNext(lab, record.researchId); assertEqual(lab.query({ offset: 1, limit: 1 })[0]?.researchId, next.researchId, "page"); } },
  { name: "statistics are deterministic", run: () => { const { lab, record } = setup(); lab.review(review(record.researchId)); const first = lab.statistics(); assertDeepEqual(first, lab.statistics(), "stats"); assertEqual(first.assumptionCount, 1, "assumptions"); assertEqual(first.unresolvedQuestionCount, 1, "questions"); } },
  { name: "export ordering is deterministic", run: () => { const { repository } = setup(); const request = { exportId: "export-1", requestedAt: "2026-07-18T20:00:00.000Z", query: {}, format: ResearchExportFormat.Ndjson, destination: ResearchExportDestination.LocalSnapshot }; const policy = { allowExternalExports: false, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: [] }; assertEqual(exportResearch(repository, request, policy).content, exportResearch(repository, request, policy).content, "export"); } },
  { name: "LOCAL_ONLY export restriction is enforced", run: () => { const { repository } = setup(snapshot({ privacyLevel: PrivacyLevel.LocalOnly })); const result = exportResearch(repository, { exportId: "export-local", requestedAt: "2026-07-18T20:00:00.000Z", query: {}, format: ResearchExportFormat.Json, destination: ResearchExportDestination.ExternalTransfer }, { allowExternalExports: true, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: [] }); assertEqual(result.status, ResearchExportStatus.Rejected, "status"); } },
  { name: "SENSITIVE export authorization is enforced", run: () => { const { repository } = setup(snapshot({ privacyLevel: PrivacyLevel.Sensitive })); const request = { exportId: "export-sensitive", requestedAt: "2026-07-18T20:00:00.000Z", query: {}, format: ResearchExportFormat.Json, destination: ResearchExportDestination.ExternalTransfer }; const policy = { allowExternalExports: true, requireSensitiveAuthorization: true, sensitiveAuthorizationReferences: ["approval-1"] }; assertEqual(exportResearch(repository, request, policy).status, ResearchExportStatus.Rejected, "rejected"); assertEqual(exportResearch(repository, { ...request, sensitiveAuthorizationReference: "approval-1" }, policy).status, ResearchExportStatus.Exported, "allowed"); } },
  { name: "secret-bearing metadata is rejected", run: () => expectError(() => setup(snapshot({ metadata: { api_key: "forbidden" } })), "SECRET_METADATA") },
  { name: "malformed source reliability is rejected", run: () => { const value = snapshot(); expectError(() => setup(snapshot({ sources: [{ ...value.sources[0]!, reliabilityScore: 101 }] })), "INVALID_SOURCE"); } },
  { name: "corrupt truncated NDJSON fails closed", run: () => { const directory = mkdtempSync(join(tmpdir(), "research-corrupt-")); try { writeFileSync(join(directory, "research-lab-v1.ndjson"), "{}"); expectError(() => new LocalNdjsonResearchRepository(directory), "truncated"); } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "non-canonical NDJSON fails closed", run: () => { const directory = mkdtempSync(join(tmpdir(), "research-noncanonical-")); try { writeFileSync(join(directory, "research-lab-v1.ndjson"), '{"sequence":1,"schemaVersion":"1.0"}\n'); expectError(() => new LocalNdjsonResearchRepository(directory), "non-canonical"); } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "local repository reload preserves records", run: () => { const directory = mkdtempSync(join(tmpdir(), "research-reload-")); try { const repository = new LocalNdjsonResearchRepository(directory); const lab = new ResearchLab(repository, new FixedClock()); const record = lab.finalize(snapshot()).record; lab.amend(amendment(record.researchId)); assertEqual(new LocalNdjsonResearchRepository(directory).getResearchHistory(record.researchId)?.amendments.length, 1, "amendment"); } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "durable append does not rewrite prior history", run: () => { const directory = mkdtempSync(join(tmpdir(), "research-append-")); try { const repository = new LocalNdjsonResearchRepository(directory); const lab = new ResearchLab(repository, new FixedClock()); const record = lab.finalize(snapshot()).record; const before = readFileSync(repository.getStoragePath(), "utf8"); lab.amend(amendment(record.researchId)); const after = readFileSync(repository.getStoragePath(), "utf8"); assertTrue(after.startsWith(before) && after.length > before.length, "append-only"); } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "path traversal is rejected", run: () => { const directory = mkdtempSync(join(tmpdir(), "research-path-")); try { expectError(() => new LocalNdjsonResearchRepository(directory, "../escape"), "path traversal"); } finally { rmSync(directory, { recursive: true, force: true }); } } },
  { name: "inputs are not mutated", run: () => { const value = snapshot(); const before = JSON.stringify(value); setup(value); assertEqual(JSON.stringify(value), before, "input"); } },
  { name: "defensive copies are returned", run: () => { const { lab, record } = setup(); const read = lab.get(record.researchId) as ResearchRecord; (read as { title: string }).title = "Mutated"; assertTrue(lab.get(record.researchId)?.title !== "Mutated", "copy"); } },
  { name: "research-to-audit translation is deterministic", run: () => { const source: ResearchAuditRecord = { auditId: "research-audit-1", operationType: ResearchAuditOperationType.Finalized, sourceRecordId: "research-source-1", researchId: "research-1", researchVersion: "v1", timestamp: "2026-07-18T20:00:00.000Z", status: "FINALIZED", reasonCodes: ["RESEARCH_FINALIZED"], evidenceReferences: ["evidence-1"], privacyLevel: PrivacyLevel.Internal, retention: AIAuditRetentionClassification.Permanent, correlationId: "correlation-1", traceId: "trace-1", policyVersions: { research: "v1" }, metadata: { category: "stock" } }; const context = { idempotencyKey: "research-audit-idempotency-1", actor: { type: AIAuditActorType.Owner, actorId: "owner-1" }, parentAuditRecordIds: [], relatedAuditRecordIds: [] }; const first = auditRecordFromResearch(source, context); assertDeepEqual(first, auditRecordFromResearch(source, context), "translation"); assertEqual(first.recordType, AIAuditRecordType.ResearchRecord, "type"); assertEqual(first.sourceSubsystem, AIAuditSourceSubsystem.Research, "subsystem"); } },
  { name: "Prediction evidence freezes version status conclusion and confidence", run: () => { const { lab, record } = setup(); const result = lab.predictionEvidence(record.researchId, { required: true, rejectNonFinalized: true }); assertEqual(result.reference?.researchVersion, "v1", "version"); assertEqual(result.reference?.confidenceScore, 72, "confidence"); } },
  { name: "missing required research rejects prediction evidence", run: () => assertEqual(new ResearchLab(new InMemoryResearchRepository(), new FixedClock()).predictionEvidence(undefined, { required: true, rejectNonFinalized: true }).accepted, false, "accepted") },
  { name: "Prediction Log source records are not mutated", run: () => { const prediction = { predictionId: "prediction-1", status: "LOCKED" }; const before = JSON.stringify(prediction); setup(snapshot({ references: { ...references(), predictions: [{ referenceId: prediction.predictionId, recordType: ResearchReferenceType.Prediction, resolution: ResearchReferenceResolution.Resolved, version: "v1" }] } })); assertEqual(JSON.stringify(prediction), before, "prediction"); } },
  { name: "Alpha Journal source records are not mutated", run: () => { const journal = { entryId: "journal-1", status: "FINALIZED" }; const before = JSON.stringify(journal); setup(); assertEqual(JSON.stringify(journal), before, "journal"); } },
];

let passed = 0;
for (const test of tests) { try { test.run(); passed += 1; } catch (error: unknown) { const message = error instanceof Error ? error.message : String(error); console.error(`FAIL: ${test.name}: ${message}`); throw error; } }
console.log(`Research Lab: ${String(passed)}/${String(tests.length)} tests passed.`);
