import {
  EVENT_ANALYZER_CANDLE_SERIES_SCHEMA_VERSION,
  EVENT_ANALYZER_INSTRUMENT_ID,
  EVENT_ANALYZER_MAX_ATOMIC_DIGITS,
  EVENT_ANALYZER_SCHEMA_VERSION,
  EventAnalyzerAuthorizationStatus,
  EventAnalyzerCandleEvidenceQuality,
  EventAnalyzerCandleInterval,
  EventAnalyzerContradictionFlag,
  EventAnalyzerDerivedMomentum,
  EventAnalyzerEventType,
  EventAnalyzerFeatureStatus,
  EventAnalyzerProfitabilityStatus,
  EventAnalyzerRangeExpansion,
  EventAnalyzerReasonCode,
  EventAnalyzerRecommendation,
  EventAnalyzerReversalRisk,
  EventAnalyzerValidationIssueCode,
  EventAnalyzerVolumeConfirmation,
  EventContractSide,
  EventMarketPriceComparison,
  RecentMomentumClassification,
  type EventAnalyzerCandleSeries,
  type EventAnalyzerInput,
  type EventAnalyzerPolicy,
} from "../../contracts/EventAnalyzer";
import { EVENT_ANALYZER_HELP, parseEventAnalyzerArguments, parseEventAnalyzerCandleFile, runEventAnalyzerConsole } from "./EventAnalyzerConsole";
import { DEFAULT_EVENT_ANALYZER_POLICY, EventAnalyzerEngine, EventAnalyzerValidationError, validateEventAnalyzerInput, validateEventAnalyzerPolicy } from "./EventAnalyzerEngine";

function assertEqual<T>(actual: T, expected: T, label: string): void { if (actual !== expected) throw new Error(`${label}: expected ${String(expected)}, received ${String(actual)}.`); }
function assertTrue(value: boolean, label: string): void { if (!value) throw new Error(`${label}: expected true.`); }
function assertDeepEqual(actual: unknown, expected: unknown, label: string): void { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(`${label}: values differ.`); }
function assertFiniteTree(value: unknown, label: string): void { if (typeof value === "number") { if (!Number.isFinite(value) || !Number.isSafeInteger(value)) throw new Error(`${label}: unsafe number.`); return; } if (Array.isArray(value)) { value.forEach((entry) => assertFiniteTree(entry, label)); return; } if (typeof value === "object" && value !== null) Object.values(value).forEach((entry) => assertFiniteTree(entry, label)); }
function expectIssue(value: unknown, code: EventAnalyzerValidationIssueCode): void { if (!validateEventAnalyzerInput(value).some((entry) => entry.code === code)) throw new Error(`Expected ${code}.`); }
function expectPolicyIssue(value: unknown): void { if (!validateEventAnalyzerPolicy(value).some((entry) => entry.code === EventAnalyzerValidationIssueCode.InvalidPolicy)) throw new Error("Expected invalid policy."); }
function expectThrow(run: () => unknown): void { try { run(); } catch { return; } throw new Error("Expected an error."); }

const engine = new EventAnalyzerEngine();
function legacyInput(overrides: Partial<EventAnalyzerInput> = {}): EventAnalyzerInput { return { schemaVersion: EVENT_ANALYZER_SCHEMA_VERSION, eventType: EventAnalyzerEventType.BtcFifteenMinute, eventId: "event:btc-15m:20260721-1445", instrumentId: EVENT_ANALYZER_INSTRUMENT_ID, observationTime: "2026-07-21T14:36:00.000Z", currentPriceSourceId: "source:owner-fixture", currentPriceSourceRecordId: "source-record:btc:20260721-1436", currentPriceObservationId: "observation:btc:20260721-1436", contractSide: EventContractSide.Up, targetPrice: { atomicValue: "10000000", scale: 2 }, currentPrice: { atomicValue: "10100000", scale: 2 }, marketPriceBasisPoints: 5_000, remainingSeconds: 450, recentMomentum: RecentMomentumClassification.Up, ...overrides }; }
function candleInput(series: EventAnalyzerCandleSeries = bullishSeries(), overrides: Partial<EventAnalyzerInput> = {}): EventAnalyzerInput { return { ...legacyInput({ currentPrice: series.candles.at(-1)!.close }), candleSeries: series, ...overrides }; }
function policy(overrides: Partial<EventAnalyzerPolicy> = {}): EventAnalyzerPolicy { return { ...DEFAULT_EVENT_ANALYZER_POLICY, ...overrides }; }

function rawSeries(closes: readonly string[], volumes: readonly (string | null)[], options: { ranges?: readonly number[]; opens?: readonly string[] } = {}): Record<string, unknown> {
  return {
    schemaVersion: EVENT_ANALYZER_CANDLE_SERIES_SCHEMA_VERSION,
    interval: EventAnalyzerCandleInterval.OneMinute,
    timestampSemantics: "INTERVAL_START",
    eventId: "event:btc-15m:20260721-1445",
    instrumentId: EVENT_ANALYZER_INSTRUMENT_ID,
    asOfTime: "2026-07-21T14:36:00.000Z",
    provenance: {
      sourceId: "source:owner-fixture",
      sourceRecordId: "source-record:btc:20260721-1436",
      observationId: "observation:btc:20260721-1436",
    },
    candles: closes.map((close, index) => {
      const open = options.opens?.[index] ?? (index === 0 ? close : closes[index - 1]!);
      const range = options.ranges?.[index] ?? 20;
      const high = (Math.max(Number(open), Number(close)) + range / 2).toFixed(2);
      const low = (Math.min(Number(open), Number(close)) - range / 2).toFixed(2);
      return { timestamp: `2026-07-21T14:${String(30 + index).padStart(2, "0")}:00.000Z`, open, high, low, close, volume: volumes[index] ?? null };
    }),
  };
}

function bullishSeries(): EventAnalyzerCandleSeries { return parseEventAnalyzerCandleFile(rawSeries(["100000.00", "100100.00", "100220.00", "100360.00", "100530.00", "100740.00"], ["100", "105", "110", "120", "160", "220"], { ranges: [40, 42, 45, 48, 65, 90] })); }
function bearishSeries(): EventAnalyzerCandleSeries { return parseEventAnalyzerCandleFile(rawSeries(["100740.00", "100600.00", "100440.00", "100250.00", "100020.00", "99740.00"], ["100", "105", "110", "130", "180", "250"], { ranges: [40, 42, 45, 55, 75, 105] })); }
function reversalDownSeries(): EventAnalyzerCandleSeries { return parseEventAnalyzerCandleFile(rawSeries(["66590.00", "66620.00", "66650.00", "66660.00", "66635.00", "66607.57"], ["100", "110", "120", "130", "180", "260"], { ranges: [25, 35, 40, 22, 2, 4], opens: ["66575.00", "66590.00", "66620.00", "66650.00", "66660.00", "66635.00"] })); }
function reversalUpSeries(): EventAnalyzerCandleSeries { return parseEventAnalyzerCandleFile(rawSeries(["66700.00", "66670.00", "66640.00", "66630.00", "66655.00", "66685.00"], ["100", "110", "120", "130", "180", "260"], { ranges: [25, 35, 40, 22, 34, 42], opens: ["66715.00", "66700.00", "66670.00", "66640.00", "66630.00", "66655.00"] })); }
function neutralSeries(): EventAnalyzerCandleSeries { return parseEventAnalyzerCandleFile(rawSeries(["100000.00", "100020.00", "99980.00", "100015.00", "99985.00", "100005.00"], [null, null, null, null, null, null], { ranges: [40, 45, 50, 45, 50, 45] })); }
function changed(series: EventAnalyzerCandleSeries, update: (draft: Record<string, unknown> & { candles: Array<Record<string, unknown>> }) => void): EventAnalyzerCandleSeries { const draft = JSON.parse(JSON.stringify(series)) as Record<string, unknown> & { candles: Array<Record<string, unknown>> }; update(draft); return draft as unknown as EventAnalyzerCandleSeries; }

const tests: ReadonlyArray<readonly [string, () => void]> = [
  ["v2 policy is immutable and versioned", () => { assertTrue(Object.isFrozen(DEFAULT_EVENT_ANALYZER_POLICY), "policy"); assertEqual(DEFAULT_EVENT_ANALYZER_POLICY.version, "2.0", "version"); }],
  ["legacy input remains analyzable", () => { const result = engine.analyze(legacyInput()); assertEqual(result.eventType, EventAnalyzerEventType.BtcFifteenMinute, "event"); assertEqual(result.candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.LegacyCoarse, "quality"); }],
  ["legacy momentum-only advantage fails closed", () => { const result = engine.analyze(legacyInput()); assertEqual(result.recommendation, EventAnalyzerRecommendation.NoTrade, "recommendation"); assertTrue(result.reasonCodes.includes(EventAnalyzerReasonCode.LegacyCoarseEvidence), "reason"); }],
  ["YES and UP use equal selected probability", () => assertEqual(engine.analyze(candleInput(bullishSeries(), { contractSide: EventContractSide.Yes })).probabilityEstimate.basisPoints, engine.analyze(candleInput(bullishSeries(), { contractSide: EventContractSide.Up })).probabilityEstimate.basisPoints, "positive")],
  ["NO and DOWN invert UP probability", () => { const up = engine.analyze(candleInput()).probabilityEstimate.basisPoints; const down = engine.analyze(candleInput(bullishSeries(), { contractSide: EventContractSide.Down })).probabilityEstimate.basisPoints; assertEqual(up + down, 10_000, "inverse"); }],
  ["target distance remains deterministic", () => { const above = engine.analyze(legacyInput({ recentMomentum: RecentMomentumClassification.Flat })).upProbabilityBasisPoints; const at = engine.analyze(legacyInput({ currentPrice: legacyInput().targetPrice, recentMomentum: RecentMomentumClassification.Flat })).upProbabilityBasisPoints; assertTrue(above > at, "distance"); }],
  ["coarse momentum still affects legacy estimate", () => { const up = engine.analyze(legacyInput({ recentMomentum: RecentMomentumClassification.Up })).upProbabilityBasisPoints; const down = engine.analyze(legacyInput({ recentMomentum: RecentMomentumClassification.Down })).upProbabilityBasisPoints; assertTrue(up > down, "coarse estimate"); }],
  ["strong bullish continuation increases UP probability", () => { const bullish = bullishSeries(); const neutral = neutralSeries(); const candle = engine.analyze(candleInput(bullish, { targetPrice: bullish.candles.at(-1)!.close })); const baseline = engine.analyze(candleInput(neutral, { targetPrice: neutral.candles.at(-1)!.close })); assertTrue(candle.upProbabilityBasisPoints > baseline.upProbabilityBasisPoints, "bullish increase"); assertEqual(candle.candleAnalysis.derivedMomentum, EventAnalyzerDerivedMomentum.StrongUp, "momentum"); }],
  ["strong bearish continuation decreases UP probability", () => { const bearish = bearishSeries(); const neutral = neutralSeries(); const result = engine.analyze(candleInput(bearish, { targetPrice: bearish.candles.at(-1)!.close })); const baseline = engine.analyze(candleInput(neutral, { targetPrice: neutral.candles.at(-1)!.close })); assertTrue(result.upProbabilityBasisPoints < baseline.upProbabilityBasisPoints, "bearish decrease"); assertEqual(result.candleAnalysis.derivedMomentum, EventAnalyzerDerivedMomentum.StrongDown, "momentum"); }],
  ["candle contribution remains conservatively bounded", () => { const bullish = bullishSeries(); const result = engine.analyze(candleInput(bullish, { targetPrice: bullish.candles.at(-1)!.close })); assertTrue(result.upProbabilityBasisPoints <= 6_600, "bounded contribution"); }],
  ["probability remains inside conservative policy bounds", () => { const high = engine.analyze(candleInput(bullishSeries(), { targetPrice: { atomicValue: "5000000", scale: 2 }, remainingSeconds: 1 })); const low = engine.analyze(candleInput(bearishSeries(), { targetPrice: { atomicValue: "20000000", scale: 2 }, remainingSeconds: 1 })); assertTrue(high.upProbabilityBasisPoints <= 9_000 && low.upProbabilityBasisPoints >= 1_000, "bounds"); }],
  ["fair value and edge remain explicit", () => { const result = engine.analyze(candleInput()); assertEqual(result.valueComparison.fairValueBasisPoints, result.probabilityEstimate.basisPoints, "fair"); assertEqual(result.edge.basisPoints, result.probabilityEstimate.basisPoints - result.valueComparison.marketPriceBasisPoints, "edge"); }],
  ["market comparison remains deterministic", () => { const result = engine.analyze(candleInput()); const fair = engine.analyze(candleInput(bullishSeries(), { marketPriceBasisPoints: result.probabilityEstimate.basisPoints })); assertEqual(fair.valueComparison.comparison, EventMarketPriceComparison.Fair, "fair comparison"); }],
  ["BUY requires sufficient candle evidence and edge", () => { const result = engine.analyze(candleInput()); assertEqual(result.candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Sufficient, "quality"); assertEqual(result.recommendation, EventAnalyzerRecommendation.Buy, "buy"); }],
  ["small positive edge produces HOLD with sufficient evidence", () => { const probability = engine.analyze(candleInput()).probabilityEstimate.basisPoints; assertEqual(engine.analyze(candleInput(bullishSeries(), { marketPriceBasisPoints: probability - 100 })).recommendation, EventAnalyzerRecommendation.Hold, "hold"); }],
  ["non-positive edge produces NO TRADE", () => { const probability = engine.analyze(candleInput()).probabilityEstimate.basisPoints; assertEqual(engine.analyze(candleInput(bullishSeries(), { marketPriceBasisPoints: probability })).recommendation, EventAnalyzerRecommendation.NoTrade, "no trade"); }],
  ["high probability alone cannot produce BUY", () => assertEqual(engine.analyze(candleInput(bullishSeries(), { targetPrice: { atomicValue: "5000000", scale: 2 }, marketPriceBasisPoints: 9_500 })).recommendation, EventAnalyzerRecommendation.NoTrade, "no trade")],
  ["market price above policy blocks BUY", () => { const result = engine.analyze(candleInput(bullishSeries(), { targetPrice: { atomicValue: "5000000", scale: 2 }, marketPriceBasisPoints: 8_600 })); assertEqual(result.recommendation, EventAnalyzerRecommendation.NoTrade, "no trade"); assertTrue(result.reasonCodes.includes(EventAnalyzerReasonCode.MarketPriceAbovePolicy), "reason"); }],
  ["too little time blocks BUY", () => assertEqual(engine.analyze(candleInput(bullishSeries(), { remainingSeconds: 30 })).recommendation, EventAnalyzerRecommendation.NoTrade, "no trade")],
  ["up-to-down reversal blocks BUY UP", () => { const result = engine.analyze(candleInput(reversalDownSeries(), { targetPrice: { atomicValue: "6662197", scale: 2 }, currentPrice: { atomicValue: "6660757", scale: 2 }, remainingSeconds: 842, marketPriceBasisPoints: 4_500, recentMomentum: RecentMomentumClassification.Up })); assertEqual(result.candleAnalysis.reversalRisk, EventAnalyzerReversalRisk.UpToDown, "reversal"); assertEqual(result.recommendation, EventAnalyzerRecommendation.NoTrade, "no trade"); }],
  ["down-to-up reversal blocks unjustified BUY DOWN", () => { const result = engine.analyze(candleInput(reversalUpSeries(), { contractSide: EventContractSide.Down, targetPrice: { atomicValue: "6665000", scale: 2 }, currentPrice: { atomicValue: "6668500", scale: 2 }, marketPriceBasisPoints: 3_000, recentMomentum: RecentMomentumClassification.Down })); assertEqual(result.candleAnalysis.reversalRisk, EventAnalyzerReversalRisk.DownToUp, "reversal"); assertEqual(result.recommendation, EventAnalyzerRecommendation.NoTrade, "no trade"); }],
  ["consecutive bearish candles are counted", () => assertEqual(engine.analyze(candleInput(reversalDownSeries())).candleAnalysis.consecutiveBearishCount, 2, "bearish count")],
  ["consecutive bullish candles are counted", () => assertEqual(engine.analyze(candleInput(bullishSeries())).candleAnalysis.consecutiveBullishCount, 5, "bullish count")],
  ["bullish and bearish candle totals are exposed", () => { const result = engine.analyze(candleInput(reversalDownSeries())).candleAnalysis; assertEqual(result.bullishCandleCount, 4, "bullish"); assertEqual(result.bearishCandleCount, 2, "bearish"); }],
  ["body pressure is fixed-decimal and complementary", () => { const result = engine.analyze(candleInput(bearishSeries())).candleAnalysis; assertEqual((result.bullishBodyPressureBasisPoints ?? 0) + (result.bearishBodyPressureBasisPoints ?? 0), 10_000, "pressure"); }],
  ["range expansion is deterministic", () => assertEqual(engine.analyze(candleInput(bullishSeries())).candleAnalysis.recentRangeExpansion, EventAnalyzerRangeExpansion.Expanding, "range")],
  ["downside acceleration is detected", () => assertEqual(engine.analyze(candleInput(bearishSeries())).candleAnalysis.downsideAcceleration, EventAnalyzerFeatureStatus.Confirmed, "downside")],
  ["upside acceleration is detected", () => assertEqual(engine.analyze(candleInput(bullishSeries())).candleAnalysis.upsideAcceleration, EventAnalyzerFeatureStatus.Confirmed, "upside")],
  ["bullish relative volume confirmation is deterministic", () => assertEqual(engine.analyze(candleInput(bullishSeries())).candleAnalysis.volumeConfirmation, EventAnalyzerVolumeConfirmation.Bullish, "volume")],
  ["bearish relative volume confirmation is deterministic", () => assertEqual(engine.analyze(candleInput(bearishSeries())).candleAnalysis.volumeConfirmation, EventAnalyzerVolumeConfirmation.Bearish, "volume")],
  ["missing volume creates no invented confirmation", () => assertEqual(engine.analyze(candleInput(neutralSeries())).candleAnalysis.volumeConfirmation, EventAnalyzerVolumeConfirmation.Unavailable, "volume")],
  ["recent short and medium returns are exposed", () => { const result = engine.analyze(candleInput(bullishSeries())).candleAnalysis; assertTrue((result.shortReturnBasisPoints ?? 0) > 0 && (result.mediumReturnBasisPoints ?? 0) > 0 && (result.recentReturnBasisPoints ?? 0) > 0, "returns"); }],
  ["duplicate timestamps fail closed", () => { const series = changed(bullishSeries(), (draft) => { draft.candles[1]!["timestamp"] = draft.candles[0]!["timestamp"]; }); const result = engine.analyze(candleInput(series)); assertEqual(result.candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); assertEqual(result.recommendation, EventAnalyzerRecommendation.NoTrade, "no trade"); }],
  ["out-of-order timestamps fail closed", () => { const series = changed(bullishSeries(), (draft) => { draft.candles[2]!["timestamp"] = "2026-07-21T14:30:30.000Z"; }); assertEqual(engine.analyze(candleInput(series)).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); }],
  ["future timestamps fail closed", () => { const series = changed(bullishSeries(), (draft) => { draft.asOfTime = "2026-07-21T14:33:00.000Z"; }); assertEqual(engine.analyze(candleInput(series)).recommendation, EventAnalyzerRecommendation.NoTrade, "no trade"); }],
  ["stale final candle is invalid and cannot BUY", () => { const series = changed(bullishSeries(), (draft) => { draft["asOfTime"] = "2026-07-21T14:37:00.000Z"; }); const result = engine.analyze(candleInput(series, { observationTime: "2026-07-21T14:37:00.000Z" })); assertEqual(result.candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); assertEqual(result.recommendation, EventAnalyzerRecommendation.NoTrade, "recommendation"); }],
  ["missing final interval is invalid", () => { const series = changed(bullishSeries(), (draft) => { draft.candles[5]!["timestamp"] = "2026-07-21T14:34:00.000Z"; }); assertEqual(engine.analyze(candleInput(series)).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); }],
  ["current price must equal latest close", () => { const result = engine.analyze(candleInput(bullishSeries(), { currentPrice: { atomicValue: "10074100", scale: 2 } })); assertEqual(result.candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); assertTrue(result.candleAnalysis.issues.some((entry) => entry.code === EventAnalyzerValidationIssueCode.CurrentPriceMismatch), "mismatch issue"); assertEqual(result.recommendation, EventAnalyzerRecommendation.NoTrade, "recommendation"); }],
  ["scale-equivalent current price equals latest close", () => { const result = engine.analyze(candleInput(bullishSeries(), { currentPrice: { atomicValue: "1007400", scale: 1 } })); assertEqual(result.candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Sufficient, "quality"); }],
  ["different instrument identity is invalid", () => { const series = changed(bullishSeries(), (draft) => { draft["instrumentId"] = "instrument:crypto:eth-usd"; }); assertEqual(engine.analyze(candleInput(series)).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); }],
  ["different event identity is invalid", () => { const series = changed(bullishSeries(), (draft) => { draft["eventId"] = "event:btc-15m:other"; }); assertEqual(engine.analyze(candleInput(series)).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); }],
  ["missing provenance is invalid", () => { const series = changed(bullishSeries(), (draft) => { delete draft["provenance"]; }); assertEqual(engine.analyze(candleInput(series)).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); }],
  ["mismatched current-price source identity is invalid", () => assertEqual(engine.analyze(candleInput(bullishSeries(), { currentPriceSourceId: "source:other" })).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality")],
  ["mismatched current-price source-record identity is invalid", () => assertEqual(engine.analyze(candleInput(bullishSeries(), { currentPriceSourceRecordId: "source-record:btc:other" })).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality")],
  ["mismatched observation identity is invalid", () => { const series = changed(bullishSeries(), (draft) => { (draft["provenance"] as Record<string, unknown>)["observationId"] = "observation:btc:other"; }); assertEqual(engine.analyze(candleInput(series)).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); }],
  ["final candle is the immediately preceding completed interval", () => { const result = engine.analyze(candleInput(bullishSeries())); assertEqual(result.candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Sufficient, "quality"); assertEqual(bullishSeries().candles.at(-1)!.timestamp, "2026-07-21T14:35:00.000Z", "final interval start"); }],
  ["valid complete chronological provenance-bound series is accepted", () => assertEqual(engine.analyze(candleInput(bullishSeries())).candleAnalysis.candleCount, 6, "count")],
  ["unsupported candle interval fails closed", () => { const series = changed(bullishSeries(), (draft) => { draft.interval = "PT5M"; }); assertEqual(engine.analyze(candleInput(series)).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); }],
  ["invalid OHLC relationships fail closed", () => { const series = changed(bullishSeries(), (draft) => { draft.candles[0]!["high"] = { atomicValue: "1", scale: 2 }; }); assertEqual(engine.analyze(candleInput(series)).recommendation, EventAnalyzerRecommendation.NoTrade, "no trade"); }],
  ["negative volume fails closed", () => { const series = changed(bullishSeries(), (draft) => { draft.candles[0]!["volume"] = { atomicValue: "-1", scale: 0 }; }); assertEqual(engine.analyze(candleInput(series)).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); }],
  ["excessive atomic digit count is rejected", () => { const series = changed(bullishSeries(), (draft) => { draft.candles[0]!["open"] = { atomicValue: "1".repeat(EVENT_ANALYZER_MAX_ATOMIC_DIGITS + 1), scale: 0 }; }); assertEqual(engine.analyze(candleInput(series)).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); }],
  ["maximum atomic digit boundary is accepted", () => { const atomic = "9".repeat(EVENT_ANALYZER_MAX_ATOMIC_DIGITS); const series = changed(bullishSeries(), (draft) => { for (const candle of draft.candles) for (const field of ["open", "high", "low", "close"]) candle[field] = { atomicValue: atomic, scale: 0 }; }); const result = engine.analyze(candleInput(series, { currentPrice: { atomicValue: atomic, scale: 0 }, targetPrice: { atomicValue: atomic, scale: 0 } })); assertEqual(result.candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Sufficient, "quality"); }],
  ["one atomic digit beyond the boundary is rejected in core input", () => expectIssue(legacyInput({ currentPrice: { atomicValue: "9".repeat(EVENT_ANALYZER_MAX_ATOMIC_DIGITS + 1), scale: 0 } }), EventAnalyzerValidationIssueCode.InvalidPrice)],
  ["excessive decimal scale is rejected", () => { const series = changed(bullishSeries(), (draft) => { draft.candles[0]!["close"] = { atomicValue: "100000", scale: 9 }; }); assertEqual(engine.analyze(candleInput(series)).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); }],
  ["unsafe bigint conversion becomes INVALID evidence", () => { const atomic = "9".repeat(EVENT_ANALYZER_MAX_ATOMIC_DIGITS); const series = changed(bullishSeries(), (draft) => { for (const field of ["open", "high", "low", "close"]) draft.candles[0]![field] = { atomicValue: "1", scale: 0 }; for (let index = 1; index < draft.candles.length; index += 1) for (const field of ["open", "high", "low", "close"]) draft.candles[index]![field] = { atomicValue: atomic, scale: 0 }; }); const result = engine.analyze(candleInput(series, { currentPrice: { atomicValue: atomic, scale: 0 }, targetPrice: { atomicValue: atomic, scale: 0 } })); assertEqual(result.candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); assertTrue(result.candleAnalysis.issues.some((entry) => entry.code === EventAnalyzerValidationIssueCode.UnsafeNumericValue), "unsafe issue"); }],
  ["scale-normalization unsafe boundary fails closed", () => { const atomic = "9".repeat(EVENT_ANALYZER_MAX_ATOMIC_DIGITS); const series = changed(bullishSeries(), (draft) => { for (const field of ["open", "high", "low", "close"]) draft.candles[0]![field] = { atomicValue: "1", scale: 8 }; for (let index = 1; index < draft.candles.length; index += 1) for (const field of ["open", "high", "low", "close"]) draft.candles[index]![field] = { atomicValue: atomic, scale: 0 }; }); assertEqual(engine.analyze(candleInput(series, { currentPrice: { atomicValue: atomic, scale: 0 }, targetPrice: { atomicValue: atomic, scale: 0 } })).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); }],
  ["zero-range candles remain finite and complementary", () => { const series = changed(bullishSeries(), (draft) => { for (const candle of draft.candles) { const close = candle["close"]; candle["open"] = close; candle["high"] = close; candle["low"] = close; } }); const result = engine.analyze(candleInput(series)); assertEqual((result.candleAnalysis.bullishBodyPressureBasisPoints ?? 0) + (result.candleAnalysis.bearishBodyPressureBasisPoints ?? 0), 10_000, "pressure"); assertFiniteTree(result, "finite"); }],
  ["uneven body division remains exactly complementary", () => { const series = parseEventAnalyzerCandleFile(rawSeries(["100.01", "100.00", "100.01", "100.00", "100.01", "100.00"], ["1", "1", "1", "1", "1", "1"], { opens: ["100.00", "100.02", "100.00", "100.02", "100.00", "100.02"] })); const analysis = engine.analyze(candleInput(series)).candleAnalysis; assertEqual((analysis.bullishBodyPressureBasisPoints ?? 0) + (analysis.bearishBodyPressureBasisPoints ?? 0), 10_000, "pressure"); assertEqual(analysis.bullishBodyPressureBasisPoints, 3_333, "authoritative rounded share"); }],
  ["all numeric output remains finite safe integers", () => assertFiniteTree(engine.analyze(candleInput(bullishSeries())), "finite output")],
  ["too few candles are insufficient and NO TRADE", () => { const series = changed(bullishSeries(), (draft) => { draft.candles = draft.candles.slice(0, 4); draft["asOfTime"] = "2026-07-21T14:34:00.000Z"; }); const result = engine.analyze(candleInput(series, { observationTime: "2026-07-21T14:34:00.000Z" })); assertEqual(result.candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Insufficient, "quality"); assertEqual(result.recommendation, EventAnalyzerRecommendation.NoTrade, "no trade"); }],
  ["too many candles are rejected", () => { const base = JSON.parse(JSON.stringify(bullishSeries())) as { schemaVersion: string; interval: string; asOfTime: string; candles: Array<Record<string, unknown>> }; base.candles = Array.from({ length: 31 }, (_, index) => ({ timestamp: `2026-07-21T${String(Math.trunc(index / 60)).padStart(2, "0")}:${String(index % 60).padStart(2, "0")}:00.000Z`, open: { atomicValue: "10000", scale: 2 }, high: { atomicValue: "10100", scale: 2 }, low: { atomicValue: "9900", scale: 2 }, close: { atomicValue: "10000", scale: 2 }, volume: { atomicValue: "1", scale: 0 } })); base.asOfTime = "2026-07-21T01:00:00.000Z"; assertEqual(engine.analyze(candleInput(base as unknown as EventAnalyzerCandleSeries)).candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Invalid, "quality"); }],
  ["candle-derived momentum overrides coarse UP", () => { const result = engine.analyze(candleInput(bearishSeries(), { recentMomentum: RecentMomentumClassification.Up })); assertEqual(result.candleAnalysis.derivedMomentum, EventAnalyzerDerivedMomentum.StrongDown, "derived"); assertTrue(result.reasonCodes.includes(EventAnalyzerReasonCode.CandleMomentumOverridesCoarse), "override"); }],
  ["candle-only input needs no coarse momentum", () => { const base = candleInput(); const { recentMomentum: _removed, ...withoutMomentum } = base; const result = engine.analyze(withoutMomentum); assertEqual(result.recentMomentum, "NOT_SUPPLIED", "coarse status"); assertEqual(result.candleAnalysis.evidenceQuality, EventAnalyzerCandleEvidenceQuality.Sufficient, "quality"); }],
  ["small target distance plus unstable structure blocks trading", () => { const neutral = neutralSeries(); const result = engine.analyze(candleInput(neutral, { targetPrice: neutral.candles.at(-1)!.close })); assertTrue(result.candleAnalysis.contradictionFlags.includes(EventAnalyzerContradictionFlag.TargetDistanceSmallRelativeToVolatility), "flag"); assertEqual(result.recommendation, EventAnalyzerRecommendation.NoTrade, "no trade"); }],
  ["identical candle input produces identical fingerprint and output", () => { const source = candleInput(); const first = engine.analyze(source); const second = engine.analyze(source); assertEqual(first.inputFingerprint, second.inputFingerprint, "fingerprint"); assertDeepEqual(first, second, "output"); }],
  ["input and output are deeply immutable", () => { const source = candleInput(); const before = JSON.stringify(source); const result = engine.analyze(source); assertEqual(JSON.stringify(source), before, "source"); assertTrue(Object.isFrozen(result) && Object.isFrozen(result.candleAnalysis) && Object.isFrozen(result.candleAnalysis.contradictionFlags), "freeze"); }],
  ["risk output preserves prediction-profitability separation", () => { const result = engine.analyze(candleInput()); assertEqual(result.profitabilityStatus, EventAnalyzerProfitabilityStatus.NotEvaluated, "profitability"); assertEqual(result.authorizationStatus, EventAnalyzerAuthorizationStatus.PrototypeOnly, "authorization"); assertTrue(result.riskExplanation.some((value) => value.includes("uncalibrated")), "warning"); }],
  ["invalid core input still throws deterministic validation", () => { expectIssue(legacyInput({ targetPrice: { atomicValue: "0", scale: 2 } }), EventAnalyzerValidationIssueCode.InvalidPrice); expectIssue(legacyInput({ marketPriceBasisPoints: 10_000 }), EventAnalyzerValidationIssueCode.InvalidMarketPrice); }],
  ["remaining time above event duration is rejected", () => { try { engine.analyze(legacyInput({ remainingSeconds: 901 })); } catch (error) { assertTrue(error instanceof EventAnalyzerValidationError, "error"); return; } throw new Error("Expected error."); }],
  ["invalid policy fails closed", () => { expectPolicyIssue(policy({ minimumCandleCount: 4 })); expectPolicyIssue(policy({ eventDurationSeconds: 600 })); expectThrow(() => new EventAnalyzerEngine(policy({ probabilityFloorBasisPoints: 9_000, probabilityCeilingBasisPoints: 1_000 }))); }],
  ["validation issues have stable ordering", () => { const issues = validateEventAnalyzerInput({}); assertDeepEqual(issues, [...issues].sort((a, b) => a.code.localeCompare(b.code) || a.field.localeCompare(b.field) || a.message.localeCompare(b.message)), "order"); }],
  ["legacy console command remains available but returns NO TRADE", () => { const output = runEventAnalyzerConsole(consoleArgs()); assertEqual((JSON.parse(output) as { recommendation: string }).recommendation, EventAnalyzerRecommendation.NoTrade, "recommendation"); }],
  ["console parses candle file with injected local loader", () => { const parsed = parseEventAnalyzerArguments(candleConsoleArgs(), () => rawSeries(["100000.00", "100100.00", "100220.00", "100360.00", "100530.00", "100740.00"], ["100", "105", "110", "120", "160", "220"])); assertEqual(parsed.candleSeries?.candles.length, 6, "candles"); }],
  ["console accepts candle file without coarse momentum", () => { const parsed = parseEventAnalyzerArguments(candleConsoleArgs(), () => rawSeries(["100000.00", "100100.00", "100220.00", "100360.00", "100530.00"], ["100", "105", "110", "120", "160"])); assertEqual(parsed.recentMomentum, undefined, "momentum"); }],
  ["console rejects undeclared candle-file fields", () => expectThrow(() => parseEventAnalyzerArguments(candleConsoleArgs(), () => ({ ...rawSeries(["100000.00", "100100.00", "100220.00", "100360.00", "100530.00"], ["100", "105", "110", "120", "160"]), providerPayload: {} })))],
  ["console requires a loader for candle files", () => expectThrow(() => parseEventAnalyzerArguments(candleConsoleArgs()))],
  ["console rejects missing duplicate and unknown arguments", () => { expectThrow(() => parseEventAnalyzerArguments(consoleArgs().slice(1))); expectThrow(() => parseEventAnalyzerArguments([...consoleArgs(), "--poll=true"])); expectThrow(() => parseEventAnalyzerArguments([...consoleArgs(), "--momentum=DOWN"])); }],
  ["help documents candle file and legacy behavior", () => { assertTrue(EVENT_ANALYZER_HELP.includes("--candles-file") && EVENT_ANALYZER_HELP.includes("NO_TRADE"), "help"); }],
  ["console output is sanitized", () => { const output = runEventAnalyzerConsole(candleConsoleArgs(), () => rawSeries(["100000.00", "100100.00", "100220.00", "100360.00", "100530.00"], ["100", "105", "110", "120", "160"])); assertTrue(!output.includes("apiKey") && !output.includes("providerPayload"), "sanitized"); }],
  ["public engine exposes no network AI persistence or execution methods", () => { assertDeepEqual(Object.getOwnPropertyNames(EventAnalyzerEngine.prototype).sort(), ["analyze", "constructor"], "methods"); const output = JSON.stringify(engine.analyze(candleInput())); for (const forbidden of ["apiKey", "http", "executeTrade", "positionSize", "persist", "providerPayload"]) assertTrue(!output.includes(forbidden), `${forbidden} absent`); }],
];

function consoleArgs(): string[] { return ["--event-id=event:btc-15m:20260721-1445", "--observation-time=2026-07-21T14:36:00.000Z", "--current-price-source-id=source:owner-fixture", "--current-price-source-record-id=source-record:btc:20260721-1436", "--current-price-observation-id=observation:btc:20260721-1436", "--target-price=100000", "--current-price=101000", "--remaining-seconds=450", "--contract-side=UP", "--market-price=0.5000", "--momentum=UP"]; }
function candleConsoleArgs(): string[] { return ["--event-id=event:btc-15m:20260721-1445", "--observation-time=2026-07-21T14:36:00.000Z", "--current-price-source-id=source:owner-fixture", "--current-price-source-record-id=source-record:btc:20260721-1436", "--current-price-observation-id=observation:btc:20260721-1436", "--target-price=100000", "--current-price=100530", "--remaining-seconds=450", "--contract-side=UP", "--market-price=0.5000", "--candles-file=fixture.json"]; }

function main(): void { let passed = 0; for (const [name, run] of tests) { try { run(); passed += 1; console.log(`PASS ${name}`); } catch (error: unknown) { console.error(`FAIL ${name}`); throw error; } } console.log(`Event Analyzer tests passed: ${String(passed)}/${String(tests.length)}.`); }
main();
